### ISSUE TITLE
Caching pygments

### ISSUE THREAD

**Issue by rubenv** [spf13/hugo#1000]
Would it be a good idea to cache multiple runs of `pygmentize`?

You could take the checksum of the input code, see if there's a file with that name and return it. If not: run `pygmentize` and write a cache file.

This would make livereload lightning fast again for those who use pygments.

* Is this something that would be accepted (I'll happily submit a patch)?
* Can I dump the cache files into `CacheDir`? Any specific naming pattern to follow?

**Comment by bep** [comment]
* That is a splendid idea.
* A PR would be welcome.
* `CacheDir` or a subdir of that would be good place, yes. I would try to find a pattern in the 1 place we cache today. We should also try to generalize the cache logic where it make sense.

**Comment by bep** [comment]
It MAY be an idea to do this on the shortcode level, and maybe turn it on/off per shortcode / all shortcodes.

The key could be calculated from the param key/vals + the inner content (if applicable).

**Comment by rubenv** [comment]
> The key could be calculated from the param key/vals + the inner content (if applicable).

Plus the shortcode definition and any other shortcodes it might call. This might be a can of worms, if you don't mind I'd like to start with the low-hanging fruit of just making pygments fast.

Most shortcodes are simple and fast anyway, so there won't be much (noticeable) gain.
