### ISSUE TITLE
Add instructions on installing from source on a Windows computer

### ISSUE THREAD

**Issue by mdhender** [spf13/hugo#1007]
Expand tutorials to add installing on Windows.

**Comment by anthonyfok** [comment]
Thank you @mdhender!  Awesome tutorial!

Committed as 06d704f243ae01b32f53d9eb947379da255a894c for `master`, and fd219610851e3b6ab6485c870d0ca109c733dd26 for `v0.13.docs`.
Should be live on http://gohugo.io/ in a few minutes.
