### ISSUE TITLE
Add command to dump template variables

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1009]
See http://discuss.gohugo.io/t/the-never-ending-confusion-over-variables/804/10

* Not sure on what level this should be performed, site, page?
* Reflection should be able to read out the exported fields and funcs in a template context

**Comment by mdhender** [comment]
I thought that we could write a for loop in the template to iterate through all the values in `.` and dump the values as needed. I added two functions in PR #1026 to help:
1. "inspect" is similar to `printf "%#v"`.
2. "typeOf" returns the type of a variable or value.

**Comment by mdhender** [comment]
Future thoughts - given how fast Hugo is, would it be possible to have a template hiding on the back end that did a pretty print of the current environment and passed that through CSS to float a window that displayed the results in a navigable hierarchy?

**Comment by bep** [comment]
Yes - that's a good idea ... but since the current context is perg page/node, it should be some kind of DebugWrapper around each html file.
