### ISSUE TITLE
Shortcodes in table of contents (ToC) doesn't work

### ISSUE THREAD

**Issue by peczony** [spf13/hugo#1010]
I have a shortcode which generates small caps from lowercase letters. Everything is OK except for when I use the shortcode in a section name (no, I don't want _all_ section names to come in small caps, only an abbreviation in one of the sections)

Then I have the table of contents on top of the text.

There, I expect to see small caps, like in ordinary running text. Instead I see things like `{@{@HUGOSHORTCODE-19@}@}`.

**Comment by bep** [comment]
* This in a markdown file (md), right?
* What exactly do you mean by "section name"? Can you post an example of where you call this shortcode?

**Comment by peczony** [comment]
1. Yes.
2. `### A section name with an {{< sc "abb" >}} inside it {#anchor}`

**Comment by peczony** [comment]
Oh shit, excuse me. In the section name in the text everything is okay, the `{@{@HUGOSHORTCODE-19@}@}` is displayed in the **table of contents**

**Comment by bep** [comment]
OK, then I understand.

**Comment by markdchurchill** [comment]
Hiya, it looks like this has resurfaced in 0.23 and is still in 0.26. Now seeing "HAHAHUGOSHORTCODE-4HBHB" throughout my TOC, for usages like:
`#### {{<icon database>}} Data`

**Comment by moorereason** [comment]
@markdchurchill, please don't comment on issues that were closed 2 years ago.  Open a new issue.

**Comment by Sharon-iguazio** [comment]
I'm seeing the same issue with v0.29 of Hugo: if a heading contains a shortcode call, it translates to `HAHAHUGOSHORTCODE-2` in the page TOC ("mini TOC"). I couldn't find an open bug for this.
-->
@bep  is this a known issue with the latest version / is there an open bug for this? 10x.

**Comment by plinss** [comment]
Using the `{{% %}}` syntax for the shortcodes fixes this (in Hugo 0.55+), see: https://github.com/gohugoio/hugo/issues/6081#issuecomment-554601922
