### ISSUE TITLE
inotify_init: too many open files

### ISSUE THREAD

**Issue by Greg-Boggs** [spf13/hugo#1011]
I get this error message from watch and Google hasn't been much help.

Hugo Static Site Generator v0.13 BuildDate: 2015-02-21T20:02:30-08:00

    hugo server --watch 

    Watching for changes in /var/www/hugo/content
    inotify_init: too many open files
    inotify_init: too many open files
    Serving pages from /var/www/hugo/public

and hugo --watch

    inotify_init: too many open files
    CRITICAL: 2015/03/29 inotify_init: too many open files

**Comment by bep** [comment]
Probably related to #168

**Comment by Greg-Boggs** [comment]
Yes thank you bep, this fixes it.

    ulimit -n 10480
