### ISSUE TITLE
Implement mousetrap to prevent cmd prompt from closing for windows users that click exe

### ISSUE THREAD

**Issue by neff** [spf13/hugo#1022]
In being relatively new to things, I had double clicked on the executable expecting it to open an installer and instead I saw a brief flash of the command window and I was the left staring at my desktop. I had remember seeing [a blog post](https://inconshreveable.com/09-09-2014/sweat-the-small-stuff/) a while ago about a method that would allow the command window to stay open and provide basic instructions to the user.

Implementing [mousetrap](https://github.com/inconshreveable/mousetrap) would help improve the user experience for non-technically minded windows users. I'm guessing since both projects are based in go that the addition *should* be trivial, but that is me just making an assumption. I would try to add the functionality myself, but I feel like I am staring at a mountain of unknown.

Hopefully this is something that would be useful to others...

**Comment by bep** [comment]
@spf13 I have looked at the moustrap library and the code looks clean and simple. This is a nice way to solve a very common problem for Windows users. This could maybe even be a candidate to put into Cobra.

What do you think?

**Comment by spf13** [comment]
I think this is a great solution and should be added directly to cobra

**Comment by bep** [comment]
OK, I have added a pull request in Cobra. I have tested it in Hugo and it works great.

**Comment by spf13** [comment]
Thanks @bep . I'm sure this will help a lot of people.

**Comment by bep** [comment]
This is now merged in Cobra - I will add a custom text for Hugo, so I'll keep this one open for a little bit.

Thanks for the heads-up @neff -- this is a major issue for some Windows users, and I would probably never noticed this lib.

**Comment by neff** [comment]
No problem @bep. I only ran across it because of a gap in my knowledge. There are some other snags I'm hitting due to a lack of understanding around the system so I'm sure you'll see me posting over on the community site in the future.
