### ISSUE TITLE
/section/subsection/ leads nowhere

### ISSUE THREAD

**Issue by peczony** [spf13/hugo#1024]
I am unsure if that’s a bug or an intended way of working, so if it’s intended feel free to close the issue.

Suppose inside of my section `blog` I want to have a separate subsection `guest` for posts written by my friends.

As for now, if I do thus with the default permalinks configuration values (as in: _no permalinks section in the config_), guest posts have paths like this: `:baseUrl/blog/guest/:slug`

Which is fine, but when I visit path `:baseUrl/blog/guest`, I expect to see something like `/layouts/_default/list.html`. Instead i see a list of directories in plain html. Seems like a bug.

OK then, suppose it was fixed, now we have another problem.

‘Guest’ posts are included in the default `:baseUrl/blog/` list with _no indication whatsoever_ that they belong to a subcategory. A site visitor who sees the page can only infer a subcategory this if he clicks on the title _and notices the url change_.

As far as I can imagine, if one creates a subfolder in one’s section folder, one __either__ wants content items in the corresponding subsection to _NOT be included at all_ in the `:baseUrl/section/` list, and be included instead in `:baseUrl/section/subsection/` list instead, __or__ one wants the subsection items to be included in `:baseUrl/section/` list, but with some indication of a subsection, say a colored badge with the subsection name near post title—else what are subsections even _for_?

If you begin to consider the issue, you should also decide on a way in which `.Paginator` will respond to the changes made. If subsection items are shown on the `:baseUrl/section/` list, there should be a way to count section and subsection items differently. Say all the items in section list are included in `.Paginator.TotalNumberOfElements`, then something like `.Paginator.TotalNumberOfElements.Section` / `.Paginator.TotalNumberOfElements.Subsection` could be introduced in order to have access to the different post counts.

Either way, `:baseUrl/section/subsection/` should lead to some meaningful place and not to the snow desert it leads to now.

**Comment by bep** [comment]
Have you read the documentation? 

http://gohugo.io/content/sections/

As to the "snow desert" -- are you use the built-in file server in Hugo (`hugo server`)?

**Comment by peczony** [comment]
Yes, I did, and I understand that the ‘subsectioning concept’ isn’t, in fact, introduced—but how is all the subdirectories system supposed to work? If the subdirectories do not in fact do anything except create ‘snow deserts’, it is logical to explicitly disallow them to be part of permalinks.

Yes, I used `hugo server`.

**Comment by peczony** [comment]
Also, suppose I wanted to get the behaviour described in the issue (‘subsection as a separate section’) using current methods. Then I would need to create, in fact, a section proper and then adjust the links. So my directory structure would be as follows:
```
content
 - section1
   - post1.md  # intended as section1/post1/
 - section2      # intended as subsection section1/section2
   - post2.md   # intended as section1/section2/post2/
```

It is easy to achive the right permalink for `post2.md` by setting the `section2` permalink in the config to `/section1/section2/:slug/`

Though, the _list_ for `section2` would be still at `section2/`, not at `section1/section2/` (and a snow desert at the latter address)

Am I right that, in current setting, it is impossible to achieve the behaviour described in Hugo?
Thank you.

**Comment by bep** [comment]
The section is defined as the first level from root. No support for sub-sections.

**Comment by dunn** [comment]
Looks like what you're requesting is similar to #465, is that right?
