### ISSUE TITLE
Standardize on "got" in result log for test cases

### ISSUE THREAD

**Issue by mdhender** [spf13/hugo#1028]
Most test cases log errors using lower-case "got":
```
t.Errorf("[%d] got %v but expected %v"...
```
A few use upper-case "Got":
```
t.Errorf("[%d] Got %v but expected %v"...
```
Standardize on a format like "[%d] got X but expected Y".

**Comment by bep** [comment]
This is nit-picking. I'm not sure how important this is ... And this commit does more than it promises, in some cases with wrong result (lower case affter period).

**Comment by mdhender** [comment]
Reopening - Github closed the PR when I deleted the branch from my repo.

**Comment by mdhender** [comment]
This PR contains two commits because I pushed before running `git rebase`. Please let me know if you need me to redo it with a single commit.
