### ISSUE TITLE
Log complete watch list

### ISSUE THREAD

**Issue by dylanmackenzie** [spf13/hugo#1030]
I love using hugo's `-w` option to watch files, but there are times when I'm editing things in `/static/` and would like to see changes reflected immediately. I know I could use something like `gulp-watch`, but could this be integrated into hugo? If this sounds like a good idea, I would be happy to submit a pull request. I was thinking something like: 

`hugo server --watch='static/css' --watch='config.toml'`

or

`hugo server --watch='static/css,config.toml'`

The first depends on the ability of the command line parser to support repeated options, but the second will break if (for some strange reason) a user has a comma in their filename. The `-w` flag would stay a boolean and watch the content directory so the common usage: 

`hugo server -w`

would continue to work as expected. However, I'm open to other ideas.

Thoughts?

**Comment by bep** [comment]
* Static is already on the watchlist (+ data, content, layout)
* livereloading of config.toml isn't supported

And since you will have to add support for each new folder/file, a hardcoded list is the way to go.

**Comment by dylanmackenzie** [comment]
Whoops. I wasn't aware it was watching static. Would it be worth adding something to the docs? The executable just spits out `Watching for changes in $BLOGDIR/blog/content`, hence my confusion.

**Comment by bep** [comment]
Oh, you are right about that one!

We should fix the docs and output.

**Comment by dylanmackenzie** [comment]
Ah. It's in the docs under LiveReload (I was looking at the usage message). I think changing that output message might help simpletons like me though.

**Comment by bep** [comment]
Totally agree.

**Comment by bep** [comment]
Fixed in 99a18b2
