### ISSUE TITLE
Strange BaseUrl behaviour

### ISSUE THREAD

**Issue by bst27** [spf13/hugo#1046]
I think the behaviour regarding the `BaseUrl` parameter is **very** confusing. 

Like described in [issue 170](https://github.com/spf13/hugo/issues/170#issuecomment-32331678) `Hugo has the behavior that if you call it with server, regardless of the baseurl in the config file it will render all links with localhost:1313.`

At least for me this behaviour is absolutely not what I expect. I think there should be no difference between the content hugo generates and the content the built-in server serves. Also it is a very daring default setting, because I have the hugo server running inside a virtual ubuntu machine and I am accessing the content with the virtual machines IP address. So obviously this will not work. Is it not meant to be used this way? Why is the hugo server then listening on 0.0.0.0?

**Comment by bep** [comment]
As this is a file server (mainly) built for live preview I wouldn't call it "daring default setting" ... when that default setting is what 99.99% wants. Very few needs to run a virtual Ubuntu since it runs fine in the main OS.

But a suggestion that would cover both bases is always welcome.

**Comment by bst27** [comment]
My suggestion is to always use the baseurl. If there is no baseurl defined the server still could fallback to its current behaviour.

**Comment by bep** [comment]
You should be able to start it with `hugo server --baseUrl=http://foo.com` or any address you want and it should work.

**Comment by bst27** [comment]
You are right, this solves the problem with the "broken" URLs but not the confusing behaviour. For example I am able to serve with `--theme=html5` which overrides the `theme` defined in my config.toml. Serving with `--baseUrl=http://foo.com` on the other hand does not override my `BaseUrl` defined in my config.toml but a BaseUrl defined somewhere internally because my `BaseUrl` defined is not used. In my opinion this shouldn't work this way.

**Comment by bep** [comment]
This was a design decision before my time -- and as such hard to revert.

I suggest you take this one further at http://discuss.gohugo.io/
