### ISSUE TITLE
404 page has no menus

### ISSUE THREAD

**Issue by martinburger** [spf13/hugo#1048]
It seems that a custom 404 page has no menus. At least the menus are empty and have no children.

**Comment by bep** [comment]
None of my sites has menus with children, but all of them has menus working on the 404 page.

Is your site's source a public Git repo by any chance?

**Comment by martinburger** [comment]
I will make my site publicly available...

**Comment by martinburger** [comment]
You can access the sources at: https://git.martin-burger.net/projects/WEB/repos/private-homepage-hugo/browse

**Comment by martinburger** [comment]
Sorry, false alarm. Works now.

Please close this issue as invalid.
