### ISSUE TITLE
noTimes feature broken for some files

### ISSUE THREAD

**Issue by martinburger** [spf13/hugo#1054]
According to #574 and the documentation, running `hugo --noTimes=false` should cause Hugo to keep the modification time of files copied from `static`. This would avoid superfluous uploads when synchronizing via FTP, for instance.

However, it seems that Hugo applies the original modification time for some files on the second run of `hugo` only. For instance:

```
$ rm -rf public
$ ls -lart@ static/test
-rw-r--r--  1 mburger  staff       0  1 Jan  2014 somefile
-rw-r--r--  1 mburger  staff       0  3 Apr 18:53 someotherfile
-rw-r-----  1 mburger  staff  295061  3 Apr 18:53 some.pdf
drwxr-xr-x  5 mburger  staff     272  7 Apr 07:07 ..
drwxr-xr-x  2 mburger  staff     170  7 Apr 07:17 .
$ hugo --noTimes=false
[...]
$ ls -lart@ public/test
-rw-r--r--   1 mburger  staff       0  1 Jan  2014 somefile
-rw-r--r--   1 mburger  staff       0  3 Apr 18:53 someotherfile
drwxr-xr-x   2 mburger  staff     170  7 Apr 07:17 .
-rw-r-----   1 mburger  staff  295061  7 Apr 19:45 some.pdf
drwxr-xr-x  11 mburger  staff     612  7 Apr 19:45 ..
$ hugo --noTimes=false
[...]
$ ls -lart@ public/test
-rw-r--r--   1 mburger  staff       0  1 Jan  2014 somefile
-rw-r--r--   1 mburger  staff       0  3 Apr 18:53 someotherfile
-rw-r-----   1 mburger  staff  295061  3 Apr 18:53 some.pdf
drwxr-xr-x  11 mburger  staff     612  7 Apr 07:07 ..
drwxr-xr-x   2 mburger  staff     170  7 Apr 07:17 .
```

As you can see, file `some.pdf` gets the original modification time on the second run only.

Interestingly enough, running `hugo --noTimes=true` causes exactly the same behavior.

Note that I am running Hugo 0.13 installed via Homebrew on OS X Yosemite 10.10.2.

**Comment by martinburger** [comment]
I just saw that command line argument `noTimes` is referred as `notimes`:

`syncer.NoTimes = viper.GetBool("notimes")`

Source: https://github.com/spf13/hugo/blob/master/commands/hugo.go#L281

Maybe that typo, if any, in use of capital and small letters causes this issue?

**Comment by bep** [comment]
No, viper isn't case sensitive.

**Comment by martinburger** [comment]
I just opened issue mostafah/fsync#4 as this issue here might be caused by that library.

**Comment by martinburger** [comment]
Hugo uses package [spf13/fsync](https://github.com/spf13/fsync) (see: [hugo.go#L29](https://github.com/spf13/hugo/blob/bebb1b9d5dfc629ec73c4d3dbdb71ac15400ff3a/commands/hugo.go#L29)) which was forked from `mostafah/fsync`.

In that fork, support for "Afero - A FileSystem Abstraction System for Go" was added in commit [1fdf08f](https://github.com/spf13/fsync/commit/1fdf08f822b05e59a6515ee151b683c3a02efea5). As far as I understand that change, one might have forgotten to adapt feature ["update dst's modification time"](https://github.com/spf13/fsync/blob/master/fsync.go#L213) which implements preservation of file modification time.

While many (well, almost all) calls to `os`-interfaces have been replaced by calls to alternative interfaces provided by Afero, in that very line that replacement has not been followed through. I think it is very likely that this is related to this issue.

I would have opened an issue in `spf13/fsync`; however, issues seems to be unavailable in that project.

**Comment by bep** [comment]
@martinburger Thanks for your detective work.

 @spf13 not sure what's the reasoning behind the fork? Keep it or do some merging?

**Comment by spf13** [comment]
The only reason for the fork is to add support for afero which was experimental so I didn't want to contribute it back to the main fsync project yet. It's also a big change for them to be dependent on a new project. 

I think we should update spf13's fork to include the latest commits to the upstream one and reach out to see if we can't combine efforts. I think afero is pretty stable and well tested at this point.

**Comment by bep** [comment]
@martinburger sorry for this late response. I have looked at the code and the arero correctly delegates to `os.Stat`, so it should work ...

I will test this myself on LInux (I use content hashing to synch changes), but I suspect this must be an OS issue of some kind.

**Comment by martinburger** [comment]
Just tell me if I could help debug somehow.

Am 24. April 2015 03:04:35 MESZ, schrieb "Bjørn Erik Pedersen" <notifications@github.com>:

**Comment by anthonyfok** [comment]
Hi @martinburger,

Thank you for reporting this issue.  I think we have found the problem and solved it.  Please read mostafah/fsync#5 for the discussion, and mostafah/fsync@42330bf for the fix.  :-)

As you may have noticed, the `some.pdf` in your example had a special permission of 0640 rather than the usual 0644 for `umask 0022`.  So, in the first run, when `some.pdf` was first copied from `static/` to `public/` for the first time, fsync had to do the extra work to change the permission bits of `public/some.pdf`, but then the code promptly `return` before it has chance to set the modification time.  In the second run, since the file permissions were already identical, it did not fall into the `return` trap and finally reached the code to sync modification time.

The `return` had been there since September 2012 when the code only sync'ed permissions, and it was perfectly fine to be there, whereas "sync-mtime-too" was a new feature added in October 2014, so it must have been too easy to miss that innocuous `return`.

Once recent mostafah/fsync fixes are merged into spf13/fsync (see spf13/fsync#2), please test `hugo --noTimes=false` again to make sure it works for you too.  Thanks in advance!

**Comment by anthonyfok** [comment]
Hi @martinburger,

spf13 is quick!  Before I knew it, spf13 has already merged the fix!  (Thanks spf13!)

So, when you have time, please verify if this fixes your problem!  Many thanks!

**Comment by martinburger** [comment]
I just tried to reproduce this bug with above test case and v0.15. Fortunately, without success. :-)

Furthermore, when I deploy my site via ftp, only files that have been actually changed are synchronized to the server, while other unchanged files - like static PDF files - do not cause superfluous uploads anymore. This saves a lot of time. Thanks!

Thus, I close this issue as resolved / fixed.
