### ISSUE TITLE
canonifyurls should append baseurl to items in srcset

### ISSUE THREAD

**Issue by rhewitt22** [spf13/hugo#1059]
To support responsive images it'd be great if the `canonifyurls` parameter in the configuration file could also append the baseurl to each of the image sources in srcset.  This could be tough if you have to parse srcset as a long string, but would be a great addition.

Current output:
![2015-04-15_1002](https://cloud.githubusercontent.com/assets/3673374/7160383/b42636f6-e356-11e4-8833-a19a9d9e4937.png)

**Comment by bep** [comment]
It should be doable.

See 
* http://www.w3.org/html/wg/drafts/html/master/semantics.html#attr-img-srcset
* https://github.com/spf13/hugo/blob/master/transform/absurlreplacer.go

**Comment by bep** [comment]
@rhewitt22 I have admittedly tested this mostly regarding non-srcset sources (it was vital that I could do this without losing speed ...), but it passes all the tests I could come up with. Shout if any trouble!
