### ISSUE TITLE
Document Amber templates

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1064]

**Comment by scottcwilson** [comment]
I'm not seeing these in https://github.com/spf13/hugoThemes/ but if you give me a pointer, I'd be happy to do this.

**Comment by bep** [comment]
I guess I need the documentation as much as the common man. It was added by someone, do not remember who. I guess a little code digging would be needed.

But something in the line of the doc for the Ace templates:

http://gohugo.io/templates/ace/

* What is the suffix for the templates
* An external link to template doc

**Comment by scottcwilson** [comment]
I'm not positive this works.  I can create (for example), `themes/MY_THEME/layouts/_default/single.ace`  (after deleting `single.html`) with "hello world" and it works like a charm, but when I create single.amber with the same content and run hugo, my single pages are all empty.

**Comment by bep** [comment]
I haven't looked into Amber syntax, but I do not expect it to be the same as Ace. A wrong template may yield an empty rendred page (not ideal, but I guess it could).

If you find a Amber template out there that you know is valid and test with that.

**Comment by scottcwilson** [comment]
I searched Github for Amber templates for Hugo and didn't find any.  You are correct, the syntax is quite different but I would expect to be able to create a page that just says "Hello World" with no markup and have that work. 

We may need to wait for an Amber expert to create a template.  If I had a working template, I am sure I could reverse engineer it and write the documentation.

**Comment by bep** [comment]
Here are some:

https://github.com/eknkc/amber

**Comment by scottcwilson** [comment]
That's the Amber project.  I mean a working Hugo template that was created from Amber.

**Comment by bep** [comment]
There was a flaw in the Amber logic, see e3ea4b48a274770d8a45fe7c1dbbce2340ec4e2d

I have tested OK with this simple template:

https://github.com/eknkc/amber/blob/master/samples/basic.amber

I notice that we have some work to do to get inheritance support up and running. But that is out of scope for this task.

**Comment by scottcwilson** [comment]
Thank you so much!  I also added a comment to that PR.  
I will start working on the docs again.

**Comment by tatsushid** [comment]
As I wrote http://discuss.gohugo.io/t/amber-templates-not-working-documentation/129, Amber template doesn't allow to call `FuncMap` function yet. Sorry, I forgot sending PR to Amber. I'll do it later.

**Comment by scottcwilson** [comment]
Thank you @tatsushid.

**Comment by tatsushid** [comment]
I sent PR to Amber https://github.com/eknkc/amber/pull/36 to support `FuncMap` functions and struct's method calls

**Comment by scottcwilson** [comment]
Quick update: thanks to @bep's fix, the following will work: 

`import ../partials/test.html`

`import ../partials/test_a.amber`

however, this does *not* work: 

`{{ partial "test" . }} `

It just renders as if it was regular text.  So does normal Go syntax not work with Amber?  Is this expected?

**Comment by tatsushid** [comment]
Amber has its own syntax and doesn't allow to use original Go template syntax in it. So, please read https://github.com/eknkc/amber and try. I recommend writing a very simple theme in normal Go template syntax first and converting it into Amber one by one. That's the way I did when I added Ace template syntax to Hugo
