### ISSUE TITLE
Pagination generates useless "page1"

### ISSUE THREAD

**Issue by drguildo** [spf13/hugo#1066]
Please see https://github.com/zyro/hyde-x/issues/22.

I don't understand enough about how Hugo works to be able to point out what exactly causes it but something about how pagination works seems to result in useless pages being generated.

**Comment by bep** [comment]
This is by design

* It's not useless - it's an alias and very handy when doing some integration with some "infinitive scroll" lib
* and it makes everything symmetrical and nice

**Comment by drguildo** [comment]
If it's not useless then why is it referenced from nowhere else on the generated site and why does it just redirect to the main page?

**Comment by bep** [comment]
* as I said, used when integrating with "infinite scroll" libs etc.
* the main page IS PAGE 1, it would be plain wrong to redirect to anything else.
