### ISSUE TITLE
Hugo QuickStart throws Incomplete Template Error

### ISSUE THREAD

**Issue by Joholland** [spf13/hugo#1067]
Following the quickstart guide:

    hugo new site /path/to/site
    cd /path/to/site
    hugo new about.md
    cd content/
    vim about.md/
    cd ..
    git clone --recursive https://github.com/spf13/hugoThemes themes
    hugo server --theme=hyde --buildDrafts
    ERROR: 2015/04/21 Rendering error: html/template: "theme/_default/single.html" is an incomplete template

Seems to throw this error regardless of the theme chosen.

Is there a breaking change in Hugo that causes the themes to be out of date?

**Comment by bep** [comment]
Works for me.

Any more info to add?

- Hugo version
- OS (Windows?)
- any other errors?

**Comment by Joholland** [comment]
$ hugo version
     Hugo Static Site Generator v0.11

Installed via Brew (OS X).

**Comment by bep** [comment]
Oh, that explains it. v0.11 is rather old.

The current release is v.0.13. A lot of cool stuff is added.

**Comment by Joholland** [comment]
Ah, so the current Brew package is out of date then.

**Comment by bep** [comment]
I'm not an OS X expert ... but I have read that should be up to date, both for release and the dev version.

Others will chime in, I'm sure.

**Comment by Joholland** [comment]
After removing hugo, doing a brew update and reinstalling, I now have 0.13 installed.  Looks like things are fixed now.
