### ISSUE TITLE
Readme.md in /data

### ISSUE THREAD

**Issue by Joholland** [spf13/hugo#1068]
Is it possible to have a .hugoignore file? It currently tries to parse a readme.md file at the root of my repo that I'm using for GitHub and fails.

**Comment by Joholland** [comment]
Just realized what is actually going on.

I have a /data linked as a git submodule to another repo that holds external .yaml files. The fact that there is a readme.me in that repository is actually what is breaking hugo, it doesn't like .md files under /data

**Comment by bep** [comment]
That could be fixed. Thanks for the report.
