### ISSUE TITLE
Config variable «watch» in config.yaml doesn't work

### ISSUE THREAD

**Issue by soulchainer** [spf13/hugo#1074]
I has this in my config.yaml:

```
# watch filesystem for changes and recreate as needed
watch: true
```
According to [Configuring Hugo](http://gohugo.io/overview/configuration/) documentation.
But, it didn't seem to work. I still need to use options `-w` or `-watch` in command line to watching files to work.

After commenting this in a [a forum thread](http://discuss.gohugo.io/t/watch-configuration-variable-doesnt-work/1092), I realized that maybe (and only maybe), considering that the documentation only says that:

```
# watch filesystem for changes and recreate as needed
watch:                      false
```

it's aimed for people that deploys their site with the hugo's built-in server (instead of nginx, apache...), and it's intended to **only** being set to `false`, **never** to `true`, just to deactivate the watch in production.

If that's the case, I think that the comment in that documentation:

```
# watch filesystem for changes and recreate as needed
```

Should be changed for something clearer, because now it'ss pretty confuse. Someone (that's me!) can guess that, if you set it to `true`, it will watch for changes without the need of explicitly using `-w` or `-watch` option in commandline.

Something like:

```
# disable watch of filesystem for changes (handy for production environments)
```

would be much clearer.

Just in case it is in fact a bug (and it should work also for activate `watch`):
I'm using archlinux and `hugo version`

>Hugo Static Site Generator v0.13 BuildDate: 2015-04-20T21:17:06+02:00

(installed from AUR package, [hugo](https://aur.archlinux.org/packages/hugo/)).

**Comment by aldendaniels** [comment]
Just ran into this as well - quite confusing
