### ISSUE TITLE
livereload does not work for me

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [spf13/hugo#1081]
Hi, 

I am running `hugo server -w` and when I change files, any file, the browser does not reload automatically. 

In order for the page to refresh, I found I need to add `<script src="/livereload.js"></script>` to the page. but then I get 404 in production because livereload.js does not exist.. 
I am doing something wrong, but cannot understand what.

**Comment by guy-mograbi-at-gigaspaces** [comment]
It seems it is my fault. Whoever is searching for this topic, I found the solution in hugo discussions : http://discuss.gohugo.io/t/livereload-only-works-on-the-homepage/1006/5

It seems I did not have a proper html/body on my pages. 

Once I took care of that, it was fine.

**Comment by bep** [comment]
@anthonyfok maybe a note in the "tips and tricks section?"

**Comment by anthonyfok** [comment]
Thanks for the heads-up, @bep!
