### ISSUE TITLE
Variables in theme.toml file vs config.toml

### ISSUE THREAD

**Issue by zhe** [spf13/hugo#1082]
Hi everybody,

I'm currently make a theme for Hugo. I want to access some custom variables in the template, the way to do that is to write those variables in `params` in `config.toml` file rather that in `theme.toml` file. The scenario for sharing a theme is to download a theme into the `themes` folder and enable it by `hugo -t themename` or add it in `config.toml`. How about those custom variables with the theme? Do we need to add thoese into the `config.toml` file too? OR just modify the values inside the `theme.toml` file.

I saw several `theme.toml` samples from existing themes. For example, some writes:

```
auther = "John Doe"
source_repo = "http://..."
```
some other writes:

```
[author]
    name = "John Doe"
    homepage = "http://..."
```

It would be better to access the variables inside the `theme.toml` file in the template files, after all some custom variables are bundled with their particular theme.

**Comment by bep** [comment]
`theme.toml` is currently only used for building the Hugo themes site (which isn't up and running) ... but maybe its use should be expanded.

**Comment by zhe** [comment]
thanks @bep! I see now. 

Another questions is when the `Params` variable's value is changed, the page won't livereload to reflect the changes. Is that because the `config.toml` is loaded once when run `hugo server -w`? For now we need to `Ctrl+C` stop the server, and run it again..

**Comment by bep** [comment]
Yes - config.toml isn't `watched`. Adding it to watch *would be* possible, I guess -- but harder than to be worth it, me thinks. If you want params/data that is livereloaded, put it in toml/yaml/json files in `/data`.
