### ISSUE TITLE
brew installer not picking up .13

### ISSUE THREAD

**Issue by moxiegirl** [spf13/hugo#1083]
I installed Hugo originally with brew.  Couldn't upgrade through brew and uninstalling didn't pick up .13

```
mary at meepers in ~
$ brew upgrade hugo
Error: hugo 0.12 already installed

mary at meepers in ~
$ brew uninstall hugo
Uninstalling /usr/local/Cellar/hugo/0.12...

mary at meepers in ~
$ brew install hugo
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/hugo-0.12.yosemite.bottle.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/hugo-0.12.yosemite.bottle.1.tar.gz
==> Pouring hugo-0.12.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/hugo/0.12: 5 files, 26M
```

**Comment by bep** [comment]
I feel these brew issues belong at ... brew?

**Comment by moxiegirl** [comment]
Well, Hugo's doc says installing with Brew is an option;that option isn't working so maybe it is docs issue.

I believe the project needs to do something on their end to get brew to work.

**Comment by bep** [comment]
The thing is, "the project" is just a few persons spending some of their spare time doing open source work. 

Brew problems is a recurring issue here, maybe we should remove it from the documentation.

**Comment by moxiegirl** [comment]
Steve's choice of course.  I just added the issue as a courtesy to let the project know.

**Comment by bep** [comment]
Replaced by #1084

I know others got this working: Post a question at http://discuss.gohugo.io/
