### ISSUE TITLE
Hugo / Go Template range based on conditonal 

### ISSUE THREAD

**Issue by simplyeffectiveweb** [spf13/hugo#1086]
I'm struggling with doing what I thought would be really simple in a Hugo template. So, as is the case with me, I want to now do two things. 

1) fix my own issue
2) put a proposal to the Go and / or Hugo folks to make this more intuitive

I want to do the following: 

_{{ range $count, $element := .Site.Taxonomies.groups.[conditionalgroup].Pages }}_

where [conditionalgroup] is an existing group name based on some condition at the point of rendering the template.

In javascript this could be something like:

_{{ range $count, $element := .Site.Taxonomies.groups.groupvar.Pages }}_

(where groupvar is a variable storing the group based on the condition)

in PHP this could be something like:

_{{ range $count, $element := $groupvar }}_

(where $groupvar contains the value of .Site.Taxonomies.groups.[conditiongroup].Pages based on the condition) 

In Hugo, I've tried:

_{{ range $count, $element := $groupvar }}_

and

_{{if eq ......... }}_

    _{{ range $count, $element := .Site.Taxonomies.groups.groupone.Pages }}_

_{{ else }}

    _{{ range $count, $element := .Site.Taxonomies.groups.grouptwo.Pages }}_

_{{ end }}_

but it seems nothing like these works with Go logic. I appreciate I'm missing the basics, so I have a lot to learn. But logic is logic..... Are Go fighting it?

I also want to put a proposal to Hugo / Go relating to current standards and intuition, as without this I don't see Go's popularity increasing. PHP became the web standard not because it was a great language (most people see Python and Pearl as more efficient) but it is very intuitive.

**Comment by bep** [comment]
It's not in Hugo's scope to work on Go's template engine (we could suggest improvements, anyone can: see https://github.com/golang/go/issues ).

You you present your problem a little bit too fragmented to understand it. It may be an issue with Go's scopes.

Post a more complete example at http://discuss.gohugo.io/ -- much better place for questions/discussions.

**Comment by simplyeffectiveweb** [comment]
Fair enough, but for the development and growth of Hugo I do not recommend closing such threads. It is a Hugo issue, in as much as I think Hugo is helped by being a repository of Go solutions directly related to the use of Go for static sites. 

The {{ range ... }} command is documented on Hugo's site. What I have found is an issue many js / php developers using Hugo may also find. If it's not an issue, it is my lack of Go / Hugo knowledge. Either way I'm going to find a fix and post it here because I think Hugo needs this type of interaction.

This is especially clear given the lack of clarity with Go, Go templates and Hugo (what I mean here is, clearly the people behind Hugo have done an amazing job and are experts in their field, but explaining how it works to others is not the strong point).

Joomla is a good example. Look at their forums and loads of issues are PHP related. It helps the project to keep the relevant ones there.

**Comment by bep** [comment]
Fair enough,

Hugo's active contributors are few in persons, so to cope with the support we have to set some lines. We have a discussion site for the above, that's my current line.
