### ISSUE TITLE
Could not create a hostable output directory

### ISSUE THREAD

**Issue by orsenthil** [spf13/hugo#1094]
hugo server worked fine to render my content. But no way, I could create a output directory which I can copy to github pages and point to html file.

What is correct way to create a bundlable/ hostable output directory of my html/css files?

**Comment by dunn** [comment]
For publishing a site, you want to run something like `hugo -d [output-directory]`, but maybe I'm not sure what you're asking.

**Comment by bep** [comment]
@dunn is right.

**Comment by orsenthil** [comment]
I checked out all the themes and I tried the theme mentioned in the docs.

```
$ hugo -t hyde

ERROR: 2015/05/01 Site's .BaseUrl is deprecated and will be removed in Hugo 0.15. Use .BaseURL instead.
```

After fixing that. 

When I did

```
hugo  server
```

Was able to see the static site.

But
```
hugo -t hyde -d output
cd output
open index.html
``` 
had just the contents, no css linked.

**Comment by bep** [comment]
Try http://discuss.gohugo.io/ for questions/troubleshooting.
