### ISSUE TITLE
Error: Paginator is not a field of struct type *hugolib.Node

### ISSUE THREAD

**Issue by zhe** [spf13/hugo#1096]
I couldn't get pagination working... When adding basic pagination to the `index.html` template, there is this error message at terminal:

```
ERROR: 2015/05/01 Error while rendering homepage: template: theme/index.html:13:25: executing "theme/index.html" at <.Paginator.Pages>: Paginator is not a field of struct type *hugolib.Node
```

I just put the simplest code to the `index.html` template:

```
{{ range .Paginator.Pages }}
   {{ .Title }}
{{ end }}
```

Where does it go wrong??

**Comment by bep** [comment]
Check the output of

`hugo version`

My guess that will give you a hint. Paginator was introduced in 0.13.

**Comment by zhe** [comment]
The version is 0.13-DEV.
```
Hugo Static Site Generator v0.13-DEV buildDate: 2015-01-16T16:28:45+08:00
```

**Comment by zhe** [comment]
I want to `brew upgrade hugo`, and found out the Hugo version is still 0.12..

```
brew upgrade hugo
Error: hugo 0.12 already installed
```

What I did is `brew uninstall hugo`, then `brew install hugo` again. It worked! Now

```
Hugo Static Site Generator v0.14-DEV BuildDate: 2015-05-01T11:56:46-04:00
```

Thanks! @bep

**Comment by dunn** [comment]
Oh yeah, the Homebrew formula wasn't working correctly until recently; it would install the work-in-progress 0.13-DEV instead of 0.12.

After `brew install hugo` you should get 'v0.13', though, not 'v0.14-DEV'.  Did you install the HEAD rather than the stable version?

**Comment by bep** [comment]
I'm on Linux, but I'm starting to hate brew by proxy  :)

**Comment by dunn** [comment]
Haha, for my part I blame the fiddly Go build process!
