### ISSUE TITLE
Web server listens on all interfaces and says it's on localhost

### ISSUE THREAD

**Issue by hut8** [spf13/hugo#1097]
`hugo server -w` outputs, inter alia:

```
Web Server is available at http://localhost:1313/
```

In fact, it's actually listening on all interfaces. Really there should be an option/flag to pick an interface (which I don't see right now), or at least display the fact that it's actually open to the rest of the internet.

**Comment by bep** [comment]
@spf13 we should fix this. Not sure what's easiest. Default to 127.0.0.1 and add a host flag?

**Comment by hut8** [comment]
@bep I think that's prudent. I'll submit a PR since it's trivial.

**Comment by hut8** [comment]
Note to self: when it says it's listening on 127.0.0.1, it does in fact set the base URL to that, which is why all the absolute references (like the css) were breaking for me (I'm developing on my VPS)
