### ISSUE TITLE
Error calling apply, too many arguments

### ISSUE THREAD

**Issue by RickCogley** [spf13/hugo#1098]
With ~ % hugo version:

    Hugo Static Site Generator v0.14-DEV BuildDate: 2015-05-02T08:58:57+09:00

... and with a single.html loading a partial to list my tags, delimiting so there's no trailing comma, as [in the documents](http://gohugo.io/templates/functions/): 

    {{ delimit (apply (apply (sort .) "partial" "post/tag/link" ".") "chomp" ".") ", " }}

I am getting this error when I run hugo server: 

    ERROR: 2015/05/02 template: partials/post/tag/list.html:4:20: executing "partials/post/tag/list.html" at <apply (sort .) "part...>: error calling apply: Too many arguments in partials/post/tag/list.html

The result is that the tags list is not rendered in my single.html. 

Is this code no longer valid in 0.14?

**Comment by bep** [comment]
Sorry - my bad ... I added some validation after some panics reported by go-fuzz ... But made a mistake.

Sorry abut that!

**Comment by RickCogley** [comment]
Glad to know it's an obvious one, rather than something really hard to debug. :-)
Thanks, @bep

**Comment by RickCogley** [comment]
@bep forgive me for asking what's probably an obvious question: I installed hugo on my mac using ``brew install hugo --HEAD`` to grab the latest code. Related to this sort of fix, which you just made I think, when can I recompile to reinstall hugo? Is it an immediate thing, or, do I need to wait for some tests to pass?

**Comment by bep** [comment]
No need to wait.

**Comment by RickCogley** [comment]
Thanks @bep for the fast fix and kind help. I just noticed that there's a "build passing" or "build waiting" button on the repo, which if you click, shows you what test are being run. That's really slick.

**Comment by RickCogley** [comment]
@bep confirm it works now, thanks again!
