### ISSUE TITLE
hugo server: read settings from config

### ISSUE THREAD

**Issue by jerryjacobs** [spf13/hugo#1101]
It would be nice to autoload the available settings from the configuration file.
E.g config.toml: baseurl = "http://spf13.org/" -> fills in the --baseUrl="http://spf13.org"

Now you need to specify it by hand.

The server is also not configurable on which port it listens.

**Comment by bep** [comment]
See `hugo server -h` and you will find the flag `-p` or `--port`

As to baseUrl, think of the value in config.toml as the published value.

The value used for `hugo server` is:

1) `--baseUrl` or if not set
2) `localhost`

This has been discussed many times before, and will most likely not change.

**Comment by jerryjacobs** [comment]
Okay, agreed. Thanks !
