### ISSUE TITLE
CDATA literally included

### ISSUE THREAD

**Issue by Dieterbe** [spf13/hugo#1103]
if a post like foo.md contains <![CDATA[ and ]]> markers, they are literally included as if they are part of the content.

in html, you can use CDATA to mean "literal data" without having to encode entities etc. i use this liberally for code in html (which needs syntax highlighting). the markers themselves however should not be rendered.
if markdown supports html then it should probably also support CDATA markers.

**Comment by soulchainer** [comment]
@Dieterbe I think this is an issue of [blackfriday](https://github.com/russross/blackfriday), the markdown processor for Go that Hugo uses (I just processed an example `file.md` with https://github.com/russross/blackfriday-tool and got the same behaviour). You should place the issue in their repo.

**Comment by Dieterbe** [comment]
ok thanks. just did!

**Comment by bep** [comment]
https://github.com/russross/blackfriday/issues/165

**Comment by bep** [comment]
This is fixed in BF.
