### ISSUE TITLE
Add support for URLs relative to context root

### ISSUE THREAD

**Issue by jbenet** [spf13/hugo#1104]
Try as I might, I cannot figure out how to get hugo to stop making urls absolute, and use only relative urls. I've set:

```
canonifyurls = false
```
in `config.toml` and removed the default baseurl directive. (The generated html files **do not** get a `<base>` html tag.) But hugo continues to make all urls absolute:

```
<a href="/post/0-hello-worlds/">(read more)</a>
```

instead of a relative

```
<a href="./post/0-hello-worlds/">(read more)</a>
<a href="./0-hello-worlds/">(read more)</a>
```

If you need motivation (in case you ask "why are you doing this?"): many static website use cases _cannot predict_ what url they will be hosted at, and **MUST** work with _only_ relative urls. For example, a content addressed static host (say, using hash-trees to make the resulting hierarchy content addressed) would place the generated site at `<domain>/<base hash>/`. Obviously, the hugo site could know its hash a priori :)

**Comment by bep** [comment]
I guess the term relative is ... relative.

**Comment by insanity54** [comment]
@jbenet What does your content source look like? I guess I'm confused as to how you're feeding the links into hugo.

I set `canonifyurls = false`, and remove the default baseurl directive in config.toml. 
 
I'm able to get a relative link with this:

```
+++
date = "2015-05-05T07:17:44-07:00"
draft = true
title = "fart"

+++

[carrot rel](./assets/carrot.jpg)
[carrot abs](/assets/carrot.jpg)
```

**Comment by jbenet** [comment]
@insanity54 setting `canonifyurls = false` and without any baseurl directive (how did you remove the default?) i still get generated links to posts like:

```
<a href="/post/0-hello-worlds/">(read more)</a>
```

@insanity54 when you built, how do the links to the first post look in `public/index.html` ?

**Comment by jbenet** [comment]
To clarity, my issue here is not with links i make inside posts, it's with links hugo generates _to_ posts from lists and so on. They are generated absolute, which simply do not work at all with content addressing (content hashing).

**Comment by bep** [comment]
@jbenet what you want isn't currently supported in Hugo. The definition of relative in Hugo is "relative to the domain root", but includes the context-root.

So for site hosted at "http://mydomain.com/site" a relative URL will look like "/site/css/somecss.css".

"css/somecss.css" would be relative to the context-root, but that would only not work when used below "/mysection".

**Comment by insanity54** [comment]
@jbenet when I followed the quickstart guide and did `$ hugo new site .`, it generated a config.toml file:

```
baseurl = "http://yourSiteHere/"
languageCode = "en-us"
title = "My New Hugo Site"
```
I just removed the line with the baseurl directive. (I was guessing that was what you did)

Ah I see what you're saying. Not links insite the post, but the links on the index to the post. In that case, I'm getting the same as you. 

```
    <h1 class="post-title">
      <a href="http://localhost:1313/post/neu/">
        neu
      </a>
    </h1>
```

**Comment by jbenet** [comment]
> @jbenet what you want isn't currently supported in Hugo. The definition of relative in Hugo is "relative to the domain root", but includes the context-root.

Could you explain to me what would be involved in adding support for this? I can see if I can PR. (IMO, lack is brittle)

**Comment by bep** [comment]
* If you set `canonifyurls = false` you shouldn't see any absolute URLs (in my definition of it) if not set explicit in the template.

But to get to where you want, I'm not sure.

URL creation isn't as "in one place" as I would want, but even if it was, your problem is contextual (a page's URL should be different when rendered on the home page, `./section/post` vs `./section/post`). To put it simply, Hugo renders a given page once, then reuses that same content in different contexts. So yo may fix the metadata methods to answer differently, but not the bytes in the rendered page.

At first thought, you would think that you could expand on the mechanism used for `canonifyurls`. If you replace baseurl below with `.` you will in theory get correct top level node.

https://github.com/spf13/hugo/blob/master/transform/absurlreplacer.go#L270

But it will fail further down. 

I may come up with a better idea later.

**Comment by wking** [comment]
The way I've seen this worked around in Jekyll is to [declare the per-page relative URL pointing to the root path][0] (e.g. [`.` from the root directory][1] and [`..` from a subdirectory][2]), and then to use those references when linking a resource (e.g. [here][3]).

I think that's a sound approach, but it would be great if the static generator could automatically calculate the relative path from a given page to the site root.  In Hugo's case, this will depend on the [ugly URLs setting][4].  That should be pretty easy with [`Rel`][5].

[0]: http://stackoverflow.com/a/8304028
[1]: https://github.com/swcarpentry/workshop-template/blob/fa7d55dd2cba7a0086dabb8d570cbe5eefc79530/index.html#L3
[2]: https://github.com/swcarpentry/workshop-template/blame/fa7d55dd2cba7a0086dabb8d570cbe5eefc79530/setup/index.md#L4
[3]: https://github.com/swcarpentry/workshop-template/blob/fa7d55dd2cba7a0086dabb8d570cbe5eefc79530/_includes/header.html#L3
[4]: http://gohugo.io/extras/urls/
[5]: http://golang.org/pkg/path/filepath/#Rel

**Comment by bep** [comment]
Sure, the `Page` knows its _normal_ place in the hierarchy. Adjusting `Page.RelPermalink` would go a long way, but ...

In Hugo it's also possible to use a Page in other sections (mostly on the home page).

**Comment by wking** [comment]
On Thu, May 07, 2015 at 05:01:41AM -0700, Bjørn Erik Pedersen wrote:
> Sure, the `Page` knows its _normal_ place in the
> hierarchy. Adjusting `Page.RelPermalink` would go a long way, but
> ...
> 
> In Hugo it's also possible to use a Page in other sections (mostly
> on the home page).

So you'd have to re-render that Page using it's new context for
constructing relative links.  That doesn't seem too difficult…

**Comment by jbenet** [comment]
Yeah, i think that would work

**Comment by bep** [comment]
Most things are doable, but it's not a one-liner change, either.

**Comment by jbenet** [comment]
Thank you @bep

**Comment by doesntgolf** [comment]
The relative URL-ifier doesn't seem to kick in on the action attribute on form tags.
