### ISSUE TITLE
Forward slash is added to BaseUrl

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1105]
See discussion http://discuss.gohugo.io/t/forward-slashes-in-url/933/12

Not sure when this happened.

Most of the themes use 

{{ .Site.BaseURL }}/mycss.css

And it becomes:

http://mybase.com//mycss.css

Which file servers interpret differently.

@spf13 how to handle this?

**Comment by bep** [comment]
I guess having `BaseURL` as a field was a bad design choice in the first place; it would be better served to be a func that takes the relative URL as an argument.

We could add one and phase out the use of BaseURL ...

`{ {  MakeBaseURL "mycss" }}`

**Comment by bep** [comment]
@anthonyfok could you take a look at my fix for this issue ...

**Comment by ehammond** [comment]
@anthonyfok The fix works for me.
