### ISSUE TITLE
Create absurl template func

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1106]
See #1105

Create a template func that given `baseUrl` variations:

* `http://mybase.com`
* `http://mybase.com/`

{{ absURL "mycss.css" }}

Prints  `http://mybase.com/mycss.css`

And for 

* `http://mybase.com/sub`
* `http://mybase.com/sub/`

Prints  `http://mybase.com/sub/mycss.css`

**Comment by ehammond** [comment]
I just ran into a situation where a server relative URL function would have been nice.

For the above two cases it would return: `/mycss.css` and `/sub/mycss.css`

but I found a workaround at a higher level with host names.

**Comment by bep** [comment]
@ehammond yes, that is a natural "pair companion" for this one -- I'll create an issue for it.
