### ISSUE TITLE
runtime error in windows 8.1 of 64bit

### ISSUE THREAD

**Issue by benshen** [spf13/hugo#1108]
D:\benshen.lee\hugo-blog\benshen.lee>hugo
panic: runtime error: invalid memory address or nil pointer dereference [recover
ed]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x480b72]

goroutine 1 [running]:
text/template.errRecover(0xc0821553d0)
        /usr/local/Cellar/go/1.4/libexec/src/text/template/exec.go:100 +0xc3
github.com/spf13/hugo/hugolib.(*pager).Pages(0x0, 0x0, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/pagination.go:55 +
0x22
reflect.Value.call(0xa3e5e0, 0xc0821cb938, 0x1353, 0xa6f750, 0x4, 0xdacaa0, 0x0,
 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.4/libexec/src/reflect/value.go:419 +0x10ec
reflect.Value.Call(0xa3e5e0, 0xc0821cb938, 0x1353, 0xdacaa0, 0x0, 0x0, 0x0, 0x0,
 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/reflect/value.go:296 +0xc3
text/template.(*state).evalCall(0xc0821b60c0, 0xa3ca60, 0xc0821b01e0, 0x16, 0xa3
e5e0, 0xc0821cb938, 0x1353, 0x2a5298, 0xc0821479b0, 0xc0821233ab, ...)
        /usr/local/Cellar/go/1.4/libexec/src/text/template/exec.go:567 +0xaab
text/template.(*state).evalField(0xc0821b60c0, 0xa3ca60, 0xc0821b01e0, 0x16, 0xc
0821233ab, 0x5, 0x2a5298, 0xc0821479b0, 0xc0821233b0, 0x1, ...)
        /usr/local/Cellar/go/1.4/libexec/src/text/template/exec.go:478 +0x352
text/template.(*state).evalFieldChain(0xc0821b60c0, 0xa3ca60, 0xc0821b01e0, 0x16
, 0xa3e5e0, 0xc0821cb938, 0x56, 0x2a5298, 0xc0821479b0, 0xc082133190, ...)
        /usr/local/Cellar/go/1.4/libexec/src/text/template/exec.go:449 +0x2b4
text/template.(*state).evalVariableNode(0xc0821b60c0, 0xa3ca60, 0xc0821b01e0, 0x
16, 0xc0821479b0, 0xc0821233b0, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.4/libexec/src/text/template/exec.go:437 +0x34b
text/template.(*state).evalCommand(0xc0821b60c0, 0xa3ca60, 0xc0821b01e0, 0x16, 0
xc082141ce0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.4/libexec/src/text/template/exec.go:364 +0xa50
text/template.(*state).evalPipeline(0xc0821b60c0, 0xa3ca60, 0xc0821b01e0, 0x16,
0xc0821134f0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/text/template/exec.go:332 +0x1af
text/template.(*state).walkRange(0xc0821b60c0, 0xa3ca60, 0xc0821b01e0, 0x16, 0xc
082145240)
        /usr/local/Cellar/go/1.4/libexec/src/text/template/exec.go:245 +0x135
text/template.(*state).walk(0xc0821b60c0, 0xa3ca60, 0xc0821b01e0, 0x16, 0x2a52e0
, 0xc082145240)
        /usr/local/Cellar/go/1.4/libexec/src/text/template/exec.go:178 +0x2ac
text/template.(*state).walk(0xc0821b60c0, 0xa3ca60, 0xc0821b01e0, 0x16, 0x2aa898
, 0xc082147770)
        /usr/local/Cellar/go/1.4/libexec/src/text/template/exec.go:175 +0x869
text/template.(*Template).Execute(0xc082139280, 0x2a2790, 0xc08207fb90, 0xa3ca60
, 0xc0821b01e0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/text/template/exec.go:155 +0x3f9
html/template.(*Template).ExecuteTemplate(0xc0820e6b40, 0x2a2790, 0xc08207fb90,
0xc0821b2b90, 0x10, 0xa3ca60, 0xc0821b01e0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/html/template/template.go:92 +0xc7
github.com/spf13/hugo/hugolib.(*Site).renderThing(0xc0820e0000, 0xa3ca60, 0xc082
1b01e0, 0xc0821b2b90, 0x10, 0x2a2790, 0xc08207fb90, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:1449 +0x21
7
github.com/spf13/hugo/hugolib.(*Site).render(0xc0820e0000, 0xab4390, 0x8, 0xa3ca
60, 0xc0821b01e0, 0xc08207fb90, 0xc082120980, 0x6, 0x8, 0x0, ...)
        /Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:1424 +0x2c
7
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc0820e0000, 0xab4390,
 0x8, 0xa6cf10, 0x1, 0xa3ca60, 0xc0821b01e0, 0xc082120980, 0x6, 0x8, ...)
        /Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:1387 +0xe6

github.com/spf13/hugo/hugolib.(*Site).RenderHomePage(0xc0820e0000, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:1201 +0x17
f
github.com/spf13/hugo/hugolib.(*Site).Render(0xc0820e0000, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:395 +0x1a8

github.com/spf13/hugo/hugolib.(*Site).Build(0xc0820e0000, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:244 +0x8b
github.com/spf13/hugo/commands.buildSite(0xc082155c1f, 0x1, 0x1, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:342 +0xd9

github.com/spf13/hugo/commands.build(0x0, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:254 +0x2d
2
github.com/spf13/hugo/commands.func路006(0xd98b00, 0xdacaa0, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:51 +0x46
github.com/spf13/cobra.(*Command).execute(0xd98b00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/cobra/command.go:399 +0x394
github.com/spf13/cobra.(*Command).Execute(0xd98b00, 0x0, 0x0)
        /Users/spf13/gopath/src/github.com/spf13/cobra/command.go:447 +0x15e
github.com/spf13/hugo/commands.Execute()
        /Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:64 +0x36
main.main()
        /Users/spf13/gopath/src/github.com/spf13/hugo/main.go:24 +0x36

**Comment by bep** [comment]
Duplicates #1087 -- among others.
