### ISSUE TITLE
relref paths are environment specific

### ISSUE THREAD

**Issue by craiggwilson** [spf13/hugo#1111]
When I use relref, when running on windows, I need the paths to use windows separaters. i.e. relref "one\two\three.md". However, this doesn't work when building on linux, which needs relref "one/two/three.md". Hugo should normalize these and let either work in either place. Either that, or pick one and require it in both places.

**Comment by bep** [comment]
This was fixed in #957

**Comment by bep** [comment]
BTW, the path used in ref and relref should be thought of as URL paths - i.e. forward slashes.
