### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference, signal 0xb code=0x1 addr=0x0

### ISSUE THREAD

**Issue by larsth** [spf13/hugo#1112]
panic: runtime error: invalid memory address or **nil pointer** dereference
[signal 0xb code=0x1 **addr=0x0** pc=0x47ab4b]

Details: https://gist.github.com/larsth/43c9d5d64cc84efc768a
Hugo src code that triggers the panic: https://github.com/larsth/www.larsth.dk (41480308d6)

It looks like that it panics early (in the main goroutine).

I am a Gopher, so I can help with more details, if necessary.

**Comment by bep** [comment]
Thanks.

This duplicates #1108 which duplicates ... @spf13 we should really release 0.14. It's not packed with nenw features, but it has some important bug fixes that I seem to have to explain over and over and over again.
