### ISSUE TITLE
Enhancement Request: Images together with Content

### ISSUE THREAD

**Issue by moxiegirl** [spf13/hugo#1122]
As Per: http://discuss.gohugo.io/t/keep-images-content-together/51/7

This is really necessary for large documentation projects. It is much easier for contributors to see the images relative to the directory in which they appear. For example:

```
/registry
   content.md
   content2.md
   /images
      image1.jpg
      ...
      image3.jpg
```
We have a large documentation project and the files live in multiple repositories as well as act as content for our official documentation. Our programmers want to ensure that documentation "works" in Github too; this would support that.

**Comment by moxiegirl** [comment]
ping @spf13 we are pretty much guaranteed to need this for release based on the feedback I'm getting from the teams.

**Comment by bep** [comment]
This duplicates #147
