### ISSUE TITLE
Upper case .Site.Params has stopped working

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1129]
So `ISO8601`doesn't work anymore. This is widely used, so this is a site-breaking change.

**Comment by bep** [comment]
Breaking commit:
https://github.com/spf13/viper/commit/8d9577a72e57989b539c3cb7d7691673ed422af1

**Comment by bep** [comment]
@spf13 not sure whats the correct medicine here ...

There is 

```
func (s *SiteInfo) GetParam(key string) interface{} {
	v := s.Params[strings.ToLower(key)]
```

But then the `Params` map is also exported ... No way to fix this without breaking stuff.

**Comment by tatsushid** [comment]
Moving `SiteInfo.Params` to function call is also impossible because `isset .Params "key"` or `index .Params "key"` idioms are used widely. As @bep mentioned, there isn't a way to fix without breaking I think.

**Comment by bep** [comment]
For now, I have reverted the Viper commit -- we have to think this through, me think.

https://github.com/spf13/viper/commit/be782f3fee037d2db69c1c8af0e985e81e1ac273
