### ISSUE TITLE
.Slug is empty if not present in front matter, can it be inferred from the name of the file ?

### ISSUE THREAD

**Issue by davecheney** [spf13/hugo#1131]
I'm trying to create a list page that includes the pages inside it, I'd like to use something like .Slug to generate the #anchor tags. But .Slug is blank if not present in front matter. Do I have to set a slug in the front matter, or can it default to the name of the file the content was loaded from ? Is there an alternative way to do this ?

**Comment by bep** [comment]
```
{{ with .Slug }}{{ . }}{{ else }}{{ .BaseFileName }}{{ end }}
```
It might be worth to read the (little bit too complex) document about cross-references:

http://gohugo.io/extras/crossreferences/

By default, the Blackfriday Markdown engine creates some crazy #anchor tags that is a combi of a filename hash and the title and a sequence if duplicates. 

You can turn this off by putting this into your config.toml (or similar in yaml):

```
[blackfriday]
  plainIdAnchors = true
```

**Comment by davecheney** [comment]
Thanks for at, is .BaseFileName mentioned in the Variables page?

**Comment by bep** [comment]
No, see #1132
