### ISSUE TITLE
Complete  doc on Page variables

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1132]
There have been some questions lately about "how to get filename" -- these fields are exported, but not documented.

They should be.

* `BaseFileName` (`mypost`)
* `FullFilePath` (`/post/mypost.md`), also see #732 - current workaround is to use `Page.File.Path`

**Comment by davecheney** [comment]
Happy to be a pain in the ass.

**Comment by bep** [comment]
Have to have some of those to push the world in the right direction :-)

Re getgb.io; GitHub do a much better job at presenting YAML frontmatter, TOML looks kind of ugly.

**Comment by davecheney** [comment]
It all looks the same in vim.

**Comment by bep** [comment]
@digitalcraftsman have this covered in another issue.
