### ISSUE TITLE
Archetype lookup fails for Windows users using forward slashes

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1133]
So

`hugo new post/new-entry.md`

Will not resolve to section `post` on Windows.

See

http://discuss.gohugo.io/t/hugo-not-finding-archetypes/

**Comment by shinmyung0** [comment]
Doing 
```
hugo new post\/post.md
```
will work. This probably has something to do with windows taking `/` as the switch character.

**Comment by bep** [comment]
Yes. Since all the samples uses forward slashes, it should work with that on both platforms.
