### ISSUE TITLE
Allow for DIY livereload.js inclusion and config to detect live mode

### ISSUE THREAD

**Issue by hura** [spf13/hugo#1135]
I'd like to use instantclick for my static website (which I think is a common use-case for hugo given it generates static websites):

http://instantclick.io/

however, I'd need to add "data-no-instant" to the `<script>` tag of livereload or it'll error on me. Currently there is also no way to figure out in a template if live reload is enabled or not.

So I'd suggest to introduce two config parameters:
- `.Site.IncludeLiveReloadScript` - can be set false in config to DYI
- `.Site.LiveReload` - the negation of `disableLiveReload` of the config (or in case it's given from the command line).

There is obviously other ways to do this. But I think this might be the simplest one. If you disagree that this isn't a common use case, feel free to close it. I can live without it... :)

**Comment by spf13** [comment]
Would it hurt anything to just add that param to the script tag for everyone?

**Comment by hura** [comment]
Given that it's supposed to be dev-only. Probably not gonna hurt/break anybody/anything. So :+1:

**Comment by bep** [comment]
Like this?

```
<script data-no-instant>document.write('<script src="http://'
        + (location.host || 'localhost').split(':')[0]
		+ ':1313/livereload.js?mindelay=10"></'
        + 'script>')</script>
```

Or to the inner script tag? Or both?

**Comment by hura** [comment]
Just tested it. Yes, just the outer works fine. Thanks!

**Comment by bep** [comment]
Just tested this myself. Super-easy to setup and really snappy response times. Almost magical. Thanks for the tip!
