### ISSUE TITLE
Evaluate templates and code for Lastmod usage

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1141]
See #733 and the comment from @jbrodriguez :

```
Two comments:

1 - There are other internal templates that should probably be modified as well:

    rss.xml
    lastBuildDate

    opengraph.html
    og -> meta property="og:updated_time"
    facebook -> meta property="article:modified_time"
    twitter -> meta itemprop="dateModified"

2 - This code

    if len(t.pages) > 0 {
        n.Date = t.pages[0].Page.Date
        n.Lastmod = t.pages[0].Page.Lastmod
    }

t.pages is a WeightedPages, so it's sorted by user's definition (defaults to Date?).

But adding Lastmod means t.pages[0] not necessarily has the "latest" Lastmod.

If that's the case, perhaps we should scan t.pages or sort a copy of t.pages, to find the latest Lastmod.

Let me know how you see this.
```

**Comment by bep** [comment]
@jbrodriguez about 1) definitive Yes.

Re 2) I have to think a little about that one.

**Comment by jbrodriguez** [comment]
Re 2) Ok, I'll try to think about some other options as well.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
