### ISSUE TITLE
shortcode output wrapped in p-tags

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1148]
See 

http://discuss.gohugo.io/t/info-img-shortcode-figure-tag-auto-wrapped-in-p-tag-invalid-html/1202/5

**Comment by bep** [comment]
I remember adding divs around the shorcode placeholders to prevent this, but this was modified by @halostatue to fix an issue with the relref shortcodes. I guess we can remove the superflous p tags when doing the replacement.

**Comment by halostatue** [comment]
:+1:

**Comment by bep** [comment]
Yea, well, a expansion of the regexp in the last replace func is a 15% slow-down on my not very shortcode-heavy site.

**Comment by darylteo** [comment]
I'm trying to understand the source (not a go dev sorry), and it looks like you're processing the shortcodes and replacing them with shortcode placeholders. Perhaps if you replaced it with a html based placeholder (like <div %s="%d"></div>) markdown wouldn't wrap it with paragraphs tags. 

Anyway, fixing this would be really handy, although it isn't a "end of the world" issue I suppose.

**Comment by bep** [comment]
@darylteo you are correct, that was my initial approach. But @halostatue changed that as it had some other side effects.

**Comment by bep** [comment]
@darylteo I have tested this one pretty good myself, but it would be cool if you also could take the latest source for a spin and confirm that it it's fixed for you.

**Comment by nicolinuxfr** [comment]
Is it related in any way with `<p>` around images or not at all ?

**Comment by bep** [comment]
@nicolinuxfr it is if you use the figure shortcode and similar.

**Comment by nicolinuxfr** [comment]
@bep nope, I'm using plain Markdown to insert images and I have `<p>`around them. I guess I should open a new bug report then ?

**Comment by bep** [comment]
@nicolinuxfr yes, but that would be for Blackfriday: https://github.com/russross/blackfriday/issues

**Comment by darylteo** [comment]
@nicolinuxfr Images would be inline so they should have p's around them, I
believe.

@bep I will try. I'm installing Hugo via Brew so I'll need to figure out
how to get a custom build first =)

**Comment by dunn** [comment]
@darylteo if you just need the latest commits from the master branch, `brew install --HEAD hugo`

**Comment by darylteo** [comment]
@dunn wonderful 

@bep confirmed working for my use cases (figure and youtube shortcodes)

**Comment by bclermont** [comment]
Well, this isn't totally fixed.

If I used the follow shortcode ``shortcodes/bleh.html``:

```
<div>
    {{ .Inner }}
</div>
```

that way:

```
{{% bleh %}}
Markdown content
{{% /bleh %}}
```

it render like this:

```
<div>
Markdown content
<p></div></p>
```

**Comment by bep** [comment]
@bclermont to mee that looks like another issue, but I may be wrong. Looks like a Blackfriday issue, but if that is your complete shortcode, your work around would be to replace `%` with `<` and `>`.

But could you create another issue for your case?

**Comment by bclermont** [comment]
@bep I think you're right, I will investigate a little more.

is that normal that when I switch ``{{%`` to ``{{<`` markdown don't render anymore?

**Comment by bep** [comment]
@bclermont yes, the < syntax was added in 0.14 to handle use cases with raw HTML that didn't need Markdown rendering (or, the Markdown rendering messed it up badly ...)

**Comment by bclermont** [comment]
I created a separated issue #1387 for that with a project to reproduce the problem

**Comment by PuffinBlue** [comment]
The original bug appears to still be active in certain situations as described here:

https://discuss.gohugo.io/t/shortcodes-and-p-tags/2164/4?u=josharcher

Should this issue be reopened or a separate one created?

**Comment by bep** [comment]
Separate.
