### ISSUE TITLE
getCsv not work with local files

### ISSUE THREAD

**Issue by sun1001sun** [spf13/hugo#1150]

**Comment by SchumacherFM** [comment]
@sun1001sun would you please provide more details?

**Comment by sun1001sun** [comment]
I have Windows 7 32bit OS and hugo 0.13 version.
I used this example code:

```` html
  <table>
  <thead>
    <tr>
    <th>Name</th>
    <th>Position</th>
    <th>Salary</th>
    </tr>
  </thead>
  <tbody>
  {{ $url := "csv/1.csv" }}
  {{ $sep := "," }}
  {{ range $i, $r := getCsv $sep $url }}
    <tr>
      <td>{{ index $r 0 }}</td>
      <td>{{ index $r 1 }}</td>
      <td>{{ index $r 2 }}</td>
    </tr>
  {{ end }}
  </tbody>
</table>
````

I placed `1.csv` in folder `static\csv\1.csv`.
I used this command line `hugo server --watch`
But nothing happened.
Everithing work ok, when I placed csv file online on the server and put direct link `{{ $url := "http://www.server.com/csv/1.csv" }}`.

**Comment by SchumacherFM** [comment]
You path must be `{{ $url := "static/csv/1.csv" }}`.

http://gohugo.io/extras/dynamiccontent/

Ok?

**Comment by sun1001sun** [comment]
Thank you! Now it works. :)

**Comment by SchumacherFM** [comment]
Awesome! :+1:  Please close this issue.
