### ISSUE TITLE
Content referencing?

### ISSUE THREAD

**Issue by klakegg** [spf13/hugo#1151]
I'd like to see functionality for content referencing, a little like Entity Reference in Drupal.

Step 1 - Adding an identifier to the frontformater:

    +++
    id = "my-identifier"
    +++

Simply use filename if no identifier is declared (/post/hugo-hugs.md => 'post-hugo-hugs').

Step 2 - Functionality in template:

    {{ range ids .Site.Pages .params.related }}

or 

    {{ $next := .Site.Pages.Get(.params.next) }}

Is this functionality we'd like to see realized in Hugo? (Or only me?)

**Comment by bep** [comment]
What slice are you ranging over in the first example? (looks like 3)

**Comment by klakegg** [comment]
In step 2, my examples contains this documents:

Example 1:
Documents: /post/foo.md, /post/bar.md + rendered document

Rendered document:

    +++ releated = ["post-foo", "post-bar"] +++

The "ids" may be implemented using "where".

Example 2:
Documents: /post/step-2.md + rendered document

Rendered document:

    +++ next = "post-step-2" +++

The examples may be seen as two solutions where both may be of interest.

**Comment by bep** [comment]
Yea, well -- I'm reading what you say but I still do not get it (rendered document? HTML with TOML?). 

But I'm sure smarter people than me will chime in. 

If this is a "show me some related post" issue, then there are other issues in here describing it better.

**Comment by benzwu** [comment]
@klakegg so you were trying to produce rendered documents (one for each id) and inside that file list all pages that containt that ids?

**Comment by bep** [comment]
@klakegg please close this if you can not come up with some better explanation.

**Comment by bep** [comment]
This fits better at http://discuss.gohugo.io/
