### ISSUE TITLE
single.html is tried used on home page

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1152]
This fails.

http://discuss.gohugo.io/t/error-from-template-content-is-not-a-field-of-struct-type-hugolib-node/1221/10

**Comment by JamesMcMahon** [comment]
Why would you want to consider the list template and not the single template?

**Comment by bep** [comment]
Good question; I would consider the list template because both the list template and index.html (usually) expects a Node (a list struct) and not a Page (a single page).

In this issue I fixed what to me was an obvious bug ... removing the list.html from that list may break a lot of sites, and isn't a obvious bug.
