### ISSUE TITLE
Do not start server on missing config.toml

### ISSUE THREAD

**Issue by RickCogley** [spf13/hugo#1165]
(or maybe I get confused)
I am setting up a multilingual site and specifying config files when I run `hugo server`, but, if I do not cd to the repository, `hugo server` gets confused even specifying `--config`. My version:

`Hugo Static Site Generator v0.14-DEV BuildDate: 2015-05-20T07:50:17+09:00`

Given a structure like: 

~~~
me@mine:~/repo/esolia
⇒  tree -L 2
...
├── config_en.toml
├── config_ja.toml
├── content
│   ├── en
│   └── ja
├── layouts
│   ├── en
│   ├── index.html
│   ├── ja
│   └── partials
└── static
  ...
~~~

... where I have `en` and `ja` language folders in `content` and `layouts`, when I am in `~` and _not_ in the repo, and I run functions in my `.zshrc`: 

~~~
function hugoserveresoliaen {
    hugo server --buildDrafts --watch --verbose --editor="atom" --source="/Users/rcogley/repo/esolia" --config="config_en.toml" --port=1377
}

function hugoserveresoliaja {
    hugo server --buildDrafts --watch --verbose --editor="atom" --source="/Users/rcogley/repo/esolia" --config="config_ja.toml" --port=1399
}
~~~

... specifying the source folder and configs, `hugo server` starts ok and appears to work, but, the content gets mixed up and confused. Variables specified in the configs do not work. It seems like whichever started first "wins" and there is no separation of data. 

Turns out I have to cd into the repo folder and then run the commands. It works fine then. So I added the `cd` commands to my functions and it's fine: 

~~~
function hugoserveresoliaen {
    cd /Users/rcogley/repo/esolia
    hugo server --buildDrafts --watch --verbose --editor="atom" --source="/Users/rcogley/repo/esolia" --config="config_en.toml" --port=1377
}

function hugoserveresoliaja {
    cd /Users/rcogley/repo/esolia
    hugo server --buildDrafts --watch --verbose --editor="atom" --source="/Users/rcogley/repo/esolia" --config="config_ja.toml" --port=1399
}
~~~

However, is this the expected behavior? If you specify a source folder, wouldn't `hugo server` naturally find the configs in there? 

Or, do I need to specify the full path of the config file in each `--config` param? 

Please advise.

**Comment by bep** [comment]
To long a post to read now, will read later, but have a look at this and see if it may be of relevance:

https://github.com/spf13/viper/issues/69

**Comment by RickCogley** [comment]
Thanks @bep. I guess it's also reasonable to require people to specify the path of the config file. However, I think hugo server should return an error if it cannot find the config as specified (with no path). 

The thing is, why does it "kind of" work. The sites load ok even when running hugo server from ~, but, things get mixed up and there is no separation.

**Comment by bep** [comment]
Looking at the source, here is what happend:

* if you set config file using --config, this is the config file that is used
* Else: If you do not set --config it is read relative to --source

In your case, you have no path in --config, hence it tries the current folder.

**Comment by RickCogley** [comment]
Thanks @bep. Yeah, that's what I suspected, but, why does `hugo server` load the site at all then? Somehow it is figuring out that one of those config files below `~` where I ran it, in `~/repo/esolia` is the "right" one and loading it. I tried this after nuking `public` too. In my opinion `hugo server` should look at the path specified, and return an error like "can't find a Hugo config file at specified path".

**Comment by bep** [comment]
1. If you run with those params outside of the project, you should get a `ERROR: 2015/05/25 Unable to locate Config file. ...` error. The site still starts with all the settings to their defaults.
2. Running the same from the project dir will pick up the config file, because now the relative path is correct.

I guess 1) should exit before the server is started.

**Comment by bep** [comment]
A workaround for your case should be:

`--config="/Users/rcogley/repo/esolia/config_en.toml"`

**Comment by RickCogley** [comment]
Yes, agreed, specifying the path is the key. But I wonder why `hugo server` being run from `~` would pick those up from a subfolder.

**Comment by bep** [comment]
`hugo server` now exits with `exit -1` if no config file found, ant that should solve the main issue here.
