### ISSUE TITLE
Add retry for dynamic content

### ISSUE THREAD

**Issue by thomasmodeneis** [spf13/hugo#1166]
Hi,

```getJson```  often get into an error that I believe is because HTTP server sometimes may return 404 or a wrong content, this is being parsed and the error is below: 
```
ERROR: 2015/05/25 Cannot read json from resource http://127.0.0.1:3000/123test with error message invalid character 'E' looking for beginning of value
ERROR: 2015/05/25 Error while rendering page 123test.md: reflect: call of reflect.Value.Type on zero Value
```
Is there a retry policy for the dynamic content ?

Thanks

**Comment by bep** [comment]
Don't thinks there's any retry policy.

/cc @SchumacherFM

**Comment by SchumacherFM** [comment]
There is no retry policy.

**Comment by SchumacherFM** [comment]
Just found this: https://github.com/sethgrid/pester
I could implement it with a default retry of 2secs and a log warning that the retry is happening.
What do you think @bep ?

**Comment by bep** [comment]
Hmm ... Hugo gets some deserved critique about having too many external dependencies ... I do not think this one reaches the bar of inclusion ( @spf13 may disagree). A simple, hardcoded retry n times with a pause would be welcome, though.

**Comment by spf13** [comment]
Agree with bep. Keep it simple. 


Best,
Steve

-- 
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13




On Tue, May 26, 2015 at 12:48 AM -0700, "Bjørn Erik Pedersen" <notifications@github.com> wrote:












Hmm ... Hugo gets some deserved critique about having too many external dependencies ... I do not think this one reaches the bar of inclusion ( @spf13 may disagree). A simple, hardcoded retry n times with a pause would be welcome, though.

**Comment by thomasmodeneis** [comment]
I also like the idea of simple retry with no external deps, just to make it simpler. I think adding warn a message with the status code (in case of failures) will also help debug possible problems :)

**Comment by SchumacherFM** [comment]
I'll build something and send a PR for review.

BTW: Dave Cheney mentioned yesterday hugo at his presentation at Sydney Go Meetup: Why hugo must use etcd libraries? So many dependencies ...

(Of course due to viper ...)

**Comment by bep** [comment]
Mr. Cheney just wants to sell his GB framework :-) About the etcd framework he's got a big point. There should be a way for us to opt-out of that feature.

PR welcome.

**Comment by spf13** [comment]
I agree about Viper needing to break up a bit. If we move the remote dependencies into another library it would keep things simple. Challenge is doing that and keeping the batteries included feel it has today in Go.

**Comment by bep** [comment]
Well, what Go should have had was a sense of enabling features from the project/client side by turning on features by adding dependencies to the GOPATH. 

Is etcd in GOPATH? Enable that feature.

In the Java world, the entire Spring Boot project is built upon this concept.

**Comment by bep** [comment]
Failing that, Viper should maybe come in two variants -- an all batteries included and a bare-bone version.

**Comment by SchumacherFM** [comment]
Yes a bare bone Viper version where I can add features from other Viper packages. These features simply fullfill an interface in Viper.
I'm currently also using Viper in an eCommerce project ... but I [hide Viper](https://github.com/corestoreio/csfw/blob/master/config/manager.go#L95) in a private struct field because I may replace Viper with a slimmer solution.

And gb is awesome :-)

**Comment by SchumacherFM** [comment]
@thomasmodeneis please see PR #1175 You can also checkout my branch, compile hugo and then test it.

**Comment by bep** [comment]
Re. Viper, see https://github.com/spf13/viper/pull/79

I hadn't thought about "blank imports".

**Comment by thomasmodeneis** [comment]
@SchumacherFM @bep @spf13 I've tested this several times and it works great...perfect! :)
Thanks
