### ISSUE TITLE
Messes up src, leaves data-src alone if non-English alt tags

### ISSUE THREAD

**Issue by rippler** [spf13/hugo#1170]
I have the current version (downloaded, binary) of hugo.

I have MD file with an `img` tag that has these attributes:
`src="http://some.link/file.jpg"`
`data-src="http://some.link/file.jpg"`

After conversion HTML source has this:
`src="data:image/gif;base64,R<snip>P///z<snip>1"`
`data-src="http://some.link/file.jpg"`

Has anyone encountered this with double-byte language strings (or non-English, for example) in `alt` tag?

**Comment by bep** [comment]
There is no alt-tag in your example. Could you provide a more complete example?

**Comment by bep** [comment]
I tried variations of the below without hitting your problem:

`<img src="http://some.link/file.jpg" data-src="http://some.link/file.jpg" alt="На берегу пустынных волн">`

**Comment by rippler** [comment]
Hmm, I tried now in Gnome/Gedit, it worked okay. Then it must have come from the WP importer, I'll submit a bug there.
