### ISSUE TITLE
Suggestion: Use github.com/natefinch/pie for plugins

### ISSUE THREAD

**Issue by natefinch** [spf13/hugo#1171]
I made a plugin toolkit package - https://github.com/natefinch/pie - which uses subprocesses that call RPC over stdin/stdout.  I've seen some calls for plugins in Hugo in the issues in the past, and I think this could be an efficient way to make it work.  The nice thing about this is that it's a persistent connection between Hugo and the plugin, so you don't have to re-run the plugin every time you want to call it (for example, if you had a highlight plugin, you could call it over and over with different content without the overhead of restarting the plugin application each time).

I see a lot of places where this could be useful in hugo:

- content type support external to Hugo, so you don't have to modify Hugo itself to add support for asciidoc or latex (for example).
- shortcode support external to Hugo
- probably 1000 other things I can't think of right now.

The nice thing about Pie is that it is language agnostic - you can write plugins in whatever language you want, as long as they can serve RPC over stdin and stdout.  This works well for getting people who don't write Go to write plugins for your application.

I may hack on this some and see what I can come up with, if anyone thinks this is worthwhile.   I'd like to put Pie through its paces in a real application, to make sure I'm not missing anything.

**Comment by natefinch** [comment]
actually, I should post this on discuss.gohugo.io... so I will :)

**Comment by bep** [comment]
Yea, discussions works best at discuss.

**Comment by natefinch** [comment]
Note, here's the discussion: http://discuss.gohugo.io/t/using-for-plugins-in-hugo/1239
