### ISSUE TITLE
Remove deprecated fields and methods

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1172]
See usage of method `helpers.Deprecated`.

Give people a week or two more, maybe ... although they have had some time already.

**Comment by anthonyfok** [comment]
Hi @bep,

Thanks for laying the framework for the smooth transition.

I have been away for a little too long, and a little bit out of touch, so I need your advice:

1.  Do you want me to just simply delete the lines that call `helpers.Deprecated()`, e.g. `helpers.Deprecated("Site", ".BaseUrl", ".BaseURL")`?
2. Or do you prefer extending `helpers.Deprecated()` or creating a new `helpers.Obsolete()` that would stop on these errors?

**Comment by bep** [comment]
@anthonyfok no problem about the time ... I thinks we should make one last check with the themes (building the hugoThemeSite should show which themes are not updated)

The task is simple:

- Delete all current usage of helpers.Deprecated (the method itself can stay)

**Comment by bep** [comment]
@anthonyfok when all (or most) of the PRs in thttps://github.com/spf13/hugoThemesSite/issues/6 goes to purple, then it is go time.

**Comment by bep** [comment]
@anthonyfok now is the time to do the cleanup: Delete all methods that use `helpers.Deprecated()`-

**Comment by anthonyfok** [comment]
@bep: Thank you for the heads up!  Please see PR #1309.
