### ISSUE TITLE
Trailing slash removed from RelPermalink when CanonifyURLs = true

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1174]

**Comment by kohlerm** [comment]
I have v0.14 and I seem to run into this bug. 
I have CanonifyURLs = true
and the links are generated without the trailing /
Our internal github server does not like that and jumps to a non existing page. 

Anyway around this other than compiling hugo by myself?

**Comment by bep** [comment]
You can add the trailing slash manually.

**Comment by kohlerm** [comment]
Thanks! I found the layout files where I had to change it.
