### ISSUE TITLE
Special characters in taxonomy and slugs

### ISSUE THREAD

**Issue by nicolinuxfr** [spf13/hugo#1180]
I'm trying Hugo for my [personal blog](http://voiretmanger.fr) which has a lot of taxonomies. And as I'm writing in French, many taxonomies have special characters in them, like an accentuated letter. 

Right now, I'm using WordPress which has the perfect behavior on this matter. The taxonomy name can have any special characters (for example, "Gérard Depardieu"), the slug associated with it only has standard characters (`gerard-depardieu`). But when you display the taxonomy archive, you still have the special characters : so in this case, you would not have "Gerard Depardieu", but "Gérard Depardieu"). You can see the example live here : [http://voiretmanger.fr/acteur/gerard-depardieu/](http://voiretmanger.fr/acteur/gerard-depardieu/).

![taxonomy-example](https://cloud.githubusercontent.com/assets/2078386/7881031/4121be16-05ff-11e5-9da6-ce704790fa41.png)

I don't know if Hugo could do the same. I know WordPress has a database, so it's easier. But I can see some solutions (or hacks) to make it work : either look in the metadata associated with the post to display the name of the taxonomy on the archive page, or have a "table" (a YAML/TOML config file, I guess) with all correspondances. 

An idea, to end my Gérard Depardieu example : 

    gerard-depardieu: "Gérard Depardieu"

I hope a solution will be feasible, because it's the main thing that would be keeping me out of Hugo and with WordPress. I think I can find a solution for every other problems I have…

Thanks anyway for your time !

**Comment by bep** [comment]
This isn't hard to fix and I understand the motivation for it.

We already do some URL normalization of the taxonomies, but probably didn't think about monsieur Depardieu back then. This might be a breaking change (as someone will have some URLs changed), but it's the right thing to do.

**Comment by nicolinuxfr** [comment]
OK, great for the first and easy part ! Thanks :-)

There's one more problem though : I don't want the accent in the URL, but I want it on the archive page (like on the screenshot). 

With nothing more, I don't see how it could work. Am I wrong ?

**Comment by bep** [comment]
You are wrong. The accents (and some others) are ONLY stripped for the paths (on disk and the URL presented to the user). The taxonomy name (or key) will be preserved as written.  

I added the "Gérard Depardieu" tag to one of my posts to make sure. It has nothing to do with the actor, but I might publish it just to confuse people.

**Comment by bep** [comment]
OK, I retract the last I said above -- there is one more fix to do.

**Comment by bep** [comment]
I can get this to work in a hackish-kind-of way, but will have to look at this later -- to do a proper fix.

**Comment by nicolinuxfr** [comment]
Well thanks ! I'm impressed, we are definitely not on the WordPress pace here… :-)

**Comment by nicolinuxfr** [comment]
Just a quick note to thank bep for his work… it works exactly as I wanted it ! So it's perfect as far as I am concerned. :-)

![capture d ecran 2015-06-01 a 17 44 13](https://cloud.githubusercontent.com/assets/2078386/7916758/2a6f5d16-0886-11e5-893b-355094b06b0c.png)

**Comment by RickCogley** [comment]
Interesting @bep, because when you "normalize" Japanese, and remove the "accent" from katakana, the meaning changes completely. In some cases it's unrecognizable or at least quite humorous.

**Comment by bep** [comment]
OK, so that part may have been a bad idea ... I can revert that if I'm convinced ... Hmm, languages. @nicolinuxfr

**Comment by nicolinuxfr** [comment]
Hum, not a bad idea for me anyway. I hope I will be able to keep this really important feature for me.

**Comment by RickCogley** [comment]
@bep, I can give you precise information about which characters in Japanese are losing their "accent" if that will help. 

For instance: 

    ビ  going to ヒ

Please advise how I can assist in figuring it out.

**Comment by bep** [comment]
@nicolinuxfr yes, that was the input I wanted (how important is it). @RickCogley I think the solution is to add an option around this, so @nicolinuxfr and other frenchmen who love their accents can have them preserved. Unicode is a science, btw.

I will fix this later tonight.

**Comment by nicolinuxfr** [comment]
He he, it's not that we love these, but the meaning is completely different without accents… :-)

Thanks for trying to satisfy everyone here !

**Comment by RickCogley** [comment]
@bep, the bit of the character in Japanese that is getting stripped is called a "dakuten" <https://en.wikipedia.org/wiki/Dakuten>. There is one that looks like a double quote and one that looks like a circle. After rendering to public using ``hugo server``, I see this: 

~~~
rcogley@jrcmbp2015:~/dev/eSolia/public/ja/topics|rc-working-2⚡
⇒  ll
total 8
drwxr-xr-x  4 rcogley  staff   136 Jun 16 22:22 about
-rw-r--r--  1 rcogley  staff     0 Jun 16 22:23 index.html
-rw-r--r--  1 rcogley  staff  1928 Jun 16 22:23 index.xml
drwxr-xr-x  4 rcogley  staff   136 Jun 14 20:58 professional
drwxr-xr-x  4 rcogley  staff   136 Jun 14 20:58 お問い合わせ
drwxr-xr-x  4 rcogley  staff   136 Jun 16 22:25 はひふへほ
drwxr-xr-x  4 rcogley  staff   136 Jun 14 20:58 サーヒス
drwxr-xr-x  4 rcogley  staff   136 Jun 16 22:25 ハヒフヘホ
~~~

I'm using "topics" as a taxonomy here. The last 3 lines in the ``ll`` output have these marks, and are supposed to be: 

~~~
topics:
  - About
  - ばびぶべぼ
  - バビブベボ
  - ぱぴぷぺぽ
  - パピプペポ
~~~

But Hugo strips the dakuten, and combines the four into two. That is, ba バ pa パ both become ハ.

**Comment by bep** [comment]
@RickCogley I know what we strip and how to not strip them ... Will fix tonight.

**Comment by bep** [comment]
@nicolinuxfr please add RemovePathAccents = true to your config to keep the behavior you want.

**Comment by nicolinuxfr** [comment]
Great, thanks for keeping me satisfied along with everyone else ! :-)

Is it merged yet so I can try using home-brew or should I compile it manually ?

**Comment by bep** [comment]
Didn't you have some success with go get -u .... ?

**Comment by dunn** [comment]
@nicolinuxfr you can install the absolute latest version with `brew install --HEAD hugo`

**Comment by nicolinuxfr** [comment]
@dunn are you sure ? I tried to upgrade that way and the build seems old : 

    Hugo Static Site Generator v0.14 BuildDate: 2015-05-26T18:46:46+02:00

@bep for me, everything is still fine !

**Comment by RickCogley** [comment]
@bep, thanks, after a recompile with ``go get -u -v github.com/spf13/hugo``, I have proper Japanese again. :-)

@dunn, I stopped using ``brew install --HEAD hugo`` after finding it wonky a while back, but the above always works for me.

**Comment by dunn** [comment]
@RickCogley yeah, new dependencies have to be added manually, so it can break. I just opened https://github.com/Homebrew/homebrew/pull/40794; thanks for the heads-up, @nicolinuxfr!

**Comment by RickCogley** [comment]
@dunn ah, I see. Thanks. I hadn't realized that.

**Comment by eugenioej** [comment]
> @nicolinuxfr please add RemovePathAccents = true to your config to keep the behavior you want.

Thanks!!!! This is what I was looking for my site on spanish :)
