### ISSUE TITLE
Adding support for breadcrumbs

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#1185]
It would be nice to have a small code snippet provided by Hugo that generates a breadcrumb with links, especially if the content is very nested.

Even smaller examples with the permalink example the docs would be great:

```
permalinks:
    post: /:year/:month/:title/`
```

would output

**Comment by bep** [comment]
In your example, what would `2015` and the others link to?

**Comment by digitalcraftsman** [comment]
The links are dummy links to make the breadcrumb a bit more visually.

**Comment by bep** [comment]
Sure, but to implement breadcrumbs one wold have to have an idea of what the site hierarchy looks like -- and currently I do not see an easy way to navigate the structure you sketch.

Thinking out loud, what we got now is:

/ (home)
/section1
/section1/post1
/cagegories/
/categories/movies/
etc.

So fairly shallow.

**Comment by digitalcraftsman** [comment]
Would it be alternatively possible to map the structure manually?

**Comment by bep** [comment]
If we assume that the site has a natural hierarchy, you could use something like 

`{{ crumbs := split .URL, "/" }}`

And use that to build your navigation.

**Comment by digitalcraftsman** [comment]
This should work and thanks for the snippet.
