### ISSUE TITLE
Livereload doesn't use BaseURL

### ISSUE THREAD

**Issue by ghost** [spf13/hugo#1187]
When I view source, I see it uses `localhost:8000`, but I'd like it to use `BaseURL:8000` instead.

```
<script data-no-instant>document.write('<script src="http://'
        + (location.host || 'localhost').split(':')[0]
        + ':8000/livereload.js?mindelay=10"></'
        + 'script>')</script></body>
</html>
```

Can I hard-code my desired hostname somewhere around https://github.com/spf13/hugo/blob/master/docs/static/js/livereload.js#L117?

**Comment by bep** [comment]
It does try to use `location.host` first. That works fine for me (I'm not running on localhost, either). 

But you're right, this should be set to something other than localhost, but not baseURL -- the `bind` flag introduced in 0.14 should be correct.

**Comment by rippler** [comment]
I don't know where it's supposed to get `location.host` from, but it's not getting it in my case (behind NAT, etc.). Is it possible to hard-code a hostname somewhere in the script?

**Comment by bep** [comment]
`location.host` is from your browser (via Javascript). As to hardcoding, test it. But if this is an issue for you, it is probably an issue for others -- and as such should be fixed more permanently. Not sure why you need to run your development server behind NAT and firewall, but that's another discussion.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by iangkent** [comment]
I am having the same problem when I run hugo server in container/pod in kubernetes cluster with ingress using path based routing. The hugo server running in container in pod listens on localhost:1313 but is accessed from browser via ingress at http://localhost/default/docs (loadbalancer address/kubernetes namespace/kubernetes service name). The livereload.js injected in hugo generated pages does not include baseurl.

I run hugo in container with following commandline:
hugo server --baseURL=http://localhost/default/docs --liveReloadPort=80 --appendPort=false --bind=0.0.0.0

**Comment by cderv** [comment]
@iangkent did you manage to make it work ?
