### ISSUE TITLE
Periods in taxonomies generates bad paths

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1188]
See

http://discuss.gohugo.io/t/periods-in-taxonomies-are-generating-bad-paths/1258

**Comment by ryanclarke** [comment]
I'm going to try to fix this. I don't know go: wish me luck... :smiley:

**Comment by bep** [comment]
Good luck!

The URL handling in Hugo is a little bit too fragmented, but there should be test cases (see site_test.go and page_test.go - esp. the first) that will break when you add some periods.

**Comment by ryanclarke** [comment]
Yes, I've discovered that the URL handling is rather complex and probably in need of streamlining.

I'm thinking the most straightforward way to do this is having a new simpler method on https://github.com/spf13/hugo/blob/master/hugolib/site.go#L1384. This new method would only know how to turn the "/<taxonomy>/<key>" and "/<section>/<key>" formats into pretty and ugly urls.

**Comment by bep** [comment]
Yes, that sounds reasonable.

**Comment by ryanclarke** [comment]
It appears that the rss feeds don't respect the ulgyURLs flag. Is this a bug?

**Comment by bep** [comment]
No, that is by design. They even have the rssURI to make them as ugly as it gets.

**Comment by ryanclarke** [comment]
I'm still working on this, as I have time. It's a rather tricky issue. I'm having trouble finding a non-invasive fix that doesn't cause side effects. And now I'm a couple months behind HEAD.

Anyway, just to let you know I'm not dead and that I'm still trying to fix this. I'd really like to upgrade from v0.12.
