### ISSUE TITLE
Int Typecast

### ISSUE THREAD

**Issue by Secretmapper** [spf13/hugo#1190]
Might be related to #620. 

Can I even typecast ints in hugo? 

Running:
`substr .Permalink (add (len .Site.BaseURL) 3) (len .Permalink)`

produces the error:
wrong type for value; expected int; got int64

Because of the `(add (len .Site.BaseURL) 3)`

I am using 0.14 by the way

**Comment by tatsushid** [comment]
I checked and found what caused it. I'll fix it in the weekend.
