### ISSUE TITLE
How to directly use static html file?

### ISSUE THREAD

**Issue by loongmxbt** [spf13/hugo#1191]
For example, if I want to create an about page, I can run `hugo new about.md` . And than access the page via `/about`. I can define the content and use the default layouts.

But here I want to create a page `about.html` because the layout is custom and unique. And I assume the html file looks like this.

```
# layouts/about.html
{{partial "head.html" .}}
{{partial "header_page.html" .}}

  {{template "page/about.html" .}}

{{partial "footer.html" .}}
{{partial "scripts.html" .}}
```
Is there an easy way to create static html page with custom layout? Thanks!

**Comment by humboldtux** [comment]
First declare a type for your about page in its metadata:

``` markdown
...
type = 'about'
...
```

Then create a custom layout in **layouts/about/single.html**

**Comment by bep** [comment]
Questions is best to put on http://discuss.gohugo.io/

**Comment by loongmxbt** [comment]
@humboldtux Exactly! Thanks a lot. Now I realize the difference between `type` and `section`.
@bep Sorry and thanks for your notice. I'll ask questions in the forum later.
