### ISSUE TITLE
Found Malware in the Latest Version

### ISSUE THREAD

**Issue by pfizerrep** [spf13/hugo#1195]
Hi Guys,
I'm a total noob to this stuff. I was using the directions given to me from the Get Started guide. I downloaded the hugo_0.14>windows_amd64.zip file. 
When I went to execute it, my Malware Bytes lit up and stated that it planted a Worm.Zhelatin. When I ran the quarantine, it removed the whole Hugo.exe file. 
Any ideas where to go from here?
Chris

**Comment by bep** [comment]
@spf13

**Comment by bep** [comment]
That file goes all green here, btw:

https://www.metascan-online.com/en/scanresult/file/d64279877fe543ccb1c9f6f1e92323ce

**Comment by pfizerrep** [comment]
Thanks bep!  So, honestly, what do I do here?  Run it again and ignore Malware Bytes? I'm not super techy, so I don't have any experience ignoring false positive threats.

**Comment by bep** [comment]
I'm closing this for now. Will reopen if any new info surfaces. Please check your own computer for infections.CC @spf13

**Comment by bep** [comment]
No you shouldnt ignore it. You could check if its modified om your side. Compare File size, hash.

**Comment by pfizerrep** [comment]
OK. Thanks.

**Comment by bep** [comment]
@pfizerrep and note that me closing this isn't me saying it isn't an issue for you. But I'm pretty sure it's not Hugo to blame.  

I will investigate further, and will reopen if we can do some active measures from our side.
