### ISSUE TITLE
Non-MD files in the content directory ignores permalinks

### ISSUE THREAD

**Issue by gima** [spf13/hugo#1199]
Does not work with permalinks.

Files are laid out in a directory path matching the pre-permalink URL, thus effecively ignoring permalinks completely.

---

_Link to the issue adding this feature: #147 (Non-MD files in the content directory (like jpg's and png's) end up as html's)_

**Comment by bep** [comment]
Permalinks applies to content generated by Hugo.

There will come an extension to this concept that, probably, will let you somehow bundle media files and content files that I guess will cover this one.

**Comment by gima** [comment]
I do not follow your reasonin. Hugo's job is to generate content from source, and permalinks are a way to facilitate changing the destination of the generated content. The feature #147 was implemented incompletely.

**Comment by bep** [comment]
Yeas, well. #147 was covered if you look at the headline. I agree that there are missing work here, but we do not get that work done by arguing which issue it belongs to.

**Comment by gima** [comment]
There is no argument. There is only the fact that you have probably misunderstood what this bug report is about and labelled it incorrectly as a feature request. Make no mistake, this is a bug report for incorrect functionality, don't down-play this.

Let me re-iterate:

1. A feature request was made in #147 to allow files accompaning a publication to be copied to the same destination directory as the index.html that was generated by hugo.
2. The feature was implemented, but if permalinks are configured so that the the destination directory is changed for the generated index.html, the accompanying files are still copied to a directory that the index.html would have been generated had there been no permalink configuration in the first place.

Does that sound like a *feaure request* or an a *bug report* for an incorrect functionality?

**Comment by bep** [comment]
We read the bug report differently, that's fine. 

Quote bug report #147: "When I put non-md files in the content directory, they should just be copied over (untouched!)." 

That was the fix for #147. Unknown files are just copied over.

**Comment by gima** [comment]
Forget it, this project is not worth the effort.

**Comment by epsitec** [comment]
@bep I must agree with @gima that there is an issue. I'd like to be able to put PNG images alongside my blog posts, and get them copied over to the output, as is.

However, when using permalinks for a post found in `content/post` (`blah.md` and `foo.png`), the HTML output of my blog post gets copied to `2015/11/blah/index.html` (as expected) whereas the image gets copied to `post/foo.png`.

This means that I cannot use the same links when editing my files in an editor with active Markdown previewing, and when pushing them through Hugo. That's sad...

**Comment by epsitec** [comment]
And by the way, if I want the images to be copied info the correct folder, I have to set:

```
uglyurls = true
```

Just disabling permalinks is not enough, as the post gets copied to `post/blah/index.html` and the image to `post/foo.png` if I don't use `uglyurls = true`.

**Comment by kirtan403** [comment]
@gima Please reopen the issue. This is something needs to be discussed.

**Comment by gima** [comment]
Trying Hugo once again, and this problem still exists.

---

Filesystem layout:
```
content/page/my_first_blog_post/index.md
content/page/my_first_blog_post/prettypicture.jpg
```

`config.toml`:
```
[permalinks]
page = "/:title/"
``` 

Output after running `hugo`:
```
public/my_first_blog_post/index.html
public/page/my_first_blog_post/prettypicture.jpg
```

---

Is the problem clear now?  
**The bug is:** Permalinks configuration doesn't affect assets, whereas this case demonstrates that it very clearly should.

**Comment by gima** [comment]
Re-closing and moving comment to more appropriate bug-report (#1768).
