### ISSUE TITLE
Quick gist for hugo config

### ISSUE THREAD

**Issue by RickCogley** [spf13/hugo#1203]
I think it would be a good addition to include the ability to make a github gist from your hugo config, for pasting on the Hugo support site. 

Perhaps this might help... 
https://github.com/delta24/go-gist

**Comment by bep** [comment]
Doesn't `hugo config` cover (about) the same?

**Comment by RickCogley** [comment]
sorry for confusing things, @bep. I meant to have some kind of native Hugo-ish way to automatically make a gist from the config, for quick sharing for troubleshooting. Maybe I was overthinking this, since it's pretty easy to install command line utils that do this (gist, gistit, paste-gist). Then you can just do: 

    hugo config > gistit

More *nix-y anyway.
