### ISSUE TITLE
Can't figure this out: similar named content in multiple folders

### ISSUE THREAD

**Issue by tnolet** [spf13/hugo#1205]
Hi,

I have documentation for our product. The docs are split into multiple categories and sub sections. Each subsection starts with an "overview". However, I can't have two pieces of content with the same "title", even when they are in separate sections. Example:

```
installation -->
  overview.md
  stuff1.md
reference -->
  overview.md
  stuff2.md
api -->
  overview.md
  morestuff.md
```

Each `overview.md` cannot have the following front matter:
```yaml
---
title: Overview
weight: 10
```

This is really prohibitive. Am I missing something?

**Comment by tnolet** [comment]
P.S you can see the source and setup here: I'm choosing different names for each "overview page":
http://vamp.io/documentation/rest-api/overview/

hugo source:
https://github.com/magneticio/vamp.io

**Comment by bep** [comment]
http://discuss.gohugo.io/ is a better place for questions. And when you do post there, supply the error message you get when building your site.

**Comment by tnolet** [comment]
Thanks. You're absolutely right. And I found my answer already!
