### ISSUE TITLE
Calling a shell script via shortcode

### ISSUE THREAD

**Issue by josephkaptur** [spf13/hugo#1211]
(Possibly a dupe of https://github.com/spf13/hugo/issues/369)

It would be useful to allow users to define shortcodes that are arbitrary shell commands. For example, it would be handy (but probably not popular enough to build into Hugo) to have a CSV to HTML converter like this:

    {{< prettytable >}}
      some,headers,here
      1,2,3
      4,5,6
    {{< /prettytable >}}

that could generate the HTML

    <table>
      <tr class="header">
        <td>some</td><td>headers</td><td>here</td>
      </tr>
      ...

It might be possible to generate this just by using shortcode syntax, but it would be much more flexible to provide a special shortcode to call out to the shell. So the true syntax could be:

    {{< shell cmd="./prettytable.py" >}}
      some,headers,here
      1,2,3
      4,5,6
    {{< /shell >}}

where prettytable.py is

    print('<table>')
    for line in sys.stdin:
      print('<tr>')
      for cell in line.split(',')
      ...

This might be difficult for the user to configure - to generate the site correctly, you need to be sure that you have the prettytable.py script, the correct version of Python, whatever dependencies it requires, etc. 

That has the potential to be a nightmare, but I think that a shortcode that runs a shell command is a simple abstraction that has great power. As far as I can tell, there's no other way to generate inline HTML. 

I can look into the work required to implement this. Does it sound like a promising idea? My true motivation, of course, isn't just generating tables - I have some more-complex code (not written in Go, unfortunately) that generates HTML.

**Comment by dunn** [comment]
See also #796

**Comment by josephkaptur** [comment]
Thanks, no idea how I missed that.
