### ISSUE TITLE
Weird handling of pdfs

### ISSUE THREAD

**Issue by Juan4** [spf13/hugo#1213]
For every pdf that is linked to, Hugo generates a folder with the same name as the pdf and a 2kb file called "index.pdf"

Steps to reproduce:

1. hugo new site test
2. hugo new post/sample.md
3. Edit sample.md to link to /static/Publications/sample.pdf
4. clone a theme
5. hugo server --theme=hyde --buildDrafts
6. Result: /public/Publications/sample/index.pdf

**Comment by spf13** [comment]
what do you mean "link to"?

**Comment by Juan4** [comment]
Sorry, should have been more explicit about that. Here's "sample.md":

+++
date = "2015-06-17T11:27:24-07:00"
draft = true
title = "sample"
url = "/Publications/sample.pdf"

+++

**Comment by spf13** [comment]
Ahh. That explains it all. 

You don't need the markdown file at all. Just place the pdf file in the /static dir and it will just work.

**Comment by Juan4** [comment]
But what if I want to have, for instance, a post with an abstract of the paper and link to it?

**Comment by spf13** [comment]
you just make a link in the body of the markdown. URL is a special field that means that this content file should reside at that URL destination.

**Comment by Juan4** [comment]
Gotcha! What if I want the title of the post to be the link to the paper?

**Comment by spf13** [comment]
HTML doesn't support a link in the <title> tag. If you mean a headline, then you can add an additional field (a non reserved one) in the markdown. Something like "pdf_link" and use that in your template.

**Comment by spencergibb** [comment]
It's how I do the download for my resume: http://spencer.gibb.us/about/

See the source for how I link: https://raw.githubusercontent.com/spencergibb/spencergibb.github.io/source/content/about.md

and where I put the static files https://github.com/spencergibb/spencergibb.github.io/tree/source/static/resume

**Comment by Juan4** [comment]
This is what I mean: http://comesana.arizona.edu/publications/
Is it possible to make it look like that without generating the index.pdf?
I got the structure form the wordpress to hugo migrator, by the way:https://github.com/SchumacherFM/wordpress-to-hugo-exporter

**Comment by Juan4** [comment]
Nevermind: I used the recommended method.
