### ISSUE TITLE
Top page renders incorrectly after ``go get`` update

### ISSUE THREAD

**Issue by RickCogley** [spf13/hugo#1214]
Doing a ``go get`` as of commit 24351c58bedea72e4e113e2d2e5753a32ce2a0e3 makes my home page render incorrectly. 

I last did a ``go get`` (yesterday?) after @bep committed the change regarding accented characters in taxonomies and everything was fine. After updating this am, my home page, based on my index.html template, renders partially incorrectly. Meta data like the title and description also now does not get merged into the page, either.

**Comment by bep** [comment]
@spf13 maybe?

**Comment by RickCogley** [comment]
What I discovered just a few minutes ago @bep, is that the new-ish ``.IsHome`` function stopped working. I was relying on this to make my css load conditionally, and the top page's was not getting loaded for whatever reason. I reverted back to that ``{{ if eq (add .Site.BaseURL "/") (add .Permalink "/") }}home page stuff{{ end }}`` and it works again.

**Comment by RickCogley** [comment]
Also, and just "for the record" in here so it's searchable, it was trivial to ``git checkout`` a specific commit, in a cloned fork of this repo, and run the included ``make`` to build a Hugo from that commit. It was much easier than I imagined it would be. Thanks for all the hard work that has gone into this.

**Comment by bep** [comment]
Yea, it kind of works for my simple pages ... But @spf13 did some work on the homepage that now can be several things I'm not sure I understand ...

**Comment by spf13** [comment]
This is probably my fault. @bep... I'm considering changing my implementation to just add the `content` field to nodes which might be a simplier approach.

I need to look at the .IsHome function. It may need fixing after my changes here. 

@RickCogley it's mostly go that makes it so easy. If you are just looking for the latest you can just call `go get -u github.com/spf13/hugo` followed by `go build` from that directory.

**Comment by RickCogley** [comment]
@spf13 getting used to it, little by little. A great system altogether. 

Please advise when I can test .IsHome. If it'll take time, I'll switch back to the old way of checking. If you wouldn't mind, just let me know if this problem is a quick fix, or, will take time. Thanks :-)

**Comment by spf13** [comment]
@RickCogley give it a try now. I think it should be working.

**Comment by RickCogley** [comment]
hi @spf13, unfortunately, it does not appear to be working. This is the code that is breaking in my partial head.html called from my top index.html. 

~~~
  <title>{{ if eq .Site.Params.locale "en-US" }}{{ if .IsHome }}Welcome to {{ end }}{{ end }}{{ .Title }}{{ if eq .Site.Params.locale "ja-JP" }}{{ if .IsHome }}へようこそ{{ end }}{{ end }}{{ if ne .Title .Site.Title }} : {{ .Site.Title }}{{ end }}</title>
  <meta name="description" content="{{if .IsPage}}{{ .Description }}{{else}}{{.Site.Params.description}}{{end}}">
  <meta name="keywords" content="{{if .IsPage}}{{ range $i, $e := .Params.tags }}{{ if $i }}, {{ end }}{{ $e }}{{ end }}{{else}}{{.Site.Params.keywords}}{{end}}">
~~~

The first line just gives the site title. The second and third lines give `` where the description and keywords are supposed to appear. 

One thing I noticed is, when I do ``hugo version`` first, then ``go get -u -v github.com/spf13/hugo``, then another ``hugo version`` the hugo being referenced in gopath definitely is a new version. (``which hugo`` gives ``/Users/rcogley/gocode/bin/hugo`` as I expect)

Isn't it running ``go build`` automatically? If not, sorry, where do I run ``go build`` from, exactly?

**Comment by RickCogley** [comment]
A bit of an aside from the bugfix: what I discovered was, given my env setting ``GOPATH=/Users/rcogley/gocode``, when I run the ``go get`` it does indeed build the latest and put it in ``$GOPATH/bin/hugo``. I can cd to ``$GOPATH/src/github.com/spf13/hugo`` and run ``make`` to compile the binary that displays the commit it was compiled from when doing ``hugo version``. That's sometimes good to know. Just have to manually copy it to ``$GOPATH/bin/hugo``.

**Comment by bep** [comment]
@spf13 I have tried to wrap my head around your changes. I think the approach with just moving the content to Node is simpler and less risky. The current situation where the home page is a Page unless it is paginated,  then it's a node, smells like trouble to me.

**Comment by spf13** [comment]
I agree. The further I got into the implementation the more I thought this was heading for trouble. I'll spend some time moving it towards a node with content.

**Comment by bep** [comment]
I was wrong about it being OK in my sites. It was my new Go build setup that was faulty:

´´´
ERROR: 2015/06/21 Error while rendering homepage: template: index.html:1:99: executing "/Users/bep/sites/bepsays.com/layouts/index.ace::main" at <.Paginate>: error calling Paginate: Paginators not supported for content pages.
´´´

**Comment by bep** [comment]
@spf13 I saved your changes in a branch and reverted your changes. Nothing was working on my side, and I had to test out a bug-fix I was going to commit. 

@RickCogley now it should work.

**Comment by spf13** [comment]
Thanks @bep. Sorry for breaking head. I'll rewrite it.

--
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by RickCogley** [comment]
@bep @spf13 thanks fellows. It works again!
