### ISSUE TITLE
Quiet mode

### ISSUE THREAD

**Issue by hickford** [spf13/hugo#1218]
Hi. Many apps have a quiet mode `-q` or `--quiet` that only prints in case of error. How about a quiet mode for Hugo? I'd find this useful for a cronjob.

**Comment by spf13** [comment]
It wouldn't be hard to write. It's as simple as changing how JWW outputs things when --quiet is set... That said, it's easy enough to use the standard way of doing this `>/dev/null 2>&1` which cron itself recommends to silence the output (by redirecting the output of your program to /dev/null)

**Comment by digitalcraftsman** [comment]
@spf13 it isn't as easy at it seems. As discussed in the corresponding pull request (#2017) `jww.FEEDBACK` is used often but is completely independent from the log level and prints straight to the console. Quiet would mean that those messages would be suppressed.

**Comment by hickford** [comment]
Thanks. I've been using `chronic` as a workaround https://joeyh.name/code/moreutils/
