### ISSUE TITLE
disqusShortname parameter ignored in config.toml

### ISSUE THREAD

**Issue by brunetto** [spf13/hugo#1224]
Hi!
I can't get disqusShortname parameter working in `config.toml`. 
I tried to put it with the main parameters and under `[params]`, but it is ignored.

This is the page source 

```javascript
(function() {    
    if (window.location.hostname == "localhost")
        return;

    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    var disqus_shortname = '';
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
```

However, if I put the shortname in the template directly, everything works.

Hugo version 

```
$ hugo version
Hugo Static Site Generator v0.15-DEV BuildDate: 2015-05-30T17:12:00+02:00
```

obtained with `go get`.

**Comment by digitalcraftsman** [comment]
@brunetto Custom parameters like your `disqusShortname` will not work as "main parameter". Storing them under `Params` would be the right way.

Furthermore you need to access your custom variable with `var disqus_shortname = '{{ .Site.Params.disqusShortname }}';`. The curly braces will allow you to insert custom logic or like in your case parameters into your template.

I did it that way in one of my own themes (which is a work in progress) but you could take a look at the [source code](https://github.com/digitalcraftsman/hugo-cactus-theme/blob/dev/layouts/partials/disqus.html#L4)

**Comment by digitalcraftsman** [comment]
Is this still an issue?
