### ISSUE TITLE
Page.Menus is empty when accessed from a shortcode.

### ISSUE THREAD

**Issue by vjeantet** [spf13/hugo#1229]
I tried to write a shortcode to display the children pages...

code in my shortcode  : 
```
{{ printf "%#v" (index .Page.Menus "main").Children }}
```
it displays ```hugolib.Menu(nil)``` 

But if i use the "same" code in a template like ```{{ printf "%#v" (index .Menus "main").Children }}```

it displays ```hugolib.Menu{(*hugolib.MenuEntry)(0xc2084afb90), (*hugolib.MenuEntry)(0xc2084af290), (*hugolib.MenuEntry)(0xc208486510), ....```

**Comment by bep** [comment]
This is a little like the story about the chicken and the egg. Your use case _may_ be solvable, but once we fix that there will be questions about _my shortcode on the page doesn't show up in the shortcode_ which will travel fast into some cyclic object graphs.

And what you try to do doesn't sound like what shortcodes were written for.

I may figure a way to print an ERROR when calling .Page.Content and .Page.Menus, to improve the usability, but that will not fix your problem.

**Comment by vjeantet** [comment]
Thanks @bep !

**Comment by vjeantet** [comment]
Is there a way to pass a variable or a context to a shortcode ?
I really need to get access to .Site or CurrentNode/Page with Menus to iterate over it.

I trying to code a {{%children-page%}} shortcode which will print all "sub pages" as a list...

**Comment by vjeantet** [comment]
i would like to create some shortcode to display children-pages or sibling-pages as i did here : http://vjeantet.github.io/hugo-menu-show/emails/serversetup/mail-server-testing/imap/

**Comment by bep** [comment]
Shortcode arguments are value types only.

**Comment by bep** [comment]
One thought:
If MenuEntry for page menus had a reference to the page it belongs to, would that solve your problem?

**Comment by vjeantet** [comment]
If i can access Menus from a shortcode, Yes

**Comment by bep** [comment]
That is a no. But I do not understand why it need to be a SC.

**Comment by vjeantet** [comment]
some times, i need to display the children pages at the bottom of the page, and some times, in the middle of the page.
Today i coded the children-page into the template itself, so there is not flexibility to position the list of page where i want in the content.

And when i change the theme, i have to change it.

This kind of usecase is close to want we can find in the atlassian'wiki (confluence) thanks to their macro you place in the page content.

**Comment by bep** [comment]
OK, then you need a fix for the issue in the topic title.

**Comment by vjeantet** [comment]
Not sure to understand ... (my english is not that good)
You want me to create a new issue as a "feature request" ?

**Comment by bep** [comment]
No, this is the issue that needs fixing. By someone.
