### ISSUE TITLE
Add option to disable Blackfriday LaTeX style dash parsing - HTML_SMARTYPANTS_LATEX_DASHES

### ISSUE THREAD

**Issue by PuffinBlue** [spf13/hugo#1231]
Issue added as requested: http://discuss.gohugo.io/t/option-to-disable-latex-style-dash-parsing/1371.

Brief recap:

Hugo offers a number of options for adjusting Blackfriday.

One that seems to be missing is disabling LaTeX style dash parsing. Taken from the Blackfriday docs:

>LaTeX-style dash parsing is an additional option, where `--` is translated into `–`, and `---` is translated into `—`. This differs from most smartypants processors, which turn a single hyphen into an ndash and a double hyphen into an mdash.

Could be implemented at the same time as #1220?

**Comment by bep** [comment]
Also see #1220
