### ISSUE TITLE
Livereload not working (for me) in OSX Yosemite

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1236]
```
Darwin bep-mac.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
```

**Comment by PuffinBlue** [comment]
I'm running Hugo 0.14 on OS X Yosemite with 14.3.0 kernel and not seeing this behaviour. Live reload is operating correctly in latest stable Safari, Firefox and Chrome.

Apologies for the 'works for me' but it may be at least somewhat helpful to know it's working here. If you'd like any more info as to my setup to compare to yours just ask.

**Comment by bep** [comment]
@PuffinBlue ... it does help ... on the morale.

I just arrived from Linux where everything worked smoothly ... to my new MacBook. I'm a heavy Hugo-user, so I gotta get it working for me. But I will fix it.

**Comment by PuffinBlue** [comment]
I installed via Homebrew and that's worked correctly for me. I'm guessing you might have different requirements for development but if you can get a Homebrew install working it might give a clue as to what's going wrong.

**Comment by bep** [comment]
I build from source, but I have also tested with the relased 0.14 binary. Doesn't work, either, but they behave sligthly differently:

Release: Detects first change and rebuilds/loads OK. The following changes are ignored.
Current dev: Detects first change, does not rebuild, but reloads browser.

**Comment by bep** [comment]
Duplicates #1053
