### ISSUE TITLE
Remove Accented Characters from URLs

### ISSUE THREAD

**Issue by hacdias** [spf13/hugo#1237]
Hi!

I'm trying to move my personal blog from Jekyll to Hugo but I'm having a simple (I think) problem. Hugo generates the URL like this "post/apresentação/" but I want "post/apresentacao" with everything escaped. 

How do I do that?

Thanks =D

**Comment by bep** [comment]
You have to use the latest Hugo 0.15 DEV (source) and set

`removePathAccents = true`

In site config.

If you search for accents in this project, you will find a long story.

http://discuss.gohugo.io/  is a better place for questions.

**Comment by hacdias** [comment]
Thanks.
