### ISSUE TITLE
 Non-content entry to a menu with a relative URL produces a rendering error 

### ISSUE THREAD

**Issue by abirger** [spf13/hugo#1239]
There is a bug in non-content menu implementation that results in a broken link to a file if a relative URL is used in a config file menu entry. For example, if the `config.toml` file looks as follows:
```
baseurl = "http://my_site.com"
CanonifyUrls = true
[[menu.extramedia]]
    name = "Presentation: Three Steps to Enrollment"
    url = "/media/enrollment-sessions.ppt"
    weight = -120
    identifier = "PowerPoint"
```
the rendered link to the .ppt file looks like

```
http://my_site.com/media/enrollment-sessions/index.ppt/
```
However, if the absolute URL is used instead of the relative one, the resulting URL is OK. i.e. 
```
baseurl = "http://my_site.com"
CanonifyUrls = true
[[menu.extramedia]]
    name = "Presentation: Three Steps to Enrollment"
    url = "http://my_site.com/media/enrollment-sessions.ppt"
    weight = -120
    identifier = "PowerPoint"
```
renders to 

```
http://my_site.com/media/enrollment-sessions.ppt/
```
Related thread in Hugo Discussion is [here](http://discuss.gohugo.io/t/non-content-entry-to-a-menu-rendering-error/1386).

**Comment by bep** [comment]
@spf13 - I think I'm gonna remove the transformation of the menu urls. It is a slightly breaking change, but it was a bad idea in the first place. People are smart enough to get the URLs correct. Agree?
