### ISSUE TITLE
Access Site or Page params from within content files / shortcodes

### ISSUE THREAD

**Issue by chha** [spf13/hugo#1246]
Hi,
I want to output self-defined Site or Page params from within a Markdown content file. Is there a shortcode (or another way) for this purpose?
Something like `{{< printvar myvar >}}`
Thanks.

**Comment by bep** [comment]
You have access to the page from the shortcode:

```
.Page.Params.myVar
```

Questions gets fastest attention at http://discuss.gohugo.io/

**Comment by chha** [comment]
I want to specify the variable/param name in the content file. So the "myVar"-part in your shortcode example should be somehow "dynamic".

**Comment by chha** [comment]
Found a solution.
```
{{ $v := $.Get 0 }}
{{ index .Page.Params $v}}
```
