### ISSUE TITLE
Posting into the past 

### ISSUE THREAD

**Issue by morriswinkler** [spf13/hugo#1263]
i have an issue with posting into the past 

```
---
Title:       "Nitro : A quick and simple profiler for Go"
Description: "Nitro is a simple profiler for you go lang applications"
Tags:        [ "Development", "Go", "profiling" ]
date:        "2014-06-19"
Authors:     "Bram de Vries"
Slug:        "nitro"
---
```

will be included in the list on my blog section but it won't build a directory with index under the slug any idea why that could happen ??

**Comment by dimo414** [comment]
I tried replicating this and I see the appropriate files being created.  Can you provide an example repo?  Or are you perhaps referring to #448 ?

**Comment by spf13** [comment]
If this is still an issue, reopen with more information
