### ISSUE TITLE
.WordCount not accurate for Japanese pages

### ISSUE THREAD

**Issue by RickCogley** [spf13/hugo#1266]
Hello - when I look at .WordCount results against an English page and a Japanese page, the count is correct for English of course, but incorrect for Japanese, returning a very small number. 

I assume it is counting words using spaces as the delimiter, but Japanese and other CJK languages are inherently space-less. This also causes trouble for search engines, as an aside. 

I am wondering if .WordCount could detect the language, and count characters for CJK language, instead of returning an incorrect number. 

Best regards,
Rick

**Comment by bep** [comment]
It can hardly detect the language, but should be able to use the `languageCode`.

**Comment by RickCogley** [comment]
Hi @bep, it's not straightforward since there are so many combinations, and no spaces. One would need a really large dictionary file of all possible combinations of kanji characters, and then run that against text to try to guess the number of words. You could not even guess what a "word" was, since sometimes what looks like a four-character combination is actually two two-character combinations. 

I think it is just better to stick to counting the double-byte characters and giving a count of those.

**Comment by RickCogley** [comment]
An interesting aside: today I was working on SEO or social partials, and discovered that the .languageCode var is used for the RSS feed, which in turn uses en-US for English, but ja for Japanese (not ja-JP). 

And that's not conducive to using for "locale" because: 

* Facebook og - uses underbar like en_US, ja_JP
* Schema.org - uses hyphen like en-US, ja_JP
* (Twitter card uses no locale)

What I ended up doing was to settle on the hyphen version in ``locale`` in site and page params, then use the replace function like ``{{ replace . "-" "_" }}`` to change to the underscore version, for Facebook og, as needed.

**Comment by bep** [comment]
@RickCogley one part of me just loves having a language guy like you on the team coming up with problems like these, the other part ...

**Comment by bep** [comment]
Reading what you say, I guess what we need here is to skip the discussion about what a word is -- and export a new method on page: `RuneCount`.

https://golang.org/pkg/unicode/utf8/#RuneCount
http://blog.golang.org/strings

**Comment by RickCogley** [comment]
@bep, hehe, "sorry". :-)
RuneCount, yes!, that would work, because we can check for locale then show either ``WordCount`` or ``RuneCount`` as appropriate.

**Comment by bep** [comment]
@RickCogley just to check: In my head it wouldn't make sense to include whitespace in that count, right?

**Comment by RickCogley** [comment]
@bep, no, I don't think we need whitespace counted. 

Japanese can use a normal ASCII space, and, there is a double byte space. Sometimes we use them in names: 

田中 太郎
田中　太郎

Those have a single byte space and a double byte space between the last and first names.

But this usage is pretty rare.

**Comment by bep** [comment]
Whitespace also includes newlines and tabs etc, so I think it would give a skewed count for small texts with lots of paragraphs. I will keep it as implemented.
