### ISSUE TITLE
<.PublishDate.IsZero>: PublishDate is not a field of struct type *hugolib.Node

### ISSUE THREAD

**Issue by hacdias** [spf13/hugo#1267]
Hi!

Last time I executed Hugo I didn't received the error above. But now I receive it. It points to this:

```
{{ if .PublishDate.IsZero }}...{{ end }}" />
```

That's strange because everything is rendered correctly. Bug (Hugo Static Site Generator v0.15-DEV BuildDate: 2015-07-08T21:47:16+01:00) ?

Thanks.

**Comment by hacdias** [comment]
Strange. I'm now receiving a similar error but for ".Type". The stranger is tha I receive the error, but the comparation is made and works where it should work.

``` <.Type>: Type is not a field of struct type *hugolib.Node in partials/header.article.html```

on

```{{ if eq .Type "post" }}...{{ end }}```

**Comment by bep** [comment]
PublishDate and Type are fields on Page. So calling it on the home page Node (or a taxonomy Node) will create the error above.

If you have a template used for both page and node:

    {{ if .IsPage }}{{ if .PublishDate.IsZero }}...{{ end }}{{ end }}

**Comment by hacdias** [comment]
Thank you. =D
