### ISSUE TITLE
Template handling for dates in custom permalinks

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#1277]
As discussed in [this forum post](http://discuss.gohugo.io/t/creating-list-view-for-custom-permalink-solved/1352), it would be nice if Hugo integrates an easy way to handle templates for dates in custom permalinks.

If the custom permalink looks like this

```toml
[permalink]
    posts = ":year/:title"
```

I want to list all posts of a year (which could be extended for months and days) under `example.com/2015/`. Therefore I  would like to see a supported folder structure like `layouts/:year/templateName.html`.

The solution of the forum post requires the ***manual*** creation of a taxonomy with the year (`"2015"`, `"2016"` and so on) and a corresponding template folder at `static/<yearOfTheTaxonomy>/templateName.html` for each year.

**Comment by bep** [comment]
Only year?

```
:year the 4-digit year
:month the 2-digit month
:monthname the name of the month
:day the 2-digit day
:weekday the 1-digit day of the week (Sunday = 0)
:weekdayname the name of the day of the week
:yearday the 1- to 3-digit day of the year
```

**Comment by digitalcraftsman** [comment]
> I want to list all posts of a year (which could be extended for months and days)

The year is only needed for my purpose but as I mentioned (quote above) could this be extended. 

Your list of all possible elements in a permalink should be added of couse.

**Comment by bep** [comment]
This duplicates #448
