### ISSUE TITLE
{{< in code highlighting breaks page renderer

### ISSUE THREAD

**Issue by ahmedre** [spf13/hugo#1287]
hi,
thanks for writing hugo, i love it so far!  i apologize if this is already filed, but i searched and didn't see anything.

anyhow, i was trying to write a blog post about how i migrated to hugo, and my page breaks due to the presence of "{{<" anywhere in a code snippet.

an easy way to repro is:

`~~~bash`
`# this is a {{< comment`
`~~~`

in case it matters, i am using the hyde-x theme. the said error while building is:

`ERROR: 2015/07/19 Unable to locate template for shortcode 'comment' in page 2015-07-19-migrating-to-hugo-from-hexo`

thanks!

**Comment by bep** [comment]
Yes,

{{< and {{% are reserved keywords. You must "comment out" them to get them rendered.

```
{{</* myshortcode */>}}<p>Hello <strong>World!</strong></p>{{</* /myshortcode */>}}
```

**Comment by ahmedre** [comment]
thanks!

**Comment by luixxiul** [comment]
Is there any reason that shortcodes without markdown in [the document](//gohugo.io/extras/shortcodes/) are not commented out?

```
{{< myshortcode >}}<p>Hello <strong>World!</strong></p>{{< /myshortcode >}}
```

**Comment by bep** [comment]
All the doc shortcodes examples are commented out. They have to be to "be visible as plain text".

**Comment by luixxiul** [comment]
Ah, I see. My misunderstanding, sorry.
