### ISSUE TITLE
% characters are stripped out of URLs

### ISSUE THREAD

**Issue by donlzx** [spf13/hugo#1292]
The ```section``` variable passed into the pagination module is already URL encoded, 

https://github.com/spf13/hugo/blob/master/hugolib/pagination.go#L370

but the pagination URLs are encoded again using function ```URLizeAndPrep()``` in

https://github.com/spf13/hugo/blob/master/hugolib/pagination.go#L515

This yields incorrect URLs for pagination templates.

For example, a section name contains accent characters (añame) encoded as  ```a%C3%B1ame```, when processed by function ```URLizeAndPrep()```, will become ```ac3b1ame```, the ```%``` characters are stripped out.

And there may be other cases for non-English section names which are not handled correctly.

Removing the call to the ```URLizeAndPrep()``` function temporarily fix this issue for me, but the URL handling should be reviewed and should be consistent with URLs in Nodes and Pages.

**Comment by donlzx** [comment]
It turns out that this issue is not limited to the pagination module.  The issues is with the ```UnicodeSanitize()``` function stripping ```%``` characters in URLs:

https://github.com/spf13/hugo/blob/master/helpers/path.go#L78

**Comment by bep** [comment]
This precedes my time with Hugo. @spf13 might now why % are stripped?

**Comment by spf13** [comment]
I just filtered out any character that may be an issue as part of a filename in any os, even some that were ok in urls. It seems innocuous enough to include this back in.
