### ISSUE TITLE
Sitemap.xml should include nodes, as well as pages

### ISSUE THREAD

**Issue by dimo414** [spf13/hugo#1303]
It could be a configuration setting if necessary, but currently sitemap.xml is missing potentially a large portion of a site, because it doesn't include node pages like tags and lists.

**Comment by dimo414** [comment]
Is there a list of node pages somewhere [`_default/sitemap.xml`](https://github.com/spf13/hugo/blob/be45399cba0a47910db7a142e1574a9da1534713/tpl/template_embedded.go#L73) can access?  I can try to fix this if the necessary data already exists.

**Comment by bep** [comment]
No. And I think that is a problem that needs to be solved first. There are related issues.

**Comment by spf13** [comment]
I think we need to rethink how we approach nodes from the ground up as the current implementation is proving to have a few flaws with it.

**Comment by bep** [comment]
Will be handled in #2297.
