### ISSUE TITLE
Sitemap.xml forces homepage to priority zero, even if a different default is set

### ISSUE THREAD

**Issue by dimo414** [spf13/hugo#1304]
See http://gohugo.io/sitemap.xml for an example:

```
<url>
<loc>http://gohugo.io/</loc>
<lastmod>2015-07-21T10:00:00+00:00</lastmod>
<priority>0</priority>
</url>
```

The homepage priority is always 0, even if a different value is set in the config file, e.g.:

```
[sitemap]
  priority = "0.5"
```

(As an aside, the [sitemap](https://github.com/spf13/hugo/blob/master/hugolib/sitemap.go) config setting is not documented anywhere, the configuration page mentions it but doesn't define it).

**Comment by bep** [comment]
As an aside: Documentation fixes are always welcome.

I didn't even know there were a sitemap config :=)

**Comment by dimo414** [comment]
Once I have better understanding of what it's supposed to do, I'm happy to post a documentation update.  For now my understanding consists solely in what I've grepped out of the codebase, so I was hesitant to do so.

**Comment by dimo414** [comment]
Posted https://github.com/spf13/hugo/pull/1332 to improve the sitemaps docs.

**Comment by aureooms** [comment]
This has popped up again in recent versions.

**Comment by moorereason** [comment]
@aureooms, then open a new issue.  Please don't comment on issues that have been closed for a year.
