### ISSUE TITLE
Parentheses in title tag not processed correctly

### ISSUE THREAD

**Issue by Jos512** [spf13/hugo#1305]
Perhaps by design, but this Markdown code:

`Then we use [Output.WriteLine()](/output-writeline/ "Learn more about Output.WriteLine()") to output the generated string.`

Is generated by Hugo v0.14 as:

> Then we use Output.WriteLine()”) to output the generated string.

Removing the parentheses in that are placed in the `title` tag like this:

`Then we use [Output.WriteLine()](/output-writeline/ "Learn more about Output.WriteLine") to output the generated string.`

Generates correctly:

> Then we use Output.WriteLine() to output the generated string.

**Comment by bep** [comment]
I'm not sure I understand this ... but assuming you are using Blackfriday, that library is to blame.

Could you open an issue at

https://github.com/russross/blackfriday

**Comment by Jos512** [comment]
Ah okay, I see that this issue is already reported at blackfriday (if that's what I use): [Link parsing doesn't correctly match URLs when they include brackets #116 ](https://github.com/russross/blackfriday/issues/116).
