### ISSUE TITLE
Template not rendered when front-matter set a layout param

### ISSUE THREAD

**Issue by vjeantet** [spf13/hugo#1306]
My content file path is content/post/test.md
When i set a ```layout = "abc"``` in its front-matter, hugo raises an error as :

```
ERROR: 2015/07/28 Unable to render [post/abc.html _default/abc.html theme/post/abc.html theme/_default/abc.html]
ERROR: 2015/07/28 Expecting to find a template in either the theme/layouts or /layouts in one of the following relative locations [post/abc.html _default/abc.html theme/post/abc.html theme/_default/abc.html]
````

I was expecting to see hugo to failback using the /themes/THEME/layouts/_default/single.html template.
as explained in [documentation](http://gohugo.io/templates/content/#single:05301946b75cb988bc2be8549079b4fa)

Not that if i replace the ```layout = "abc"``` with ```type = "abc"``` in front-matter, it works.

**Is that an issue, or a misunderstanding from my side ?**

**Comment by bep** [comment]
What OS are you running?

**Comment by vjeantet** [comment]
Mac Osx

**Comment by vjeantet** [comment]
This change may resolve the issue issue : 
https://github.com/vjeantet/hugo/commit/f3f5a3a35a47274727cea7084f3366f367154d29

**Comment by bep** [comment]
Me, too. OK, then I cannot reproduce your issue. Just tested by putting `layout: foo` into a page and rebuild using a theme -- the single template is picked up just fine.

I'm not saying you're not having a problem, just that I don't understand it.

**Comment by vjeantet** [comment]
ok @bep, I will share a full example.
I used casper theme, which one did you use ?

**Comment by vjeantet** [comment]
Ok i just saw it, this issue seems to be specific to  casper theme :(

Somewhere in index.html template, there is a ```{{ .Render "li" }}``` when i replace it with ```{{ partial "li.html" . }}```, everything is ok, no more errors....

**Comment by bep** [comment]
Hmm ... that doesn't make much sense ... and that is connected to having a layout in front matter?

**Comment by vjeantet** [comment]
Yes.
You can reproduce error with this repo https://github.com/vjeantet/hugo-test-site
