### ISSUE TITLE
BaseURL Error

### ISSUE THREAD

**Issue by x0054** [spf13/hugo#1308]
Hi,

I am new to Hugo. I installed it on OS X and followed the Hugo in 2 Min video. However, when compiling the page, I keep getting an error about base URL:

> BaseURL is not a field of struct type *hugolib.SiteInfo in ...

I tried half a dozen different themes, and I keep getting the same error. I am sure I am missing something, but I cant figure out what it is. Any ideas?

**Comment by bep** [comment]
Upgrade to Hugo version >= 0.14 and it should work.

`hugo version` should show you what you are at now.

In general, http://discuss.gohugo.io/ is a better place for questions.

**Comment by x0054** [comment]
I had 0.13, forgot to update brew. Ops, thanks!
