### ISSUE TITLE
Allow more error pages than (currently) only 404

### ISSUE THREAD

**Issue by rauhs** [spf13/hugo#1316]
Via: http://discuss.gohugo.io/t/how-to-create-custom-error-pages/755

Currently hugo only allows `404.html` in the `layouts/` directory to render. Any other error pages get ignored.

As proposed:
- Pick up any filename `/\d{3}.html/` in `/layouts/` and render them.

A comprehensive list of error code is at: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

Though, it's easier to do the regex approach.

An even more general approach could be to accept `*.html` and just render them. Not sure what implications that'd have.

**Comment by bep** [comment]
@rauhs what is the use case for this? What other HTTP error codes can happen in a static site?

**Comment by rauhs** [comment]
In our use case we still do javascript with some lua+nginx scripting to add some dynamic elements to the site. For instance, we realized an internal section of our docs only available to logged in (staff) users. Thus, you'd get a 403/401 (forbidden/unauthorized) if you are not logged in. Best would be to display a login page (or at least a link to a login page).

Though, I'm not sure it's necessary anymore:

I just created a `content/error` section and various `401.md`, `403.md` files that simply have a preamble of `layout="403"`. Then I can just have my custom error pages in `layouts/error/401.html` etc..

Maybe there is more general approach: Allow a config directive like `renderLayoutsDirs="errors", "customXYZ"` that simply takes all html files in those directories and renders them (just like `index.html` and `404.html` currently).

**Comment by dimo414** [comment]
I'll +1 @rauhs, though the layout workaround is reasonable.

**Comment by bep** [comment]
I think there is a use case for a flexible number of layouts on the root level -- there is a related issue about getting the nodes into some structure with front matter etc.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by rauhs** [comment]
Workaround is fine. Seems to have affected few number of users who'd want this feature.

**Comment by solutionroute** [comment]
I wish I'd seen this last year to lobby for the enhancement request as I'm currently implenting yet-another-workaround for a site. ;-)

While the workaround is reasonable it's a per-site workaround requiring content files. It would be nice to have a more generalized approach that was at minimum usable for all `/\d{3}.html/ ` as @rauhs has suggested or `*.html` in /layout. 

The most common use case, one I run into all the time, is 401 - Unauthorized.  It's not an uncommon site request to have a "private" section - a file area for staff or members or family or what-have-you. It would be nice to be able to ship with a template package a 401.html much the way we do with 404.html. 

Likewise with 403.

Template writers could optionally include content. On a 404 page in addition to a menu listing a site may wish to include a help desk number. On a 401 Unauthorized page content might direct the site user to how to obtain a password.

```
/layout		/content (theme specific potentially optional)
401.html		_401.md
403.html		_403.md
404.html		_404.md
index.html	_index.md # hey, we do this now :-)
```
With that support in hand a theme writer (or Hugo documentation writer) may be encouraged to include usage notes for common web servers. Using Caddy as an example:

> In order for your website to respond with custom error pages you'll need to configure your webserver accordingly; complete information on how to do this should be obtained from the webserver documentation. Example configurations for [Apache](#) | [nginx](#) | [lighttpd](#) | [Caddy](#):

### Caddy [docs](https://caddyserver.com/docs/errors)
```
yoursite.com {
	errors {
		401 401.html
		403 403.html
		404 404.html
	}
}
```
### nginx [docs](http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page)
```
error_page 401	/401.html;
error_page 404 	/404.html;
```
The plus side for this expansion of generated content in /layout - template designer job is easier, user gets NNN.html files generated, easy configuration and no (but optional) content to create.

**Comment by cmod** [comment]
Just adding my vote for better handling of error pages beyond 404. Setting up a 401 template and was completely thrown by the fact that Hugo wasn't automatically treating the 401.html file in the same way it treats the 404.html.

**Comment by retifrav** [comment]
> What other HTTP error codes can happen in a static site?

Here's an example for `401`. If I have some paths protected with Basic authentication in NGINX like this:

``` nginx
# ...
error_page 401 /401.html;

location /secret-stuff {
    try_files $uri $uri/ =404;
    auth_basic "Speak, friend, and enter";
    auth_basic_user_file /etc/nginx/.htpasswd;
}
```

then if user will hit Cancel on authentication dialog, he will get `/401.html`, which I, like others here, would like to have templated the same way as `/404.html` is.

The `403` code can also happen, though more rarely (*due to missing `.htpasswd`, for example*).
