### ISSUE TITLE
Number in front matter is an int64. substr requires int

### ISSUE THREAD

**Issue by mkolosick** [spf13/hugo#1317]
A number defined in the front matter is an int64. `substr` in the go template requires an int.

Example front matter:

```
+++
rating = 4
+++
```

Example template
```
{{ substr "hello" 0 .Params.rating }}
```

The error given is `wrong type for value; expected int; got int64`

**Comment by tatsushid** [comment]
It is fixed at 51cabe6fafe5b18ce27962b7ec469f69fd5e2229. Please try the tip of the repository.
