### ISSUE TITLE
Ignore delimiter strings in values

### ISSUE THREAD

**Issue by gauntface** [spf13/hugo#1320]
If I use the following in my yaml:

    permalink: "/updates/2011/06/HTML5-Libraries---Late-June.html"
    ---

I get the following error:

    "Errors reading pages: Error:frontmatter delimiter must be followed by CR+LF or LF but those can't be found at filepos ..."

It's basically erroring at the '---' in the permalink, is there a way to escape the value?

**Comment by tatsushid** [comment]
I sent a PR to fix it
