### ISSUE TITLE
How to use date as path for files?

### ISSUE THREAD

**Issue by glitchesnetwork** [spf13/hugo#1324]
Hello, I'm trying to port over my wordpress blog while not breaking my current URL structure in wordpress. For example, consider the following blog post:

**http://mysite.com/2015/08/04/hello-world**

I do not want to create my folder directory structure the same way the URL is created. Instead I want to have my own structure like so:

```
- content
  - personal
    - hello-world.md
 - writtings
   - some-writing.md
```

**Questions:**

1) How do I accomplish this?

2) I might want to move to the more natural way of displaying building my urls; like they are in my file system. Is there a way to have hugo output a file into multiple paths so I do not break old urls?

ie: **2015/08/04/hello-world** and **personal/hello-world**

3) Perhaps there is a simpler way and have url redirects from an old path to the new path that search engines would pick up? All I know is of meta-refesh but I don't think that is the best way.

Thank you!

**Comment by bep** [comment]
See http://gohugo.io/extras/permalinks/

Also see http://gohugo.io/content/organization/

For the other question, see alias in the documentation. 

In general, though, http://discuss.gohugo.io/ is a better place for questions.
