### ISSUE TITLE
.deb file has no depends, breaks apt.

### ISSUE THREAD

**Issue by ftpd** [spf13/hugo#1325]
When I'm trying to add hugo .deb package into my internal deb repository, it breaks apt. apt-get update has the following error:

E:Problem parsing dependency Depends 
E:Error occurred while processing hugo (NewVersion2) 
E:Problem with MergeList /var/lib/dpkg/status 
E:The package lists or status file could not be parsed or opened.

**Comment by thagabe** [comment]
I don't think this is hugo's fault it could either be the way you packaged the deb or ubuntu trying to update hugo even though it doesn't have dependencies or should be connected to the apt-get update since no ppa is involved.

**Comment by ftpd** [comment]
It's not my own package, I'm using .deb provided by @spf13 (https://github.com/spf13/hugo/releases) and _this_ .deb isn't created properly, so I've decided to submit bug report.
I've put package inside my company's internal repo, no ppa is needed for this (as our hosts use this internal repo directly).

**Comment by thagabe** [comment]
Oh right it seems like it is broken. Let's see if we can make enough noise so @spf13  can hear us.

**Comment by jzmp** [comment]
I could install the .deb for amd64 with dpkg without any errors. Beside this, the Depends field is optional in .deb files.

**Comment by ftpd** [comment]
Yes, I didn't have errorr when installing via dpkg. The problem occurs after adding this .deb into a repository and trying to use apt.

**Comment by jzmp** [comment]
Mmh, did you run `dpkg-scanpackages` in your internal repository (and `apt-get update` of course) before installation? It seems more like an error with apt-get than the hugo .deb file.

**Comment by anthonyfok** [comment]
For what it's worth, I am slowly beginning to package Hugo and its dependencies for Debian.
([Debian Bug #798418: Intent-to-Package: hugo -- Fast and flexible Static Site Generator written in Go](https://bugs.debian.org/798418))
While some of the dependent libraries were already packaged by other Debian developers, there are still a dozen or two dependencies to go.

Meanwhile, The Debian Go Packaging Team has recently released a very helpful tool called `dh-make-golang` (https://github.com/Debian/dh-make-golang) which automates much of the Debian Go package creation process, so hopefully an official Debian package for Hugo will appear in Debian and Ubuntu soon, say in two months?  :-D

**Comment by ftpd** [comment]
Ok, so let's close the issue for now, I'll wait for the 'official' release.

**Comment by anthonyfok** [comment]
Follow-up:

Hugo has been available as an official Debian and Ubuntu .deb package since 2016-01-11.

See:
* https://packages.debian.org/search?keywords=hugo
* http://packages.ubuntu.com/search?keywords=hugo

See also discussion at https://discuss.gohugo.io/t/please-maintain-a-ppa-for-debian-folk-debian-ubuntu-elementary-etc/2946 about future plan of a Hugo PPA.
