### ISSUE TITLE
substr slicestr template func and unicode issue

### ISSUE THREAD

**Issue by benzwu** [spf13/hugo#1333]
{{ $cap := substr "ĀĀĀ" 0 1}}
    {{ $cap }}

result

    �

slicestr produce similar result

**Comment by tatsushid** [comment]
Fixed in my local repository. I will send a PR later

**Comment by benzwu** [comment]
super! thanks

**Comment by bep** [comment]
oh, I didn't see that you already have a fix, @tatsushid

**Comment by tatsushid** [comment]
@bep no problem. The commit is the same I did. Thanks!
