### ISSUE TITLE
Documentation update for nil in template function where

### ISSUE THREAD

**Issue by benzwu** [spf13/hugo#1341]
This fix is not reflected back to documentation

>`where` template function's internal condition check function always
returns `false` when a target value doesn't exist or it's nil value but
this behavior makes it difficult to filter values which doesn't have a
particular parameter.

>To solve it, this adds nil value comparison to the function.
`where Values ".Param.key" nil` like clause can be used for the case
above.

>Only "=", "==", "eq", "!=", "<>", "ne" operators are allowed to be used
with `nil`. If an other operator is passed with `nil`, the condition
check function returns `false` like before.

Fix [#1232](https://github.com/spf13/hugo/issues/1232)

I can update and submit PR for this. Is there any documentation writing guideline?

From http://discuss.gohugo.io/t/template-function-where-with-boolean-and-operator-with-not-set-params/1539/2

**Comment by bep** [comment]
No writing guideline (we need one ...), just try to follow whats already there. This is would be so useful/important that it needs its own headline, I think.

**Comment by benzwu** [comment]
the patch is not applied in current 0.14 release. So should wait for release 0.15?

**Comment by benzwu** [comment]
https://github.com/spf13/hugo/pull/1349
