### ISSUE TITLE
Documentation update for relativeURLs configuration /extras/urls/

### ISSUE THREAD

**Issue by benzwu** [spf13/hugo#1342]
Documentation need explain relativeURLs at /extras/urls/

function highlight: for browsable local copy

**Comment by anthonyfok** [comment]
Reminder to self (and others): This is in addition to the one-line doc in docs/content/overview/configuration.md in #1145.

**Comment by anthonyfok** [comment]
Hope to find some time to do it soon, hopefully before tomorrow, but if anyone would like to contribute, you are more than welcome to go ahead and make a pull request!  :-)
