### ISSUE TITLE
template function: passing sub result to slicestr

### ISSUE THREAD

**Issue by benzwu** [spf13/hugo#1347]
{{ substr .Title 0 (sub (len .Title) 1) }}

got this error

    executing "theme/_default/list.html" at <1>: wrong type for value; expected int; got int64

from http://discuss.gohugo.io/t/template-list-of-content-adding-s-to-section-name-as-page-title-title/1547

**Comment by bep** [comment]
What Hugo-version did you test with? I'm pretty sure this was fixed at some point recently.

**Comment by bep** [comment]
See https://github.com/spf13/hugo/commit/51cabe6fafe5b18ce27962b7ec469f69fd5e2229

**Comment by benzwu** [comment]
>Hugo Static Site Generator v0.15-DEV BuildDate: 2015-08-08T21:02:13+07:00

My bad. I copied the wrong line. It was not substr, It was slicestr.

Checked the source,

the int conversion applied to substr but not slicestr

```
	var start, length int
	toInt := func(v interface{}, message string) (int, error) {
		switch i := v.(type) {
		case int:
			return i, nil
		case int8:
			return int(i), nil
		case int16:
			return int(i), nil
		case int32:
			return int(i), nil
		case int64:
			return int(i), nil
		default:
			return 0, errors.New(message)
		}
	}
```

**Comment by bep** [comment]
OK, a pull request is welcomed! (put that toInt-func outside the method for starter).
