### ISSUE TITLE
Document lastmod

### ISSUE THREAD

**Issue by frank06** [spf13/hugo#1351]
I have two dates in my front matter:

```
+++
date = "2015-07-14T12:38:31-03:00"
updated = "2015-08-13T17:20:01-03:00"
```

In the template I can call  `{{ .Date.Format "January 2, 2006" }}` but `{{ .Params.updated.Format "January 2, 2006" }}` fails with `can't evaluate field Format in type interface {}`.  Or do I have to specify the type of `updated` somewhere?

**Comment by bep** [comment]
It seems undocumented, but you should use `lastmod` instead of inventing your own.

We have a discussion board more suitable for questions.

**Comment by frank06** [comment]
Thanks. But isn't that a bug?  I have two dates exactly the same: one works and the other doesn't. If I wanted to display `randomdate = "2003-08-13T17:20:01-03:00"`

**Comment by bep** [comment]
Yea... maybe. But that would be a bug in the TOML parser, see https://github.com/BurntSushi/toml

The thing is, for `date` and `lastmod` we *know* what to parse. For unknown cases, we take what the front matter parser gives us, in this case an `ìnterface{}´.

**Comment by frank06** [comment]
Sorry, I should ask this in the discussion board. But for the record, `{{ .Lastmod.Format "January 2, 2006" }}` does **not** print the latest modified date (I'm modifying the file now, and it prints yesterday's date).

**Comment by bep** [comment]
and what is the value of 

``
lastmod
```

in that file's front matter?

If not set, it inherits the `date`value. All this would be clear if documented. Hopefully. And as this is an open source project, pull requests are always welcome!

**Comment by frank06** [comment]
Thanks @bep . I understand now, `date` and `lastmod` are both casted to `Date` but you need to supply them. :+1: to add this to the docs!
