### ISSUE TITLE
Mixed style page (content + list)

### ISSUE THREAD

**Issue by hauleth** [spf13/hugo#1354]
Currently I'm writing Hugo site where I need to mix content and list of items. I can create static page with all content, but it was not as flexible as I want it. Is it possible to mark some content page to use `list.html` template?

**Comment by benzwu** [comment]
Add this in your front matter

    layout: "list"

This will use list.html template from

`/layouts/TYPE-or-SECTION/LAYOUT.html` 

or just any other custom template you might want

**Comment by hauleth** [comment]
That doesn't work (`Hugo Static Site Generator v0.14 BuildDate: 2015-08-12T15:18:51+02:00`) and is not documented. So either this is issue or feature request.

**Comment by benzwu** [comment]
check this out http://gohugo.io/templates/content/

**Comment by hauleth** [comment]
Ok. I got it. But description of thece variables should be also in http://gohugo.io/content/front-matter/

**Comment by benzwu** [comment]
good point 😄 

we need to consolidate all variables into one easy too check documentation
