### ISSUE TITLE
Create alias from .URL to .RelPermalink 

### ISSUE THREAD

**Issue by hanwentao** [spf13/hugo#1355]
Why the variable for relative URL is named `.RelPermalink` for a page, but `.URL` for a node?  Any plan to unify this strange naming?

**Comment by tiramiseb** [comment]
I have the same concern. I am creating a multilingual website and wanted to make direct links between pages in different languages, to switch the current page's language easily. With the same name, templates would be simpler...

**Comment by bep** [comment]
I'm fairly new to this project, so I can only guess to what's the difference is (the permalink is more ... permanent?). @spf13 may chime in with a history lesson.

But even if `.RelPermalink` may be *more*, it is also an `URL`, and me too like symmetry.

There is also `Permalink`, but I guess it would make sense to create an alias func from `URL` to `Permalink`.

Agree, @spf13 ?

**Comment by tiramiseb** [comment]
> I guess it would make sense to create an alias func from `URL` to `Permalink`.

A alias to `.RelPermalink` would be great. Not to `.Permalink`.

I'm also fairly new (I started using Hugo yesterday), but as I understood the documentation `.Permalink` include the hostname, `.URL` and `.RelPermalink` exclude it.

**Comment by tiramiseb** [comment]
An alias would allow to write `{{ .URL }}` instead of:
```
{{ if .IsPage }}{{ .RelPermalink }}{{ else }}{{ .URL }}{{ end }}
```

**Comment by bep** [comment]
@tiramiseb sorry, a little typo. Yes, as the URL on Node is relative, that should also be the case for the Page "alias". So you yes, you would be able to remove the IsPage conditional.

**Comment by bep** [comment]
I had a look at this, and -- sadly -- Page already have an URL, embedded through Node. It gets its value from the front matter. So overriding it with a func will create havoc, so I'll have to think more about this one.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
