### ISSUE TITLE
Certain markdown sequences not handled correctly

### ISSUE THREAD

**Issue by msaied93** [spf13/hugo#1356]
Here is a part of my input:

```
**`/usr`** : this folder contains other important folders

**`/usr`** : 

this folder contains other important folders such as
```

Here is the html produced by Hugo (v0.14):

```
<p>**<code>/usr</code>** : this folder contains other important folders</p>

<p><strong><code>/usr</code></strong> :</p>

<p>this folder contains other important folders such as</p>
```

The markdown in the first case is not rendered properly. I've [opened an Issue against blackfriday here](https://github.com/russross/blackfriday/issues/156); however, they cannot reproduce it.  Maybe it's a Hugo bug?

**Comment by bep** [comment]
I can not reproduce it in Hugo (OSX, Hugo 0.14-DEV), either, which must mean it is a weird platform related issue.

**Comment by bep** [comment]
No response = close this one. If it still persists as a problem, please open up an issue at Blackfriday:

https://github.com/russross/blackfriday
