### ISSUE TITLE
Add hasPrefix function

### ISSUE THREAD

**Issue by dvdsgl** [spf13/hugo#1366]
When rendering my large navigation hierarchy, I'd like be able to determine if a link is a child (or ancestor) of the current page.

For example, when rendering `/guides/`, I'd like to make sure navigation links to `/guides/foo` are highlighted. Conversely, when rendering `/guides/foo/bar`, I'd like to make sure the navigation link to `/guides/` is active.

With a `startswith` function, I could compare `.RelPermalinks` to determine page paternity:

```
// We're rendering /guides
{{ range .Data.Pages }}
    {{ if startswith .RelPermalink $.RelPermalink }}
        // This is a child page (e.g. /guides/foo/bar)
    {{ end }}
{{ end }}
```

For example, suppose this is my content structure that I'd like to render in a sidebar on every page:

```
A
    - A1
        - A1A
        - A1B
        - A1C
    - A2
        - A2A
        - A2B
        - A2C
B
    - B1
        - B1A
        - B1B
```

When visiting page B1A, I want to:
* collapse A, A1, and A2
* expand B and B1
* highlight B, B1, B1A

`startswith` would let me determine which nodes to collapse and which to expand.

`.Children` is not powerful enough because I am trying to compare the pages I am looping over to the current page being rendered, and I want arbitrary ancestry (e.g. `startswith "/a/b/c/d" "/a/b"` is a grandchild relation).

Is there any way to do this?

**Comment by dvdsgl** [comment]
`.Children` is not powerful enough because I am trying to compare the pages I am looping over to the current page being rendered, and I want arbitrary ancestry (e.g. startswith "/a/b/c/d" "/a/b" is a grandchild relation).

**Comment by dvdsgl** [comment]
For example, suppose this is my content structure that I'd like to render in a sidebar on every page:

```
A
    - A1
        - A1A
        - A1B
        - A1C
    - A2
        - A2A
        - A2B
        - A2C
B
    - B1
        - B1A
        - B1B
```

When visiting page B1A, I want to:
* collapse A, A1, A1
* expand B and B1
* highlight B, B1, B1A

`startswith` would let me determine which nodes to collapse and which to expand.

**Comment by tatsushid** [comment]
Now Hugo doesn't have a template function like `startswith` but how about using following

```
// We're rendering /guides
{{ range .Data.Pages }}
    {{ if eq (substr .RelPermalink 0 (len $.RelPermalink)) $.RelPermalink }}
        // This is a child page (e.g. /guides/foo/bar)
    {{ end }}
{{ end }}
```

It replaces `{{ if startswith .RelPermalink $.RelPermalink }}` to ` {{ if eq (substr .RelPermalink 0 (len $.RelPermalink)) $.RelPermalink }}`

**Comment by bep** [comment]
@tatsushid's workaround should work, but I guess it would be a useful addition. But maybe name it `hasPrefix` to indicate what Go strings func we will pass it on to.

**Comment by bep** [comment]
See #1243
