### ISSUE TITLE
Embedding Shortcodes Does Not Process Inner Markdown

### ISSUE THREAD

**Issue by matthewdolman** [spf13/hugo#1367]
My aim is to output sections of content within different containers, that themselves are within a grouping container.  At the moment the only way that I can see to do this is to embed shortcodes within shortcodes.  For example

Output HTML:

    <div class="container">
        <div class="box>
        	Box 1 content
        </div>
        <div class="box>
        	Box 2 content
        </div>
        <div class="box>
        	Box 3 content
        </div>
    </div>
    
I would have two shortcode templates

container.html:

    <div class="container">
    	{{ .Inner }}
    </div>

box.html:

    <div class="box">
    	{{ .Inner }}
    </div>
	
Then in the markdown I would have:

    {{< container >}}
    	{{< box >}}
    		Box 1 content
    	{{< /box >}}
    	{{< box >}}
    		Box 2 content
    	{{< /box >}}
    	{{< box >}}
    		Box 3 content
    	{{< /box >}}
    {{< /container >}}

The problem is with this set-up is that the content does not get marked down.  I have tried using % instead of < and that does not work either.  I can format the content as HTML and that workds fine, but it defeats the object of markdown.

Is this an issue or am I going about this in completely the wrong way?

**Comment by bep** [comment]
```
<div class="box">
    {{ .Inner }}
</div>
```
The `Blackfriday` markdown rendererer skips content wrapped with `div` and some other container types. Remove that and try again.

**Comment by matthewdolman** [comment]
Thanks for the reply, however I'm still having trouble.  I swapped out the <div>'s for <p>'s but still the problem exists that the {{ .Inner }} on the innermost shortcode is not being processed.

**Comment by bep** [comment]
Can you try to replace it with, say, Markdown?

See the list at

https://github.com/russross/blackfriday/blob/master/markdown.go#L105

**Comment by matthewdolman** [comment]
Please give me the idiot of the week award.  I was indenting the markdown and it was outputting it as code.

**Comment by andresmv** [comment]
@matthewdolman thank you for posting back with what the issue was, I was doing exactly the same thing! :)
