### ISSUE TITLE
Hugo crashes due to folder called "foo.zip" in my content directory

### ISSUE THREAD

**Issue by dvdsgl** [spf13/hugo#1371]
It tries to create a folder by the same name in `./public` but crashes with:

```
FATAL: 2015/08/21 mkdir /Users/david/.../public/foo.zip/: not a directory
```

**Comment by bep** [comment]
Works fine on OSX. What OS and what Hugo version do you use?

**Comment by dvdsgl** [comment]
Sorry, clearing my public folder fixed this – there was an actual .zip there from earlier, and perhaps this conflict caused the crash.
