### ISSUE TITLE
Conditionals for Hugo template language

### ISSUE THREAD

**Issue by JellisHeRo** [spf13/hugo#1374]
Can someone provide for me a list, or direct me to one, of conditionals for the Hugo template language? I haven't a clue if this is Hugo's template language or someone else's template language Hugo is simply using; but either way, I'd like to learn more about the conditionals.

**Comment by bep** [comment]
See doc at http://gohugo.io/overview/introduction/

For questions, http://discuss.gohugo.io/ is a better place.
