### ISSUE TITLE
Evaluate borrowed code snippets from Go's stdlib

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1375]
There are a couple of examples, this is one:

https://github.com/spf13/hugo/blob/master/source/lazy_file_reader.go#L132

These are cases where useful functionality exists in unexported funcs, and the only way to use them is to inline it.

Check if the existing reference is "good enough" for the license used or if we need more.

**Comment by bep** [comment]
According to@spf13:

>We should add a line to the top of the file saying "Portions Copyright (c) 2012 The Go Authors".

**Comment by moorereason** [comment]
I think `LazyFileReader.WriteTo` section in question can be refactored to use the stdlib:

```go
        return io.CopyBuffer(w, f, nil)
```

**Comment by moorereason** [comment]
Doh.  I should probably test an idea before commenting.  Using the stdlib makes it no longer "lazy."
