### ISSUE TITLE
Fix summary for Chinese and Japanese

### ISSUE THREAD

**Issue by siren93** [spf13/hugo#1377]
I saw the code "var SummaryLength = 70" in the hugo/helpers/content.go, but in my case, the summary contains all the text in the markdown file except tags(I didn't use the SummaryDivider).

**Comment by bep** [comment]
The auto summary has some word logic in it that may fail for languages where wordsplit by space doesn't make sense.

What language are you writing in?

/cc @RickCogley

**Comment by RickCogley** [comment]
thanks for the heads-up @bep

**Comment by siren93** [comment]
I use Chinese, Thanks.

**Comment by bep** [comment]
The summary i 70, but it tries to finish the sentence. What is the end-of-sentence marker in Chinese?

**Comment by siren93** [comment]
。, it equals "." in English.

**Comment by tatsushid** [comment]
It is the same with Japanese, U+3002 Ideographic Full Stop is used as end-of-sentence. U+3001 ideographic comma is used as comma in English.

These are most common characters in Chinese and Japanese but there are some more variation, e.g. full width and half width etc.
