### ISSUE TITLE
Any reasons why .Site.Social isn't documented? 

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#1380]
While reading the source code of Hugo fall over [this line of code](https://github.com/spf13/hugo/blob/04b4c996ac25fc0860cc24bb2e90d39404907345/hugolib/site.go#L120). As it looks like Hugo supports the attachement of social networks to `.Site.Social` by doing the following:

#### configs.toml

```toml
[social]
twitter = "spf13"
```

Inside a template I can access the value with `.Site.Social.twitter`. Is there any reason why this feature lacks documentation?

**Comment by bep** [comment]
There was a discussion about it when it was added -- kind of "this is unfinished work, but we'll add it anyway ..." Use the search function.
