### ISSUE TITLE
l6 problem with go-4.2 inux/amd64

### ISSUE THREAD

**Issue by mjfh** [spf13/hugo#1381]
Running make gave a 6l error. Splitting -ldflags arguments worked for me:

>diff --git a/Makefile b/Makefile
>index 823428f..de1ba9c 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -6,7 +6,8 @@
> 
> COMMIT_HASH=`git rev-parse --short HEAD 2>/dev/null`
> BUILD_DATE=`date +%FT%T%z`
>-LDFLAGS=-ldflags "-X github.com/spf13/hugo/hugolib.CommitHash=${COMMIT_HASH} -X github.com/spf13/hugo/hugolib.BuildDate=${BUILD_DATE}"
>\+LDFLAGS=-ldflags "-X github.com/spf13/hugo/hugolib.CommitHash=${COMMIT_HASH}" \
>\+	-ldflags "-X github.com/spf13/hugo/hugolib.BuildDate=${BUILD_DATE}"
> 
> all: gitinfo
> 

Kind regards
Jordan

**Comment by bep** [comment]
See https://github.com/spf13/hugo/pull/1365

**Comment by mjfh** [comment]
Hi Bjørn

It does not work on my system unless you split the -ldflags arguments so
you get the option twice (each one with a single "-X .." argument). I
have it not tested against go 1.5.

	System:		Debian/stretch
	Go version:	go1.4.2 linux/amd64
	Deb/package:	golang 2:1.4.2-3

Thanks for providing hugo - it is great.
Jordan

**Comment by bep** [comment]
It works fine with Go 1.5. I would blame the Go team for this -- we could maybe make it so it works for both, but we got enough other stuff to focus on -- and this can be a motivation to get people onto Go 1.5. And it still builds fine with 1.4.2 and 1.3, but not with the provided make file.

**Comment by mjfh** [comment]
On Thu, 27 Aug 2015 20:16:18 +0000
Bjørn Erik Pedersen <<notifications@github.com>> wrote:

> It works fine with Go 1.5. I would blame the Go team for this -- we
> could maybe make it so it works for both, but we got enough other stuff
> to focus on -- and this can be a motivation to get people onto Go 1.5.

You are right. I would not do anything - just keep it in mind in case
somebody cares. No many people would probably try to compile it on
Stretch at the moment (just a guess).

> And it still builds fine with 1.4.2 and 1.3, but not with the provided
> make file.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spf13/hugo/issues/1381#issuecomment-135540131>.
> 

Jordan
