### ISSUE TITLE
Euro sign not displayed with data-driven content

### ISSUE THREAD

**Issue by Jos512** [spf13/hugo#1383]
Hello,

I use a .csv file [data-driven content](http://gohugo.io/extras/datadrivencontent/) that looks like:

<pre>
Anonymous;$75;Well done!
Anonymous;$40;
Anonymous;$40;Nice!
Anonymous;$40;Reasonbly nice
Anonymous;$30;
Anonymous;€10;
</pre>

I include that in my theme with this:

```html
  <tbody>    
      {{ range $i, $r := getCSV ";" "backers.csv" }}
        <tr>
          <td>{{ index $r 0 }}</td>
          <td class="backers-amount">{{ index $r 1 }}</td>
          <td class="backers-comment">{{ index $r 2 }}</td>
        </tr>
      {{ end }}
  </tbody>
```

The output is wrong however; while the dollar sign is displayed correctly, the euro sign is dropped and replaced with �.

(Hugo v0.14)

**Comment by bep** [comment]
Could you check that your CSV file is in UTF-8?

**Comment by Jos512** [comment]
> Could you check that your CSV file is in UTF-8?

Thanks for commenting. The file was saved in ANSI by Excel. Switching it to UTF-8 actually made the euro sign disappear from the .csv file source file and replaced with `x80`.

With both encodings the euro sign isn't shown in Hugo in my case.

**Comment by SchumacherFM** [comment]
I will have a look

**Comment by bep** [comment]
@SchumacherFM and your look revealed?

**Comment by SchumacherFM** [comment]
@Jos512 I've tried it with my own created CSV file ... and it worked. The EURO sign gets rendered correctly. Can you maybe provide me your CSV file?

**Comment by bep** [comment]
Closing this as an error in the file encoding.
