### ISSUE TITLE
Get list of files in directory

### ISSUE THREAD

**Issue by rcsenkbeil** [spf13/hugo#1388]
Is there any way to get a list of files in a directory? The use case for me is to be able to build a gallery based on all of the images in a specific directory. The methods I've seen so far have been to specify each individual file via data files or individual markdown files.

What I would prefer would be to have some sort of function to be able to get a list of files. E.g.

```
<!-- Get files by name such as 'picture.png' -->
{{ $filesInDir := files "./static/img/" }}

<!-- Produce img tags based on images in specified directory -->
{{ range $filesInDir }}
  <img src="/img/{{ . }}" />
{{ end }}
```

Does this already exist? Is this beyond the scope of Hugo? Just seems more convenient than specifying data entries, which would involve changing the data whenever you add/rename/delete a file.

**Comment by digitalcraftsman** [comment]
As far as I know does such function not exist in Hugo. But it's not out of the scope. Some would need to add this function the templates. And the idea with the image gallery is good. It could be a nice addition to one of my themes so that the users don't need to mess with the configs.

**Comment by bep** [comment]
In the upcoming Hugo 0.15 there is a new `readDir` template func that does exactly this.

See

https://github.com/spf13/hugo/blob/master/docs/content/meta/release-notes.md

The discussion forum is, however, a better place for questions.
