### ISSUE TITLE
Suggestion: add safeCSS for partials?

### ISSUE THREAD

**Issue by Jos512** [spf13/hugo#1390]
Hello,

I inline CSS in the head of my template like this:

```
<style>
  {{ partial "css-default.html" . }}
  
  {{ if not (eq .Section "") }}
    {{ partial "css-post.html" . }}
  {{ else }}
    {{ partial "css-page.html" . }}
  {{ end }}
  
  {{ partial "css-responsive.html" . }}
</style>
```

This triggers the `ZgotmplZ` value in the HTML code, caused by unsafe CSS content reached ([docs](http://gohugo.io/templates/functions/)). Using `safeCSS`, however, generates an error:

```
{{ partial "css-default.html" | safeCSS . }}
```

```
executing "theme/partials/head.html" at <safeCSS>: wrong num
ber of args for safeCSS: want 1 got 1 in theme/partials/head.html
```

Is it perhaps an idea to also allow `safeCSS` to work with partials?

**Comment by bep** [comment]
You could try it would the correct syntax. The types are slightly incompatible, so you need to convert the partial result to a string, I guess:

```
{{ printf "%v" (partial "css-default.html" . ) | safeCSS  }}
```

**Comment by Jos512** [comment]
Thanks Bep, that's insightful. With that code, it works. 

```
<style>
  {{ printf "%v" (partial "css-default.html" . ) | safeCSS  }}

  {{ if not (eq .Section "") }}
    {{ printf "%v" (partial "css-post.html" . ) | safeCSS }}
  {{ else }}
    {{ printf "%v" (partial "css-page.html" . ) | safeCSS}}
  {{ end }}
  
  {{ printf "%v" (partial "css-responsive.html" . ) | safeCSS }}
</style>
```

As far as I'm concerned, this Github issue can be closed since it's already possible.
