### ISSUE TITLE
Can an agency charge for Hugo's output?

### ISSUE THREAD

**Issue by dheerajbhaskar** [spf13/hugo#1391]
Hi Guys, I did read up on the GPLv2 and SimPL, but I was unsure about how I can use Hugo, so I'm going ask here.

We're an agency making apps and websites. I know Hugo is SimPL(similar to GPLv2), does that mean the output of Hugo, which is the site itself is also GPLv2 or SimPL? 

### Here are my questions
1. Can we charge for the output of Hugo i.e. the site itself?
2. If we cannot sell the output, can we have a service charge for the effort we put in in making the site for clients?
3. Do we have to make the code for the website i.e. output available to the client? (Whether the output comes under SimPl or GPLv2 will answer this question I suppose)

Please let me know if something wasn't clear.

**Comment by dheerajbhaskar** [comment]
Okay, a little more googling, gave more clarity. I just need a confirmation now. I shall try and answer my own questions, let me know if my understanding is correct.

From: http://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

> Activities other than copying, distribution and modification are not covered by this License; they are outside its scope. The act of running the Program is not restricted, and the output from the Program is covered only if its contents constitute a work based on the Program (independent of having been made by running the Program). Whether that is true depends on what the Program does. 

### Answers:

> We're an agency making apps and websites. I know Hugo is SimPL(similar to GPLv2), does that mean the output of Hugo, which is the site itself is also GPLv2 or SimPL?

Based on the above snippet from GPLv2 site, the output does not depend on Hugo, hence is not a derivative work and does not come under SimPL or GPLv2.

> 1.Can we charge for the output of Hugo i.e. the site itself?
Yes. 

I'm guessing even if it was GPLv2, we could've charged for the site, but only had to make its source availabe.

> 2.If we cannot sell the output, can we have a service charge for the effort we put in in making the site for clients?

You can always charge for your services, essentially you're paid for your work.

> 3.Do we have to make the code for the website i.e. output available to the client? (Whether the output comes under SimPl or GPLv2 will answer this question I suppose)

We're not required to, given the output doesn't come under GPLv2 or SimPL

**Comment by bep** [comment]
I'm not a lawyer, but in my eyes these questions gets into play once you start to include Hugo binary and or source code into your product (you are building your own CMS, for instance, and using the Hugo core to do the heavy lifting).

The output of `hugo` command is plain HTML -- *your* HTML. But again, I'm not a lawyer.

On a side note, Hugo is in the progress (slowly) to change its license to Apache.

**Comment by dheerajbhaskar** [comment]
Thanks for the confirmation. @bep 

Even if one builds a CMS, it falls into the loophole of hosting a site. So, using Hugo binary will not be considered distribution.

**Comment by bep** [comment]
The Apache 2, right.
