### ISSUE TITLE
Fix menu doc

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1393]
```
Additionally, there are some relevant functions available on the page:
IsMenuCurrent (menu string, menuEntry *MenuEntry ) bool
HasMenuCurrent (menu string, menuEntry *MenuEntry) bool
```

Also on node.

See

http://discuss.gohugo.io/t/confusion-regarding-proper-use-of-menus/1647/2

**Comment by LiaungYip** [comment]
This ASCII diagram would go a ways towards documenting the functions:

                              |  IsMenuCurrent()  | HasMenuCurrent() |
                              |                   |                  |
    └── Names                 |  ...............  | ....  TRUE ..... |
        ├── Starting with A   |  ...............  | ....  TRUE ..... |
        |   ├── Alana         |  ..... TRUE ..... | ................ |
        |   ├── Alfred        |                   |                  |
        |   └── Alice         |                   |                  |
        └── Starting with B   |                   |                  |
            ├── Blake         |                   |                  |
            ├── Brittany      |                   |                  |
            └── Bryan         |                   |                  |

Some usage examples would also help.

I'll look at this more tomorrow.
