### ISSUE TITLE
Hugo file server shouldn't list directory

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1400]
See 

http://discuss.gohugo.io/t/layout-for-subdirectory-in-section/1651

Maybe 404?

**Comment by arunk-s** [comment]
Hey, I can help on this issue. @bep Can you help me to get started ? I'm a little new around here. ;)

**Comment by bep** [comment]
@arunk-s have a look at this discussion, esp. the suggestion from Brad F:

http://grokbase.com/t/gg/golang-nuts/12a9yhgr64/go-nuts-disable-directory-listing-with-http-fileserver
