### ISSUE TITLE
Error when front matter section is commented out

### ISSUE THREAD

**Issue by SvenDowideit** [spf13/hugo#1401]
we have some text like:

```
$ docker inspect -f '{{.State.Pid}}' 1f1f4c1f931a
2989
$ docker inspect -f '{{.State.Pid}}' 12e343489d2f
3004
$ sudo mkdir -p /var/run/netns
```

in https://github.com/docker/docker/blob/master/docs/articles/networking.md

which has the metadata html commented out so it doesn't mess up the github rendering:

```
<!--[metadata]>
+++
title = "Network configuration"
description = "Docker networking"
keywords = ["network, networking, bridge, docker,  documentation"]
[menu.main]
parent= "smn_administrate"
+++
<![end-metadata]-->

# Network configuration

## Summary

...
```

it makes hugo exit/hang.

```
ERROR: 2015/09/04 Error while rendering page articles/articles/networking.md: template: __articles/networking.html:1024:29: executing "__articles/networking.html" at <.State.Pid>: State is not a field of struct type *hugolib.Page
make: *** [docs] Interrupt
```

**Comment by bep** [comment]
What 

- hugo version?
- OS?

**Comment by SvenDowideit** [comment]
v0.14 hugo, on linux and windows - There's one more detail I've found - it only happens when the frontmatter is surrounded by html comment stuff (yus, our devs didn't want the frontmatter to be visible in the github view.

(updating the original desc)

**Comment by bep** [comment]
Yes, I see what's happening ... It doesn't hang on my computer, but your document gives an error.

**Comment by SvenDowideit** [comment]
I'm going to implement a hugo  option to strip out stuff like that, so its kinda minor - but having garbage that makes hugo stop is sub-optimal :)

**Comment by SvenDowideit** [comment]
https://github.com/SvenDowideit/hugo/commit/f68a0121280bdf0658cfbb4c8e0c65a6e80ac5a4 implements the stripping out we were doing using `sed`

**Comment by SvenDowideit** [comment]
I was wondering if I could re-implement it using nested NewSectionReaders, but that was more intrusive than I was up to at the time.

**Comment by bep** [comment]
Duplicates #1428
