### ISSUE TITLE
watch=true in config should not trigger livereload

### ISSUE THREAD

**Issue by zonov** [spf13/hugo#1410]
I've built and deployed my site on a webserver. After that I got error message in console. It says that livereload.js is not available. 

![image](https://cloud.githubusercontent.com/assets/862521/9706372/d6d05806-54eb-11e5-8cf2-1fc80233c74c.png)

Command ```hugo``` does not have option --disableLiveReload like ```hugo server```. Is there other way to exclude livereload code if it is not desirable at the moment?

**Comment by benzwu** [comment]
livereload is embedded only from public folder generated with "hugo server -w" or "--watch"

Try to generate the htmls with just "hugo"

**Comment by zonov** [comment]
I have used just ```hugo```. But there was other reason. I placed ```watch = true``` setting in my config.toml file in purpose to avoid typing -w or --watch for ```hugo server``` command. But this affected not only ```hugo server``` command but and for just hugo too. I think ```hugo``` command can ignore this setting as well.

**Comment by benzwu** [comment]
@bep can we reopen this? `watch` (livereload embed) only honored if running in `server` mode. Currently command line already behave like that already.

**Comment by zonov** [comment]
```hugo version``` says: "Hugo Static Site Generator v0.14 BuildDate: 2015-09-05T21:32:33+03:00". As I know it is last version. It put livereload,js into builded files with ```hugo``` command if find watch=true instruction in config.toml file. Yes, I think you can reopen this.

**Comment by zonov** [comment]
Is here something I can help you with?

**Comment by benzwu** [comment]
@zonov I even haven't start learn go yet 😂 just as a hugo user here. Someone, maybe you if you want, can delve in the source code, patch it up and send a pull request.

**Comment by zonov** [comment]
@benzwu I'll try in couple of days
