### ISSUE TITLE
Add validation for alias

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#1418]
Following some tests related to the discussions at Issue #701, I came to realize that Hugo would happily create aliases (redirections) outside of the `public/` directory if a content page contains aliases that traverse up parent directories.  For example:

    aliases = [ "/some-page/", "../some-page-2/", "../../some-page-3/" ]

After a Hugo run, `some-page-2/` would be created in the same parent directory as `public/`, whereas `some-page-3/index.html` would be created outside of the web site source directory altogether.

At least Hugo v0.13, v0.14, as well as the current HEAD are affected.  (I did not test v0.12.)

**Comment by bep** [comment]
But this

- is still is the user him or herself who does this?
- still needs a web server that travels outside the content root, and even then it is to your own content ...

It needs some validation, but I'm not sure about the "High Priority".

**Comment by anthonyfok** [comment]
What I worry is a scenario where a naïve user tries out a sample Hugo-based website that he/she downloads from somewhere, and then blindly tries to build it with Hugo...

Worse, he/she runs Hugo as `root`...

Granted, the chances of that happening are slim, and probably a malicious attacker could only create/overwrite certain `index.html` or other `randomly-named.html` on the system.

So, I think it would qualify as a security issue, though probably not a "High Priority" one, so I have removed that label.

**Comment by anthonyfok** [comment]
Well, changing the bug title to a lukewarm "Add validation for alias" seems like hiding the problem, as it is indeed a security issue, even if mildly...
