### ISSUE TITLE
Sections Not Rendering?

### ISSUE THREAD

**Issue by rdegges** [spf13/hugo#1419]
Heyo,

I'm a bit new to Hugo, so I might be off here. I've built a new Hugo site that renders fine, but what I'm trying to do is create an archives page for my site (`/archives`). From the documentation, it appears the proper way to do this is via sections: http://gohugo.io/templates/list/

Specifically:

<img width="496" alt="screenshot 2015-09-09 23 54 40 2" src="https://cloud.githubusercontent.com/assets/90247/9782013/5ebae830-574e-11e5-9e1b-5ebbcc1ca4e1.png">

Anyhow: here's what I've tried so far:

1) I tried putting an `archives.html` inside of `mysite/layouts/section/archives.html`. This does not have an effect.

2) I've built my own theme, so I also tried creating `mysite/theme/rdegges/layouts/_default/archives.html`. This also does not have any effect.

3) I also tried `mysite/theme/rdegges/layouts/section/archives.html`, this also doesn't work.

What do I need to do to get an arbitrary template to render? Ideally, I'd like to make this work from inside my theme =)

**Comment by bep** [comment]
In general, questions gets faster response on http://discuss.gohugo.io/

**Comment by fedelibre** [comment]
@rdegges I think that I asked the same question in [this thread](http://discuss.gohugo.io/t/two-views-pages-for-the-same-content-type/1502/3). But I didn't find a solution

**Comment by bep** [comment]
OK, lets keep discussion in that thread.
