### ISSUE TITLE
No mention of CSV in extras/datafiles/ documentation ?

### ISSUE THREAD

**Issue by jygastaud** [spf13/hugo#1420]
Hi,

Documentation in extras/datafiles/ doesn't mention CSV as an allowed format in data/ folder.
So it assumes that we absolutly need to use "URL" (doc from Data-driven Content) to be able to get CSV value.

Is that correct ?

**Comment by bep** [comment]
Yes, that is correct. The /data is loaded into a map/dictionary, and I don't see the CSV fitting into that model.
