### ISSUE TITLE
Support HTML comments frontmatter

### ISSUE THREAD

**Issue by wenerme** [spf13/hugo#1428]
Something like 
```
<!---TOML
+++
title = "spf13-vim 3.0 release and new website"
description = "spf13-vim is a cross platform distribution of vim plugins and resources for Vim."
tags = [ ".vimrc", "plugins", "spf13-vim", "vim" ]
date = "2012-04-06"
categories = [
  "Development",
  "VIM"
]
slug = "spf13-vim-3-0-release-and-new-website"
+++
-->
```

Or

```
<!--- title : "spf13-vim 3.0 release and new website" -->
<!--- description : "spf13-vim is a cross platform distribution of vim plugins and resources for Vim." -->
<!--- tags :  ".vimrc", "plugins", "spf13-vim", "vim" -->
<!--- date : "2012-04-06"-->
<!--- categories :"Development", "VIM" -->
<!--- slug : "spf13-vim-3-0-release-and-new-website"-->
```

This is very important when content is not processed by hugo and display elsewhere directly.The frontmatter is very noise.

**Comment by bep** [comment]
A variation of the first would be good; no need to specify the "TOML".

**Comment by SvenDowideit** [comment]
There is a partial implementation of this in #1398 - in the Docker documentation we're using `<!--[metaData]>` ... `<![end-metadata]-->`

Should I extract it and make it configurable?

**Comment by wenerme** [comment]
Thanks @SvenDowideit I thinks there must have a way to do this, `<!--[metadata]> ... <![end-metadata]-->` is acceptable, as along as it can hide the metadata.but we should chose a good enough format that most people can accept.

**Comment by bep** [comment]
What is wrong with just:

```
<!-- -->
```
??

**Comment by SvenDowideit** [comment]
I think someone wanted to make it really obvious that this was the hugo
metadata, and not some other commented out section.

**Comment by wenerme** [comment]
```
<!-- -->
```

Is fine, maybe this should configurable ?

**Comment by bep** [comment]
We have too many config options as is. This should be a good old constant.

**Comment by wenerme** [comment]
So, just do it, people will get used to.

```
<!-- -->
```
Is not a format of front-matter, hugo will detect `<!--` and remove the wrap then pass to other front-mater ?

**Comment by moxiegirl** [comment]
`<!—[metadata] ...` is useful because it is clear why the comment is there.  This was suggested by one of Docker's contributors.  It would be useful to have other comments in Markdown that are carried into the HTML as HTML comments.  In tech docs, it is common for writers to leave comments in the source code like `<!--- We are keeping this in due to issu XXX -->` or `

**Comment by bep** [comment]
I think we can specify it like this to support any variant:

``
* A line preceding the front matter start ("+++" for TOML) that starts with "" is removed (and ignored) by the Hugo parser.
``

**Comment by SvenDowideit** [comment]
https://github.com/spf13/hugo/pull/1398/files#diff-f8b09d3e9ccc0204fe73f8480af394f4R85

I implemented the initial version using the Peek method that was already being used - that's not quite as robust for variable length

I was contemplating re-writing the frontmatter parser replacing the Peek's with http://golang.org/pkg/io/#NewSectionReader's

What do you think?
