### ISSUE TITLE
Check content for dead links during the generation

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#1430]
This optional feature could check if a link inside a document is and output a warning.

**Comment by bep** [comment]
This sounds out of scope. The only way to check dead links is to "try it" -- and that is too slow to be part of Hugo's build process.

**Comment by carlmjohnson** [comment]
I think we could add a separate subcommand for this, like `hugo test`. For the site I'm working on, I'd like to have a step that will check for broken links before deploying. I could do this by just building on localhost and running a link checker over that, but ISTM it'd be faster/more efficient if it were built into Hugo.
