### ISSUE TITLE
Allow pluralizing/inflecting from template

### ISSUE THREAD

**Issue by aktau** [spf13/hugo#1438]
First of: I'm very sorry if this either (1) already exists or (2) I'm stupid.

While the automatic pluralization that Hugo does is sometimes not helpful (see #344), sometimes it _is_ the desired state. For example, on my homepage, I have a list per section:

```go
  {{ range .Data.Pages.GroupBy "Section" }}
  <h2>{{ .Key | title }}</h2>
  <ul>
  {{ range .Pages }}
      <li>
        {{ .Render "li" }}
      </li>
  {{ end }}
  </ul>
  {{ end }}
```

Not only would I like the `.Key` to be capitalized properly, which I can do by piping to `title`, but I also would like it to be pluralized (in the same way that Hugo automatically does within sections).

Is it possible to add a `pluralize` and `singularize` filter?

I've tried looking in the `tpl/` subfolder in the source and on the website describing template functions and with Google, to no avail.

The desired state would thus be: `{{ .Key | pluralize | title }}`.

**Comment by bep** [comment]
No it doesn't exist. Yes it should be easy to add. Pull requests are welcome.

**Comment by aktau** [comment]
I know it's a trivial change, and would've done it if it weren't for an unfortunate situation at my current employer making it cumbersome to do so. If no-one does it in a few weeks, I might go ahead and move through the process.

Thanks for the quick reply!
