### ISSUE TITLE
Save data to "data/pages.json"

### ISSUE THREAD

**Issue by robotamer** [spf13/hugo#144]
How about saving all the data to json files.
These could be used for ajax calls from client site.
Could also help with i18 (Multi Language) etc

**Comment by oskarrough** [comment]
This would be a great feature! For the schema there's always http://jsonapi.org/ to look at.

**Comment by rhewitt22** [comment]
Creating a template that outputs JSON would be great in order to build a site index.  The index would be used for client-side search with something like lunrjs.

**Comment by digitalcraftsman** [comment]
There is some progress in this direction. See #1853.

**Comment by bep** [comment]
There is fairly good JSON support for this use case in Hugo now. Improvements to this is covered by other issues.
