### ISSUE TITLE
Execute Hugo from other Go program with flags

### ISSUE THREAD

**Issue by hacdias** [spf13/hugo#1445]
Hi!

I'm building caddy-hugo and Hugo it's going to be bundled with Caddy in that version so I need to some way to execute Hugo supporting the flags. Right now I'm just calling ```commands.Execute()``` but in that way I can't use the flags.

If I have a string with the flags as they will be set in the command line, how should I proceed to execute Hugo with them?

**Comment by bep** [comment]
Have no idea, but it might be an idea to ask this question at the Cobra project, too, because that's whats driving the CLI.

**Comment by hacdias** [comment]
@bep I was trying some things and I found out that ```commands.HugoCmd.ParseFlags([]string{"--baseUrl=https://teste/"})``` works. I think I can close the issue for now. Thanks anyway.
