### ISSUE TITLE
Get the Last-Modified date from the .md files 

### ISSUE THREAD

**Issue by robotamer** [spf13/hugo#145]
If we can get the Last-Modified date from the md files we can use that to setup fingerprinting to dynamically enable caching in the browser.

More info:
https://developers.google.com/speed/docs/best-practices/caching?csw=1

**Comment by bep** [comment]
This has been added with `lastmod` in front matter. I do not believe in using the content file's timestamp as an indicator for this -- that will lead to lots of surprises.
