### ISSUE TITLE
Brew install hugo

### ISSUE THREAD

**Issue by kevincrocker** [spf13/hugo#1452]
As per the main page, if we use brew, we should do a

brew install hugo
well, this is the error I get:

$ brew install hugo

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool

BTW, installing as root also fails politely saying I shouldn't install hugo as root, which is good advice! :-)

Since I just upgraded XCode, I hadn't started it to accept the licence. Once doing so everything installed just fine, but I thought you should know.

**Comment by dazuaz** [comment]
Just open Xcode and accept the agreement,

also run `brew doctor` and `brew update` before you try to install.

Hope it helps :)

**Comment by kevincrocker** [comment]
thanks, I got it to install after I fixed the Xcode license issue.
