### ISSUE TITLE
Support GitHub reference

### ISSUE THREAD

**Issue by wenerme** [spf13/hugo#1458]
Nowadays, people use to put there posts in github, github has simple and easy api to fetch these files.Hugo should consider support GitHub reference, include

* Repo reference
* Directory reference
* File reference

I'm new to hugo, but I implement this in my [simple blog platform](https://github.com/wenerme/tellets),the configuration look like this(write in php, WenerLove is my older name)

```
$plugins['github_repo']['repos'] = preg_split('#[\n\r]+#',<<<REPOS
WenerLove/blog
WenerLove/asp.net.SaySay/README.md
WenerLove/greedy_snake/README.md
WenerLove/java.blog/README.md
WenerLove/tellets/README.md
WenerLove/GTetris/README.md
REPOS
);
```

For [tellets/README](https://github.com/wenerme/tellets/edit/php/README.md) there is html commented front matter like this
```
<!-- title: Tellets README -->
<!-- category: Posting -->
<!-- tag: Project -->
<!-- date: 2013/12/7 -->
<!-- state: published -->
<!-- link: tellets -->
```

So if some one read from github will not feel confuse and noise, that's why I create #1428 ,this project is about 2 years ago, have no time to maintain.Hugo is good, hope it better.

Also hope hugo support 
```
<!-- more -->
```
Which means content above this will show in list, content bellow will show in detail, like I mentioned above in  [tellets/README](https://github.com/wenerme/tellets/edit/php/README.md), should I create another issues for this ?

**Comment by wenerme** [comment]
For current work around, I have to clone my [blog repo](https://github.com/wenerme/wener) and `ln -s ~/somewhere content` but not for trivial files. But sadly 
```
ERROR: 2015/09/25 Symbolic links for directories not supported, skipping
```

**Comment by wenerme** [comment]
I can understand hugo can not watch symbolic links, but I can not serve from symbolic links.

**Comment by wenerme** [comment]
How can I specify the content directory ?

**Comment by bep** [comment]
You post a lot of questions. Put those on http://discuss.gohugo.io/

If you by your initial post means that Hugo should fetch the content from a configured GitHub repo, that sound like a job that Git does wonderfully well today. 

If I misunderstood, please reopen.
