### ISSUE TITLE
Non-MD files in the content directory (like jpg's and png's) end up as html's

### ISSUE THREAD

**Issue by RubenN** [spf13/hugo#147]
When I put non-md files in the content directory, they should just be copied over (untouched!).
  
Now they end up as html's

**Comment by mrkishi** [comment]
Any updates on the custom processors, as well? It's an idea that also interests me. For instance, one could optimize images on build.

Honestly, I found the *content* folder somewhat misleading as it's not meant to hold arbitrary site content, but processable inputs.

Also, if we are to think them as *raw, unprocessed documents*, it makes sense that's the place we'd place related data, full resolution images and etc., as well. They would then be processed on build: charts generated, images resized and optimized, html generated. Of course, a pass-through processor is still a valid processor. :)

As not every file could (easily) have a front matter, @stou's file extensions idea seems like an acceptable solution for processor selection, if slightly magic. Some ideas of what may be possible:

- `/content/articles/lengthy-research.md`: Article.
- `/content/articles/lengthy-research/chart1.pngchart.json`: json to png charting.
- `/content/articles/lengthy-research/image1.optim.png`: image optimization.
- `/content/articles/lengthy-research/image2.optim-600x150.png`: image optimization and resizing.
- `/content/articles/lengthy-research/image2.png`: pass-through?

**Comment by spf13** [comment]
I like this idea, but @stou's file extension idea only allows for a single result from the process. What if I want to make a thumbnail, medium size and full size from a single image?

**Comment by mrkishi** [comment]
How about introducing the concept of external alternatives to front matter? Appendix, lol?

This could make things slightly more consistent: every input (to be processed) must have a front matter, either embedded (markdown's front matter) or external (stand alone yaml and toml files that select the processor?). On the other hand, it adds to the project complexitivity and, potentially, build time.

- `/content/articles/test.md`: embedded front matter.
- `/content/articles/test/image.png`: means nothing by itself.
- `/content/articles/test/image.toml`: what to do with `image.png`.

This could get annoying pretty fast, though. Another option would be to add the processing options to the pages' front matter:

- `/content/articles/test/image-{1,2,3}.png`: do nothing by themselves.
- `/content/articles/test.md`: embedded front matter saying *hey, include images 1, 2 and 3, using preprocessor x with arguments y and z.*

I think this could work, but it would limit our ability to process arbitrary files: they would to belong to an article. Perhaps on top of that there could exist support for stand alone `.toml` and `.yaml` files, that simply contain instructions for other files, similarly to the first suggestion but without the 1:1 toml/file relation.

**Comment by bguiz** [comment]
Think we might be getting a little side tracked here, with the discussion on preprocessing files. That's a nice to have for non markdown files, but for a first cut, I will be quite happy in *.md files are the only ones that are processed, and everything else just gets copied as-is.

Creating a rails or docpad style asset pipeline based on multiple file extensions is a nice to have, but I think simply being able to put images referenced in a markdown file in the same folder as the markdown file will aid authoring in Hugo quite a lot.

**Comment by jcw** [comment]
+1

**Comment by bjornerik** [comment]
+1 what bguiz says

**Comment by stou** [comment]
+1 I agree. The processing chain can easily be postponed

**Comment by bjornerik** [comment]
One note to he who implements the "copy files from content without processing" -- it would be very nice if static images/css could be treated as their cousins in the /static folder for livereloads (soft, not hard refreshes).

**Comment by spf13** [comment]
I'm 90% done with this today. 

Steve Francia
spf13.com
@spf13

**Comment by dcorb** [comment]
Glad to arrive to this issue and it's 90% ready! This improves the UX of writing complex articles.

I was thinking to have a developer blog with "demo.js" or "demo.css" per article or even JSON files .. so each article could be customized. Not only it would be useful for dev blogs.. also is a trend called "JavaScript Journalism", like you can see in some New York Times articles.

**Comment by gima** [comment]
+1
The current logic feels counter-intuitive. Some posts need assets, such as images. These images are, by their name, assets, and hence belong with the post. I shouldn't have to worry about where they are located as a result of rendering the website, but currently I have to. I have to either refer to them by their rendered path or use the static folder trick to mirror the post's directory structure, and place my assets there, afterwhich I can then refer to them in the post simply by their name.

This, again, is counter-intuitive. Not only for the extra work, but also for the fact that the filesystem already provides for a way for me to bundle things together that belong, together, by using directories. Now if I have to mirror this directory structure, I have broken the connection between the post and it's assets [in the filesystem], then during rendering Hugo rebuilds the connection, and as a result the outcome is the same as if Hugo just let me have my damn files in the post's directory and be done with it.

**Comment by spf13** [comment]
100% agree. Working on making it better.

**Comment by yml** [comment]
@spf13 are you pushing your work somewhere ? I would be very interested to see this being built. I have been working myself on thumbnailing pipeline recently and would be willing to contribute / adapt some of it to hugo.

**Comment by ivanjuras** [comment]
+1

**Comment by spf13** [comment]
It's in master. The foundation is there to handle specific file types
differently. CSV already has a handler as an example / prototype.

--
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by marcojakob** [comment]
+1 It would be awesome to be able to store assets next to the content files. 

As I've outlined in [File-Based CMS and Hugo as Static Site Generator](http://discuss.gohugo.io/t/file-based-cms-and-hugo-as-static-site-generator/914) it would be great to also allow `.toml` files as content instead of `.md` files.

**Comment by eduncan911** [comment]
@spf13 You stated the foundation is already in master.  Could we get an example of how to use it?

Out of all comments, @gima said it best: it is akward and the file system already provides me a way to organize with directories.  :+1: 

My current blog, started way back in 2002, has been through 3 serious "technology/generator" changes.  In doing so, and preventing broken links, I have a wide swath of existing static content next to posts and articles.  Things like:

    /blog/archives/2015-02-22-hello-world.aspx
    /blog/archives/images/hello-world.jpg
    /blog/2nd-overhaul-posts.html
    /blog/images/newer-images-and-thumbnails-here/...
    /current-version-at-root.html
    /images/different-format-images

And I have quite a few videos, PDFs and such lined up next to their posts.

I liked Octopress exactly for this, as I was free to create any directory and/or file I wanted anywhere, and it would be copied over in that exact place.  I will admit that Hugo's forced separation approach irked me for some time - and still does.  I haven't launched my new overhaul yet because of these restrictions - I don't want to separate 1000s of posts and content.  Asking me to break up my site for a migration is a deal breaker.

Octopress (aka Jekyll) allowed you to create your own structure - and it would only process files by their extension type.  `.html` files are treated differently than `.md` files.  Have a new `.adoc` type?  No problem, copy a plugin (or write your own) to process that file extension.

^- Hey, someone had to mention Octopress/Jekyll already does this in this thread (and kind of trains you to do this).

**Comment by bguiz** [comment]
@eduncan911 Yup, you're venting the very same frustrations that I have with Hugo, when I commented on this thread earlier: https://github.com/spf13/hugo/issues/147#issuecomment-71126819

> Think we might be getting a little side tracked here, with the discussion on preprocessing files. That's a nice to have for non markdown files, but for a first cut, I will be quite happy in *.md files are the only ones that are processed, and everything else just gets copied as-is.
> Creating a rails or docpad style asset pipeline based on multiple file extensions is a nice to have, but I think simply being able to put images referenced in a markdown file in the same folder as the markdown file will aid authoring in Hugo quite a lot.

Rather than whitelist a select number of file extensions which should get pre-processed, and error on everything else, I would much rather have a select number of extensions which get pre-processed, and have everything else simply pass through, by simply getting copied from the source folder to the destination folder.

I am currently using Hugo on a couple of static sites, but am still stuck on Docpad for my blog. I would very much like to switch that to Hugo too, but I am waiting for this issue to pan out, mainly due to me not wanting to copy images that are currently in the same folder as my markdown files into a separate parallel folder structure - it would simply be way too much tedious work!

@spf13 could we please get files extensions without a handler simply copied across?

**Comment by spf13** [comment]
Yes. I'll work on that this week.

**Comment by bep** [comment]
"I'm 90% done with this today."

This was January. I understand it's not uncommon in software development that the last 10% is the toughest  - but is it possible to get a realistic estimate? Should we remove this from the v.0.14 milestone?

**Comment by bguiz** [comment]
I'd really really like to see this feature make it into the next release,
can we please keep it in the milestone?

W: http://bguiz.com

**Comment by bep** [comment]
v0.14 is long overdue and we cannot release something that isn't there, but I'm not doing the release, so I wouldn't know.

**Comment by jbenet** [comment]
just ran into this problem. it's really annoying, particularly when using hugo as part of a pipeline for a bigger site.

**Comment by gour** [comment]
Let me just add that the other day I was playing with [Nikola](https://getnikola.com/) which allows to use code like this:

```
/path-to/content/post/hello-world.rst
/path-to/content/post/hello-world/image.jpg
```
and the image is referenced within the post with:

```
.. thumbnail:: image.jpg
                  :alt: Some alt-text
                  :align: center
                  :scale: 60        
                  etc.
```

Simple & clean way to keep images/assets along with posts...

**Comment by eduncan911** [comment]
Hello @Gour

Could you give us more details?

What version were you using? Latest from master?

Can you give/link to a full example?   I don't recognize :alt: :scale:.

Thanks!

**Comment by gour** [comment]
@eduncan911 I am speaking how one can tie one's assets (e.g. images) close to the post in [Nikola](https://getnikola.com/) static-site-generator, iow. it's **not** about Hugo, but example **how** it could the problem of tying images close to the post be solved within Hugo.

**Comment by eduncan911** [comment]
Oh, I didn't catch that.  Yeah, Octopress/Jekyll does as well.

**Comment by derekperkins** [comment]
This seems like a great place to hook in an image processing pipeline, which has two major stages I can think of:

 - Compression & Optimization
We could check for the availability of some commandline tools like optipng, jpegtran, etc and use them if they are available. If not, the user doesn't know the difference. The user could specify in their config file whether they want to enable processing.

 - Resizing & Cropping
As mentioned in #1014, it would be nice to provide this as an option. Off the top of my head, you could also use the config file in a similar fashion to WordPress to register specific file sizes that can be referenced elsewhere in the code. https://codex.wordpress.org/Function_Reference/add_image_size

This is obviously much more intensive than just generating html files, so it'd have to come with some sort of caching mechanism so it didn't have to copy and regenerate all the image files every single time.

**Comment by derekperkins** [comment]
The more I think about it, the more that seems a little intense for Hugo. While it would be super nice if it could fit the workflow, it may be more suited to a CI environment to go through and build all the right sizes on deployment. The only thing you lose by doing that is not being able to set the right width / height attributes inside your html tags.

**Comment by eduncan911** [comment]
This is not to address only images next to md files, but all file types.

We all agree that Hugo:

1) should not try to process files it doesn't know about in the /content
directory.
2) move all files it finds in /content over to that same directory in the
generated site, keeping the exact same structure.

E.g., side-by-side files:

/content/post/summer-fun/what-i-did-last-summer.md
/content/post/summer-fun/jet-skiing.png
/content/post/summer-fun/jet-skiing.mkv
/content/post/summer-fun/jet-ski-for-sale.zip

**Comment by spf13** [comment]
To everyone. I committed a generic file handler that simply places the files in the same path in the destination directory. This will enable people to place images and other files along side their content. There's still a bit more to do around this, but the fundamental issue / request in these 3 tickets is solved. It does need a bit of testing so I'd love everyone to check out head and play with it.

**Comment by eduncan911** [comment]
Awesome Steve!

Will let know in the next few days!

-E

**Comment by bep** [comment]
Works for me.

**Comment by FooSoft** [comment]
Thank you very much for this change.

**Comment by FooSoft** [comment]
Running into an issue when I have HTML files (specifically reveal.js stuff) along with markdown files:

```
ERROR: 2015/05/21 Error rendering site: Error(s) rendering pages: template: __research/search/presentation/bower_components/reveal.js/plugin/notes-server/notes.html:188: function "socketId" not defined
Available templates:
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/test/examples/embedded-media.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/test/test-markdown-element-attributes.html
ERROR: 2015/05/21 	_internal/shortcodes/test.html
ERROR: 2015/05/21 	partials/header.html
ERROR: 2015/05/21 	partials/photos.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/test/examples/barebones.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/plugin/notes/notes.html
ERROR: 2015/05/21 	
ERROR: 2015/05/21 	_internal/shortcodes/ref.html
ERROR: 2015/05/21 	_internal/_default/sitemap.xml
ERROR: 2015/05/21 	partials/navbar.html
ERROR: 2015/05/21 	_internal/google_news.html
ERROR: 2015/05/21 	404.html
ERROR: 2015/05/21 	partials/article-contents.html
ERROR: 2015/05/21 	partials/github.html
ERROR: 2015/05/21 	_internal/shortcodes/highlight.html
ERROR: 2015/05/21 	_internal/_default/rss.xml
ERROR: 2015/05/21 	_internal/disqus.html
ERROR: 2015/05/21 	_internal/twitter_cards.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/plugin/markdown/example.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/test/examples/slide-backgrounds.html
ERROR: 2015/05/21 	_internal/pagination.html
ERROR: 2015/05/21 	_default/single.html
ERROR: 2015/05/21 	_internal/shortcodes/relref.html
ERROR: 2015/05/21 	_internal/shortcodes/figure.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/test/test-pdf.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/plugin/notes-server/notes.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/test/test-markdown-slide-attributes.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/test/test.html
ERROR: 2015/05/21 	__research/search/presentation/index.html
ERROR: 2015/05/21 	_internal/schema.html
ERROR: 2015/05/21 	partials/article-summary.html
ERROR: 2015/05/21 	partials/footer.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/index.html
ERROR: 2015/05/21 	_internal/opengraph.html
ERROR: 2015/05/21 	_default/list.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/test/examples/math.html
ERROR: 2015/05/21 	__research/search/presentation/bower_components/reveal.js/test/test-markdown.html
CRITICAL: 2015/05/21 Error(s) rendering pages: template: __research/search/presentation/bower_components/reveal.js/plugin/notes-server/notes.html:188: function "socketId" not defined
```

It appears that Hugo tries to interpret them as templates.

**Comment by spf13** [comment]
Html files are interpreted as content files and will be parsed as such when in the content directory. 

If you would like them to not be parsed then they need to be in the static directory. 

This error seems to indicate that they are not in the content directory but in layouts as that is the only place where templates are looked for. Can you provide more complete paths for these files?

Best,
Steve

-- 


Steve Francia
steve.francia@gmail.com

Docker Inc
http://spf13.com 

     




On May 21, 2015 at 12:56:46 AM, Alex Yatskov (notifications@github.com) wrote:

Running into an issue when I have HTML files (specifically reveal.js stuff) along with markdown files:

ERROR: 2015/05/21 Error rendering site: Error(s) rendering pages: template: __research/search/presentation/bower_components/reveal.js/plugin/notes-server/notes.html:188: function "socketId" not defined
Available templates:
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/test/examples/embedded-media.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/test/test-markdown-element-attributes.html
ERROR: 2015/05/21   _internal/shortcodes/test.html
ERROR: 2015/05/21   partials/header.html
ERROR: 2015/05/21   partials/photos.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/test/examples/barebones.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/plugin/notes/notes.html
ERROR: 2015/05/21    
ERROR: 2015/05/21   _internal/shortcodes/ref.html
ERROR: 2015/05/21   _internal/_default/sitemap.xml
ERROR: 2015/05/21   partials/navbar.html
ERROR: 2015/05/21   _internal/google_news.html
ERROR: 2015/05/21   404.html
ERROR: 2015/05/21   partials/article-contents.html
ERROR: 2015/05/21   partials/github.html
ERROR: 2015/05/21   _internal/shortcodes/highlight.html
ERROR: 2015/05/21   _internal/_default/rss.xml
ERROR: 2015/05/21   _internal/disqus.html
ERROR: 2015/05/21   _internal/twitter_cards.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/plugin/markdown/example.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/test/examples/slide-backgrounds.html
ERROR: 2015/05/21   _internal/pagination.html
ERROR: 2015/05/21   _default/single.html
ERROR: 2015/05/21   _internal/shortcodes/relref.html
ERROR: 2015/05/21   _internal/shortcodes/figure.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/test/test-pdf.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/plugin/notes-server/notes.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/test/test-markdown-slide-attributes.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/test/test.html
ERROR: 2015/05/21   __research/search/presentation/index.html
ERROR: 2015/05/21   _internal/schema.html
ERROR: 2015/05/21   partials/article-summary.html
ERROR: 2015/05/21   partials/footer.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/index.html
ERROR: 2015/05/21   _internal/opengraph.html
ERROR: 2015/05/21   _default/list.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/test/examples/math.html
ERROR: 2015/05/21   __research/search/presentation/bower_components/reveal.js/test/test-markdown.html
CRITICAL: 2015/05/21 Error(s) rendering pages: template: __research/search/presentation/bower_components/reveal.js/plugin/notes-server/notes.html:188: function "socketId" not defined

It appears that Hugo tries to interpret them as templates.

**Comment by FooSoft** [comment]
I ended up moving the stuff out of content into static and it's all groovy now. I was just under the impression that with this new change, when processing the content directory, Hugo would convert markdown files to HTML, and pass everything else through without processing it (I thought that the layout directory is the only place that would be processed for templates). I'll post a repro in a few.

**Comment by spf13** [comment]
The intent of /content is things are in there to be processed. This change does permit files to live alongside the content and if a dedicated handler isn't found it will just copy them over. This isn't the safest thing to do as in the future a handler may be defined for the file type and change the behavior. For instance, we could (and probably will) add a handler that does some automatic optimization to images... a generally but not universally desirable feature. If you want the images untouched...

The intent of /static is that things in there are not to be processed and will be copied over exactly as they are.

**Comment by spf13** [comment]
It's also the case that hugo supports html, markdown, asciidoc and rst currently as content files.

**Comment by eduncan911** [comment]
There's the list... Was searching the docs for what is currently processes.

Maybe someone with a little more time can update the docs and submit a pull
request.  (FYI, the Hugo docs is in github as well, generated by Hugo
itself - by Steve I am guessing).

**Comment by FooSoft** [comment]
In case there is interest, I put up the website that illustrates the issue I was having here (5mb download):

http://foosoft.net/dl/hugo-repro.tar.gz

**Comment by zachdyer** [comment]
Can you make hugo ignore desktop.ini files? Google Drive puts that file in there if your using Google Drive sync on Windows. So you have to manually delete all the desktop.ini files to get Hugo to work.

**Comment by bep** [comment]
@zachdyer ini-files should be covered by fc946ded29149443e21587c7f513d4550dc67f39 . Have you tested this with Hugo 0.14?

**Comment by zachdyer** [comment]
Actually no but good job dude yes!

On Wed, May 27, 2015 at 3:48 PM, Bjørn Erik Pedersen <
notifications@github.com> wrote:

> @zachdyer <https://github.com/zachdyer> ini-files should be covered by
> fc946de
> <https://github.com/spf13/hugo/commit/fc946ded29149443e21587c7f513d4550dc67f39>
> . Have you tested this with Hugo 0.14?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spf13/hugo/issues/147#issuecomment-106069347>.
>



-- 
[image: ZachDyerDesignHeaderGoogle.png]
*Zach Dyer*
1471 W South St.
Ozark, MO 65721
417.582.5445
www.zachdyerdesign.com
hosting.zachdyerdesign.com

*Breach of confidentiality & accidental breach of confidentiality*

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by gima** [comment]
Does not work with permalinks.

Files are laid out in a directory path matching the pre-permalink URL, thus effecively ignoring permalinks completely.

**Comment by fazalmajid** [comment]
Interesting discussion. I am in the process of converting a WP blog to Hugo, and my last big hurdles are image gallery handling and ATOM support. To be a world-class platform, Hugo needs fully integrated media management.

I am experimenting with a different approach than what was suggested above: treat JPEG files in /content as an external media type (the same way asciidoc, mmark, ReST and HTML are treated), copy the file as-is, but process its metadata (EXIF/IPTC/XMP/ICC) as implied front matter, and provide templates with functions that can perform standard image operations like thumbnail generation, resizing, watermarking, cropping, and so on.

This would allow templates to become full-fledged gallery generators, e.g. automatically generate a photoblog or galleries from photos dropped into /content/photos/<gallery name> by Lightroom et al. This seems to me like more powerful and extensible, and aligned with the design of Hugo (and the limitations of Go in terms of lacking dynamic linking or similar extensibility mechanisms to implement plugins).

I'll share my work if it turns out to be successful. Happy Thanksgiving!
