### ISSUE TITLE
"Bad character" for valid YAML keys

### ISSUE THREAD

**Issue by gjtorikian** [spf13/hugo#1474]
Supposing you have a YAML data file called *commits.yml* that looks like this:

``` yaml
about-commits: |
  Some words about commits.
```

Attempting to reference this data file in a template yields:

```
ERROR: 2015/10/05 template: layout.html:7: bad character U+002D '-'
ERROR: 2015/10/05 Error while rendering page guides/about-commits.md: html/template: "layout.html" is an incomplete template
```

**Comment by bep** [comment]
This is a restriction of the Go template parser. Try to quote the key. If that works, please close this issue. If you want hyphens unquoted in keywords in Go templates, please open an issue here:

https://github.com/golang/go/issues

**Comment by bep** [comment]
Please reopen if you still believe there is something Hugo should do about this.

**Comment by thxCode** [comment]
@bep , hi~ 
However, if I define this kind of key (i.e. "healthz-port") on `values.yaml`, how can I access its value on other template files? 

For example, [HAProxy](https://github.com/jcmoraisjr/haproxy-ingress#configmap) supports to config its [`healthz-port`](https://github.com/jcmoraisjr/haproxy-ingress#healthz-port), it's not necessary but I hope to expose this configuration on `values.yaml` for other developers, meanwhile, I use `readinessProbe` to check `/healthz` on `healthz-port`.

**Comment by severo** [comment]
> Try to quote the key on the calling side

-> https://stackoverflow.com/a/24629884/7351594

**Comment by vishrantgupta** [comment]
I think HELM does not allow hyphen in the name, change `about-commits` to `aboutCommits`

**Comment by marceloverdijk** [comment]
Sorry to hijack this one a bit.

I'm trying to quote on the calling side like:

```
{{ $tyre_manufacturer := index ".Site.Data.tyre-manufacturers" .Page.Params.tyre_manufacturer_id }}
```

but it gives: `error calling index: cannot index slice/array with type string`

Is there a way to access the data collection (`tyre-manufacturers`) with the hyphen in the name?
