### ISSUE TITLE
Support multiple lists for one type of content

### ISSUE THREAD

**Issue by chuckha** [spf13/hugo#148]
I'd like to be able to:

```
content/
    post/
        ...
layouts/
    post/
        ...
indexes/
    post/
        archive.html
        active.html
```

The intention here is to have an archive page of all posts and an active page of only active posts, say, the 5 latest posts.

**Comment by d4l3k** [comment]
I ran into this exact problem yesterday, but followed @spf13 's advice and figured out a work around.

Here's the post about it: https://fn.lc/post/hugo-multiple-lists/#multiple-list-views

**Comment by bep** [comment]
Handled by https://github.com/spf13/hugo/issues/2828

**Comment by mamluka** [comment]
@bep 

I don't see how it's handled by #2828 

Can you please explain, how is that related
