### ISSUE TITLE
problem to install

### ISSUE THREAD

**Issue by sk9g3** [spf13/hugo#1481]
I'm trying to create a personal blog with hugo but I can not, I tried to follow the footsteps of http://gohugo.io/tutorials/github-pages-blog/, but I'm enfretando a problem, my page sk9g3.github.com only 404 displays the message, someone could tell me where I am going wrong, noting that I am not able to do the steps "git submodule add git@github.com: <username> / <username> .github.io.git public Almost done: add the deploy.sh script to help you (and make it executable: chmod + x deploy.sh), "and I'm using Windows 8 operating system

**Comment by bep** [comment]
Questions are best handled at http://discuss.gohugo.io/
