### ISSUE TITLE
Add description to Page.Params

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1484]
Now it is set on Page.Description -- it would be useful if it was ALSO set in the Params map.

See #1462

**Comment by arunk-s** [comment]
I am interested to work on the issue. Can you explain what's exactly is needed ?

**Comment by bep** [comment]
See

https://github.com/spf13/hugo/blob/c274e21356826a6aa1e04d875a37838a6fe1a6c6/hugolib/page.go#L508

Just put the same value into the Page.Params map with "description" as key.

**Comment by spf13** [comment]
@arunk-s do you want to make a Pull request?

**Comment by arunk-s** [comment]
@spf13 I've actually created a pull requested quite earlier: https://github.com/spf13/hugo/pull/1522.
