### ISSUE TITLE
Menu entry URL printed incorrectly

### ISSUE THREAD

**Issue by synful** [spf13/hugo#1485]
I have the following entry in my config.toml file:

```
[[menu.main]]
	name = "Resume"
	url = "/files/Resume.pdf"
	weight = "4"
```

When I generate my site, the value of the `URL` field for this menu entry in `.Site.Menus.main` is `/files/resume/index.pdf/ `. I've tried, but have been so far unable to figure out what the source of this bug is.

**Comment by bep** [comment]
A workaround would be to define an absolute URL.

**Comment by synful** [comment]
Hmm. That works, although I'm curious as to why. Do you know what's causing this weird transformation?

**Comment by bep** [comment]
Duplicates https://github.com/spf13/hugo/issues/1239

**Comment by synful** [comment]
Ah.
