### ISSUE TITLE
Include file name in errors

### ISSUE THREAD

**Issue by robotamer** [spf13/hugo#149]
I am getting following errors, but can't figure out the origin of the errors.
Could you please include at leased the file names in the errors?
 
 - Only Strings are supported for this key []
 - 2013/12/04 16:41:49 Fatal Error: EOF

Thank you

**Comment by scottcwilson** [comment]
Can someone provide a demonstration of this issue?  The zip that @robotamer put up isn't there anymore.

**Comment by xaprb** [comment]
Take a look at https://github.com/xaprb/xaprb-src. This is what I get with Hugo 0.14 running on that source right now. Notice that it doesn't tell me which files contain the deprecated syntax:

```
~ $ cd repos/xaprb-src
xaprb-src $ hugo
ERROR: 2015/07/22 Node's .Url is deprecated and will be removed in Hugo 0.15. Use .URL instead.
ERROR: 2015/07/22 MenuEntry's .Url is deprecated and will be removed in Hugo 0.15. Use .URL instead.
ERROR: 2015/07/22 Paginator's .Url is deprecated and will be removed in Hugo 0.15. Use .URL instead.
ERROR: 2015/07/22 Site's .BaseUrl is deprecated and will be removed in Hugo 0.15. Use .BaseURL instead.
0 draft content
0 future content 
1074 pages created
209 paginator pages created
22 categories created
3 tags created
in 3005 ms
```

**Comment by bep** [comment]
@xaprb yea, well -- these are logged on the template function level (and only once) -- the calling template is unknown. And I'm having problem seeing a problem in this case (there are others, gradually being fixed). I have fixed 20ish themes/sites in this area (see https://github.com/spf13/hugoThemesSite/issues/6), and some simple Perl one liner replacements (or similar) fix these easily.

**Comment by bep** [comment]
Major improvements have been made in this area. I think this issue is resolved now.
