### ISSUE TITLE
Include code tag for server-side syntax highlighting

### ISSUE THREAD

**Issue by nathany** [spf13/hugo#1490]
GitHub-style code fencing as well as tildes output [a code tag for client-side highlighters](https://gohugo.io/extras/highlighting/#using-client-side-highlighting).

```html
<code class="language-go">
```

But the `{{< highlight >}}` short-code and PygmentsCodeFences options (#1255) don't include the code tag.

I am porting a Jekyll+Pygments site to Hugo where I use the code tag for CSS hooks, including displaying the language of the snippet. With Jekyll the output looks like this:

```html
<code class="language-go" data-lang="go">
```

**Comment by nathany** [comment]
Blackfriday is outputting the code tag when highlighting is disabled. https://github.com/russross/blackfriday/blob/8cec3a854e68dba10faabbe31c089abf4a3e57a6/html.go#L256

**Comment by bep** [comment]
Sure, but the code tag without the additional language-info wouldn't be more helpful than the current `div class="higlight"`?

Note that `highlight` is also a template func, so it should be fairly straight forward to create a custom highlight shortcode that wraps the output in a code block.

**Comment by nathany** [comment]
I certainly would want the code tag to include the language-info.

I'm also using PygmentsCodeFences rather than shortcodes.

**Comment by nathany** [comment]
I don't see an option to Pygments HtmlFormatter. http://pygments.org/docs/formatters/

**Comment by nathany** [comment]
Jekyll's approach is to remove `<div class="highlight"><pre>` and `</pre></div>` as part of the Pygments function (or similarly for other syntax highlighters it supports).

Then it wraps the code in a standard set of tags.

**Comment by nathany** [comment]
I can do a pull request for this.
