### ISSUE TITLE
Allow excluding the beginning of a post from the summary

### ISSUE THREAD

**Issue by dimo414** [spf13/hugo#1495]
I find myself putting contextual information at the top of posts, e.g.

     *For some background on this topic, see [this other post](...).*

Which looks good in the post, but takes up a lot of real estate on list pages, without really being part of a reasonable summary.  It'd be nice if, in addition to `<!--more-->` there were a `<!--preface-->` or `<!--summary-->` comment that would delimit the beginning of the desired summary text, excluding earlier text.

For instance:

```
*For more background, see [this page](...).*

## Overview

<!--preface-->

This is the text I'd like in the summary, it's brief and to the point.

<!--more-->

The rest of the article...
```

Should generate a one sentence summary, rather than one with two paragraphs and an H2.

**Comment by bep** [comment]
I think what you *really* want is a page parameter, then combine that with the `markdownify` template function in the single template.

What you're asking for, you're not getting. We are going to get a better story for getting hold of the different parts of the page, but I doubt it will at this granularity.

For further questions, post at http://discuss.gohugo.io/
