### ISSUE TITLE
Inconsistent menu behaviour

### ISSUE THREAD

**Issue by jpatters** [spf13/hugo#1496]
If I create a menu in config.toml like so:
```
[[menu.main]]
  name = "Blog"
  url = "/blog"
```
This works. If I create it like so:
```
[menu.main]
  name = "Blog"
  url = "/blog"
```
It doesn't work. This would be my expectation given the docs.  
However, if I create a menu on a page like so:
```
title = "About me"
[[menu.main]]
  name = "About"
```
It doesn't work properly. The page is added to the menu but the link text is "About me" and not "About".  
If I add a menu to a page like so:
```
title = "About me"
[menu.main]
  name = "About"
```
I get the behaviour I would expect: the page is added to the menu with the link text of "About".  

So I feel like there might be some confusion around the proper formatting of a menu item depending on where it is defined. I know it just cost me an afternoon.

`Hugo Static Site Generator v0.14 BuildDate: 2015-06-16T17:41:12-03:00`

**Comment by deanc** [comment]
Why are you using double square brackets. It could be the case that if you use two square brackets, it interprets the inner square brackets as part of the menu name.

**Comment by jpatters** [comment]
I am just following the example found here: http://gohugo.io/extras/menus/#adding-non-content-entries-to-a-menu:4044c7430755cd64e5b7c48e836cea57.

But as I said, using single square brackets in config.toml, it doesn't work.

**Comment by bep** [comment]
Please take questions at http://discuss.gohugo.io/
