### ISSUE TITLE
Creating a themes folder by default

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#1507]
Is there any reason why Hugo doesn't create a `themes` folder when a user runs `hugo new site example` in the terminal? You can use Hugo without a theme by putting all necessary files in the right folders (static, layouts...) at the root level. But this isn't mostly the practice.

**Comment by spf13** [comment]
There's no good reason for not doing this. I believe the command pre-dated themes and it never made it over. Someone should add this. It's probably a one line fix.

**Comment by digitalcraftsman** [comment]
> There's no good reason for not doing this.

Do you mean this issue or the practice of including all theme files in the root folders instead of a self-contained theme?

**Comment by spf13** [comment]
I mean it should create an empty themes folder.

**Comment by digitalcraftsman** [comment]
Exactly this was my attention but I wanted to be sure what you meant.

**Comment by inondle** [comment]
Hey, I looked at the source code and it is a one line fix in the commands/new.go file. I've already forked my own version and patched it. I made a new site running the patched command and it correctly made a 'themes' subdirectory. I also followed the steps to contribute on the readme and everything checked out. Should I open a pull request now?

**Comment by anthonyfok** [comment]
@inondle Yes, please do.  :-)

**Comment by inondle** [comment]
Opened one up here:

https://github.com/spf13/hugo/pull/1669

**Comment by jygastaud** [comment]
I ask myself if creating an empty `themes` folder isn't confusing ?
I mean Hugo allows (recommand ?) you to use root folders (archetypes, layouts ...) to override existing themes inside `themes/` folder.

But if you create a themes/ folder as a default, users will ask the difference between using root folders or themes folder.

**Comment by anthonyfok** [comment]
@jygastaud, that's a possibility, though most newbie users would likely start out by using a theme.
Those who build their own layouts in the root folders (rather than using an existing theme) most likely know Hugo much better to be confused by the existence of an empty `themes/` directory.  :wink:
