### ISSUE TITLE
Sharing same static folder in Multilingual Site

### ISSUE THREAD

**Issue by jmarente** [spf13/hugo#1511]
I'm following this hugo tutorial [1] to create a multilingual site.

I haven't been able to share the same static folder between languages, since when I run hugo for a language the static folder content is not generated in the public directory.

Using the *staticdir* option in each language config file, hugo duplicates the static folder content in every language folder.

Having the following static folder:
```
- static/
   |__ js/
   |__ css/
   ...
```
I would like to have in the public folder:
```
- public/
   |__ en/
   |__ es/
   |__ js/
   |__ css/
   ...
```
But I have:
```
- public/
   |__ en/
         |__ js/
         |__ css/
   |__ es/
         |__ js/
         |__ css/
   ...
```
Any ideas?

[1] https://gohugo.io/tutorials/create-a-multilingual-site/

**Comment by bep** [comment]
Then remove `staticdir` from your config.
Questions fits best at http://discuss.gohugo.io/
