### ISSUE TITLE
Add a flag to enable larger RSS feeds

### ISSUE THREAD

**Issue by mattstratton** [spf13/hugo#1515]
Currently Hugo limits the number of posts in an RSS feed to 15 to maintain compatibility with Feedburner standards. There are a few edge cases (podcast feeds, for example) which require the ability to override this to allow for a larger RSS feed. 

Proposed solution is to add a configuration flag to enable a larger feed size in configuration.

**Comment by bep** [comment]
Should be a global config variable, I guess. `RSSLimit`?

Can be added here:

https://github.com/spf13/hugo/blob/master/commands/hugo.go#L169

With a default to current hardcoded value.

**Comment by bep** [comment]
As mentioned in the discussion forum, this can be easily fixed by a template.
