### ISSUE TITLE
replaceShortcodeTokens should modify the input slice

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1516]
See

https://github.com/spf13/hugo/blob/master/hugolib/shortcode.go#L471

Currently a []byte copy is returned. In most cases this is the safe thing to do, but we should just modify/grow the slice as needed:

1. Will be faster / less memory use.
2. It is better that Page.rawContent reflects the content after shortcode expansion.

**Comment by bep** [comment]
@arunk-s I have started on this task, and plan to finish it when I get some spare time.

**Comment by arunk-s** [comment]
@bep Cool. :)
