### ISSUE TITLE
Docs site renders incorrectly in Firefox

### ISSUE THREAD

**Issue by callahad** [spf13/hugo#1523]
Notice the arrows in this screenshot:

<img width="243" alt="screen shot 2015-10-26 at 12 32 53" src="https://cloud.githubusercontent.com/assets/24193/10736973/b47f1e54-7bdd-11e5-80fc-a22095f5adf8.png">

This is due to the order the arrows appear in the DOM, along with their being floated right. Switching to flexbox would make this work pretty trivially.

**Comment by anthonyfok** [comment]
Hi @callahad,

@ffrizzo's solution does fix the rendering issue on Firefox (as well as Iceweasel and Icecat) quite nicely without converting the site layout to flexbox.  However, if you think it would be best if we switch the documentation menu layout to flexbox in the future, please feel free to file a new issue for it.  :-)

Cheers,
Anthony

**Comment by anthonyfok** [comment]
Oh, I forgot to add: gohugo.io uses CloudFlare, which caches static assets like CSS and image files like `docs/static/css/style.css` that @ffrizzo modified.  It takes some time for the cache to clear and refreshed, so you won't see the fixed rendering right away.  But it will happen.  :-)

Cc: @spf13

**Comment by callahad** [comment]
Thanks!

The code in 217ffa87c9f8a1c4d18373556594d4d9fb9a4151 is a browser-specific hack which increases the project's complexity and likelihood of breaking in the future.

Can we revert and look for a cross-browser solution so we don't add technical debt?

**Comment by callahad** [comment]
(FWIW, I'm fine with or without flexbox, only suggesting it since other parts of the docs already use `display: flex`)
