### ISSUE TITLE
`livereload.js` not being injected properly

### ISSUE THREAD

**Issue by pandorahlz** [spf13/hugo#1526]
Per some forum posts and another issue, it seems that it gets injected before the closing body tag, but I think this isn't right. HTML5 supports omitting (implied) body and head tags, so I think a line with the script tag should just be appended to the file on the fly upon client service. That said, there's still some sort of bug, because even with opening `html`, `head`, and `body` tags, the script isn't being injected.

**Comment by bep** [comment]
You need a closing body tag. We are not changing that. We need something to search for.

**Comment by pandorahlz** [comment]
What? Why? HTML5 is abundantly clear that there's no need for head and body tags. It's code clutter in your markup to include something unnecissarily. Why wouldn't yo just append it?

**Comment by pandorahlz** [comment]
Also, there's a bug at least on OSX Yosemite, which is another issue in this bug that you haven't addressed. I think the suggestion to lose the requirement is an enhancement idea, but there's additionally an actual bug here, where even when meeting the ostensible requirement, it doesn't work as it should.

**Comment by bep** [comment]
The HTML5 spec doesn't say that you can not have a end body tag. The Hugo spec says that you need an end body tag to use live reload. You can easily follow both HTML5 and Hugo spec by adjusting your template.

**Comment by pandorahlz** [comment]
Don't you think the burden of justification should be on the software package imposing extra complexity?

**Comment by pandorahlz** [comment]
And, according to HTML5, you really don't need to have beginning, or end, html, head, or body tags.

**Comment by bep** [comment]
Please take discussions and questions at the forum.

**Comment by pandorahlz** [comment]
Why so salty?

**Comment by bep** [comment]
Because my time doing free work for the open source community is a limited resource. So, bring your questions to the forum where there are more people to answer.
