### ISSUE TITLE
Hash generating id messes up links

### ISSUE THREAD

**Issue by rodzzlessa24** [spf13/hugo#1541]
So Hugo adds a hash to every id. For example:

`<h2 id="team-structure:e7fc36525fb189e35e1a68dee9489709">Team Structure</h2>`
I have a site that uses ids as links:

`<a href="#team-structure">Team Structure</a>`

Now that link is broken since the `h2` ID now has a hash

**Comment by bep** [comment]
Please use the http://discuss.gohugo.io/ for questions. There is a setting that let you turn off those hashes. See the docs.

**Comment by dnephin** [comment]
I'm not seeing any related option in the docs.  Got a link to more information about it?

**Comment by bep** [comment]
It's in the docs. Other than that, try the discussion site mentioned above.

**Comment by dnephin** [comment]
I ended up finding it.

For anyone else that finds this issue, the option you're looking for is `plainIDAnchors` (http://gohugo.io/overview/configuration/).

There was a change at some point, it used to be `plainIdAnchors`.
