### ISSUE TITLE
Fix doc where taxonomy template file name should be PLURAL instead of SINGULAR

### ISSUE THREAD

**Issue by yvele** [spf13/hugo#1546]
`SINGULAR` should be replaced by `PLURAL` here :
- Page [templates/list](https://gohugo.io/templates/list/#which-template-will-be-rendered:8c265e2adc353bedf8022b542a0b78ab)
  - Section [Taxonomy Lists](https://github.com/spf13/hugo/blob/master/docs/content/templates/list.md#section-lists) : 2 words to be replaced
  - Section [Taxonomy RSS](https://github.com/spf13/hugo/blob/master/docs/content/templates/list.md#taxonomy-rss)  : 2 words to be replaced (not tested.. but I guess it also need to be fixed)
- Page [templates/terms](https://gohugo.io/templates/terms/#which-template-will-be-rendered:9b10c1f64082d3869fd4cb1f85809430)
  - Section [Which Template will be rendered](https://github.com/spf13/hugo/blob/master/docs/content/templates/terms.md#which-template-will-be-rendered) : 1 word to be replaced

Also, the page source [overview/source-directory](https://gohugo.io/overview/source-directory/) is wrong, I suggested to have something like that:

```
├── layouts
|   ├── taxonomies
|   |   ├── categories.html
|   |   ├── categories.terms.html
|   |   └── tags.html
|   |   └── tags.terms.html
```

**Comment by yvele** [comment]
Sorry I was confused because of the [overview/source-directory](https://gohugo.io/overview/source-directory/) page.
Taxonomy template file is SINGULAR in the doc and **that's actually correct**.

The only page to fix is [overview/source-directory](https://gohugo.io/overview/source-directory/) where

````
|   ├── taxonomies
|   |   ├── category.html
|   |   ├── post.html
|   |   ├── quote.html
|   |   └── tag.html
````

should be

````
|   ├── taxonomy
|   |   ├── category.html
|   |   ├── category.terms.html
|   |   ├── tag.html
|   |   └── tag.terms.html
````

With a **SINGULAR** directory name

I'm sorry about the wrong PR. BTW, can you revert PR https://github.com/spf13/hugo/pull/1547 I made ?

**Comment by rdwatters** [comment]
This is no longer an issue with the new docs site.
