### ISSUE TITLE
Allow inserting file, bypassing rendering

### ISSUE THREAD

**Issue by yitzhakbg** [spf13/hugo#1551]
See [my post](http://discuss.gohugo.io/t/incorporated-remark-js/2017) on incorporating [remark.js](http://remarkjs.com/#1).
It required pulling in a markdown file without hugo rendering it (remark does the rendering). I had to trick hugo by placing the md file in the partials directory and pulling it in from there as a partial. But why sneak in the back door? The capability of pulling other files in could be useful in many situations.

**Comment by bep** [comment]
See http://discuss.gohugo.io/t/howto-embed-remarkjs-com-slides-in-hugo/1403

**Comment by yitzhakbg** [comment]
Thanks for the info. I see you closed this. .RawContent isn't in v0.14, so I can't use it.
I would suggest making it more flexible so that it can raw load any file and not only the equivalent of the .Content file.

**Comment by bep** [comment]
Well, any new suggested features wouldn't be in 0.14 either. Raw content include is, kind of, already covered by the Exec issue and pull request. But I'll reopen this to keep track of it. Someone may make a cross platform "cat file" feature.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Thanks
    
    On 5/11/15 16:17, Bjørn Erik Pedersen
      wrote:
    
    
      Well, any new suggested features wouldn't be in 0.14 either.
        Raw content include is, kind of, already covered by the Exec
        issue and pull request. But I'll reopen this to keep track of
        it. Someone may make a cross platform "cat file" feature.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by yitzhakbg** [comment]
I think that enhancing the partial functionality is the way to go. Allow pulling in different content types from a range of locations. Could open the way to future innovation

**Comment by spf13** [comment]
Is this resolved now with the release of 0.15?

**Comment by yitzhakbg** [comment]
I'd also like to know if this is resolved with 0.15

**Comment by bep** [comment]
No.

**Comment by yitzhakbg** [comment]
With your kind permission, I'd like to expand on why this is a valuable addition IMHO:
Remark.js, which renders slides with its own engine, is but an example of a wide range of possible intermediate processing applications which can be performed during rendering outside of but not interfering with Hugo. Remark.js renders Markdown, but many applications might need intermediate processing of different types altogether.
Optimally, it should be made available to users within the context of Hugo syntax without having to invoke an API call.
Thanks

**Comment by yitzhakbg** [comment]
I'm having trouble understanding this. Could you kindly provide some non-technical documentation with an example of how to use this?

**Comment by bep** [comment]
Use https://discuss.gohugo.io/ for questions.
