### ISSUE TITLE
[Suggestion][Doc] Shallow clone of theme repository

### ISSUE THREAD

**Issue by PhiLhoSoft** [spf13/hugo#1553]
The Quickstart Guide suggests the following line to download the themes:
`git clone --recursive https://github.com/spf13/hugoThemes themes`

It took forever to download (on Windows 7) with an otherwise fast connection (Git reports an average of 2 MiB/s though).
I think the command should include  `--depth 1` to avoid downloading the whole history of these themes, as it is generally not useful for this usage.

WDYT?

**Comment by abhi1010** [comment]
I agree. I think it is a good suggestion. If somebody is willing to download all themes, most likely they are in there to isolate the best ones for them before they dig deeper. 

I just gave it a try and it is indeed faster.

**Comment by digitalcraftsman** [comment]
And if you want to contribute to a theme you normally work with a fork seperate from the Hugo site.

**Comment by bep** [comment]
Agree.

**Comment by spf13** [comment]
please make a PR with this change to the guide. It's much better.

**Comment by PhiLhoSoft** [comment]
I fear I won't have time to do a PR (GitHub makes it so lengthly...) but go ahead, just slip the change anonymously in a site update, I won't mind at all. :smile:
