### ISSUE TITLE
Support themesDir option

### ISSUE THREAD

**Issue by SebastianM** [spf13/hugo#1556]
I would like to configure where my themes are located. Currently the "themes" dir name is hardcoded ([path.go#L213](https://github.com/spf13/hugo/blob/36adb5fb883bb7170d062334f8aaa64ed191be68/helpers/path.go#L213)) and not configurable. My proposal is to add a **themesDir** option (in addition to dataDir, staticDir, etc.):

``` yaml
themesDir: 'assets/docs/themes'
theme: 'myTheme'
```

In this case, hugo would use `asset/docs/themes/myTheme` as the theme folder.

**Comment by spf13** [comment]
Great idea. Do you want to code it?

**Comment by SebastianM** [comment]
I'm not familiar with the codebase but I will try :-)
Steve Francia <notifications@github.com> schrieb am Sa., 7. Nov. 2015 um
14:02:

**Comment by AldenJole** [comment]
It seems like it might be more useful to just have a `themePath` option. Then I could use it like `hugo server -wD --themePath . --source exampleSite` during theme development.

**Comment by spf13** [comment]
@AldenJole I like that idea as well. Not sure which one is better. Probably yours, it's simpler. Is there a valid use case for the themeDir approach if we have themePath?

**Comment by AldenJole** [comment]
Eventually we might be able to replace the whole `themeDir` concept with `themePath` and then just put them in `themes` by convention. Then the config option would look like `theme = "themes/<theme-name>"`. That would also give use the ability to specify remote themes, e.g., github projects.

**Comment by spf13** [comment]
I agree. I like this much better.

--
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by AldenJole** [comment]
We maybe be able to figure out a reasonable way to parse the theme option to figure out if it's a path or not.

**Comment by moorereason** [comment]
Fixed by #2817
