### ISSUE TITLE
Rendering shortcodes within page stops us #including a bunch of HTML

### ISSUE THREAD

**Issue by mdda** [spf13/hugo#156]
Since commit(f432b187a0ec52629ad1b9d993a5c3203e3699d5) the way that I found to include raw HTML (a google map layout, or a specialized form) doesn't work : Suddenly the HTML shortcode is being rendered as {PRE} because it is assumed to be .md (because it was included in a .md page)

What is the Right Way to include a fairly large block of verbatim HTML?

**Comment by bep** [comment]
This was fixed in Hugo 0.13.
