### ISSUE TITLE
GroupByParam makes the key lowercase

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1564]
See 

http://discuss.gohugo.io/t/why-are-page-params-lowercase/2064/3

Not sure why.

@tatsushid ?

**Comment by tatsushid** [comment]
`GroupByParam` internally calls `Page.GetParam` and it returns lower character string every time. It may be better to use unexported `Page.getParam` function for this purpose instead of `Page.GetParam`

**Comment by bep** [comment]
Aha! Thanks. Agree about that ... not sure why `Page.GetParam` does what it does, but that's a discussion for another century.

**Comment by tatsushid** [comment]
Yes, and I don't know why `Page.GetParam` does it but in `GroupByParam`, it is easily fixed by editing just a line. I will send PR as a quick fix.
