### ISSUE TITLE
How to use Hugo's docs theme

### ISSUE THREAD

**Issue by chankeypathak** [spf13/hugo#1567]
I want to have a theme similar to Hugo docs, I have downloaded https://github.com/spf13/hugo/tree/master/docs and tried running below command:

$ hugo server

It didn't work. See below errors:

![hugo](https://cloud.githubusercontent.com/assets/424822/11084306/cb2afa5e-885f-11e5-91d4-30ee6107d21a.png)

What am I missing?

**Comment by digitalcraftsman** [comment]
Did you use the latest release (0.14) or Hugo or did you compiled the latest version of HEAD? The template function readDir will be included in the next release and seem to cause the error since can't find any definition for it.

**Comment by chankeypathak** [comment]
Thanks. Downloaded source of 0.14 and from there it worked.
