### ISSUE TITLE
Add built-in shortcodes for common usecases

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#1576]
Why shouldn't we add a number of shortcodes for the most popular usecases and services. New users could use them out of the box without the need of creating them manually.

Follow the [forum discussion](https://discuss.gohugo.io/t/shoud-we-add-internal-shortcodes-for-popular-services/2085) for more information.

Just a quick compilation of usecases / services (todo list):

- [x] Twitter
- [x] Speakerdeck presentations
- [x] YouTube videos
- [x] Vimeo videos
- [x] Github gists

**Comment by derekperkins** [comment]
@digitalcraftsman - that's a good idea and not particularly difficult to implement. If you could figure out what the input options should be and sample output, that'd make it a piece of cake.

**Comment by digitalcraftsman** [comment]
@derekperkins - below you find a list of the syntax that user would use to call the shortcodes. Do you think that something could be improved?

#### Speakerdeck
Required is the id of the slide. This id can be found on the right side of the presentation on Speakerdeck under 'Direct link'

    {{< speakerdeck "4e8126e72d853c0060001f97" >}}

#### YouTube
Just the id of the video is required:

    {{< vimeo "146022717" >}}

#### Vimeo
Just the id of the video is required:

    {{< vimeo "146022717" >}}

#### Gists
Gists would need the owner's username and its unique id:

    {{< gist "digitalcraftsman" "85f59771b5ae1e2091a8" >}}

**Comment by bep** [comment]
A comment for the documentation: You only need quoted parameters if you have spaces or very special chars, so this is better:

```
{{< youtube w7Ft2ymGmfc >}}
```

**Comment by digitalcraftsman** [comment]
Thanks for annotating this. I'll update the examples above.

**Comment by digitalcraftsman** [comment]
All shortcodes are implemented (including Twitter) and the docs have been written.

**Comment by derekperkins** [comment]
Awesome!

**Comment by umtksa** [comment]
how about responsive vimeo and youtube
i have some custom shortcodes [here](https://github.com/umtksa/hugo-short-code)
