### ISSUE TITLE
localhost still used when I do hugo server --bind="0.0.0.0"

### ISSUE THREAD

**Issue by nikolas** [spf13/hugo#1582]
Hi,
When I do `hugo server --bind="0.0.0.0"` on a remote computer, then access it at `http://myserver:1313`, my CSS file is still linked to as `<link href="http://localhost:1313/css/site.css" rel="stylesheet" type="text/css">`, not `http://myserver:1313/css/site.css` as expected. I'm referring to the path as `"{{ .Site.BaseURL }}css/site.css"` in my `layouts/partials/header.html`. Is this a bug in hugo?

    $ hugo version
    Hugo Static Site Generator v0.15-DEV BuildDate: 2015-10-19T16:14:44-04:00

And here is my complete hugo site: https://github.com/ccnmtl/digitaltibet

**Comment by nikolas** [comment]
I found a way to fix this: Pass in your hostname as well with `--baseUrl`:

    hugo server --baseUrl=myhostname --bind="0.0.0.0"

**Comment by debianmaster** [comment]
cab this be achieved with out using ?  --baseURL ?   my route is dynamically decided

**Comment by fiatjaf** [comment]
As of today, `--bind=0.0.0.0` works here.

**Comment by Fazendaaa** [comment]
@Nichlas, six years later on and you saved my skin; I was having this issue running my website through HTTPS locally even tho I had defined the `baseURL` in my TOML file.
