### ISSUE TITLE
hugo server fails to serve files in /static on Windows

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1586]
This is related to the new "in memory" file system.

Tested on Windows 8.1, multiple sites. All files in /static is 404. Also reported to fail on Windows 10.

Would be good with a failing automated test.

**Comment by spf13** [comment]
I have now found and fixed the bug. It was in a dependency we have which called path.Join instead of filepath.Join. See https://github.com/spf13/fsync/commit/1a03b59821319ad444dd28ea219e409e2815182e

**Comment by anthonyfok** [comment]
:clap: :bow:
