### ISSUE TITLE
Use absolute path when opening new content in editor

### ISSUE THREAD

**Issue by riklopfer** [spf13/hugo#1589]
Currently, when `hugo --source="/path/to/hugo/site" new post/test.md --editor="subl"` is invoked from anywhere but inside the hugo site directory, it will create the file in the correct place, but the editor will open a non-existent file referenced by the relative path `post/test.md`

**Comment by kujohn** [comment]
I was not able to use those two flags `--source` and `--editor` in conjunction with the `new` command.
Yields:
```
~  hugo --source="/Users/john/src/hugotest/" new posts/in.md
Error: unknown flag: --source                                  
```

**Comment by riklopfer** [comment]
Humph. `hugo --help` doesn't mention `--source`?

**Comment by anthonyfok** [comment]
> Humph. `hugo --help` doesn't mention `--source`?

For almost two weeks in Hugo v0.16-DEV: No, because I removed it, see #1624.
I have just added it back a few minutes ago in commit c1e134f after committing @kujohn's excellent fix to this issue.  :wink:

Cheers,
Anthony
