### ISSUE TITLE
ge, gt, le, lt should support time.Time

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1593]
See 

https://discuss.gohugo.io/t/trying-to-filter-data-files-based-upon-a-date-field/2114

**Comment by tatsushid** [comment]
`where` function's condition checker `checkCondition` supports `time.Time` type comparison. So it may be used in them.

And the case discussed at the forum may avoid by using `where` instead of `range` and `if` combination.

(Sorry I cannot login the forum now so reply here)

**Comment by bep** [comment]
Agree about the use of `where`, but i added time support here as well for completeness.
