### ISSUE TITLE
Support for preprocessors

### ISSUE THREAD

**Issue by redalastor** [spf13/hugo#16]
There should be some support for HTML/CSS/JS preprocessors even if it's just adding shell commands to run in the config.

**Comment by truongsinh** [comment]
+1

**Comment by omeid** [comment]
_*Shameless-plug*_: You might find [slurp](https://github.com/omeid/slurp) useful, which is a gulp.js inspired build system written in Go.

You can write your builder (like Gulpfile.js) and compile it so you don't need to have a Go tool chain to use it.

**Comment by sandcastle** [comment]
+1 - Pre-processor support is a must for me.

**Comment by fgimian** [comment]
+1 please :smile:

**Comment by csuarez** [comment]
Until this is supported, I have published the template that I use built with Gulp: https://github.com/csuarez/hugo-gulp-template

I hope that someone find it useful.

**Comment by nathany** [comment]
I currently use https://github.com/rjeczalik/cmd to watch my `sass/**` folder and run `sassc`. My script to do this is here:
https://github.com/nathany/hugo-deploy/blob/master/watch.sh
(it was quite a pain to write that)

It would be nice if Hugo's watcher ran sassc if available: `exec.LookPath("sassc")`. But it would probably be better if it was configurable.

@omeid Have you used either of Slurp's successors? I'm curious.

**Comment by moorereason** [comment]
I use [Wellington](https://github.com/wellington/wellington) as my sass processor cmd.  Run it in watch mode alongside Hugo.

If Wellington matures to the point where it's 100% Go, we could potentially use it as part of the Hugo site build.

**Comment by nathany** [comment]
@moorereason I'm not sure if that makes sense in the long term. Much like asset concatenation, spriting becomes an anti-pattern when served with HTTP/2, for the same reasons. See https://github.com/spf13/hugo/issues/432#issuecomment-211708907.

**Comment by moorereason** [comment]
@nathany, agreed.  I don't use sprites and don't care for them.  That wasn't my point.  Wellington uses libsass for many operations, so it's not a great solution for Hugo right now.  But he's building out a [pure Go sass parser](https://github.com/wellington/sass) to eventually have a pure Go solution.  I think that's very relevant to Hugo and the Go ecosystem.

**Comment by nathany** [comment]
@moorereason Sorry, I misunderstood. A pure Go sass parser would be awesome, esp. for embedding in tools like Hugo. Achieving and maintaining feature parity is certainly a challenge.

**Comment by adrinux** [comment]
Integrated Sass parser...except all the buzz is around PostCSS now ;)
I think the approach of having a build tool run Hugo works pretty well.

**Comment by declanqian** [comment]
It would be great if `hugo` has `sass` integrated somehow.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
