### ISSUE TITLE
Request Support for Custom 403.html Error Page

### ISSUE THREAD

**Issue by ghost** [spf13/hugo#1606]
Can we please get support for `403.html` "Access Denied" page ? Thank you!

**Comment by bep** [comment]
When is this happening in a static file server?

**Comment by tuxy** [comment]
Yeah but I don't think you can use it the same way like you can ``/layouts/404.html`` to include header/footer ;-) This custom error 403 page would go into ``/layouts/403.html`` and could be used the same way.

**Comment by spf13** [comment]
I don't fully understand the usefulness of the request. Can you provide more information?

**Comment by tuxy** [comment]
@spf13 Well you have ``404.html`` that we can put inside ``/layouts/`` and then include header/footer partials. But we can't do the same with ``403.html``

https://gohugo.io/templates/404/

**Comment by tuxy** [comment]
Perhaps even better way is to use special directory for all the custom errors like ``/layouts/errors/`` where we can put ``403.html``, ``404.html`` and others.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by nidrissi** [comment]
@bep @spf13 Some parts of the website may be behind some `auth_basic` password protection...

**Comment by radusuciu** [comment]
Also would use this. Developing an intranet site that has authentication with `auth_basic`. Would be great if the 403 Unauthorized page could be handled the same way as 404..

**Comment by davidsneighbour** [comment]
Create  a page with the following frontmatter:

```
---
url: /403
layout: 403
---
```

Then create a layout for it. In the end, you will have to add server rules that point to this error page.

In my own opinion: It's not worth a feature if only 4 people in 4 years require it.

**Comment by naggie** [comment]
> In my own opinion: It's not worth a feature if only 4 people in 4 years require it.

I'm sure there are more than 4 people. 

This would be a useful feature to me, where a portal I'm building is only accessible from within a VPN.

I'll use the suggested workaround for now, thanks.

**Comment by frozenpandaman** [comment]
@davidsneighbour As previous commenters have said, also pretty sure it's more than just four people – and I think many new users have been confused + surprised to find this inconsistency here…
