### ISSUE TITLE
Update shortcode documentation

### ISSUE THREAD

**Issue by moorereason** [spf13/hugo#1613]
Two issues:

1. There are errant `***` lines scattered throughout `shortcodes.md` file after the most recent update.
2. The `tweet` shortcodes needs to have the author ID removed from the parameter list.

Cc: @digitalcraftsman

**Comment by digitalcraftsman** [comment]
The current version of the shortcodes in the docs doesn't contain the username/author id:

    {{</* tweet 666616452582129664 */>}}

**Comment by moorereason** [comment]
Yeah, I jumped the gun here.

The first issue is a problem with a Vim Markdown plugin not styling `***` as a horizontal rule but as strong.  The second issue was already fixed.

There are a couple other issues I see:

3. The `gist` example is not indented like it should be.
4. The links provided with the new built-ins are being formatted as code and look weird.

**Comment by digitalcraftsman** [comment]
What I've changed so far:

- remove the horizontal lines
- moved the example links for the shortcodes on their own line (without any formatting)

> The gist example is not indented like it should be.

Could you explain what exactly should be changed?

**Comment by moorereason** [comment]
This line:
```
{{</* gist spf13 7896402 */>}}
```
Needs to be indented:
```
    {{</* gist spf13 7896402 */>}}
```

Also, delete trailing whitespace at the end of lines.  :smile: 

In case you didn't notice it, you can go into the `docs` folder and run Hugo.  It's a self-contained Hugo site.

**Comment by moorereason** [comment]
I don't mind the horizontal rules.  I normally use `---` for that instead of `***`.  The broken syntax highlighting of my vim plugin confused me.  I can see that they are being used in `tools/index.md` file.

**Comment by digitalcraftsman** [comment]
Sorry, I already fixed the issue with the gist code example on the go. However, I actually run the local server while editing the docs.

I'm mainly the currator of `tools/index.md`. The intended use of the horizontal lines was to visually seperate certain sections. But In the current state I removed them from the shortcodes page due to your advise above.

**Comment by digitalcraftsman** [comment]
Are there any updates to the related PR?
