### ISSUE TITLE
hugo server hang for windows_386 binary

### ISSUE THREAD

**Issue by tpng** [spf13/hugo#1621]
Since the new hugo server serves the generated site from memmap files, using `windows_386` version of hugo on `windows_amd64` machine will hang on [fs.Create()](https://github.com/spf13/afero/blob/master/memmap.go#L89).

Maybe add a reminder on the release note or documentation for this issue so people can avoid using `windows_386` binary on `windows_amd64` Windows machine.

**Comment by tpng** [comment]
https://github.com/spf13/afero/issues/23 should fix this issue.

**Comment by anthonyfok** [comment]
:+1:

**Comment by anthonyfok** [comment]
Hi @spf13,

As more people are hit by this bug, e.g. #1628, I have taken the liberty of adding a big note at the top of the v0.15 release note and renaming the windows_386 (32-bit) zip file.  When you have time, could you please rebuild and upload hugo_0.15_windows_386.zip, to replace the old hugo_0.15_windows_386_32-bit-only.zip?  Many thanks!

**Comment by anthonyfok** [comment]
See also https://discuss.gohugo.io/t/hugo-server-returns-runtime-error-on-armhf/2293
