### ISSUE TITLE
CLI UX: Flags shouldn't be global

### ISSUE THREAD

**Issue by joneskoo** [spf13/hugo#1624]
Command line flags should not be global. This is obvious when you look at for example the help for "gen man"; the options don't make sense with that command.

    $ hugo gen man --help
    This command automatically generates up-to-date man pages of Hugo's
    command-line interface.  By default, it creates the man page files
    in the "man" directory under the current directory.
    
    Usage:
      hugo gen man [flags]
    
    Global Flags:
      -b, --baseURL="": hostname (and path) to the root, e.g. http://spf13.com/
      -D, --buildDrafts[=false]: include content marked as draft
      -F, --buildFuture[=false]: include content with publishdate in the future
          --cacheDir="": filesystem path to cache directory. Defaults: $TMPDIR/hugo_cache/
          --canonifyURLs[=false]: if true, all relative URLs will be canonicalized using baseURL
          --config="": config file (default is path/config.yaml|json|toml)
      -d, --destination="": filesystem path to write files to
          --disableRSS[=false]: Do not build RSS files
          --disableSitemap[=false]: Do not build Sitemap file
          --editor="": edit new content with this editor, if provided
          --ignoreCache[=false]: Ignores the cache directory for reading but still writes to it
          --log[=false]: Enable Logging
          --logFile="": Log File path (if set, logging enabled automatically)
          --pluralizeListTitles[=true]: Pluralize titles in lists using inflect
          --preserveTaxonomyNames[=false]: Preserve taxonomy names as written ("Gérard Depardieu" vs "gerard-depardieu")
      -s, --source="": filesystem path to read files relative from
          --stepAnalysis[=false]: display memory and timing of different steps of the program
      -t, --theme="": theme to use (located in /themes/THEMENAME/)
          --uglyURLs[=false]: if true, use /filename.html instead of /filename/
      -v, --verbose[=false]: verbose output
          --verboseLog[=false]: verbose logging

**Comment by spf13** [comment]
This is a good request. Originally hugo only had two commands, `hugo` and `hugo server`. Since they shared a lot of flags it made sense to make it global (then). Now with a lot of other sub commands we should create them separately on server and root.
