### ISSUE TITLE
Sanity checks for import jekyll

### ISSUE THREAD

**Issue by joneskoo** [spf13/hugo#1625]
There should be sanity checks for jekyll import:

    $ hugo import jekyll . .

**WARNING: This will overwrite config in current directory and create a messy directory tree.**

For instance this should not be allowed (it creates a very deep structure as it reads its own output).

The import should verify that

 1. the source directory looks like a valid jekyll install (look for config maybe? fail if no posts are found?
 2. target directory is empty or doesn't exist (create it)

**Comment by anthonyfok** [comment]
Hi @coderzh, wants to look at this?  :-)

**Comment by coderzh** [comment]
Thanks for your commit, @anthonyfok .  I'm so busy these days and have too few time to solve this issue.

**Comment by anthonyfok** [comment]
You are very welcome, @coderzh.  我被那个 exp/beginner 标签吸引了，所以就边学习边改代码了，嘿嘿。 :-)
