### ISSUE TITLE
Hugo baseURL HTTPS Support

### ISSUE THREAD

**Issue by tuxy** [spf13/hugo#1632]
Can we get support for https in ``-b, --baseURL`` when using it like this ``hugo server -w -b //domain.com/ --appendPort=false`` It works just fine in ``config.toml`` ``baseUrl = "//domain.com/"`` Thank You!

**Comment by bep** [comment]
Note that this task would also include setting up the server with SSL with a certificate and all that shebang.

**Comment by tuxy** [comment]
Yeah that fine, at least will have the option :-)

**Comment by bep** [comment]
@tuxy curious: How would you set up SSL *without* a certificate?

**Comment by tuxy** [comment]
Self-Signing or using CloudFlare ;-) For localhost simply do something like this;
https://github.com/tuxy/configs/blob/master/generate-ssl-keys.md

Then see config examples here;
https://github.com/tuxy/configs/blob/master/nginx/nginx.conf
https://github.com/tuxy/configs/blob/master/nginx/hugo.conf
https://github.com/tuxy/configs/tree/master/hugo

**Comment by bep** [comment]
Ah, OK (but self-signed is still a certificate) -- but lets just drop this issue down to be about the `baseURL` only, not about SSL support in the server.

**Comment by tuxy** [comment]
@bep yes, its what I wanted ^_^ Simply support both http and https in BaseURL by adding config line such as ``baseURL = "domain.com"`` for example, instead of having to use ``//``

**Comment by klauern** [comment]
I don't know what kind of work would need to be done, but [Caddy server](https://caddyserver.com) supports Lets Encrypt, and it works pretty slick.  I think the source code for how it works can be [found here](https://github.com/mholt/caddy/tree/master/caddy/letsencrypt), although I'm not sure how much of that is tied to Caddy-specific implementation.

**Comment by stuartweir** [comment]
I'm taking a look at this now

**Comment by bep** [comment]
@stuartweir yes.

**Comment by Draga** [comment]
It seems to me that baseUrl just disregards the protocol.
I've tried to use https (i redirect http to https, if you need a free cert try letsencrypt) but the url was still using http.
Using "/" works but then the sitemaps are broken because the path are relative, and at least in google webmaster tools it doesn't work :(

**Comment by jamesward** [comment]
+1

Hard coding the URL into a config file makes it hard to support cloud environments for a number of reasons.  One being that https may be provided by a proxy server.

**Comment by anthonyfok** [comment]
Special thanks to @moorereason for solving this issue in PR#2144.

Merged as ca6b26f.
