### ISSUE TITLE
Feature request: create `index.json` or `index.js` for client-side search libraries like Tipue and Lunr.js.

### ISSUE THREAD

**Issue by rdwatters** [spf13/hugo#1635]
### 1. Roll Your Own
- `range` to loop through all `.Site.Pages`, escape the html/md (similiar to `| jsonify` in Liquid), and write it to a file with a `.js` or `.json` file extension. This is spitballing, but to keep everything HTML, maybe it's as simple as a parameter in `layout/searchIndex.html` that allows for a different file extension to be copied to `public/`. 
### 2. [Lunr.js](http://lunrjs.com/)
- Loops through every content page and pulls title, subtitle, description, tags, categories, dates, and body copy
- Excludes all .md files with `inSearch: false` / `inSearch = false`   in the toml/yaml of individual file; ie, if the following is set to `true`...
- Global param in `config.toml` /  `config.yaml` with `createJsonIndex = true`. Maybe the default behavior should be set to `false` in case something like this would slow down build time for larger sites. The default destination could be `static/js` since this dovetails with the folder structure for themes.
- Lunr requires some JS acumen to display your contents to the page. Larger sites would need a webworker. That might get trickier for newbs. Also, this is less customizable than option 1.  

This would then make it really easy to add weights to properties and have lunr.js index content on the client and display results by score. 
### 3. [Tipue](http://www.tipue.com/search/)
- The same as #2, but allow to write to a `.js` file instead for a `var tipue_search = {}...`

**Comment by digitalcraftsman** [comment]
:+1: This feature would be really nice and could replace a lot of Gulp/Grunt scripts that are used the generate the search index.

If you range over all files, take care that you only include files that aren't marked as drafts.

**Comment by rdwatters** [comment]
@digitalcraftsman Excellent point and something I should have mentioned above. At the page level, the index would look at two conditionals: 

1. `insearch != false`
2. `draft != true`

Thanks!

**Comment by bep** [comment]
Agree about the "usefulness", but I'm pretty sure this is somehow a duplicate of some other issue.

**Comment by digitalcraftsman** [comment]
This is related to #144

**Comment by bep** [comment]
See https://discuss.gohugo.io/t/simple-json-site-index-in-hugo/2854

**Comment by rdwatters** [comment]
I'm closing this issue since it's now a non-issue with the upcoming custom outputs...
