### ISSUE TITLE
Add documentation to address questions with section lists in themes

### ISSUE THREAD

**Issue by mdhender** [spf13/hugo#1637]
See https://discuss.gohugo.io/t/only-layouts--default-list-html-will-work-for-my-post-section/1491 for an example of the confusion.

**Comment by rdwatters** [comment]
News docs have a whole snazzy new page that details what a "list" means in Hugo. 

@mdhender I'm considering the following comment your implicit approval of the new lists documentation:

https://discuss.gohugo.io/t/new-docs-site-need-feedback/5765/24

:smile:
