### ISSUE TITLE
Fix copyright header in source files

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1646]
In #201 there was an understanding of the copyright situation of  this projcect, at least depending on which CLA you agreed upon.

Currently it says:

> // Copyright © 2013-14 Steve Francia <spf@spf13.com>.

The copyright owner would  be the person(s) with the majority contribution in a given source file (or something), but that would be too complicated. 

I suggest we do as in the Go std lib:

>// Copyright 2009 The Go Authors. All rights reserved.

So for us I suggest:

// Copyright 2015 The Hugo Authors. All rights reserved.

Then add a AUTHORS and maybe a CONTRIBUTORS file (if the two differs).

**Comment by spf13** [comment]
I agree.

**Comment by spf13** [comment]
I believe this is now resolved. If yes can one of you close? @bep @anthonyfok

**Comment by bep** [comment]
We need an AUTHORS file of sorts.

**Comment by spf13** [comment]
Why? Git dynamically already tracks and can produce authorship. I don't
believe legally we need to provide a file listing authors, just a means to
obtain a list.
