### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by jungle-boogie** [spf13/hugo#1649]
This crash mean much to you?

goroutine 1 [running]:
flag.init()
	/usr/local/go/src/flag/flag.go:840 +0x11a
github.com/spf13/pflag.init()
	/home/caddy/go/src/github.com/spf13/pflag/uint8.go:91 +0x59
github.com/spf13/viper.init()
	/home/caddy/go/src/github.com/spf13/viper/viper.go:1026 +0x42
github.com/spf13/hugo/create.init()
	/home/caddy/go/src/github.com/spf13/hugo/create/content.go:165 +0x42
github.com/spf13/hugo/commands.init()
	/home/caddy/go/src/github.com/spf13/hugo/commands/version.go:76 +0x5e
github.com/hacdias/caddy-hugo/utils.init()
	/home/caddy/go/src/github.com/hacdias/caddy-hugo/utils/utils.go:208 +0x42
github.com/hacdias/caddy-hugo.init()
	/home/caddy/go/src/github.com/hacdias/caddy-hugo/hugo.go:135 +0x4c
github.com/mholt/caddy/config.init()
	/tmp/custombuild_5197_315274122/src/github.com/mholt/caddy/config/directives.go:52 +0x4f
main.init()
	/tmp/custombuild_5197_315274122/src/github.com/mholt/caddy/main.go:174 +0x47

full log:
http://termbin.com/gpms

**Comment by anthonyfok** [comment]
Hi @jungle-boogie,

Thank you for filing this issue.  Could you please tell us what the steps/commands to use to reproduce this "index out of range" runtime error panic?  Many thanks!

**Comment by jungle-boogie** [comment]
Hi @anthonyfok,

I'm trying to get caddy running with inetd on freebsd and I don't think my inetd service is correct, but I don't think I should see the error.

in my `etc/services/`:

    caddy           2021/tcp # caddy webserver

in my `/etc/inetd.conf`

    caddy  stream tcp nowait.1000 sean /home/sean/bin/caddy/caddy

My Caddyfile:

    example.com:2020 {
    log access.log
    ext .txt .csv
    proxy / http://10.132.5.134:8080 {
    proxy_header X-Real-IP {remote}
        proxy_header Host {host}
        }
     }

    example.com:2021 {
    log access.log
    gzip
    ext .txt .csv
    search
    browse
    root /home/sean/site
    search
    }

**Comment by moorereason** [comment]
@hacdias, care to help here?

**Comment by hacdias** [comment]
Hi!

@jungle-boogie where is the ```hugo``` directive placed on your Caddyfile? Are you using ```caddy-hugo```?

**Comment by jungle-boogie** [comment]
Hi,

I'm using Caddy with hugo built in with it from http://caddyserver.com/download

Thanks!

**Comment by hacdias** [comment]
But why are you using Caddy with Hugo built in it if you're not using it?

**Comment by jungle-boogie** [comment]
Would that cause the crash?

**Comment by hacdias** [comment]
That's strange. I think @spf13 could help because of what I can see in the error above, the root of the error is in spf13/flag.

**Comment by moorereason** [comment]
@jungle-boogie, if you add the `hugo` directive to your Caddyfile, does the panic go away?

@hacdias, I suspect that it has something to do with `caddy-hugo` importing `github.com/spf13/hugo/commands`, but I can't think of reason why that would cause a panic.

**Comment by jungle-boogie** [comment]
Hi @moorereason,

No, the panic does not go away. 

Go to http://jungleboogie.me:2021/ and see the error. If you refresh, you'll notice that everything below `main.init()` changes between refreshes.


I also see references to blevesearch/bleve

**Comment by bep** [comment]
This issue belongs to caddy-hugo.

I'm sorry, but we have to scope the issues here if we're gonna have a chance to handle them all.

**Comment by jungle-boogie** [comment]
Thanks for the assistance, @bep.

I will raise an issue with https://github.com/hacdias/caddy-hugo
