### ISSUE TITLE
static folder content isn't copied over when used theme doesn't have one

### ISSUE THREAD

**Issue by ifraixedes** [spf13/hugo#1655]
I have created a new hugo site and I observed one behaviour with hugo v0.15.

1. I have a theme which doesn't have a static folder
2. The site uses that theme
3. Site has a static folder
4. `hugo` create public directory with the content except the content inside of "static" folder. It happens with `server` command too.

My current workaround is to create an empty "static" folder in the theme directory and then `hugo` copy the content inside of "static" into the "public" directory (or the specified output directory) as expected.

**Comment by tatsushid** [comment]
It seems to be caused by around https://github.com/spf13/hugo/blob/master/commands/hugo.go#L370.

If there is not "static" directory in theme directory, it always returns an error from https://github.com/spf13/hugo/blob/master/helpers/path.go#L220 and later copy processes are skipped.

**Comment by anthonyfok** [comment]
Fixed by @tatsushid in Pull Request #1656 in commit 6c81031.
