### ISSUE TITLE
question: which theme is the one for hugo documentation?

### ISSUE THREAD

**Issue by jeffpeiyt** [spf13/hugo#1658]
This is great. We need a template with drop down menus (better to have multiple level support) such as http://www.mkdocs.org/

Wonder which theme makes the hugo doc http://gohugo.io/overview/introduction/ ?  or would be great to suggest any theme that has readthedocs kind of theme... 

Thanks much!

**Comment by anthonyfok** [comment]
Please see:

* Issue #715 - "Where is the theme used by hugo's own docs?".

See also the Hugo [Site Showcase](http://gohugo.io/showcase/) where both the LearnOverpass site and especially the recently added **Camunda Docs site** provides a documentation theme with source, under MIT and Apache-2.0 licenses respectively.

For further discussion, please visit https://discuss.gohugo.io/ and comment on the thread at https://discuss.gohugo.io/t/theme-based-on-hugo-doc-theme/232 .

Cheers,
Anthony
