### ISSUE TITLE
Add something like {{ .Site.TemplateRole }}

### ISSUE THREAD

**Issue by studiomohawk** [spf13/hugo#166]
It would be very handy to be able to tell which template roles Hugo uses.

A variable `TemplateRole` most likely will be used with Chrome Templates in sutuation something like below:

`{{ if .Site.TemplateRole "Homepage" }}`

or 

`<body class="{{ .Site.TemplateRole }}">` will yield something like:

```
<body class="homepage"> <!-- in homepage -->
<body class="content-li"> <!-- in li -->
<body class="content-single"> <!-- in single -->
```

according to rendered template.
I believe this capability will add more flexibilities to chrome template.

**Comment by bep** [comment]
We currently have:

´´´
* IsPage: Single page
* IsNode: home page, taxonomy page or section list
* IsHome: home page
´´´

Does that cover this issue?

**Comment by bep** [comment]
No response to my question, so I'll assume the answer was yes.
