### ISSUE TITLE
Hugo log contains entries with "thatswhyyoualwaysleaveanote.go"

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#1660]
Not sure if it is a problem with Hugo itself or with https://github.com/spf13/jWalterWeatherman,
but the final lines the log file generated by `hugo --logFile=/tmp/hugo.log` contains `thatswhyyoualwaysleaveanote.go`, the jWalterWeatherman source file that actually prints the lines to the output file:

```
LOG:   2015/12/02 00:56:36 thatswhyyoualwaysleaveanote.go:175: 0 draft content
LOG:   2015/12/02 00:56:36 thatswhyyoualwaysleaveanote.go:175: 0 future content
LOG:   2015/12/02 00:56:36 thatswhyyoualwaysleaveanote.go:183: 164 pages created
LOG:   2015/12/02 00:56:36 thatswhyyoualwaysleaveanote.go:183: 0 paginator pages created
LOG:   2015/12/02 00:56:36 thatswhyyoualwaysleaveanote.go:183: 41 tags created
LOG:   2015/12/02 00:56:36 thatswhyyoualwaysleaveanote.go:183: 0 groups created
LOG:   2015/12/02 00:56:36 thatswhyyoualwaysleaveanote.go:183: in 2387 ms
```

This problem affects Hugo v0.11 to v0.15 as well as 0.16-DEV (current HEAD) as of today.

**Comment by tatsushid** [comment]
The `thatswhyyoualwaysleaveanote.go` string is printed by `LOG.Println(v...)` or `LOG.Printf(format, v...)` in that file.

To fix it, we should modify jWalterWeatherman. Should it print a caller file or be silent on a file name?

**Comment by tatsushid** [comment]
I sent a [PR](https://github.com/spf13/jWalterWeatherman/pull/8) to make the logger output its caller's file name and line.

**Comment by anthonyfok** [comment]
:clap:

**Comment by tatsushid** [comment]
The [PR](https://github.com/spf13/jWalterWeatherman/pull/8) was merged and I confirmed it worked.

**Comment by anthonyfok** [comment]
Nice, very nice!  I really like the new output that your PR spf13/jWalterWeatherman#8 now generates, e.g.:

```
LOG:   2016/01/01 02:48:51 site.go:1395: 0 draft content
LOG:   2016/01/01 02:48:51 site.go:1396: 0 future content
LOG:   2016/01/01 02:48:51 site.go:1397: 10 pages created
LOG:   2016/01/01 02:48:51 site.go:1398: 38 paginator pages created
LOG:   2016/01/01 02:48:51 site.go:1402: 20 tags created
LOG:   2016/01/01 02:48:51 site.go:1402: 13 categories created
LOG:   2016/01/01 02:48:51 site.go:1402: 3 series created
LOG:   2016/01/01 02:48:51 hugo.go:534: in 332 ms
```

Thank you @tatsushid!  And Happy New Year!  :-)
