### ISSUE TITLE
time.Now template function

### ISSUE THREAD

**Issue by thrisp** [spf13/hugo#1663]
Is there a template function for the current date? I did not see one. I am conversant enough with go templates to add my own, but not here in this setup without forking & creating my own version (which is a pain, and obviously ineffective just to get a function that prints the current year which is what I need to do).

**Comment by bep** [comment]
There is a `Now` func on `Node`, so `.Now` should work ... Not sure why that's how it was implemented ... Lots of examples/discussions about this one the forum.
