### ISSUE TITLE
Mention Mmark math (MathJax/KaTeX) support in docs

### ISSUE THREAD

**Issue by oblitum** [spf13/hugo#1666]
Duplicating discussion here, since it looks like feasible through Mmark, which has been adopted recently.
- https://discuss.gohugo.io/t/mathjax-and-katex-support/2205

From Mmark README:

> -   **Math support**, use `$$` as the delimiter. If the math is part of a paragraph it will
>    be displayed inline, if the entire paragraph consists out of math it considered display
>    math. No attempt is made to parse what is between the `$$`.

Is this already working? What are the steps to use Mmark and have this enabled?

If it's OK for being used, I guess the official hugo docs about MathJax support could be updated with this information.

If it's not working, I'd propose for the issue to keep open (in case it's not a "won't fix") to target enabling it for Mmark.

**Comment by moorereason** [comment]
Create `.mmark` files in your `content` folder instead of `.md` files.

Use the [discussion forum](https://discuss.gohugo.io/) to ask questions.

**Comment by donbright** [comment]
Here is my test. I ran the standard setup on linux as instructed here

http://gohugo.io/overview/quickstart/

I created two files under 'content', about.md and about.mmark

```
+++
date = "2015-12-04T22:28:34-06:00"
draft = true
title = "about.md"

+++

Hello $x^2=y^2$ World

$$ x^2 = y^2 $$
```

```
+++
date = "2015-12-04T22:28:34-06:00"
draft = true
title = "about.mmark"
+++

Hello $$x^2=y^2$$ World

$$ x^2 = y^2 $$

```

Then I edited ../theme/hyde/layouts/partials/head.html as per http://gohugo.io/tutorials/mathjax/  (with the recommended javascript and CSS added to the bottom of head section)

With the solution , added to  it rendered as follows

![hugo2](https://cloud.githubusercontent.com/assets/896858/11610328/3a16b904-9b65-11e5-9aa2-65babe6bf93b.png)


Then i removed the javascript solution. It rendered as follows

![hugo1](https://cloud.githubusercontent.com/assets/896858/11610326/24f72310-9b65-11e5-943f-82605fa96448.png)

**Comment by oblitum** [comment]
ok, waiting ;-)

**Comment by oblitum** [comment]
The orange thing is exquisite, but thanks for trying it all through. It looks like Mmark already can be employed just like its documentation, without the extra javascript and backquotes, which could be added to current gohugo docs.

**Comment by JimAmuro** [comment]
I have found the reason for the orange thing. If you right click on the equations and choose Math settings->math renderer->Common HTML instead of HTML-CSS by default, you shall see decent black equations. But I don't know how to make it default when other people is visiting this site... Is it the problem of hyde theme? I really have no idea...

**Comment by oblitum** [comment]
@JimAmuro Thanks.

**Comment by oblitum** [comment]
I've been using GitLab Pages hosted Hugo with KaTeX over Mmark to great effect, it works like a charm.

**Comment by oblitum** [comment]
I've been using GitLab Pages hosted Hugo with KaTeX over Mmark to great effect, it works like a charm, no hacks to setup.

http://nosubstance.me/post/a-great-toolset-for-static-blogging/

**Comment by senykam** [comment]
Got Hugo working with Mmark and Mathjax. The only issue that came up was with display-mode equations and with references. The problem was the following from the Hugo docs: 
```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['$','$'], ['\\(','\\)']],
    displayMath: [['$$','$$'], ['\[','\]']],
    processEscapes: true,
    processEnvironments: true,
    skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
    TeX: { equationNumbers: { autoNumber: "AMS" },
         extensions: ["AMSmath.js", "AMSsymbols.js"] }
  }
});
</script>
```
This makes Mathjax interpret `[...]` blocks as display-mode equations whereas Mmark outputs `\[...\]` blocks for display-mode equations. 

To fix use `displayMath: [['$$','$$'], ['\\[','\\]']]` above

**Comment by rdwatters** [comment]
New docs take care of this (including the `displayMath` gotcha):

https://hugodocs.info/content-management/formats/#solution

**Comment by oblitum** [comment]
@rdwatters it fails to mention that Mmark is a whole alternative solution to all the hacks and fixes suggested in that page. Mmark simply works. From the modest mention one can think that the MathJax fixes are still necessary when using Mmark while in truth MathJax just works out of the box with it.

**Comment by oblitum** [comment]
I don't consider the "if you're using Mmark" short passage a solution to this issue at all...

**Comment by rdwatters** [comment]
@oblitum 

> it fails to mention that Mmark is a whole alternative solution to all the hacks and fixes suggested in that page

Are the Hugo docs intended to extol the virtues of Mmark, which is supported through an external helper, or is that documentation that should fit in with...Mmark.  (This is a legitimate question and I am by no means trying to be snide; I don't know enough about MathJax to really make that call.)

That said, I'd certainly appreciate a PR for suggested content revisions:

https://github.com/rdwatters/hugo-docs-concept

**Comment by oblitum** [comment]
@rdwatters that section is a FAQ on MathJax and Mmark is just a dropin solution to many of the issues mentioned there, no need to extol, just mention that it's a solution that happens to be because gohugo ends up using its parser.

Notice that I _discovered_ this because I checked sources to know what parsers gohugo were actually using at the time. From the two I've seen I learned that Mmark was a Markdown superset that covered MathJax/KaTeX without need to worry about using divs and other fixes.

One should learn that from Mmark parser docs indeed. Duplicating it in GoHugo FAQs is not the intention of the issue but just pointing that Mmark is a supported dialect in GoHugo and that it supports MathJax/KaTeX without issues.

**Comment by oblitum** [comment]
@rdwatters also, AFAIK, the Mmark parser is built in to gohugo like the default parser, not an external helper that needs an external tool to be installed.

**Comment by rdwatters** [comment]
@oblitum Excuse my ignorance on these matters. I re-opened this issue, but you can see the changes I've made to the upcoming docs here:

https://hugodocs.info/content-management/formats/#mmark

**Comment by oblitum** [comment]
@rdwatters that's fine but the it solves one of the issues, which is the mention of Mmark support, the other issue is that the section on MathJax has a subsection "Issues with Markdown", issues that don't apply when using Mmark because it covers MathJax already and as such is a natural solution to the "Issues with Markdown" presented there.

**Comment by oblitum** [comment]
@rdwatters relevant docs about that: https://github.com/miekg/mmark/wiki/Syntax#math-blocks. With the parser supporting this, there's no need to worry about the issues mentioned at "Issues with Markdown" and "Solution".

**Comment by rdwatters** [comment]
And for users creating content with just markdown/BlackFriday rather than MMark and still using MathJax? Wouldn't they still run into the "Issues with Markdown?"

**Comment by oblitum** [comment]
Yes.

Knowing that GoHugo supports a parser builtin where math is a non-issue may be useful information to math interested users.

**Comment by oblitum** [comment]
https://github.com/spf13/hugo/issues/1666#issuecomment-162250842

**Comment by rdwatters** [comment]
Thank your for all the feedback @oblitum. At this point, I think this is more than sufficient:

https://hugodocs.info/content-management/formats/#issues-with-markdown

**Comment by oblitum** [comment]
@rdwatters Thanks for all additions.

**Comment by rdwatters** [comment]
@oblitum My pleasure, brother. I appreciate your patience and expertise on this. Hopefully it drives some people to your blog as well :smile: Cheers!
