### ISSUE TITLE
Using variables in content

### ISSUE THREAD

**Issue by wayneashleyberry** [spf13/hugo#1670]
Being able to use variables in content such as `.RelPermalink` would be very useful :)

**Comment by michaelthorne** [comment]
+1

**Comment by bep** [comment]
This is what shortcodes where built for.

**Comment by wayneashleyberry** [comment]
@bep is it possible to get access to variables like `.Title` and `.Description` in a shortcode template?

**Comment by bep** [comment]
```
{{ .Page.Title }}
```
Etc.

**Comment by wayneashleyberry** [comment]
Oh awesome! That's great, thanks @bep
