### ISSUE TITLE
Can't filter out draft pages

### ISSUE THREAD

**Issue by tucnak** [spf13/hugo#1673]
I've got an `article` archetype and a bunch of draft and non-draft pages. That's what I'm trying to do:
```
// here $articles are legit and refer to all articles
{{ $articles := (where .Site.Pages "Type" "article") }}

// $articles is empty after this
{{ $articles := (where .Site.Pages "Draft" "false") }}
```

I double-checked: `$articles` from the first action is of type `hugolib.Pages` and consists of all the articles. I can't see a reason why it fails to sort drafts out.

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions.
