### ISSUE TITLE
Add support for pre-compressed gzip files

### ISSUE THREAD

**Issue by teran-mckinney** [spf13/hugo#1674]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=28880925)](https://www.bountysource.com/issues/28880925-add-support-for-pre-compressed-gzip-files?utm_source=28880925&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Most of the discussion around this has been in #1251. It seems these should be broken up into different parts, so this is the one I care the most about.

This is a feature request to have gzip -9'ed files generated along side the finished HTML, CSS, JS, etc.

**Comment by mjanda** [comment]
Instead of gzip -9, why not use zopfli? Compatible and better compression.

**Comment by teran-mckinney** [comment]
Never heard of it before, so I looked it up: https://github.com/google/zopfli

Sounds like it could be even better. May want to make a Go binding for zopfli for a cleaner integration here.

**Comment by teran-mckinney** [comment]
I did one test and zopfli took 1m4s vs 0.4s for gzip -9. The output was less than 1% smaller.

Do you have any benchmarks showing it being worthwhile?

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by zivbk1** [comment]
I think that with Pipes in place, one of the last bits to finish the pipeline of generating a site for production would be to compress the files before pushing them to the hosting provider.  It seems that other cases like this have gone stale and closed. I am hoping that this feature request can be reopened and used to implement this capability in Hugo.

**Comment by zivbk1** [comment]
@bep now that you have implemented minification, can we open this issue back up to add gzip compression as a final step?

**Comment by bep** [comment]
No.

**Comment by mateusfccp** [comment]
It would be great to have gzip and brotli on assets compilation.

Any reason why it won't be implemented? Design decisions or manpower? Maybe I could help.

**Comment by LeonB** [comment]
It would be nice to have this feature. With my current middleman site I gzip everything before rsyncing it to the server and let apache service the *.gz files directly.

**Comment by pierredewilde** [comment]
I have naively tried `hugo server --minify --compress` but it does not work &#x1F914;

The idea was to catch performance issues with DevTools Lighthouse in _production-like_ mode.

Of course, we can do it with `hugo --minify` and serve `/public` with another HTTP server. 
But it would be nice if it was built-in within Hugo.
