### ISSUE TITLE
Hugo v0.15-DEV - Server Watch Not Working

### ISSUE THREAD

**Issue by tuxy** [spf13/hugo#1676]
Command such as; ``hugo server -w -b http://domain.com --appendPort=false``
no longer works under v0.15-DEV Using v0.14 as a workaround for now =((

**Comment by anthonyfok** [comment]
How come you are using v0.15-DEV and not v0.15 official release?
And what about v0.16-DEV?

By the way, `hugo server` now has `--watch=true` by default, so you no longer need to specify `-w` on the command line, though it shouldn't hurt.

**Comment by tuxy** [comment]
I've just re-checked and yes I was using v0.16-DEV but for some reason even v0.15 did not work for me, but I'll check again. Thanks.

**Comment by bep** [comment]
Please reopen if still an issue.

**Comment by tuxy** [comment]
I'm still using v0.14 will test newer one later and report back.
