### ISSUE TITLE
Unable to build from head

### ISSUE THREAD

**Issue by sjug** [spf13/hugo#1681]
$ go version
`go version go1.2.1 linux/arm`

$ go build -o hugo main.go
`# github.com/spf13/hugo/bufferpool`
`bufferpool/bufpool.go:21: undefined: sync.Pool`

**Comment by dirceu** [comment]
`sync.Pool` was [introduced in Go 1.3](https://golang.org/doc/go1.3), but the older version listed in the [Travis config](https://github.com/spf13/hugo/blob/6a519e692ba55d25ceb3a57e5c815f9b91daaebb/.travis.yml) is 1.4.3; either way, you need to update Go.

**Comment by anthonyfok** [comment]
Your Go version is too low.  You need at least Go 1.4 to compile Hugo, but Go 1.5.2 is recommended.

Please read the README.md for instructions on how to build Hugo from source.  The recommended build command, which also fetches Hugo's dependencies, is

```
go get -u -v github.com/spf13/hugo
```
