### ISSUE TITLE
Hugo compiled with go1.6 branch gives template errors with some themes

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#1683]
When using a `hugo` binary compiled with the go1.6 development branch, some themes give errors related to template parsing.  For example, with `hugo -t casper`, errors like these pop up:

```
ERROR: 2015/12/07 template: theme/partials/li.html:10:21:
  executing "theme/partials/li.html" at <index .Site.Data.aut...>:
    error calling index: value is nil; should be of type string in theme/partials/li.html
```

The line in question in themes/casper/layouts/partials/li.html is:

```
        {{$author := index .Site.Data.authors .Params.author }}
```

`hugo-compiled-with-go1.6` still finishes rendering the website without aborting, though the layout/formatting was off.

Meanwhile, `hugo` compiled with go1.5.x runs `hugo -t casper` perfectly fine without error.

**Comment by anthonyfok** [comment]
For reference, from https://golang.org/pkg/text/template/, the predefined template global function `index` does the following:

>	Returns the result of indexing its first argument by the
>	following arguments. Thus "index x 1 2 3" is, in Go syntax,
>	x[1][2][3]. Each indexed item must be a map, slice, or array.

So, at first glance, `index .Site.Data.authors .Params.author` would be interpreted in Go syntax as something like .SiteData.authors[.Params.author], which doesn't quite seem to make sense, so, perhaps the theme's `li.html` has an error that was left undetected in go1.5 but will be correctly detected in go1.6?  Not sure yet.  I still have to figure out how `index` work exactly.  :-)

**Comment by moorereason** [comment]
Does this fix it?

```
{{ $author := index .Site.Data.authors (.Params.author) }}
```

**Comment by tatsushid** [comment]
The argument check was introduced at upstream https://github.com/golang/go/commit/6599450016244b9e3e074e87d7064219ee2e5cf8. According to this commit, `index` ignores `nil` second argument and returns `reflect.Zero` value silently till this commit so no error occurred. I guess there is an article which doesn't have `author` frontmatter value and it causes the error with go 1.6.
