### ISSUE TITLE
Dynamic reloading of config file not always reliable

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#1684]
This new feature in v0.15: "Add support for dynamic reloading of config file when watching" (commit bccf957) is a welcomed addition, but may not work reliably for all OSs or text editors.  See spf13/viper#142 and go-fsnotify/fsnotify#80.

**Comment by anthonyfok** [comment]
Related issues:

* Issue #1053: File change watcher is not working in TextMate2 on Mac
* go-fsnotify/fsnotify#17: Atomic saves in text editors cause havoc, unable to watch individual files

**Comment by bep** [comment]
Once this is merged we can close this:

https://github.com/go-fsnotify/fsnotify/pull/111

**Comment by derekperkins** [comment]
Also related: #1840 Duplicate pages created
