### ISSUE TITLE
Incorrect information about ghost

### ISSUE THREAD

**Issue by jabyrd3** [spf13/hugo#1688]
'This means that, unlike systems like WordPress, Ghost and Drupal, which run on your web server expensively building a page every time a visitor requests one'

This section in the introduction of the docs is incorrect regarding ghost; all pages outside of the admin interface are static.

**Comment by anthonyfok** [comment]
Done!  Thank you @jabyrd3 for your insight, and thank you @moorereason for the revision!
Fixed in PR #1688.
