### ISSUE TITLE
Jinja support in Hugo

### ISSUE THREAD

**Issue by codefx9** [spf13/hugo#1697]
Hi,
We are really liking Hugo. Thanks for the great software. We would like to see Jinja template support in Hugo. My questions are:

 * Is there any plan to add support for Jinja(via flosch/pongo2 maybe) templates?
 * If there is no plan to add Jinja support by the core team, are you folks interested in accepting code contribution to this regard? Is there any guide on how to add new template support?

Thanks.

**Comment by digitalcraftsman** [comment]
Hello @codefx9,

there is already an issue (#1359) with the request of adding support for pongo2. Your effort could maybe give this enhancement a push.

**Comment by codefx9** [comment]
@digitalcraftsman, thanks for pointing this out. Closing this one.
