### ISSUE TITLE
`hugo import jekyll` fails if unrecognized files exist

### ISSUE THREAD

**Issue by antifuchs** [spf13/hugo#1705]
Congrats on the new release, I couldn't be more excited about the new `import jekyll` command! I just tried it out on [my existing octopress blog](https://github.com/antifuchs/octopress), but it reported an error - it sounds like I opened the _posts directory in Finder one time:

```
$ hugo import jekyll --verbose --log=true ~/Documents/Blog/ ./
Importing...
ERROR: 2015/12/13 Parse filename error: .DS_Store
filename not match
```

Not sure what behavior would be best there (I suppose this is to catch the case where the importer isn't able to infer what kind of file it's seeing), but maybe this could be made a warning and not an error.

**Comment by bep** [comment]
Yes, it should be a warning. Thanks for the report.
