### ISSUE TITLE
Integrate textql

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1718]
Hugo can read CSV files ... It would be cool to integrate this cool little Go lib: 

https://github.com/dinedal/textql

**Comment by ffrizzo** [comment]
@bep can you give me a direction about this? What's your idea?

**Comment by digitalcraftsman** [comment]
The package looks interesting but it would be great to have an example usecase

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
