### ISSUE TITLE
ERROR: reflect: call of reflect.Value.Type on zero Value

### ISSUE THREAD

**Issue by waddlesplash** [spf13/hugo#1722]
Copying this example straight out of the documentation (https://gohugo.io/templates/functions/#where:904d9cf85d985550c869e6d9741448cc):
```
	{{ range where .Data.Pages "Section" "!=" "post" }}
		{{ .Content }}
	{{ end }}
```
Hugo v0.15 outputs two "ERROR: reflect: call of reflect.Value.Type on zero Value" messages (I have only 2 posts in the site currently, so this makes sense.)

The test seems to work as intended (looking at the output), but the error message remains.

**Comment by waddlesplash** [comment]
I'm on Windows x64, Hugo AMD64, Windows 10.

**Comment by waddlesplash** [comment]
Oh, my mistake. This is causing an issue -- on a page I didn't notice before. It occurs on an article page, when that code appears in one of the partials the page layout includes. That appears to be the only way to reproduce this.

**Comment by bep** [comment]
The error is produced by Go's stdlib, I wish it was clearer -- but I don't think we can do anything about it. .Data.Pages isn't available on content pages, so don't use it in page templates.
