### ISSUE TITLE
Add an option to use pygments with fenced code blocks

### ISSUE THREAD

**Issue by hynek** [spf13/hugo#1731]
Hi,

most of my blog posts contain some amount of source code and I’m using the semi-standardized GitHub fenced code blocks that are semi-supported by editors.

In that case, client-side rendering is used which I find very unfortunate because:

1. it slows down rendering for the *reader*
2. it adds another external dependency that has to be loaded which is another slowdown
3. it's lacking languages I need (most notable Python console sessions)

To use server-side rendering I have to use your shortcode that isn't supported by *any* editor and which breaks all markup: either I have to indent my code which the shortcode doesn’t remove or the source code is interpreted like Markdown.

I find it also a bit odd to be the default because to me, static rendering is about speed *for the user*; build times are only secondary.

***

Is there any chance that you could add a switch that makes GitHub code blocks use pygments?

I’m sorry if this is an FAQ, I couldn’t find anything relevant…

**Comment by bep** [comment]
It is in the 0.15 release notes, but not in the documentation I see (I will create an issue for that).

But set:

```
pygmentscodefences: true
```

Or similar in YAML.
