### ISSUE TITLE
Bugs in internal opengraph.html template 

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#1733]
(writing these down before I forget)

Found two bugs in the internal opengraph.html template while I was testing a new theme:
1. `ERROR: 2015/12/27 reflect: call of reflect.Value.Type on zero Value in theme/partials/head.html`
2. opengraph.html's "see_also" would not work if the name of the series is not "sanitized", i.e. all lowercase and space-changed-to-hyphen.

For Bug 1, it turns out that:
1. The said theme loads `{{ template "_internal/opengraph.html" . }}` in its layouts/partials/head.html file.
2. I had `series` defined in the front matter in one of my Markdown content files.
3. But I did not have `series = "series"` under `[taxonomies]` in config.toml, so `.Site.Taxonomies.series` is not defined.
4. opengraph.html uses an equivalent of `{{ index .Site.Taxonomies.series $name }}` without checking first whether `.Site.Taxonomies.series` is defined or not, leading to the rather cryptic error message from Go template's `index`: `reflect: call of reflect.Value.Type on zero Value`  (Maybe an issue to be filed against Go to be more informative in its error message...)

For Bug 2:
1. Say we have `series = [ "Hugo is my life", "Chinese 中文" ]` defined in the front matter of one of the content files.
2. In the "keyPrep" function named `kp()` in hugolib/taxonomy.go, the keys are processed through helpers.MakePathSanitized() before being stored inside `.Site.Taxonomies.series`.
3. Currently, opengraph.html goes through each key in `Params.series`, sets it as `$name` without preprocessing, and tries to matches it with the ones listed in `.Site.Taxonomies.series` by using the equivalent of `{{ index $.Site.Taxonomies.series $name }}`.
4. But we would than have mismatches such as `Hugo is my life` vs `hugo-is-my-life`, and `Chinese 中文` vs `chinese-中文`.

In http://npf.io/2014/08/making-it-a-series/, @natefinch preprocesses `$name` like this:

``` go
{{ $name := $name | urlize }}
```

which would change `Hugo is my life` to `hugo-is-my-life`, allowing `index` to match properly.
However, it would also change `Chinese 中文` to `chinese-%E4%B8%AD%E6%96%87`...

A possible solution is to expose helpers.MakePathSanitized() as template functiion `makePathSanitized` so we can use `{{ $name := $name | makePathSanitized }}`.  This way, non-ASCII Unicode strings like `Chinese 中文` can be properly transformed to `chinese-中文`, matching what `kp()` does.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by bep** [comment]
If this still is an issue, please remove the stale label, else close.
