### ISSUE TITLE
Unable to do Quick Start due to issues with Hyde

### ISSUE THREAD

**Issue by cfjedimaster** [spf13/hugo#1749]
Following the Quick Start, when I do 

hugo server --theme=hyde --buildDrafts

I get a large number of errors, all roughly the same:

ERROR: 2016/01/03 template: theme/partials/sidebar.html:4:23: executing "theme/partials/sidebar.html" at <.Site.BaseURL>: BaseURL is not a field of struct type *hugolib.SiteInfo in theme/partials/sidebar.html
ERROR: 2016/01/03 template: theme/partials/head.html:14:39: executing "theme/partials/head.html" at <.Site.BaseURL>: BaseURL is not a field of struct type *hugolib.SiteInfo in theme/partials/head.html
ERROR: 2016/01/03 template: theme/partials/sidebar.html:4:23: executing "theme/partials/sidebar.html" at <.Site.BaseURL>: BaseURL is not a field of struct type *hugolib.SiteInfo in theme/partials/sidebar.html
ERROR: 2016/01/03 Error while rendering 404 page: template: theme/404.html:8:123: executing "theme/404.html" at <.Site.BaseURL>: BaseURL is not a field of struct type *hugolib.SiteInfo

**Comment by bep** [comment]
You use an old version of Hyde. Please update.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to the [Hugo Discussion Forum](https://discuss.gohugo.io/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by cfjedimaster** [comment]
I got this because the documentation says to use Brew as the easiest option and the Brew version is old. Therefore, this bug should be reopened, right? Or at least a new bug filed to update the version available via Brew. Right? (If no bug exists, I'll file one.)

**Comment by bep** [comment]
The Brew version should be up to date. Try a "brew upgrade". This is a case for the discussion forum. We got plenty of real issues and not too many people to handle it. Remember, this is an open source project with people doing free work on their spare time.

**Comment by cfjedimaster** [comment]
I understand what an OS project is and I manage plenty of my own. If a user follows the directions the site provides and it doesn't work, is that not a bug in the documentation versus a support request? What exactly am I doing wrong here? And as far as I know, I had no previous version of Hugo and installed fresh yesterday.

**Comment by cfjedimaster** [comment]
As an FYI, and I'm new to brew, but "brew info hugo" shows hugo: stable 0.13, HEAD

**Comment by digitalcraftsman** [comment]
I'm not a homebrew user but a quick look in the repository [showed](https://github.com/Homebrew/homebrew/blob/0d4d3fa097428b1bcb5442942113938d82ede78b/Library/Formula/hugo.rb#L6) that the latest release v0.15 is the newest listed one.

**Comment by cfjedimaster** [comment]
@digitalcraftsman - right - which is the version you get if you download manually, but not via brew. As I've said, if the issue is "someone needs to push new bits to Brew", I'm happy to file a new report. But right now,a new user (like me :) can't go through the quick start because of this issue.

**Comment by bep** [comment]
Brew and Hugo 0.15 is confirmed to work. If you have problems with Brew, please file an issue on their repo.

**Comment by cfjedimaster** [comment]
So are you saying an install from Brew, which according to brew info is 0.13, should work? Or are you saying Brew should install 0.15? Am I using brew info wrong?

**Comment by digitalcraftsman** [comment]
Other people had problems with the installations via brew too. According to [this thread](https://discuss.gohugo.io/t/hugo-0-14-in-homebrew/1581/4), do this commands resolve your issue?

    brew rm Hugo
    brew upgrade
    brew install hugo

**Comment by cfjedimaster** [comment]
Did that, and I still get 0.13. brew info hugo still say s0.13 too. brew reports as version 0.9.5.

**Comment by cfjedimaster** [comment]
Ahah - it was brew update, then upgrade, and that got me going. So it seems like the brew CLI is fundamentally at fault here. If a user is told to use brew to install some app, they will *always* need to brew update first to ensure they have the latest definitions, which makes it seem like a pretty bad flaw in how brew works. Either way, since it seems like more than myself have been hit by this, does it make sense to edit the docs to add a small warning? Even *one* line would clear it up I think. (And I can file another bug for that.)

**Comment by anthonyfok** [comment]
See also #824, #1067, #1537 and #1633

**Comment by anthonyfok** [comment]
Thanks for the great suggestion, @cfjedimaster!   I have just updated the documentation to say `brew update && brew install hugo` instead of just `brew install hugo`.  Hope that will prevent other new brew and Hugo users from running into brew-related installation problems.  :wink:

**Comment by cfjedimaster** [comment]
That's perfect - thank you (everyone) for the help. Loving Hugo.

On Tue, Jan 5, 2016 at 12:45 AM, Anthony Fok <notifications@github.com>
wrote:

> Thanks for the great suggestion, @cfjedimaster
> <https://github.com/cfjedimaster>! I have just updated the documentation
> to say brew update && brew install hugo instead of just brew install hugo.
> Hope that will prevent other new brew and Hugo users from running into
> brew-related installation problems. [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spf13/hugo/issues/1749#issuecomment-168918107>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
