### ISSUE TITLE
Hugo 0.15 not responding to server command

### ISSUE THREAD

**Issue by cfjedimaster** [spf13/hugo#1750]
Following the directions here, https://gohugo.io/tutorials/installing-on-mac/, option 2, I can use Hugo to make a new site and new content, but when I tell it to run the server, I get nothing. No error, no output, it just hangs.

➜  site  hugo version                          
Hugo Static Site Generator v0.15 BuildDate: 2015-11-25T14:35:20-06:00
➜  site  hugo server --theme=hyde --buildDrafts

**Comment by cfjedimaster** [comment]
FYI, if I do hugo server by itself, I get errors (this is just the top portion):

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2242bb]

goroutine 1 [running]:
sync/atomic.StoreUint64(0x10b12f94, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/sync/atomic/asm_386.s:190 +0xb
github.com/spf13/afero.(*InMemoryFile).Open(0x10b12f50, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/afero/memfile.go:55 +0x6d
github.com/spf13/afero.(*MemMapFs).lockfreeOpen(0x10b6eb18, 0x10c4db40, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:222 +0xf8

**Comment by cfjedimaster** [comment]
Using renderToDisk=true allows it to work ok.

**Comment by spf13** [comment]
That's very odd. Can you tell us more about the environment you are running this in?

Can you post a gist with the full output of the panic?

**Comment by cfjedimaster** [comment]
I got this while trying Hugo from the zip download. Switching to Hugo from Brew (but still 0.15), it seems to work ok.

**Comment by bep** [comment]
There has been a similar report about the 32 binary on Windows -- but I suspect it is a 32 bit vs 64 bit issue on all the platforms. 

See #1621

**Comment by eMerzh** [comment]
hi, same issue here, 32-bit archlinux...

**Comment by bep** [comment]
@eMerzh if you really need 32-bit, building one from the latest source is your only workaround. I guess this and some other issues should be a good argument for a new Hugo release in a not so distant future ...

**Comment by ghlecl** [comment]
Newbie here, so maybe I am doing things wrong, but when I do `hugo` to build my site and then `hugo serve` to see how it looks locally, nothing happens.  I did `hugo -v serve` and the messages are not really informative.  Upon reading this issue, I did `hugo serve --renderToDisk=true` and that got the server started and everything working ok.  I am on OSX El Capitan 10.11.3, have Go installed via MacPorts (which if I understand correctly should make no difference) and have hugo 0.15 installed from the website (not from HomeBrew).

**Comment by spf13** [comment]
@ghlecl Can you provide more information. Perhaps a gist of the output from `hugo serve -v`?

**Comment by ghlecl** [comment]
Sorry, not used to doing gists.  I copy pasted the command and the result of the command here:
```
[21:20:11] gh-pages$ hugo -v server --baseURL="http://localhost:1313" --bind="127.0.0.1"
INFO: 2016/02/09 Using config file: /Users/ghlecl/blog/gh-pages/config.yaml
INFO: 2016/02/09 syncing from /Users/ghlecl/blog/gh-pages/static/ to /
```
Whether I add or remove the options `--baseURL` and `--bind` makes not difference in the output.  I then try to go to http://localhost:1313/ and nothing gets displayed.  As I said, if I had the `--renderToDisk=true` option, then the "local" website is up and running and I can preview my blog.

Hope this is the info you need.  Willing to trying something else out if you need it.
Thanks.

**Comment by michaeltlombardi** [comment]
I'm seeing the same behavior as @ghlecl with a fresh pull.

```
Hugo Static Site Generator v0.15 BuildDate: 2016-03-13T19:23:39-05:00
```

Including the `--renderToDisk=true` flag causes Hugo to run as expected.

Running on i686 Arch Linux.

**Comment by gbb** [comment]
I think I have the same bug on a fairly fresh FreeBSD 10.2 install; running "hugo server" while following this tutorial (http://gohugo.io/overview/quickstart/) results in : 

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x826c4fb]  + a whole ton of spew.

Whereas --renderToDisk=true   works.

**Comment by bep** [comment]
@gbb could you post the stack trace (the spew) here? (or at pastebin or similar if too long).

**Comment by bep** [comment]
Also, to the people *seeing this with a fresh pull*: Make sure the Hugo dependencies are up to date (esp. Afero).

**Comment by gbb** [comment]
Hi @bep , here you are: 

# hugo server
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x826c4fb]

goroutine 1 [running]:
sync/atomic.StoreUint64(0x38b0fda4, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/sync/atomic/asm_386.s:190 +0xb
github.com/spf13/afero.(*InMemoryFile).Open(0x38b0fd60, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/afero/memfile.go:55 +0x6d
github.com/spf13/afero.(*MemMapFs).lockfreeOpen(0x38a06b38, 0x38b035c0, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:222 +0xf8
github.com/spf13/afero.(*MemMapFs).findParent(0x38a06b38, 0x58aee928, 0x38b0fd60, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:117 +0x89
github.com/spf13/afero.(*MemMapFs).registerWithParent(0x38a06b38, 0x58aee928, 0x38b0fd60)
	/Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:128 +0x38
github.com/spf13/afero.(*MemMapFs).lockfreeMkdir(0x38a06b38, 0x38b035c0, 0x1, 0x1ff, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:170 +0x338
github.com/spf13/afero.(*MemMapFs).registerWithParent(0x38a06b38, 0x58aee928, 0x38b0fd10)
	/Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:131 +0xc5
github.com/spf13/afero.(*MemMapFs).Mkdir(0x38a06b38, 0x38b035c0, 0x6, 0x1ff, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:192 +0x373
github.com/spf13/afero.(*MemMapFs).MkdirAll(0x38a06b38, 0x38b035c0, 0x6, 0x1ff, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/afero/memmap.go:199 +0x3d
github.com/spf13/hugo/helpers.WriteToDisk(0x38b035c0, 0x10, 0x58aee868, 0x38b3e5a0, 0x58aee180, 0x38a06b38, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/helpers/path.go:535 +0x9a
github.com/spf13/hugo/target.(*PagePub).Publish(0x38ab1860, 0x38b025c0, 0x4, 0x58aee868, 0x38b3e5a0, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/target/page.go:31 +0x94
github.com/spf13/hugo/hugolib.(*Site).WriteDestPage(0x38a56900, 0x38b025c0, 0x4, 0x58aee868, 0x38b3e5a0, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:1572 +0x164
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0x38a56900, 0x38b033d0, 0xc, 0x38b025c0, 0x4, 0x85d68e0, 0x38a3c6e0, 0x38b3a7e0, 0x5, 0x5, ...)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:1482 +0x4c3
github.com/spf13/hugo/hugolib.(*Site).RenderSectionLists(0x38a56900, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:1201 +0x50f
github.com/spf13/hugo/hugolib.(*Site).Render(0x38a56900, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:395 +0xd8
github.com/spf13/hugo/hugolib.(*Site).Build(0x38a56900, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/hugolib/site.go:246 +0x6c
github.com/spf13/hugo/commands.buildSite(0x38a15c7f, 0x1, 0x1, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:458 +0xab
github.com/spf13/hugo/commands.build(0x38a15d32, 0x1, 0x1)
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:348 +0x2db
github.com/spf13/hugo/commands.server(0x890ec40, 0x89293ac, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/server.go:149 +0x637
github.com/spf13/cobra.(*Command).execute(0x890ec40, 0x89293ac, 0x0, 0x0, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/cobra/command.go:572 +0x666
github.com/spf13/cobra.(*Command).ExecuteC(0x890e240, 0x890ec40, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/cobra/command.go:662 +0x41e
github.com/spf13/cobra.(*Command).Execute(0x890e240, 0x0, 0x0)
	/Users/spf13/gopath/src/github.com/spf13/cobra/command.go:618 +0x25
github.com/spf13/hugo/commands.Execute()
	/Users/spf13/gopath/src/github.com/spf13/hugo/commands/hugo.go:72 +0x39
main.main()
	/Users/spf13/gopath/src/github.com/spf13/hugo/main.go:24 +0x22

goroutine 7 [chan receive]:
github.com/spf13/viper.(*Viper).WatchConfig.func1(0x38a7fea0)
	/Users/spf13/gopath/src/github.com/spf13/viper/viper.go:268 +0x176
created by github.com/spf13/viper.(*Viper).WatchConfig
	/Users/spf13/gopath/src/github.com/spf13/viper/viper.go:269 +0x2c

goroutine 8 [syscall]:
syscall.Syscall6(0x4, 0x0, 0x0, 0x38a0170c, 0xa, 0x89293c8, 0x89293c8, 0x0, 0x38a017f0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/syscall/asm_freebsd_386.s:44 +0x5
syscall.kevent(0x4, 0x0, 0x0, 0x38a0170c, 0xa, 0x89293c8, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/syscall/zsyscall_freebsd_386.go:202 +0x57
syscall.Kevent(0x4, 0x0, 0x0, 0x0, 0x38a0170c, 0xa, 0xa, 0x89293c8, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.5.1/libexec/src/syscall/syscall_bsd.go:447 +0x6b
gopkg.in/fsnotify%2ev1.read(0x4, 0x38a0170c, 0xa, 0xa, 0x89293c8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/spf13/gopath/src/gopkg.in/fsnotify.v1/kqueue.go:458 +0x65
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0x38a2ad80)
	/Users/spf13/gopath/src/gopkg.in/fsnotify.v1/kqueue.go:267 +0x14b
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/Users/spf13/gopath/src/gopkg.in/fsnotify.v1/kqueue.go:61 +0x2de

goroutine 9 [select]:
github.com/spf13/viper.(*Viper).WatchConfig.func1.1(0x38a2ad80, 0x38a7fea0)
	/Users/spf13/gopath/src/github.com/spf13/viper/viper.go:243 +0x3ab
created by github.com/spf13/viper.(*Viper).WatchConfig.func1
	/Users/spf13/gopath/src/github.com/spf13/viper/viper.go:256 +0x12e

-----------------------------

**Comment by bep** [comment]
@gbb I'm pretty confident that this is fixed in the latest Afero (i.e. next Hugo release).
