### ISSUE TITLE
Shortcodes are always injected with a trailing newline.

### ISSUE THREAD

**Issue by drajmarsh** [spf13/hugo#1753]
When a shortcode is injected into a rendered page, it always includes a trailing newline character. Even if you save the shortcut file itself without a newline between the end of data and EOF, one is still added.

Consider, as a trivial but useful example, a single-line shortcode used to generate links with a particular class:

    <a href="{{ .Get 1 }}" class="external">{{ .Get 0 }}</a> 

Because of the trailing newline, you cannot use such links within brackets or at the end of a sentence without a space being visible in the rendered text between the result of the shortcode and the following close bracket or period.

For example, the following usage of the above shortcode ...

    There is a slight problem ({{< link "Issue 1750" "https://github.com/spf13/hugo/issues/1750" >}}) with the great static site generator {{< link "Hugo" "https://gohugo.io/" >}}.

... would produce the following:

    There is a slight problem (Issue 1750 ) with the great static site generator Hugo .

There does not appear to be any simple workaround for this.

**Comment by bep** [comment]
>Even if you save the shortcut file itself without a newline between the end of data and EOF, one is still added.

I don't think this is true. I suspect this is your editor adding a trailing newline. But that is a common thing, so we should probably just remove it? @spf13 thoughts?

**Comment by spf13** [comment]
@drajmarsh Does this even happen with internal shortcodes? that can't be from the editor. I've not seen this myself, but we've seen odd things before with other components.

**Comment by drajmarsh** [comment]
__@bep__
Sorry, my bad. You are absolutely right, a trailing newline keeps sneaking back into all my single-line files. This happens when I sync between my Mac and Windows machines and whenever I save in Atom or Brackets (my editors). If I use TextWrangler to properly remove the extra newline and then immediately rebuild, that solves the problem.

__@spf13__ No, they work fine.  _ref_ and _relref_ are the only internal shortcodes that generate output that is entirely inline-able and they don't add anything extra. The issue is actually with the reappearing newline at the end of my custom shortcode files.

Thus it's not a Hugo bug, but one due entirely to the tool stack that I'm currently using.

**Comment by drajmarsh** [comment]
__BTW:__ Thank you both for looking into this and for responding so promptly. I spent most of the recent holidays converting a pretty complex Drupal site and there hasn't been anything in it that I couldn't replicate using Hugo. Plus - Hugo itself has been an absolute pleasure to learn and use.

**Comment by ybizeul** [comment]
For reference I happened to have the same issue. Atom thinks it's smart to add a newline at the end of your files. Not even going to debate this, but there is a "Whitespace" package that disables that

**Comment by dkrieger** [comment]
In a Unix-like environment (which I gather is a first class environment for hugo), it is "proper" to end text files with a trailing newline. As such, might it be appropriate to add a hugo configuration flag to ignore trailing newline in shortcodes?

**Comment by countermeasure** [comment]
Just to save anyone who happens by here a few minutes...

You should be able to fix this problem by removing the trailing newline from your shortcode file with:
```
$ truncate -s -1 <filename>
```

**Comment by junedev** [comment]
If anyone comes by here and eventually finds out how to fix the problem for VSCode, please leave a note. The `truncate` command is nice but as soon as I save the file VSCode inserts the newline again although I have inserting newlines disabled in the settings.

**Comment by beausmith** [comment]
Having this issue with not being able to trip whitespace from end of shortcode files which end with a blank line.

Shorcode file `layouts/shortcodes/mailto-info.html`:
```
{{- $email := "info@example.com" -}}
<a target="_blank" href="mailto:{{- $email -}}">
  {{- with .Get "label" }}{{.}}{{else}}{{ $email }}{{end -}}
</a>
```

When I use this shortcode in a page (eg `contact.md`) like this:
```
Email us at {{% mailto %}}.
```

Then the output contains a linebreak after the output:
```
<p>Email us at <a target="_blank" href="mailto:info@example.com">info@example.com</a>
.</p>
```

I've tried updating the shortcode tag to use a dash at the end to remove whitespace but none of these remove the whitespace from the template:
```
{{% mailto -%}}
{{% mailto %-}}
```

I can truncate the shortcode file to not end with a line break, but that seems like a hack.

Anyone else have a solution?

**Comment by adrian5** [comment]
In my opinion this issue should not have been closed. All Unix systems (and their tools) will produce files that do this. A global config toggle might be the best idea. At least introduce this as an experimental flag and see if you run into issues.

**Comment by namoscato** [comment]
Here's a relevant workaround for anyone else still running into this issue: Add something like this to the end of your shortcode template:

```html
{{- print "" -}}
```

_per [Whitespace](https://gohugo.io/templates/introduction/#whitespace)_

**Comment by briandfoy** [comment]
I ended up with silliness like this, where I wrap the final text so I have something that can strip whitespace:

     https://example.com/functions/{{- .Get 0 -}}{{- if 1 -}}.html{{- end -}}

**Comment by RalphCorderoy** [comment]
POSIX defines a text file as zero or more lines with each line being zero or more characters terminated by a linefeed thus stripping the trailing linefeed off a POSIX text file results in a non-text file and commands defined to handle text files can then fail, e.g. by ignoring the last, unterminated, 'line'.

So I think Hugo must take action to remedy this problem, or at least document it and the preferred workaround. The simple example is where a shortcode is used for an abbreviation, e.g. `{{<FBX>}}` for `F.&nbsp;B.&nbsp;Xyzzy &amp; Sons`. Sticking with the current syntax for removing whitespace, could shortcodes accept an optional `-` just inside the braces before the `%` or `<>`, e.g. `{{<FBX->}}`.

But that takes control of the whitespace gobbling away from the shortcode to where it's used and needs specifying each time whereas @namoscato's workaround with `print` above doesn't. I didn't spot a better `nop` no-operation function than the `print` it uses.

(Dennis Ritchie's m4(1) macro processor had this issue and introduced `dnl` for delete up to and including newline, as if `{{dnl-}}`. :-)

**Comment by jmooring** [comment]
@RalphCorderoy In the future please raise issues like this in the [forum](https://discourse.gohugo.io/). 

When I need to chomp the trailing newline from a template, partial, or shortcode, I use a [comment](https://golang.org/pkg/text/template/#hdr-Actions). For example:

```
{{ .Get 0 }}
{{- /* Strip trailing newline. */ -}}
```

**Comment by RalphCorderoy** [comment]
Thanks for the comment idea, @jmooring. I'll switch to that.

Given Google directed me here, as it has others before me, this would seem the place to decide if a code change or documentation change is the maintainers' preference. If it's neither then users will continue having to suffer the problem, spot it, experiment with `-` in shortcodes, search the documentation but find nothing, Google, and read this whole issue for the changing state of workarounds. And some users will bail part-way through all of that and store corrupt non-POSIX text files in their repo instead.

**Comment by MartinHotmann** [comment]
I indeed had the same problem today (Hugo v82.1) and used the `{{- print "" -}}` solution from @namoscato to solve the problem.
I think its very bad behaviour from Hugo and really should be fixed globaly or at least provided a config to prevent this behaviour!

If I like a whitespace somewhere, then I place it there. If I like a newline somewhere then I again place it where I want/need it.
But a system that does thios (for me not even for all Shortcodes, but some) this is a very inconsistent behaviour which is bad practice.

@spf13 @bep may I please you to again look into this?

The behaviour is very clearly (in the generated HTML files) visible as soon as you activate `[minify]` for the output.

```
[minify]
  disableHTML = false
```

Then the expected result is "everything in one line"
But it actually does have the exact amount of lines as many ShortCodes you have.

**Comment by kcarnold** [comment]
While it might be nice for hugo to just strip whitespace from shortcodes, any solution here needs to account for situations where the author actually *does* want whitespace. Options include:

1. If the last character is a newline, remove it. This allows a shortcode to end with a blank line by ending it with *two* blank lines.
2. Always strip all whitespace. If shortcode authors want leading or trailing whitespace, they can be explicit and use `{{ print "\n" }}` or the like.
3. Leave it as is, and require shortcode authors to work around this.

I think many authors would expect Option 2 by analogy to how JSX removes whitespace. However, it risks breaking current sites. Option 1 is more conservative, but I'm not thinking of a precedent for it in other software. Perhaps it would be helpful to see examples of shortcodes where whitespace *is* necessary.

**Comment by davidsneighbour** [comment]
The option you are missing is to add simple whitespace-strip parameters to shortcodes like any other Go-template code:

```
{{- < shortcode > -}}
{{- % shortcode % -}}
```

I just recently realised that this is not possible. If implemented, all layout files would behave as one would expect them to behave.
