### ISSUE TITLE
gohugo.io: "background: fixed" desk image jitters when scrolled with mousewheel (IE11, Edge)

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#1755]
Very minor issue, but anyhow:

While testing a Windows 10 installation inside VirtualBox, I opened up the Microsoft Edge browser, and opened up http://gohugo.io/.  When I scrolled down the home page with my mousewheel, the fixed background image kind of wants to scroll with the whole page, but quickly returning to its original place.

Here are some workarounds that uses a JavaScript snippet to prevent default action with mousewheel event and scroll directly to a fixed offset:
- https://social.msdn.microsoft.com/Forums/ie/en-US/9567fc32-016e-48e9-86e2-5fe51fd67402/new-bug-in-ie11-scrolling-positionfixed-backgroundimage-elements-jitters-badly?forum=iewebdevelopment
- http://stackoverflow.com/questions/27966735/why-background-image-is-moving-when-scroll-at-ie/28529089#28529089

However, they do disable smooth-scrolling with the mousewheel...

Sites like http://www.manyrivers.fr/ seem to have found another workaround that does not sacrifice smooth-scrolling, but I don't know how.

If you know how, please help.  Many thanks!

**Comment by digitalcraftsman** [comment]
This issue will become irrelevant once the new redesign of @budparr will be deployed. Shall we close it then?
