### ISSUE TITLE
http://themes.gohugo.io/ build error?

### ISSUE THREAD

**Issue by rpdillon** [spf13/hugo#1759]
The  list of themes is  truncated at 'Github Project Page', even though there  are dozens more that appeared previously.

**Comment by bep** [comment]
@spf13 is working on it ... I think.

**Comment by spf13** [comment]
resolved. See https://github.com/spf13/hugoThemeSiteScript/commit/4ee31ec1dd88f2b9071bb9dc72f241bc10e11d75

**Comment by spf13** [comment]
@rpdillon thanks for letting us know. I hadn't seen the error yet.

**Comment by rpdillon** [comment]
Was selling a friend on Hugo and pointed him to the site when I realized the issue.   Thanks for the fast fix!
