### ISSUE TITLE
FATAL: mkdir /hugo: permission denied

### ISSUE THREAD

**Issue by jbshirk** [spf13/hugo#1765]
this is the very first [instruction given](https://github.com/spf13/hugo/issues/new) (after installing): 

> Hugo has the ability to create a skeleton site:

    $ hugo new site /path/to/site

Result: FATAL: 2016/01/09 mkdir /hugo: permission denied

Now, it's not a very warm welcome and not surprising this kind of thing happens on Mac, but it is surprising that [google site search](https://www.google.com/search?client=safari&rls=en&q=gohugo.io+permissions+denied+mkdir) turns up absolutely nothing about this, or what to do about it.

https://github.com/spf13/hugo/issues/837 appears to be a related issue, but it is more specific, and does not address the current issue.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to the [Hugo Discussion Forum](https://discuss.gohugo.io/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by jbshirk** [comment]
how could this not be a bug? 
using sudo will create in root home if not prepended by ./ but created folders are only visible to root

    joe$ sudo hugo new site /hugo/default
    Password:
    localhost:nonde joe$ ls -la
    total 0
    drwxr-xr-x+   2 joe  staff     68 Jan  8 15:15 .
    drwx------+ 853 joe  staff  29002 Jan  8 15:15 ..
    localhost:nonde joe$ sudo ls -la
    total 0
    drwxr-xr-x+   2 joe  staff     68 Jan  8 15:15 .
    drwx------+ 853 joe  staff  29002 Jan  8 15:15 ..
    localhost:nonde joe$ sudo hugo new site ./hugo/default
    localhost:nonde joe$ sudo ls -la
    total 0
    drwxr-xr-x+   3 joe   staff    102 Jan  9 13:03 .
    drwx------+ 853 joe   staff  29002 Jan  8 15:15 ..
    drwxr-xr-x+   3 root  staff    102 Jan  9 13:03 hugo

**Comment by jbshirk** [comment]
this is a documentation issue.
https://discuss.gohugo.io/t/fatal-mkdir-hugo-permission-denied/2424

**Comment by anthonyfok** [comment]
Hi @jbshirk,

Welcome to Hugo.

Mac OS X, being a Unix-like system, follows specific file system hierarchy and permissions conventions.  Therefore, by OS X's design:

* Ordinary users' working directory is in /Users/_username_, for example, `/Users/joe`.  When you are working on developing a website, this is the place to do it.

* Ordinary users are not supposed to right to a root directory like `/Apple` or `/hugo` or `/whatnot`.  That / directory is often reserved for OS X system files.  `Result: FATAL: 2016/01/09 mkdir /hugo: permission denied` simply means that OS X is **protecting** you from writing randomly to your file system.

* `sudo` gives you administrative rights and allows you to make anything to your file system, including destroying it.  Avoid `sudo` unless you really need to.

* Hugo does not need to be run with `sudo` unless you want to run `hugo server --port 80` to serve web pages over port 80.

**Comment by jbshirk** [comment]
I think you misread the original post of this issue. I did not use sudo, i used my own user and permissions in my own home. that generated the FATAL.

**Comment by jbshirk** [comment]
the only way to accomplish what is implied on quickstart:

    joe$ cd ~
    joe$ mkdir path
    joe$ cd path
    joe$ mkdir to
    joe$ cd to
    joe$ hugo new site site

**Comment by anthonyfok** [comment]
@jbshirk, please read http://blog.teamtreehouse.com/introduction-to-the-mac-os-x-command-line and make sure you understand the difference between absolute path and relative path first.  Hugo documentation assumes the reader understand that difference.  Thanks.

The instruction in the quickstart does work if permission is not an issue.  Try this:

    joe$ hugo new site /Users/joe/my-new-hugo-site
    joe$ cd /Users/joe/my-new-hugo-site

But I will be making some minor changes to the docs as you've suggested so future new users to the command-line would not run into the same problem.  Thank you for your suggestion!

**Comment by h-b** [comment]
Under step 4, the tutorial says 

`hugo new posts/my-first-post.md`

This is a relative path and on my Mac I get `Error: open /my-first-post.md: permission denied`. But using an absolute path (to the same directory, being inside my home directory), it works.

The tutorial only uses an absolute path for the new site, but not for the first post. So it seems to me that it is unintended that the current directory is ignored, which would I would regard as a bug.

In my opinion the requirement to use absolute paths on the command line is probably unexpected even for experienced users.

I installed hugo on Mac OS 10.14.4 according to the [Fetch from GitHub documentation](https://gohugo.io/getting-started/installing/#fetch-from-github), `hugo version` says:
`Hugo Static Site Generator v0.55.0-DEV/extended darwin/amd64 BuildDate: unknown`

**Comment by anthonyfok** [comment]
@h-b Please file a new issue instead of adding a comment on an old closed issue as otherwise no one would usually see it.  (It was a fluke that I saw your message at all.)  Thanks!

**Comment by rootkea** [comment]
@h-b Please open the issue as suggested by @anthonyfok 

I also came across this same bug just now.

```
$ hugo version
Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
$ hugo new content/binary-search.md
Error: open /binary-search.md: permission denied
$ hugo new ./content/binary-search.md
content/binary-search.md created
```
As indicated above I solved it by appending `./`, thereby converting relative path to absolute.
