### ISSUE TITLE
`hugo --watch` doesn't watch the change in config.toml

### ISSUE THREAD

**Issue by c4po** [spf13/hugo#1770]
If I'm using a single page theme like (http://themes.gohugo.io/agency/) and only update the site by changing the value in `config.toml`. The `hugo --watch` won't detect the changes in `config.toml` file

**Comment by bep** [comment]
Thanks, this duplicates #1684 -- and is almost fixed ...

**Comment by anthonyfok** [comment]
See also #1773 where `hugo --watch` detects the changes in config.toml once only and then gets stuck.
