### ISSUE TITLE
Nesting menus not working

### ISSUE THREAD

**Issue by notzippy** [spf13/hugo#1775]
According to the [docs](https://gohugo.io/extras/menus/) menu nesting is supposed to occur when a `parent` attribute has a value of a menu with a specific `identifier`. But this does not appear to be implemented in the code. `MenuEntry.AddChild` is not called from anywhere. I think `site.getMenusFromConfig` should have some code added to it to run through the created menus and linking the child menus to the parents by calling the `MenuEntry.AddChild` function. Or am I missing something else ?

**Comment by bep** [comment]
It is implemented, there are tests for it, and other people have confirmed it to work. Have a look at Site.assembleMenus.

**Comment by notzippy** [comment]
Quite right, my issue was the documentation did not state that the child had to be in the same menu as the parent. I should have looked at the test cases first .. d'oh
