### ISSUE TITLE
Fix project tag line

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1781]
Currently it says: "A Fast and Flexible Static Site Generator built with love by spf13 in GoLang http://gohugo.io "

Which was true at some point,  but now it is a collective and the project tag line should reflect that.

I think this would be better:

 "A Fast and Flexible Static Site Generator built with love in GoLang http://gohugo.io "

**Comment by anthonyfok** [comment]
Or how about

* A Fast and Flexible Static Site Generator built with love by **spf13 and friends** in GoLang http://gohugo.io

**Comment by bep** [comment]
Mine is better.

**Comment by bep** [comment]
@anthonyfok - this wasn't an invitation to a "branding contest".

If we start out that discussion, then I would want my name in there, I am a pretty big contributor. And then maybe you would want your name in there, so "A Fast and Flexible Static Site Generator built with love by spf13, bep, anthonyfok and friends in GoLang" ... and that would be the start of this ridiculous vanity-discussion with no ends. By removing all individuals from the project tag l ine, we avoid that.

**Comment by anthonyfok** [comment]
Except that @spf13 is the founder of the project, and I think somehow we should honour that fact.

**Comment by anthonyfok** [comment]
That said, as long as other ways are used to acknowledge our project founder/creator, I am okay with any change to the project tag line.  The important thing is that this is something that @spf13 is comfortable with, because, if it weren't for him, none of us would be here.  :wink:

Personally, I think the phrase "spf13 and friends" gives a kind of warm fuzzy feeling, and shows our mutual friendship and solidarity, and it is also the phrase displayed within `hugo help`, that's why I suggested it.

Just my 2 cents.  :wink:

**Comment by bep** [comment]
>Except that @spf13 is the founder of the project, and I think somehow we should honour that fact.

His nick is all over the place.

**Comment by anthonyfok** [comment]
By the way, I agree with @bep in #1646 that there should be some kind of AUTHORS and/or CONTRIBUTORS document, like many other larger projects have, to highlight some major features contributed by our contributors.  For example, randomly picked out of the hat, @coderzh's "import jekyll" and @abourget's upcoming i18n.  (@bep, you have so many that I don't know where to start.  :laugh:)

Running `git log` or `git shortlog` may not be obvious, and definitely not to someone merely browsing GitHub through the browser.  I think this would better show our acknowledgement and appreciation for their hard work.

But yes, it will take some time and effort to do it well.  I could start looking into it next month.

**Comment by bep** [comment]
https://github.com/torvalds/linux

Tag line: "Linux kernel source tree"

If it said "Linux built by Linus Torvalds" I wouldn't say that would be odd. But it doesn't. And this isn't the most advanced operating system known to man. 

Re. AUTHOR file that sounds like too much work ... and is another issue.

**Comment by spf13** [comment]
It's been that tag line from the beginning when it was a one person
project. I think @bep's proposal makes sense. Over 250 contributors to
date. Definitely bigger than any one of us.

I like the way Jekyll's readme does it. Having a by line that features some
of the more notable contributors and then linking to the others.

I do think that including some names helps bring a more human aspect to the
software.

I also like using the "and friends" as it accurately conveys the type of
development culture we aspire to.

**Comment by bep** [comment]
>I think @bep's proposal makes sense.
Should I read this as: "It makes sense in the general case, but in this specific case I'm running with with what we got! ...?

**Comment by spf13** [comment]
No. I'm saying you are right and we should change it.

I'm also saying we should highlight contributors more.

**Comment by spf13** [comment]
@bep I've changed it on the project settings. There's probably other places to change it as well. 

@anthonyfok I'd like for you to have the task of highlighting a few of the more impactful contributors to the readme. I think you provide the right perspective to be able to select a good group to highlight and I think there's value it in coming from someone other than myself.
