### ISSUE TITLE
Inconsistent use of camelCase when dealing with Viper & configuration data

### ISSUE THREAD

**Issue by mdhender** [spf13/hugo#1785]
I was trying to help @xiaomingplus with a themes question (https://discuss.gohugo.io/t/can-hugo-t-params-custom-a-directory/2481) and got confused on the way Hugo is using Viper. It looks like Viper is not case-sensitive, so things like ContentDir are spelled differently in different parts of the code.

```
viper.GetString("ContentDir")
```

```
viper.GetString("contentDir")
```

```
$ hugo config | grep -i contentdir
contentdir = "content"
```

This was really confusing since I thought that `SetDefault("ThemesDir", "themes")` in hugo/hugo.go would automatically pick up ThemesDir in the config file. If I change a line in `hugolib/site.go`

```
func (s *Site) absThemeDir() string {
	return helpers.AbsPathify(viper.GetString("themesDir") + "/" + viper.GetString("theme"))
}
```

to use `ThemesDir` rather than `themesDir`

```
func (s *Site) absThemeDir() string {
	return helpers.AbsPathify(viper.GetString("ThemesDir") + "/" + viper.GetString("theme"))
}
```

Hugo/Viper picks up the path like I'd expect. I think that it's a bug, but I don't know which part is the bug - Viper or Hugo.

**Comment by moorereason** [comment]
I don't think this is a bug.  All of the keys are converted to lowercase prior to lookup by Viper.  We may be inconsistent in using camelCase or TitleCase when we reference them in our `viper.GetString` calls, but Viper doesn't care.  [See here](https://github.com/spf13/viper/blob/a212099cbe6fbe8d07476bfda8d2d39b6ff8f325/viper.go#L461)

**Comment by moorereason** [comment]
@mdhender,
Can we close this issue?

**Comment by mdhender** [comment]
Steve suggested that I create a test case to determine if this is Hugo or Viper. I'm planning on doing that this weekend.

**Comment by mdhender** [comment]
I've tried recreating it and running with the following test in `hugolibs/site_test.go` and can't duplicate it, so I'll close this issue.

```
func TestGetString(t *testing.T) {
	viper.Reset()
	defer viper.Reset()

        var myTomlExample = []byte(`

        ThemesDir = "/foo/bar/themes"
	theme = "vanilla"

        `)

        defaultValue := "themes"
        expectedValue := "/foo/bar/themes/vanilla"

        viper.SetDefault("ThemesDir", defaultValue)
        assert.Equal(t, defaultValue, viper.GetString("themesDir"))
        assert.Equal(t, defaultValue, viper.GetString("ThemesDir"))

        viper.SetConfigType("toml")
        viper.ReadConfig(bytes.NewBuffer(myTomlExample))

	assert.Equal(t, expectedValue, helpers.AbsPathify(viper.GetString("themesDir") + "/" + viper.GetString("theme")))
	assert.Equal(t, expectedValue, helpers.AbsPathify(viper.GetString("ThemesDir") + "/" + viper.GetString("theme")))
}
```
