### ISSUE TITLE
Pages created without a parent directory fail to detect their section

### ISSUE THREAD

**Issue by integrii** [spf13/hugo#1789]
``` bash
hugo new site test
cd test
hugo new about.md
hugo undraft content/about.md
hugo -v
```

You will get the following error:
```
WARN: 2016/01/21 Unable to locate layout for section : [section/.html _default/section.html _default/list.html indexes/.html _default/indexes.html]
```

According to [this documentation](https://gohugo.io/templates/content/), hugo should determine this automatically.  It appears it does not do so unless there is a parent directory.

 > Section is determined based on the content file’s location.

If this worked properly, I would expect to add the font matter `layout = about` and place my layout file in ``layouts/about/about.html``.  However, Hugo can not resolve the section and this fails.  Hugo appears to default to the section name `page`.

```
WARN: 2016/01/21 Unable to locate layout for page about.md: [page/about.html _default/about.html theme/page/about.html theme/_default/about.html _default/single.html]
```

Funny enough, I can make a directory in `layouts/page` and place the `about.html` file in it to make my layout work.  This of course leaves the original error indicating a blank section in my debug output forever.

Thanks for Hugo!

**Comment by integrii** [comment]
Hugo Static Site Generator v0.15 BuildDate: 2015-11-25T22:29:07-08:00

**Comment by moorereason** [comment]
@integrii,
Correct me if I'm wrong, but it appears that Hugo is complaining that there are **no** layouts defined.  Following the commands you posted above yields an empty `layouts` directory.

**Comment by integrii** [comment]
The layouts directory is empty in the exanple, but had I put something in layouts/about/single.html, it would not have been loaded because the section was undefined within hugo.  You can see this in the "unable to locate layout for section" error.  It looks like later on in hugo the code defaults to the section name 'section'.

Without a layout, hugo should load /layouts/$section/single.html or in this case I would expect /layouts/about/single.html.  You can make this file and it won't be used (that was the bug and I should have included that here).

**Comment by moorereason** [comment]
This is working as designed.  Section is determined based on the content file’s location.  Creating `content/about.md` creates content with **no** section.  You need to create `content/about/index.md`.  See the [content organization docs](https://gohugo.io/content/organization/).

**Comment by integrii** [comment]
Thanks @moorereason - I didn't see anywhere in the docs that mentioned `index.md`, but it makes a lot of sense now that you point it out!

**Comment by integrii** [comment]
I wanted to note today that I think the example site and documentation need updated here.  Not once on the content organization docs does it mention a folder with an `index.md` file in it.  Furthermore, the example site shows an [abount.md file in the main directory](https://github.com/spf13/HugoBasicExample/tree/master/content), just like I was assuming you should do!

**Comment by moorereason** [comment]
Just to clarify, it's not wrong to create an `about.md` file and have it render as `/about/index.html`, so the example site is correct.

Your original question was about how Hugo auto-assigns "sections" to content, and that is currently determined by the first-level directory under `content`.  But to your last point, we probably do need to give an example of using `index.md`.

**Comment by integrii** [comment]
Check my pull request: #1806 

So, because it is valid to create a top level `about.md` file that produces an `/about` URL, then Hugo should probably fail back to determining the section based on the `about.md` file name if there is no default layout file present and no containing directory.

I checked the example site and noticed that this error does not occur because hugo finds the default layout in the theme.  It looks like this issue only occurs when no content folder is specified, the section is supposed to be automatically determined, and there is not a default layout file present in the theme or layout directory.

In that specific case, hugo does this:
```
WARN: 2016/02/01 Unable to locate layout for section : [section/.html _default/section.html _default/list.html indexes/.html _default/indexes.html]
```

The blank section variable and assumed section path are unexpected behavior and would be averted if the section name 'about' was determined based on `about.md`.

My pull request adds an example to the docs on how to create an `/about` path and I would be happy to dig into the code and add some logic that determines the section based on filename as a last resort.

**Comment by moorereason** [comment]
That's an interesting idea.  My initial reaction is that it would create unnecessary confusion and complicate the layouts search path.  Under your proposal: if you initially created a site with no *default* template, but later added one, the `about.md` page rendering would change to the default template.  At that point, you'd still have to do *something* with your about content in order for it to use the section template you desire.

The existing layouts search path is not overly complex and relatively easy to explain and document.

My recommendation is to simply add `type="about"` in your `about.md` front-matter.  This approach is what I use on my sites for single-page sections, but I also use default templates.

@bep & @spf13, would you guys care to comment?

**Comment by spf13** [comment]
I agree with @moorereason's suggestion. Alternatively you could just specify `layout="{templatefile}"` in the front matter directly.

**Comment by spf13** [comment]
Additionally your issue comment is accurate, but it's not a bug, it's by design. Top level content doesn't have a section because it exists in the root. It seems like bug is in the documentation which doesn't explain this clearly enough.

**Comment by integrii** [comment]
Thanks for the input!  I will let the documentation part of this discussion live on in my pull request.
