### ISSUE TITLE
Markdown list type ignored with two adjacent lists

### ISSUE THREAD

**Issue by Solumin** [spf13/hugo#1795]
When two lists are separated by empty lines, the list type (ordered or unordered) of the second list is overridden by the first list.

Example:

- first item
- second item
- next is whitespace

1. should be numbered "1."
2. also numbered.

Raw:
```markdown
- first item
- second item
- next is whitespace

1. should be numbered "1."
2. also numbered.
```

When Hugo renders the above, it generates only an unordered list. Inserting more whitespace line does not help, though a line with text will force Hugo to separate the lists.

Putting the ordered list first has a similar result, except the ordered list overrides the following unordered list.

This Gist contains a minimal complete example, and as a bonus shows how another Markdown engine renders it: https://gist.github.com/Solumin/d08107fe9d1c30756f7b

Here is a screenshot showing the resulting page using hugo-base-theme:
![hugo_test](https://cloud.githubusercontent.com/assets/930857/12626179/5af02128-c505-11e5-99b1-c28607db4cc8.png)

I've tried a handful of themes just to make sure it wasn't an issue with hugo-base-theme, and have seen the same behavior in all of them.

**Comment by moorereason** [comment]
I've created an [issue for Blackfriday](https://github.com/russross/blackfriday/issues/235), which Hugo uses as the default markdown renderer.

As a work-around, you can add `<!-- -->` between the lists.

**Comment by Solumin** [comment]
Thank you for posting it to Blackfriday!

I'll keep that workaround in mind.
