### ISSUE TITLE
hugo shouldn't delete public/.git if present

### ISSUE THREAD

**Issue by maruel** [spf13/hugo#1796]
Some (weird?) people track the public/ directory with a SCM like git. This is orthogonal to tracking the root repository, public/ is tracked as a separate repository.

While it is better to clean up public/ at generation time so stale files are not left by accident, the current behavior can be problematic for user who wish to track the generated output in public/.

The action item would be to leave a few known directories/files alone. The list could include ".git", ".hg".

I understand this is very specific use case. In the meantime I work around by checking out in public_tmp, running `hugo`, then `mv public_tmp/.git public/`. Since the workaround works fine, I don't see this as a high priority for now but the whitelist could probably be generalized for other use case, if any.

**Comment by bep** [comment]
Hugo doesn't (or shouldn't is the correct word) delete any thing in /public. We have had many requests for that, but I have been very reluctant to any "rm -rf" behaviour.

Are you sure it isn't some other script in your build setup doing this?

**Comment by jygastaud** [comment]
I use something close to the process you describe @maruel.
I don't do anything specific and my custom git repository in public/ is kept.

**Comment by moorereason** [comment]
@bep, I believe HEAD now deletes stale files from public.

**Comment by bep** [comment]
@spf13 is that true? And should it? I vote a pretty big NO.

**Comment by moorereason** [comment]
@bep, see the latest discussion in Gitter.

**Comment by spf13** [comment]
I've restored the previous behavior and added a flag to enable the cleaning behavior in c438f45629a42fe1a38ea1ff665c6016bb5e8aa1
