### ISSUE TITLE
Hugo 0.16-DEV (Jan 2016) aborts with error when syncing static files on Windows

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#1800]
With the latest Hugo HEAD as of 2016-01-30, e.g. commit 57eebbf, running `hugo` on Windows 8.1 results in the following error message:

```
Anthony@Veronica-V5 MINGW64 ~/test-site
$ hugo -v -t hyde
INFO: 2016/01/30 02:37:10 hugo.go:393: Using config file: C:\Users\Anthony\test-site\config.toml
INFO: 2016/01/30 02:37:10 hugo.go:483: using a UnionFS for static directory comprised of:
INFO: 2016/01/30 02:37:10 hugo.go:484: Base: C:\Users\Anthony\test-site\themes\hyde\static
INFO: 2016/01/30 02:37:10 hugo.go:485: Overlay: C:\Users\Anthony\test-site\static\
INFO: 2016/01/30 02:37:10 hugo.go:517: syncing static files to C:\Users\Anthony\test-site\public\
Error: Error copying static files to C:\Users\Anthony\test-site\public: GetFileAttributesEx C:\Users\Anthony\test-site\static\C:\Users\Anthony\test-site\public: The filename, directory name, or volume label syntax is incorrect.

Anthony@Veronica-V5 MINGW64 ~/test-site
$ 
```

I wonder what resulted in the incorrect path `C:\Users\Anthony\test-site\static\C:\Users\Anthony\test-site\public`.  Hmm...

**Comment by anthonyfok** [comment]
Slightly different incorrect path with `hugo server` rather than plain `hugo`:

```
Anthony@Veronica-V5 MINGW64 ~/test-site
$ hugo server -v -t hyde
INFO: 2016/01/30 02:59:14 hugo.go:393: Using config file: C:\Users\Anthony\test-site\config.toml
INFO: 2016/01/30 02:59:14 hugo.go:483: using a UnionFS for static directory comprised of:
INFO: 2016/01/30 02:59:14 hugo.go:484: Base: C:\Users\Anthony\test-site\themes\hyde\static
INFO: 2016/01/30 02:59:14 hugo.go:485: Overlay: C:\Users\Anthony\test-site\static\
INFO: 2016/01/30 02:59:14 hugo.go:517: syncing static files to C:\Users\Anthony\test-site\
Error: Error copying static files to C:\Users\Anthony\test-site: GetFileAttributesEx C:\Users\Anthony\test-site\static\C:\Users\Anthony\test-site: The filename, directory name, or volume label syntax is incorrect.

Anthony@Veronica-V5 MINGW64 ~/test-site
$ 
```

So, to recap, `hugo -v` results in the incorrect path:

    C:\Users\Anthony\test-site\static\C:\Users\Anthony\test-site\public

whereas `hugo server -v` results in the incorrect path:

    C:\Users\Anthony\test-site\static\C:\Users\Anthony\test-site

**Comment by Zenithar** [comment]
Same problem on Linux (Asset are not synced.)

```
INFO: 2016/01/30 17:37:53 hugo.go:393: Using config file: /home/tnormand/Repositories/github/zenithar/zenithar.hugo/config.toml
INFO: 2016/01/30 17:37:53 hugo.go:483: using a UnionFS for static directory comprised of:
INFO: 2016/01/30 17:37:53 hugo.go:484: Base: /home/tnormand/Repositories/github/zenithar/zenithar.hugo/themes/bleak/static
INFO: 2016/01/30 17:37:53 hugo.go:485: Overlay: /home/tnormand/Repositories/github/zenithar/zenithar.hugo/static/
INFO: 2016/01/30 17:37:53 hugo.go:517: syncing static files to /
INFO: 2016/01/30 17:37:53 site.go:1274: found taxonomies: map[string]string{"tag":"tags", "topic":"topics"}
INFO: 2016/01/30 17:37:53 htmlredirect.go:116: Alias "/tags/pssh/page/1" translated to "tags/pssh/page/1/index.html"
```

**Comment by anthonyfok** [comment]
Hi @Zenithar, no, it is a different issue on Linux where the theme's static directory is not synced.  Please see Issue #1802 about the bug on Linux, thanks!

**Comment by Skrylar** [comment]
Seems to be related to `AbsPathify.` Two absolute paths appear to be getting concatenated together, which is not helpful.

**Comment by Skrylar** [comment]
Doing some minor test programs to make sure its not a problem in the standard packages. If you try to combine two absolute paths, this happens:
```
func main() {
	fmt.Println("%q",
		filepath.Join("C:\\frogs", "C:\\toads"))
}
// Output: C:\Frogs\C:\Toads
```
While a properly absolute+relative value works as expected;
```
func main() {
	fmt.Println("%q",
		filepath.Join("C:\\frogs", "toads"))
}
// Outputs: C:\frogs\toads
```

**Comment by Skrylar** [comment]
Replacing hugo.go:584 `	err := syncer.Sync(publishDir, helpers.FilePathSeparator)` with `err := syncer.Sync("bonk", helpers.FilePathSeparator)` confirms that the error is coming from within fsync. Manually inserting an absolute path here causes fsync to choke, while manually inserting a relative one has no such error.

**Comment by Skrylar** [comment]
I fixed the problem. It turns out, there is a typo in fsync:
```diff
diff --git a/fsync.go b/fsync.go
index 2a933fc..e854b74 100644
--- a/fsync.go
+++ b/fsync.go
@@ -123,7 +123,7 @@ func (s *Syncer) sync(dst, src string) {
        defer s.syncstats(dst, src)

        // read files info
-       dstat, err := s.SrcFs.Stat(dst)
+       dstat, err := s.DestFs.Stat(dst)
        if err != nil && !os.IsNotExist(err) {
                panic(err)
        }
```

**Comment by hacdias** [comment]
I get this error too.

**Comment by anthonyfok** [comment]
@Skrylar wrote:

> I think I fixed the problem. It turns out, there is a typo in fsync:
> ```diff
> diff --git a/fsync.go b/fsync.go
> index 2a933fc..e854b74 100644
> --- a/fsync.go
> +++ b/fsync.go
> @@ -123,7 +123,7 @@ func (s *Syncer) sync(dst, src string) {
>         defer s.syncstats(dst, src)
> 
>         // read files info
> -       dstat, err := s.SrcFs.Stat(dst)
> +       dstat, err := s.DestFs.Stat(dst)
>         if err != nil && !os.IsNotExist(err) {
>                 panic(err)
>         }
> ```
> Both "sstat" and "dstat" end up assigned to the same SrcFs object, which then runs in to a compound problem with afero's BasePath implementation. This change doesn't cause test failures in fsync, and appears to allow Hugo to run again. Will have to poke around a bit more to be sure.

@Skrylar, you are awesome!  Thank you for investigating this issue and providing a fix!

@spf13, this is specific to spf13/fsync; please take a look and confirm when you have time.  Many thanks!

**Comment by Skrylar** [comment]
@anthonyfok It's worse than fsync specific; it appears that there is a typo at work here (causing the error) however it reveals a problem in afero's underlying BasePather filesystem. BasePather is supposed to ensure all access happens within a set subdirectory (or not at all) and uses the OS package for file path manipulation, yet if an absolute path is given on Windows that will result in an illegal path being returned. Trying to join "C:\Foo" and "C:\Bar" creates "C:\Foo\C:\Bar" which is illigitimate.

**Comment by anthonyfok** [comment]
@Skrylar Thank you for your clarification.

By saying it is "spf13/fsync" specific, I meant to say that the bug is specific to @spf13's fork of fsync at https://github.com/spf13/fsync, not to the original upstream https://github.com/mostafah/fsync (without Afero support).  Some months ago, there was another bug that originated from mostafah/fsync that was fixed there.  So I was also doing a tiny bit of triage work.  Because the "spf13/fsync" fork, like most GitHub fork, does not allow filing a fork-specific issue, the discussion about fixing spf13/fsync stays here in this Hugo issue.

But yes, if you think Afero's underlying BasePather is buggy, then we should investigate that too, and file an issue at https://github.com/spf13/afero/issues/new if necessary.

**Comment by spf13** [comment]
Thanks for digging into this. Windows is hard because there isn't a sense
of root. Afero tries hard to abstract this and operate the same but it
sometimes causes issues like this.

The good news is it should be easy to resolve. We just need a test that
triggers this behavior and then fix the underlying issue.

I'm traveling and without access to Windows right now. If someone can add
the test we can validate the fix via our windows CI.

**Comment by Skrylar** [comment]
@spf13 What should happen when an invalid absolute path is given?

For a base path of "C:\Foo\", "C:\Foo\Bar" is a reasonable path. But "C:\Bar\Foo" is clearly not valid.

**Comment by bep** [comment]
@spf13 see https://github.com/spf13/fsync/pull/3

**Comment by bep** [comment]
@Skrylar see https://github.com/spf13/afero/pull/71

**Comment by bep** [comment]
I can confirm that  see spf13/fsync#3 fixes this issue on Windows. I'm surprised it works at all on Unix, but I guess the symmetry of the write/reads saves it ...
