### ISSUE TITLE
Where should a new theme be placed?

### ISSUE THREAD

**Issue by wsw70** [spf13/hugo#1801]
I just discovered Hugo and wanted to try to port my existing site (in harp.js), to give it a try as it looks like a very, very good project.

I failed at understanding from the docs where the templates should go.

When creating a new site with `hugo new` I ended up with a `layouts` directory. My expectation was that the server starting with no theme would go there looking for `_default\single.html`. I do not think it does (the file is not taken into account).

I then created from the same place (the root of my site) a new theme (via `hugo new theme myowntheme`). This created `themes/myowntheme` aan some dirs inside, including `layouts`. I tried to edit `_default\single.html` there -- still not taken into account (after restarting `hugo server --theme=myowntheme`. 

Where should I start?

Thank you!

**Comment by digitalcraftsman** [comment]
Hello @wsw70,

it feels like this is a question that would be better suited to the [Hugo Discussion Forum](https://discuss.gohugo.io/). You will reach a wider audience of Hugo users if you could repost your question there.

**Comment by wsw70** [comment]
Thank you. I posted my question there, expanding it with the information I found in the meantime.

**Comment by anthonyfok** [comment]
For reference, @wsw70 (@WoJ on discuss.gohugo.io) has posted the question at:

* https://discuss.gohugo.io/t/where-to-place-templates-for-a-single-page/2575
