### ISSUE TITLE
Cannot download hugo-type-theme

### ISSUE THREAD

**Issue by ottuzzi** [spf13/hugo#1810]
Hi,

I was following the Hugo Guide and when I try to download themes using the following command `git clone --recursive https://github.com/spf13/hugoThemes.git themes` I get:
```
Cloning into 'type'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=No error

Clone of 'git://github.com/digitalcraftsman/hugo-type-theme.git' into submodule path 'type' failed
```
and it stops here. If I try to get the theme with a regular `git clone` the theme is regularly downloaded: is there something wrong in the submodule definition?

Thanks
Bye
Piero

**Comment by bep** [comment]
You could try to post the issue at the Hugo themes repo.
