### ISSUE TITLE
Indentation levels in templates are ignored

### ISSUE THREAD

**Issue by Javivi** [spf13/hugo#1819]
As seen on the images, an indentation level of 4 spaces only gets applied to the first line of the template, when it should be applied to every line on it.

![1](https://cloud.githubusercontent.com/assets/1174585/12846082/c1c76a1c-cc0a-11e5-8e29-cb660956bcfc.png)
![2](https://cloud.githubusercontent.com/assets/1174585/12846083/c1cbca62-cc0a-11e5-9b1d-c08d337741b3.png)

Removing the 4 spaces before the partial inclusion and adding them at every line on the the .html file obviously would fix this, but having templates comply with the current indentation level would be better and lead to better formatted webpages as there is cases where you use the same template on different scopes and indentation levels.

**Comment by bep** [comment]
The Go templates are a product of the Go stdlib. Any issues should be raised there:

https://github.com/golang/go

**Comment by Lyberta** [comment]
But it's up to Hugo to compute proper indentation level.
