### ISSUE TITLE
Commit 87ca0d0 broke caddy-hugo

### ISSUE THREAD

**Issue by hacdias** [spf13/hugo#1827]
Hey guys,

I'm reporting that the [commit](https://github.com/spf13/hugo/commit/87ca0d0cbea19dd2c0aac44dc2731e6247a82ece) made by @bep unexported the var ```HugoCmd```. That broke ```caddy-hugo``` plugin because it needs to [use](https://github.com/hacdias/caddy-hugo/blob/master/utils/utils.go#L177) that variable to work.

I suggest, or export again the variable, or give me another way to do what I was doing in those lines linked above.

Thanks :)

**Comment by bep** [comment]
I will re-export the var now, but we should think of a better API for you (and others) to use.

**Comment by hacdias** [comment]
Thanks. Yes, we should. :100:
