### ISSUE TITLE
Add support for Template Blocks in Go 1.6

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1832]
Probably something similar to the `baseof.ace` templates.

https://github.com/golang/go/issues/3812

**Comment by bep** [comment]
I cannot get this to work with Hugo. I don't understand it, and have wasted enough time. I'm happy enough with the Ace templates. If someone wants to take a stab at it, be my guest.

**Comment by bep** [comment]
OK, found a way to make this work without *too intrusive* changes. I still believe the Go team should have made a better job with this. To quote Rob PIke: "Simplicity is Complicated".

**Comment by anthonyfok** [comment]
@bep, Kudos to you!  You are awesome as always!  Thank you for implementing this feature!
