### ISSUE TITLE
Pages duplicated when editing config.toml

### ISSUE THREAD

**Issue by derekperkins** [spf13/hugo#1840]
When running `hugo server --watch`, all my pages get duplicated when I edit `config.toml`. Notice below how the total pages created goes from 4 to 8 to 12. None of the taxonomy pages are duplicated though.

```
Change detected, rebuilding site
2016-02-11 02:47 -0700
Template changed /Users/derek/github/website/themes/nozzle/layouts/partials/taxonomies/personas.html
0 draft content
0 future content
4 pages created
0 non-page files copied
0 paginator pages created
2 tags created
0 series created
3 personas created
in 17 ms

Config file changed: /Users/derek/github/website/config.toml
0 draft content
0 future content
8 pages created
0 non-page files copied
0 paginator pages created
2 tags created
0 series created
3 personas created
in 67 ms

Config file changed: /Users/derek/github/website/config.toml
0 draft content
0 future content
12 pages created
0 non-page files copied
0 paginator pages created
2 tags created
0 series created
3 personas created
in 57 ms
```

**Comment by moorereason** [comment]
This would explain why I was getting these duplicate item errors with a main menu the other day:

```
ERROR: 2016/02/05 15:08:08 site.go:1234: Two or more menu items have the same name/identifier in Menu ...
```
I didn't realize that the page count may have been growing.

**Comment by bep** [comment]
I cannot reproduce this locally -- so I guess this is a OS thing? Windows?

@spf13 my best guess this and some other issues have a root in the changes you made recently. Do you have any plans to look at these?

**Comment by bep** [comment]
I was wrong, I can reproduce it .. It only happens when I edit the config.toml.
