### ISSUE TITLE
Symbolic link error shown but link as root folder is followed and works

### ISSUE THREAD

**Issue by simplyeffectiveweb** [spf13/hugo#1855]
In Windows 7 x64, created symlink **content** in Hugo source folder to **content_src** which contained content to be generated.

Hugo throws error on build: '_Symbolic links not supported_'. However the content from **content_src** is generated as normal (so in this case, symobilic links work).

Solution: remove error when symbolic link is a root folder, leave it as-is for all other cas

**Comment by bep** [comment]
Just tested this on OS X, and I get the error ... but I also don't get the content created. I believe we could make this work, but I cannot see how it could right now, even on Windows ....

**Comment by simplyeffectiveweb** [comment]
I was pretty carefult in testing. I put the word symlink in the content of a _content_src_ folder, and then created a symlink _content_ to that folder. This was built by Hugo, with the error shown, and with the content generated.

Unless Hugo took the content from _content_src_ ? Is this possible? Using the word 'content' in this folder name was probably not the best idea.

**Comment by bep** [comment]
It doesn't really matter -- the pull request that is referenced to this issue should fix this issue for both you and me.
