### ISSUE TITLE
Disable language guessing with PygmentsCodeFences

### ISSUE THREAD

**Issue by phil-opp** [spf13/hugo#1861]
The `PygmentsCodeFences` option enables highlighting for all \`\`\` ... \`\`\` blocks, even if no language is specified. This leads to unwanted highlighting since the [-g flag is passed to pygments](https://github.com/spf13/hugo/blob/26d23f7f4becb2bbfa80d91ae9b27ffc76e13e3a/helpers/pygments.go#L99) in that case.

I think that the highlighting should only be be enabled for fenced blocks with an explicitly specified language. This would be in line with [Github's fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

To disable automatic highlighting we could insert additional checks for `(lang != "")` in [line 38](https://github.com/spf13/hugo/blob/0f6b334b6715253b030c4e783b88e911b6e53e56/helpers/content_renderer.go#L38) and [line 81](https://github.com/spf13/hugo/blob/0f6b334b6715253b030c4e783b88e911b6e53e56/helpers/content_renderer.go#L81) in `content_renderer.go`.

**Comment by bep** [comment]
@bramp do you have any opnion on this?

**Comment by bramp** [comment]
Yes that would certainly make this consistent with Github. We originally guessed the language to be inline with who the highlight shortcode worked.

I would be in favor of not guessing the language, but this would be consider a regression to any user depending on the guess.

**Comment by bep** [comment]
Agree, for most people this will be a surprise, but then again many people would want it. So here is my suggestion:

Add a config option:

```
PygmentsCodeFencesGuessSyntax = true 
```
So the default will still be a breaking change, but people will have the chance to get the old back if the need.

**Comment by phil-opp** [comment]
@bep should the default be `true` or `false`?

**Comment by moorereason** [comment]
Default is `false`.

**Comment by bep** [comment]
My bad, my example was confusing. Default should be `false`.

**Comment by bep** [comment]
43b5dfabb5fb36bb4574289912c66a46ef20ffce

**Comment by frioux** [comment]
Looking forward to getting this in a release.  With guessing enabled, my blog takes 42s to build.  Too slow! :)

**Comment by bep** [comment]
>Looking forward to getting this in a release. With guessing enabled, my blog takes 42s to build. Too slow! :)

With cache enabled?

**Comment by frioux** [comment]
Nah I had never needed that before. I'll try it out tomorrow, but even an
initial build of 40s strikes me as too long.

-- 
sent from a rotary phone, pardon my brevity

**Comment by frioux** [comment]
[I don't see cache documented](https://gohugo.io/overview/configuration/)
