### ISSUE TITLE
Function "urlize" does not remove "." 

### ISSUE THREAD

**Issue by luke1001** [spf13/hugo#1862]
It seems that function "urlize" does not replace "." Is this a bug? eg:

```
+++
names: [ "Mr. Perkins", "Mrs. Bergevin", "Tanner Linsley" ]
+++

{{ .Params.names | urlize}} -> ["mr.-perkin"s, "mrs.-bergevin", "tanner-linsley"]
```

**Comment by bep** [comment]
"." is a pretty common character in URLs, I would say.

**Comment by aalfiann** [comment]
yes it's common, but is there a way to remove a custom char?

**Comment by moorereason** [comment]
@aalfiann, please don't comment on 4 year old, closed issues.  Either ask on the forums (preferred) or open a new issue.
