### ISSUE TITLE
Hugo 0.15 doesn’t seem to release memory

### ISSUE THREAD

**Issue by Jos512** [spf13/hugo#1871]
Hugo doesn't seem to release its memory when used for a longer time (that is, after several rebuilds). 

This GitHub issue originates from the forum discussion: [Hugo doesn't seem to release memory](https://discuss.gohugo.io/t/hugo-0-15-doesnt-seem-to-release-memory/2720). See that thread for more information.

**Comment by aresta** [comment]
My Mac: Run Hugo - 1.9G RAM

![image](https://cloud.githubusercontent.com/assets/236967/15804591/6e4fb474-2b38-11e6-98d4-097e782db4b1.png)

**Comment by bep** [comment]
@aresta that screenshot isn't very helpful without a context.

**Comment by aresta** [comment]
@bep Just updated! Let's me know if you need more information.

**Comment by anthonyfok** [comment]
@aresta Is this still an issue for the newly released Hugo v0.16?  Thanks!

**Comment by aresta** [comment]
@anthonyfok I think same issue with version 0.16

![image](https://cloud.githubusercontent.com/assets/236967/16139438/753d57f4-3471-11e6-9027-c27fab73c0b7.png)

**My Hugo:**
Hugo Static Site Generator v0.16 BuildDate: 2016-06-06T19:37:59+07:00

**Started building site**
0 draft content
0 future content
264 pages created
0 non-page files copied
345 paginator pages created
250 tag created
17 category created
0 series created
in 2376 ms

**Comment by bep** [comment]
@aresta -- this issue is about "not releasing memory". To prove that you would have to trigger updates over time.

**Comment by Jos512** [comment]
Just as an update since I made the original issue (and to help clean up open issues): 

I haven't experienced any memory issues with Hugo anymore in version 0.17. So I would consider this issue closed & fixed, and from my standpoint there's no need to spend time on it.

**Comment by digitalcraftsman** [comment]
Is this still an issue in the current version of Hugo (v0.18.1)?

**Comment by Jos512** [comment]
Not for me on Windows, and that's with building the same site as the original issue I reported. Haven't experienced memory issues with other sites either.

~~~
Hugo Static Site Generator v0.18.1 BuildDate: 2016-12-30T10:03:28+01:00
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.7.4"
~~~

**Comment by bep** [comment]
OK, any new reporter will have to create a new issue. There are lots of changes to simplify the object model in 0.17/0.18, with significant reduction in memory footprint, so chances are this has improved.
