### ISSUE TITLE
Remove or fix CircleCI

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1874]
The current setup doesn't handle library updates. Have no clue how to fix it. Is pretty annoying and demotivating with perfectly fine, but red pull requests.

**Comment by anthonyfok** [comment]
You mean, for example, https://circleci.com/gh/spf13/hugo/908?

Does CircleCI's "Rebuild without cache" feature work for you?  (Caveat: It needs to be done manually AFAIK.)

**Comment by bep** [comment]
Yea, that works -- but it doesn't solve the general problem. We have travis and appv.; do we need CircleCI for pull requests?

**Comment by bep** [comment]
Never mind, we have plenty of more important issues ...
