### ISSUE TITLE
Documentation: Menu bug

### ISSUE THREAD

**Issue by drembaru** [spf13/hugo#1875]
On my computer the menue from the Hugo documentation does not work properly. There is an offset between the menue entries and the small arrows. For example: If my mouse hovers 'Themes' the 'Themes' button and the arrow from 'Templates' is highlighted. If I push the arrow next to 'Templates' the 'Themes' subsection is opened.

I'm using Ubuntu 14.04 with Firefox 43.04.

**Comment by dokempf** [comment]
I can confirm this bug on Debian 8 with Firefox 43.0
I have tested it with Chromium on the same system and it looks fine, so it seems like a Mozilla issue.

**Comment by robertbasic** [comment]
Bug present in Firefox:

![hugo-docs-menu-firefox](https://cloud.githubusercontent.com/assets/166625/14153692/1a2d12b4-f6b9-11e5-8ab3-a6ccfb859d01.gif)

Works as expected in Chrome:

![hugo-docs-menu-chrome](https://cloud.githubusercontent.com/assets/166625/14153691/1a297f14-f6b9-11e5-9ce9-f28175d96a89.gif)

**Comment by robertbasic** [comment]
Setting `margin-top` [here](https://github.com/spf13/hugo/blob/a89035bdaaa8bb1525a74d82e068ef80bfa28aed/docs/static/css/style.css#L312) to `-16px` fixes it for me, but not sure how it would affect [this previous fix](https://github.com/spf13/hugo/issues/1523)?

**Comment by dokempf** [comment]
The applied fix does not solve the origin issue for me, unfortunately.

**Comment by robertbasic** [comment]
@dokempf probably because the fix has not yet propagated through Cloudflare, see #2045

**Comment by dokempf** [comment]
No, I use the hugo docs layout for my own project and I applied the fix there.

**Comment by digitalcraftsman** [comment]
@dokempf checked it in Firefox 45 and it worked fine. Did you reset the browser's cache? It a common source for problems like this.
