### ISSUE TITLE
Avoid the need to copy config.toml from inside themes

### ISSUE THREAD

**Issue by joegalaxy71** [spf13/hugo#1876]
Suggestion: most theme I see hint you to copy a config.toml file from inside the theme dir to the appropriate place.
Then you need to edit baseURL, obviously. This make the process of trying templates painful and confusing. Can I suggest to parse a theme-config.toml inside the specified theme after finished parsing config.toml? This would make template switch easy. Would also allow better separation between theme and content.

**Comment by bep** [comment]
Totally agree.

I think this is handled by #1344 -- so I'll close this as a duplicate. This should be easy to add... but someone would have to find the time to do it.
