### ISSUE TITLE
Prevent capitalized taxonomy labels

### ISSUE THREAD

**Issue by agoldst** [spf13/hugo#1880]
According to <https://gohugo.io/taxonomies/usage/>, Hugo "titleizes" taxonomy labels automatically. This is often not desirable if the taxonomy label is an acronym or a proper name. For example, suppose I tag some of my posts about making stylish webpages with the tag "CSS." Then, in the listing for all posts with that tag at /tags/css, the header will read "Css," which is not correct. There is no way to adjust this within the /layouts/taxonomy/tag.html template, because the .Title variable has already been title-cased. This happens even if the preserveTaxonomyNames option is true. An option to turn off this behavior and provide taxonomy terms as-is in the .Title variable in this case would be very helpful. I'm sorry I don't know go well enough to provide a PR.

I think this similar but not quite the same as the issues referenced in #1641 and #1407.

**Comment by agoldst** [comment]
No, I put this wrong. I apologize. With preserveTaxonomyNames set to true, all-upper case terms are preserved. But all-lower-case terms are titlecased. This is still not ideal. Better to control this in the template, not enforce it in the data passed into templates.

**Comment by bep** [comment]
> But all-lower-case terms are titlecased.

That is not true. They are capitalized ("do be do be do" becomes "Do be do be do"), which is something different in my dictionary.

**Comment by bep** [comment]
With that said, I'm going to close this issue as a duplicate. This will get solved once @spf13 get out of his think tank and we can make the taxonomies first-class citizens of Hugo.

**Comment by agoldst** [comment]
Thank you, and you're right that it's sentence-cased, not title-cased.
It's still making a decision for the user that the user might want to
make differently depending on how they use taxonomies. I'll keep an eye
out for that future update. AG

**Comment by bep** [comment]
>It's still making a decision for the user that the user might want to make differently depending on how they use taxonomies. 

You are right. I thought about it when I introduced `preserveTaxonomyNames`. I may have done it wrong. Maybe I'll revert that.

**Comment by mohae** [comment]
well, one option for the "Css" example is to use something like what golint does: a common initialisms lookup map so that CSS would be properly handled: https://github.com/golang/lint/blob/master/lint.go

I'm not suggesting that that map should be used as is.  Also this would probably end up adding knobs.

**Comment by ITSecMedia** [comment]
Is there a new bug introduced in Version 0.19?

https://discuss.gohugo.io/t/hugo-0-19-preservetaxonomynames-true-false/5640/1
