### ISSUE TITLE
Data Not Accessible by URL

### ISSUE THREAD

**Issue by tuxy** [spf13/hugo#1881]
Hey everyone, I'm trying to load dynamic yaml data by accessing it from url.

So my data location is: "/data/books". Then it has files like "book-title-one.yaml". I want to use common layout to display this books, by going to ``http://domain.com/books/book-title-one`` All I see is empty page.

/data/books/book-title-one.yaml
```
title: "Book Title One"
text: "some text here"
```

/content/books/index.html
```
---
url: "/books/"
type: books
title: Books
---
```

/layout/books/single.html
```
{{ partial "header.html" . }}

{{ range .Site.Data.books }}
<h1> {{ .title }} </h1>
<p> {{ .text }} </p>
{{ end }}

{{ partial "footer.html" . }}
```

**Comment by bep** [comment]
This is not supported, but is in some future plans; there are similar issues, so close thi one.
