### ISSUE TITLE
Humanize ordinals

### ISSUE THREAD

**Issue by waddles** [spf13/hugo#1886]
As in https://github.com/dustin/go-humanize/blob/master/ordinals.go I would like to be able to pass an integer to the humanize function and have it return an ordinal.

eg. in a shortcode:
```go
{{ $url := "/data/rallies.json" }}
<ul>
{{ range $rally := getJSON $url }}
{{ if modBool $rally.order 2 }}
<li>{{ $rally.order | humanize }} rally - {{ $rally.location }}</li>
{{ end }}
{{ end }}
</ul>
```

Should render as

- 1st rally - Sydney
- 3rd rally - Melbourne
- 5th rally - Adelaide

**Comment by moorereason** [comment]
@waddles, we use the [inflect](https://godoc.org/bitbucket.org/pkg/inflect) package instead of `go-humanize`, but we can add an `ordinalize` func.

**Comment by bep** [comment]
We should think a little about this and see in connection with the multi-language work being done somewhere else.

**Comment by michaelorr** [comment]
I'm looking for a way to contribute and this seems like it could be an good candidate for a first PR. 
@bep would you envision this being a new template function or an addition to the existing `humanize` template function which could behave differently depending on what was passed in? Additionally, back in February you mentioned the multi-language work being done, how could these two things relate?
I apologize for the questions, I'm not super familiar with the design goals of hugo, just curious what a good approach would look like to you before I go down a path.

**Comment by waddles** [comment]
Actually the inflect package has a https://godoc.org/bitbucket.org/pkg/inflect#Ruleset.Ordinalize function already but I decided I didn't need it after all.

**Comment by michaelorr** [comment]
Even if you don't need it, someone else probably will and it's a simply enough thing to support I think.

**Comment by bep** [comment]
@michaelorr I have no clue how this intersects with multilanguage, but the thing is that for Norwegians (like myself), Chinese etc. having ordinals that creates 1st, 2nd etc. is of not much use ...

But since we already have a humanize func it would sensible to change it so:

**If the argument is one of the integer types, then return ordinal.**

PR welcomed.

**Comment by waddles** [comment]
https://github.com/spf13/hugo/blob/273a68400ff081d05508afbcb6d158711b865307/tpl/template_funcs.go#L1728 would be the place to put it

**Comment by bep** [comment]
No, https://github.com/spf13/hugo/blob/273a68400ff081d05508afbcb6d158711b865307/tpl/template_funcs.go#L1707

**Comment by michaelorr** [comment]
@bep First stab is here: https://github.com/spf13/hugo/pull/2197
There are a few things I want to take care of before it's ready but they are noted in the PR comment.

**Comment by michaelorr** [comment]
PR with the fix is ready: https://github.com/spf13/hugo/pull/2197
