### ISSUE TITLE
Add emojis support

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1891]
See the update task here for inspiration for a `go generate` task:

https://github.com/Ranks/emojify.js/blob/master/gulpfile.js

The images´ license looks complicated:

https://github.com/arvida/emoji-cheat-sheet.com/blob/master/LICENSE

Not sure if there are any options here.

It could hook nicely into the transformer chain, maybe. Not sure how be should bundle the images.

Should have a flag, default off.

**Comment by digitalcraftsman** [comment]
[kyokomi/emoji](https://github.com/kyokomi/emoji) seems to be a lightweight Go implementation for printing emojis.

**Comment by bep** [comment]
Thanks, @digitalcraftsman  - I have tested that one in Hugo (see PR in progress) and it only partially works in my tests ... And it is not very efficient the way it is done now, but that can be fixed ... Will have a look at it ... later.

**Comment by bep** [comment]
Maybe this is better to do directly with the content files.

**Comment by bep** [comment]
OK, I found the issue now ... that emoji gets confused if you have colon ( : )  in your text ...

**Comment by digitalcraftsman** [comment]
That was a fast bugfix. I think it would also make sense to add a template function, something like `emojify`.

**Comment by bep** [comment]
Another issue in that library: https://github.com/kyokomi/emoji/issues/6

It doesn't matter too much for us as I'm rewriting the replacement part of it to fit Hugo, but I use that library as a facit in my tests.

**Comment by yangwao** [comment]
Thanks!

**Comment by yangwao** [comment]
@bep do I need enable something for templating functions? Looks like templating doesn't work for me. 
like for example `{{ "cat" | pluralize }}` doesn't work for me, it just prints {{ "cat" | pluralize }}

**Comment by bep** [comment]
@yangwao please use http://discuss.gohugo.io/ for questions.
