### ISSUE TITLE
Says shortcode has no .Inner when it does

### ISSUE THREAD

**Issue by davityle** [spf13/hugo#1894]
I have a short code `read-more.html` with the contents
```html
<div class="read-more">
    Click here to reveal text
</div>

<div class="collapse-read-more">
    Click here to hide text
</div>

<div class="body">
</div>

<div class="offscreen" >
    {{ .Inner }}
</div>
```
However when I use the shortcode. 
```
{{< read-more >}}
 ....
{{< /read-more >}}
```

I get this error

`ERROR: 2016/02/24 Shortcode 'read-more' in page '...' has no .Inner, yet a closing tag was provided`

If I leave off the closing tag than Hugo simply inserts read-more.html and ignores the `{{.Inner}}` variable. I've tried moving `{{.Inner}}` around and interacting with it in different ways but always either doesn't recognize it or ignores it if I leave off the closing tag.

**Comment by bep** [comment]
As I cannot reproduce this neither understand how on earth this check could fail, there must be *something else* in play.

* What is the output of `hugo version`?
* What OS?

The failing project; is it in the open on GitHub? If not, can you put a minified failing version out there for me to look at?

**Comment by davityle** [comment]
version: Hugo Static Site Generator v0.15 BuildDate: 2015-11-25T07:35:21-07:00
OS: Ubuntu 14.04 

I created a new project to try to reproduce the error but it worked correctly in the new project. 

Then, after in worked in the test project and without any changes, it started working in the original project.

Something weird is going on but I have no idea what it is.

You can find the project [here](https://github.com/davityle/blog)
[here](https://github.com/davityle/blog/blob/master/layouts/shortcodes/read-more.html) is the shortcode file
[here](https://github.com/davityle/blog/blob/master/content/post/health-or-points.md) is the markdown page that was failing

But it started working so idk what to tell you or if you even want to look at it.

**Comment by bep** [comment]
As I said, I have no clue -- my best guess is that the error message is wrong, that "something else" was going on -- because the "inner check" is a pretty standard regexp.

**Comment by davityle** [comment]
Alright, I'll mark it as closed. If I find a way to reproduce it I'll open a new issue with instructions on how to reproduce it.

**Comment by dicknaniel** [comment]
For me, fixing this issue was as simple as restarting the hugo server I had running.

**Comment by dmitriid** [comment]
This still happens: if you add a short code while the server is running, it's picked up incorrectly and causes the error above. Restarting the server helps

**Comment by haylingsailor** [comment]
This is happening for me too. Hugo Static Site Generator v0.16-DEV BuildDate: 2016-02-06T17:14:17Z

I was running the server with "hugo server -ws ."

* Then I added a shortcode to a page which didn't yet exist (e.g. `{{% warning %}}This is a **Warning!**{{% /warning %}}`
* Then added the definition for the shortcode in the theme which was being used (`themes/<themeName>/shortcodes/warning.html`)  - e.g.
```
<div class="alert alert-warning" role="alert">
  <strong>Warning!</strong> {{ .Inner }}
</div>
```
That's when I got this error `ERROR: 2016/12/01 16:11:51 shortcode.go:266: Shortcode 'warning' in page 'overview/access-keys.md' has no .Inner, yet a closing tag was provided`

Restarting hugo fixed it.

**Comment by bep** [comment]
Please don't comment on old issues, and esp. not if you use an ancient Hugo version.
