### ISSUE TITLE
{{<figure>}} shortcode breaks relative links when not using uglyURLs

### ISSUE THREAD

**Issue by spanezz** [spf13/hugo#1898]
Hello, and thank you for hugo.

I like to keep my pages and assets together (#330), and I'm so glad to find that it now works out of the box.

I also like to use relative paths in my pages to reference images, and ideally I could just do:
```
# halmerweg.md
{{< figure src="halmerweg.jpg" alt="Nice mural" >}}
```

However, when that becomes `halmerweg/index.html`, the image stays one level up, and the `<img>` tag that gets generated still points to just `halmerweg.jpg` instead of `../halmerweg.jpg`.

This is somehow related to #1768.

Using `relref` instead the links are correct:
```
[internal link]({{< relref "other-post.md" >}})
```
renders correctly as:
```
<a href="/blog/full/path/other-post/">internal link</a>
```

**Comment by bep** [comment]
```
{{< figure src="halmerweg.jpg" alt="Nice mural" >}}
```
What is this relative to?

**Comment by spanezz** [comment]
Oh I see. I assumed it was possible to just refer to resources relative to the current page, so to answer your question, in my example, that would have been relative to where `halmerweg.md` is located.

The ikiwiki that I currently use supports that, and it is a feature that I have so far relied on, because it allows me to prepare content without needing to know in advance where it's going to be located on the site.

**Comment by bep** [comment]
There are similar discussions/issues about this. Close this as a duplicate.
