### ISSUE TITLE
.Date is empty on index.html

### ISSUE THREAD

**Issue by helmbold** [spf13/hugo#1903]
If I insert `{{ dateFormat "2006-01-02" .Date }}` into the "layouts/index.html" file, the rendered result is "0001-01-01". It works in other templates. 

Other variables of "node" types like `.URL` or `.Title` are working as expected.

**Comment by bep** [comment]
Thanks for this report.

**Comment by thepian** [comment]
I tried something similar, not sure if it's another issue. I render dates in sitemap.xml and for the layouts/index.html it uses 0001-01-01

    <lastmod>0001-01-01</lastmod>
