### ISSUE TITLE
Shortcodes with rst are broken

### ISSUE THREAD

**Issue by fbeutel** [spf13/hugo#1904]
When using restructuredText, the rst2html tool converts the `@` sign into the HTML entity code `&#64;`.
Apparently that screws up the shortcode mechanism in hugo.

I'm not sure if there is a way to tell rst2html to stop doing that (I didn't find any such options), but if not then probably the simplest thing to do would be to adapt the shortcode replacement code to look for `&#64;` instead of `@`

**Comment by bep** [comment]
The `@` sign is just picked by random, it can be anything, but the replacement function is hand-coded for pure speed, so it should ideally be a one-byte character and not 5 ... What does RST not encode?

**Comment by fbeutel** [comment]
A quick test showed that the following characters are not being encoded, at least when using no special settings and using docutils version 0.12:
`? + _ # ~ - / ! § $ % = ° :`

Plenty to choose from :)
