### ISSUE TITLE
set config from `hugo` command

### ISSUE THREAD

**Issue by robmuh** [spf13/hugo#1909]
Making hugo a part of an event-driven or crontab auto-build system (as many others) and am currently setting a `setdate` config value dynamically in the config.toml file, which got me to thinking being able to pass in one or two key/value pairs from the hugo command-line that automatically get written/updated in the config file might be handy. Just saves the step to automate the changing of those lines in a script before calling hugo for the compile. Not a huge issue, just posting to get thoughts on.

**Comment by bep** [comment]
Hmm ... That sounds like a feature that is best handled by text editors, in any case this feels like a topic for https://discuss.gohugo.io/

**Comment by robmuh** [comment]
Definitely not a text editor thing, which misses the whole point of "an event-driven or crontab auto-build" system. But I will take it up there and hopefully someone will comprehend the question.
