### ISSUE TITLE
How to prevent blackfriday from interpret & to &amp;

### ISSUE THREAD

**Issue by invkrh** [spf13/hugo#1914]
I need to write & in my latex formule.
But it seems that blackfriday interprets `&` to `&amp;` which can not recognized by Katex.
Any way to turn off this feature via configuration ?

**Comment by bep** [comment]
> Any way to turn off this feature via configuration ?

Not in Hugo. You could ask https://github.com/russross/blackfriday

**Comment by bep** [comment]
BTW, I'm not sure it's Blackfriday who encodes those amperands; it could be insightful if you posted a question at https://discuss.gohugo.io/

**Comment by invkrh** [comment]
Hi, I have posted my question on both of them
