### ISSUE TITLE
Stable .ByCount index sort?

### ISSUE THREAD

**Issue by frioux** [spf13/hugo#1930]
Currently the .ByCount sorter for indices does not order things reliably within a given count.  This means that every time I make a build my index of tags changes order.  It's not a huge deal but it's sortav annoying and adding a secondary sort seems like it would only help.  I could probably draft a patch but I wanted to verify that others are interested first.

**Comment by bep** [comment]
Patch is welcomed.

**Comment by frioux** [comment]
Cool.  I just upgraded to 0.15 and I think this was resolved without any kind of mention in the Changelog.  I'll verify and then close.

**Comment by bep** [comment]
@frioux have you checked?

**Comment by frioux** [comment]
Yeah, sadly the issue does still exist.  I am not sure why it varied from
one system to the next.  I still would like to send a patch but if I don't
get around to it it seems like good low hanging fruit.

On Fri, Mar 11, 2016 at 8:05 AM, Bjørn Erik Pedersen <
notifications@github.com> wrote:

> @frioux <https://github.com/frioux> have you checked?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spf13/hugo/issues/1930#issuecomment-195429299>.
>



-- 
fREW Schmidt
http://blog.afoolishmanifesto.com

**Comment by moorereason** [comment]
A patch would be great, but a test case that could be added to `hugolib/taxonomy_test.go` would be helpful, too.  We clearly need more tests for the taxonomies.
