### ISSUE TITLE
Multiple Menus only has first menu array element

### ISSUE THREAD

**Issue by jeremyricharddavies** [spf13/hugo#1934]
If I create a front-matter menu entry for content that should be in multiple menus (as per the example in the documentation) :
```
---
menu: ["main", "footer"]
---
```
when I try to access .Site.Menus.footer there is nothing there. .Site.Menus.main works correctly. If I reverse the definition :
```
---
menu: ["footer", "main"]
---
```
then .Site.Menus.footer works but .Site.Menus.main is empty.

Version: Hugo Static Site Generator v0.15 BuildDate: 2015-11-25T14:36:28Z

**Comment by bep** [comment]
A workaround is to define the menu entries as dictionaries:

```
menu: 
    p_footer:
    main:
```
There is a superfluous error in the log with the above, too. I will fix that (you could add some of the attributes to the menu entries to fix that ...).

**Comment by codefx9** [comment]
@bep, thanks a lot for fixing this bug. It will be great if this can be mentioned in the docs. I wasted half a day thinking something else was broken in my website. I installed hugo via brew, so don't get these latest fixes like `go get`.

**Comment by bep** [comment]
> It will be great if this can be mentioned in the docs. 

I agree; if you could maintain a list of bugs fixed that is not yet released, and keep it in sync at all times in the future, that would be a valuable contribution.

Thanks for volunteering.

**Comment by codefx9** [comment]
@bep, may be an less time consuming solution will be to just mention in the readme file that this project does not release patch versions of cli / Master is usually stable enable for day to day use / `go get is the preferred installation method` or some combination of these. Then users can use `go get` to get latest bug fixes for hugo.
