### ISSUE TITLE
docs: Add doc for Go 1.6 block syntax

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1947]
See https://github.com/spf13/hugo/pull/1836

**Comment by ebsen** [comment]
Hi! I mentioned taking a stab at this over at [Hugo's discussion site](https://discuss.gohugo.io/t/inherited-layouts/955/8?u=ele). Thanks for pointing me toward the [Ace documentation](http://gohugo.io/templates/ace/).

From that, I understand how Hugo can identify a base theme using Ace but I don't see how that system could apply to "regular" template files (i.e., those not suffixed with `.ace`) and work within the existing single/list/homepage system. Could we follow the same rules as with Ace, just with `base.html` instead? Could/does `_default/single.html` serve as the de facto "base" template? That seems to be the first place Hugo looks, so maybe blocks defined there carry on down the chain?

These might be dumb questions but I haven't got Hugo compiled on 1.6 yet to try anything out so I thought I'd ask.

**Comment by bep** [comment]
@ebsen have a look at my blog at https://github.com/bep/bepsays.com/tree/master/layouts I have both Ace base templates and Go base templates living side by side: Ace for the list and Go for the rest. The base templates are named "baseof.<suffix>". As I said: Conceptually this works EXACTLY like the Ace.

**Comment by ebsen** [comment]
Okay. I was just overthinking it then.

**Comment by ebsen** [comment]
No pull request yet because I want to test locally with a 1.6 build but initial draft here: https://github.com/ebsen/hugo/commit/f429fc7b030bdf60888c94022c04c9885d4df1bf

**Comment by ebsen** [comment]
Submitted #2043 to document new block syntax.

**Comment by digitalcraftsman** [comment]
Merged in 65f9427031ae57c0d78360dbbfe03428fe922b49.
