### ISSUE TITLE
Always set Markup variable in Page struct

### ISSUE THREAD

**Issue by ypnos** [spf13/hugo#1950]
Theme behavior may depend on the markup processor used. An example is custom CSS for markdown tables that would ruin asciidoc styling.

Right now, the `Page` struct has a `Markup` variable. It can be set explicitely to override markup-type guessing. However, if the type is guessed, it remains unset, therefore being unavailable to the theme.

This would be a place where the  variable could be set:
https://github.com/spf13/hugo/blob/924028a9be4e468b38f3b7a530253c7c09a0d10e/hugolib/page.go#L813

However that might be an unexpected side-effect. I would suggest to rename `guessMarkupType` in `determineMarkupType`, then call it explicitely as an initialization step before rendering and always use `Page.Markup` when rendering.

**Comment by bep** [comment]
>However that might be an unexpected side-effect. 

Yea, not really. It is fairly controlled: One could argue that Page.Markup is a cached version ...
