### ISSUE TITLE
docs: Add sourceRelativeLinks to Blackfriday options

### ISSUE THREAD

**Issue by moorereason** [spf13/hugo#1958]
Needs docs for this commit: https://github.com/spf13/hugo/commit/0f6b334b6715253b030c4e783b88e911b6e53e56

**Comment by moorereason** [comment]
@SvenDowideit,
I was looking at documenting these changes from back in September, but I have a question:  what does the `sourceRelativeLinks` have to do with Blackfriday?

All of the config options under `blackfriday` have to do with toggling Blackfriday extensions.  Your `sourceRelativeLinks` option does not.  Should the `sourceRelativeLinks` feature be decoupled from the Blackfriday options?

**Comment by moorereason** [comment]
Already work in progress in #1977

**Comment by SvenDowideit** [comment]
I'm not sure :)

at this point, its a blackfriday only - it hasn't been implemented when using the MMark renderer.

setting the option overrides the blackfriday link and file render functions.

**Comment by moorereason** [comment]
Fixed by #1977
