### ISSUE TITLE
helpers: TestCodeFence test FAIL with Pygments 2.1 (since Jan 2016)

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#1969]
On my local Debian GNU/Linux go1.6 installation, running `go test ./...` on current Hugo master fails:

```
--- FAIL: TestCodeFence (0.53s)
	content_renderer_test.go:69: Test 0 failed. BlackFriday enabled:true, Expected:
		"<div class=\"highlight\"><pre><code class=\"language-html\" data-lang=\"html\"><span class=\"nt\">&lt;html&gt;&lt;/html&gt;</span>\n</code></pre></div>\n" got:
		"<div class=\"highlight\"><pre><code class=\"language-html\" data-lang=\"html\"><span class=\"p\">&lt;</span><span class=\"nt\">html</span><span class=\"p\">&gt;&lt;/</span><span class=\"nt\">html</span><span class=\"p\">&gt;</span>\n</code></pre></div>\n"
	content_renderer_test.go:74: Test 0 failed. Mmark enabled:true, Expected:
		"<div class=\"highlight\"><pre><code class=\"language-html\" data-lang=\"html\"><span class=\"nt\">&lt;html&gt;&lt;/html&gt;</span>\n</code></pre></div>\n" got:
		"<div class=\"highlight\"><pre><code class=\"language-html\" data-lang=\"html\"><span class=\"p\">&lt;</span><span class=\"nt\">html</span><span class=\"p\">&gt;&lt;/</span><span class=\"nt\">html</span><span class=\"p\">&gt;</span>\n</code></pre></div>\n"
FAIL
FAIL	github.com/spf13/hugo/helpers	0.558s
```

What perplexed me was that our Travis CI tests etc. all pass.  It took me a while to realize that TestCodeFence() is only run when Pygments is available, whereas none of our automated CIs environment install Pygments.

**Comment by anthonyfok** [comment]
TestCodeFence() was added by Andrew Brampton (@bramp) in commit c2c694f in September 2015, when Debian had Pygments 2.0.1 (upstream: Pygments 2.0.2).  Then, in January 2016, Pygments 2.1 was released, and Debian had the new version packaged in 8 days.

Could this be a simple case of Pygments changing its rendered output in the new version?  To be tested.

**Comment by anthonyfok** [comment]
Turns out that indeed Pygments 2.0.x and Pygments 2.1.x produce slightly different rendered HTML output.

I downgraded to Pygments 2.0.1 (2.0.1+dfsg-1.1+deb8u1 to be exact)using `sudo apt-get install python-pygments/jessie`, and `go test ./...` on Hugo passes.  Once I upgraded it to (almost) the latest version (2.1+dfsg-1, whereas upstream now has 2.1.1), TestCodeFence fails.

**Comment by bep** [comment]
>CIs environment install Pygments.

I now know how to add that to CircleCI, will add fix that.

**Comment by anthonyfok** [comment]
Wow, that was a really quick and thorough fix!  Thank you @bep!
