### ISSUE TITLE
Partial file can not use the outer context passed to it

### ISSUE THREAD

**Issue by invkrh** [spf13/hugo#1981]
I have a partial file, like the following:

File: pagination.html
```html
<div class="pagination">
  {{ if .NextInSection }}
    <a class="btn next" href="{{.NextInSection.Permalink}}">Next</a>
  {{ end }}
  {{ if .PrevInSection }}
    <a class="btn previous" href="{{.PrevInSection.Permalink}}">Prev</a>
  {{ end }}
</div>
```

In the post's single.html file, I wrote the following:
```
{{ partial "pagination.html" . }}
```

Then the build come up with an error saying:
`NextInSection` is not a field of struct type `*hugolib.Node`

However, if I replace the partial part in `single.html` with `pagination.html`'s content. It works.

When calling partial file in `single.html`, I just passed the current context to it. Normally, pagination.html should take the outer context and find the `.NextInSection` variable.

Maybe I am missing something here. Any ideas ?

**Comment by moorereason** [comment]
This should not happen.  What version of Hugo are you running?

If you are doing this from a `single.html` page template, the default context should be `*hugolib.Page`.  What does the following do?

```
{{ partial "pagination.html" $ }}
```
`$` is an alias to the initial template context.

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions.

@moorereason I know you started a dialogue here, but if we cut a strict line here, we'll drown.

**Comment by invkrh** [comment]
Hi @moorereason @bep ,

I have posted a question on the forum
https://discuss.gohugo.io/t/partial-file-can-not-use-the-outer-context-passed-to-it/2931

@moorereason , I have tried what you said. There are still errors.
In fact, the strange thing here is that the pagination still works on my site even if there are errors during compilation. FYI, the version of hugo is v0.15
