### ISSUE TITLE
export wordpress themes to hugo

### ISSUE THREAD

**Issue by icf20** [spf13/hugo#1990]
i was searching about this but i dint find any relevant information about exporting wordpress themes to hugo, how is this done ?

**Comment by Jos512** [comment]
Please ask questions like these on the [Hugo forum](https://discuss.gohugo.io/); GitHub is used for concrete issues and requests/enhancements.

But to answer your question, there's no automated way to convert a WordPress theme to Hugo. See the available Hugo themes [here](http://themes.gohugo.io/) for examples, and the [documentation](http://gohugo.io/overview/introduction/) for more information about Hugo.
