### ISSUE TITLE
 page.go:832: Error parsing page meta data

### ISSUE THREAD

**Issue by icf20** [spf13/hugo#1991]
i did a test on the documentation example and i got the following error

> hugo serve  
> page.go:832: Error parsing page meta data for review/book01.md

**Comment by digitalcraftsman** [comment]
Which version of Hugo are you using? Run `hugo version` to find it out. I tested it with the latest release and the current developer version (HEAD).

**Comment by bep** [comment]
I just verified that the page metadata examples in this example are correct and working. This feels like a question better suited for http://discuss.gohugo.io/

**Comment by icf20** [comment]
the issue is still there

```
hugo serve -w
ERROR: 2016/04/10 06:34:48 page.go:832: Error parsing page meta data for review/book01.md
ERROR: 2016/04/10 06:34:48 page.go:833: yaml: line 2: did not find expected <document start>
ERROR: 2016/04/10 06:34:48 page.go:393: yaml: line 2: did not find expected <document start>
Error: Error building site: Errors reading pages: Error:yaml: line 2: did not find expected <document start> for book01.md
```
```
cat book01.md 
---
...
affiliatelink: "http://www.my-book-link.here"
recommendedby: "my Mother"
---
`

```
hugo version
Hugo Static Site Generator v0.16-DEV BuildDate: 2016-02-06T18:14:17+01:00
```


```
tree
.
├── archetypes
├── config.toml
├── content
│   └── review
│       └── book01.md
├── data
├── layouts
```

**Comment by moorereason** [comment]
Remove `...`

**Comment by icf20** [comment]
@moorereason why? what’s the logic behind that ?

**Comment by digitalcraftsman** [comment]
This snippet is an example from the docs. Usually, the frontmatter contains more information like a date or the title. But those information aren't relevant for the example. Therefore, they are removed. `...` should just indicate that this is only an excerpt.

**Comment by icf20** [comment]
@digitalcraftsman thank you for the information, i had no way to guess that ... are supposed to be

**Comment by isaisi98** [comment]
Tengo este error 

Building sites … Built in 189 ms
Error: Error building site: "C:\hugo\site\tarea3\content\post\Metadatos-post.md:2:1": failed to unmarshal YAML: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `Metadat...` into map[string]interface {}
