### ISSUE TITLE
Rebuild doesn't handle change in sort order

### ISSUE THREAD

**Issue by bep** [spf13/hugo#1993]
Say you create a new post by `cp some-old-post.md new-version.md` and then change the date when in `watch` mode, you will have to restart the server to see the new page at the top of stack.

I guess this is a consequence of the new "partial read" implementation. 

/cc @spf13

**Comment by spf13** [comment]
Just to make sure I understand the issue, the date updates properly for that content, but it's not re-sorted. 

Yeah, I didn't trigger a sort after updating the meta data. Should be an easy fix.

**Comment by bep** [comment]
>Just to make sure I understand the issue, the date updates properly for that content, but it's not re-sorted. 

Yes, I guess the page is just "appended at the end".

**Comment by bep** [comment]
But: This "partial read" feature of yours has not been without issues, and I'm pretty sure there are other related issues (I jotted down something about ignoreFiles), so it would be great if a fix for this also could supply some test harness around all of this.

**Comment by bep** [comment]
I cannot reproduce this now, seems to have been fixed.
