### ISSUE TITLE
Add surge.sh to main page of static site hosters

### ISSUE THREAD

**Issue by robmuh** [spf13/hugo#1994]
Surge.sh is one of the easiest static site hosting services our there (all our students use it). I'd like to add it to the list on the home page. Will submit pull req.

**Comment by anthonyfok** [comment]
Thank you for your contribution!  @digitalcraftsman merged Pull Request #1996 a few days ago:

> I've merged your additions as d65fbfe (master) and eff078f (v0.15.docs).

thus fixing this issue.  Closing it now.
