### ISSUE TITLE
Single-page independent layout like 404.html (atom.xml, etc.)

### ISSUE THREAD

**Issue by solarsailer** [spf13/hugo#2011]
Hello,

I'm migrating from Jekyll and I would like to port my atom.xml file (I don't want to use the built-in functionality for RSS—it creates a feed for every section, and I just want a global feed for a list of post that I choose myself).

A solution would be to create a new layout in `layouts/` which, like every node, could access the site pages and data. However, I can't find a way to create a layout which will be converted to a page like the 404.html layout.

Is it possible? I would want that for my atom.xml file, but I can see other uses in the future.

Thanks. :)

**Comment by digitalcraftsman** [comment]
Please ask questions like this in the [Hugo forum](https://discuss.gohugo.io/); GitHub is used for concrete issues and requests/enhancements.
