### ISSUE TITLE
Proposal: add a isExternal template func

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2012]
While creating themes I got requests from users to be able link to link locally (inside the Hugo website) or to external sources. Common usecases would be:

- a menu that either links to some page of the website with a relative path
- custom assets that are either stored locally in `static/` or externally (e.g. with a CDN)
  - or as shown below a banner that is used as thumbnail for posts. The picture is either stored locally or on a different server (externally)

My current approach is to check wether the link starts with `https://` or `http://`. This causes a lot boilerplate code that checks if such a substrings exists:

```html
{{if or (in (substr .Params.banner 0 7) "http://") (in (substr .Params.banner 0 8) "https://")}}
    <img src="{{ .Params.banner }}" class="article-banner">
{{ else }}
    <img src="{{ .Site.BaseURL }}{{ .Params.banner }}" class="article-banner">
{{end}}
```

Therefore, I suggest to add a template functions that checks if a string starts with `https://` or `http://`. Other protocolls can be added if you like. The function should return a boolean. That allows me to write cleaner code:

```html
<img src="{{ if .Params.banner | isExternal }}{{ .Params.banner }}{{ else }}{{ .Site.BaseURL }}{{ .Params.banner }}{{end}}" class="article-banner">
```

Now I have a nice one-liner.

**Comment by bep** [comment]
What about:

```
<img src="{{ if .Params.banner | absURL }}" class="article-banner">
```

**Comment by digitalcraftsman** [comment]
I tested this with multiple URLs the logic shows always `external`:

```
{{ if .Permalink | absURL }}external{{else}}local{{end}}
{{ if "https://google.com" | absURL }}external{{else}}local{{end}}
{{ if "/post/foo/" | absURL }}external{{else}}local{{end}}
```

**Comment by bep** [comment]
That doesn't look remotely similar to my example.
