### ISSUE TITLE
Wish a feature for TODO lists (Incorporate shurcooL/github_flavored_markdown?)

### ISSUE THREAD

**Issue by weaming** [spf13/hugo#2022]
```
* [ ] foo
* [x] bar
* [ ] baz
```

Refer: [FND/markdown-checklist: Python Markdown extension for lists of tasks with checkboxes](https://github.com/FND/markdown-checklist)

**Comment by bep** [comment]
Your odds getting this improves drastically if you open an issue at https://github.com/russross/blackfriday

**Comment by weaming** [comment]
@bep 
...

Done.

**Comment by weaming** [comment]
[Wish a feature for TODO lists · Issue #249 · russross/blackfriday](https://github.com/russross/blackfriday/issues/249)

**Comment by anthonyfok** [comment]
Interesting!  @shurcooL, who helps maintain blackfriday, replied at russross/blackfriday#249:

> FWIW, this is already implemented in github_flavored_markdown, which is a renderer that implements the blackfriday.Renderer interface. It's listed here:
>
> https://github.com/russross/blackfriday#other-renderers
> 
> (It wasn't hard, just... shurcooL/github_flavored_markdown@2b74a5b .)

So, it appears that it can be incorporated into Hugo, perhaps in a special "GitHub Flavored Markdown" mode.

**Comment by phtan** [comment]
I want to tackle this. As far as I can see, nobody is claiming this issue.

**Comment by shurcooL** [comment]
Let me know if you have any questions or if I can provide helpful guidance with this.

**Comment by phtan** [comment]
@shurcooL , I appreciate your offer. I found what I needed when I looked through your tests at the github_flavored_markdown repository.

**Comment by bep** [comment]
Replaced by more concrete issues.

**Comment by phtan** [comment]
@shurcooL , was `github_flavored_markdown.Markdown()` meant to be a replacement of  blackfriday? Can a developer use github_flavored_markdown while still using blackfriday?

**Comment by shurcooL** [comment]
@phtan, yes, `github_flavored_markdown.Markdown` method is very high level and does everything needed to convert source Markdown to output HTML, using GitHub-Flavored Markdown rendering rules.

It also performs HTML sanitization (since the GFM rendering method does too).

It uses `blackfriday` for parsing and rendering, and `bluemonday` for sanitization.

You can look at the [code](https://github.com/shurcooL/github_flavored_markdown/blob/b3921bea4a899100a4fd522dd940b819af56e437/main.go#L31-L59):

```Go
// Markdown renders GitHub Flavored Markdown text.
func Markdown(text []byte) []byte {
	htmlFlags := 0
	renderer := &renderer{Html: blackfriday.HtmlRenderer(htmlFlags, "", "").(*blackfriday.Html)}

	// Parser extensions for GitHub Flavored Markdown.
	extensions := 0
	extensions |= blackfriday.EXTENSION_NO_INTRA_EMPHASIS
	extensions |= blackfriday.EXTENSION_TABLES
	extensions |= blackfriday.EXTENSION_FENCED_CODE
	extensions |= blackfriday.EXTENSION_AUTOLINK
	extensions |= blackfriday.EXTENSION_STRIKETHROUGH
	extensions |= blackfriday.EXTENSION_SPACE_HEADERS
	//extensions |= blackfriday.EXTENSION_HARD_LINE_BREAK

	unsanitized := blackfriday.Markdown(text, renderer, extensions)

	// GitHub Flavored Markdown-like sanitization policy.
	p := bluemonday.UGCPolicy()
	p.AllowAttrs("class").Matching(bluemonday.SpaceSeparatedTokens).OnElements("div", "span")
	p.AllowAttrs("class", "name").Matching(bluemonday.SpaceSeparatedTokens).OnElements("a")
	p.AllowAttrs("rel").Matching(regexp.MustCompile(`^nofollow$`)).OnElements("a")
	p.AllowAttrs("aria-hidden").Matching(regexp.MustCompile(`^true$`)).OnElements("a")
	p.AllowAttrs("type").Matching(regexp.MustCompile(`^checkbox$`)).OnElements("input")
	p.AllowAttrs("checked", "disabled").Matching(regexp.MustCompile(`^$`)).OnElements("input")
	p.AllowDataURIImages()

	return p.SanitizeBytes(unsanitized)
}
```

The `renderer` type implements [`blackfriday.Renderer`](https://godoc.org/github.com/russross/blackfriday#Renderer) interface, but it's not exported (because I didn't think anyone would need it).
