### ISSUE TITLE
tpl: Extend "where" to iterate over maps

### ISSUE THREAD

**Issue by moorereason** [spf13/hugo#2028]
Hugo can't resolve the following template construct since the starting sequence is a map:

```
{{ range where .Site.Data.person "name" "Victor Hugo" }}
```

Extend `where` to iterate over maps.

See [Tutorial: Link .Site.Data to Content Types by Filename](https://discuss.gohugo.io/t/tutorial-link-site-data-to-content-types-by-filename-call-for-review/3011) discussion.

**Comment by waddles** [comment]
Is that even correct syntax? Shouldn't it be
```
{{ range where .Site.Data.person ".name" "eq" "Victor Hugo" }}
```

**Comment by bep** [comment]
I believe where defaults to eq if not present.

**Comment by TSFoster** [comment]
+1 from me, I just ran into the exact same problem.

FWIW, this is what I ended up with, I'd be interested to know if there was something more elegant:

```hbs
{{ $people := slice }}
{{ range .Site.Data.people }}{{ $people = $people | append . }}{{ end }}
{{ range where $people "name" "Victor Hugo" }}
  {{ .twitter_handle }}
{{ end }}
```
