### ISSUE TITLE
docs: Fix references to section list templates

### ISSUE THREAD

**Issue by moorereason** [spf13/hugo#2032]
Section list templates are looked up as described in http://gohugo.io/templates/list/.

http://gohugo.io/content/types/ is wrong in listing `/layouts/post/list.html` as a valid template location.  Should be in `/layouts/section/post.html`.  This section was removed in HEAD, but the 0.15 docs (and the hugo website) are still inaccurate.

http://gohugo.io/tutorials/creating-a-new-theme/ is wrong in telling you to create `article/list.html`.

**Comment by wholien** [comment]
Can I take this? This a simple change to the docs, right?

**Comment by bep** [comment]
>

>Can I take this? This a simple change to the docs, right?

Go ahead! Help is much appreciated.

**Comment by wholien** [comment]
@moorereason @bep what is the pull request workflow? Should I ping people after a pull request is created or will people get to them eventually? Thanks.
