### ISSUE TITLE
Support the ability to ignore files based on regex

### ISSUE THREAD

**Issue by cfjedimaster** [spf13/hugo#2046]
I've got a Hugo implementation of a blog with over ten years of content (5.5K entries). While I've done a few things to speed up compilation, I'd love the ability to tell Hugo to simply ignore content/post/200*/ while working. That would cut out about 7 years of history and - in theory - greatly speed up compilation even more.

**Comment by moorereason** [comment]
What version of Hugo are you running?

**Comment by cfjedimaster** [comment]
Latest, 0.15 I believe.

**Comment by cfjedimaster** [comment]
Btw, I see ignorefiles in the config docs, but I'd be worried about forgetting that when I go to production. I don't see a way to pass that setting via CLI.

**Comment by moorereason** [comment]
There have been changes to 0.16-DEV server mode such that Hugo only rebuilds changed files whiles you work (although, it does need to build everything on initial startup).  Do you think that would solve your issue?

**Comment by cfjedimaster** [comment]
Sure. I'd love to see that. Easy to upgrade/downgrade?

**Comment by moorereason** [comment]
Depends on where you're starting from.  You'll have to build it from source.  See the [README](https://github.com/spf13/hugo/blob/master/README.md).  If you have more questions, ask them in the discussion forums.

**Comment by cfjedimaster** [comment]
Ok - thank you!

On Mon, Apr 4, 2016 at 3:02 PM, Cameron Moore <notifications@github.com>
wrote:

> Depends on where you're starting from. You'll have to build it from
> source. See the README
> <https://github.com/spf13/hugo/blob/master/README.md>. If you have more
> questions, ask them in the discussion forums.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/spf13/hugo/issues/2046#issuecomment-205470653>
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for StrongLoop at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by bep** [comment]
In Hugo 0.15 there is also the ignoreFiles option; A list of content regexps to ignore.

**Comment by cfjedimaster** [comment]
@bep As far as I know, that is a config file only setting, and my concern is forgetting to remove that for a 'real' build.
