### ISSUE TITLE
Enhancement Suggestion: run script after rebuilding

### ISSUE THREAD

**Issue by windch** [spf13/hugo#205]
Forked for minor enhancement.  [https://github.com/windch/hugo](https://github.com/windch/hugo)

This fork will run script "runme" which is under the base folder whenever rebuilding finished. So that one could easily sync the latest public folder to remote server with rsync efficiently.

Typically the script "runme" could be something like:

    #!/bin/bash
    rsync -aze ssh public/ user@remoteserver:/opt/www/projecta --stats --delete

Just a minor hack with several lines added to hugo/command/hugo.go.   Maybe one parameter, such as 'run-script: runme', could be added to config.yaml to make things formal.   But that would make too much modification to the original codes.

Thanks for the great golang project.

**Comment by bep** [comment]
Duplicates #47
