### ISSUE TITLE
Docs - How to get sidenav of sibling content?

### ISSUE THREAD

**Issue by wmakley** [spf13/hugo#2050]
I am trying to follow this example: https://gohugo.io/templates/list/ but it only works on the home page! I think? It really isn't clear at all how to get a list of sibling items.

Context: I have a content type called "attorney" and I want to list other attorneys in the side navigation in the "single" layout. Reading the documentation, it is REALLY vague to me what the name of this data will be, if anything.

**Comment by bep** [comment]
Try https://discuss.gohugo.io/
