### ISSUE TITLE
Make footnote URL nicer

### ISSUE THREAD

**Issue by octref** [spf13/hugo#2056]
Currently the generated footnote turns URL into this:

`http://localhost:1313/read/post/1/#fnref:10d8aa81d13021669fdcd5a46901e0c0:1`

Is it possible to have something like:

`http://localhost:1313/read/post/1/#fnref:1`?

Or should this issue belong to `blackfriday`?

**Comment by bep** [comment]
The funky (md5) comes from us. 

What do you get with:

```
[blackfriday]
  plainIDAnchors = true
```

**Comment by octref** [comment]
Works great. Thank you so much! 🍻
