### ISSUE TITLE
Support for case sensitive indexes

### ISSUE THREAD

**Issue by zachad** [spf13/hugo#206]
Is there a way to have case-sensitive indexes within Hugo?  There's a comment at https://github.com/spf13/hugo/blob/master/hugolib/index.go#L60 that indicates that it could be possible someday.

It would be great to create categories that are case (and space) sensitive. 

```yaml
---
categories:
  - Introductory Text
  - Help Notes
---
```

And be able to list them so that they keep the original formatting.

```
{{ range .Site.Indexes.categories.ByCount }}
<li>{{ .Name }}</li>
{{ end }}
```

What would need to be done to accomplish this?

**Comment by bep** [comment]
Set 

```
preservetaxonomynames: true
```
in config. And the indexes will be, among other things, case sensitive.
