### ISSUE TITLE
Add splitRE template func

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2061]
`splitRE` would work analogous to #2048. Users pass the regular expression, content that should be splitted and an optional third parameter to limit the matches. A slice of strings would be returned.

```
{{ splitRE "<h2.*?>(.|\n)*?</h2>" .Content }}
```

It's implementation would upon `regexp`'s [`split`](https://godoc.org/regexp#Regexp.Split) function.

**Comment by bep** [comment]
Hmm... I think we should think hard before we add more regexp stuff. This is needed to patch shortcomings of Hugo, and it opens up to fairly ineffective pipelines of 

```
{{ index (.Content | splitRe "h1") 0 }}
{{ index (.Content | splitRe "h1") 1 }}
```
We should solve this properly, I believe there are other issues floating around about getting the different content sections.

**Comment by digitalcraftsman** [comment]
The reason why I planned to implement both template funcs was to improve the [results of the search index](https://github.com/spf13/hugo/pull/1853#issuecomment-204764754). I know that regexp are a bad (and perhaps slow) approach to solve the problem. But the template limit my possibilities.

Maybe you new an alternative way to achieve this.

**Comment by bep** [comment]
This is the alternative: https://github.com/russross/blackfriday/issues/166

Hugo's speed is one of its main selling points, and is the reason why I spent three hours implementing a emoji parser instead of using an existing slow, memory-consuming and buggy one. It adds up. This function would maybe be fine when used "within reason", but then it ends up in your themes and it becomes the new Hugo benchmark.

**Comment by bep** [comment]
Regexps isn't bad. But in this case it is the wrong choice.

**Comment by digitalcraftsman** [comment]
As I stated I know that regexp are not my first tool of choice in this case. That why I asked for better alternatives and I share your thoughts.

The linked Blackfriday issue would solve a lot of problems. But the project doesn't seems to be very active (I do not want to blame anyone - it's just an observation).

Concluded: we have to wait.

**Comment by DanySK** [comment]
I would need this now... I need to split a string that may end with Unix or Windows newlines, and by far this would be the easiest way to do it I can think of.

**Comment by DanySK** [comment]
(I will use `replaceRE` + `split` as a substitution, I guess that is the intended way to do it...)
