### ISSUE TITLE
--ignoreCache=true doesn't work for pygments

### ISSUE THREAD

**Issue by srsudar** [spf13/hugo#2066]
It appears that calling `hugo server -w --buildDrafts --ignoreCache=true` doesn't actually ignore the cache when it comes to styling via `pygments`. Perhaps I'm misunderstanding how that argument is supposed to work, but I was editing a custom pygment style and couldn't seem to get it to take. Turns out it was due to the caching feature. Deleting the hugo cache dir gave me back the changes.

I would expect `--ignoreCache=true` to also refresh pygments. Apologies if I'm missing how this is supposed to work.

**Comment by bep** [comment]
>I would expect --ignoreCache=true to also refresh pygments. Apologies if I'm missing how this is supposed to work.

No, that makes perfectly sense, but I notice that that flag isn't used for Pygments. It should.

**Comment by bep** [comment]
Also re. the description of the flag:

```
"Ignores the cache directory for reading but still writes to it"
```
Ignore that ... ignore is ignore both for write and read. Keep it simple stupid.
