### ISSUE TITLE
Error building hugo template

### ISSUE THREAD

**Issue by teopost** [spf13/hugo#2073]
Hi,
  I have this error building hugo template (https://github.com/spf13/hugo/tree/master/docs)

```bash
$ docs:  hugo
ERROR: 2016/04/11 template: index.html:143: function "shuffle" not defined
ERROR: 2016/04/11 Error while rendering homepage: html/template: "index.html" is an incomplete template
````

**Comment by digitalcraftsman** [comment]
Hello @teopost,

the master branch is the (stable) developement branch. `shuffle` is a template function that will be part of the next release of Hugo. You seem to use the one of the already released versions.
