### ISSUE TITLE
Project website isn't rebuild automatically

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2074]
Within the last days I merged pull request for the documentation. But the docs aren't rebuild. A look in the build log of Wercker showed that it was unable to `go get` an updated version of `afero`.

/cc @bep

**Comment by bep** [comment]
This builds on a @spf13 server -- so no use in pinging me.

**Comment by digitalcraftsman** [comment]
I'm sorry. I thought it would be possible to fix this in the `wercker.yml` file.
