### ISSUE TITLE
Doesn't copy everything if url is specified

### ISSUE THREAD

**Issue by Keats** [spf13/hugo#2077]
To give some context, I'm doing a portfolio where there pages are `project`.
For example a frontmatter would be 
```md
+++
client = "ACME"
date = "2016-04-14T19:32:42+01:00"
tags = ["x", "y"]
title = "Some UX work"
url = "acme"
listimages = ["abc.png", "abc@2x.png"]
+++
```
I specify the url to have a clean domainname.com/acme and I would like to put all the assets for a project in a folder so the directory structure is:

```bash
├── content
│   └── project
│       └── test1
│           ├── abc@2x.png
│           ├── abc.png
│           └── index.md

```

2 things I noticed after trying that and just running `hugo` to see the output:

- the `project/test1` folder is still copied, including the assets in it while
- the `acme` folder only contains the index.html

Both of those sound like a bug, duplicated creation and not copying the full folder).

**Comment by bep** [comment]
This is as designed. Changes to this approach is well discussed elsewhere here and on http://discuss.gohugo.io/

**Comment by Keats** [comment]
Just for people finding this issue, you can do the right link like so for the case above:

```
{{ .Site.BaseURL }}{{$project.Source.Dir}}{{ index $project.Params.listimages 0 }}
```
