### ISSUE TITLE
go parser not ignoring commented hugo code

### ISSUE THREAD

**Issue by Lynxiayel** [spf13/hugo#2082]
Say we have a template file test.html as follows:
`<!-- {{ if eq 1 1}} -->`

The hugo code is inside html comments, thus it should do nothing and hugo should build fine with it, at least I think that's the expected behavior. But for now, hugo's template function complains the test.html to be incomplete.

If we change test.html to:
```
<!-- {{ if eq 1 1 }} -->
<!-- {{ end }} -->

```
The problem is gone. I guess the go parser is not ignoring commented hugo code which leads to this issue.

**Comment by bep** [comment]
If you think Go's template parser is behaving badly, please file an issue at https://github.com/golang/go/issues/

For other questions, see http://discuss.gohugo.io/
