### ISSUE TITLE
Add treat-warnings-as-errors option

### ISSUE THREAD

**Issue by zeisss** [spf13/hugo#2086]
Hey,

just started adding CI/CD to my hugo site and accidentially deployed an empty page because I had a typo in my templates which only triggered a warning but resulted in missing headers.

It would be nice to have a flag to treat those template warnings as errors, so I get a != 0 exitcode.

**Comment by bep** [comment]
Are they WARNING or ERRORs? Because the current Hugo 0.16-DEV (source builds) exits with -1 on all ERRORS and other fatal situations.

**Comment by zeisss** [comment]
Mh, you are right, they were ERRORs.

```
ERROR: 2016/04/15 template: theme/partials/footer.html:2: unexpected bad character U+00A0 in command
ERROR: 2016/04/15 template: theme/partials/header.html:8: unrecognized character in action: U+00A0
ERROR: 2016/04/15 html/template: "theme/partials/header.html" is an incomplete template in theme/partials/header.html
ERROR: 2016/04/15 html/template: "theme/partials/footer.html" is an incomplete template in theme/partials/footer.html
ERROR: 2016/04/15 html/template: "theme/partials/header.html" is an incomplete template in theme/partials/header.html
ERROR: 2016/04/15 html/template: "theme/partials/footer.html" is an incomplete template in theme/partials/footer.html
ERROR: 2016/04/15 html/template: "theme/partials/header.html" is an incomplete template in theme/partials/header.html
ERROR: 2016/04/15 html/template: "theme/partials/footer.html" is an incomplete template in theme/partials/footer.html
ERROR: 2016/04/15 html/template: "theme/partials/header.html" is an incomplete template in theme/partials/header.html
ERROR: 2016/04/15 html/template: "theme/partials/footer.html" is an incomplete template in theme/partials/footer.html
1 of 1 draft rendered
0 future content
1 pages created
0 paginator pages created
0 tags created
0 categories created
in 7 ms
```

Weird though that [the build](https://app.wercker.com/#zeisss/moinz.de-blog/build/5711663320f9eb2b63001b85?step=57116636b9c026000142ad39) didn't fail. The hugo is executed in the CI step with `eval` though. Maybe the exitcode got lost there somewhere or this was fixed in master already. Closing then.

**Comment by bep** [comment]
Yes, this is fixed recently.

**Comment by zeisss** [comment]
thx for the quick replies!
