### ISSUE TITLE
Switch to a more up to date TOML library

### ISSUE THREAD

**Issue by spf13** [spf13/hugo#2089]
https://github.com/pelletier/go-toml seems like a good candidate.

**Comment by pelletier** [comment]
Maintainer of https://github.com/pelletier/go-toml here. Let me know if there is anything I can do to help!

**Comment by mohae** [comment]
It appears that https://github.com/pelletier/go-toml only does parsing.  Encoding would be needed too.

**Comment by bep** [comment]
Not sure what you refer to by encoding, but in the latest revision, you can get a "map of plain Go objects", which is what we need.

If it is more "up to date" (whatever that means; I'm guessing supporting more of the TOML spec and not more up to date in tech fashion, although there have been some fishy stuff in what we use now; an os.Exit on error being one I remember).

**Comment by bep** [comment]
Or: Do we ever *write* TOML?

**Comment by mohae** [comment]
https://github.com/spf13/hugo/blob/master/parser/frontmatter.go#L32

**Comment by pelletier** [comment]
@mohae go-toml does serialize back to a string, see https://godoc.org/github.com/pelletier/go-toml#TomlTree.ToString

**Comment by mohae** [comment]
@pelletier thanks for the info!  I missed that.
