### ISSUE TITLE
Support reading config vars from ENV

### ISSUE THREAD

**Issue by nicdoye** [spf13/hugo#2090]
In addition to `--baseurl`, I'd like to be able to pass the site title. Other people may have use cases for other options that are normally set in `config.toml` etc.

Is this a worthy enhancement?

Command line arguments appear to be set in `[initHugoBuildCommonFlags()]` in [commands/hugo.go](https://github.com/spf13/hugo/blob/master/commands/hugo.go#L214) but I can't see immediately where they're merged with the config contents.

An alternative would be to use environment variables, but I don't think Hugo uses them at all.

_Note: In Jekyll, I currently do this by abusing `ENV['JEKYLL_ENV']` and using `{{jekyll.environment}}` (there may be a "correct" way, but I don't know it)._

**Comment by bep** [comment]
>An alternative would be to use environment variables, but I don't think Hugo uses them at all.

I'm pretty sure you can set config vars from environment vars. See https://github.com/spf13/viper  ... if it doesn't work, Viper is the correct repo to report issues about it. 

We will not create flags for all the config.

**Comment by nicdoye** [comment]
Thank you. Apologies for not having looked at viper to work it out.

**Comment by bep** [comment]
No problem - and don't hesitate to revisit this issue if you don't get it working.

**Comment by nicdoye** [comment]
I don't _think_ environment variables are currently set up in hugo. Testing `$BASEURL` (as an example, because it's already accepted by `--baseurl`) doesn't work.

Adding a quick hack of
```
snagglepuss:~ nic$ diff -bu GitHub/hugo/commands/hugo.go Go/src/github.com/spf13/hugo/commands/hugo.go
--- GitHub/hugo/commands/hugo.go	2016-04-18 15:36:28.000000000 +0100
+++ Go/src/github.com/spf13/hugo/commands/hugo.go	2016-04-18 15:27:24.000000000 +0100
@@ -334,6 +334,8 @@
 	}

 	viper.RegisterAlias("indexes", "taxonomies")
+        viper.SetEnvPrefix("hugo")
+        viper.AutomaticEnv()

 	loadDefaultSettings()
```
Allows me to run

```shell
HUGO_TITLE='Example Title' HUGO_BASEURL='http://example.com' /Users/nic/Go/src/github.com/spf13/hugo/hugo
```

Obviously:

- the `SetEnvPrefix()` wasn't necessary; 
- the two lines may not be in the right place; 
- `AutomaticEnv()` may not be exactly the right thing should you wish to enable environment variables;
- you may still not want to enable environment variables.

**Comment by bep** [comment]
OK, I calling `AutomaticEnv()` works ... but Hugo has a lot of very generic variable names, so without any namespace this will get confusing. Will have to think about this. @spf13 might chime in with an idea.

**Comment by bep** [comment]
Never mind, I misunderstood the prefix feature. That solves it. Will fix.
