### ISSUE TITLE
Permalink behaving unexpectedly with subdomain

### ISSUE THREAD

**Issue by taywhited** [spf13/hugo#2096]
Expected
http://subdomain.domain.com/ => Click link => http://subdomain.domain.com/privacy

Actual
http://subdomain.domain.com/ => Click link => http://subdomain.domain.com/subdomain/privacy

config.toml
```
baseurl = "http://subdomain.domain.com/"
...
[permalinks]
  singlets = "/:slug/"
...
[[params.footer.quicklinks]]
	text = "Privacy Policy"
	link = "privacy"
```

themes/theme/layouts/partials/footer.html
```
<li><a href="{{ .link | absURL }}">{{ .text  | markdownify }}</a></li>
```

content/singlets/privacy.md
```
+++
title = "Privacy Policy"
date = "2016-03-11"
slug = "privacy"
type = "singlets"
layout = "privacy"
+++
```

public/index.html
```
<li><a href="http://subdomain.domain.com/privacy">Privacy Policy</a></li>
```

public/.htaccess
```
Contains only Auth restrictions
```

Tested after deployed. The page can be accessed fine by going directly to http://subdomain.domain.com/privacy, but goes to http://subdomain.domain.com/subdomain/privacy when accessing the link from index.html. Also tested by hardcoding a non-permalink, non-existent page and it acted as expected:

http://subdomain.domain.com/ => Click link => http://subdomain.domain.com/test

themes/theme/layouts/partials/footer.html
```
<li><a href="{{ "test" | absURL }}">{{ .text  | markdownify }}</a></li>
```

Any advice would be much appreciated.

**Comment by bappamungkas** [comment]
i think it's about the url rewrite config of your subdomain.

edit or create `.htaccess` file at the same level of your subdomain folder and put this. 

```
RewriteEngine On
RewriteBase /

RewriteCond %{HTTP_HOST} ^subdomain.domain.com$
RewriteCond %{REQUEST_URI} !subdomainfolder/
RewriteRule (.*) /subdomainfolder/$1 [L]
```
change the `subdomain.domain.com` to your subdomain address
change the `subdomainfolder` to your subdomain folder name

**Comment by taywhited** [comment]
Turned out to be a server cache issue rather than a redirect. Thanks for the reply though!
