### ISSUE TITLE
Expected 'Z' in ISO8601 datetime, but found '+' instead.

### ISSUE THREAD

**Issue by red-trela** [spf13/hugo#2100]
According to the docs, this should be a valid date / frontmatter, I think:
```
+++
title = "Whatever"
date = 2013-03-27T16:36:00+01:00
categories = [ "this", "that" ]
+++
````

However, hugo complains about the date format:
`Error:Near line 3 (last key parsed 'date'): Expected 'Z' in ISO8601 datetime, but found '+' instead. for whatever.html`

Is something wrong with the hugo version I'm using? It's the Fedora 23 package from the COPR repo which looks recent.

**Comment by traveller42** [comment]
That is the correct ISO 8601 format when providing timezone offset

**Comment by bep** [comment]
What is the output of `hugo version"`?

**Comment by bep** [comment]
Also, as a workaround, you can try to put the date inside quotes.

**Comment by bep** [comment]
Yes, this has been fixed in the latest Hugo. Please update or use my workaround for now.

**Comment by traveller42** [comment]
Thanks.

I was reviewing Issues and thought that looked containable.  Since it is fixed, I will remove it from the list I had to address.
