### ISSUE TITLE
Test: Do some manual testing of the watch/live reload

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2101]
I have some nagging feeling that there is still are some glitches with the live reload / watch / rebuild. I have some weird encounters when it doesn't work, but when I restart the server ... it starts to work.

I will keep this as a placeholder for some testing that needs to be done before 0.16. 

**I'm on OS X. Would be great if others could chime in with their experiences.**

A test scenario I think would cover most bases would be:

Start `hugo server`on a site:

- [ ] Edit an image or CSS in /static and verify that it's loaded OK.
- [ ] Edit a md file in /content and ...
- [ ] Add a new image to /static 
- [ ] Add a new md file to /content
- [ ] Remove an image from /static 
- [ ] Remove a md file from /content
- [ ] Edit a layout file 
- [ ] Edit a shortcode and verify that pages gets updated

Start `hugo server --renderToDisk` on a site:

- [ ] Edit an image or CSS in /static and verify that it's loaded OK.
- [ ] Edit a md file in /content and ...
- [ ] Add a new image to /static 
- [ ] Add a new md file to /content
- [ ] Remove an image from /static 
- [ ] Remove a md file from /content
- [ ] Edit a layout file 
- [ ] Edit a shortcode and verify that pages gets updated

**If you perform the test above, please make sure you test with a Hugo built from the latest source and report back what OS/platform you tested on.**

**Comment by digitalcraftsman** [comment]
Operating system: Ubuntu 15.10

Start `hugo server` on a site:

- [ ] Edit an image or CSS in /static and verify that it's loaded OK.
- [ ] Edit a md file in /content and ...
- [ ] Add a new image to /static 
- [ ] Add a new md file to /content
- [ ] Remove an image from /static 
- [ ] Remove a md file from /content
- [ ] Edit a layout file 
- [ ] Edit a shortcode and verify that pages gets updated

Start `hugo server --renderToDisk` on a site:

- [ ] Edit an image or CSS in /static and verify that it's loaded OK.
- [ ] Edit a md file in /content and ...
- [ ] Add a new image to /static 
- [ ] Add a new md file to /content
- [ ] Remove an image from /static 
- [ ] Remove a md file from /content
- [ ] Edit a layout file 
- [ ] Edit a shortcode and verify that pages gets updated

**Comment by rdwatters** [comment]
FWIW, I find about half the time I run Hugo server, the livereload doesn't work when I update my SASS files. 

I should note that this is not *just* a matter of the watch on the static folder, since my gulp assets actually write the minified CSS to an HTML partial I include in my <head> for the sake of critical render path in addition to writing to a style.min.css file I keep in the static folder.

**Comment by digitalcraftsman** [comment]
Operating system: Windows 8.1

Start `hugo server`on a site:

- [ ] Edit an image or CSS in /static and verify that it's loaded OK.
- [ ] Edit a md file in /content and ...
- [ ] Add a new image to /static 
- [ ] Add a new md file to /content
- [ ] Remove an image from /static 
- [ ] Remove a md file from /content
- [ ] Edit a layout file 
- [ ] Edit a shortcode and verify that pages gets updated

Start `hugo server --renderToDisk` on a site:

- [ ] Edit an image or CSS in /static and verify that it's loaded OK.
- [ ] Edit a md file in /content and ...
- [ ] Add a new image to /static 
- [ ] Add a new md file to /content
- [ ] Remove an image from /static 
- [ ] Remove a md file from /content
- [ ] Edit a layout file 
- [ ] Edit a shortcode and verify that pages gets updated

**Comment by bep** [comment]
On my OS X with Byword as Markdown editor:


Start `hugo server`on a site:

- [x] Edit an image or CSS in /static and verify that it's loaded OK.
- [ ] Edit a md file in /content and ... **FAILED**
- [x] Add a new image to /static 
- [x] Add a new md file to /content
- [x] Remove an image from /static 
- [x] Remove a md file from /content
- [x] Edit a layout file 
- [x] Edit a shortcode and verify that pages gets updated

Start `hugo server --renderToDisk` on a site:

- [x] Edit an image or CSS in /static and verify that it's loaded OK.
- [] Edit a md file in /content and ... **FAILED**
- [x] Add a new image to /static 
- [x] Add a new md file to /content
- [x] Remove an image from /static 
- [x] Remove a md file from /content
- [x] Edit a layout file 
- [x] Edit a shortcode and verify that pages gets updated

The content file issue is editor specific, it seems. I'll create an issue for that.
