### ISSUE TITLE
CSS fails to load or reload from hugo server

### ISSUE THREAD

**Issue by battlmonstr** [spf13/hugo#2104]
CSS fails to load via the hugo server.

Steps to reproduce:
1. Create a simple hugo site with a linked CSS file and some simple rules (like `BODY { color: red; }` ).
1. Run "hugo server".
2. Open site on http://localhost:1313/

expected: rules applied from the CSS file
actual: default style as without any CSS

Happens in Chrome 50 and Firefox 45 on Windows 7.
Hugo version: 0.15.
There was no problem on Mac.

Investigation:
Chrome debugging tools show that the CSS is served with "304 Not Modified" status and "plain/text" content type.
This can be tested with a command like:
`wget -S localhost:1313/style.css --header="If-Modified-Since:Sat, 23 Apr 2016 14:09:13 GMT"`
This is what hugo server sends in response:

    HTTP/1.0 304 Not Modified
    Date: Sat, 23 Apr 2016 15:46:28 GMT

Only 1 header. Content-Type is missing.

In fact the content type is always wrong, because this command:
`wget -S localhost:1313/style.css`
Returns the following header:
`Content-Type: text/plain; charset=utf-8`

Some possibly related stuff:
https://bugs.chromium.org/p/chromium/issues/detail?id=246875
http://blog.extramaster.net/2013/05/resolving-304-not-modified-google.html

**Comment by bep** [comment]
What Hugo version? (`hugo version`)

**Comment by battlmonstr** [comment]
0.15 stable, it's written in the description.

**Comment by tischda** [comment]
Could be related to this issue in afero: https://github.com/spf13/afero/issues/86

**Comment by bep** [comment]
>Could be related to this issue in afero: spf13/afero#86

I'm pretty sure that copyOnWrite FS arrived after Hugo 0.15, but that looks like a valid issue, too.

**Comment by battlmonstr** [comment]
This is a piece of "go" functionality that is needed:
https://github.com/golang/go/commit/ac17fd4cd2daba25471c07d25d618171e905fd2d

**Comment by battlmonstr** [comment]
A quick fix would be to wrap around FileServer, and call `w.Header().Set("Content-Type", "whatever")` before calling the native ServeHTTP.

**Comment by battlmonstr** [comment]
Nice, thanks. That was easy.
I'll be waiting for 0.16...

**Comment by moorereason** [comment]
@bep, I've removed 2b02a402a05b637ca9c0af4a86525d299c387daa and tested on Windows 7, and the content type is correct.  The `mime` package loads the default MIME types (from `mime/types.go`) and then loads all of the MIME types from the Windows Registry.  I'm assuming his registry is wrong.

@battlmonstr, can you tell us what you have in your registry for `HKEY_CLASSES_ROOT\.css\Content Type`?  I'm betting that your system has `text/plain` instead of `text/css`.

**Comment by battlmonstr** [comment]
It is text/plain.
