### ISSUE TITLE
Feature to have pagination stay within a section

### ISSUE THREAD

**Issue by abh** [spf13/hugo#211]
I am using this in my "posts" template (yes, I think next/previous are backwards :-) )

        <ul class="pager">
          {{if .Next}}
            <li><a class="previous" href="{{.Next.Permalink}}">← {{.Next.Title}} </a></li>
          {{end}}
          {{if .Prev}}
            <li><a class="next" href="{{.Prev.Permalink}}">{{.Prev.Title}} →</a></li>
          {{end}}
        </ul>

I didn't expect it to include pages from outside the current section, but looking at the code I see there's just a concept of one list of pages.

It'd be nice with a way to have .Next and .Prev only iterate on items in the current section (I realize the follow-up question from someone else might be "in the current category" or other meta-data).

(I posted this [on the mailing list](https://groups.google.com/forum/#!topic/hugo-discuss/t4DsQ-VLQ0Y) earlier but I think it's more appropriate here now that I know better how the code works).

**Comment by bjornerik** [comment]
This is solved in more than one way.

**Comment by bryfry** [comment]
What are the ways! 

https://xkcd.com/979/

**Comment by moorereason** [comment]
@bryfry,
Please use the discussion forums for this kind of request in the future.

You want `.NextInSection` and `.PrevInSection` from https://gohugo.io/templates/variables/.

**Comment by bryfry** [comment]
Sorry, posted in humor and frustration.  Thanks for the link.
