### ISSUE TITLE
Future Posts dont work.

### ISSUE THREAD

**Issue by noqqe** [spf13/hugo#2111]
I created a post with a date in the future. So it does not get published yet. 
When I build hugo, it gets parsed and published as every other post.

Am I doing it wrong?

```
0 draft content
0 future content
8 pages created
0 non-page files copied
1 paginator pages created
0 tags created
in 67 ms
``` 

So 0 future content posts. In the help page, its only shown that when I do `-F` I can *include* build future posts. I cannot find a flag for excluding them. So I guess its by default.

**Comment by christophberger** [comment]
In the risk of asking the obivious - but have you ruled out simple issues already, like a typo in the name or the value of the publishdate attribute? This could prevent Hugo from properly parsing or even recognizing the publishing date.

**Comment by mohae** [comment]
If the publish date is > than Now it is considered a future post, otherwise it is published.

For more help, please provide the frontmatter of the post in question.

**Comment by rdwatters** [comment]
How about your config.toml as well? Again, this is trying to rule out the more obvious issues. Do you have the buildFuture variable in there as well or just running the server with the flag?

**Comment by noqqe** [comment]
Here is my usecase. 

<img width="495" alt="screenshot 2016-05-06 13 29 34" src="https://cloud.githubusercontent.com/assets/203902/15071812/d1555a54-138e-11e6-9c29-280bfbc5053a.png">

What am I doing wrong? I created the post using 

```
$ hugo new post/foo.md
```

Version:

```
$ hugo version
Hugo Static Site Generator v0.16-DEV BuildDate: 2016-04-24T18:21:23+02:00
```

**Comment by christophberger** [comment]
There is an extra variable `publishdate` available for specifying the publishing date:

    publishdate: 2016-05-09T13:25:11+02:00

The `date` variable is only used for sorting the content. (See Content > Front Matter > [Variables](https://gohugo.io/content/front-matter/#variables) in the Hugo docs.)

**Comment by noqqe** [comment]
@christophberger ohhh. All my fault. I understand. Everythings alright then :)
