### ISSUE TITLE
How do you reference a variable declared in a pages front matter?

### ISSUE THREAD

**Issue by EdgarAllenPoe** [spf13/hugo#2127]
The link to this page said issues and _help_, and I need a bit of help.

File /themes/simple/archtype/post.md contains the following:
```
+++
author="Bill Smith"
+++
```
File /themes/simple/layouts/partials/blogpost.html contains the following:
```
{{ range first 10 .Data.Pages }}
{{ if eq .Type "post"}}
<div class="blog-post">
<h3><a href="{{ .RelPermalink }}">{{ .Title }}</a> <small>{{ .Date.Format "1/2/2006" }}</small></h3>
	<img class="thumbnail" src="{{ .Site.BaseURL }}img/850x350.png">
	{{ .Summary}}
				{{ if .Truncated }}
			<div class="read-more-link">
				<p><a href="{{ .RelPermalink }}">Read More…</a></p>
			</div>
			{{ end }}
	<div class="callout">
		<ul class="menu simple">
			<li><a href="#">Author: {{.author}}</a></li>
			<li><a href="#">Comments: 3</a></li>
		</ul>
	</div>
</div>
{{ end }}
{{ end }}
```
When `hugo new post/test-post.md` is executed and then hugo serve

After adding a little content post.md looks like this
```
+++
author = "Bill Smith"
date = "2016-05-06T22:13:55-04:00"
title = "test post"

+++

Here is a little content

```

but hugo produces this error:
`ERROR: 2016/05/06 template: theme/partials/blogpost.html:19:29: executing "theme/partials/blogpost.html" at <.author>: author is not a field of struct type *hugolib.Page in theme/partials/blogpost.html
`

and html that looks like this:
```
...
<div class="callout">
		<ul class="menu simple">
			<li><a href="#">Author: 
		</div>
				<div class="medium-3 columns" data-sticky-container>
...
```

How do I declare and reference the variable "author" correctly under these circumstances?

**Comment by heavywatal** [comment]
> Any other value defined in the front matter, including taxonomies, will be made available under `.Params`

https://gohugo.io/templates/variables/#page-params

**Comment by digitalcraftsman** [comment]
@EdgarAllenPoe  Please ask questions like these on the [Hugo forum](https://discuss.gohugo.io/); GitHub is used for concrete issues and requests/enhancements.

**Comment by EdgarAllenPoe** [comment]
Thank you, and sorry about the mis-post
