### ISSUE TITLE
watch should ignore .DS_Store

### ISSUE THREAD

**Issue by thepian** [spf13/hugo#2128]
When browsing the site source the browser gets updated a lot. I'm guessing it is because .DS_Store is updated and watch triggers a page reload. If that's the case might it be an idea to support a watch exclude list supporting file globs

**Comment by bep** [comment]
It is https://github.com/spf13/hugo/blob/b5030782ae5e6cda3aa7a7dd9fb8ffa4f2d16a32/commands/hugo.go#L748

I think you must experience "something else"

As to your other question; we have a ignoreFile config option for /content -- and there is an open issue about doing the same for /static.

**Comment by thepian** [comment]
could it be .git (wouldn't have thought so as it is two levels up). I'm starting to speculate if the Tower git app is triggering something, just navigating the git changes triggers a site rebuild.
