### ISSUE TITLE
Man Page

### ISSUE THREAD

**Issue by robmuh** [spf13/hugo#2133]
Optional convenience for sure, but when installing onto a Linux or Mac having a `man hugo` page would be nice.

**Comment by bep** [comment]
I'm pretty sure you get that if you do `apt-get install hugo` on Ubuntu.

Also see:

```
hugo gen -h
```

**Comment by robmuh** [comment]
![screen shot 2016-05-08 at 7 25 22 am](https://cloud.githubusercontent.com/assets/3749067/15097594/10e2b24c-14ee-11e6-9a31-ea2999f722e4.png)

**Comment by anthonyfok** [comment]
Hi @robmuh, you may now visit https://github.com/spf13/hugo/releases/tag/v0.16 and download https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16-1_amd64.deb (Assuming you are running on amd64 architecture.)
