### ISSUE TITLE
how to set the img size in the markdown?

### ISSUE THREAD

**Issue by sd886393** [spf13/hugo#2139]
I use this code in my raw markdown post like 
"![]("https://upload.wikimedia.org/math/c/a/e/caec49086f2faf102df7972d0dcde54b.png")"
but this image display like the attach file,and i don't know how to fix it , thanks for your attention!
![qq 20160512203248](https://cloud.githubusercontent.com/assets/7655877/15214633/b4a146d8-1880-11e6-9848-2d60c7738255.png)

**Comment by bep** [comment]
Ask questions at http://discuss.gohugo.io/
