### ISSUE TITLE
generate content from json

### ISSUE THREAD

**Issue by tomdavidson** [spf13/hugo#2140]
Hello, a project I am working on produces content in json. Most of it is structured and some elements have a type "markdown" with formatted text. I understand the ability to getJSON in my template, but for this project I would rather generate and ship html. What is the best way for hugo to generate a static site from json files?

 Here is an gist [example of the content](https://gist.github.com/tomdavidson/1316d1024cc0e56cdc73434f1ed3c533).

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions.
