### ISSUE TITLE
AbsURL tests

### ISSUE THREAD

**Issue by amitsaha** [spf13/hugo#2147]
I came across this test of the absolute URL function (in `helpers/url_test.go`):

```
{"/test/2/foo/", "http://base/path", "http://base/test/2/foo/"},
```

Shouldn't the right result be http://base/path/test/2/foo ?

**Comment by bep** [comment]
Why?

**Comment by amitsaha** [comment]
What do you mean "why"? If my blog is hosted at "http://example.com/mysite", I want the CSS path to be "http://example.com/mysite/css/style.css" and not "http://example.com/css/style.css".

**Comment by bep** [comment]
"/test/2/foo/" is an URL that is relative to the server root.
"test/2/foo/" is an URL that is relative to the context root.

The tests are correct, and there is no problem creating CSS paths as in your examples.

**Comment by amitsaha** [comment]
I suspect it's an issue with the theme I was using, let's see: https://github.com/zyro/hyde-x/issues/67
