### ISSUE TITLE
Custom Template Functions without Compiling

### ISSUE THREAD

**Issue by justinoverton** [spf13/hugo#2148]
I'm new to Hugo and Go, and I think I can implement this if it's something the Hugo community would be interested in.
1. Take a JavaScript engine like this: https://github.com/robertkrimen/otto
2. Create a Template function for loading a javascript file into the Otto VM. This file would have custom functions that are available in templates.
3. Create a template function to execute the javascript... {{ ExecJs 'functionName' ....args... }}

Or something along those lines.

**Comment by bep** [comment]
1. Can you supply a concrete example of a very useful template function that cannot be handled by the current built-ins?
2. Spinning up a JavaScript VM sounds sub-optimal. It should be pretty straight forward to dynamically compile Go template funcs, but it would add complexity and should only be done if someone comes up with really, really good answers to 1)

**Comment by justinoverton** [comment]
Right now my use-case is that I want a rand() function. I also am thinking of a not-quite-random hash based function for the same thing.

Let's say I have a nice tile-layout for grid display of images and content. Let's say that I don't want to have to specify a bunch of layout parameters in each md file, unless I don't like the default. Let the default be "random" where "random" is really just based on a hash of the permalink.

Example layout:
```html
        <div class="tile-area no-padding">
            <div class="tile-container bg-darkCobalt" style="width: 640px">
                <div class="tile-large bg-lighterBlue" data-role="tile"></div>
                <div class="tile-square bg-cobalt" data-role="tile"></div>
                <div class="tile-small bg-red" data-role="tile"></div>
                <div class="tile-small bg-orange" data-role="tile"></div>
                <div class="tile-small bg-green" data-role="tile"></div>
                <div class="tile-small bg-pink" data-role="tile"></div>
                <div class="tile-wide bg-lightGreen" data-role="tile"></div>
            </div>
        </div>
```
Looks something like this:
![image](https://cloud.githubusercontent.com/assets/3522194/15270081/e2ff4300-19d8-11e6-8d92-df000f88dbab.png)

Now unless some of those sizes and colors (color could be replaced with an image) are specified in the content's markdown file.... let's come up with a default that gives a "random" but stable layout.

I've got something like this in javascript (untested, but you get the idea)

```javascript
function hashedIndex(items, hashBits){
    
    var targetBits = items.toString(2).length;
    
    var idx = parseInt(hashBits.splice(0, targetBits).join('')) % items.length;
    
    return idx;
};
```

So if I have an array of classes ['tile-small', 'tile-wide','tile-large'] I could do as follows.
1. Get hash of permalink (or other content identifier) as a bit array
2. use hashedIndex for each "random" class needed

I could do this all client-side after rendering, but since I'm generating a static site anyway.... why not do it a compile time?

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
