### ISSUE TITLE
Improve error feedback in case of 404

### ISSUE THREAD

**Issue by stephanwesten** [spf13/hugo#2149]
Hi,

I'm trying out Hugo. The Hugo Quickstart Guide is okay. I got that working. 

Now i'm moving to the next phase; trying out themes from the Showcase gallery. I added a theme (hugo freelance theme in this case) following the instructions and when I visit the local site i get a 404.

I've no clue where to look. It has to be an error related to theme, because that is the only thing i've changed.

I looked up the Debugging documentation. This does not help, too detailed for now. I would not know which file i've to extend.

I restored the config.toml to the original file (thanks to time machine) and this seems to fix the problem.

What I probably did wrong is that i visited the url of as specified in the original config.toml. When you are new you need more feedback to put you in this direction.  It would be nice to have some feedback in the console (shell) about a mismatch between the requested url and what is allowed/expected. 

thanks,

Stephan

**Comment by bep** [comment]
404 is what it is, and there are millions of reasons behind it. As Hugo is a static site generator, the error code is provided by your web server, and even the web server cannot give you better answers.

I'm closing this, as this isn't possible. To get help with debugging, try the Hugo discussion site.

**Comment by stephanwesten** [comment]
Well, since i'm running 'Hugo server' on the cmd line, I assume it is possible to provide feedback during _local development_. I mean, the server is also watching for changes, so there is some sugaring going on.

Perhaps your argument is that it is not worth the trouble, that could be the case.

i'm fine closing this issue.
