### ISSUE TITLE
Changes in Toml not always picked up

### ISSUE THREAD

**Issue by stephanwesten** [spf13/hugo#2152]
Hi,

I think i've run into a bug when changing the key in a config.toml file.

Reproduction steps:
Suppose i have the following content in the config.toml file:

```
    [params.header]
        image = "profile.png"
        name = "todo change name"
```

I run Hugo server from the cmd line. If I make a change in the config.toml file by changing the value of the key 'name' then the preview shows the new, updated value in the browser after save. Everything is fine.

Now suppose I do not like the key 'name', so I change it into 'description' and I do the same in the html (partial) file and save both files. Now I expect the change to be reflected in the preview. However this is this not the case. If I restart hugo from the cmd line, the change is shown.

Restarting the server is cumbersome and should not be necessary for this particular kind of change.

Version:
```
$ hugo version
Hugo Static Site Generator v0.15 BuildDate: 2015-11-26T07:29:07+01:00
```

I'm new to Hugo, so apologies if i'm making wrong assumptions here.

thank you, 

Stephan

**Comment by bep** [comment]
Thanks for the report. This is fixed in the upcoming Hugo 0.16.
