### ISSUE TITLE
Proposal: Automatic detection of exampleSite folders in theme

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2157]
Many themes have their own `exampleSite` folder to show the intended usage of a theme, including specially prepared content files, example config file etc. While checking out a theme it's often required to copy these files manually in the first place. 

Therefore, we could add a command line flag that looks for an `exampleSite` folder in a theme and uses its content to serve a webpage.

This would be possible since the `exampleSite` folder is a stand-alone Hugo website (by mirroring the root directory of such a website). The actual setup of the user, especially the content files and the config file in the root folder would remain untouched.

```
hugo server --useExampleSite
```

would have the following effect on this example folder structure:

```
content/   <-- remains untouched
    posts/
        foo.md
...
config.toml  <-- ignore this config file
themes/
    someTheme/
        ...
        exampleSite/ <-- serve this Hugo website
           content/
               posts/
                    example-post.md  <-- use this content
           ...
           config.toml  <-- use this configuration instead
```

It would also be required if we want to introduce a quickstart command (see #505). The quickstart site would be a theme with it's own "exampleSite" (folder).

**Comment by bep** [comment]
Where do you go from the example site setup to your own version of it?

**Comment by digitalcraftsman** [comment]
Do you thought about some type of importer that copies the files from the example site setup the actual one?

**Comment by bep** [comment]
I'm just asking ... If a user wants to browse themes, I think it is better to do that on themes.gohugo.io ... I could imagine that he/she would like to use the exampleSite as a starting point. I don't see your suggestion taking him/her there. This should also be seen in relation to the issue about "themes should be able to set default param values" or something.

**Comment by digitalcraftsman** [comment]
> I could imagine that he/she would like to use the exampleSite as a starting point. I don't see your suggestion taking him/her there. 

I thought about an importer first. My approach would be to let the user which user he wants to copy from the exampleSite folder. This should "take him/her there". Something like

```
$ hugo import exampleSite
Please confirm with "y" what you would like to use in your website. 

Do you want to copy the config file?
y
Do you like to copy the content folder?
Do you want to copy the data folder?
...
```

If we use this approach we need to handle name collisions of filenames.

Currently, I'm playing around with my approach for the quickstart site (see #505). Would you rather load a while Hugo website instead of a theme +  exampleSite?

> This should also be seen in relation to the issue about "themes should be able to set default param values" or something.

Isn't the `default` template function a problem solver in this case?

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by digitalcraftsman** [comment]
Adding `themesDir = "../.."` in the example config file make the `exampleSite` folder a stand-alone Hugo site. So an extra command line flag isn't neccessary.
