### ISSUE TITLE
disqus using folder for post reference

### ISSUE THREAD

**Issue by mubix** [spf13/hugo#2162]
I'm at a loss. I'm using hugo w/ Blackburn. I have disqus, and I'm using a folder structure to keep my posts sorted. Folder structure looks a bit like this:
```
.
content
--> post
     --> 2005
(.....)
     --> 2016
           -> 05-23-Blogpost.markdown
```

And for some reason Disqus is only seeing https://myblog/2016/   for the post and comments. Am I not supposed to use folders inside of the post folder? is something in the Blackburn theme making Disqus URL point somewhere it shouldn't?

I have tried setting the following as Diqus suggests:
```
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
```

By modifying the partial in Blackburn (disqus.html) to look like this:

```
        this.page.url = '{{ $.BaseURL }}';
        this.page.identifier = '{{ $.RelPermalink }}';
```
and still no luck, not sure what I'm doing wrong, if it's using folders in the "post" directory I really need some better way because I have too many posts to have them all in one folder.

**Comment by mubix** [comment]
Also, for some reason it's escaping the information on the live site:

```
        this.page.url = '\/\/myblog.com\/';
        this.page.identifier = '\/post\/2016\/05-23-Blogpost\/';
```

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions / troubleshooting.

**Comment by mubix** [comment]
Will do, sorry, thanks

**Comment by mubix** [comment]
@bep never got a response - https://discuss.gohugo.io/t/disqus-using-folder-for-post-reference/3384

**Comment by mubix** [comment]
Code is here: https://github.com/mubix/mubix.github

**Comment by fiunchinho** [comment]
Facing the same issue with Hugo and Disqus
