### ISSUE TITLE
Custom parameters in Menus

### ISSUE THREAD

**Issue by rafgeekee** [spf13/hugo#2163]
In my current project I'm required to add additional description text alonside menu links. I can't seem to find a way of adding custom params into Menus or workaround without losing the benefits of using menu objects (children and parents).

Is there a workaround or anything in the pipeline to add custom params?

**Comment by bep** [comment]
You have the Pre and Post parameters you could use. Other than that, please use http://discuss.gohugo.io/ for questions.
