### ISSUE TITLE
"hugo server" does not work on my Windows 10 machine.

### ISSUE THREAD

**Issue by j-k** [spf13/hugo#2164]
"hugo server" does not work on my Windows 10 machine.
hugo version: v0.15
Log: [log.txt](https://github.com/spf13/hugo/files/278661/log.txt)

**Comment by bep** [comment]
This is a known issue -- workaround: `hugo server --renderToDisk`

**Comment by j-k** [comment]
Oh, ok. Sorry. I didn't find it in the issues list.
Am 24.05.2016 17:59 schrieb "Bjørn Erik Pedersen" <notifications@github.com

**Comment by bep** [comment]
It is fixed in the source version, btw.
