### ISSUE TITLE
spurious warnings for section rendering

### ISSUE THREAD

**Issue by SvenDowideit** [spf13/hugo#2169]
we have an `index.md` file for each of these sections, and expect the normal `_default/single.html` to be used to render it. This is what happens, but `hugo` complains with an warning saying that it is rendering empty.

```
...
WARN: 2016/05/26 20:51:07 site.go:1974: "" is rendered empty
WARN: 2016/05/26 20:51:07 site.go:1998: Unable to locate layout for section test: [section/test.html _default/section.html _default/list.html indexes/test.html _default/indexes.html theme/section/test.html theme/_default/section.html theme/_default/list.html theme/indexes/test.html theme/_default/indexes.html theme/section/test.html theme/_default/section.html theme/_default/list.html theme/indexes/test.html theme/_default/indexes.html theme/theme/section/test.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/test.html theme/theme/_default/indexes.html]
WARN: 2016/05/26 20:51:07 site.go:1974: "test" is rendered empty
WARN: 2016/05/26 20:51:07 site.go:1998: Unable to locate layout for section nomenu: [section/nomenu.html _default/section.html _default/list.html indexes/nomenu.html _default/indexes.html theme/section/nomenu.html theme/_default/section.html theme/_default/list.html theme/indexes/nomenu.html theme/_default/indexes.html theme/section/nomenu.html theme/_default/section.html theme/_default/list.html theme/indexes/nomenu.html theme/_default/indexes.html theme/theme/section/nomenu.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/nomenu.html theme/theme/_default/indexes.html]
WARN: 2016/05/26 20:51:07 site.go:1974: "nomenu" is rendered empty
```

**Comment by digitalcraftsman** [comment]
Could you share an `index.md` that reproduces the issue? Or perhaps the a link to the source?

This would help to trace the issue.

**Comment by SvenDowideit** [comment]
oh YES. ( I thought this would be harder)

checkout https://github.com/docker/docs-base

and if you have Docker installed, run `make docs`

otherwise, hugo is a go :)

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
