### ISSUE TITLE
Make canonical template paths more intuitive

### ISSUE THREAD

**Issue by dencold** [spf13/hugo#2170]
Adding an official issue to github, after consulting @spf13, @bep, and @moorereason on gitter (thanks for the initial dialog there everyone!)
### The Issue

I'm guessing that the majority of Hugo users define layouts via the `_default` path structure and likely have these three templates defined:
- `/layouts/_default/single.html`
- `/layouts/_default/list.html`
- `/layouts/index.html`

That works well if you are okay with all content in your static site getting the same layout everywhere, however, if you need to provide different layouts on a per-section basis, things get **much** trickier in Hugo. For example, say you have these three sections on your site:
- `/content/post`
- `/content/travel`
- `/content/quote`

For posts and quotes you are fine with the default templates defined above, but for the travel section, you want to have a special layout that puts extra emphasis on photographs. My intuition was to create the following:
- `/layouts/travel/single.html`
- `/layouts/travel/list.html`

Which would match the paths we've defined in `_default`, but **bzzzzzzzt**, I was WRONG. Hugo expects this config:
- `/layouts/travel/single.html`
- `/layouts/section/travel.html`

So, a single item of content uses `/layouts/travel/single.html` and when you are displaying a list, Hugo looks in `/layouts/section/travel.html`. I would **never** have guessed that and needed to spend a lot of time digging through the docs to figure this out. I probably spent an hour or two looking through all of the docs just looking for the definition of how Hugo decides what layouts to use. The pertinent docs are [here](https://gohugo.io/templates/content/) and [here](https://gohugo.io/templates/list/).

Single content precedence is defined as:

![image](https://cloud.githubusercontent.com/assets/1844771/15599849/014bbee4-239b-11e6-9633-816874f4dac4.png)

...and list content precendence is defined as:

![image](https://cloud.githubusercontent.com/assets/1844771/15599855/232d11a2-239b-11e6-8956-bddf3b0aeae9.png)

As you can see, there doesn't exist an entry for `/layouts/SECTION/list.html` in that precedence list.
### Proposal

I'd like to deprecate the current canonical location for section list content. Instead of `/layouts/section/travel.html`, we should define section list templates where we expect to find them, as a file called `list.html` under the appropriate section (in my example, travel). This has several benefits:
1. It matches how `_default` organizes its templates.
2. We keep section layouts contained to just one directory.
3. We can tell, just by looking at the file, that this is intended to display a list of content (/layouts/section/travel.html doesn't indicate anything, other than that it is for travel content)

Also, when I say "deprecate" I mean from **documentation**. Because of backwards-compatibility requirements, we should continue to accept the old configuration, but it should be lower in the precedence chain, and it shouldn't be mentioned in the documentation going forward.

Please let me know if the community agrees. I am willing to make the required changes to the Go code if we have enough interest. Thanks!

**Comment by bep** [comment]
I agree, but I'm not sure about the deprecation/documentation part. There are thousands of Hugo sites with this setup today, and people will get confused if their setup isn't in the documentation. They will have some totally unrelated problem, then look at the documentation and think, oh, maybe my template path is wrong?

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
