### ISSUE TITLE
Use variables in toml files from other toml files

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [spf13/hugo#2171]
Hi,

My goal is to build a multilingual site. For this I would like to:

* not touch the theme file
* have a config file which defines the overall structure for all languages (config.toml)
* have a "string" file for all languages

So for example, I would have a config.toml file like this:

```
	[params.navigation]
		brand = "out-website"

		[params.navigation.links]
			about     = $ABOUT_NAME
			services  = $SERVICES_NAME
			team      = $TEAM_NAME
			impressum = $IMPRESSUM_NAME
```

a english language file:

```
ABOUT_NAME=About
SERVICES_NAME=Services
TEAM_NAME=Team
IMPRESSUM_NAME=Impressum
```

and a german language file like this:

```
ABOUT_NAME=Über uns
SERVICES_NAME=Dienste
TEAM_NAME=Mitarbeiter
IMPRESSUM_NAME=Impressum
```

And then I want to compile the project for english:

```
hugo --theme=... --config=config.toml --config=english.toml
```

and german:

```
hugo --theme=... --config=config.toml --config=german.toml
```

Or in same way similar.

For this I need to use variables in the config.toml that are defined in english.toml or german.toml

Is this possible?
Tanks!

**Comment by bep** [comment]
For questions, please use http://discuss.gohugo.io/
