### ISSUE TITLE
Nested shortcodes get rendered as Markdown

### ISSUE THREAD

**Issue by mitchchn** [spf13/hugo#2173]
Version: Hugo Static Site Generator v0.16-DEV BuildDate: 2016-05-27T20:32:19+02:00.

My post has two shortcodes, one that is nested:

```
{{% wrapper %}}

## Some Markdown goes here.

This paragraph invokes a shortcode for retina images: {{< retina src="image.png" >}}

{{% /wrapper %}}
```

The issue is that `retina.html` is rendered as Markdown. Line breaks in the template code are treated as `<p>` tags, and other accidental Markdown syntax is parsed.

I get that the `%` sign means "render the insides as Markdown," but it shouldn't apply to internal shortcodes, which are HTML files and usually treated as such, even when they're invoked from Markdown content.

Otherwise, it's very difficult to mix Markdown and shortcodes inside another shortcode without running into formatting glitches.

**Comment by bep** [comment]
I don't have the implementation details in my head now, but if you say this is how it is, then this is by design. Your obvious workaround here is to not use markdown in the outer wrapper.

**Comment by bep** [comment]
OK, this was it:

https://github.com/spf13/hugo/issues/797

I guess it is hard to make everyone happy.

**Comment by mitchchn** [comment]
Could `<` and `%` perhaps be overloaded to determine this behaviour? If I have an internal `{{% shortcode %}}`, it would be passed through the Markdown renderer, but `{{< shortcode >}}` wouldn't.

It seems to me like that wouldn't conflict with the normal behaviour of those symbols. `<` would just be extended to mean "treat everything about this shortcode as HTML, always."

**Comment by bep** [comment]
>Could < and % perhaps be overloaded to determine this behaviour? 

No idea what you mean here, but the current definition of:

{{<: The Inner content will not be passed through the markdown (or whatever) rendering engine
{{%: The Inner content will be passed through the markdown (or whatever) rendering engine

This is how it behaves today. I understand what you want, but you haven't presented a solution to it, at least not one that I understand.

**Comment by mitchchn** [comment]
You're right. It doesn't make sense. I mixed up inner content (which this particular shortcode) doesn't have) with the HTML output of the shortcode itself.

It just goes to show that it's unintuitive for a shortcode to ever be rendered as anything but HTML. I do understand why you did it from your linked use case above. But I wish there were a way to avoid it.

**Comment by bep** [comment]
>But I wish there were a way to avoid it.

Me, too. And I will think about it. If you have any simple and good idea, please chime in.

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
