### ISSUE TITLE
Won't run on 32-bit debian 8.4

### ISSUE THREAD

**Issue by parlux** [spf13/hugo#2175]
I've tried installing both the debian package and the tarball, and both end with the same result. This is on debian 8.4, Linux version 2.6.32-042stab093.5, i686, installing hugo_0.15_i386.deb

```
$ hugo
Trace/breakpoint trap
```

Any thoughts what might be going on, or how I can get more debug info?

**Comment by anthonyfok** [comment]
> This is on debian 8.4, Linux version 2.6.32-042stab093.5

Wait a second, Debian 8.4 comes with Linux kernel 3.16.0.  Why are you using such an outdated kernel?  Are you using OpenVZ or something like that?  The ancient kernel version might be the culprit.

Anyhow, according to https://github.com/spf13/hugo/releases:

> ## Known Issues
> 
> Using the Hugo v0.15 32-bit Windows or ARM binary, running hugo server would crash or hang due to a memory alignment issue in Afero. The bug was discovered shortly after the v0.15.0 release and has since been fixed by @ tpng. If you encounter this bug, you may either compile Hugo v0.16-DEV from source, or use the following solution/workaround:
> 
> * 64-bit Windows users: Please use hugo_0.15_windows_amd64.zip (amd64 == x86-64). It is only the 32-bit hugo_0.15_windows_386.zip that crashes/hangs (see #1621 and #1628).
> * 32-bit Windows and ARM users: Please run `hugo server --renderToDisk` as a workaround until Hugo v0.16 is released (see “hugo server” returns runtime error on armhf and #1716).

Hmm... not quite the same, but it could affect your 32-bit v0.15 binary too.

I recommend that you:

1. Go to https://packages.debian.org/sid/hugo and download the official Debian Hugo package from your favorite mirror, e.g., http://ftp.us.debian.org/debian/pool/main/h/hugo/hugo_0.15+git20160427.545.0903886-1_i386.deb and install that.
    * Alternatively, compile Hugo from the latest source on the master branch.  (git clone)
    * Wait until next week for the v0.16 release.  :-)
2. Upgrade your Linux kernel!

**Comment by parlux** [comment]
Hi, yeah it's an old VPS using OpenVZ :(, (and 2.6.32 only reached end of life in Feb :p)

The official package seems to work, but I'll prob get a new VPS anyway. Thanks!
