### ISSUE TITLE
Unable to push the hugo website using git submodule 

### ISSUE THREAD

**Issue by meganeshkadam** [spf13/hugo#2176]
Hi, 

I am trying to publish my blog in Hugo using github pages. I have followed the tutorial here,
https://gohugo.io/tutorials/github-pages-blog/ ,

I have two repos, one is for hosting hugo content and another repo with, <username>.github.io hosting only the public dir's contents. When I try to : 
git submodule add -b master git@github.com:<username>/<username>.github.io.git public

It gives me error : 

[gkadam@TheMachine myproject-hugo]$ git submodule add -b master git@github.com:meganeshkadam/meganeshkadam.github.io.git public
git: 'submodule' is not a git command. See 'git --help'.

Please help!

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions.
