### ISSUE TITLE
Paginator URL encoding problem

### ISSUE THREAD

**Issue by RNAer** [spf13/hugo#2177]
I use the following to paginate my posts:

```
<nav class="pagination">
        {{if .HasPrev}}
             <a class="newer-posts" href="{{ .Prev.URL }}">&larr; Newer</a>
        {{else}}
             <a class="newer-posts" disabled="disabled" href="#">&larr; Newer</a>
        {{end}}
        <span class="page-number">Page {{ .PageNumber }} of {{.TotalPages}}</span>
        {{if .HasNext}}
            <a class="older-posts" href="{{ .Next.URL }}">Older &rarr;</a>
        {{else}}
             <a class="newer-posts" disabled="disabled" href="#">Older &rarr;</a>
        {{end}}
</nav>
```

I have chinese characters "阅读" in the tag, which is encoded as  "%e9%98%85%e8%af%bb". Looks like Hugo encodes it and strips "%" to generate the URL, because `.Next.URL` returns this url `http://localhost:1313/tags/e99885e8afbb/page/2/`. This causes problem, for the directory structure is still in Chinese character, resulting in a 404 error.

Is this a bug? What is the easiest way to fix this? Thanks!

**Comment by bep** [comment]
>What is the easiest way to fix this? Thanks!

A pull request would be fastest.

**Comment by RNAer** [comment]
Currently Hugo doesn't support ulr decoding and encoding? I am a newbie to
golang. It might take me a while to do that, although I image this should
be an easy fix.

**Comment by ks888** [comment]
I can't reproduce the bug. Hugo version and your config file might be helpful.

**Comment by Funatiker** [comment]
Not sure whether that is related but if my base URL contains the tilde symbol (~), then it won't show in the paginator-Link which makes the pages 404.

**Comment by marcliberatore** [comment]
I have the same issue as Funatiker with `Hugo Static Site Generator v0.18 BuildDate: 2016-12-19T14:43:00-05:00` and `baseurl = "http://people.cs.umass.edu/~liberato/home/"`. in my config; the `~` is stripped from the paginator's Next and Previous URLs, but not from other URLs.

**Comment by Funatiker** [comment]
@marcliberatore maybe I should add some more information on that:

    $ hugo version
    Hugo Static Site Generator v0.18 BuildDate: 2016-12-19T15:44:47+01:00

(using the .deb-Package that was released here on GitHub)

I'm using the theme https://github.com/jnjosh/internet-weblog . My wild guess (without knowing much about hugo's code) is that the problem occurs somewhere around the function `URLizeAndPrep` that is used by `newPaginationURLFactory`.

**Comment by marcliberatore** [comment]
I've created a small site that should enable reproducing this issue. Clone https://github.com/marcliberatore/disappearing-tilde, use hugo v0.18 in server mode to render it, and check the "Older" button's URL. It's missing a tilde (at least for me).

**Comment by marcliberatore** [comment]
Thank very much @bep!

**Comment by bomzj** [comment]
[I found workaround to disable encoding/escaping of  UTF-8 urls](https://github.com/gohugoio/hugo/issues/5153)
