### ISSUE TITLE
Please add hightlights theme

### ISSUE THREAD

**Issue by schmanat** [spf13/hugo#2181]
First of all thanks, for this great software.

For learning i played a litte bit arround and migrated the theme [Highlights](http://html5up.net/highlights) from [HTML5UP](http://html5up.net).

If its ok i would like to add the theme.
You'll find the repo on https://github.com/schmanat/hugo-highlights-theme.git

**Comment by bep** [comment]
Please use https://github.com/spf13/hugoThemes for theme related questions.

**Comment by bep** [comment]
Never mind, theme added, I needed to test the deployment scripts ... NIce theme.

**Comment by schmanat** [comment]
thanks for adding the theme. In future I will use the right repo.
