### ISSUE TITLE
Google Analytics Async not working

### ISSUE THREAD

**Issue by vguhesan** [spf13/hugo#2184]
When I use this:
{{ template "_internal/google_analytics_async.html" . }}

when I generate the site I get this error:

ERROR: 2016/06/05 html/template:theme/partials/footer.html:27:16: no such template "_internal/google_analytics_async.html" in theme/partials/footer.html

Where as if I use the non-async Google Analytics option, it works fine as shown below:
{{ template "_internal/google_analytics.html" . }}

Instructions for the above steps is from here:
https://gohugo.io/extras/analytics/

**Comment by digitalcraftsman** [comment]
Hello @vguhesan,

the async version was [accidently documented](https://discuss.gohugo.io/t/using-google-analytics-internal-template-in-footer-partial/3025/4?u=digitalcraftsman) as it was part of the dev version. 

A few hours ago we released a new version of Hugo that actually ships this template. Just upgrade to the latest version.

Happy Hugoing,
Digitalcraftsman
