### ISSUE TITLE
Header markdown breaks shortcode output v0.16; OS: Arch Linux

### ISSUE THREAD

**Issue by nboughton** [spf13/hugo#2192]
I noticed some odd behaviour today, I have a shortcode:

`
	
	<span id="countdown-{{ .Get 0 }}" class="countdown"></span>
	<script type="text/javascript">
	(function() {
		var f   = function(n) { return n < 10 ? n = "0"+n : n }
		var out = function(d, h, m, s) { return f(d) + "d, " + f(h) + "h, " + f(m) + "m and " + f(s) + "s" }
		var el  = document.getElementById("countdown-{{ .Get 0 }}")
		var to  = new Date({{ .Get 0 }})
		setInterval(function() {
			var now  = new Date()
			var diff = (to.getTime() - now.getTime())/1000
			if (diff > 0) {
				el.innerText = out(
					Math.floor(diff/3600/24),
					Math.floor(diff/3600)%24,
					Math.floor(diff/60)%60,
					Math.floor(diff%60)
				)
			} else {
				el.innerText = out(0, 0, 0, 0)
			}
		}, 1000)
	})()
	</script>
`

That renders a countdown to a given date when called with, for example, {{% countdown 2016-08-10 %}} 

On 0.15 this still renders fine if I make a it header by prefacing it with a #

`# {{% countdown 2016-08-10 %}}`

Since updating to 0.16 this now only renders '#}'

Removing the `#` from the beginning of the line or substituting it for other markdown characters (tested > and +) works properly.

**Comment by bep** [comment]
What OS is your netbook running?

**Comment by nboughton** [comment]
Arch Linux, Hugo v0.16

**Comment by nboughton** [comment]
I just updated to 0.16 on my 64bit machine and the problem now occurs there too.

**Comment by nboughton** [comment]
Problem also occurs on 32bit debian

**Comment by moorereason** [comment]
So, all this noise about 32-bit vs 64-bit is irrelevant?  It looks like 0.16 is the problem regardless of the OS or architecture.  Please confirm.

**Comment by nboughton** [comment]
Checked again on a vm, yes, it definitely appears to be 0.16, I'll amend the issue title and original post.

**Comment by bep** [comment]
Probably a regression from this fix: https://github.com/spf13/hugo/issues/1904

But Blackfriday should have handled it.
