### ISSUE TITLE
Base url not honored for CSS paths in 0.16

### ISSUE THREAD

**Issue by dahankzter** [spf13/hugo#2194]
--baseURL=http://localhost:1313/blog

used to render css includes (0.15) with the "/blog" in the url but now the path element seems to be missing.

**Comment by bep** [comment]
Is "blog" also a section on your Hugo site?

**Comment by dahankzter** [comment]
Not really. The hugo site is just a part of the whole site and served apache on the path "/blog". The thing is that all the other links follow the baseURL except css links.

I have reverted to 0.15 and then it works as at least I expect it to work.

**Comment by dahankzter** [comment]
Is it really supposed to not set the css path as well or is this a bug? If it is not a bug how would I go about  to work with this? I got 0.16 through homebrew locally the other day. On our CI machine we still run 0.15 for this very reason.

**Comment by bep** [comment]
>Is it really supposed to not set the css path as well or is this a bug? If it is not a bug how would I go about to work with this? 

Someone will look into it when spare time pops up. Your current workaround may be to use Hugo 0.15.

**Comment by dahankzter** [comment]
If you can point me in the right direction I can have a look. Go is no problem but Hugo has grown quite large.

**Comment by moorereason** [comment]
How are you importing your CSS resources?  Can you diff the HTML HEAD sections between 0.15 and 0.16 to see what's different?

**Comment by bep** [comment]
>If you can point me in the right direction I can have a look.

@dahankzter You have a breaking test. Look at the template where the CSS URL is constructed, then follow the code path to look where it went wrong. The `BaseURL` is located on the SiteInfo object.

Thanks for looking into this, no I can scratch it off of my TODO list.

**Comment by 1mentat** [comment]
I've just run into this as well trying to work with github pages publish. CSS doesn't honor baseurl and canonify = true.

**Comment by dahankzter** [comment]
I am sorry I haven't had any time to look into this.

One thing that struck me was to have a look at my template. Perhaps it is
possible to ignore the whole thing by specifying the css location without
explicit host.

**Comment by GuangchuangYu** [comment]
I also find this issue and switch back to 0.15.

**Comment by RaphaelVenel** [comment]
If it can help.
I have the same problem on ubuntu but it works fine on windows.

And, it's not only for css link, the variable {{ .Site.BaseURL }} seem to be empty for any link (image src, hyperlink href, etc...)

**Comment by RaphaelVenel** [comment]
I found that on the [documentation](https://gohugo.io/templates/functions/) :
{{ "mystyle.css" | absURL }} → “http://mysite.com/hugo/mystyle.css"

With this structure it works as expected.

**Comment by fmpwizard** [comment]
The reason why a site built with 0.15 produced the right path to the css file but newer version don't is that in 0.15, we could have:

`<link rel="stylesheet" href="{{ "/css/main.css" | absURL }}">`
but now we need
`<link rel="stylesheet" href="{{ "css/main.css" | absURL }}">`

note the last line doesn't have `/css`

in my case the baseURL is `baseurl = "https://www.examplesite.com/docs"` and  the css real path needs to be

https://www.examplesite.com/docs/css/main.css

**Comment by stephenbe** [comment]
@bep I have the exact same problème and I have no choice to use {{ "css/main.css" | absURL }} to make this work. 

I have an about page and all the {{ .Site.BaseURL }} do not seem to work in that specific page. 

You can test it out here : https://github.com/stephenbe/hugo-error

I would reopen this issue if you can confirm this bug with my repo
