### ISSUE TITLE
Smart quotes in titles, and mmark bodies

### ISSUE THREAD

**Issue by adrianmsmith** [spf13/hugo#2195]
The smart quotes option, as far as I can tell, only applies to the bodies of content, which are processed using the default BlackFriday ".md" parser.

The mmark seems superior in so many ways, so I have taken to using it. As it is derived from BlackFriday, presumably it also has the options for smart quotes. Yet I think they're not being used by Hugo.

Further, even if I use the BlackFriday parser, or I/we extend Hugo to also pass smartquotes and other options to mmark, it seems that quotes in titles are not processed. Is this correct? I suppose there's no easy way to solve this, as the smart quotes are done by the markdown processor, and the titles aren't markdown?

Could you confirm the above is correct, or let me know where I can set the options in case I'm missing them.

**Comment by bep** [comment]
Please take questions at http://discuss.gohugo.io/

**Comment by anthonyfok** [comment]
Hi @adrianmsmith,

Pleaes do what @ bep said, and see also Issue #1970 and Pull Request #2118.
(In short: It is forthcoming, hopefully for 0.17.)

**Comment by anthonyfok** [comment]
Oh cool, @ bep is already a step of me as always.  :wink:  See https://discuss.gohugo.io/t/smart-quotes-in-titles-and-mmark-bodies/3485
