### ISSUE TITLE
[bug] Emoji not parsed on certain text patterns

### ISSUE THREAD

**Issue by revelt** [spf13/hugo#2198]
Hi all,

There is a bug in the emoji rendering, probably related to #1892. My post content with emoji is sometimes parsed, sometimes not, and I distilled the following:

* Emoji are not parsed when the colon character is being present
* If the text after comma is short enough, emoji renders fine, no matter is there a colon or not

See this:
![hugo-emoji-bug](https://cloud.githubusercontent.com/assets/8344688/15985550/680c9270-2fe9-11e6-8806-50bb275fbcff.gif)

Try copy-pasting into your sites to test:

    Aaaaaaaaaa: aaaaaaaaaa aaaaaaaaaa aaaaaaaaaa.

    :rocket:

In practice, my blog articles contain some colon characters and emoji are not being parsed on the whole article. By the way, I'm using the latest Hugo v0.16 from Brew.

**Comment by memiks** [comment]
Hello,

Ok but I try my text with master source code without success...
After the merge of your commit.

You can test if you want.

Best regards,
Memiks.

**Comment by bep** [comment]
I did: https://github.com/spf13/hugo/commit/aa66478c201053165e5f7dd041915f68f7f87c27

Are you saying there are other failing test cases?

**Comment by revelt** [comment]
I'd help testing, but I'm not good at compiling. I'm still at 0.16 first release...
