### ISSUE TITLE
hugo new from outside root directory

### ISSUE THREAD

**Issue by teamblubee** [spf13/hugo#2200]
```
hugo new /path/to/hugo/project/post/location post post_name
Error: Unable to locate Config file. Perhaps you need to create a new site.
       Run `hugo help new` for details. (Unsupported Config Type "")
```
If you try to run the above command from outside of the hugo project folder structure it will complain about the config file. Is it possible to allow passing the location of the config file to hugo so that you could create posts from a directory outside of the hugo project directory?

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions.
