### ISSUE TITLE
Cross links in header not redendering correctly

### ISSUE THREAD

**Issue by vishr** [spf13/hugo#2209]
In v.15 I had `### [Foo]({{< ref "foo.md">}})` which rendered correctly but in latest (v.16) it produces `[Foo](#})`. 

I have searched docs and other issues but could not find anything related.

**Comment by vishr** [comment]
@bep Quick question: Will you cut a new release? Otherwise what's the best way to get it?

**Comment by bep** [comment]
>@bep Quick question: Will you cut a new release?  

@spf13 cuts releases, and traditionally it hasn't been often. `go get` is the easiest way.

**Comment by vishr** [comment]
Got it.
