### ISSUE TITLE
dev server css mimetype errors with internet explorer 8

### ISSUE THREAD

**Issue by cpisto** [spf13/hugo#2218]
commands/server.go adds ".json" and ".css" to the standard library mime package with a charset of "utf8". Internet Explorer 8 (and probably other versions) errors out loading this mimetype in certain situations (error c00ce56e in the case of AJAX loads).

https://github.com/spf13/hugo/blob/master/commands/server.go#L100

Changing this mimetype to the (correct) "utf-8" solves the problem.

Incidentally, the mime package already includes a builtin entry for ".css", with the correct mimetype, so maybe consider simply removing the override hugo adds?

https://golang.org/src/mime/type.go?#L36

**Comment by bep** [comment]
The CSS entry was added recently because someone complained loudly, so I'm not sure that can be removed.

**Comment by cpisto** [comment]
Curious, the css builtin has been there forever.

**Comment by cpisto** [comment]
From what I can tell, the added mime type doesn't actually do anything besides override the builtin type "text/css; charset=utf-8" with "text/css; charset=utf8", so not only is it not the thing that fixed #2104 (some other change must have fixed that), it also introduced an invalid mimetype.

**Comment by cpisto** [comment]
You rock :+1:
