### ISSUE TITLE
docs: Make the baseof.html reference in the docs more obvious

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2231]
See https://discuss.gohugo.io/t/blocks-and-define-override-in-hugo-theme/3543

**Comment by marcojakob** [comment]
Yes, the use of block templates needs to be more clear:

* What's the meaning of `baseof`?
* Can I create multiple `baseof` files like `baseof-blog.html` or `baseof*`?
* Where can I use block templates? It's not obvious why you can't use `block` keywords in partial files.

**Comment by bep** [comment]
This duplicates https://github.com/spf13/hugo/issues/2363

(@marcojakob I see some questions in your list that is better suited for the forum (like "what is the meaning of `baseof`?")
