### ISSUE TITLE
Doubled blank line breaks in rendered code blocks

### ISSUE THREAD

**Issue by tomduncalf** [spf13/hugo#2233]
First, great piece of software. Was really impressed how easy it was to get a blog up and running, so thanks very much!

I'm having an issue where blank line breaks in code blocks are being doubled (so two new blank lines instead of one) in the rendered output. This occurs with all the themes I have tried.

An example can be seen in the code block in point `2` at http://blog.tomduncalf.com/posts/setting-up-typescript-and-react/#adding-react-to-the-project:0a3ac9e5e91cb9461812f85f023fcd75 – in the original source, this is a single line break (https://github.com/tomduncalf/blog/blob/master/content/posts/setting-up-typescript-and-react.md#adding-react-to-the-project) but it appears doubled when rendered.

**Comment by bep** [comment]
What is

1) The output of `hugo version`
2) The output of `hugo config | grep -i pygm`

If you are on Windows (aka an OS without pipes and grep, just do `hugo config` and look for the pygments settings.

**Comment by tomduncalf** [comment]
1) `Hugo Static Site Generator v0.15 BuildDate: 2015-11-26T06:29:07Z` (installed from `brew`)
2) ```pygmentscodefences = false
pygmentsoptions = ""
pygmentsstyle = "monokai"
pygmentsuseclasses = false```

Thanks

**Comment by bep** [comment]
I would recommend you start by upgrading Hugo. That is a very old version (don't ask me about Brew ... I'm not sure if that is up-to-date).

**Comment by tomduncalf** [comment]
Ah sorry, I thought I had an up to date version as I ran `brew upgrade hugo`, but didn't realise you had to run `brew update` before running that. Everything is great with `0.16`, thanks and sorry to waste your time!
