### ISSUE TITLE
Error: unknown command "genautocomplete" for "hugo"

### ISSUE THREAD

**Issue by AnneTheAgile** [spf13/hugo#2235]
per 
http://gohugo.io/commands/hugo_genautocomplete/
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-hugo-a-static-site-generator-on-ubuntu-14-04

I can run; 
$ sudo hugo genautocomplete

and get bash typings. 
On Ubuntu 16.04, I get instead; 
Error: unknown command "genautocomplete" for "hugo"

Details;
$ which hugo ; hugo version /usr/bin/hugo
Hugo Static Site Generator v0.16 BuildDate: 2016-06-12T04:47:29-04:00

**Comment by bep** [comment]
It is `sudo hugo gen autocomplete`, will fix the doc.
