### ISSUE TITLE
Document homepage content workaround

### ISSUE THREAD

**Issue by jzacsh** [spf13/hugo#2240]
**tl;dr** is markdown inclusion for homepage already being worked on? if not i'll just send a pull request to document that markdown (and in turn shortcodes) require a workaround hardcoding the page title in an if~ish statement.

If no one is working on it at the moment, and a patch would be welcome to fix some of this, I'd be happy to help. Would it be acceptable to just have a hardcoded file-check for a `content/index.*` file when rendering a homepage node?

**Comment by bep** [comment]
>Would it be acceptable to just have a hardcoded file-check for a content/index.* file when rendering a homepage node?

The problem needs a better solution, and a temporary solution like this is bad if we decide for some other naming scheme. A document patch about the workaround would be welcomed, though.

**Comment by bep** [comment]
Will be handled in #2297.

**Comment by jzacsh** [comment]
thanks! _(and sorry for the radio silence - i totally forgot about this)_
