### ISSUE TITLE
`hugo server` should check for /foo.html when requesting /foo

### ISSUE THREAD

**Issue by octref** [spf13/hugo#2242]
I'm using https://surge.sh/ to deploy my hugo site. It has a great [clean url feature](https://surge.sh/help/using-clean-urls-automatically), so if you have `/foo.html`, `/foo` will get it, `/foo/` will redirect to `/foo`.

So now I'm creating `content/foo.md`, and enabling `uglyurls` so hugo generates `/foo.html`.

In some pages, such as listing page, I'm now using `{{ trim .RelPermalink ".html" }}` to use clean url in href. However, this causes problem with hugo server. A request of `/foo` doesn't check the existence of `/foo.html`, but directs to `/foo/` to try `/foo/index.html` immediately.

**Comment by octref** [comment]
@anthonyfok Hey I'm interested in doing this myself, but I don't have much experience with golang. or hugo. Would you mind giving me a pointer as to where to start?

**Comment by bep** [comment]
@octref this issue is in the category of "we should most likely not do this", and only if it is really simple and someone is providing a finished solution for it. Teaching you Golang doesn't fit that bill.

**Comment by octref** [comment]
@bep I understand that. Just want to know where to start. Guess I'll look into https://github.com/spf13/hugo/blob/master/commands/server.go and how `net/http fileserver` handles request.

Just wondering, is it that you are against this feature?
If not, are you OK if I do it this way?

`/foo` serves `/foo.html` if it's available. If not, directs to `/foo/` and behave like it is before.

**Comment by octref** [comment]
Knowing "we should most likely not do this" is useful as I can possibly avoid the awkward situation where I take time to do a PR and you don't want this feature at all.

Also saw your comment at #874:
> @rustyoz I agree, but I still feels that the FileServer devs should have made this extensible in the first place. When they sober up from GopherCon I will post an issue; but that will be Go 1.6 at best.

> I guess this discussion can hold until we decide what to do about a REST api.

So as for approach to this problem:
- Is `FileServer` made extensible now go is 1.7?
- Does hugo need to take dep on https://github.com/julienschmidt/httprouter to implement this feature?
- Or is it you are doing the REST api(didn't see it in code, and didn't find it on roadmap)?

**Comment by octref** [comment]
Guess I'll should switch back to jekyll.

**Comment by carlmjohnson** [comment]
I'm not sure I understand this feature request. 

Is it that you want the page URL to be /a/ but you want the filename to be /a.html instead of /a/index.html so your provider will do redirects? If so, there's no need to adjust Hugo. Just write a script (could be in any language, doesn't have to be Go) to move /a/index.html to /a.html after you've done a build with Hugo, since it's really about the final file locations, not the URL as Hugo understands them.
