### ISSUE TITLE
Incorrect node variable values for homepage in custom sitemap.xml template

### ISSUE THREAD

**Issue by ianbrandt** [spf13/hugo#2251]
```
$ hugo version
Hugo Static Site Generator v0.16 BuildDate: 2016-06-06T05:37:59-07:00
```

I've been trying to get an accurate `<lastmod>` value for my homepage in my sitemap.xml.  I'm working on a non-blog site that so far has just a homepage and one other content page.  Hugo seems to default the `.Lastmod` and `.Date` values for the homepage [to that of the other content page](https://github.com/spf13/hugo/blob/858810331604749843cb761779498309701aaea5/hugolib/site.go#L1722).  This doesn't make sense in my use case.

Since there doesn't appear to be a way to provide [front matter for the homepage](https://discuss.gohugo.io/t/is-there-any-way-to-have-frontmatter-metadata-for-homepage/), I figured I'd have to resort to a [custom sitemap.xml template](https://gohugo.io/templates/sitemap/) to hardcode `<lastmod>` for the homepage.  In doing so I've found that some of the node variables for the homepage are not what I as expecting.  I added the following debug code to 'layouts/sitemap.xml':

```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	{{ range .Data.Pages }}
	URL: {{ .URL }}
	Title: {{ .Title }}
	Type: {{ .Type }}
	IsPage: {{ .IsPage }}
	IsNode: {{ .IsNode }}
	IsHome: {{ .IsHome }}
[...]
```

This was the result for the homepage:

```
.URL: /
.Title: 
.Type: page
.IsPage: true
.IsNode: false
.IsHome: false
```

Instead I expected the `.Type` value to be "node", with corresponding `.IsNode` and `.IsPage` values.  I also expected the `.IsHome` value to be `true`.

For now I'm calling out the homepage in my template with `{{ if eq .URL "/" }}` instead of `{{ if .IsHome }}`.

**Comment by bep** [comment]
There is only one sitemap and it is of type page, not home and not node. For any other questions, take it at the forum.

**Comment by ianbrandt** [comment]
@bep Hi, sorry, my report perhaps could have been more clear.  I'm referring to the values for the [current iteration of a `{{ range .Data.Pages }}` action](https://gohugo.io/templates/go-templates/#context-a-k-a-the-dot), not those for the top-level sitemap.xml template context.  In the iteration context I'm expecting the result of `{{ .IsHome }}`, etc. to be that of the homepage and the other content pages, not that of the sitemap page.  Is that not correct?

For reference here is the full content of my current sitemap.xml template, where I would expect to be able to use `{{ if .IsHome }}` in place of `{{ if eq .URL "/" }}`:

```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	{{- range .Data.Pages }}
	{{- if eq .URL "/" }}
	<url>
		<loc>{{ .Permalink }}</loc>
		<lastmod>2016-07-03T19:43:46-07:00</lastmod>
	</url>
	{{- else if not .Params.private }}
	<url>
		<loc>{{ .Permalink }}</loc>
		<lastmod>{{ safeHTML ( .Lastmod.Format "2006-01-02T15:04:05-07:00" ) }}</lastmod>
		{{- with .Sitemap.ChangeFreq }}
		<changefreq>{{ . }}</changefreq>
		{{- end }}
		{{- if ge .Sitemap.Priority 0.0 }}
		<priority>{{ .Sitemap.Priority }}</priority>
		{{- end }}
	</url>
	{{- end }}
	{{- end }}
</urlset>
```
