### ISSUE TITLE
Can't specify sitemap variables via front matter

### ISSUE THREAD

**Issue by ianbrandt** [spf13/hugo#2252]
The [Sitemap Template doc](http://gohugo.io/templates/sitemap/) says, "The same fields can be specified in an individual page’s front matter in order to override the value for that page."  I added the following to the front matter of my content page:

```
[...]
changefreq = "monthly"
priority = "0.5"
+++
```

After doing so and rebuilding, the `<changefreq>` and `<priority>` elements did not render for the page when using the default sitemap.xml template.

**Comment by amritha-v** [comment]
Just try including your changes under sitemap header as follows:
+++
sitemap:
  changefreq: "monthly"
  priority: 0.5
+++
This worked for me under hugo v0.16
Hope this solves your problem @ianbrandt

**Comment by bep** [comment]
Does that solve your issue @ianbrandt ?

**Comment by ianbrandt** [comment]
@bep That did it, with minor syntax corrections for TOML:

```
+++
[sitemap]
changefreq = "monthly"
priority = 0.5
+++
```

Thanks!
