### ISSUE TITLE
Nested archetypes

### ISSUE THREAD

**Issue by josdem** [spf13/hugo#2256]
I have the following structure in content:

```
content
├── techtalk
│   ├── algorithms
│   │   ├── algorithm_binary_tree.md
│   │   ├── algorithm_fastman.md
│   │   ├── algorithm_stream_merger.md
```

So in my archetype directory I have:

```
archetypes
├── jmetadata.md
└── techtalk.md
```

There is no way to specify an archetype to algorithms pages directory?

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions.
