### ISSUE TITLE
hugo new [post] fail with cast error when +++ has one trailing space in CRLF archetype file

### ISSUE THREAD

**Issue by the1900** [spf13/hugo#2258]
Hi I'm not native please understand.

It said problem at theme`s archtypes and my archtypes either. I totally can`t understand What did i wrong....

OS: Win 10 x64
Hugo version: v0.16

default.md
```
+++ 
draft = false
isCJKLanguage= true
+++

```

ko.md 
```
+++ 
tags = ["ko"]
draft = false
isCJKLanguage = true
+++

```

en.md
```
+++ 
tags = ["en"]
draft = false
isCJKLanguage= true
+++

```

this is config
![006](https://cloud.githubusercontent.com/assets/10105141/16608137/c9ecb5d0-4383-11e6-8ae1-482f98d8219f.png)

this is cmd
![005](https://cloud.githubusercontent.com/assets/10105141/16608134/c6b75c12-4383-11e6-9c92-1ca155412dd9.png)

**What is wrong of mine???**

**Comment by the1900** [comment]
I found the reason. It was just a `white space`.

I've tried to figure out what is wrong and i realized a `white space` inserted top of the `default.md`
so it had to be like `+++` but mine was `+++ `. The `white space` was exist after `+++` 

I hope to help to other guys who`s got same situation.

**Comment by anthonyfok** [comment]
@the1900, I am glad that you found the solution to the problem.

There is another thing that I noticed: You seem to be misusing <kbd>`</kbd> (U+0060 grave accent) when you actually mean to use <kbd>'</kbd> (U+0027 apostrophe).  You should use the key to the left of the <kbd>Enter</kbd> key, not the key above the <kbd>Tab</kbd> key.  Hope this helps!

**Comment by anthonyfok** [comment]
See also #315 and #1279

**Comment by anthonyfok** [comment]
Maybe not really a bug, but I do notice an inconsistency:

Using `+++ ` (with one trailing space) in the archetype on Linux (with LF line ending) does not cause an error.  But when converted to CR/LF line ending in DOS/Windows (with `todos`, for example), the error is triggered.  A somewhat inconsistent behaviour that could trip up new and old users alike.  To investigate and see if a fix is necessary.

**Comment by the1900** [comment]
@anthonyfok  thanks to respond.

yeah I actually didn't know that I should use <kbd>'</kbd> (U+0027 apostrophe) for short form.
Thanks to notify me.

I think *goLang* should update this problem. It has to recognizes and works line ending whatever  machine's line ending type

**Comment by anthonyfok** [comment]
> yeah I actually didn't know that I should use <kbd>'</kbd> (U+0027 apostrophe) for short form.
Thanks to notify me.

You are very welcome.  U+0060 (grave accent, or backtick quote) means something special in Markdown, so if you were using U+0060 for U+0027, you would get something like this, as you typed earlier:

> It said problem at theme`s archtypes and my archtypes either. I totally can`t understand What did i wrong....

Notice how "s archtypes and my archtypes either. I totally can" becomes monospaced?  Markdown sees the U+0060 backticks, and thought you meant to type code.

> I think *goLang* should update this problem. It has to recognizes and works line ending whatever machine's line ending type

GoLang is fine in handling CR/LF line endings.  It is something else, I suspect.
