### ISSUE TITLE
`hugo new` no longer accepts config file string

### ISSUE THREAD

**Issue by ashitaka1** [spf13/hugo#2261]
In v0.15, `hugo --config=<config-file> new <path>` worked. In 0.16 it produces:

`Error: unknown flag: --config`

**Comment by ashitaka1** [comment]
v0.16

**Comment by ashitaka1** [comment]
sweet.

**Comment by bep** [comment]
Sorry about the bug, my fault, but I had to clean up that flag mess, before every flag were globals ...

**Comment by ashitaka1** [comment]
Well, thanks for fixing it!
