### ISSUE TITLE
Default baseurl of replace-this-with-your-hugo-site.com is a very suspicious

### ISSUE THREAD

**Issue by martylookalike** [spf13/hugo#2264]
Going through the quick start and noticed that a generated site contains the url "replace-this-with-your-hugo-site.com" as the default baseurl in config.toml (and in the docs). This url, which may be clicked unknowingly by a new user (I did, lol), and it's very suspicious (executed script redirecting to pages my adblocker dislikes and pops up notices about infected computer and plays beeping sounds, etc). 

Here's a google search showing the link to this site. Now appears to forward through some advertising url to a real estate site.
https://www.google.com/#q=http:%2F%2Freplace-this-with-your-hugo-site.com%2F

Can we possibly replace the baseurl with something more benign like the gohugo.io url or something that won't resolve to a real domain? Doesn't seem like the ideal thing for a new user to see just when trying out Hugo. Even just dropping the ".com" would probably be an improvement. 

Thanks very much. This is my first posted issue so hopefully it's in the right place. I'd be interested in contributing to Hugo's development at some point so let me know if I can help directly with this -- e.g., updating the code and docs.

**Comment by bep** [comment]
Thanks for the heads up, what those scammers will do to to earn a few extra cents is incredible.

**Comment by martylookalike** [comment]
Absolutely, you're welcome =)

**Comment by bep** [comment]
```bash
d
▶ find . -name "*.md" | xargs grep "replace-this-with-your-hugo-site.com"
./content/overview/quickstart.md:baseurl = "http://replace-this-with-your-hugo-site.com/"
./content/tutorials/creating-a-new-theme.md:baseurl = "http://replace-this-with-your-hugo-site.com/"
./content/tutorials/creating-a-new-theme.md:    <h1><a href="http://replace-this-with-your-hugo-site.com/article/second/">second</a></h1>
./content/tutorials/creating-a-new-theme.md:    <h1><a href="http://replace-this-with-your-hugo-site.com/article/first/">first</a></h1>
./content/tutorials/creating-a-new-theme.md:  <p><a href="http://replace-this-with-your-hugo-site.com/">Home</a></p>
./content/tutorials/creating-a-new-theme.md:  <p><a href="http://replace-this-with-your-hugo-site.com/">Home</a></p>
./content/tutorials/creating-a-new-theme.md:  <p><a href="http://replace-this-with-your-hugo-site.com/">Home</a></p>
./content/tutorials/creating-a-new-theme.md:    <h1><a href="http://replace-this-with-your-hugo-site.com/about/">about</a></h1>
./content/tutorials/creating-a-new-theme.md:    <h1><a href="http://replace-this-with-your-hugo-site.com/article/second/">second</a></h1>
./content/tutorials/creating-a-new-theme.md:    <h1><a href="http://replace-this-with-your-hugo-site.com/article/first/">first</a></h1>
./content/tutorials/creating-a-new-theme.md:      <h2><a href="http://replace-this-with-your-hugo-site.com/article/second/">second</a></h2>
./content/tutorials/creating-a-new-theme.md:      <h2><a href="http://replace-this-with-your-hugo-site.com/article/first/">first</a></h2>
./content/tutorials/creating-a-new-theme.md:      <h2><a href="http://replace-this-with-your-hugo-site.com/about/">about</a></h2>
./content/tutorials/creating-a-new-theme.md:  <p><a href="http://replace-this-with-your-hugo-site.com/">Home</a></p>
./content/tutorials/creating-a-new-theme.md:  <p><a href="http://replace-this-with-your-hugo-site.com/">Home</a></p>
```

Not sure what to put there, though ...

**Comment by knarz** [comment]
How about `example.org`?

**Comment by anthonyfok** [comment]
Thank you all for having this fixed!  I should have known better than to have picked this somewhat convoluted domain name!  Though it being registered by a spammer is a surprise to me.  Lesson learned.

**Comment by LiaungYip** [comment]
I got caught by this as well.

In addition to the occurrences in the docs, a lot of themes have `baseurl = "replace-this-with-your-hugo-site.com"` in their default `config.toml` - Blackburn and `hugo-material-docs`, are some examples, I think.
