### ISSUE TITLE
Keep order consistent in generated source

### ISSUE THREAD

**Issue by thepian** [spf13/hugo#2267]
It seems that every time source is generated the order changes randomly. In my sitemap for instance the entries are swapped around after generation. This makes checking generated source into source control quite messy.

**Comment by bep** [comment]
Not sure why you would check the generated source into source control, but each its own taste.

There is a stable sort in every page list generated by Hugo. Re. the sitemap, this might have been an issue with < Hugo 0.16 with duplicate dates, but now it uses title and file path as alternative sort keys. 

Can you check your Hugo version and your sort keys (dates).

**Comment by thepian** [comment]
I have to wait for home-brew to update. It's at 0.14

**Comment by bep** [comment]
Brew is up-to-date, but I believe the trick is to do brew upgrade + brew update hugo (or something).

**Comment by rdwatters** [comment]
brew update && brew upgrade hugo
