### ISSUE TITLE
It would be nice if "draft" was added to Params

### ISSUE THREAD

**Issue by evanmcc** [spf13/hugo#2271]
Here is where it gets dropped: https://github.com/spf13/hugo/blob/master/hugolib/page.go#L592

It'd be nice if it were added to the map, as it would make it quite easy to add preview functionality.  I.e. generating with -D and having the page generated, but easy to remove from main page and post list generation templates.

**Comment by bep** [comment]
You have it in `.Draft`, why do you also need it in params?

**Comment by evanmcc** [comment]
this is what you get got opening issues after bedtime.  sorry!
