### ISSUE TITLE
SiteInfo Authors AuthorList is never populated

### ISSUE THREAD

**Issue by eljobe** [spf13/hugo#2282]
On [line 106 in site.go](https://github.com/spf13/hugo/blob/ef9b915680e21d5ab5fceb7c7957fd0b626942a7/hugolib/site.go#L106) there is the declaration of a field `Authors` of type `AuthorList`

I haven't figured out any way to populate that field from a config file. In fact in [InitializeSiteInfo()](https://github.com/spf13/hugo/blob/ef9b915680e21d5ab5fceb7c7957fd0b626942a7/hugolib/site.go#L773) it doesn't appear to be populating the `Authors` field.

Please either clean up the dead code, or support it.

**Comment by bep** [comment]
For questions, please use discuss.gohugo.io/

**Comment by eljobe** [comment]
I actually did post a question there: [How to configure and use .Site.Author](https://discuss.gohugo.io/t/how-to-configure-and-use-site-author/3682?u=pepper)

But, then, when investigating the answer further, I saw what I believe to be an actual bug in the code, so I filed this issue. Notice, I didn't ask any questions in the issue description.

**Comment by bep** [comment]
>I haven't figured out any way to populate that field from a config file.

This is a question without a question mark. Let's take this in the relevant thread.
