### ISSUE TITLE
docs: "Installing on Windows" rendering

### ISSUE THREAD

**Issue by samozzy** [spf13/hugo#2285]
Got some raw markdown and what looks like mis-rendering in the "installing on Windows" doc page.
![windows](https://cloud.githubusercontent.com/assets/15388319/16913078/25278898-4ce0-11e6-8f07-169e52be2e2c.png)
Renders fine on the [GitHub page](https://github.com/spf13/hugo/blob/master/docs/content/tutorials/installing-on-windows.md)

**Comment by anthonyfok** [comment]
Hi!  Just to say that I have been working on #2280 and have fixed this doc issue too on my computer by removing the indent.  I will make a push soon.

That said, this perplexes me: Is such indented paragraphs, including the indented headings, supposed to be supported by Blackfriday (or with the github_flavored_markdown extension) and/or Mmark?  (Sorry, I haven't looked into this in detail.)

What do you think, @shurcooL and @miekg?  Many thanks for your insights.

**Comment by shurcooL** [comment]
It's a known difference between blackfriday rendering and that of GitHub.com. Blackfriday requires list entries that consist of multiple paragraphs to be indented by at least 4 spaces or a single tab, whereas GitHub.com markdown renderer is happy with only 2 spaces.

**Comment by anthonyfok** [comment]
Thank you @shurcooL for your quick response and great insight.  Per your explanation, I have fixed the rendering issue by changing the 2-space indents to a 4-space indents, and they are now rendered correctly.

The corrected page is now live at https://gohugo.io/tutorials/installing-on-windows/#less-technical-users
