### ISSUE TITLE
Fix Node vs Page

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2297]
This issue tracks improvements as described in https://discuss.gohugo.io/t/node-improvements/1593

Related issues dangling around will be closed as they must be considered when fixing this.

**Comment by VoidingWarranties** [comment]
Has this been resolved? Curious because in a07293cf9741c9b5c10c80db9870ebfd2d2849c1 the commit message says
>... This implementation is a temp solution until we fix #2297.

**Comment by bep** [comment]
No it was closed by mistake.
