### ISSUE TITLE
Improve taxonomies performance

### ISSUE THREAD

**Issue by thunderer** [spf13/hugo#2301]
Hi everyone, let me start by thanking you for Hugo. I was really stunned when I saw that static page generator can be *that* good. :)

I just downloaded latest release `v0.16` for Linux amd64. I have a blog with nearly 300 posts, all of them have taxonomies `categories` and `tags` (around 10 entries per post in total) with corresponding entry in `config.yaml`. The problem is that enabling those taxonomies causes massive performance drop. I ran `hugo --stepAnalysis` for both versions and time difference is around `1100ms` vs `5000ms`. The only difference in step analysis output is "render and write taxonomies" step:

```
render and write taxonomies:
	3.87564192s (4.16626472s)	  876.48 MB 	16698838 Allocs

render and write taxonomies:
	44.31µs (198.28967ms)	    0.00 MB 	23 Allocs
```

I understand that having more things to compute takes more time, but I didn't expect such difference. Is it something that can be fixed or improved?

**Comment by bep** [comment]
This site, is it public so others can test it? What is the output of one Hugo build (the stats)?

**Comment by thunderer** [comment]
I'm migrating my blog from WordPress to Hugo, but the "converted" version is not published yet. To see what kind of content is there please visit http://blog.kowalczyk.cc/ . I assume you want "stats" from the whole run with `--stepAnalysis`, here you are:

```
Started building site
Go initialization:
	25.912695ms (27.20941ms)	    1.57 MB 	14618 Allocs
initialize & template prep:
	7.92949ms (35.261322ms)	    0.69 MB 	9652 Allocs
load data:
	192.272µs (35.51272ms)	    0.00 MB 	143 Allocs
read pages from source:
	62.067436ms (97.712098ms)	   12.55 MB 	118937 Allocs
convert source:
	76.690027ms (174.57676ms)	   35.91 MB 	164209 Allocs
build taxonomies:
	102.173599ms (276.839263ms)	    4.67 MB 	175744 Allocs
render and write aliases:
	1.781µs (276.946809ms)	    0.00 MB 	0 Allocs
render and write taxonomies:
	3.876748986s (4.153844571s)	  873.82 MB 	16698997 Allocs
render & write taxonomy lists:
	368.252µs (4.154290837s)	    0.02 MB 	632 Allocs
render and write lists:
	339.592272ms (4.494014846s)	   27.93 MB 	680881 Allocs
render and write pages:
	203.99572ms (4.698288244s)	   40.30 MB 	1003762 Allocs
render and write homepage:
	376.701625ms (5.07511913s)	   28.90 MB 	678384 Allocs
render and write Sitemap:
	34.128885ms (5.10941466s)	    2.39 MB 	60042 Allocs
render and write robots.txt:
	12.701µs (5.109583023s)	    0.00 MB 	15 Allocs
0 of 1 draft rendered
0 future content
280 pages created
0 non-page files copied
2168 paginator pages created
2013 tags created
29 categories created
in 5082 ms
```

**Comment by bep** [comment]
```bash
280 pages created
0 non-page files copied
2168 paginator pages created
2013 tags created
29 categories created
in 5082 ms
```

This doesn't look far off from Hugo's "speed promotions" at 5000ms for about 5000 pages, so wouldn't label this as anything close to "massive".

There are a few things you could try:

1) You have a very un-natural tag-to-page ratio. Tags are in my head "common labels", there cannot be much "common" in your tagging. In my blog, with 138 pages, I have 20 tags ...
2) Increase the paginator size may help reduce the number of paginator pages.

Take further questions at http://discuss.gohugo.io/

**Comment by thunderer** [comment]
Maybe I did something wrong with my custom WordPress exporter script. :) I agree that 5000ms for 5000 pages does not sound slow, so I'll tinker with my content and try to reduce that to acceptable amount.
