### ISSUE TITLE
Spurious results using range where .Site.Menus

### ISSUE THREAD

**Issue by waddles** [spf13/hugo#2307]
I have a menu called 'main' that has at least 11 entries in it and I am trying to pull only 4 submenus out of it as 4 columns using a `where identifier in "list"` construct.

I have created the following in my template:

```
{{- range $index, $entry := where .Site.Menus.main ".Identifier" "in" "events history rallies trophies" -}}
{{- with $entry -}}
<div class="menu-col-{{ add $index 1 }} col-sm-3">
    <a href="{{ .URL }}" class="dropdown-link {{ .Identifier }}">{{ .Pre }}<span>{{ .Name }}</span></a>
    <ul class="dropdown-menu dropdown-menu-sub">
{{- range .Children -}}
      <li>
        <a href="{{ .URL }}">{{ .Pre }}<span>{{ .Name }}</span></a>
      </li>
{{- end -}}
    </ul>
</div>
{{- end -}}
{{- end -}}
```

but the results have 3 extra empty columns which are entries without an identifier configured in the site's config.toml.

Should the `where` function filter out nodes where the requested field is nil?

**Comment by bep** [comment]
The in operator matches in a slice. A string happens to be a slice, but it also matches on empty strings, apparently, which is what Identifier is when empty.

Try:

```
{{- range $index, $entry := where .Site.Menus.main ".Identifier" "in" (slice "events", "history", "rallies", "trophies") -}}
```
