### ISSUE TITLE
v0.16 release tagged code is 0.17-DEV

### ISSUE THREAD

**Issue by drewbroadley** [spf13/hugo#2308]
Hi there,

We have had a problem with `go get -u -v github.com/spf13/hugo` on the latest version of hugo when trying to run it through Codeship.

We've been beating our heads over the issue of it always installing 0.17-DEV, not 0.16.

After doing testing of the following:
- Install from `go get -u -v github.com/spf13/hugo`, output of hugo version is 0.17-DEV
- Download from https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16_linux-64bit.tgz and run ./hugo, we get version 0.16
- Download source from https://github.com/spf13/hugo/archive/v0.16.tar.gz, build using `go build -o hugo main.go` and run ./hugo, we get version 0.17-DEV

**Comment by digitalcraftsman** [comment]
Even if this issue is still existent I don't think that it will be fixed nor that it affects a lot of users anymore. Hence I propose to close this issue.
