### ISSUE TITLE
Supress "missing static" ERROR when static exists in theme

### ISSUE THREAD

**Issue by anagio** [spf13/hugo#2311]
After uploading a hugo site to a repo someone who cloned it ran `hugo server -w` and got this error `ERROR: 2016/07/28 23:33:38 hugo.go:637: Walker:  lstat /Users/.../testhugo/static: no such file or directory`

It was because I did not include the root level `static` folder in the repo. The theme however has a static folder which is where all the static assets live. Should I be placing static assets into the root static folder and not within the theme static folder?

I do not have a root level `archetypes` and got no errors about it. What's the reason the static folder is required?

**Comment by bep** [comment]
I think you currently need a /static folder even if it is empty. So if your files iive in the theme, just create a dummy /static (with a .gitkeep file or something) in the root. 

We should fix this. There is no real reason the static is required (at least one static folder is requred, I guess ...)
