### ISSUE TITLE
multilingual: Add option to keep the main language on top level

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2312]
See #2309 

I'll add this here for discussion

I'll take two of my Hugo sites as an example:

http://bepsays.com/ => Norwegian
http://bep.is/ => English

`bepsays.com` has some English content, so I would love to have a `http://bepsays.com/en/`, but I would still like my old URLs (the main content) to live as before.

`bep.is` has a short presentational text in English. It would be cool to point to translations in French, Japanese etc., but I would still like the main language to stay where it is.

* This complicates things a little, it somewhat put restrictions on section namings etc., but I think it is worth it.
* It should be optional, but probably default `on`

/cc

@abourget 
@spf13 
@RickCogley 
@the1900 I

**Comment by abourget** [comment]
You mean you'd like to render the English homepage at the complete root ?

I use a quick redirection based on browser settings with a hard coded
fallback. Have you seen that ?

GolangMontreal.org/index.html

**Comment by bep** [comment]
>You mean you'd like to render the English homepage at the complete root ? I use a quick 

Yes.

>redirection based on browser settings with a hard coded fallback. Have you seen that ?

Yes, and that is the good an natural solution for the "full multilanguage" sites. But that does not fit some of my use cases, for SEO reasons etc. (I don't want to move 90% of my URLs one level down), I don't want my "main page" be a redirect etc.

**Comment by abourget** [comment]
OK this shouldn't be very difficult.. as the addition of prefixes happens
only in a few places. We don't have anything to detect collisions though..
but I would be comfortable not having any.. assuming people don't name
their posts "en" or such.

**Comment by bep** [comment]
Things to keep in mind when implementing:

* [ ] sitemap.xml

**Comment by abourget** [comment]
What I did (if I didn't document it, I should), is I wrote a static `sitemap.xml` in my `static/` dir like:

```
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap>
      <loc>https://blog.abourget.net/en/sitemap.xml</loc>
   </sitemap>
   <sitemap>
      <loc>https://blog.abourget.net/fr/sitemap.xml</loc>
   </sitemap>
</sitemapindex>
```

**Comment by reuixiy** [comment]
@bep Hi there, I got a problem when I test Hugo Multilingual Mode for my unfinished Hugo theme, and I Google here...

Briefly, Hugo generated a useless folder `zh` in `public` directory, which includes `index.html`(a redirect file, use `http-equiv="refresh"` to redirect to home(`/`), same as Hugo Aliases) and `sitemap.xml` two files.

My `config.toml`:

```toml
DefaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[languages]
  [languages.zh]
    languageName = "中文"
    contentDir = "content/zh"
    weight = 0
    languageCode = "zh-CN"
    hasCJKLanguage= true
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
    languageCode = "en-US"
```

What’s more, this folder still could not be removed after I’v tried some tricks, such as:

1. set `disableAliases = true` in `config.toml`
2. add `content/zh/zh/_index.md` and add `outputs: []` to its front matter

Although this folder has no side effects and I can delete it by myself or bash script, it’s great if Hugo won’t generated it at all or give an option to config it.

Thx.

**Comment by reuixiy** [comment]
Oh I see… It’s not useless… The `/sitemap.xml` is just a link to the `/zh/sitemap.xml` and the `/en/sitemap.xml`… In multilingual mode, it has to be like this… Because there can only be one file with the same name in the same folder…
