### ISSUE TITLE
Markdown file not rendering

### ISSUE THREAD

**Issue by afandian** [spf13/hugo#2316]
I have a site working, but one specific markdown file is failing to render. It's very strange.

test.md:

```
---
title: "test"
date: 2011-01-01
---

test
```

rendered content

```
<hr />

<p>title: &ldquo;test&rdquo;</p>

<h2 id="date-2011-01-01">date: 2011-01-01</h2>

<p>test</p>

```

If I make another file with the same content, it is rendered correctly. I am getting my render from `hugo server` which I have restarted to make sure there wasn't a cache issue.

**Comment by bep** [comment]
For questions and troubleshooting, please use http://discuss.gohugo.io/

**Comment by afandian** [comment]
Fine, but I think this is a bug.

**Comment by bep** [comment]
I doubt it, but it is impossible to say without context. But it looks like a question, and since we are so understaffed here, I'll delegate to the forum whenever I can.

**Comment by afandian** [comment]
Sorry for hassling you. It was only happening for one file and I've deleted it now. I'll ask the forum it if happens again.
