### ISSUE TITLE
Iterating over items in a taxonomy does not always work

### ISSUE THREAD

**Issue by gkiagia** [spf13/hugo#2323]
I'm developing a site where I want to range over the items of a taxonomy inside a shortcode like normal:
`{{ range $key, $taxonomy := $.Site.Taxonomies.categories }}`

I'm including this shortcode in a markdown file, and it works, but with a catch...
* When generating static html files by runing `hugo`, this range prints nothing, as if there are no items in the taxonomy
* When running `hugo server`, this range also generates nothing initially, but it will generate properly the content as soon as I modify the shortcode .html file (adding a whitespace character is enough) while `hugo server` is running. After restarting it, it's of course not generating anything again.

This makes the whole feature unusable for production.
I'm using hugo 0.16.

**Comment by bep** [comment]
This isn't currently supported and discussed elsewhere. I'm currently working on some improvements in this are. I'm pretty sure we have several similar issues, so I'll close this.

On a foot note, this isn't the core use case of a shortcode. Do this in a template.

**Comment by bep** [comment]
It will be fixed as part of https://github.com/spf13/hugo/issues/2309

**Comment by bep** [comment]
I'll reopen and close it with my fix.
