### ISSUE TITLE
Paginator-generated /page/1/index.html is invalid HTML.

### ISSUE THREAD

**Issue by middling** [spf13/hugo#2324]
The auto-refresh page generated by the paginator does not validate.

The issues are:

* Missing `<title>` element
* In the `<meta http-equiv="refresh">` element `0;url=` should be `0; url=` (space between `;` and `url`)

**Comment by bep** [comment]
What validator do you use?

https://validator.w3.org/nu/?doc=http%3A%2F%2Fbepsays.com%2Fside%2F1%2F

It valdates fine at w3.org.

**Comment by middling** [comment]
Looks like it's already [been fixed](https://github.com/spf13/hugo/commit/5d3aabcb32f33715eddb378f12541c7c412ee261) in the dev version (i'm using 0.16 release).

Sorry about reporting it.

**Comment by bep** [comment]
No problem, thanks for letting us know.
