### ISSUE TITLE
Generate non html files (xml)

### ISSUE THREAD

**Issue by stou** [spf13/hugo#233]
Hi I consider using hugo for maintaining java helpset files.

Generation of the html files in the desired structure works like a charm.
My question is Is it possible to generate other filetypes using the meta data specified in the front matter, inside the markdown files. e.g. to produce the xml files required by the helpset compilation.
### Example content

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE index PUBLIC "-//Sun Microsystems Inc.//DTD JavaHelp Index Version 2.0//EN" "http://java.sun.com/products/javahelp/index_2_0.dtd">
<index version="2.0">
<indexitem text="My title of chapter 1" target="com.example.app.chapter1" />
<indexitem text="My title of chapter 2" target="com.example.app.chapter2" />
</index>
```

Of course I could just put the xml files in the static folder, but my idea was to avoid maintaining titles and package id's both in the front matter and in the related xml files.

**Comment by vimdude** [comment]
xml works fine for me if I don't provide layouts. So if you remove layouts directory and themes, you will not get any html files.

**Comment by bep** [comment]
Duplicates https://github.com/spf13/hugo/issues/2828
