### ISSUE TITLE
unable to download  gopkg.in/gcfg.v1

### ISSUE THREAD

**Issue by pkhadka56** [spf13/hugo#2330]
# go get -u -v gopkg.in/gcfg.v1
Fetching https://gopkg.in/gcfg.v1?go-get=1
Parsing meta tags from https://gopkg.in/gcfg.v1?go-get=1 (status code 200)
get "gopkg.in/gcfg.v1": found meta tag main.metaImport{Prefix:"gopkg.in/gcfg.v1", VCS:"git", RepoRoot:"https://gopkg.in/gcfg.v1"} at https://gopkg.in/gcfg.v1?go-get=1
gopkg.in/gcfg.v1 (download)

My real problem was downloading another but it also stuck here:

# go get -u -v github.com/paulstuart/influxsnmp
github.com/paulstuart/influxsnmp (download)
github.com/influxdata/influxdb (download)
github.com/kardianos/osext (download)
github.com/paulstuart/snmputil (download)
github.com/hashicorp/go-immutable-radix (download)
github.com/hashicorp/golang-lru (download)
github.com/pkg/errors (download)
github.com/soniah/gosnmp (download)
Fetching https://gopkg.in/gcfg.v1?go-get=1
Parsing meta tags from https://gopkg.in/gcfg.v1?go-get=1 (status code 200)
get "gopkg.in/gcfg.v1": found meta tag main.metaImport{Prefix:"gopkg.in/gcfg.v1", VCS:"git", RepoRoot:"https://gopkg.in/gcfg.v1"} at https://gopkg.in/gcfg.v1?go-get=1
gopkg.in/gcfg.v1 (download)

Any help?

**Comment by bep** [comment]
I suspect you have come to the wrong project. None of the above ring any bells or relevance to Hugo.

**Comment by pkhadka56** [comment]
ooppss moving to https://github.com/golang/go/issues/16613
