### ISSUE TITLE
parse emoji patters in pages as well

### ISSUE THREAD

**Issue by anaderi** [spf13/hugo#2342]
seems like enableEmoji only affects posts, but not pages. Would be good to enable emoji for pages as well.

**Comment by bep** [comment]
What exactly do you mean by "pages"?

**Comment by anaderi** [comment]
as I add emoji to a file created by `hugo new post/title`, it renders correctly. 
It is not the case as I add it to a page created by `hugo new page/title`.

**Comment by thiagomgd** [comment]
Did you test it with the exact same surrounding text?
Check this issue (and related PR) to see if it solves your problem #2391
