### ISSUE TITLE
Atom.xml not respecting `baseurl` when using `server` option

### ISSUE THREAD

**Issue by gglanzani** [spf13/hugo#2348]
When I'm generating the site with `hugo server`, the `atom.xml` uses and thus contains `localhost:1313/...` as baseurl (see here as well: https://github.com/spf13/hugo/issues/1147#issuecomment-148748730).

However, when generating the website with `hugo`, the correct `baseurl` is used.

If extra info is needed, let me know. If this is intended behavior, feel free to close it.

**Comment by bep** [comment]
The hugo server is mainly meant for development, and the defaults are geared towards that. 

If you want it to respect the baseURL you have to add it via the command line:

```
hugo server --baseUrl=http://mydomain.com
```
