### ISSUE TITLE
'hugo help' command undocumented in --help output

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/hugo#2349]
The final line printed by `hugo help` is:

> Use "hugo [command] --help" for more information about a command.

(`hugo --help` prints the same, BTW.)

Typing `hugo help new` (for example) works fine.

Typing `hugo new --help` also works. (That's natural, since `hugo --help` recommends it.)

The command `hugo help` is undocumented, in the sense that `help` isn't included in the list of `Available Commands` printed by `hugo --help`.

Generally speaking, new users can feel "lost in a thicket" of new syntax. To help promote Hugo to new users, IMO `hugo help` should be included as an `Available Command`.

Some of the discussion in [this Cobra PR](https://github.com/spf13/cobra/pull/32) seems relevant.

**Comment by traveller42** [comment]
This appears to be the opposite situation, but I agree `help` should be in the Available Commands list as it *is* an available command.

I'm looking for the right place to make this change right now, but I think I need to understand Cobra better.

**Comment by MarkDBlackwell** [comment]
The second option (adding to Cobra "the ability to include help in the Available Commands list") seems more useful in the long run (of course)—especially for other Cobra users.

> If the only subcommand is Help [BTW, this case is irrelevant to Hugo], then don't display Available Commands at all. Otherwise, [Help] should be included in the list.

> This seems like the ideal behavior for Cobra, and fits exactly with the Unix tool philosophy, as well as the subcommand philosophy.

Part of the first comment above can be rephrased as follows:

"If other subcommands join Help, then Help should be included in the list of Available Commands."

The location of Steve Francia's [above](https://github.com/spf13/cobra/pull/32#issuecomment-72347180) two [comments](https://github.com/spf13/cobra/pull/32#issuecomment-72484151) (i.e., in the Cobra repository) also seems to imply he prefers the second option (implementing this in Cobra).

**Comment by MarkDBlackwell** [comment]
@traveller42 the second option (adding to Cobra "the ability to include help in the Available Commands list") seems more useful in the long run (of course)—especially for other Cobra users.

> If the only subcommand is Help [BTW, this case is irrelevant to Hugo], then don't display Available Commands at all. Otherwise, [Help] should be included in the list.

> This seems like the ideal behavior for Cobra, and fits exactly with the Unix tool philosophy, as well as the subcommand philosophy.

Part of the first comment above can be rephrased as follows:

"If other subcommands join Help, then Help should be included in the list of Available Commands."

The location of Steve Francia's [above](https://github.com/spf13/cobra/pull/32#issuecomment-72347180) two [comments](https://github.com/spf13/cobra/pull/32#issuecomment-72484151) (i.e., in the Cobra repository) also seems to imply he prefers the second option (implementing this in Cobra).

**Comment by bogem** [comment]
Fixed in https://github.com/spf13/cobra/pull/394

**Comment by bogem** [comment]
@bep sorry for bothering you, but https://github.com/spf13/hugo/commit/b7a672fd22794ea7c32a958739c6b12aba5dadf8 didn't actually fix this issue. `govendor` didn't update it correctly. 
As you can see revision time is 2017-02-23, but fix is merged on 1st March.
I tried to make PR and update it by myself, but `govendor` always updates `vendor.json` to commit of newest PR to cobra, so I didn't figure out, how to use it :(
