### ISSUE TITLE
.Data.Pages not accessible inside of _default/single.html???

### ISSUE THREAD

**Issue by xDinomode** [spf13/hugo#2355]
I created a partial navbar.html that uses .Data.Pages to link to all main pages (about, contact..), but it doesn't print anything out inside of _deafault/single.html. I'm guessing this variable isn't accessible inside of singles only lists or homepage...  How do I access them if I can't use .Data.Pages?

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions.
