### ISSUE TITLE
TestShortcodeTweet accesses network

### ISSUE THREAD

**Issue by moorereason** [spf13/hugo#2359]
See https://discuss.gohugo.io/t/hugos-twitter-shortcode-test-accesses-the-actual-internet

**Comment by bep** [comment]
Fixed by https://github.com/spf13/hugo/commit/f6d4801ba488e34f898906d3d8b6757dc0f2b13e

**Comment by moorereason** [comment]
@bep, I'm working on a real fix.

**Comment by bep** [comment]
And my fix was ... unreal?
