### ISSUE TITLE
Improve documentation for block templates

### ISSUE THREAD

**Issue by juh2** [spf13/hugo#2363]
The documentation of block templates starts with a link to https://gohugo.io/templates/ace/ which contains a hint to the naming convention of block templates.

Please insert the naming convention of block templates (baseof.html) in this chapter. Many readers won't consult the ace documentation before using block templating. 

https://github.com/spf13/hugo/blob/master/docs/content/templates/blocks.md

**Comment by bep** [comment]
Wouldn't it be easier to just fix the documentation and create a PR?

**Comment by juh2** [comment]
Generally you're right, but I am far from understanding the mechanism. I guessed it from a question on discuss.gohugo.io. 

I'll dive into it so if the issue is still open when I think I know what I am talking about, I'll make a PR.

**Comment by irwinsol** [comment]
Took me awhile to figure this out too. Had to reverse-engineer "hugo-alabaster-theme" since that was the only Hugo theme that had an example of the implementation. Would be happy to collaborate on this.
