### ISSUE TITLE
tpl: Expose funcMap as FuncMap

### ISSUE THREAD

**Issue by buro9** [spf13/hugo#2364]
Hugo has the best template funcmap that I've seen and to be able to use it in any other Go project I'm faced with either:

1. Fork Hugo, change visibility of funcMap to FuncMap, vendor forked Hugo
2. Copy the bits of the funcMap I need, attempt to ensure all licenses and credits are copied, maintenance nightmare
3. Ask if Hugo would consider just changing the visibility of funcMap
4. Extract tpl into it's own project to supply improved templating and functions to all Go projects

I'm thinking option 3 is the most trivial for now and achieves the goal. The license already permits the code re-use, but the default unexposed visibility does not. This change would be just to make the code follow the spirit of the license.

PS: My usage scenario is that I'm porting a Django project to Go and need a few simple functions within my templates, and whether it's `dfault` or `in` Hugo has the best so it makes sense to use these.

**Comment by bep** [comment]
We're not exporting funcMap. We want as a small external API to Hugo as possible. Hugo is a lot of things, it is not a "library for template funcs". Many of them are special to Hugo, and we want the liberty change them at will without having to consider breaking other peoples' apps.

**Comment by moorereason** [comment]
bep is right, so don't complain if your code breaks.  However, you can already do what you want by looking up the underlying `html.Template` object (which also doesn't export it's FuncMap, btw).

```go
myFuncMap := template.FuncMap{...}
templ := tpl.New()
templ.Lookup("").Funcs(myFuncMap)
```
