### ISSUE TITLE
Update docs to show class param in youtube and vimeo shortcodes

### ISSUE THREAD

**Issue by irwinsol** [spf13/hugo#2366]
Wrappers for built-in Hugo shortcodes like Vimeo, Youtube, Gist, and so forth have no div class at the outer most wrapper to identify it as a specific default shortcode. This poses a problem when a user may need to slightly adjust the presentation (i.e: CSS) of a default shortcode but have no particular div unique to that shortcode to call.

For example, when I want to adjust the size of Vimeo or Youtube videos for a theme, I have no control over editing the Vimeo shortcode over Youtube. My best solution is overriding the shortcode template in layouts/shortcode (despite almost adequate implementation with the default shortcode), when all I needed was to adjust width and height.

**Comment by moorereason** [comment]
There's already a div.  Some of the embedded shortcodes (including Youtube and Vimeo) allow you to pass in a `class` name to override the `style` attribute.
```
{{< youtube id="w7Ft2ymGmfc" class="css-class" >}}
{{< youtube w7Ft2ymGmfc css-class >}}
```
We should probably update the docs to point that out.

**Comment by irwinsol** [comment]
@moorereason I see that docs now that the Vimeo one definitely has a default div class:

`<div class="{{ if .Get "class" }}{{ .Get "class" }}{{ else }}vimeo-container{{ end }}">`

 but when I use the default shortcode with the ID parameter I don't get the "vimeo-container" wrapper. Where can I get a view of the templating for the default shortcodes?

**Comment by moorereason** [comment]
What version of Hugo are you using?

**Comment by irwinsol** [comment]
@moorereason v0.16

**Comment by moorereason** [comment]
@irwinsol, v0.16 should work as I described.  The embedded vimeo shortcode for v0.16 is here: https://github.com/spf13/hugo/blob/v0.16.docs/tpl/template_embedded.go#L54-L60.

Make sure you're not using a theme that has it's own vimeo shortcode defined.

Please continue this discussion in the forums.  If it turns out to be a bug, we can reopen this issue.

**Comment by irwinsol** [comment]
@moorereason There is still a discrepancy between the description of the Vimeo shortcode in the docs and the internal shortcode implementation you linked.  The shortcode in the docs contains a "vimeo-container" div wrapper, whereas the implementation in 0.16 does not.

Hugo documentation example:
```go
{{ if .IsNamedParams }}
  <div class="{{ if .Get "class" }}{{ .Get "class" }}{{ else }}vimeo-container{{ end }}">
    <iframe src="//player.vimeo.com/video/{{ .Get "id" }}" allowfullscreen></iframe>
  </div>
{{ else }}
  <div class="{{ if len .Params | eq 2 }}{{ .Get 1 }}{{ else }}vimeo-container{{ end }}">
    <iframe src="//player.vimeo.com/video/{{ .Get 0 }}" allowfullscreen></iframe>
  </div>
{{ end }}
```

0.16 Implementation:
```go
t.AddInternalShortcode("vimeo.html", `{{ if .IsNamedParams }}<div {{ if .Get "class" }}class="{{ .Get "class" }}"{{ else }}style="position: relative; padding-bottom: 56.25%; padding-top: 30px; height: 0; overflow: hidden;"{{ end }}>
  <iframe src="//player.vimeo.com/video/{{ .Get "id" }}" {{ if not (.Get "class") }}style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" {{ end }}webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
 </div>{{ else }}
<div {{ if len .Params | eq 2 }}class="{{ .Get 1 }}"{{ else }}style="position: relative; padding-bottom: 56.25%; padding-top: 30px; height: 0; overflow: hidden;"{{ end }}>
  <iframe src="//player.vimeo.com/video/{{ .Get 0 }}" {{ if len .Params | eq 1 }}style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" {{ end }}webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
 </div>
{{ end }}`)
```

**Comment by moorereason** [comment]
Thanks for the clarification, @irwinsol.

**Comment by wholien** [comment]
@moorereason How can I help on this issue? Would just adding a `vimeo-container` to the implementation suffice?

**Comment by rdwatters** [comment]
@moorereason @wholien 

Both video SCs have more extensive explanations in the new docs:

https://hugodocs.info/content-management/shortcodes/#vimeo
