### ISSUE TITLE
docs: documentation site sidebar vertical scrollbox fails, sometimes

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/hugo#2373]
The vertical scrolling of the [documentation site](http://gohugo.io/)'s (left) sidebar displays some peculiar behavior:
1. The top vertical scroll button is invisible.
2. When certain leaves are selected, both the vertical scroll bar and the bottom vertical scroll button don't work as expected, but instead cause the selection to jump to the previous leaf (and load that page). The peculiar leaves run:
   - From "Getting Started ->Quickstart" down through "Tutorials ->Multilingual Site" (the last leaf of "Tutorials").
3. However, when certain other leaves are selected, the vertical scroll functionality works normally. The normal leaves run:
   - From "About Hugo ->Release Notes" at the top down through "Getting Started ->Introduction" near the middle; and
   - From "Troubleshooting ->Troubleshooting Overview" near the middle down through "Troubleshooting ->Accented Categories" at the bottom.

Possibly interesting and relevant is the fact that the first-failing leaf "Getting Started ->Quickstart" isn't the first leaf of "Getting Started", but its second.

I observed this behavior in (maximized) Firefox and Opera windows with screen resolution 1440 by 900 pixels (on Microsoft Windows).

Possibly related to #363.

**Comment by MarkDBlackwell** [comment]
I observed the same problem on Linux in a maximized Chromium browser window.

If a document displays a certain graphic, then it seems to have the problem — otherwise not.

The particular graphic is the less-than sign `<` (on the left side, at the beginning) which causes the browser to navigate upwards by one document (as usual).

If a document is long enough, and its beginning has the problem, then its end won't.

I'm thinking it may be a CSS or bounding box problem on that `<` graphic.

**Comment by digitalcraftsman** [comment]
This issue will become irrelevant once the new redesign of @budparr will be deployed. Shall we close it then?
