### ISSUE TITLE
In docs add example usage of {{- -}}

### ISSUE THREAD

**Issue by anagio** [spf13/hugo#2380]
Output from `{{ }}` often returns white space and new lines in templates which may also end up being URL encoded and break layouts.

The function section of the docs should include usage examples of `{{- -}}` which trims white space, and new lines from rendering in HTML

Additional info at https://github.com/golang/go/commit/e6ee26a03b79d0e8b658463bdb29349ca68e1460

**Comment by digitalcraftsman** [comment]
Look here: http://gohugo.io/templates/go-templates/#whitespace
