### ISSUE TITLE
Script in markdown document gets wrong encoding

### ISSUE THREAD

**Issue by snapo** [spf13/hugo#2385]
I am referencing to this post https://discuss.gohugo.io/t/javascript-in-blogpost-but-not-on-all-sites-at-the-same-time/3978/2

To test it i created a test.md document

```
+++
title = "hugo encoding test"
description = "this is a test"
tags = [ "hugo", "test", "encoding" ]
date = "2016-04-06"
slug = "blah test"
+++
This is normal Text parsed by hugo
# titel parsed by hugo

<canvas id="myCanvas" width="200" height="100" style="border:1px solid #d3d3d3;">
Your browser does not support the HTML5 canvas tag.</canvas>

<script>
var c = document.getElementById("myCanvas");
var ctx = c.getContext("2d");
ctx.font = "30px Arial";
ctx.fillText("Hello World",10,50);
</script>

another normal text parsed by hugo
## test
```

more text blahblah

if you try to render this, at first it seems everything works... but then you notice that the encoding of the javascript is broken and you get &lsquo; instead of the "

I did test it with the following encoding inputs:

UTF8
UTF8-without-BOM
Win1252

Nothing did work... First is this a normal behavior or a bug?

If this is not a bug, could we implement a feature request for 1:1 parsing between a start and end tag?

{{ HUGODONTRENDER }}
Mycode
{{ /HUGODONTRENDER}}

im very often testing javascript files , and it would be (for example if you blog about something) very helpful to just have this javascript called once and not everytime all javascripts that we test.

**Comment by bep** [comment]
I suspect you have to use a div block around your script tag, optionally use a shortcode.

As to the 1:1 parsing feature request, whatever that means, I think not. Please use the forum for questions.
