### ISSUE TITLE
Development server doesn't regenerate list pages ordered `ByWeight`

### ISSUE THREAD

**Issue by chrisguidry** [spf13/hugo#2396]
To reproduce:
1. Have some content in `content/` with various `weight` attributes to control the ordering
2. Have this in `index.html`:

```
<ol>
    {{ range .Data.Pages.ByWeight }}
    <p class="{{ .Type }}">{{ .Content }}</p>
    {{ end }}
</ol>
```
1. Run the hugo development server with normal watching enabled
2. Render the page, confirm that things are in order by weight
3. Edit a content file to adjust it's body, save
4. Confirm in the console that hugo did detect the change
5. Confirm in the browser that live-reload triggered
6. BUG: the body of the item you changed won't have updated
7. Stop and restart the dev server; confirm that the body of the content is now reflecting the update

If you change this to `{{ range .Data.Pages }}` things work exactly as expected.  It's like the `ByWeight` filtered results are cached in-memory and won't clear until you restart the server.

(PS: I LOVE LOVE LOVE Hugo)

**Comment by 5d-cornelius** [comment]
I've just encountered the same problem with sorting "ByTitle". (Hugo 0.17)

**Comment by bep** [comment]
This is fixed.
