### ISSUE TITLE
Better info message when rendering Asciidoc

### ISSUE THREAD

**Issue by essen** [spf13/hugo#2399]
Hugo Static Site Generator v0.16 BuildDate: 2016-08-30T11:56:44+02:00

Sometimes Asciidoc errors out without any output. The problem is that Hugo does not tell us which file it is rendering, so finding where the error happens can be difficult:

```
INFO: 2016/08/30 12:40:44 content.go:476: Rendering with /usr/bin/asciidoc ...
ERROR: 2016/08/30 12:40:44 content.go:482: exit status 1
```

The verbose flags don't seem to help.

**Comment by choeppler** [comment]
In #2567 there is a partial solution in that the errors in asciidoc / asciidoctor's stderr would now be reported by hugo:
```
Started building sites ...
ERROR: 2016/10/13 07:30:53 content.go:558: asciidoctor: ERROR: <stdin>: line 139: mismatched macro: endif::backen-docbook[], expected endif::backend-docbook[]
Built site for language en:
<snip/>
```
As the source filename is not available in the function `getAsciidocContent` which hands over the file contents to asciidoc / asciidoctor via stdin, reporting of which file is being rendered is still missing.
AFAICT -- being on a hacktoberfest stroll, I'm both very new to the used technology and hugo's codebase... -- the last place in the call stack where that information is still readily available is `commonConvert` in hugolib/handler_page.go. However, adding a log message there about which page is about to be converted obviously does not help much if more than one file is being converted concurrently and the log messages start to get interleaved. 
Thoughts?
