### ISSUE TITLE
Lists render problem

### ISSUE THREAD

**Issue by k0pernicus** [spf13/hugo#2405]
Hi,
I don't know if this problem concerns directly Hugo or not, but I have a problem to have a correct render on lists.

Actually, the following Markdown code is inlining via Hugo:
```
This is my list:
*  Hello,
*  World!
```

Is there a problem in a Hugo library or something?

**Comment by k0pernicus** [comment]
I tried to had some spaces after `list:` but it doesn't change the render...
The only thing that works to render the list correctly after the title is to add two newlines, but the list is so far than the title now...

**Comment by thiagomgd** [comment]
As far as I know, you are supposed to have an empty line before and after the list.

```
List:

* Hey
* Hi

See the list above?
```

The list being far from the title is another thing. What's the html generated? It's probably your theme's CSS doing this.

**Comment by k0pernicus** [comment]
Oh ok - my bad for this thing so...  
I am using `ghostwriter`.

**Comment by thiagomgd** [comment]
Is you result similar to the example below?

http://themes.gohugo.io/theme/ghostwriter/2014/04/02/hugoisforlovers/

![image](https://cloud.githubusercontent.com/assets/12170252/18167774/cc99da20-7028-11e6-810d-b08fc199cfdc.png)

If yes, just change the margins on your css :)

**Comment by k0pernicus** [comment]
Thanks @thiagomgd, saved my day! :-D

👍

**Comment by thiagomgd** [comment]
You're welcome!
