### ISSUE TITLE
tpl: echoParam doesn't support interface map values

### ISSUE THREAD

**Issue by moorereason** [spf13/hugo#2406]
### Test Case
Something like this:

```go
{map[string]interface{}{"foo": 1, "bar": 2, "baz": 3}, "bar", 2},
```

### Reproducing The Issue
Given this site config:

```toml
[params]
langCode = "en"
```
and template usage:

```
{{ echoParam .Site.Params "langCode" }}
```
Expect to see `en` as output, but get empty string.

Reported here:  https://discuss.gohugo.io/t/how-can-i-get-echoparam-to-work/3801

Updated(2016.09.01): fixed typo in template usage example.

**Comment by bep** [comment]
>{{ echoParam ".Site.Params" "langCode" }}

That is not the signature of `echoParam`.

**Comment by moorereason** [comment]
Oops.  Fixed my typo.  Thanks
