### ISSUE TITLE
Category casing issues

### ISSUE THREAD

**Issue by joostfarla** [spf13/hugo#2408]
When using categories, the casing seems to get lost on the terms/taxonomy pages:

* On the `terms.html` page, I would like to show the original form of the category name, including the original casing. It now seems to auto-convert to the urlized "kebab-cased" form when rendering `{{ $value.Name }}`. Example: `API Design` becomes `api-design`.

* On the `taxonomy.html` page, I would like to show the original form of the category name, including the original casing when rendering `{{ .Title }}`. Example: `API Design` becomes `Api Design`.

**Comment by bep** [comment]
Please ask questions at http://discuss.gohugo.io/
