### ISSUE TITLE
Youtube shortcode processing omits `https:`

### ISSUE THREAD

**Issue by Seanmatthews** [spf13/hugo#2413]
When using youtube shortcode for embedding youtube videos in a page, the resultant html is:

```
<div style="position: relative; padding-bottom: 56.25%; padding-top: 30px; height: 0; overflow: hidden;">
  <iframe src="//www.youtube.com/embed/XXXXXXXXX" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" allowfullscreen frameborder="0"></iframe>
</div>
```

**Comment by moorereason** [comment]
That's a feature.  Your browser will use whichever protocol your site is using.

**Comment by Seanmatthews** [comment]
Is there a way to alter shortcodes for local testing-- when the browser is opening a local html file? At least in that case, the Chrome browser does not seem to fill it in.

**Comment by felicianotech** [comment]
@Seanmatthews Run a web server locally. Then, use `localhost://` as the host and it will work. As you said, opening a local file will lead to `file:///` which causing the links to break :/

**Comment by Seanmatthews** [comment]
Thx.
