### ISSUE TITLE
can't evaluate field Content in type - in index.html of theme

### ISSUE THREAD

**Issue by tchncs** [spf13/hugo#2418]
Hi there i am currently trying to create a page using hugo (surprise).
However, in the `/layouts/index.html` of my theme is the following:

```
{{ partial "header.html" . }}
<body>
    <div class="container">
        {{ partial "navbar.html"  . }}
        <div class="content">
            <h2>{{.Title}}</h2>
            {{.Content}}
        </div>
    </div>
{{ partial "footer.html" . }}
</body>
```
I created two test pages in the main directory, in /content using html files (index.html and test.html).

My issue is: 

```
[...]
WARN: 2016/09/08 17:45:36 site.go:2004: "" is rendered empty
ERROR: 2016/09/08 17:45:36 general.go:212: Error while rendering homepage: template: theme/index.html:7:14: executing "theme/index.html" at <.Content>: can't evaluate field Content in type *hugolib.Node
0 draft content
0 future content
0 expired content
2 pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
in 19 ms
[...]
```
The rendered page is cutted after .Title

I am not sure if i am just doing it wron or if it is an valid issue.
Sorry if i just doing it wrong.

**Comment by digitalcraftsman** [comment]
Please ask questions like these on the [Hugo forum](https://discuss.gohugo.io/); GitHub is used for concrete issues and requests/enhancements.
