### ISSUE TITLE
docs: Special Google Analytics partial file seems redundant

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/hugo#2425]
Since Hugo contains [an internal template](https://github.com/spf13/hugo/pull/1505) for Google Analytics (added in October, 2015), the existence (in the Hugo docs) of a special [partial file for Google Analytics](https://github.com/spf13/hugo/blob/9c5f2befc0818bd14df63b30f96edff14bd10316/docs/layouts/partials/analytics.html) (added in May, 2014) seems redundant—or, basically so. It almost exactly duplicates Hugo's internal template, with two differences:
1. The Google Analytics tracking code is hard-coded; and
2. The third argument (to script `ga` in the template) is `spf13.com`.

The tracking code could be moved to the Hugo docs' [config](https://github.com/spf13/hugo/blob/9c5f2befc0818bd14df63b30f96edff14bd10316/docs/config.toml) file by adding to it the usual `googleAnalytics` variable.

The third argument has remained unchanged from its original value of [`spf13.com`](https://github.com/spf13/hugo/blob/532e2e7b931e852c6c96711ba2e6eaea8911d7b7/docs/layouts/chrome/analytics.html#L7) set in November, 2013, despite the fact that in September, 2014 the Hugo docs [moved](https://github.com/spf13/hugo/commit/bf980bc13814b2eda7c5ed2b258c059747f801c3#diff-9eeff327a6e03d2bf2ac9a555745cbf2L1) (from `http://hugo.spf13.com` to `http://gohugo.io`). BTW, a [search](http://stackoverflow.com/questions/tagged/google-analytics+github-pages) confirmed that Google Analytics generally works on Github Pages.

If the third argument is best kept as it is (or changed to `auto`), then its configurability (in a new variable in `config.toml` if different from `baseurl`), since useful to the Hugo docs, presumably also would be useful to some of Hugo's users on their own sites.

If the third argument is best changed to `gohugo.io` then, for the Hugo docs, the present default value as calculated in Hugo's internal Google analytics partial (i.e., the value of `baseurl`) would work.

Then, seemingly, either way would enable Hugo to:
1. Drop the Hugo docs file [`layouts/partials/analytics.html`](https://github.com/spf13/hugo/blob/9c5f2befc0818bd14df63b30f96edff14bd10316/docs/layouts/partials/analytics.html); and
2. Provide the Hugo docs themselves as an example of how to use the internal Google analytics template.

Just to confirm, should the third argument indeed be `spf13.com`? or should it change to `gohugo.io`?

If a new, "`ga` third argument" configuration variable is desirable, what should its name be?

**Comment by digitalcraftsman** [comment]
This issue becomes irrelevant with @rdwatters revision of the docs.
