### ISSUE TITLE
benchmark: add --benchmem flag to benchmark command

### ISSUE THREAD

**Issue by bogem** [spf13/hugo#2432]
I want to see, how many memory `hugo` consumes in the same way as `go test -bench=. --benchmem` do.

**Comment by bep** [comment]
Use http://discuss.gohugo.io/ for questions.

**Comment by bogem** [comment]
But it's not the question, it's feature request: it would be great to add `--benchmem` flag to `benchmark` command🙏

**Comment by bep** [comment]
Yes, we should maybe refit that command to a Go benchmark ...

Also see https://github.com/bep/hugo-benchmark

**Comment by bogem** [comment]
I think, it could be implemented like that:
```go
var mem runtime.MemStats
runtime.ReadMemStats(&mem)
before := mem.Alloc
// operations...
runtime.ReadMemStats(&mem)
after := mem.Alloc

memUsage := after - before
// print memUsage
```
