### ISSUE TITLE
absLangURL adds language prefix when already present

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2444]
I use the template func `absLangURL` [to link menu](https://github.com/digitalcraftsman/hugo-multilingual/commit/b08a7da1268b3e7ae8bf101e7aef26d6b0ddb61b) items with the correct language prefix in the url.

In the German version `/` links as expected to `/de`. But I if I add links to content pages via their frontmatter in the menu (look at the [about page](https://raw.githubusercontent.com/digitalcraftsman/hugo-multilingual/master/content/about.de.md)) the language prefix is added twice.

The menu entry for the German about page links to `/de/de/about` instead of `/de/about`

**Comment by bep** [comment]
I will have to think about this, it may lead to some false positives trying to detect if prefix is already there. Your workaround in this case is to use the `absURL` func. Feel free to fix this yourself if you can suggest a bullet proof way.
