### ISSUE TITLE
absLangURL has no effect on base the url

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2445]
Scenario: the site name or logo in the header should link [link to the homepage](https://github.com/digitalcraftsman/hugo-multilingual/commit/a3f972b20c1cfc6c70692f35a71e9be53ee0e9d9) of the corresponding language. The German version links to `/` instead of `/de`.

It would also be nice if I don't have to convert the base url into a string before piping it to absLangURL.

**Comment by bep** [comment]
I assume the `baseURL` is absolute already, and then this is by design -- I do not touch absolute URLs. The trick here is do do something ala `absLangURL "/"`.
