### ISSUE TITLE
Can a parent shortcode defer output of rendered Inner content?

### ISSUE THREAD

**Issue by marfarma** [spf13/hugo#2448]
I need markup at the top of an outer shortcode template that depends on .Inner shortcodes having been parsed, but not yet rendered.  I.e. (an extremely simplified example):

    // in content.md
    {{< outer-thing-container id="x">}}
  
    {{< inner-thing id="first-inner-thing" >}}
    {{< inner-thing id="second-inner-thing" >}}
    {{< inner-thing id="nth-inner-thing" >}}

    {{< /outer-thing-container >}}

    // in shortcodes/outer-thing-container.html
    {{.Parent.Scratch.set innerCounter 0}}
    {{.Scratch.set deferred-rendered-inner = Render(.Inner)}}
    <div name="x" id="x">
      <p>there are {{.Scratch.innerCounter}} things in my container, and here they are: </p>
      {{Scratch.deferred-Rendered-Inner}}
    </div>

    // in shortcodes/inner-thing.html
    {{.Parent.Scratch.add innerCounter 1}}
    <p>  The inner-thing template .... </p>

I can't see anyway to do it.  Did I miss something?

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions. And I would try to describe *what* and not *how*.
