### ISSUE TITLE
Make paginate settings configurable per language

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2449]
The default paginate path is "page". I would like to [translate this part of the url as well](https://github.com/digitalcraftsman/hugo-multilingual/commit/bac433462fe8add66ce6c3a1aa0244cfbb661714). But setting a different paginate path for a translation has no effect. Hugo still refers to the "global" setting.

**Comment by bep** [comment]
This is "as designed". It may be fixed in the future, but not for 0.17. Or: Not by me.
