### ISSUE TITLE
Language is prefixed in URL when set manually in frontmatter

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2450]
The `url` attribute allows users to specify a custom url on the frontmatter. Currently, the German about page is accessible under `/de/about`.[ I would like to change it to `/de/über-mich`](https://github.com/digitalcraftsman/hugo-multilingual/commit/0d4cbcb584cf52a70829b2cdaf5586f3b6cfa647).

The page is linked correctly in the menu but no page is rendered at `/de/über-mich`, which results in a 404 error. Hugo renders the about page still under `/de/about`.

**Comment by bep** [comment]
Is this introduced in 0.17? If not, add it to the future milestone.

**Comment by bep** [comment]
There is an issue here, but not the one you describe (your TOML is misconfigured). In my head the `url` in front matter is something we need to take literally (as in my example on the disussion forum with the JSON search index). So if you really want it at `/de/über-mich`, set `url= "/de/über-mich./de/über-mich"`. 

But there is an issue with `URL`, which has a prefix it shouldn't have (the `Permalink` seems to be correct).

If you agree, please correct the description of this issue.

**Comment by digitalcraftsman** [comment]
> There is an issue here, but not the one you describe (your TOML is misconfigured).

This is good to know. Otherwise the mistake isn't very obvious.

> In my head the url in front matter is something we need to take literally

This depends on how we define the behavior of url. Then I have no issue with the language independency. Users just have remind themselves to update it once the language prefix changes.

In conclusion: this issue isn't an issue. We can close it. Unless you want to use it for bug with `URL`.

**Comment by bep** [comment]
>In conclusion: this issue isn't an issue. We can close it. Unless you want to use it for bug with URL.

Lets use this for the URL. And please shout if my thinking is wrong on this; but I don't see how the `url` setting can stay really flexible if we prepend stuff to it. I think most people use `slug` etc. to create custom base URLs.

**Comment by digitalcraftsman** [comment]
I didn't thought about `slug`. It fits my needs much better because users don't have to set the language prefix manually. After it is nonsense to prepend something to `url`.

**Comment by moorereason** [comment]
My understanding of `url` matches @bep's.  However, we should clarify the docs around `url` to make it clear that it overrides the `slug` and any calculated URLs (which is only translation URLs right now).  An `alias` works is a similar fashion.

**Comment by digitalcraftsman** [comment]
I added more information about the difference in 742911146a24a0c39e4dcc516583fe5ed5567fa2.
