### ISSUE TITLE
i18n: return empty string by default when no match

### ISSUE THREAD

**Issue by mitchchn** [spf13/hugo#2451]
If `i18n` finds no matches, it should return a nil value (empty string?) instead of the string "[i18n] %s". 

It could also simply return the identifier, but a nil value is idiomatic go and would let us check if  a match exists in template code, e.g. `{{ with i18n "some_identifier" }}`.

**Comment by bep** [comment]
Why would you not provide translations for all strings? I think the `i18n` placeholders provide a nice visual to indicate the progress of the translation process.

And it is not like we can turn this off with a flag, either (which will confuse themes), so unless you provide some other arguments than the mere technical ones ...

**Comment by mitchchn** [comment]
In practice, translations lag. On a large project you have multiple translators who are all catching up to the main site, which is a moving target.

Hugo allows for this by not requiring all content to be translated at once. It's simple to create a site which checks for translated content and handles the lack of it gracefully.

Strings are currently an exception; you get undefined behaviour like this if not all strings are translated in all languages. Hugo should accommodate for untranslated strings just like it does for untranslated content.

**Comment by bep** [comment]
OK, let other chime in with their "votes" ...

**Comment by digitalcraftsman** [comment]
On the one hand a visual indicator makes it easy for developers to notice this issue. On the other hand I can understand that it isn't a good sign if the identifier of a missing translation shows up in a production system (unless it was catched by the default translation).

How does the workflow of your colleagues look like? 

There is an `--i18n-warnings` flag that be used while translating your website. Isn't this sufficient? Users should always have a look at the console before merging any changes. If you use a deployment system you could integrate a check that catches the i18n-warnings.

But this are just my two cents.

**Comment by mitchchn** [comment]
> How does the workflow of your colleagues look like?

Changes are regularly made to the English site. Individual translators work on their own pace to catch up. The site can't be blocked waiting for every translator to respond to every single change, so warnings would not help. In other words, we don't consider it an error state for the site to be partially translated.

This workflow is already supported for _content_ in Hugo. There are functions to test for available translations, and there is no assumption that all content is represented in all languages. The docs even have an example of a language switcher which only shows available translations. (It doesn't replace the missing ones with a user-facing message!)

> It will not print anything if there are no translations for a given page, or if it is – in the case of the home page, section listing etc. – a site with only one language.

So this strikes me as an inconsistency: you can guard against untranslated content, but not untranslated strings.

**Comment by digitalcraftsman** [comment]
If you've to keep moving then it's the best approach to just return nil instead of the indicator. A (partially) translated website either shows the correct translation, the default one or nothing.

As a best practice I would always use the `i18n-warnings` flag to catch as much errors as possible. I think that this decision still statisfies most users. Alternatively, those who use continous integration services could `grep` the standard output to find missing translations and handle them as they like.

**Comment by bep** [comment]
I suggest this:

* Add a flag that enables the current behaviour: `EnableMissingTranslationPlaceholders`, default false.
* If that is not set, return ""

But this need to come in form of a PR from someone other than me. I'm tired of this language stuff.

**Comment by digitalcraftsman** [comment]
I opened a pull request to add this config option.
