### ISSUE TITLE
How to properly capitalize a title in hugo?

### ISSUE THREAD

**Issue by LazyZhu** [spf13/hugo#2455]
For example, i set title as `I love the hugo` in post, but I need it to be `I Love the Hugo`, the related function are `title`, `upper` and `humanize`, but neither of them could achive that.

Updated:
Found a recipe about this:
http://golangcookbook.com/chapters/strings/title/
How to implement this function to hugo?

**Comment by digitalcraftsman** [comment]
Please ask questions like these on the [Hugo forum](https://discuss.gohugo.io/); GitHub is used for concrete issues and requests/enhancements.

**Comment by LazyZhu** [comment]
Obviously you didn't read my post, otherwise you will know this is a issue and need to be fixed.

**Comment by moorereason** [comment]
Two ideas:  use `text-transform: capitalize` in your CSS or solve this in a template by ranging over the words in a string.  Ask in the forums for more help.  We won't be adding a built-in template function for this.

**Comment by LazyZhu** [comment]
The second one that didn't read post.
