### ISSUE TITLE
Add some band-aid to convert

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2458]
See #2439 #2441 

The above needs proper solutions, but we got to postpone those.

A temporary hack would be to:

1) Log and continue on error in `convert`
2) Include panics in 1)

**Comment by moorereason** [comment]
Can you isolate the conversions in wrapper functions to recover from panics?

```go
func marshalYAML(v interface{}) (b []byte, err error) {
    defer func() {
        if r := recover(); r != nil {
            var ok bool
            err, ok = r.(error)
            if !ok {
                err = fmt.Errorf("pkg: %v", r)
            }
        }
    }()
    return yaml.Marshal(v)
}
```

**Comment by bep** [comment]
The recover is implicit in 2) above. I know Go. I taught Steve Go. And now he is on the Go team :-)

**Comment by bep** [comment]
But you are correct, your wrapper func would work.
