### ISSUE TITLE
gohugo.io Domain Expired

### ISSUE THREAD

**Issue by bariman77** [spf13/hugo#2462]
Not sure if this is the correct location but it appears the gohugo.io domain has expired and is no longer resolving.

**Comment by moorereason** [comment]
Cc: @spf13

**Comment by spf13** [comment]
Doh.. I'm on it.

**Comment by spf13** [comment]
renewed it. It will take a bit for the processing to finish, but I've done everything I know needs doing. Should work in a bit again.

**Comment by spf13** [comment]
and we're back up
