### ISSUE TITLE
Taxonomy pagination shows more articles than it should be

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2463]
In my [demo setup](https://github.com/digitalcraftsman/hugo-multilingual) I've have two content files (foo.md and bar.md) that are also translated to German. All are part of the category "Getting started". So, the taxonomy categories should list two content files per language.

I set the `paginate` to force the appearence of the pagination with one page per site. However, on the taxonomy page I can see two articles per site of the pagination (four in total). The pagination contains correctly only the pages of the current locale, but seems to insert them twice.

Pull the latest commits and open [http://localhost:1313/categories/getting-started/](http://localhost:1313/categories/getting-started/).

Sorry to bug you again.

**Comment by bep** [comment]
See referenced commit.
