### ISSUE TITLE
Breaking API-change re Author

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2464]
From my own site:

```
ERROR: 2016/09/17 14:38:27 general.go:212: Error while rendering taxonomy category rss: template: _default/rss.xml:7:54: executing "_default/rss.xml" at <.Site.Author.email>: can't evaluate field Author in type *hugolib.SiteInfo
ERROR: 2016/09/17 14:38:27 general.go:212: Error while rendering taxonomy tag rss: template: _default/rss.xml:7:54: executing "_default/rss.xml" at <.Site.Author.email>: can't evaluate field Author in type *hugolib.SiteInfo
ERROR: 2016/09/17 14:38:27 general.go:212: Error while rendering section post rss: template: _default/rss.xml:7:54: executing "_default/rss.xml" at <.Site.Author.email>: can't evaluate field Author in type *hugolib.SiteInfo
ERROR: 2016/09/17 14:38:27 general.go:212: Error while rendering section page rss: template: _default/rss.xml:7:54: executing "_default/rss.xml" at <.Site.Author.email>: can't evaluate field Author in type *hugolib.SiteInfo
ERROR: 2016/09/17 14:38:27 general.go:212: Error while rendering homepage rss: template: _default/rss.xml:7:54: executing "_default/rss.xml" at <.Site.Author.email>: can't evaluate field Author in type *hugolib.SiteInfo
```

This needs to be fixed.

**Comment by digitalcraftsman** [comment]
We could use the author profiles feature to add a profile for the website. A new config option could be assigned with an identifier of a profile. Now, we have a reference and can insert the information again.

Furthermore, some websites have their own social media accounts that are independent from those of the content creators. This way we could use a profile to link the social media accounts in the footer like we would do with the authors.

**Comment by bep** [comment]
I didn't understand any of that. 

So: Here is what someone should do:

**Add an Authors method to SiteInfo that returns the first author in the sorted site authors list.**

**Comment by moorereason** [comment]
@bep,
Adding a `SiteInfo.Author()` func to return the first Author is good, but the API would still break.  You can't access `Author.email` from the template--it's now `Author.Email`.  The old `SiteInfo.Author` was a map.  The new one is a struct.  The only way to keep from breaking compatibility is to have `SiteInfo.Author()` func return a map.

My vote is to break the API by returning the first Author (as you suggested), and make it clear in the release notes that the `.Site.Author` API has changed.  Authors are no longer maps.

Cc: @derekperkins

**Comment by bep** [comment]
Hmm ...

**Comment by bep** [comment]
```
find themes -name "*.html" | xargs grep "Site.Author" | wc -l
      88
```

We cannot have this kind of breakage in a release. It will flood the discussion forum / GH with questions.

**Comment by bep** [comment]
Om the other hand, I see constructs like  `.Site.Author.twitter`, so breakage will happen one some level ... 

Thinking ...

**Comment by moorereason** [comment]
Release Notes:
```
<blink>NOTICE: The .Site.Author API has changed.</blink>
```
:smile:

**Comment by bep** [comment]
The main problem with this is all the themes. Last time we did something like this we did a deprecation release and created PRs for all the themes ... Even doing that created lots of noise from the users. And that was a LOT of job, and now the themes will just start to break and most users will not be able to do anything to fix it (it is in some other person's theme).

**Comment by bep** [comment]
OK, here is what we're going to do:

1. Add `Site.Author` as a func that returns a map that mimics the old behavior as best as possible. 
2. Add a deprecation message (see helpers.DeprecationLogger or something) that tells the user to migrate to node.Author and that the site method will be gone in 0.18.

**Comment by derekperkins** [comment]
IIRC, `.Site.Authors` was a map and `.Site.Author` was just a single author, so @bep's suggestion to return a single author should work.

**Comment by derekperkins** [comment]
Nope, it was `map[string]interface{}`

**Comment by moorereason** [comment]
@bep,
Do we have to get rid of Site.Author in the long run?  On the returned map, just duplicate the struct fields as map keys.  Tell people to move to the titlecase fields.  The lowercase fields would be deprecated.  In the end, we keep the Site.Author func and have it return Author[0].

```go
{
    "email": "x@a.com",

    "Email": "x@a.com",
    "Social": map[string]interface{}{
       // whatever...
    },
}
```

**Comment by bep** [comment]
>Do we have to get rid of Site.Author in the long run?

We can keep it, but it will have to be replaced wit the Author struct at some point. We can not maintain both as that would be stupid (Author.twitter vs Author.Social.twitter etc). We should figure out a way to support case insentitive struct member access, but that is outside of this dicsussion.

**Comment by derekperkins** [comment]
So the Author object has `Params` as a `map[string]interface{}`, so we could move that data inside there. Is there any way to intercept the `.Site.Author.twitter` call and have it return whatever is in `.Site.Author.Params.twitter`? It seems unlikely since it's map access, but I rarely interact with Go templates, so I figured it'd be worth asking, since that should eliminate any API incompatibilities.

**Comment by moorereason** [comment]
@derekperkins, AFAIK only exported fields/funcs are accessible from the templates.

**Comment by derekperkins** [comment]
Another potential breakage point is `.Site.Authors`, that changed from `map[string]Author` to `[]Author`
![image](https://cloud.githubusercontent.com/assets/3588778/18612930/c8fa8656-7d27-11e6-8fa0-337f6902e83d.png)

**Comment by derekperkins** [comment]
`.Site.Author` isn't referenced anywhere in master right now. I removed the reference to it in the embedded 
https://github.com/spf13/hugo/commit/cf978c06496d99e76b08418422dda5797d90fed6#diff-296ec07d79d440e0b26277b7f38162a1L83

I don't think that variable was getting loaded anywhere either, unless config was loading it automatically. @bep Did you copy out that rss template into a theme? The fallout from losing `.Site.Author` should be almost zero I'd think.

**Comment by moonytheloony** [comment]
I have fallen headfirst into this. My travis builds are failing. What is the workaround to get my blog up and running again?

**Comment by derekperkins** [comment]
@moonytheloony What commit is your build based on?

**Comment by moonytheloony** [comment]
@derekperkins my build script downloads the latest version from github and builds the site.

**Comment by phil-opp** [comment]
@moonytheloony `(.Site.Authors.Get "0").Email` seems to work
