### ISSUE TITLE
Default language at the root with other content inlanguage subfolders.

### ISSUE THREAD

**Issue by pawelurbanski** [spf13/hugo#2487]
I have the following Hugo generated site structure: /en/* for English, /pl/ for Polish.
I would like to have English as default language, Polish as translated content, and keep the default language at the root "/" without redirecting the root site to the subfolder. Since the urls are gnerated based on language and folders, they will be still valid.
Can we keep the default language at the root of the domain?

**Comment by moorereason** [comment]
Please use https://discuss.gohugo.io/ for questions.
