### ISSUE TITLE
safeHTML still escapes "&" inside HTML attributes

### ISSUE THREAD

**Issue by seschwar** [spf13/hugo#2489]
In Hugo 0.16 The following template

    <a href="{{ "&#x0061;" }}">{{ "&#x0061;" }}</a>
    <a href="{{ "&#x0061;" | safeHTML }}">{{ "&#x0061;" | safeHTML }}</a>

renders to

    <a href="&amp;#x0061;">&amp;#x0061;</a>
    <a href="&amp;#x0061;">&#x0061;</a>

Notice the `&amp;` in second line's `href` attribute.

I would expect the template above to be rendered like this:

    <a href="&amp;#x0061;">&amp;#x0061;</a>
    <a href="&#x0061;">&#x0061;</a>

**Comment by bep** [comment]
`safeHTML` doesn't do any escaping. It just marks the text as safe for the Go template parser. Please ask any further questions on http://discuss.gohugo.io/

**Comment by seschwar** [comment]
But apparently `safeHTML` has no effect on the second line's `href` value. Shouldn't it?

**Comment by bep** [comment]
Please ask any further questions on http://discuss.gohugo.io/
