### ISSUE TITLE
Don't use viper.Get* in tight loops

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2495]
Profiling indicate that using `viper.GetBool` inside  the url funcs (MakePath etc.) have a surprising cost.

Just removing one viper.Get temporary from `MakePathSanitized`:

```
benchmark           old ns/op       new ns/op       delta
BenchmarkHugo-4     20347856514     17916615991     -11.95%

benchmark           old allocs     new allocs     delta
BenchmarkHugo-4     66611825       60243953       -9.56%

benchmark           old bytes       new bytes       delta
BenchmarkHugo-4     10282345656     10122546104     -1.55%
```

**Comment by bep** [comment]
I have "suggested" this for the 0.17 release. My PR isn't entirely finished, but I will wrap it up during the day. 

I'm not sure why Viper allocates memory on a simple `GetBool` (I will look into that), but we should anyhow avoid doing lookups in tight loops (I didn't consider the URL funcs to be in "tight loops").

```
benchmark           old ns/op       new ns/op       delta
BenchmarkHugo-4     32771543767     20956368681     -36.05%

benchmark           old allocs     new allocs     delta
BenchmarkHugo-4     66611886       51747681       -22.31%

benchmark           old bytes       new bytes      delta
BenchmarkHugo-4     10272277160     9906356584     -3.56%
```

/cc @spf13

**Comment by bep** [comment]
Also see https://github.com/spf13/viper/issues/242

**Comment by bep** [comment]
With the fix in `cast`, the win is less, but still significant:

```
benchmark           old ns/op       new ns/op       delta
BenchmarkHugo-4     24116936011     19791183884     -17.94%

benchmark           old allocs     new allocs     delta
BenchmarkHugo-4     60902955       50003607       -17.90%

benchmark           old bytes       new bytes      delta
BenchmarkHugo-4     10121519632     9857226960     -2.61%
```

**Comment by moorereason** [comment]
I like your PathSpec approach.  I was thinking along the same lines when I first saw this issue, but with your fix in `cast`, I'd say we hold this change for 0.18.

**Comment by bep** [comment]
I have another simple fix for Viper coming that will improve this even further.

**Comment by bep** [comment]
This is the delta after the latest Viper update:

```
benchmark           old ns/op       new ns/op       delta
BenchmarkHugo-4     14465408023     13147573109     -9.11%

benchmark           old allocs     new allocs     delta
BenchmarkHugo-4     55147163       48210421       -12.58%

benchmark           old bytes      new bytes      delta
BenchmarkHugo-4     9998583512     9815322448     -1.83%
```

Still worth doing, but not super-important anymore.
