### ISSUE TITLE
Erroneous "LinkResolver: No page found"

### ISSUE THREAD

**Issue by kontsevoy** [spf13/hugo#2506]
When I build my Hugo website I get a lot of erroneous LinkResolver errors like this:

```
ERROR: 2016/09/28 15:49:10 content_renderer.go:56: LinkResolver: No page found for "using#secure-sessions" on page "teleconsole.md".
ERROR: 2016/09/28 15:49:10 content_renderer.go:56: LinkResolver: No page found for "using#using-private-proxies" on page "teleconsole.md".
ERROR: 2016/09/28 15:49:10 content_renderer.go:56: LinkResolver: No page found for "tos" on page "teleconsole.md".
```

They are caused by Hugo believing that every markdown link must point to another markdown file. Consider this markdown fragment:

```markdown
You can also [forward local TCP](using#port-forwarding) ports to...
```

Hugo complains that `No page found for "using#secure-sessions"` well, yes - because that page is not generated by Hugo. Our website is composed of static and dynamic parts, some are generated by Hugo, others aren't.

I have not found a way to suppress this, but it feels like something a lot of people would run into if they try to use Hugo to generate HTML for the static portions of a web app.

[EDIT] Another use case where this is happening is when you have `alias` directives under `path` in Nginx, serving different URL paths, like `/documentation` from different sources. In that case Hugo again won't have any idea if a link is valid or not because it effectively gets rewritten by Nginx.

**Comment by bep** [comment]
I assume you have `sourceRelativeLinks = true` in your Blackfriday config? If yes, you can get rid of those errors by switching the flag to `false`.

**Comment by kontsevoy** [comment]
Ha! You're right. Should I close the issue then?
