### ISSUE TITLE
ref/relref issue with duplicate base filenames

### ISSUE THREAD

**Issue by kontsevoy** [spf13/hugo#2507]
I have tried using `relref` to generate links to other parts of the site. In my case the generated links are broken, consider the following example:

```
~$: tree content/
content/
├── teleport
│   ├── admin-guide.md
│   ├── architecture.md
│   ├── faq.md
│   ├── quickstart.md
│   └── user-manual.md
├── teleport.md
```

Inside of `teleport/quickstart.md` I have a link declaration:

```
{{< relref "faq.md" >}}
```

And it generates `/teleport/faq`. I expect it to generate simply `faq` because the rendered page is already under `/teleport`. So the generated link is not relative at all, it's an absolute URL without a hostname.
### Problem

This is a problem because such a page won't work if the generated HTML will be "mounted" into another subsection of a larger website, say `/projects/teleport`. 

In fact, it doesn't even work in "pure Hugo" situations when you have two `faq.md` files in `content/a/faq.md` and `content/b/faq.md` - it will always produce to `/a/faq` for some reason

**Comment by bep** [comment]
This is as designed. If you want your site "mounted into" a larger website, you will have to use something other that `relref`, which, if the memory serves me correct, does produce links `relative to the server root`.

If you want to address `b/faq.md`you should be able to:

```
{{< relref "b/faq.md" >}}
```

But looking at the code I see a bug where the order of the pages matters.

**Comment by bep** [comment]
For the problem code line, see https://github.com/spf13/hugo/blob/master/hugolib/site.go#L271

It breaks out of the loop when match on base filename when it should have kept on looking for a more specific match.

// cc @halostatue

**Comment by moorereason** [comment]
The line in question can be seen in commit [a0167d8](https://github.com/spf13/hugo/blob/a0167d838ea37082e55da7941f32cce0e0662cf4/hugolib/site.go#L271).
