### ISSUE TITLE
RSSlink doesnt seem to work

### ISSUE THREAD

**Issue by jubalh** [spf13/hugo#2527]
I tried to add a link to the generated RSS feed following this [article](https://gohugo.io/templates/rss/) with hugo 0.15 and hugo 0.16. But the link isnt created. `{{ .RSSlink }}` doesn't output anything. To be sure I also tried wih `{{ .RSSLink }}`If I navigate to `/post/index.xml` however I see that the feed is created.

**Comment by moorereason** [comment]
First, please use https://discuss.gohugo.io/ to ask questions.

The `RSSLink` variable is only relevant for the Site and Sections/Taxonomies, I believe.  Try `.Site.RSSLink`.

We may need to update the docs to make this more apparent (ie. the Template Variables page lists `.RSSLink` under the Page variables, which is actually inherited from Node).

**Comment by jubalh** [comment]
Okay.
Thank you anyways, this soved it :)
