### ISSUE TITLE
Allow alias page to be templated

### ISSUE THREAD

**Issue by natefinch** [spf13/hugo#2533]
This is a bug to track work I'm doing to allow the redirect page created for aliases to have templated information in it.  This will function similarly to the 404 page template, i.e. one template for the whole site.  The template should be given the metadata from the page it is aliasing, so you can customize the redirect per-aliased page.

**Comment by bep** [comment]
Note that the template will not always have a `Page` context (it is used for other redirects as well).

**Comment by natefinch** [comment]
Being worked on in #2576
