### ISSUE TITLE
`index` and `sort`

### ISSUE THREAD

**Issue by robsonsobral** [spf13/hugo#2541]
Hi!

Trying to use `sort` with `index` returns the following error: `error calling sort: sequence must be provided`.

Using:

    {{ range sort ( index $.Site.Data.cases $.Lang ) ".home.weight" }}

On `Hugo Static Site Generator v0.17 BuildDate: 2016-10-07T11:46:29-03:00`.

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions.
