### ISSUE TITLE
Website could be more platform-agnostic

### ISSUE THREAD

**Issue by grawlinson** [spf13/hugo#2551]
Every time I visit Hugo's [website](https://gohugo.io), I'm slightly annoyed by this:

> Using Homebrew?
>
> brew update && brew install hugo

[Source](https://github.com/spf13/hugo/blob/88ec7d88d1b77a407fd1050d107f3c58ab1804da/docs/layouts/index.html#L256-L257)

Is there any way we could make it less Mac-centric?

NB: I'm not interested in signing CLAs, so will not perform any PRs.

**Comment by bep** [comment]
The documentation is work in progress -- and built from PRs.

Discussions lives at http://discuss.gohugo.io/ -- this issue isn't concrete enough to trigger some action.
