### ISSUE TITLE
doc: multilingual mode config example should be in toml instead of yaml

### ISSUE THREAD

**Issue by brunoqc** [spf13/hugo#2553]
On http://gohugo.io/content/multilingual/, the example code is in yaml (I think) while I assumed it was toml (because of the "in your top-level config.toml (or equivalent)" and because `hugo new site` generates a 'config.toml' file.

You could specify that it's yaml but newbs like me will have to learn how to convert it. Using toml would mean a newb like me could have run a multilingual sample in just a few minutes.

**Comment by bep** [comment]
Note that the i18n translation config can only be in JSON and YAML.

**Comment by digitalcraftsman** [comment]
Fixed in #2804.
