### ISSUE TITLE
Add support for TOML Inline tables

### ISSUE THREAD

**Issue by grabarczyk-t** [spf13/hugo#2554]
When I wanted to created an Inline Table variable in a front matter file, like this: 

```
my_variable = { key = "value" }
```

I got an error:

```
ERROR: 2016/10/11 09:42:50 page.go:828: Error parsing page meta data for post\some_post.md
ERROR: 2016/10/11 09:42:50 page.go:829: Near line 9 (last key parsed 'my_variable'): Expected value but found '{' instead.
ERROR: 2016/10/11 09:42:50 page.go:393: Near line 9 (last key parsed 'my_variable'): Expected value but found '{' instead.
Error: Error building site: Errors reading pages: Error:Near line 9 (last key parsed 'my_variable'): Expected value but found '{' instead. for post\some_post.md
```

Same thing was when I tried to do it in toml data file. 

Toml docs: https://github.com/toml-lang/toml#user-content-inline-table

**Comment by bep** [comment]
Please create an issue here https://github.com/pelletier/go-toml/issues

And link back to this issue.

**Comment by grabarczyk-t** [comment]
It seems that this feature is already implemented in go-toml and works fine. @bep why didn't you check it before you asked me to create the issue there?

**Comment by bep** [comment]
>why didn't you check it before you asked me to create the issue there? 

You asked for it so you do the work. Simple as that. I don't need inline tables.

**Comment by grabarczyk-t** [comment]
> If this already works, please close this issue.

It works in go-toml, not in Hugo

> You asked for it so you do the work. Simple as that. I don't need inline tables.

First of all: ok, but why did you ask me to create an issue right off the bat? You could've first ask me to check if this problem is caused by the go-toml library..

Secondly: the way you said that was really off-putting. I thought I would do something good by reporting a bug.. 

If this is not considered a bug, it should be at least mentioned in the docs. https://gohugo.io/content/front-matter/ states that: `Hugo supports a few different formats [...] Supported formats: TOML`. There should be a note there somewhere saying that not all TOML constructs are currently supported

**Comment by bep** [comment]
Hugo uses `go-toml` so I assumed the problem was with `go-toml`. I still do. The answer you got was the pragmatic and correct answer -- this is an open source project, not some big expensive software with 24h/7 perfect support. 

* What is the output of *hugo version*?
* What operating system?

**Comment by moorereason** [comment]
@grabarczyk-t,
I'm unable to reproduce this problem with the latest Hugo.  I suspect that you have an older version of Hugo that used a different TOML library, which was only TOML v0.2.0 compliant and did not support inline tables.

**Comment by grabarczyk-t** [comment]
>  I suspect that you have an older version of Hugo 

That's true, I was using 0.16. I didn't notice that there was a new version already. I checked it in 0.17 and indeed, there is no problem with the inline tables anymore. I am closing the issue
