### ISSUE TITLE
Hugo 0.17 regression with page names that contain dot

### ISSUE THREAD

**Issue by miltador** [spf13/hugo#2555]
On Hugo 0.16 the pages with dot in name were rendering correctly.

With Hugo 0.17 pages with dot in their name won't render. With `hugo server` I get only 

```
<pre>
</pre>
```

in output.
However when doing a build of site with `hugo` the name of page with dot get stripped down to the first dot. The content of the page is correct though.

**Comment by bep** [comment]
By "name of page" you mean exactly?

**Comment by miltador** [comment]
I mean name of file e.g. `10.3.md` won't work.

**Comment by tphalp** [comment]
I'm experiencing the same thing. See #2579.

**Comment by bep** [comment]
@abourget I believe this is your logic.

**Comment by vyuh** [comment]
I investigated this behaviour on a recent version db86f48 by simple print-lining, relevant observations are listed below for a file named `"moo.0.7.78787.md"`. It'll help if you refer to the code of `func`s linked below while reading:
- **in v0.17 and later:**
    - file hugolib/page.go, [`func permalink`](https://github.com/spf13/hugo/blob/db86f480824d69f71b9eecc3c22b9d7d2622e55b/hugolib/page.go#L593): `t` is set to a value returned by `translationBaseName()`. The value is "moo.0.7" (but it should be "moo.0.7.78787.md" to work correctly). The permalink returned by function ends with "moo.0" which is value of `t` after removing the 'extension' (".7").
    - file source/file.go, [`func NewFile`](https://github.com/spf13/hugo/blob/db86f480824d69f71b9eecc3c22b9d7d2622e55b/source/file.go#L129): `f.basename` is set to "moo.0.7.78787", `f.lang` is set to "78787", `f.translationBaseName` is reduced to "moo.0.7" (this is set as `t` in `func permalink()`). `f.translationBaseName` excludes what hugo thinks is a lang code (".78787"), and it excludes the extension (".md") too. This incorrect value is returned to `func permalink` and ...
        This function must ensure that *only* file names ending with `".<valid_lang_code>.<extension_like_md>"` are adjusted by removing *only* the `".<valid_lang_code>"` part, `".<extension_like_md> "`should be kept intact.

        **Most probably this is the function which needs a FIX. Some Ideas:**
        - `translatedBaseName` must keep the extension (".md") because it is removed when `permalink` is created from `t` in `func permalink()`.
        - also, before setting a garbled `translationbasename`, it should perform some check to verify that the site `ismultilinual` or that `f.lang` is some valid language code the author has explicitly listed in config. (though it looks like such a check was removed in [708bc78](https://github.com/spf13/hugo/commit/708bc78770a0b0361908f6404f57264c53252a95#diff-11ef8f3d3393d6df7b93de219441eeb2L127)).
- **in v0.16:**
    - file hugolib/page.go, [`func permalink`](https://github.com/spf13/hugo/blob/v0.16/hugolib/page.go#L447):`t` was "moo.0.7.78787.md", a value that came from `_, t := filepath.Split( p.Source.LogicalName() )`. Using this value of `t` generates correct permalinks in v0.17,  by breaking multi language support of course. :P
    - file source/file.go, [`func NewFile`](https://github.com/spf13/hugo/blob/v0.16/source/file.go#L104): f.{basename,lang,translationBaseName} didn't exist.

**Comment by abourget** [comment]
Good and thorough analysis @vyuh .. I think you're right, last time I had my head into this, very few places read and tweaked those fields.

Doing validity check on the `lang` section would be a great addition, as well as putting back that multilingual enablement check.

@vyuh do you think you could propose a patch for that ?  It'd be a great contribution I think :)  I'd gladly review.

btw, are you using Multilingual ? If not, then adding some simple checks for multilingual enablement, and sort of reverting to previous behavior when not enabled, would be a quick fix, wouldn't it ?
