### ISSUE TITLE
IsMenuCurrent always returning `false` for current menu

### ISSUE THREAD

**Issue by vcatalano** [spf13/hugo#2556]
Attempting to determine if a given navigation item is active, the following block never renders the class attribute:

`{{if $currentNode.IsMenuCurrent "main" . }}class="active"{{end}}`

It only appears to work for the root (/) endpoint.

v0.18-DEV BuildDate: 2016-10-10T22:08:27-07:00

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting.
