### ISSUE TITLE
{{ .Site }} and {{ .Hugo }} Variables not rendered reliable.  

### ISSUE THREAD

**Issue by kevingimbel** [spf13/hugo#2560]
I'm currently moving my website from Jekyll to Hugo and I'm encountering some issues with the `{{ .Hugo }}` site variables. When I try to output the current version with `{{ .Hugo.Version }}` inside the footer it only works on the front-page but not on single pages.

I have the current dev version on http://hugo.kevingimbel.de, as you can see the Footer reads "Hugo v0.18-DEV" on the front page but not on the single-pages (e.g. http://hugo.kevingimbel.de/projects/bash-vhost/). The same  happens with `{{ .Hugo.Generator }}` I use for the meta tag and the `{{ .Site.BaseURL }}` which I use with the `<base>` tag. 

My Hugo Version: `Hugo Static Site Generator v0.18-DEV BuildDate: 2016-10-10T15:35:19+02:00`

I updated Hugo a few days ago but have had the same issue with v0.16 before. 

---
 
I would've asked on the Forum but I'm getting "New registrations are not allowed from your IP address (maximum limit reached). Contact a staff member." when I try to sign up. 

@bep Since you're the main contributor to Hugo I added you to the private repo holding the source code so you can look around if required. If you require more information let me know.

**Comment by bep** [comment]
This belongs on the forum.

If you cannot post there for some reason, you should fix that first. 

I'm the *lead developer* in Hugo -- I also happen to be the *main developer*, but it doesn't sound fair to dump more work in the lap of the person who does the most work. Please do not add me as a collabrator to a repo and assume I will help without asking first.
