### ISSUE TITLE
Add TOML support for language files

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2577]
Doing this in YAML is frustration galore.

EDIT: https://github.com/nicksnyder/go-i18n

**Comment by moorereason** [comment]
Why is this an upstream issue?  What's missing?

**Comment by bep** [comment]
>Why is this an upstream issue? What's missing?

It is maybe more clear now. The snyder lib does the parsing and currently only supports JSON and YAML.

**Comment by bogem** [comment]
The question is, which syntax should be used. I mean, there are no anonymous tables in TOML and it should be implemented in another way. For example, how could be written following structures in TOML:
```json
[
  {
    "id": "settings_title",
    "translation": "Settings"
  }
]
```
```json
[
  {
    "id": "d_days",
    "translation": {
      "one": "{{.Count}} day",
      "other": "{{.Count}} days"
    }
  }
]
```

**Comment by bep** [comment]
```toml
[[d_days]]
one = "{{.Count}} day"
  other = "{{.Count}} days"

[[string_id_2]]
translation = "Some other translation"
```

go-i18n's file format is probably an attempt of future-proofing, making it more complex than it should.

If `go-i18n` could take the data structure directly (it should), Hugo could define whatever format it likes and creat an adapter for it. 

With that in mind, we could also maybe create some support for `PO` files (or whatever they are called).

My main issue about `YAML` is that it is soooo easy to get the indentation wrong, and the error messages are terrible.

**Comment by bogem** [comment]
I think, the adapter is the best option for hugo now. I will try to implement it if there will be no more ideas

**Comment by nicksnyder** [comment]
> go-i18n's file format is probably an attempt of future-proofing, making it more complex than it should.

go-i18n's file format is an attempt to match the data that it actually needs. Each translation object has an id and _either_ one translation (non-plural form) or multiple translations (plural form).

> If go-i18n could take the data structure directly (it should)

It can, so you can choose any format and inject translations as you see fit:
https://godoc.org/github.com/nicksnyder/go-i18n/i18n#AddTranslation

If you prefer a flatter format I would recommend treating non-plural forms exactly the same:

```
[[d_days]]
one = "{{.Count}} day"
other = "{{.Count}} days"

[[string_id_2]]
other = "Some other translation"
```

If you need to differentiate between a plural and non-plural form (the `goi18n` command does), then the logic would be something like "if there is only `other` key and the value doesn't contain `{{` then it is non-plural, else plural".

The `goi18n` command helps manage translation files so if you want to use it, then you would either need to be able to either (1) convert TOML to YAML or JSON, or (2) add support to go-i18n for TOML.

If there is general agreement that a flatter format would be better (even in JSON and YAML) then I am open to changing go-i18n.

**Comment by bogem** [comment]
@nicksnyder but support for TOML will break all existing API of `go-i18n` package. This moment should be discussed in separate issue at `go-i18n`'s page. But for hugo at the moment the adapter should be implemented.
IMHO it looks not so good to hold only one `other` for non-plural form. It looks nicer as bep has offered

**Comment by bep** [comment]
>But for hugo at the moment the adapter should be implemented.

We have no real rush; @nicksnyder is right about the translation workflows, and we don't want to add additional glue code in Hugo if we don't really have to.

I'll create an issue on the go-i18n tomorrow where we can continue this discussion. A flattening of the data format would be breaking, but it should be fairly easy to support both in a grace period.

**Comment by nicksnyder** [comment]
> but support for TOML will break all existing API of go-i18n package

It doesn't need to. We can support a new format without dropping support for the old format.

**Comment by nicksnyder** [comment]
go-i18n 1.8 now supports TOML and a flatter file format
https://github.com/nicksnyder/go-i18n/releases/tag/v1.8.0

Thanks @bogem !
