### ISSUE TITLE
Content after <!--more--> is included in summary if on the same line as summary

### ISSUE THREAD

**Issue by MaxMilton** [spf13/hugo#2586]
Content after the  summary divider is being included in the summary if it's on the same line.

**Example:**
```
this is an example <!--more-->of the issue.
```
**... results in:**
```
<p>this is an example of the issue.</p>
```
**Expected result:**
```
<p>this is an example </p>
```

I'm using markdown for articles (I havn't tried with other formats).

Hugo version:

> Hugo Static Site Generator v0.17 BuildDate: 2016-10-08T01:45:27+11:00

**Comment by MaxMilton** [comment]
Actually I'm still having this issue. Is there something else I need to do for this functionality to work correctly?

Version: `Hugo Static Site Generator v0.18 BuildDate: 2016-12-20T01:42:20+11:00`

**Comment by karelfiser** [comment]
I am experiencing same problem.

Hugo version ‘0.22.1’

**Comment by BigKuCha** [comment]
same issue d
