### ISSUE TITLE
Page Params  got lowercased

### ISSUE THREAD

**Issue by moonytheloony** [spf13/hugo#2590]
I used to have images displayed through a dynamic url e.g.
`<img src="{{ .Site.Params.resourcesBaseUrl }}/profilePicture.jpg" class="img-responsive" alt="Profile Picture"/>`

This used to work fine until recently. Now Hugo is not able to concatenate the two strings and just outputs image source as /profilePicture.jpg which does not render any images.

I am using the latest build to deploy my website.

**Comment by chaseadamsio** [comment]
> All Params are only accessible using all lowercase characters.

https://gohugo.io/templates/variables/

Have you tried changing `.Site.Params.resourcesBaseUrl` to `.Site.Params.resourcesbaseurl` (in both the markdown and the template)?

**Comment by moonytheloony** [comment]
That fixed the issue. However, this is a recently added feature. My site was working fine until my last deployment last month. I hope Hugo maintains backward compatibility and documents breaking changes somewhere.

**Comment by chaseadamsio** [comment]
What version did you upgrade from and to? Are you compiling off of master?

**Comment by chaseadamsio** [comment]
@moonytheloony I've left you a github issue on one of your projects [Blog-Web](https://github.com/moonytheloony/Blog-Web/issues) with a recommendation of how to install hugo for usage. using `go get` on hugo will get you the latest master and you likely want to use a version of hugo that won't change so you know the API you're working with won't change.

Hope that helps!

**Comment by bep** [comment]
I will reopen. This lower-casing of `Params` is a mistake that should be reverted. ´Page.Params` should be as the author meant -- the `.Param` method etc. should be case insensitive.

**Comment by sylus** [comment]
Also ran into this unexpectedly as my Travis deploy of compiled assets to github pages were missing all param attributes. Glad for this issue to know it wasn't a misconfiguration ^_^

**Comment by remeh** [comment]
What would you advice for themes maintainers ?

We have the problem with the cocoa theme where we can't support both Hugo 0.17 and Hugo 0.18 because one looks for case sensitive variable in Params and the latter is looking for the lowercased ones.

Maybe changing all the sample `config.toml` variables to lowercase ?
