### ISSUE TITLE
/public is added to watchlist

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2602]
Noticed this when having `hugo server` and doing a `hugo` on the side:

```
adding created directory to watchlist /Users/bep/sites/hugo-slate/exampleSite/public
adding created directory to watchlist /Users/bep/sites/hugo-slate/exampleSite/public/errors
adding created directory to watchlist /Users/bep/sites/hugo-slate/exampleSite/public/slate
adding created directory to watchlist /Users/bep/sites/hugo-slate/exampleSite/public/slate/fonts
adding created directory to watchlist /Users/bep/sites/hugo-slate/exampleSite/public/slate/images
adding created directory to watchlist /Users/bep/sites/hugo-slate/exampleSite/public/slate/javascripts
adding created directory to watchlist /Users/bep/sites/hugo-slate/exampleSite/public/slate/javascripts/app
adding created directory to watchlist /Users/bep/sites/hugo-slate/exampleSite/public/slate/javascripts/lib
adding created directory to watchlist /Users/bep/sites/hugo-slate/exampleSite/public/slate/stylesheets
```

That doesn't sound right.

**Comment by Imhotup** [comment]
Hi @bep Are there any files I should look at to fix this?

**Comment by bep** [comment]
@Imhotup I will have to think about this ... this may be as designed, but still is unfortunate. We are listening for changes in the site root for config.toml, and the watches seems to be recursive by default.

**Comment by bep** [comment]
OK, I see what's happening now.

I was doing some work in a theme, so I have

```bash
myTheme/exampleSite
```

and set 

```bash
themesdir = "../.."
```

In the exampleSite to test it.

This works fine, but he/she who made the watcher dir logic for themes was lazy (probably me, then :-)) and added the entire theme dir to watch list, while doing the proper thing for the base project (adding static, content etc.)

While this works, it is annoying when you have stuff like /assets/javascript etc. that you don't want to trigger reloads.
