### ISSUE TITLE
Interpolating object property name

### ISSUE THREAD

**Issue by eduardoboucas** [spf13/hugo#2611]
Sorry if this is more of a question about Go and not specifically Hugo, but I'm trying to access data files that are nested inside a folder whose name is stored in a variable.

File is in `data/comments/myDirectory` and `myDirectory` is stored as a string in a variable. How can I use that variable in the expression below?

```
{{ range $.Site.Data.comments.>variable here?< }}
    {{ . | jsonify }}
{{ end }}
```

Thanks!

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions.
