### ISSUE TITLE
Error install latest hugo (v0.17) on ubuntu?

### ISSUE THREAD

**Issue by cafe4it** [spf13/hugo#2612]
Sorry, I do not know English.[GG translate]

I installed the latest version of hugo: hugo_0.17-64bit.deb
After installation, I run: 
```
hugo version
```
```
Hugo Static Site Generator v0.11
```
I thought it must be:
```
Hugo Static Site Generator v0.17
```
When I tried all of hugo guide, I often get an error:
```
ERROR: 2016/10/20 Rendering error: html/template: "theme/taxonomy/tag.html" is an incomplete template
```
Thanks.

**Comment by cafe4it** [comment]
Hix, i've been tried : 
```
go get -v github.com/spf13/hugo
```
but 
```
Hugo Static Site Generator v0.11
```

**Comment by bep** [comment]
Pleease use http://discuss.gohugo.io/ for questions.

**Comment by anthonyfok** [comment]
See https://discuss.gohugo.io/t/error-install-latest-hugo-v0-17-on-ubuntu/4367
