### ISSUE TITLE
Can't create a new theme

### ISSUE THREAD

**Issue by matduarte** [spf13/hugo#2613]
Hello, I have a problem with creating a new theme : 
```
$ hugo new theme sometext
Error: Unable to locate Config file. Perhaps you need to create a new site.
       Run `hugo help new` for details. (Unsupported Config Type "")
```
I'm using the latest version (0.17), installed using Homebrew on macOS. I tried to create a new theme using `hugo` installed from source but I got the same problem.
I attach a screenshot in case...
<img width="922" alt="screen shot 2016-10-20 at 06 06 58" src="https://cloud.githubusercontent.com/assets/16789874/19545964/71a26112-968b-11e6-9c4c-b624e123c483.png">
How you can see I am able to create a new site but not a new theme.

**Comment by cafe4it** [comment]
1. hugo new site someOtherText
2. cd someOtherText
3. hugo new theme someText

**Comment by matduarte** [comment]
@cafe4it Thank you it works, I'm feel so dumb
