### ISSUE TITLE
First paragraph in markdown not being wrapped with <p></p>

### ISSUE THREAD

**Issue by glockjt** [spf13/hugo#2616]
I have a markdown file where the first piece of content is a paragraph and it is not being wrapped with `<p></p>` on the rendered html page using `{{ .Content | markdownify }}`.

Example `.md` file:
```markdown
---
title: Sample Title
date: 2016-10-20
---

Content that is not being wrapped with paragraph tags.

Content that is being wrapped with paragraph tags.
```

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions (and .Content IS markdown -- no need to markdownify it)
