### ISSUE TITLE
Adding Disqus - Error: While parsing config: (7, 21): never reached

### ISSUE THREAD

**Issue by pwmcintyre** [spf13/hugo#2620]
while following the quickstart, at Step "10. Integrate Disqus"
http://gohugo.io/overview/quickstart/

I copy/pasted as specified, to give me this:
```
baseurl = "http://blog.example.com/"
title = "example"
languageCode = "en-gb"

[Params]
  Author = "Peter"
  disqusShortname = blog-example-com
```
And tried to build:
```
C:\Users\peter\git\blog>hugo
Error: While parsing config: (7, 21): never reached
```

Removing the [params] stanza restores things to normal

**Comment by digitalcraftsman** [comment]
Try to wrap `blog-example-com` in quotes, like it was done with `Author`'s value. Please refer to the [Hugo forum](discuss.gohugo.io) for such questions.

**Comment by pwmcintyre** [comment]
Oh good call, thanks. Quoting it seems to have fixed the error.
Just reading through the .toml spec and apparently dashes are perfectly valid when not quoted.
https://github.com/toml-lang/toml#keyvalue-pair

Is this a toml bug I should raise or a Hugo bug do you think?

**Comment by bep** [comment]
>Is this a toml bug I should raise or a Hugo bug do you think?

String values *must* be quoted. This is how I read the spec.

**Comment by pwmcintyre** [comment]
The toml spec? where do you read that?
> Keys may be either bare or quoted. Bare keys may only contain letters, numbers, underscores, and dashes (A-Za-z0-9_-). ... Best practice is to use bare keys except when absolutely necessary.

**Comment by bep** [comment]
**value* not **key**

**Comment by pwmcintyre** [comment]
Important distinction which I glossed over! Got it, thanks.
