### ISSUE TITLE
Improper import sequence of package

### ISSUE THREAD

**Issue by vikashvverma** [spf13/hugo#2621]
https://github.com/spf13/hugo/blob/master/main.go#L21

internal package should be imported together

**Comment by bep** [comment]
Says who?

It passes GoLint and GoVet -- and that makes me happy enough.

**Comment by vikashvverma** [comment]
@bep Everywhere internal packages are imported first and external packages are imported letter having a line between. Just wanted to make sure the convention is followed, however there is nothing wrong in mixing internal & external package import order.
