### ISSUE TITLE
Panic on batch-resizing images during livereload

### ISSUE THREAD

**Issue by brasilikum** [spf13/hugo#2625]
The following panic occurred while I was batch resizing images with `sips -Z 1280 *.png` with `hugo serve -v` running on OSX `10.12.1 Beta (16B2553a)`.

```
Syncing /images/video_thumb_play.png to /
panic: close of closed channel

goroutine 163 [running]:
panic(0x64cdc0, 0xc4200b0d40)
    /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/spf13/hugo/livereload.(*hub).run(0xa46880)
    /private/tmp/hugo-20161007-85797-vy50e9/hugo-0.17/src/github.com/spf13/hugo/livereload/hub.go:44 +0x1d9
created by github.com/spf13/hugo/livereload.Initialize
    /private/tmp/hugo-20161007-85797-vy50e9/hugo-0.17/src/github.com/spf13/hugo/livereload/livereload.go:64 +0x41
```

**Comment by bep** [comment]
This looks rare -- and the code in question seems to have been borrowed from the  Gorilla mux project.

**Comment by moorereason** [comment]
The underlying problem appears to be that we have a race condition between two code paths that can close the websocket `send` channel: [hub.go#L44](https://github.com/spf13/hugo/blob/88b5bbd5329a87046979e222a9ccf74eda59df3c/livereload/hub.go#L44) and [hub.go#L51](https://github.com/spf13/hugo/blob/88b5bbd5329a87046979e222a9ccf74eda59df3c/livereload/hub.go#L51).

I don't think we copied this from the gorilla project, or at least I can't find it anywhere.

**Comment by bep** [comment]
>I don't think we copied this from the gorilla project, or at least I can't find it anywhere.

Let's assume I didn't make that up, but it doesn't matter.

**Comment by gwatts** [comment]
As an extra datapoint I hit this same panic last night while a large number of files were being updated by a build program

**Comment by d-led** [comment]
been getting these crashes frequently today

**Comment by philc** [comment]
I use hugo often and haven't ran into crashes, but today I discovered I can pretty reliably crash hugo by editing a large file (5284765 bytes of generated HTML in my case). I tried trimming this file to see if there's a specific file size the triggers the crash, but I can't reliably zero in on semi-precise threshold.

It would be great to fix the race condition. It's very annoying.
