### ISSUE TITLE
Pagination bug?

### ISSUE THREAD

**Issue by gsdu8g9** [spf13/hugo#2636]
I found this special issues during my tests with IPv4 and domains data using Hugo as site generator.

Categories = ["127.0.0.1"]

Such IPv4 like category name will have such link to second page. 
Tested on 0.14, 0.15, 0.16, 0.17 versions of Hugo.

/categories/127.0.0/index.1/page/2/

Сonfig file includes these options:

preserveTaxonomyNames = true
uglyURLs = false
disablePathToLower = true

With such category

Categories = ["ns1.someverynicewebhostingservice.com."]

Hugo will produce this such link to second page. 

/categories/ns1.someverynicewebhostingservice.com/index./page/2/

NS server was extracted from ns lookup with that dot at the end.

It looks like there is some bug related to dots in category names.

**Comment by gsdu8g9** [comment]
I have forgotten to add that these links are 404. That is the issue.
But all generated files looks normal and they are located in right places on disk.

**Comment by bep** [comment]
Duplicates #1885
