### ISSUE TITLE
Markdown pipe inside a template

### ISSUE THREAD

**Issue by lebarde** [spf13/hugo#2641]
Hello,
I just wondered if there is a `markdown` pipe to escape Markdown content inside a template?

I would like to do something like:

```
{{ with .Widget.content }}
{{ . | markdown }}
{{ end }}
```

If so, how to search it in the code?

Thanks!

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by lebarde** [comment]
Ok, thanks for the explanation (all this is new for me).
