### ISSUE TITLE
Remove Site Showcases with no mention of Hugo

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2655]
It should be very little to ask to either add a "Powered by Hugo" or not disabling the meta generator tag for Hugo (added in 0.16) -- I suspect some of these aren't Hugo sites at all.

These are the current sites with no "hugo" (case insensitive) in their source:

```
http://gophercon.com/
http://chimeraarts.org/
http://ifup.org/
http://heyitsalex.net/
http://it.hackmeeting.org/
http://philosophy.ucsb.edu/
http://arianv.com/
http://kangkona.github.io/
http://osmlab.github.io/learnoverpass/
http://www.arqueart.com/
http://www.greenitglobe.com/
http://www.humboldtux.net/
http://www.javaunion.com/
http://webstudylist.com/
```

**Comment by moorereason** [comment]
A link to the source repo would be sufficient as well.

For GopherCon, the source repo is https://github.com/gophercon/gc15.

**Comment by ITSecMedia** [comment]
I agree but to force people to show their repo would be imho too aggressive, don't you think so?

There might be api code, layouts solutions or scss files people are not absolutely willing to share with the public.

**Comment by bep** [comment]
The easy scriptable rule is: 

**If "hugo" (case insensitive) isn't mentioned in the home page HTML source, then it isn't a Hugo schowcase..**

**Comment by ITSecMedia** [comment]
Have you already added this mandatory requirement to the docs?

**Comment by bep** [comment]
It is an unwritten rule.

**Comment by moorereason** [comment]
Seems a little heavy-handed to remove sites with source links.  I'm sure our users would rather see a showcase site with sources than a rendered site with the word "hugo" embedded in it.
