### ISSUE TITLE
Pushing from Bitbucket and getting and error

### ISSUE THREAD

**Issue by guillemhs** [spf13/hugo#2659]
Hi,

I was trying to deploy this site (https://bitbucket.org/acenhauer/acenhauer-site) from Bitbucket to Aerobatic using Hugo.

I added the configuration file package.json at the root of the project (https://bitbucket.org/acenhauer/acenhauer-site/src/8a010b5d0209?at=master) but it does work.

Is it an issue from my Hugo project or from Aerobatic?

Best regards,

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
