### ISSUE TITLE
doc: meta/roadmap needs update or removal

### ISSUE THREAD

**Issue by lebarde** [spf13/hugo#2666]
Going to [the documentation roadmap](https://gohugo.io/meta/roadmap/), we can see that the last revision is February 16, 2015. So either we should edit it to reflect the new labels in the github's issue system, or remove it.

**Comment by bep** [comment]
Remove.

**Comment by digitalcraftsman** [comment]
Should I remove the page and all references to it completely?

**Comment by bep** [comment]
>Should I remove the page and all references to it completely?

Easiest is maybe to remove the content and leave the file.

**Comment by digitalcraftsman** [comment]
> Easiest is maybe to remove the content and leave the file.

So you just want to leave a blank page?

**Comment by bep** [comment]
The important thing is to remove the misleading info that is there. I have no road map to fill in.

**Comment by digitalcraftsman** [comment]
> The important thing is to remove the misleading info that is there. I have no road map to fill in.

Which info exactly is misleading? Nobody of us has a concrete roadmap for Hugo. Hence all listed features could be misleading.

**Comment by bep** [comment]
>Which info exactly is misleading?

I just glanced it, and "paginator support" is certainly misleading as we added that years ago.
