### ISSUE TITLE
Build Hugo from a Go program

### ISSUE THREAD

**Issue by swill** [spf13/hugo#2667]
I use Hugo for most of my sites now, it is awesome. Thanks... 

The command line is great, but I am wondering what the best approach would be if I want to have a different Go program do the build of a Hugo site. 

My guess is that I would need to create a viper config and then find an entry point while bypassing cobra. Does anyone have suggestions for how I would go about doing this? Thanks...

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by bep** [comment]
But you may get a hint at https://github.com/bep/hugo-benchmark/

(we may get a proper API in the future)

**Comment by swill** [comment]
Thank you @bep for getting me pointed in the right direction.  I will review Hugo-benchmark and will post on http://discuss.gohugo.io/ if I can't figure it out from there.
