### ISSUE TITLE
[dev 18] .Site.Params in partials not writing to page

### ISSUE THREAD

**Issue by rdwatters** [spf13/hugo#2668]
Ran go get to use the dev build. `.Site.Params` values that worked in 17 are no longer showing up when running the local server. 

For example, in my `config.toml`, I have:

```
[params]
  CopyrightLine = "College of American Pathologists"
```

And then in `partials/footer.html`, I use the following:

```
<ul class="copyright">
      <li><small>© {{ .Site.LastChange.Format "2006"}}</small></li>
      {{ with .Site.Params.CopyrightLine }}<li>{{.}}</li>{{end}}
</ul>
```

The second `<li>` no longer writes to the page. Same if I use `if` or just `<li>{{.Site.Params.CopyrightLine}}</li>`.

@bep, it's in a [private repo](https://github.com/caporg/digital-strategy-documentation/) for work, but I'll add you as a collaborator in the event you want to test this locally....

**Comment by bep** [comment]
See https://github.com/spf13/hugo/pull/2630
