### ISSUE TITLE
Website: Hover effect on illustrations incorrectly suggest that they are clickable

### ISSUE THREAD

**Issue by dikarel** [spf13/hugo#2678]
The graphics used in the [landing page](http://gohugo.io) has a hover effect that may mislead the typical web user into thinking that they're clickable and would do something useful when clicked

In particular, this one example made me think that that clicking it would show instructions on how to set it up on Mac. I was disappointed to find out that clicking on it did nothing.

![screen shot 2016-11-08 at 9 21 39 pm](https://cloud.githubusercontent.com/assets/15131271/20102630/5ccbd566-a5f9-11e6-95eb-df40157c1530.png)

I would suggest removing the hover effect, so that it's unambiguous that they're just static illustrations.

**Specs**
- Browser: Google Chrome 54.0 (64 bit)
- OS: Mac OSX Sierra

**Comment by fbnlsr** [comment]
Agreed, not only the hover effect is useless but these illustration could use a bit more space.

![hugo-capture](https://cloud.githubusercontent.com/assets/1923346/20651478/7abde9dc-b4e6-11e6-8876-668a4df1eb0d.png)

**Comment by MarkDBlackwell** [comment]
> this one...made me think that that clicking it would show instructions on how to set it up on Mac.

These three ("Run Anywhere") images could be wrapped with anchor tags and easily linked to tutorials:
1. [Installing Hugo](http://gohugo.io/overview/installing/);
1. [Installing on a Mac](http://gohugo.io/tutorials/installing-on-mac/); and
1. [Installing on Windows](http://gohugo.io/tutorials/installing-on-windows/).

The "Make the Web Fun Again," "Fast & Powerful," and "Flexible" images could link to the [Introduction](http://gohugo.io/overview/introduction/) (just as the Docs button does).

Above the carousel of praise for Hugo, the star image could link to [Press, Blogs and Media Coverage](http://gohugo.io/community/press/).

The "Open and Free" image could link to the [GitHub repository](https://github.com/spf13/hugo) (just as the "open source" link does immediately below it).

For most of the images at "Built with &hearts;," perhaps the hover effect could go away (or link to Wikipedia articles [Software Construction](https://en.wikipedia.org/w/index.php?title=Software_construction&oldid=743472700) and [Software Development](https://en.wikipedia.org/w/index.php?title=Software_development&oldid=752055752)). However, the "spf13" image could link to Steve Francia's profile on GitHub.

**Comment by MarkDBlackwell** [comment]
> this one...made me think that that clicking it would show instructions on how to set it up on Mac.

@fbnlsr These three ("Run Anywhere") images could be wrapped with anchor tags and easily linked to tutorials:
1. [Installing Hugo](http://gohugo.io/overview/installing/);
1. [Installing on a Mac](http://gohugo.io/tutorials/installing-on-mac/); and
1. [Installing on Windows](http://gohugo.io/tutorials/installing-on-windows/).

The "Make the Web Fun Again," "Fast & Powerful," and "Flexible" images could link to the [Introduction](http://gohugo.io/overview/introduction/) (just as the Docs button does).

Above the carousel of praise for Hugo, the star image could link to [Press, Blogs and Media Coverage](http://gohugo.io/community/press/).

The "Open and Free" image could link to the [GitHub repository](https://github.com/spf13/hugo) (just as the "open source" link does immediately below it).

For most of the images at "Built with &hearts;," perhaps the hover effect could go away (or link to Wikipedia articles [Software Construction](https://en.wikipedia.org/w/index.php?title=Software_construction&oldid=743472700) and [Software Development](https://en.wikipedia.org/w/index.php?title=Software_development&oldid=752055752)). However, the "spf13" image could link to Steve Francia's profile on GitHub.

**Comment by digitalcraftsman** [comment]
This issue will become irrelevant once the new redesign of @budparr will be deployed. Shall we close it then?
