### ISSUE TITLE
[FEATURE REQUEST] Add additional source to new site generator

### ISSUE THREAD

**Issue by rdwatters** [spf13/hugo#2679]
I like that Hugo makes zero assumptions about your content or source organization, but I wonder if there is an advantage to adding a few sane defaults to `hugo new site`:

* archetypes
  * default.md
* content
* data
* layouts
  * /_default
    * baseof.html
    * list.html
    * single.html
  * /partials
  * /shortcodes
  * index.html
  * 404.html
* static
  * /css
  * /js
  * /img
* themes

This might be a bit opinionated, but I guess the question is how many new sites *wouldn't* use partials, shortcodes, `index.html`, `404.html`, and the `static` folder directories (which are already [suggested in the docs](https://gohugo.io/themes/creation#static)). 

I would go so far as to recommend that `baseof.html` include a doctype declaration with the generator meta tag, maybe something like the following: 

```
<!DOCTYPE html>
<html lang="en">
<head>
{{.Hugo.Generator}}
</head>
<body>
<h1>{{.Site.Title}}</h1>

</body>
</html>
```

But that would be a more opinionated suggestion than what I have above. You could even put `{{block "main" .}}{{end}}`, but that may be assuming too much as far as a new person using blocks...

**Comment by bep** [comment]
>his might be a bit opinionated, but I guess the question is how many new sites wouldn't use partials, shortcodes, index.html, 404.html

All the sites that prefer to use a theme?

**Comment by rdwatters** [comment]
True, but again, these files are pretty standard across all hugo sites, regardless of whether they live in the themes or root. And doesn't the cascade for Hugo first look for these files in the declared theme directory from config and *then* look in the root directory?  

So while it may add unused files, would this necessarily break any of the theming?

**Comment by bep** [comment]
>first look for these files in the declared theme directory from config and then look in the root directory? 

It is the other way around, which is the only thing that makes sense. See https://github.com/bep/docuapi as an example -- a user wold very rarely provide his/her own templates, but I provide some "hooks" that can be used to override stuff. 

I totally agree that we could and should make it easier to get started, but I'm not sure the answer is more empty files.

**Comment by rdwatters** [comment]
Shi*. I had it backwards. 

I just looked at the base scaffolding for Jekyll and Hexo to see how they're doing it. 

These are just ideas and not necessarily in order of preference:

1. Have `hugo new site my-site` generate new folder structure similar to what I have above. 
2. `hugo new site my-site -t ThemeName` installs with the current basic scaffolding (ie, none of the new empty files I mentioned above) and the appropriate theme in `/themes`.
3. With Jekyll 3.0+, it looks like they reconfigured the starting source to default to the "minima" theme and the only directories created with the `new` command are for content (ie, `_posts` and `_site`, the latter of which is the Hugo equivalent of `public`). Everything else is set in a configuration file. Maybe this would mean not creating `layouts`,`data`,`static`, etc in the root folder, but instead creating only `content` in the root, and all the other generator directories going directly into `themes`. This would mean every new site being developed is done so in a sort of "theming" context. This could be confusing w/r/t naming conflicts if a user has a ton of themes installed.
4. Have the community put together starter kits and feature them in an area in the docs; this is probably the most viable option. :smile:

All said, this can probably wait for another time in the future, so I won't be offended if you want to close this issue. I agree that empty files might not do much, but there could be an advantage to very basic templating build out for users each time they create a new site. It's just a matter of finding the balance between a nice convenience and something annoying that experienced users will have to go in and delete...
