### ISSUE TITLE
Bad HTML when using <!--more--> to define summary

### ISSUE THREAD

**Issue by LordMathis** [spf13/hugo#2688]
To generate post summary I'm using `<div class="post-summary><p>{{ .Summary }}...</p></div>`

HMTL code that is generated when I'm not manually defining summary split with `<!--more-->` looks like this:

    <div class="post-summary">
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed urna sapien, pellentesque nec justo sed, iaculis elementum tortor. Nam ultrices eros eget elit sodales, eget sagittis velit varius. Proin sodales pharetra libero in vestibulum. Donec id metus purus. Phasellus eu justo vulputate, vestibulum nisi sit amet, fringilla ante. Sed et molestie diam. Mauris eros mauris, viverra aliquam neque id, mattis pulvinar eros. Nam hendrerit quis mi sed accumsan. Etiam at...
      </p>
    </div>

which is exactly what I would expect. But when I use `<!--more-->` the HTML code looks like this:

    <div class="post-summary">
      <p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed urna sapien, pellentesque nec justo sed, iaculis elementum tortor
      </p>
      ...
     </p>
    </div>

which is not correct. I wouldn't notice it but I'm putting the three dots after my summary and when I use `<!--more-->` they get pushed to the next line.

Edit: The version of Hugo is 0.17

**Comment by bep** [comment]
Try using the elipse symbol instead of the 3 dots, i.e.  U+2026 or “…”. I'm no sure I'm going to fix make the summary logic more complex to handle this case.

**Comment by LordMathis** [comment]
Using elipse symbol doesn't help. Same code is generated even when no following symbols are used. So when I have `<div class="post-summary"><p>{{ .Summary }}</p></div>`
resulting HTML is:

    <div class="post-summary">
      <p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed urna sapien, pellentesque nec justo sed, iaculis elementum tortor
      </p>
      </p>
    </div>

It looks like the code that handles `<!--more-->` encloses the summary with extra `<p>` tags and the default summary generator does not.

**Comment by cdancette** [comment]
This issue is the same https://github.com/spf13/hugo/issues/1217
