### ISSUE TITLE
Inconsistent naming in manual pages: underscore vs dash

### ISSUE THREAD

**Issue by ejsmit** [spf13/hugo#2695]
Run `hugo gen man` on a new installation of hugo 0.17

- The manual pages created on disk:  `hugo_server.1`   **(underscore)**
- The SEE ALSO section in the hugo(1) manpage:   `hugo-server(1)`    **(dash)**

this makes it difficult to find other related manpages from the basic hugo(1) page.   I actually had to go and look at the man directory to see what the filenames are for the SEE ALSO pages.  It would be more useful if the names match.  

Tested on Fedora 24 64bit hugo 0.17 and Arch arm hugo 0.17, using binaries downloaded from hugo releases page.

**Comment by moorereason** [comment]
Upstream issue: https://github.com/spf13/cobra/issues/342

**Comment by anthonyfok** [comment]
Thanks @moorereason for the heads-up!

I have gone ahead and merged @knz's PR spf13/cobra#343, which closes Issue spf13/cobra#342, which should allow this issue to be closed.

Let me do a final test before closing this issue.  :-)

**Comment by anthonyfok** [comment]
It works with the latest Cobra!  Thank you @knz!

**Comment by bep** [comment]
@anthonyfok Hugo 0.18.1 is a REGRESSION bug fix release. If it was broken in Hugo 0.18 it does not belong in this release.
