### ISSUE TITLE
Could we have an option for aliases to throw a 301/302 redirect?

### ISSUE THREAD

**Issue by iandouglas** [spf13/hugo#2703]
Hi folks, thanks for such an awesome tool!

For users migrating from other platforms, maintaining 301/302 redirects is a bit of a challenge. I'm switching from self-hosted WordPress to Hugo on App Engine, and I'm curious how best to handle SEO corrections. I understand the reasons why Hugo can only do a meta-refresh redirect, but I'm curious if anyone has thoughts on whether there's any "pre-compiler" component to Hugo which could perhaps generate an .htaccess file where it turns aliases into 301/302 redirects.

**Comment by bep** [comment]
I doubt that this is possible in a general way, but I suggest you lift the problem at http://discuss.gohugo.io/ -- if someone comes up with a simple solution, we can reopen this issue.
