### ISSUE TITLE
docs: Certain menu items' opening behavior should be consistent

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/hugo#2712]
Clicking each of the following sidebar menu items replaces the content of the current window (or tab):

1. Download Hugo
1. Discuss Hugo

These should open IMO in a new window (or tab), and thus match the behavior of item, "Issues & Help".

**Comment by fbnlsr** [comment]
Opening links in a new window is generally considered bad behavior. Such links steal the user from his interface and generate a confusing and blurry experience.

Read more here: https://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/

**Comment by MarkDBlackwell** [comment]
@fbnlsr You have a good point. I'm convinced!

Therefore, each external-link menu item should replace the Hugo documentation website (in the current tab) IMO by default (unless the user explicitly requests a new window or tab).

Yet the opening behavior of sidebar menu items:
1. [Download Hugo](https://github.com/spf13/hugo/releases); and
1. [Discuss Hugo](http://discuss.gohugo.io/)

IMO should match (i.e., be consistent with) that of item, [Issues & Help](https://github.com/spf13/hugo/issues).

In order to achieve this consistency (in this way), we need merely adjust menu item [Issues & Help](https://github.com/spf13/hugo/issues) so it too replaces the Hugo documentation website (in the current tab).

**Comment by fbnlsr** [comment]
Indeed, it's important to have a consistent UI throughout the site.

In a broader sense, the Hugo Docs lack consistency and are imho Hugo's weakest point. For instance, some examples use TOML configuration, others JSON, etc... But it's another discussion.

So you're right, links throughout the site should always let the user decide wether they open in another tab or not.

**Comment by digitalcraftsman** [comment]
This issue will become irrelevant with the revised menu structure of @rdwatters . Shall we close it then?
