### ISSUE TITLE
Add support for language suffixes in filenames (aka support for Apache MultiViews)

### ISSUE THREAD

**Issue by stephenreay** [spf13/hugo#2713]
Apache httpd can serve language-negotiated content based on a Browser's Accept-Language headers, if we tell it how to find language-specific content for a given URL.

This can be achieved via maps (typically *.var files), or MultiViews (see http://httpd.apache.org/docs/2.4/content-negotiation.html)

maps require an additional file per language-agnostic URL (i.e. if you have /foo for EN and FR, you need a `foo.var` file with references to the two language files)

MultiViews simply requires that each .html file be named with the language code e.g. `/foo` would search and match against `foo.en.html` or `foo.fr.html` or `foo.html.en` or `foo.html.fr`, `/foo.html` would match against  `foo.html.en` or `foo.html.fr`

Use of either of the above techniques can also deliver "pretty" URLs without the need for the name/index.html pattern. Obviously, it will only work when served via Apache configured properly, but I imagine that not needing to handle this option in conjunction with "pretty" URLs can simplify things a bit.

**Comment by bep** [comment]
I thinkg the *.var approach wold fit nicely into my thoughts here:

https://discuss.gohugo.io/t/custom-output-content-types/4584

Instead of creating lots of special Apache and nginx etc. features, we should aim for a solution where the en user can help him/herself.

**Comment by stephenreay** [comment]
I like that approach. I did briefly try to find how non-html pages are currently generated to see if it's generic enough to adapt.

The map approach also allows the use of directories, if the user still wanted (or implementation requires) the /prefix/ directory rather than a filename suffix.

**Comment by bep** [comment]
I think that feature is a natural next step for Hugo 0.19 -- we just need to get the big changes in the pipeline out in the open.

**Comment by stephenreay** [comment]
Unfortunately no, it has to be per URL, which basically means one per language-agnostic 'page', and theoretically one per language-agnostic 'resource' (i.e. if you made the same content available via json or xml or html) - Content Negotiation is about serving the most appropriate content based on the various Accept* headers, not just Accept-Language.

However, it seems unlikely the other use-cases are even remotely common for Hugo users.

**Comment by bep** [comment]
This should now be possible with custom output formats.

**Comment by porridge** [comment]
@bep can you please point to an example of how to achieve this? It's not obvious to me after skimming through https://gohugo.io/templates/output-formats/
