### ISSUE TITLE
docs: some previous/next links incorrect

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/hugo#2714]
Some "Previous" and "Next" links in the documentation seem incorrect. The fairly large size of the following body of errors seems to imply that further automation (of some kind) might help.

The errors:
1. Outside any group, the following (perhaps wrongly) lack any "Previous" and "Next" links:
    1. Press & Articles;
    1. Tools;
    1. Hugo Cmd Reference.

1. In the About Hugo and Troubleshooting groups:
    1. Release Notes lacks a "Next" link; this should link to Hugo Roadmap (in the About Hugo group);
    1. Accented Categories lacks a "Previous" link; this should link to Strange EOF error (in the Troubleshooting group); and
    1. All the other entries should have both "Previous" and "Next" links, but lack them.

1. In the Taxonomies group:
    1. For Overview, "Previous" links to Custom 404 page; instead, it should link to Debugging (both in the Templates group).

1. In the Community group:
    1. For Mailing List, "Previous" links to URLs; instead, it should link to Custom robots.txt (both in the Extras group).

1. In the Content group:
    1. For Front Matter, "Previous" links to Organization; instead, it should link to Supported Formats;
    1. For Markdown Extras, "Next" links to Example; instead, it should link to Multilingual Mode;
    1. For Multilingual Mode, "Previous" links to Summaries; instead, it should link to Markdown Extras; and
    1. For Example, "Previous" links to Summaries; instead, it should link to Multilingual Mode.

1. In the Templates group:
    1. For Ace templates, "Next" links to Functions; instead, it should link to Amber templates;
    1. For Amber templates, "Previous" links to Go Template Primer; instead, it should link to Ace templates;
    1. For Functions, "Previous" links to Go Template Primer; instead, it should link to Amber templates; and
    1. Debugging lacks a "Next" link; this should link to Overview (in the Taxonomies group).

1. In the Tutorials group:
    1. For Creating a New Theme, "Next" links to Hosting on GitHub; instead, it should link to Hosting on Bitbucket;
    1. For Hosting on GitHub:
        1. "Previous" links to Creating a New Theme; instead, it should link to Hosting on Bitbucket; and
        1. "Next" links to How to contribute; instead, it should link to Hosting on GitLab.
    1. For How to contribute, "Previous" links to Hosting on GitHub; instead, it should link to Hosting on GitLab;
    1. Multilingual Site lacks a "Next" link; this should link to Deployment with rsync;
    1. For Deployment with rsync:
        1. "Previous" links to Automated deployments; instead, it should link to Multilingual Site; and
        1. "Next" links to Creating a New Theme; instead, it should link to Troubleshooting Overview (in the Troubleshooting group).

1. In the Extras group:
    1. For Aliases, "Previous" links to Ordering; instead, it should link to Structure & Methods (both in the Taxonomies group);
    1. For Permalinks, "Next" links to Shortcodes; instead, it should link to Pagination;
    1. For Pagination, "Previous" links to Shortcodes; instead, it should link to Permalinks;
    1. For Scratch, "Next" links to Data Files; instead, it should link to Shortcodes;
    1. For Shortcodes:
        1. "Previous" links to Permalinks; instead, it should link to Scratch; and
        1. "Next" links to Pagination; instead, it should link to Data Files.
    1. For Data Files:
        1. "Previous" links to Scratch; instead, it should link to Shortcodes; and
        1. "Next" links to Data-driven Content; instead, it should link to Syntax Highlighting.
    1. For Syntax Highlighting:
        1. "Previous" links to Data-driven Content; instead, it should link to Data Files; and
        1. "Next" links to Table of Contents; instead, it should link to Data-driven Content.
    1. For Data-driven Content:
        1. "Previous" links to Data Files; instead, it should link to Syntax Highlighting; and
        1. "Next" links to Syntax Highlighting; instead, it should link to Table of Contents.
    1. For Table of Contents:
        1. "Previous" links to Syntax Highlighting; instead, it should link to Data-driven Content; and
        1. "Next" links to URLs; instead, it should link to Traversing Local Files.
    1. For Traversing Local Files:
        1. "Previous" links to URLs; instead, it should link to Table of Contents; and
        1. "Next" links to Mailing List (in the Community group); instead, it should link to URLs.
    1. For URLs, "Previous" links to Table of Contents; instead, it should link to Traversing Local Files.

**Comment by digitalcraftsman** [comment]
This issue will become irrelevant with @rdwatters restructering of the docs. Shall we close it then?
