### ISSUE TITLE
Serve static/index.html when there is no layouts/index.html

### ISSUE THREAD

**Issue by philc** [spf13/hugo#2716]
My team uses `hugo --watch` as a live-reloading workflow for web development. We place files in the `static` directory and the browser is auto-refreshed if it has any of the files in `static` open. 

Even if static/index.html exists, when `hugo server` first starts up, curling localhost:1313/index.html returns an empty page. However, if static/index.html is modified while the server is running, it will then get served on localhost:1313. Note that the layouts directory is empty.

The expected behavior is that static/index.html is served when navigating to localhost:1313/index.html.

**Comment by bep** [comment]
This should be fixed by https://github.com/spf13/hugo/commit/3b42640e3fb914aa48ae8036d2cb774cb45892de
