### ISSUE TITLE
Params not working anymore

### ISSUE THREAD

**Issue by ePirat** [spf13/hugo#2718]
I've just updated to latest HEAD to try out the new Node features and realized that suddenly
`{{ .Site.Params.someThing }}` is not working anymore.
Was this removed and if yes, what is the proper replacement? Or is this a regression?

**Comment by bep** [comment]
What is the definition of "just" in your book?

**Comment by bep** [comment]
Also see https://github.com/spf13/hugo/commit/e1da7cb3204c6d232f4a1bdbf89ce75d8459a8b8

**Comment by ePirat** [comment]
> What is the definition of "just" in your book?
right now

Thanks, I've switched to `{{ .Site.Params.something }}` and it works fine again.

**Comment by bep** [comment]
>Thanks, I've switched to {{ .Site.Params.something }} and it works fine again.

That is not helping me very much. Do you mean that the CURRENT master doesn not work with `someThing` typed params? Can you show me your project/site to I can test it?

**Comment by ePirat** [comment]
> Do you mean that the CURRENT master doesn not work with someThing typed params?
Yes, this is what I have in my config:

```toml
[params]
  tagLine = "Random thoughts and ideas about development, programming and other stuff."
```

and what I had in my template:

```
{{ .Site.Params.tagLine }}
```

Hugo version gives me:
Hugo Static Site Generator v0.18-DEV BuildDate: 2016-11-22T16:22:17+01:00

(Used go get to build it, so I expect it uses the current master)

**Comment by bep** [comment]
>so I expect it uses the current master

Expecting is not very scientific. I would have a look at the options to `go get`. Also, if you build Hugo with `make` you will get the Git hash as part of the output in `hugo version` -- and then you will *know* what version you are running.

**Comment by ePirat** [comment]
Ok, did what you suggested and can confirm that the commit you mentioned fixed the issue.

Works fine with v0.18-DEV-E1DA7CB

**Comment by bep** [comment]
Thanks!
