### ISSUE TITLE
hugo new content creates slices with closing bracket on new line

### ISSUE THREAD

**Issue by christophermancini** [spf13/hugo#2720]
When you create a new content file using Hugo new, it takes empty slice values and places the closing bracket on the next line for TOML. This is new behavior and messes up my automation for one of my sites.

old way:
```
tags = []
```

new way:
```
tags = [
]
```

Is there a flag / config value I can set to go back to the old way? I dug in the code but I could not pinpoint exactly where this change occurred, possible that it happens in a dependency.

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting.
