### ISSUE TITLE
Docs: Can the sidebar be changed based on tag or category?

### ISSUE THREAD

**Issue by chankeypathak** [spf13/hugo#2721]
I'm using the Hugo Docs' theme for my website.

Now my plan is to have two different layouts.

Let's say my site offers "Documentation" and "How to Articles".

I'm using Hugo Docs theme for Documentation. So all of my docs look like https://gohugo.io/overview/introduction/.

Notice the sidebar. The documentation topics will go in sidebar.

Now for the "How to Articles" I want different topics in the sidebar.

At presents all the content, be it Documentation or How to Articles, is appearing in the sidebar.

How can I make something such that docs and How to Articles have different sidebar?
Documentation (sidebar A which contains introduction, quickstart and some_more_doc)

example.com/overview/introduction
example.com/overview/quickstart
example.com/something/some_more_doc
How to Articles (sidebar B which contains how-to-do-this, how-to-do-that)

example.com/blah/how-to-do-this
example.com/woo/how-to-do-that

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
