### ISSUE TITLE
Don't ERROR log deprecated warnings, but make sure they are visible

### ISSUE THREAD

**Issue by cdupont** [spf13/hugo#2726]
Running Hugo on Travis I got the error:
```
ERROR: 2016/11/23 11:30:01 general.go:236: .Page's RSSlink is deprecated and will be removed in a future release. Use RSSLink instead.
```
It gives an exit code 255, which puts Travis in error.

**Comment by bep** [comment]
I will find a milder way to report those deprecated errors. But the error message is pretty clear and easy to fix, alternatively you could use a stable release.
