### ISSUE TITLE
Allow 'jekyll import' to accept both  2006-01-02 and 2006-1-2 date format

### ISSUE THREAD

**Issue by kongakong** [spf13/hugo#2738]
I have some markdown files in my jekyll site that do not follow the yyyy-mm-dd date format convention. 'hugo import jekyll' will fail with this error message:

    import_jekyll.go:390: Failed to parse filename '2012-7-8-p-26697918479.markdown': parsing time "2012-7-8": month out of range. Skipping

It is better if the import tool can be more flexible when it comes to handling date in the file name.

**Comment by bep** [comment]
I don't know the Parse method good enough to know for sure that this change will not break the old date format, so without some kind of test that tests both variants, I cannot merge this as is.
