### ISSUE TITLE
Issue with mixed case params in nested template func invocations

### ISSUE THREAD

**Issue by digitalcraftsman** [spf13/hugo#2740]
The [Steam theme](https://github.com/digitalcraftsman/hugo-steam-theme) allows users to choose between a variety of base colors in the config file, e.g.

```toml
[params]
themeColor = "red"
```

Based on that I include the corresponding partial:

    {{ partial (printf "themes/%s-theme" .Site.Params.themeColor) . }}

However, the problem is that `themeColor` doesn't work with camelCase. Hence Hugo displays a bunch of error messages because no partial called `nil` can be found. Lowercasing the variables solves this issue. 

#1129 and #2590 describe similar problems and should be fixed by #2717.

The original theme issue is digitalcraftsman/hugo-steam-theme#13

/cc @mdhender

**Comment by bep** [comment]
>and should be fixed by #2717.

And?

**Comment by digitalcraftsman** [comment]
I deleted my old Hugo version and compiled the latest version of master. Lowercasing `themeColor` in the template solved the problem. This issue could be closed if @mdhender's isn't facing this issue anymore in this setup.

**Comment by bep** [comment]
>Lowercasing themeColor in the template solved the problem. 

What is a workaround. I have added a PR to fix this issue.
