### ISSUE TITLE
Allow default title to have initial caps

### ISSUE THREAD

**Issue by mdhender** [spf13/hugo#2743]
Would like to specify the name of new content in all lower case and have the default title created in the front matter converted to initial caps.
```
$ hugo new post/init-caps.md
```
Current output:
```
+++
date = "2016-11-27T18:58:19-06:00"
title = "init caps"

+++
```
Would like to see
```
+++
date = "2016-11-27T18:58:42-06:00"
title = "Init Caps"

+++
```

**Comment by bep** [comment]
Note that title casing is a style not used in all languages, also title casing isn't probably what you really want in this case, see #989.

So, to get this right would be a challenging task.

**Comment by mdhender** [comment]
If no one objects, I'll name the config option "newContentTitleFormat" with this fix looking for "initCaps". That way I can avoid title case completely.

**Comment by bep** [comment]
This will be handled in round-about way in #2746
