### ISSUE TITLE
Garbled TOML archetype parsing in hugo new

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2745]
See https://discuss.gohugo.io/t/hugo-new-command-scrambles-front-matter/4682

Probably an issue with the new TOML lib. We should report it there, but a fix for this is more likely a proper fix for #452 -- which we may just have to do now.

```

I spent some time working out a good set of archetypes, with menu entries placed last.
However, "hugo new " scrambles the order of the fields badly.

For example, I have a review archetype:

+++
tags = ["review", "opinion"]
categories = ["reviews"]
type = "page"
[menu.main]
weight = 99
name = "menu name"
parent="parentid"
+++

If I run "hugo new page/writing/new_story.md" and then look at the file, it looks like this:

+++

categories
= ["reviews", ]
parent = "parentid'
[menu.main]
type = "page"
tags = ["review", "opinion"]

+++

Sometimes it is worse.

Any ideas?
```

Probably related to

**Comment by kaushalmodi** [comment]
I have been seeing this too (on v0.17 too). The TOML front matter always comes up in random order.

**Comment by bep** [comment]
@kaushalmodi ordering of the TOML isn't this issue, but #452 -- and, btw, it isn't random, the order is undefined. Which is different.

**Comment by kaushalmodi** [comment]
@bep Thanks. I realize that I already had commented on that issue thread too.

**Comment by moorereason** [comment]
This may be fixed by https://github.com/pelletier/go-toml/pull/111

**Comment by bep** [comment]
I have updated go-toml, would be cool if someone could test it out.

**Comment by bep** [comment]
This looks to be working fine with the latest Hugo.
