### ISSUE TITLE
TOML array not parsed

### ISSUE THREAD

**Issue by stp-ip** [spf13/hugo#2752]
Within my front-matter I have the following toml:
```
+++
title = "$title"
joined = "2011-01-01"
img = "3.jpg"
position = "$position"
social = [
  ["fa-twitter", "#"],
  ["fa-facebook", "#"],
  ["fa-linkedin", "#"]
]
+++
```
Rendering {{ .Params }} returns an empty social [ ].

I retried using yaml:
```
---
title: "$title"
joined: "2011-01-01"
img: "3.jpg"
position: "$position"
---
social:
  -
    - "fa-twitter"
    -  "#"
  -
    - "fa-facebook"
    -  "#"
  -
    - "fa-linkedin"
    -  "#"
---
```

Version used: Hugo master and Hugo 0.17 were tested. Both render an empty social [  ].

**Comment by bep** [comment]
This was fixed like in the last week -- are you **really** sure you have tested this with the latest Hugo?

**Comment by stp-ip** [comment]
Will definitely recheck, but I did use "go get -u + go build, which should have updated and rebuild".

**Comment by stp-ip** [comment]
Hugo Static Site Generator v0.18-DEV BuildDate: 2016-11-30T08:57:46Z

**Comment by stp-ip** [comment]
git log for the golang source: "971d1ba commands: Add noChmod option to disable perm sync"

**Comment by bep** [comment]
That is sadly not a proof since the fix was in the go-toml library. We use govendor to do vendoring, and I must admit that I'm no expert here ... But the makefile should help out.

**Comment by stp-ip** [comment]
Triple checked. Updated go vendor, updated deps, rebuild. Using make and without. Toml still comes up empty.

**Comment by stp-ip** [comment]
Might this be an issue with using arrays within arrays? It seems with the right syntax on both yaml and toml, both return an empty array.

**Comment by bep** [comment]
You are right, Hugo does something weird in this case.

**Comment by bep** [comment]
@moorereason I'm pretty sure this is not a 0.18 regression.
