### ISSUE TITLE
Pagination breaks when using ugly + relative URLs

### ISSUE THREAD

**Issue by Scefing** [spf13/hugo#2753]
Using Hugo Dev 0.18.

If you direct a link, to, say, `post.html` for posts, the resulting pagination will be created as `post.html/PAGINATION/NUMBER` if the pagination is set relatively (e.g. as `/page`). This breaks all pagination on such pages.

For `index.html`, the pagination expects there for be an `index` folder containing the `post` folder in the site directory, as well. However, hugo understands at least to use `index` rather than `index.html`.

**Comment by bep** [comment]
What exactly do you mean by "pagination is set relatively (e.g. as /page)"? How do you set pagination relatively?

**Comment by Scefing** [comment]
If `paginatePath` is set to simply `page` I've found that it breaks under relative URLs, since I'm not using an explicit base URL.  Any pagination URL links to a top level non-existent `http://page/NUMBER`.

If you set to it `/page` however, under 0.17 the pagination using relative URLs would work correctly except for the first page of the main page (because it would refer to `./`, which is the top level folder rather than an html file). I think this is because Hugo considers `/page` to mean "the page folder after the current URL" rather than `http://page`.

This breaks under 0.18, but there seems to be no good way of getting around it since `paginatePath = "page"` will still give `http://page/NUMBER`.

**Comment by bep** [comment]
OK, I will check ... and fix, but the paginatePath isn't supposed to (in my head) contain any slashes.

**Comment by bep** [comment]
@Scefing By relative you mean having no (or empty) `baseURL`? If that is the so, that is currently not supported. Or the behavior is undefined.

**Comment by moorereason** [comment]
@Scefing,
We're awaiting your feedback to help define this issue.

**Comment by Scefing** [comment]
Terribly sorry, holidays got ahead of me. And yes, I mean with no (or an empty) baseurl.

**Comment by bep** [comment]
The behaviour with empty baseURL isn't defined.
