### ISSUE TITLE
Check RSS 

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2761]
https://discuss.gohugo.io/t/hugo-0-18-release-scheduled-for-mon-19th-december-please-help-test-test-test/4726/19

**Comment by bep** [comment]
Cannot reproduce, suspect and oldish version for the user reporting this. I fixed these RSS issues fairly late in the game.

**Comment by hnarayanan** [comment]
This is likely true. I will investigate this on my own. Thanks.
