### ISSUE TITLE
Watch doesn't always watch on Ubuntu 16.04

### ISSUE THREAD

**Issue by anagio** [spf13/hugo#2774]
My local machine runs Ubuntu 16.04.1 LTS, with Hugo version `Hugo Static Site Generator v0.17 BuildDate: 2016-10-07T10:46:29-04:00`

`hugo server --renderToDisk` was working but seems to have stopped. I've also tried `hugo server`. Hugo says `Watching for changes in /home/peter/project/{data,content,layouts,static,themes}` but making edits doesn't rebuild. I'm also using sublime 3

However if I edit my `config.yml` it's updated. 

My `go env`

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build618227981=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by digitalcraftsman** [comment]
Is this still an issue with Hugo v0.20.* ?

**Comment by anagio** [comment]
No it is not, Hugo is watching and working.
