### ISSUE TITLE
docs: Fix querify docs

### ISSUE THREAD

**Issue by madhead** [spf13/hugo#2780]
ver
    Microsoft Windows [Version 10.0.10586]

    hugo version
    Hugo Static Site Generator v0.17 BuildDate: 2016-10-07T15:45:26-04:00

Trying to use `querify` function, literally as in the docs:

    <a href="https://www.google.com?{{ (querify "q" "test" "page" 3).Encode | safeHTML }}">Search</a>

Getting this error while rendering:

    ERROR: 2016/12/12 16:35:33 template.go:132: template: theme/partials/post_meta.html:38:66: executing "theme/partials/post_meta.html" at <3>: can't evaluate field Encode in type string in theme/partials/post_meta.html

Does it look like `querify` returns string instead of `Values`?

**Comment by bep** [comment]
>Does it look like querify returns string instead of Values?

Yes. The docs is broken.

**Comment by madhead** [comment]
Is `Encode` redundant? The result of 

    <a href="https://www.google.com?{{ (querify "q" "test" "page" 3) | safeHTML }}">Search</a>

is

    <a href="https://www.google.com?page%3d3%26q%3dtest">Search</a>

Which does not look valid too...

**Comment by bep** [comment]
See https://github.com/spf13/hugo/commit/7862de91de5d8d8d6e00804f8352bd665d86d202

**Comment by madhead** [comment]
`safeURL`, thanks!

**Comment by madhead** [comment]
Sorry, didn't notice, that the title was changed

**Comment by digitalcraftsman** [comment]
Isn't this issue fixed by #2782

**Comment by madhead** [comment]
It should be closed automatically, based on a commit message pattern (`Fix #issue`)...

**Comment by digitalcraftsman** [comment]
In the GitHub docs I only saw that this pattern is only possble in the [commit message](https://help.github.com/articles/closing-issues-via-commit-messages/).
