### ISSUE TITLE
regression: IsTranslated can be wrong for "node types"

### ISSUE THREAD

**Issue by pierreozoux** [spf13/hugo#2812]
Hello and thanks for the great work :)

I have a quick question (referring to [this issue](https://git.indie.host/meta/website/issues/14) )

Our website is printing a little icon "fr" link for french translation of the home page.
(You can see it in action here: https://indie.host/ on the top right)
This was built with 0.17.

I just tried with 0.18, and the "fr" link disappeared.
I checked the value of "IsTranslated" and it is to false.

Could you tell us what happened during the upgrade, and what can we do to fix?

You can find the code for the website here:
https://git.indie.host/meta/website/tree/master

Thanks a lot!

**Comment by bep** [comment]
Hey and thanks for the bug report.

It is the `IsTranslated` that is faulty.

In your case you can just remove this:

```
   {{ if .IsTranslated }}
```

If you want to replace that conditional until we get a fix for this, you can do something like this:

```
   {{ if gt (len .Translations) 0 }}
```

**Comment by bep** [comment]
Note to self, the `IsTranslated` func actually looks correct, so there must be something other going on. (but the workaround still holds)

**Comment by bep** [comment]
OK, now I see it. IsTranslated is wrong for sites with only 1 translation.

**Comment by pierreozoux** [comment]
Happy that it helped! And thanks for your reactivity!
