### ISSUE TITLE
Add support for JSON output

### ISSUE THREAD

**Issue by Thomasdezeeuw** [spf13/hugo#2813]
I'm looking to add support for loading pages with Javascript for my website. Mainly by loading a JSON file rather then the complete page. I'm looking for support for outputting JSON, something along these lines:

```json
{
	"title": "Hello World",
	"html_body": "<h1>Hello world</h1><p>Hello</p>",
	"url": "/hello_world"
}
```

The `html_body` would be the page body in HTML, excluding the header, footer etc. So basically the rendered content of a page.

And possibly timestamps for the publish date and last edited date.

I'm willing to contribute the code if you agree this can be something useful (and maybe give me some pointer as to where to start).

**Comment by bep** [comment]
This is supported in a roundabout way (use the search at the forum) -- and we will implement a better and more general solution.

**Comment by Thomasdezeeuw** [comment]
@bep I'm not sure which thread you had in mind, but I can't find much. I found https://discuss.gohugo.io/t/generating-json-for-consumption-by-javascript-framework/195/7, but it doesn't seem to have a conclusion. I also found your post regarding search using JSON, https://discuss.gohugo.io/t/simple-json-site-index-in-hugo/2854, but it's not what I'm looking for.

Could you point me to a thread that you had in mind?

**Comment by bep** [comment]
>Could you point me to a thread that you had in mind?

I would have to search for it, too, so no.
