### ISSUE TITLE
docs: Fix GitInfo on docs build server

### ISSUE THREAD

**Issue by Jos512** [spf13/hugo#2829]
The docs are of good quality, there's no doubt about that. But the "Last revision" date in the bottom of the post is very often wrong.

For example, the [template functions](https://gohugo.io/templates/functions) page was last revised on September 20, 2015. But it contains information about `partialCached` and the fact that every page now has a `Kind` attribute. Those things were introduced with Hugo 0.18 that was released on December 19, 2016. So that page is much more up to date than 1+ year ago.

Perhaps the "Last revision" date isn't seen as important for those who contribute to the docs. That's okay and I don't look at that negatively. But then I would suggest to drop the "Last revision" line. 

(I'm concerned that those 15 month old revision dates can give people that consider using Hugo the impression that nothing new or improved happened, which is far from the case.)

**Comment by bep** [comment]
You have right -- we have fixed this with the GitInfo feature -- but Git isn't installed on the docs build server (I think), @spf13 is working on it (I hope).

**Comment by digitalcraftsman** [comment]
@rdwatters currently you're using the [date defined in `.lastmod` or `publishDate` ](https://github.com/rdwatters/hugo-docs-concept/blob/master/layouts/partials/content-footer.html#L1) in your docs revision. Shall we make use of the `.GitInfo` feature (which requres Git to be installed)?

**Comment by bep** [comment]
1) Use `Lastmod` only.
2) Do not put `enableGitInfo` in site config (we set it as a flag when building)

**Comment by rdwatters** [comment]
> 1. Use Lastmod only.

This is currently what I am doing to write the date to the page. Thanks @digitalcraftsman 

> 2. Do not put `enableGitInfo`

Thank you for noting this, @bep. I will make sure not to use this in the docs concept.

**Comment by rdwatters** [comment]
Per the above 2 requirements from @bep , I'm closing this. It's a non-issue in the new docs site and use of `lastmod` will not change with @budparr 's theme changes.
