### ISSUE TITLE
Implement semver

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2832]
Looks like we need to do some bugfix releasing, and with the new and simpler docs versioning, that may be feasible.

So we may have a `Hugo 0.18.1` etc.

**Comment by bep** [comment]
I want to add some kind of `semver` lib to Hugo, I found these candidates (there are more):

* https://github.com/blang/semver
* https://github.com/Masterminds/semver

The former have more stars, but I kind of like the last one: It supports "v" prefix and have caret and tilde support in its range matching.

Thoughts anyone?

/cc @moorereason

**Comment by moorereason** [comment]
Yes, yes, yes!  We should be using Semantic Versioning.

Read [this](https://blog.gopheracademy.com/advent-2016/saga-go-dependency-management/) if you haven't yet.  It looks like [gps](https://github.com/sdboyer/gps) will be the basis of whatever gets merged into the go tool chain, and gps uses https://github.com/Masterminds/semver.

However, what's the point of using a semver library in Hugo?  Why do we need to parse semver?  All Hugo needs is a version string.  What are you wanting to do other than just using a proper vMAJOR.MINOR.PATCH release version and creating a git tag?

**Comment by bep** [comment]
>What are you wanting to do other than just using a proper vMAJOR.MINOR.PATCH release version and creating a git tag?

I'm currently doing calculations on "what is next release version" and "is this theme compatible with the current Hugo version?" That math is trivial with the current versioning scheme; it's not too hard with 3 digits, either, but it gets complicated once we get some range logic.
