### ISSUE TITLE
hugo themes installation

### ISSUE THREAD

**Issue by Adeel992** [spf13/hugo#2840]
I want to know that when i'm using $ cd themes command for themes installation, then why i face "$ is not recognize" error.
![hugo](https://cloud.githubusercontent.com/assets/19798126/21494902/5d39a024-cc36-11e6-9b00-d6166cdf350f.jpg)

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
