### ISSUE TITLE
Improve .Site.GetPage so it can get a specific regular content page

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2844]
See https://discuss.gohugo.io/t/can-we-use-hugo-commands-in-markdown-files/4937/2

**Comment by bep** [comment]
We should probably build some kind of index (a map?) if this is going to be used a lot.

**Comment by vjeantet** [comment]
Maybe we can use last `outputFormats` feature to generate the required "index" ?

I try to generate a json file with all the information about pages, it generate the correct file in public/idx/pages.json but impossible to use/reference this folder it in templates. (egg and chicken problem ?)

**Is there a way to generate an outputFormat to `data` dir ?**

**Is there a way to order outputFormats'runs ?** (to be sure that my generate date are created before used by other templates..)

```
[outputFormats.IDXPAGES]
MediaType = "application/json"
BaseName = "pages"
IsPlainText = true
Path = "idx"
```

**Comment by bep** [comment]
> (egg and chicken problem ?)

Yes. Output format is a _rendering format_, so your thoughts would only make sense if you build the site several times and route the output to data to first n times ...

But in any case, what you are talking about (not sure what) is not covered by this issue, and probably belong in discussion form.
