### ISSUE TITLE
proposal: Rename labels  from is/bug => Bug

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2849]
To make them more URL friendly. Right now, we get:

```
https://github.com/spf13/hugo/labels/is%2Fbug
```

**Comment by bep** [comment]
Or, probably better, do as the Go stdlib and do `Bug`, `WaitingForFeedback`, `NeedsFix`etc.

**Comment by moorereason** [comment]
Updated the labels.  With a small number of labels, I think we're okay removing the `status` prefix.  All of the `status` labels are light colored now.  All others are darker.

LGTM :+1:
