### ISSUE TITLE
Forced injection of meta[name="generator"] tag in <head> is surprising/befuddling

### ISSUE THREAD

**Issue by chbrown** [spf13/hugo#2850]
I'm all for handy helpers like

    {{ .Hugo.Generator }}

which renders to

    <meta name="generator" content="Hugo 0.18" />

but automatically and silently [injecting](https://github.com/spf13/hugo/blob/v0.18/transform/hugogeneratorinject.go#L27) HTML into my pages is a bit surprising, and consequently, annoying.

I can stick in my own meta generator value to satisfy the `metaTagsCheck` regex and escape `HugoGeneratorInject`'s wrath, but apparently I cannot omit the meta generator tag altogether. Doesn't strike me as particularly "[flexible](https://gohugo.io/)".

The meta generator tag is not required as per the HTML spec, as far as I know. Is the injection simply for self-promotional purposes, or is there some loftier reason I'm not aware of?

**Comment by moorereason** [comment]
Use `disableHugoGeneratorInject = true` in your [site config](https://gohugo.io/overview/configuration/).

**Comment by chbrown** [comment]
Ah, okay. I still think it's surprising, and therefore poor default behavior, but I retract my accusation of it being 'not particularly "flexible"'.

And I assume that the answer to my explicit question is: "no"

**Comment by bep** [comment]
>Ah, okay. I still think it's surprising, and therefore poor default behavior

@chbrown We spend many, many, many hours implementing this great and FREE piece of software. It is called open source. I think it is very, very, very little to ask from the users in return to include a Hugo generator meta tag on the home page (i.e. only 1 page).

**Comment by chbrown** [comment]
I know, @bep, I know. I try to help out with this thing called open source too.

[![@chbrown: 1,357 contributions in the last year](https://cloud.githubusercontent.com/assets/360279/21552076/a16989fa-cdc4-11e6-80ec-c9d861fb3fef.png)](https://github.com/chbrown)

I strive to make my contributions as transparent and unsurprising and as broadly applicable as possible.

But then, none of my projects are anywhere nearly as successful as `hugo`, so maybe I'm doing it wrong ;)

I entirely support embedding `{{ .Hugo.Generator }}` in all the [official themes](http://themes.gohugo.io/). But in this particular case, there's just something about sneaking in that tag that rubs me the wrong way.

Anyhow, thanks for all your (plural) work on `hugo`, and thanks to @moorereason for promptly pointing me to the `disableHugoGeneratorInject = true` config option.

**Comment by bep** [comment]
@moorereason I think it is a good rule to have to ALWAYS refer to the discussion forum for questions and similar, even if the answer seems simple and fast to jot down.

**Comment by CelticParser** [comment]
I agree to injecting the generator tag by default. However, it is injected as the very first tag below the `<head>` which is intrusive and does not follow basic protocol. 

I recommend that the generated tag be injected farther down the head tree.

**Comment by midzer** [comment]
Yeah, i think the same like @CelticParser 

A typical HTML5 document in 2018 could start like
```
<!DOCTYPE html>
<html lang="Your language code">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Your awesome title</title>
    <meta name="generator" content="Hugo 0.xx">
```
for example.

"The title element is a required child in most situations" (via https://html.spec.whatwg.org/multipage/semantics.html#the-head-element). So putting `<meta name="generator">` right below it might be a good choice

**Comment by moorereason** [comment]
@CelticParser & @midzer: your comments are off-topic on a really old, closed issue.  Please open a new issue.
