### ISSUE TITLE
Failed to load translations in file "en.yaml". Why?

### ISSUE THREAD

**Issue by frankwang0909** [spf13/hugo#2860]
I'm newer to Hugo, I just did exactly what the Hugo Quickstart Guide (http://gohugo.io/overview/quickstart/) says. Everything went fine until I entered the following code:
"  $ hugo server --theme=hugo-tranquilpeak-theme --buildDrafts  "

I got the following warning:

Started building sites ...
Error: Error building site: Failed to load translations in file "en.yaml": failed to load en.yaml because yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `en-us.yaml` into []map[string]interface {}

I tried to search this, but didn't get anything helpful.
Is there anyone who can help me?

My Hugo Version is   v0.18.1 ;
My PC system is Windows 7;

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
