### ISSUE TITLE
.UniqueID not unique for pages with the same filename in sibling folders

### ISSUE THREAD

**Issue by tjallingt** [spf13/hugo#2861]
I am creating a website using Hugo and noticed that my "read more" list at the end of posts were showing up very empty.
This is an overview of the structure of my content folder:
```cmd
content/
    project/
        test0.md
        test1/
            index.md
            ...
        test2/
            index.md
```
And I was using this code to render my read more block at the end of a post:
```
<div>
	<h1 class="center">Read more</h1>
	<div class="post-list">
		{{ range first 4 (where (where .Site.Pages "Section" .Section) "UniqueID" "!=" .UniqueID) }}
			{{ .Render "summary" }}
		{{ end }}
	</div>
</div>
```
In this simplified example Hugo would render test1 and test2 with only the test0.md summary in the read more block. Test0 correctly shows both test1 and test2's summary in read more.
This leads me to believe that .UniqueId is not including the path correctly in its hash but I don't have enough Go experience to check whether this is true or not.

BTW: happy new years 🍾 🎉

**Comment by digitalcraftsman** [comment]
> This leads me to believe that .UniqueId is not including the path correctly in its hash but I don't have enough Go experience to check whether this is true or not.

You're correct. The "uniqueid" is just the [MD5 hash of the file name](https://github.com/spf13/hugo/blob/7665dd239e825be83c0eabadb914f5859bb902af/source/file.go#L35). You can find the decleration of the variable [here](https://github.com/spf13/hugo/blob/7665dd239e825be83c0eabadb914f5859bb902af/source/file.go#L140).
