### ISSUE TITLE
docs: `Params.toc` versus `Params.notoc`

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/hugo#2866]
Hugo's documentation layouts refer to front-matter variable `toc` [here](https://github.com/spf13/hugo/blob/c2bf748ec5ca662384953ec3fe4345218afb71b1/docs/layouts/_default/baseof.html#L2). This variable first appeared in commit be4f486 (I think).

Front-matter variable `notoc` was used earlier. It remains in [fifteen (15) content pages](https://github.com/spf13/hugo/search?utf8=%E2%9C%93&q=notoc&type=Code), as well as in Hugo's [Go templates docs page.](https://github.com/spf13/hugo/blob/26084ad198044519e10b96ac5432be874c0ae1b4/docs/content/templates/go-templates.md#L364)

Do these two front-matter variables have different purposes? Alternatively, should one variable's usage instances be changed perhaps to the other?

**Comment by bep** [comment]
Remove the notoc.

**Comment by digitalcraftsman** [comment]
This issue will become irrelevant with @rdwatters docs revision. Shall we close it then?
