### ISSUE TITLE
release for linux has changed and breaks automation

### ISSUE THREAD

**Issue by chaseadamsio** [spf13/hugo#2877]
versions 0.16, 0.17 and 0.18 have different naming schemes for the Linux releases which makes upgrading versions a "moving target". As an example, today I wanted to upgrade to 0.18 in my GitLab ci build and had to change the following:

- for getting the tarball I had to change the case of `linux` => `Linux` _and_ the `_amd64` to `64bit` 
- once the tarball is extracted, I thought the naming convention would continue, but the extracted directory is the old `linux_amd64`

Is the release schema change something we should expect or is it possible we can always normalize the version to the correct/same name as we had previously?

**Comment by bep** [comment]
hugo_0.18.1_Linux-64bit.tar.gz
hugo_0.18_Linux-64bit.tar.gz
hugo_0.17_Linux-64bit.tar.gz

It changed in 0.17 -- but we have found a "Hugo standard".
