### ISSUE TITLE
docs: _index.md etc... About behavior changed from 0.18

### ISSUE THREAD

**Issue by koba-ninkigumi** [spf13/hugo#2878]
0.18以降で挙動が変わって悩んでいる迷える子羊はどれぐらいいるんだい？
俺が 0.19 Dev で index.html を作成する Best Practice を教えてやるぜ！

http://qiita.com/koba_ninkigumi/items/40ad864c34d06337b24f

でも俺は英語が苦手だから誰か英語に翻訳して欲しいんだ。
よろしく頼むぜ！

このサンプルを使えば、君もきっと理解できるさ！
https://github.com/koba-ninkigumi/hugo-sample-0.19

もしまたいつか挙動を変えるなら、今度はドキュメントにもちゃんと掲載しといてね。

日本語が苦手なあなたへ
https://translate.google.com

**Comment by bep** [comment]
Please keep this discussion on the forum -- and in English, please.
