### ISSUE TITLE
Minor - Comment modification - metadata date - create/content.go

### ISSUE THREAD

**Issue by magikstm** [spf13/hugo#2885]
I would replace the current comment with these:

> metadata date needs to be formatted to RFC3339 for some formats. It is a profile of ISO 8601 and it has some minor differences.
> Ref: http://stackoverflow.com/questions/522251/whats-the-difference-between-iso-8601-and-rfc-3339-date-formats
> Ref: https://tools.ietf.org/html/rfc3339

> // TOD(bep) what is this?
> 	if x := parser.FormatSanitize(viper.GetString("metaDataFormat")); x == "json" || x == "yaml" || x == "toml" {
> 		metadata["date"] = date.Format(time.RFC3339)
> 	} else {
> 		metadata["date"] = date
> }

**Comment by bep** [comment]
Closing, ref comment on #2897
