### ISSUE TITLE
hugo supports mathjax, but doesn't show matrix correctly

### ISSUE THREAD

**Issue by caijun** [spf13/hugo#2893]
I create a post with following mathjax code

```
$$
        \begin{matrix}
        1 & x & x^2 \\
        1 & y & y^2 \\
        1 & z & z^2 \\
        \end{matrix}
$$
```

but the rendering result shows all the elements of the matrix in one line:

![image](https://cloud.githubusercontent.com/assets/2522593/21651673/802c59fa-d2e4-11e6-923c-0c51bb98cb2f.png)

Does anyone know how to make `\\` into effects?

**Comment by caijun** [comment]
This can be solved by adding `<div></div>`. Another example may better demonstrate my problem.

```
$$
\begin{equation}
\begin{aligned}
  & \frac{dy}{dt} = f(t, y) \\
  & y(t_0) = y_0
\end{aligned}
\label{eq1}
\end{equation}
$$
```

The above mathjax code produces following equations

![image](https://cloud.githubusercontent.com/assets/2522593/21652232/decd4968-d2e6-11e6-8a0a-ab9fe75c1a87.png)

I would like each equation is displayed in one line.

**Comment by moorereason** [comment]
@caijun,
Can you show us the generated HTML for a minimal example?  And show us the HTML of how you currently work around it.

**Comment by caijun** [comment]
Yes.

The following is my post on this question.

http://tonytsai.name/Test-MathJax.md

and my MathJax support is configured in the `footer.html`. The following is my `footer.html`.

 http://tonytsai.name/footer.html

The generated HTML is as follows

http://blog.tonytsai.name/blog/2017-01-05-test-mathjax/

**Comment by tpapp** [comment]
@caijun: Wrapping in `<div></div>` (as mentioned [in the manual](https://gohugo.io/tutorials/mathjax/)) works fine for me on `v0.21` with your example.
