### ISSUE TITLE
Build problems on Arch linux

### ISSUE THREAD

**Issue by runical** [spf13/hugo#2900]
Currently hugo 0.18.1 and 0.18 refuse to build on Arch Linux. I think it has to do something with a dependency that has been updated or something similar, but I'm not sure.

The log of the build can be found [here.](https://gist.github.com/runical/db1c02d2075e3c143d2d7a9ccbe56065) Is there are questions, I'm happy to answer them. The PKGBUILD file used can be found [on the AUR](https://aur.archlinux.org/packages/hugo/)

EDIT: The build was done using a clean chroot by the way.

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting.

**Comment by runical** [comment]
The problem is reproducible and not only on my system, so I'm pretty sure it is a bug. But sure, I'll try the forums before trying to reopen this bug report.
