### ISSUE TITLE
Question about Block Template Lookup Order

### ISSUE THREAD

**Issue by VioletVivirand** [spf13/hugo#2920]
Hi! Newbie of Hugo here. I've come up with some questions, hope someone could help me. [Here is my repo](https://github.com/VioletVivirand/hugo-block-template-question), please use it if you wanna reproduce the issue.

First downloaded Hugo (**v0.18.1**), applyed [hugo_theme_robust](http://themes.gohugo.io/robust/), and added a post as the tutorial did.

Then I wanted to try if the Block Template worked or not, so I did these:

1. Duplicated `/themes/hugo_theme_robust/_default/baseof.html`, added something different from the original file (In my repo was `<p>Hello baseof.html!!!</p>`), renamed to `post-baseof.html`, and move to `/themes/hugo_theme_robust/layouts/section/`
2. Duplicated `/themes/hugo_theme_robust/_default/list.html`, added something different from the original file (In my repo was `<p>Hello post.html!!!</p>`), renamed to `post.html`, and move to `/themes/hugo_theme_robust/layouts/section/`

Now I wanna know if the Block Template Lookup Order worked or not. If it worked, when I visit `http://base_url/post`, the page should showed "Hello baseof.html!!!" and "Hello post.html!!!".

The [docs page](http://gohugo.io/templates/blocks/) described the order. After some experiments, and it's the result (Checked means worked, unchecked means not):

- [ ] `/layouts/section/post-baseof.html` (Moved `post-baseof.html` to this path)
- [ ] `/themes/exampletheme/layouts/section/post-baseof.html` (Moved `post-baseof.html` to this path)
- [ ] `/layouts/section/baseof.html` (Rename `post-baseof.html` to `baseof.html`)
- [ ] `/themes/exampletheme/layouts/section/baseof.html` (Rename `post-baseof.html` to `baseof.html`)
- [x] `/layouts/_default/post-baseof.html` (Moved `post-baseof.html` to this path)
- [x] `/themes/exampletheme/layouts/_default/post-baseof.html` (Moved `post-baseof.html` to this path)

(Didn't try the last two because it will override the original `baseof.html`)

So, is it a bug, or I just misunderstood something?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
