### ISSUE TITLE
plainIDAnchors doesn't produce unique IDs

### ISSUE THREAD

**Issue by afeld** [spf13/hugo#2921]
Example:

```markdown
# Foo
## Summary
...
# Bar
## Summary
```

with `plainIDAnchors = true` produces

```html
<h1 id="foo">Foo</h1>
<h2 id="summary">Summary</h2>
...
<h1 id="bar">Bar</h1>
<h2 id="summary">Summary</h2>
```

GitHub Markdown (or Jekyll...I can't remember) would produce `id`s of `summary` and `summary-1`, respectively. Any interest in mirroring that behavior? Thanks!

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by afeld** [comment]
I would consider this a bug...happy to open as a discussion if that's preferred though.
