### ISSUE TITLE
url:  purell.NormalizeURLString throws errors in 0.19-DEV

### ISSUE THREAD

**Issue by kevingimbel** [spf13/hugo#2934]
I am running `v0.19-DEV` on a server to build hugo after pushing to a remote git repository. The `v0.19-DEV` throws errors which appear to come from [url.go line 308-312](https://github.com/spf13/hugo/blob/4352156a2730eddda6b05b66b73d910e4ac9abff/helpers/url.go#L308-L312) but I cannot see/do not understand why they are thrown. 

The errors are: 
```
[...]
ERROR 2017/01/13 12:15:21 Failed to normalize URL string. Returning in = "tags/thoughts"
ERROR 2017/01/13 12:15:21 Failed to normalize URL string. Returning in = "categories/thoughts"
ERROR 2017/01/13 12:15:21 Failed to normalize URL string. Returning in = "tags/tools"
ERROR 2017/01/13 12:15:21 Failed to normalize URL string. Returning in = "tags/ui"
ERROR 2017/01/13 12:15:21 Failed to normalize URL string. Returning in = "categories/ui/x"
[...]
```
A full gist of all the errors is [available here](https://gist.github.com/kevingimbel/ae9a0e16f9d12d86d737cca3d716d226)

As you can see at the end of the full error log the site is build anyway and it appears most parts work as expected, however, on [kevingimbel.com/projects/](https://kevingimbel.com/projects/) the `{{ .Permalink }}` variable includes `.html` at the end which is not correct (Relevant [template file](https://github.com/kevingimbel/kevingimbel.com/blob/master/themes/kevingimbel/layouts/section/projects.html#L15)). The Project pages are generated without `.html` and are accessible as expected under URLs like [https://kevingimbel.com/projects/go-goserve/](https://kevingimbel.com/projects/go-goserve/).

When I build the site on my local machine using `v0.18-DEV` the content is created without issues and the `{{ .Permalink }}` variable renders without `.html` at the end so I assume this is an issue with the `0.19-DEV` release.

Output of `hugo env`:
```
Hugo Static Site Generator v0.19-DEV linux/amd64 BuildDate: 2017-01-12T20:20:36+01:00
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.7.4"
```

**Comment by bep** [comment]
See https://discuss.gohugo.io/t/started-getting-failed-to-normalize-url-string-returning-in/5034/11
