### ISSUE TITLE
Sidebar's scroll bar on documentation got only one pixel

### ISSUE THREAD

**Issue by Arch-Mage** [spf13/hugo#2938]
The documentation sidebar's scroll bar is very difficult to use because it's got only one pixel. When I take a look at it's stylesheet, the `#sidebar` got `214px` width (see [this](https://github.com/spf13/hugo/blob/master/docs/static/css/style.css#L179)) and the `#main-content` got `200px` margin-left (see [this](https://github.com/spf13/hugo/blob/master/docs/static/css/style.css#L179)), so the scroll bar is eaten.

It's a minor issue though.

**Comment by Jos512** [comment]
I don't see that on FireFox 50.1; the sidebar's scrollbar has the same appearance and size as on other pages.

![Example screenshot](https://cloud.githubusercontent.com/assets/13403160/21975061/c62dcaee-dbca-11e6-8c88-1418e2cdfbb2.png)

**Comment by digitalcraftsman** [comment]
This issue will become irrelevant once the new redesign of @budparr / @rdwatters will be deployed. Shall we close it then?
