### ISSUE TITLE
Is it possible to redirect from a chapter page to a non-chapter page?

### ISSUE THREAD

**Issue by matthewgourd** [spf13/hugo#2942]
Hi there,

I work on the documentation team at Miracl.com. We're thinking of moving our documentation to Hugo but have a requirement for redirects to be set up from chapter pages, so users don't have to read perfunctory intro. text. Is this technically possible? If so, how would I go about doing it? We're using the Learn Theme: https://matcornic.github.io/hugo-learn-doc/cont/pages/

To be more specific, if say a visitor clicks on a chapter named "Registering" containing two sub-pages, one with Android instructions and one with iOS instructions, the visitor should be taken directly to the first sub-page, /registering/registering-android rather than its parent, /registering. Hope that makes sense!

Thanks, 

Matt

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
