### ISSUE TITLE
Is it possible to use content/language/contentfiles.md...

### ISSUE THREAD

**Issue by Dexus** [spf13/hugo#2944]
Hi

i habe a problem or maybe i did not got it how the multilanguage works.

i would like to create a structure for each language and also use the correct name of the directory.

my structure now is:

content/
content/index.en.md
content/index.de.md
content/news/
content/news/index.en.md
content/news/index.de.md
content/news/news.100.en.md
content/news/news.100.de.md

but im not able to change the url for the de-files to use as section: "nachrichten"

Is there a example with more customized ways?

or would it be able to use `content/{en,de...}/` and insert there the correct folders and the translated files?
But without to need a new domain for each translation?

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
