### ISSUE TITLE
hugo serve issue with Gulp

### ISSUE THREAD

**Issue by andi1984** [spf13/hugo#2946]
Steps:

My steps in my project:

- Running `hugo serve`
- Running my gulp file updating `themes/mytheme/static/css/main.css``

The CLI is stating:

> Syncing /css/main.css to /
> Syncing /css to /
> Syncing  to /

This mapping seems to be quite wrong and after this the watcher doesn't seem to work anymore.

**Comment by bep** [comment]
What is the output of `hugo env`?

**Comment by andi1984** [comment]
Hello @bep,

the outpupt is: 

Hugo Static Site Generator v0.18.1 BuildDate: 2016-12-29T18:12:41+01:00
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.7.4"

**Comment by bep** [comment]
OK, what do you mean by 

>This mapping seems to be quite wrong

What did you expect? Remember, it is a virtual file system (memory mapped).

**Comment by andi1984** [comment]
Hmm,

I just wonder what's happening internally. When I change `themes/mytheme/static/css/main.css` via my gulp process the first time it works great and on all following runs it doesn't state that it is syncing something and the changes in the file show no effect in the browser.

So I deduct that the sync mapping seems to get wrong (esp. that a file "main.css" is mapped to a folder?), but not 100% sure about it.

Any ideas why it is not working on following runs when I change the file?

**Comment by andi1984** [comment]
I can confirm that the issue comes with gulp. When I change the file directly via text editor the sync message looks like this instead:

Syncing /css/main.css to /

So this comes from the gulp task itself handling the files.

**Comment by andi1984** [comment]
I close the issue then as it is only partly related to Hugo and impacted by Gulp. But has anybody an idea how to solve the issue?

**Comment by bep** [comment]
I'll reopen to track this. I use Gulp myself for at least bepsays.com -- so I should be able to test it.

**Comment by kevingimbel** [comment]
@andi1984 I am using gulp for CSS and JS modifications, too. So far I never had issues with hugo. If you provide the files I could take a look tonight. ([Here's my gulpfile for reference](https://github.com/kevingimbel/kevingimbel.com/blob/master/themes/kevingimbel/gulpfile.js))

**Comment by andi1984** [comment]
Hi @kevingimbel, thx that you are gonna have a look. My project is this one: https://github.com/andi1984/blog 

The gulpfile is in the root folder and the problem is based on my `gulp css` task. It pushes changes to the `themes/andi/static` folder. Could it be a problem that gulp seems to update the parent directories as well? When I check them via `ls -la` their modified timestamp always updates when I run gulp, so this could be the reason for the 

> Syncing /css/main.css to /
> Syncing /css to /
> Syncing to /

messages going up folder by folder. When we change files directly only the file itself is changed. Maybe that's the difference?

I worked a bit yesterday evening on the gulpfile, but didn't push yet, but I guess the problem is also reproducible in the pushed one, so would be nice if you could have a look. I will push my newer version later today to check whether I introduced the issue with my nightly changes ;)

**Comment by bep** [comment]
@andi1984 https://github.com/andi1984/blog/blob/master/gulpfile.js#L14

You do a clean of ../static before your css task is run -- which seems like overkill. At least it seems to confuse the watcher. It should *maybe* have handled it better, but ...

**Comment by kevingimbel** [comment]
@andi1984 
It appears your gulp tasks are falsy. I wonder what the point of the clear task is - why would you clear the directory? Gulp can and will override files on change so I do not see the point of this tasks. 

When I execute the clear task standalone (`$ gulp clear`) I see that is removes the entire static directory in `themes/andi/` - and I believe this is what makes hugo have a hickup.

```
ERROR: 2017/01/18 17:52:22 hugo.go:867: stat /Users/kevingimbel/Development/test/blog/themes/andi/static/sw.js: no such file or directory
ERROR: 2017/01/18 17:52:22 hugo.go:867: stat /Users/kevingimbel/Development/test/blog/themes/andi/static/sw.js: no such file or directory
ERROR: 2017/01/18 17:52:47 hugo.go:902: open /Users/kevingimbel/Development/test/blog/themes/andi/static/css: no such file or directory
```

```sh
$ ls -l themes/andi/static/
ls: themes/andi/static/: No such file or directory
```

I forked your repository and re-wrote your gulpfile so that it does not use the `clear` task. I also added a watch task because I didn't want to run `gulp` all the time during debugging - for development a watch-task is better anyway. :)

You can see the changed gulpfile with comments [here](https://github.com/kevingimbel/blog/blob/fix-gulpfile/gulpfile.js) - would you try it out and see if it works as expected? Is there any reason you used the clear task? Especially the `force: true` option concerns me - a clean/remove task which has a force option makes me suspicious.

**Comment by andi1984** [comment]
Hi @kevingimbel,

thanks for going so much into detail, really appreciate it!

> I see that is removes the entire static directory in themes/andi/ - and I believe this is what makes hugo have a hickup.

Yes, I also think so… But that's not a bummer for me as you are apparently showing I can rewrite my Gulpfile a bit or create some hugo-serve specific gulp task where I avoid cleaning folders completely by removing it.

The only reason I like to clear folders is about removing potential stale files, but I don't honestly need it during development work, but maybe on production/deployment mode. And it's "only" my personal blog, so I don't really want to overcomplicate things.

Maybe, but that's something you all can decide better, I would vote for that the Hugo watcher can cope with those folder removals, so I leave it open to you to close this issue or go ahead with it later on when you want to tackle that later on, but I can really understand if you don't.

Thx for all!

**Comment by kevingimbel** [comment]
Glad I could help!

I'm not sure if the removal of the `static` folder is an issue for hugo - I think @bep knows more here. It's just my guess because I got the errors I posted above when it was removed. 

I'm not familiar enough with Go to tackle this myself. I might be able to poke around a bit but I honestly don't know how to effectively debug go code or were to start in the fist place. 😊

**Comment by bep** [comment]
Deleting the `static` folder is like removing the branch you're sitting on and will not be supported (by me) in Hugo. This sounds like a strange setup anyway. In normal setups I imagine setting Gulp up to create specific assets to subfolders, say `/static/css`etc., and if you really want to clean stuff, deleting the `css` folder should be enough.

I'm closing this as a problem that lies outside of Hugo.
