### ISSUE TITLE
Preserve query and hash params when redirecting

### ISSUE THREAD

**Issue by TamalSaha** [spf13/hugo#2949]
Hi,
I noticed that if I type url `http://mysite.com/docs?p=abc`, hugo redirects me to `http://mysite.com/docs/`. This also happens for # params. Is there a way to preserve the query & hash params when this redirection happens?

Thanks.

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by TamalSaha** [comment]
I reposted to discuss. But I think it went to moderation queue.
