### ISSUE TITLE
Server local preview normal but push github has no css styles

### ISSUE THREAD

**Issue by jintianme** [spf13/hugo#2950]
I choose serveral different theme, and use those commond:
```
hugo server --theme=mainroad
hugo --theme=mainroad
```
I generated public files, and runserver preview fine, **When push it on github , it just like ancient htmls has no css style**, anybody could help me ? I don't what I miss or did wrong.
![Uploading Screen Shot 2017-01-18 at 10.29.21 PM.png…]()

**Comment by kevingimbel** [comment]
@jintianme You need to use https to request your CSS files. When you open the developer tools in Chrome (or Firefox, Internet Explorer) you see a warning that your site is loaded with https but requests insecure resources from "http://jintianme.github.io"

![screen shot 2017-01-18 at 16 30 46](https://cloud.githubusercontent.com/assets/2161714/22070275/b39c08d2-dd9b-11e6-8009-b7cb9a45ae00.png)

To fix this, you need to set the base url in your config.toml (or config.yaml) file or build our site with

```sh
$ hugo -b="https://jintianme.github.io" --theme=mainroad
```

--- 

In the future consider asking inside the discussion forum at https://discuss.gohugo.io/ for this kind of issues.
