### ISSUE TITLE
Build failure for a site with shortcodes

### ISSUE THREAD

**Issue by peterychuang** [spf13/hugo#2951]
[My site](https://github.com/peterychuang/peterychuang.github.io) cannot be generated with the hugo build from the latest commit (3ac1b9fe33c42f53f90f6868d82450213cf844d7), but it can be built successfully with v.0.18.1.

At build time, one of the following errors is shown.

```
Error: Error building site: Prepare pages failed: ["html/template: cannot redefine \"shortcodes/youtube.html\" after it has executed"]…

Error: Error building site: Prepare pages failed: ["html/template: cannot redefine \"_internal/shortcodes/highlight.html\" after it has executed"]…

Error: Error building site: Prepare pages failed: ["html/template: cannot redefine \"shortcodes/img.html\" after it has executed"]…
```

I find that the site can be built successfully if I remove the pages that uses shortcodes (youtube, img, highlight).

**Comment by bep** [comment]
Will fix, thanks for the report.

**Comment by bep** [comment]
Just wanted to chime in and say that this will be resolved with https://github.com/spf13/hugo/pull/2932 -- It has taken me a little longer than it should, partly because I'm on vacation in a sunny part of the world ... But I have mostly a set of tests to fix before wrapping that one up, so it should happen in the next few days,

**Comment by Tristor** [comment]
I just wanted to note that I am still seeing this issue occurring in `master` after #2932 was merged.  

```
❯ hugo server ws .
Started building sites ...
Error: Error building site: Prepare pages failed: ["html/template: cannot redefine \"shortcodes/flickr.html\" after it has executed" "html/template: cannot redefine \"shortcodes/gist.html\" after it has executed" "html/template: cannot redefine \"shortcodes/gist.html\" after it has executed" "html/template: cannot redefine \"shortcodes/gist.html\" after it has executed" "html/template: cannot redefine \"shortcodes/gist.html\" after it has executed"]…
```

```
❯ hugo version
Hugo Static Site Generator v0.19-DEV darwin/amd64 BuildDate: 2017-02-01T16:46:43-05:00
```

**Comment by shohan4556** [comment]
I am also having this issue, how can I solve this please tell me.
