### ISSUE TITLE
Installation instructions for Mac

### ISSUE THREAD

**Issue by gcasalett** [spf13/hugo#2953]
Pardon the ignorance, but I'm trying to install Hugo on a Mac from the Tarball (Homebrew is not an option), but I don't see a tar.gz download listed for Mac, as mentioned in the instructions. The only Mac OS download is hugo_0.18.1_macOS-64bit.zip, and I don't know what to do with that file...

Any pointers? Thanks!

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
