### ISSUE TITLE
docs: Accessibility: the document content isn't first in the DOM

### ISSUE THREAD

**Issue by MarkDBlackwell** [spf13/hugo#2969]
Accessibility: the document content isn't first in the DOM. This affects people who use many audible screen readers.

This means, in order to hear each document's content, currently we require they wait (somewhat frustratingly) until all of the text in the sidebar menu (and header) are slowly read through, first.

**Comment by moorereason** [comment]
@MarkDBlackwell,
We need a total revamp of the docs site.  Please stop creating issues for every little thing you find wrong with the existing site.  If you can't help yourself from documenting all of the problems, do it in a single issue or create a wiki page or a forum thread or a google doc or a hackpad or anything besides this annoying issue-flood.

**Comment by MarkDBlackwell** [comment]
@moorereason Still, these are real problems. Pull request #2896 fixes them. :)

Furthermore, the pull request's color scheme, etc., can be improved later, if desired.

**Comment by bep** [comment]
@MarkDBlackwell please close this and the other issues and create write this somewhere else.

**Comment by MarkDBlackwell** [comment]
@bep Now, I have closed the other, similar issues. :)

I'd rather not write them up, somewhere else, also, though (if you don't mind).
