### ISSUE TITLE
default site spam / grossness

### ISSUE THREAD

**Issue by b5** [spf13/hugo#2975]
Hi! So I made a bit of a boneheaded mistake and posted a site without changing the default url in config.toml:
`http://replace-this-with-your-hugo-site.com/`

I posted the site and a friend clicked a link, which resolved to the above url, which was some sort of horrible spam. Is there any chance we could change that url to _anything_ else, and not feed the spammers any more naive traffic? I'll happily submit a one-line PR if that helps!

Thanks again, Hugo's Great!

**Comment by moorereason** [comment]
:man_facepalming: 

I'd recommend removing the `.com`.

**Comment by bep** [comment]
This should be fixed in latest version.
