### ISSUE TITLE
Empty taxonomy term is no more generated since 0.18

### ISSUE THREAD

**Issue by kakawait** [spf13/hugo#2977]
Since hugo `0.18` (bug still on `0.18.1`) with following setup (to reproduce)

```bash
mkdir blog
cd blog/
hugo new site .
hugo new post/welcome.md
cd themes/
# Random theme
git clone https://github.com/dim0627/hugo_theme_robust.git 
cd ..
echo -e "[taxonomies]\n  tag = \"tags\"" >> config.toml
./hugo_0.18_darwin_amd64 -w server --theme=hugo_theme_robust --buildDrafts
```

Then open http://localhost:1313/tags/ give me `404`

<img width="400" alt="screen shot 2017-01-22 at 10 43 08" src="https://cloud.githubusercontent.com/assets/275609/22181583/965eeb4e-e08f-11e6-8333-0027767b4758.png">

Whereas using

```bash
./hugo_0.17_darwin_amd64 -w server --theme=hugo_theme_robust --buildDrafts
```

I get following result

<img width="1438" alt="screen shot 2017-01-22 at 10 43 56" src="https://cloud.githubusercontent.com/assets/275609/22181591/b89accd2-e08f-11e6-929b-54e973e251d1.png">

As you can imagine the big difference is that on `public` folder using `0.18` there is no more `public/tags/index.html` unlike when generating using `0.17`.

---

I know that from `0.18` everything is now a `Page` it's maybe related, but empty taxonomy term should be possible.

**Comment by felicianotech** [comment]
I hit this issue today as well. Starting making my test from HTML Proofer fail due to the 404s.

**Comment by kakawait** [comment]
Any contributors can claim it's a _bug_ in order to allow theme developers to know if they are doing wrong or just wait for fix (or propose PR)?

**Comment by kakawait** [comment]
still reproducible using `Hugo Static Site Generator v0.19 darwin/amd64 BuildDate: 2017-02-27T11:21:29+01:00`

**Comment by kakawait** [comment]
Nice thank you @bep for fix
