### ISSUE TITLE
docs: Drop = from Nginx 404 configuration

### ISSUE THREAD

**Issue by tkorri** [spf13/hugo#2981]
In the _Automatic Loading_ section of _Custom 404 page_ documentation, the configuration for Nginx is given as `error_page 404 = /404.html;`

This is correct, but sets the status code Nginx returns to the client to what requesting /404.html returns. I.e. if /404.html exists the status code is 200 OK.

When the configuration is changed to `error_page 404 /404.html;` (without the = ) Nginx returns the status code that matched the error_page configuration, which in this case is 404.

Detailed info about error_page configuration available in [Nginx documentation](http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page)

**Comment by rdwatters** [comment]
This has been updated in the new docs site, so I think we can close. Up to you @digitalcraftsman 

https://hugodocs.info/templates/404/#automatic-loading
