### ISSUE TITLE
Incomplete or empty template

### ISSUE THREAD

**Issue by Nolanus** [spf13/hugo#2985]
I've got a very basic partial template in a file called `nav.html`:

```
<a href="{{ .Permalink }}"><img src="images/logo_nav{{ if eq .frontlogo true }}_large{{ end }}
.png" class="logo"/></a>
```

Included like that in my index.html:

```

{{ partial "nav" . }}
```

Now I want to provide an additional flag to the partial to change the rendering a little bit, based on the place the partial is used in (e.g. large logo image file on front, small one for other pages).
I read about the [dict()](https://gohugo.io/templates/functions#dict) function and tried the following:

```
{{ partial "nav" (dict "content" . "frontlogo" true ) }}
```

Which works, as the logo image is adjusted as expected, but produces the following Error in the console:

```
ERROR: 2017/01/23 15:48:37 general.go:236: theme/partials/nav.html is an incomplete or empty template
```

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by pieterjandesmedt** [comment]
Having the same issue when I add a simple `len` function to my partial...

This works **perfectly**: 
```
{{ $categories := . }}
{{ range $index, $category := $categories }}
	<a href='{{ (printf "categories/%s" $category) | urlize | lower | relLangURL }}'>{{ $index }} - {{ $category }}</a>
{{ end }}
```

This gives an **error** but still renders the page as expected:
```
{{ $categories := . }}
{{ len $categories }}
{{ range $index, $category := $categories }}
	<a href='{{ (printf "categories/%s" $category) | urlize | lower | relLangURL }}'>{{ $index }} - {{ $category }}</a>
{{ end }}
```
_(the first `.` is the post's `.Params.categories`, an array)_

Error is:
```
ERROR: 2017/02/20 13:51:59 general.go:236: theme/partials/widgets/article_categories.html is an incomplete or empty template
```

What am I missing?

**Comment by pieterjandesmedt** [comment]
Apparently I was missing the fact that some articles didn't have `.Params.categories`. D'oh!
Fixed it by guarding that code block with a 
```
{{ with . }}
  <!-- rest of the code here -->
{{ end }}
```
