### ISSUE TITLE
Page build error 

### ISSUE THREAD

**Issue by blh5yb** [spf13/hugo#2986]
I have been getting the following error when I try to build me web page:
 Permission to kakawait/hugo-tranquilpeak-theme.git denied to blh5yb.
fatal: unable to access 'https://github.com/kakawait/hugo-tranquilpeak-theme.git/': The requested URL returned error: 403

I tried initializing the theme using the git submodule init and git submodule update commands, but the page still failed to build

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
