### ISSUE TITLE
Slashes between numbers are not always fractions.

### ISSUE THREAD

**Issue by paul-hammant** [spf13/hugo#2997]
1/2 - fraction
2001/2 is a reference to a year.

If I do 2001&#47;2 then I've hacked it (yay) but not when that is in a H1 H2 or H3, as anchors now contain -47- instead of the slash.

**Comment by bep** [comment]
You can turn off automatic fractions. See documentation link below. If you want smarter fractions, post an issue at 970314

For further questions, please use http://discuss.gohugo.io/. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
