### ISSUE TITLE
Spurious warning: "Your rendered home page is blank: /index.html is zero-length"

### ISSUE THREAD

**Issue by sometimesfood** [spf13/hugo#3002]
I recently moved the contents of my index page to "content/index.md" and noticed that hugo v0.18.1 emits a spurious warning when rebuilding the site:

```
=============================================================
Your rendered home page is blank: /index.html is zero-length
 * Did you specify a theme on the command-line or in your
   "config.toml" file?  (Current theme: "blank")
 * For more debugging information, run "hugo -v"
=============================================================
```

Steps to reproduce:

```
hugo new site hugo-temp
cd hugo-temp
hugo new theme blank
cat >config.toml <<EOF
title = "My New Hugo Site"
baseurl = "http://example.org/"
languageCode = "en-us"
theme = "blank"
EOF
echo '{{ .Content }}' > themes/blank/layouts/_default/single.html
echo Hello world > content/index.md
ls -l public/index.html
hugo
```

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by sometimesfood** [comment]
@bep Sorry if I was not clear enough before, but I think this spurious warning is indeed a bug.

Hugo correctly produces a proper home page, but still complains about a zero-length index.html:

```
~/hugo-temp % hugo
Started building sites ...
=============================================================
Your rendered home page is blank: /index.html is zero-length
 * Did you specify a theme on the command-line or in your
   "config.toml" file?  (Current theme: "blank")
 * For more debugging information, run "hugo -v"
=============================================================
Built site for language en:
0 draft content
0 future content
0 expired content
1 regular pages created
1 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 17 ms
~/hugo-temp % cat public/index.html 
<p>Hello world</p>
```

Please consider reopening this issue.

**Comment by bep** [comment]
I read your issue. This is not a bug.

**Comment by sometimesfood** [comment]
>  This is not a bug: You have in a hacky way created two pages that renders to the same location (/index.html), one of them fails

I am not sure I quite understand your point. If I delete all index.html templates in the project I still get the same warning.

Anyway, thanks for your time. Since I cannot seem to find any relevant documentation regarding this behaviour, I'll open a thread in the forum.
