### ISSUE TITLE
Retrieval of multi-language taxonomies from i18n-pages

### ISSUE THREAD

**Issue by JLKM** [spf13/hugo#3014]
Unless I've overlooked something, this is a feature request...

Having experimented quite a lot with the rather new i18n features of Hugo I've encountered almost nothing but nice options so far. And they work!

1. Language in filename `this-file.en.md` comes in handy, when you want to keep the overview of, what's written on the given subject (=folder) across different languages.
2. The option for different taxonomies for each language in the config-files deserves big credit. This makes my list-pages with taxonomies and taxonomies/terms work out of the box with the right words on top in the right language. Thumbs up again.
3. [Translation of strings](https://gohugo.io/content/multilingual/#translation-of-strings) are also a pleasure to work with. And the option for mixing variables - ex.`{{ .Count }} and translations really rocks. Not to mention separation of singular and plural!

```
- id: wordCount
  translation:
    one: One word
    other: "{{ .Count }} words"
```

So what might possibly be missing?

I may push the limit with a kind og syndicated [website about open source and open standards](https://staticsitegenerators.dk) - at this moment across 9 domains in 2 languages (danish and english so far) each. Please bear over with bugs. It's still under construction - and will probably be for some time.

Hugo is able to deliver the grouping of tags  _(=taxonomies)_, that I insist on putting in the top menu. I guess this - also - makes Hugo outstanding. Thanks once more for the awesome work, contributors.

The only challenge, however, shows up in the templates for content-pages. I use one template for both languages, and in the top section there's a reference to authors, tags etc. However these taxonomies are different in english and danish. Again this separated approach works fine in lists-pages, but on the content-pages this leaves you with the problem of referring different keys - depending on the language being used on the actual document.

The following code-snippet illustrates the challenge:
```
               {{ range .Params.authors }}
               <a href="/authors/{{ . | urlize | lower }}" rel="authors tag">{{ . }}</a>
                {{ end }}
                {{ .Site.Params.indexes.calendar.icon | safeHTML }}
                {{ .Date.Format .Site.Params.date_format }} · {{ i18n "wordCount" .WordCount }} ·
                    ~{{ i18n "readingTime" .ReadingTime }}
```

- `.Params.authors` returns nothing on pages in danish - where .Params.skribenter contains the author-names
- `/authors/` should be `/skribenter/` on the danish pages

For the time being I'll take the quick fix road and put in some if-statements with reference to the language in use. But I suppose this solution will grow at least un-elegegant with f.ex. 5 languages.

Again - supposing I haven't missed a better solution: Is it possible to extend the string-translation-feature to include references to taxonomies - like...

1. A new config.yaml-setting (example):
`TaxonomyLanguageEnforced: en`

Which in general should tell Hugo to look only for english taxonomies in config.yaml and then get their translations from the available i18n-files...

2. ...where the taxonomies might be set up in f.ex. `da.yaml`something along the lines of this:

```
- id: authorName
  taxonomies: .Site.Taxonomies.authors
  translation:
    one: Skribent
    other: Skribenter

```

In this case:
- `id` *authorName* would be available for reference on content-page-templates in all defined languages
- `taxonomies` would stand by for generation of taxonomy-lists and taxonomy-terms-lists
- front matter keys would be the same across languages, since they are translated on generation
- we will have a i18n setup, where both strings and taxonomies are connected across languages.

The drawback is likely to be longer generation time, when taxonomies for a the relevant languages will have to be combined from several files.

But again. Which language offers the speed necessary - if not GoLang?

At least I would have no problems waiting another couple of seconds to see this small dream come through...

**Comment by bep** [comment]
Thanks for getting in touch, but I suggest you post this at the [Hugo Discussion Forum](http://discuss.gohugo.io/).  

I'm not totally sure what your problem here, but I think I would standardize the keys (like `author`) in one of the languages to avoid this. 

If you would really like to be clever, I guess you could do some thing ala:

````
$authors := (index .Params (i18n "authors"))
```

But again, we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
