### ISSUE TITLE
Build failure with HTML content with no frontmatter with shortcodes

### ISSUE THREAD

**Issue by Tristor** [spf13/hugo#3021]
In Issue #2951 that the merger of PR #2932 should resolve this.

I just wanted to note that I am still seeing this issue occurring in master after #2932 was merged.

`v0.18.1` works fine however.  Only failing in `master`

```
❯ hugo server ws .
Started building sites ...
Error: Error building site: Prepare pages failed: ["html/template: cannot redefine \"shortcodes/flickr.html\" after it has executed" "html/template: cannot redefine \"shortcodes/gist.html\" after it has executed" "html/template: cannot redefine \"shortcodes/gist.html\" after it has executed" "html/template: cannot redefine \"shortcodes/gist.html\" after it has executed" "html/template: cannot redefine \"shortcodes/gist.html\" after it has executed"]…
```
```
❯ hugo version
Hugo Static Site Generator v0.19-DEV darwin/amd64 BuildDate: 2017-02-08T13:39:30-05:00
```

**Comment by bep** [comment]
I need to see your site or a site that reproduces this issue.

**Comment by Tristor** [comment]
Howdy bep.  I'm pretty sure that I'm on the latest source as I manually built using `go install` from the `$GOPATH/src/github.com/spf13/hugo` directory after doing a `go get -v -u github.com/spf13/hugo`

I attempted a `make install` but encountered an error because `govendor` wont follow HTTP redirection:

```
❯ make install
go get github.com/kardianos/govendor
govendor sync github.com/spf13/hugo
# cd .; git clone https://gopkg.in/yaml.v2 /Users/tristor/projects/go/.cache/govendor/gopkg.in/yaml.v2
Cloning into '/Users/tristor/projects/go/.cache/govendor/gopkg.in/yaml.v2'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
Error: Remotes failed for:
	Failed for "gopkg.in/yaml.v2" (failed to clone repo): exit status 128

make: *** [vendor] Error 2
```

The site I'm building is publicly on Github at https://github.com/tristor/tristor.ro

**Comment by Tristor** [comment]
Looks like my issue above with `govendor` is a problem within `gopkg`  https://github.com/niemeyer/gopkg/issues/50   I'm performing a workaround to get gopkg.in working again so I can run a `make install` and provide you the requested information.

**Comment by Tristor** [comment]
Applying the workaround allowed `make install` to succeed.  I still get the same error as before, here's my updated version string after performing `make install`

```
❯ hugo version
Hugo Static Site Generator v0.19-DEV-7A5CC3CF darwin/amd64 BuildDate: 2017-02-09T12:06:55-05:00
```

**Comment by bep** [comment]
OK, I can reproduce this now -- will fix.

**Comment by Tristor** [comment]
Thanks a bunch @bep.  Just tested and confirmed that this fixes the issue!
