### ISSUE TITLE
Custom type in frontmatter and .Type-variable mismatch

### ISSUE THREAD

**Issue by bilke** [spf13/hugo#3023]
I have a page in a section `mysection`. I set a custom type in the frontmatter: `type = "myothersection"`. When I render the page and output the type with `{{ .Type }}` this will print `mysection`. Is this a bug?

**Comment by bep** [comment]
>Is this a bug?

Doubtful. This is well tested, and I use `type` myself extensively.

I'm short of time these days, so I'm going to ask you to do the troubleshooting at https://discuss.gohugo.io/
