### ISSUE TITLE
More String Utilities?

### ISSUE THREAD

**Issue by Campanula** [spf13/hugo#3024]
https://discuss.gohugo.io/t/more-string-utilities/5410

I encounter some problems to handle strings when working with the "shortcodes" variable {{ .Inner
}}

1.How to use a escape newline character "/n" in go template ?
{{ delimit (slice "foo" "bar" "buzz") "/n" }} dosen't work as I expected to get three lines.

2.How to remove the leading newline characters "/n" ?
"/nHello world!" -> "Hello world!"

3.How to concatenate a string constant and a string variable in one step directly ?
{{ $prefixed := delimit (slice "bar" .Title) "" }}
It looks strange to do this with the function delimit. I'd prefer a new function concat()
{{ concat "bar" .Title }}

4.How to count number of lines in a string ?
"foo/nbar/nbuzz" => three lines

is there a easier way to do these ? thank you ~

**Comment by bep** [comment]
You have started a thread on the forum, please do not double post. Finish that discussion, then we can maybe create some practical issues in here.

**Comment by Campanula** [comment]
Sorry to do that , Thanks for your advice.
