### ISSUE TITLE
Gravatar isn't added to generated html files

### ISSUE THREAD

**Issue by erkanerol** [spf13/hugo#3031]
I upgraded the hugo version to v18 and the gravatar in the sidebar dissappeared. When I downloaded the v17 and generated it again, the the problem was fixed. 

Configs:
https://github.com/erkanerol/erkanerol.github.io/blob/hugo/config.toml

SideBar.html
https://github.com/erkanerol/erkanerol.github.io/blob/hugo/themes/hyde-x/layouts/partials/sidebar.html

Page with version18
https://github.com/erkanerol/erkanerol.github.io/blob/d441494d23f535cb5bdfe80e0140fdd45adf642a/index.html

Page with version17
https://github.com/erkanerol/erkanerol.github.io/blob/6ace81a32bbd62051aa3c0e6dd0fe20616d92dfe/index.html

**Comment by bep** [comment]
You need to use `with`(or lowercase the params in `isset`) to check for params presence:

https://github.com/erkanerol/erkanerol.github.io/blob/hugo/themes/hyde-x/layouts/partials/sidebar.html#L4

There is an open issue about fixing `isset` vs params. 

Take further questions at the discussion wofru.
