### ISSUE TITLE
hugo import jekyll is broken

### ISSUE THREAD

**Issue by buynov** [spf13/hugo#3032]
### The Problem
I am trying to debug the `hugo import jekyll` command (the latest code from the Github repository) and the command doesn't work properly (it used to work before). When I build hugo on my machine and run `hugo import jekyll`, I get:

```
$ hugo import jekyll ~/Work/buynov.github.com/source .
ERROR 2017/02/12 16:41:17 Failed to load templates: Path too short. Stop walking.
Error: Your Jekyll root contains neither posts nor drafts, aborting.
```
This same command works fine with the latest official release (0.18.1) and manages to import 70 posts. The paths that I provide are correct. I tried with full paths from root, but I get the same result. 

I tried to debug and fix this, but I am new to Golang and Hugo, and it is not obvious for me what the problem might be (the file system abstraction, `afero`, is quite hard to read and understand). It seems that hugo thinks that my Octopress/Jekyll source directory does not exist but I don't understand why.

### My environment
OS: macOS Sierra
Source: [My Octopress blog](https://github.com/buynov/buynov.github.com/tree/source) (branch `source`)
Hugo version: Latest from the Github repository (v0.19-DEV)

**Comment by bep** [comment]
I broke it, so I'll fix it. Thanks for the report.

**Comment by mesibo** [comment]
We are facing same issue with latest hugo 0.52, macOS. 

$ hugo import jekyll ../jekyllproject . 
Error: abort: jekyll root contains neither posts nor drafts

$ hugo version
Hugo Static Site Generator v0.52/extended darwin/amd64 BuildDate: unknown

**Comment by moorereason** [comment]
Please don't comment on old, closed issues.  Use the discussion forums or open a new issue.
