### ISSUE TITLE
Random order of the TOML configuration for new posts support

### ISSUE THREAD

**Issue by FaBMak** [spf13/hugo#3038]
Hi, I'm running Hugo 0.18.1 and every time that i create a new post, the TOML configuration of the post, it's in random order.

Here is an example.

hugo new t1
hugo new t2
hugo new t3

cat content/t*
+++
draft = true
date = "2017-02-14T22:15:43-02:00"
title = "t1"

+++

+++
date = "2017-02-14T22:16:05-02:00"
title = "t2"
draft = true

+++

+++
date = "2017-02-14T22:22:43-02:00"
title = "t3"
draft = true

+++

This is not a big deal, but it's very annoying. Is there an fix, please?

**Comment by bep** [comment]
https://github.com/spf13/hugo/issues/452
