### ISSUE TITLE
How to integrate a WebGL canvas into a page

### ISSUE THREAD

**Issue by Ravenwater** [spf13/hugo#3043]
I am trying to figure out how to incorporate an interactive 3D visualization into a Hugo documentation site. Has anyone been successful in that task?

**Comment by digitalcraftsman** [comment]
Hello @Ravenwater,

please ask questions like these on the [Hugo forum](https://discuss.gohugo.io/);  we use GitHub only  used for concrete issues and requests/enhancements.
