### ISSUE TITLE
Static Asset Management

### ISSUE THREAD

**Issue by neilchaudhuri** [spf13/hugo#3051]
I would like to migrate my Octopress site to Hugo, but one apparent obstacle at the moment is automated static asset management. In particular, I would like my static assets to be published to a CDN (in my case Amazon CloudFront) with fingerprints for cache busting purposes and GZipping. I don't see anything like that currently. Am I missing something? It may be a good idea to provide ways to use build pipelines from the Node stack to solve this (and other things like CoffeeScript or SASS transpilation) if not available already.

Thanks.

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by neilchaudhuri** [comment]
Three problems:

1. I did look at the documentation and found no answer. 
2. The forum site you linked to won't let me sign up. I get this error: "New registrations are not allowed from your IP address."
3. The main Hugo website brought me to this page from the menu item "Issues & Help." Perhaps someone should rephrase "Issues & Help" if this isn't the place to get, you know, help?

**Comment by moorereason** [comment]
You could search the issues, as well.  See #621

**Comment by neilchaudhuri** [comment]
Already saw that. That issue only covers part of my question, and it doesn't even have a true resolution. Just some workarounds with their pros and cons. Static asset management is much bigger than just cache busting.
