### ISSUE TITLE
Wrong hugo_0.18.1_Linux-64bit version in releases page

### ISSUE THREAD

**Issue by oneohthree** [spf13/hugo#3053]
I downloaded [hugo_0.18.1_Linux-64bit]( https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz) but version is wrong.

```
hugo version
Hugo Static Site Generator v0.15 BuildDate: 2016-03-04T10:19:23-05:00
```

**Comment by bep** [comment]
Check your PATH.

I use that exact package in my CI builds, and it reports the version as expected:

https://circleci.com/gh/bep/docuapi/28
