### ISSUE TITLE
support for Isso (Disqus alternative)

### ISSUE THREAD

**Issue by gour** [spf13/hugo#306]
I'm very much pleased with what I see in Hugo and it makes me enthusiastic to start learning Go in order to be able to tweak it and/or help contributing back somehow...

One of the nice features I find in e.g. Nikola (python-powered static site generator) is support for Isso (http://posativ.org/isso/) which is light open-source alternative for Disqus commenting system.

It is written in Python, but it is not tied to any specific engine and it would be nice to provide some hooks to integrate it nicely with Hugo.

Sincerely,
Gour

**Comment by bep** [comment]
Close as stale.
