### ISSUE TITLE
hugo server fails with non-renderable content pages

### ISSUE THREAD

**Issue by moshee** [spf13/hugo#3062]
System info:

```
$ uname -a
Linux deimos 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ hugo version
Hugo Static Site Generator v0.19-DEV linux/amd64 BuildDate: 2017-02-19T08:31:09-08:00
$ go version
go version go1.8 linux/amd64
```

What I tried:

- `hugo -w -v`
- add content file that's rendered as part of `public/index.html`

What I expect: `public/index.html` re-generated accordingly with new content.

What I got:

```
$ ls -l content/serialization/test.md public/index.html
-rw-r--r-- 1 tsp sftponly   343 Feb 19 08:45 content/serialization/test.md
-rw-r--r-- 1 tsp sftponly 24909 Feb 19 08:33 public/index.html
````

The HTML remains untouched. After I interrupt Hugo and restart it with the same options,

```
$ ls -l content/serialization/test.md public/index.html
-rw-r--r-- 1 tsp sftponly   343 Feb 19 08:45 content/serialization/test.md
-rw-r--r-- 1 tsp sftponly 26448 Feb 19 08:50 public/index.html
```

the HTML gets re-rendered as expected.

This seems to be somewhat related to #2869 and #2774, but whereas both of those issues involved `hugo server`, I'm just running `hugo -w` and serving using nginx.

Seems to be a regression:

- 0.17 release: all pages work as expected
- 0.18.x releases: only one particular section has the issue
- tip: all pages have the issue

I had built from master after seeing #2869 in an attempt to get rid of the issue I was experiencing in 0.18.1. On 0.18.1, this issue only happened on one particular section, whereas on tip, it happens on every page. The particular section in question has no content of its own, I'm using a dumb trick to populate it with content from a different section (using `.Data.Pages` and leaving a dummy content file in the content directory so the section doesn't get ignored) so that I can get the content under the URL structure I want.

### Details

Output upon creating `content/test.md` and then restarting hugo:

```shell
INFO 2017/02/19 08:44:53 Received System Events: ["/home/tsp/tsp/content/serialization/.test.md.swp": CREATE "/home/tsp/tsp/content/serialization/.test.md.swx": REMOVE "/home/tsp/tsp/content/serialization/.test.md.swp": REMOVE "/home/tsp/tsp/content/serialization/.test.md.swp":
CREATE "/home/tsp/tsp/content/serialization/.test.md.swp": WRITE]
INFO 2017/02/19 08:44:58 Received System Events: ["/home/tsp/tsp/content/serialization/.test.md.swp": WRITE]
INFO 2017/02/19 08:45:26 Received System Events: ["/home/tsp/tsp/content/serialization/test.md": CREATE "/home/tsp/tsp/content/serialization/test.md": WRITE]

Change detected, rebuilding site
2017-02-19 08:45 -0800
Source changed /home/tsp/tsp/content/serialization/test.md
INFO 2017/02/19 08:45:26 rereading /home/tsp/tsp/content/serialization/test.md
INFO 2017/02/19 08:45:26 rereading /home/tsp/tsp/content/serialization/test.md
INFO 2017/02/19 08:45:26 found taxonomies: map[string]string{"category":"categories", "tag":"tags"}
INFO 2017/02/19 08:45:27 Received System Events: ["/home/tsp/tsp/content/serialization/.test.md.swp": WRITE]
INFO 2017/02/19 08:45:35 Received System Events: ["/home/tsp/tsp/content/serialization/.test.md.swp": WRITE]
^C
$ # first ls command done here
$ hugo -w --ignoreCache -v
INFO 2017/02/19 08:50:07 Using config file:
INFO 2017/02/19 08:50:07 /home/tsp/tsp/static/ is the only static directory available to sync from
INFO 2017/02/19 08:50:07 syncing static files to /home/tsp/tsp/public/
WARN 2017/02/19 08:50:07 Translation func for language en not found, use default.
WARN 2017/02/19 08:50:07 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
Started building sites ...
INFO 2017/02/19 08:50:07 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
WARN 2017/02/19 08:50:07 complete/dummy.html is rendered empty
WARN 2017/02/19 08:50:07 footer is rendered empty
WARN 2017/02/19 08:50:07 serialization is rendered empty
WARN 2017/02/19 08:50:07 sidebar is rendered empty
Built site for language en:
0 draft content
0 future content
0 expired content
27 regular pages created
7 other pages created
0 non-page files copied
3 paginator pages created
0 tags created
0 categories created
total in 15 ms
Watching for changes in /home/tsp/tsp/content
Press Ctrl+C to stop
WARN 2017/02/19 08:50:07 Skip i18nDir: lstat /home/tsp/tsp/i18n: no such file or directory
```

Based on this, it appears that the actual "build site" logic doesn't get triggered on content updates in my situation, though it does still seem to be aware of them and builds correctly when running the generator explicitly. However, static files are updated, such as CSS and images.

Things that don't seem to make a difference (duplicates the above log output):

- `--ignoreCache`
- Editing existing content

Feel free to ask specific questions about the site layout. For the index page, I'm building the front page by ranging through `.Data.Pages` with a `where` filter to build a list of articles.

**Comment by bep** [comment]
Thanks for the detailed report.

I have made som big refactorings that touch more or less all over (to, so to speak,  easier handle change in the future), so a regression or two would not surprise me. 

But I have, of course, tested this manually myself, and have no such issues on my MacBook.

But the devil is in the details in this area, so the best thing is if you could provide a link (or a zip) with a "failing Hugo site".

**Comment by moshee** [comment]
I have constructed a minimal site by adding files until I could trigger the behavior on 0.18.1 release:

[test.zip](https://github.com/spf13/hugo/files/786265/test.zip)

Some of the files including `layouts/404.html` and `layouts/section/dummy.html` were added to suppress missing layout warnings, and I don't think this matters, but I did it to replicate my actual site.

Hopefully, the timestamps will help show what I mean. The file `content/post/testpost.md` contained a few words upon initial site generation by invoking `hugo -w`. With `hugo -w` running, I appended some more text to `content/post/testpost.md` in a different tmux window, and that got added to `public/index.html` and `public/post/index.html`, but not `public/dummy/index.html`, despite the modtimes being the same for all.

**Comment by bep** [comment]
The good thing is, I can reproduce it.

The bad thing is, I have no idea, as I can see nothing special about this project. But I will figure it out, eventually.

**Comment by bep** [comment]
Seems like we "swallow" an error message (will fix that):

```
failed: ["html/template: cannot Parse after Execute"]
````

Which I suspect is your use of `Render` -- which is probably because of some refactorings in the template loading department lately. Will check and fix.

**Comment by bep** [comment]
The "sinner" in your test case is the empty `dummy.md` -- I will fix it later, but will add some context:

Content files (html, md etc) in /content without frontmatter, will be parsed "as is" as Go templates. With some changes in the Go templates in stdlib lately, we had to make some changes in the order etc. in how we parsed these templates. We have tests for this, but not for the live reload part, which fails. The solution is to make sure we create a new template clones for these "special" templates on reload.

**Comment by divinerites** [comment]
May be useless, but seems related to this closed issue. So just in case :
- Hugo 0.32.3 on Mac
```
$ hugo benchmark --gc
Started building sites ...
Started building sites ...
Error: Prepare pages failed: ["html/template: cannot Parse after Execute"]…
```

Once I added a front matter to my empty _header.md, it worked fine.
