### ISSUE TITLE
Names misunderstoods

### ISSUE THREAD

**Issue by bogem** [spf13/hugo#3063]
Continue of https://github.com/spf13/hugo/issues/2701#issuecomment-280941180

**Comment by bogem** [comment]
But how about `CfgProvider`?

**Comment by bep** [comment]
I think it is fine as is -- and I see no good reason to change it now.

**Comment by bogem** [comment]
It's really hard to understand at start, what is `cfg.Cfg`.

**Comment by bogem** [comment]
And now there are a lot of configurators like `Deps`, `DepsCfg`, `Commandeer`. It's need to take a lot of time to understand the code, because they are very abstract and there are a few  understandable differences between them. It really complicates the code. I ask to document them in detail (e.g. why and where it should be used, differences between the others configurators), please. It will reduce the barrier to entry and thanks this there will be a lot of benefit in the long term.

**Comment by bep** [comment]
`Cfg` stays. Documentation updates are welcome in the form of a PR, but, looking at the current issue tracker, there are more important tasks. The structs you mention are used all over the place in the tests, so there are plenty of examples of how and what.

**Comment by bep** [comment]
Also, if that wasn't' clear: These objects are not meant to be used by end Hugo users. Only for Hugo development. And Hugo developers, I consider them to be expert users.

**Comment by bogem** [comment]
Of course they are for hugo developers, but they are also people, not robots. It's very good for every programming project to have clear and obvious names, so it will reduce the barrier to entry and allows to encourage more new developers to make valuable PRs.
