### ISSUE TITLE
Errors should include path when filename is not unique 

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [spf13/hugo#3079]
I'm using a ```<slug>/index.md``` structure for my content to store assets alongside the posts. After making a change that touched almost every post, I got the following error:

```
started building sites ...
ERROR: 2017/02/21 22:05:10 shortcode.go:290: index:19: unclosed shortcode
```

"index", however, isn't helpful in this situation, as there are dozens of those. It would be helpful to include the first directory up, either for common names only, or always if complexity is a concern.

Sorry for not contributing a patch – I'm still "stop" on Go. Will come back to this if it's still open by the time I've picked up some speed.

**Comment by bep** [comment]
I will close this. We may improve this in the future, as an ongoing process, but for your case the obvious solution is to NOT name every content file the same.

**Comment by MatthiasWinkelmann** [comment]
I see your altruism got the better of you :). Thanks for the incredibly fast fix – I actually switched to HEAD, noticed it had changed, and came here to take a well-deserved beating for not checking the dev version first.

Regarding  your comment: I have about five images specific to each page. It's just incredibly more easy to have them next to the ```.md``` instead of some location in ```/static/images...```.
