### ISSUE TITLE
docs: are references on landing page broken?

### ISSUE THREAD

**Issue by leipert** [spf13/hugo#3081]
The same quote is repeated thrice for me:

<img width="1228" alt="screen shot 2017-02-21 at 23 46 49" src="https://cloud.githubusercontent.com/assets/2906107/23188711/0e3d5002-f890-11e6-8956-cb934ae68bcd.png">

**Comment by bep** [comment]
I suspect there is a date greater than where clause in there ... So I guess the solution is to add some more recent references.

**Comment by digitalcraftsman** [comment]
This issue will become irrelevant once the new redesign of @budparr will be deployed. Shall we close it then?
