### ISSUE TITLE
tplimpl: isset should return an error on unsupported type

### ISSUE THREAD

**Issue by moorereason** [spf13/hugo#3092]
`switch` should have a default case that returns an error when an unsupported `reflect.Kind` is encountered.

See https://discuss.gohugo.io/t/help-understanding-isset/5577/2

**Comment by kaushalmodi** [comment]
Related: https://github.com/spf13/hugo/issues/3089

Thanks for fixing this!

**Comment by kaushalmodi** [comment]
Confirmed the fix.. now if I do `isset .Site "DisqusShortname"`, I get:

> ERROR 2017/03/01 18:19:13 Error while rendering "page posts/installing-go-toolchain.md": template: /home/kmodi/hugo/kaushalmodi.gitlab.io/themes/refined/layouts/_default/baseof.html:45:10: executing "after_main" at <isset .Site "DisqusS...>: error calling isset: unsupported type "ptr"

**Comment by bep** [comment]
Reopened -- as this breaks lots of themes and the theme site. Will have to be re-evaluated.

**Comment by vielmetti** [comment]
Looks like this affects the "Casper" theme.

**Comment by saso94** [comment]
In "hugo-coder" theme, when I start to building site, in the command line there is this warning:

WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.
