### ISSUE TITLE
Menu on multilanguage not work

### ISSUE THREAD

**Issue by igramnet** [spf13/hugo#3094]
Good afternoon. I try to create a new topic for example

https://gohugo.io/content/multilingual#menus2

and does not work.

Can you check this example on hugo v0.18.1

**Comment by bep** [comment]
I'll assume this is working, and ask you to wait for someone to respond to your thread on the forum.

**Comment by igramnet** [comment]
I've tried a lot of options. If you provide a working template, I agree that it works.
