### ISSUE TITLE
Strange issue with Scratch in loop

### ISSUE THREAD

**Issue by denyskoch** [spf13/hugo#3098]
`len` show that `.Data.Page` contains 259 pages. But the range loop iterates only 22 times (only 22 `wtf?` are rendered). If I remove Scratch related calls, I got 259 `wtf?`. What is going on here and how to fix it?

    {{ len (where .Data.Pages "Section" "article").ByDate.Reverse }}                                                                                                                               
    {{ range (where .Data.Pages "Section" "article").ByDate.Reverse }}                            
      wtf?                                                                                         
      {{ $.Scratch.Add .Params.category 1 }}                                                                                                                                      
    {{ end }} 

**Background:** I have custom Param called `category`. Now I want to list 2 Pages for every category sorted by Date. Something like this:

    {{ range (where .Data.Pages "Section" "article").ByDate.Reverse }}                                                                                                                             
        {{ if lt ($.Scratch.Get .Params.category) 2 }}
          {{ $.Scratch.Add .Params.category 1 }}
          <div class="column">
            {{ .Render "list-item" }}
          </div>
        {{end}}
    {{ end }}

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by denyskoch** [comment]
{{ range (where .Data.Pages "Section" "article").ByDate.Reverse }}                            
      wtf?                                                                                                                                                                                                                        
    {{ end }} 

iterates 259 time (this ist correct) but this

    {{ range (where .Data.Pages "Section" "article").ByDate.Reverse }}                            
      wtf?                                                                                         
      {{ $.Scratch.Add .Params.category 1 }}                                                                                                                                      
    {{ end }} 

only 22 times. Sounds like a bug 💯
