### ISSUE TITLE
Generation mode that changes hyperlinks from / to /index.html where applicable.

### ISSUE THREAD

**Issue by paul-hammant** [spf13/hugo#3101]
Usage Scenario: book stitching, using a hugo site as the place where the book content is drafted.

When stuff is served by Apache (etc), a GET of /foo/ is understood to mean a GET of /foo/index.html . All is good in this world.

When I'm handing a table-of-contents page to [Calibre's CLI tool](https://manual.calibre-ebook.com/generated/en/ebook-convert.html) to stitch into a single PDF, the tool chokes.

```
../ is a link to a directory. Ignoring.
``` 

I can hack it via `sed` but would prefer to not hack. Thus can we have an option `--expand-links-to-index-files`.

I'll raise a similar request for an option in Calibre.

**Comment by ominty** [comment]
how about "uglyURLs = true"?

**Comment by bep** [comment]
You can use uglyURLs, in any case, we are not doing anything more in this area.

**Comment by paul-hammant** [comment]
`--uglURLs` does not do what I am asking for. I've just tested it. Behavior is as expected after reading the documentation for `--uglURLs`.

> in any case, we are not doing anything more in this area.

Can you link to a policy document that gives more information please?
