### ISSUE TITLE
Handle uglyURLs ambiguity in Permalink

### ISSUE THREAD

**Issue by ominty** [spf13/hugo#3102]
[Link to repo](https://github.com/ominty/ominty-hugoissues/tree/16555037268e1b3266a6144876f34ea46daf4963)  - this includes the following:

I find this working: create a `/section/index.md` in a section and it renders to `/section/index.html` in that same section in the public folder.

> index.md or foo.md is content and metadata for the single pages,

I like to have an index-file in each content subdirectory as every webserver I know will deliver this when a user uses an address like `http://domain.tld/section/`.
All works fine so far.

I use  the following structure:

```
.
├── config.toml
├── archetypes
├── content
|   ├── _index.md
|   ├── womo
|   |   ├── index.md
|   |   ├── fahrgestell.md
|   |   ├── aufbau.md
|   |   ├── einrichtung.md
|   |   └── {more pages}.md
|   ├── hund
|   ├── blog
|   └── kontakt
├── static
├── data
├── layouts
└── themes
```

and this renders to

```
.
└── public
    ├── index.html
    ├── womo.html
    ├── womo
    |   ├── index.html
    |   ├── fahrgestell.html
    |   ├── aufbau.html
    |   ├── einrichtung.html
    |   └── {more pages}.html
    ├── hund.html
    ├── hund
    ├── blog.html
    ├── blog
    ├── kontakt.html
    └── kontakt
```

which is ok so far - and as expected following [@bep](/users/bep) 's definition.

Now I use the following code to produce a sidenav within the womo section. 

```
<ul> 
            {{ $act_section := .Section}}                  
            {{ range where .Site.Pages "Section" $act_section }}       
        	<li><a href="{{ .RelPermalink }}">{{- .LinkTitle -}}</a></li>    
            {{ end }}      
</ul>
```
It ends up like this:

```
<li><a href="../womo.html">Einführung</a></li>                   
<li><a href="../womo/fahrgestell.html">Fahrgestell</a></li>            
<li><a href="../womo/aufbau.html">Aufbau</a></li>            
<li><a href="../womo/einrichtung.html">Einrichtung</a></li>
```

which obviously is wrong since the first line should be like

```
<li><a href="../womo/index.html">Einführung</a></li>
```

So at least for creating the menue index.md is NOT treated as content and metadata for a single page.

Hugo uses linktitle from the frontmatter of `/section/index.md` but the created link instead points to `/section.html` which gives a simple list but not the content of `/section/index.md`. 

That's why I used to rename `/section/index.md` to something else like `/section/intro.md` in the snapshots above and everything worked fine

**Comment by bep** [comment]
The repo you link to does not look like the site you describe (no motorhome).

**Comment by ominty** [comment]
sorry, but all the site is in german.
motorhome would be "womo"
dogs would be "hund"
contact would be "kontakt"

I hope this will solve this - I translated the excerpts for the convenience of the readers as the support forum is in english. But translate all of the site - I hope this will not be necessary ...

**Comment by ominty** [comment]
I updated the structure above to match the actual repo. Readme.md is also updated.
Sorry for the confusion.

**Comment by bep** [comment]
OK, I see it now, but I'm not sure how to solve it. Maybe others will.

There is an `uglyURLs` ambiguity here, but we seem to have gotten it right when we wrote the file to disk, so ...

* The page starts out with the URL "womo/index.html"
* The logic to make that ugly "womo/index.html" => "womo.html"

**Comment by bep** [comment]
That said, a workaround that should work for you is to put a `url` override in your `womo/index.md`:

```
url = "womo/index.html"
```

**Comment by ominty** [comment]
Thanks - I did not know about that override - will test it.
