### ISSUE TITLE
hugo version reports v0.2 not v0.20

### ISSUE THREAD

**Issue by timbunce** [spf13/hugo#3112]
`hugo version` now reports `Hugo Static Site Generator v0.2-DEV darwin/amd64 BuildDate: 2017-02-28T16:39:14Z`
Note the `v0.2` instead of `v0.20`.

See 072cd003053f90f3f954434b7ddcbb9ac1c123ea

**Comment by bep** [comment]
Covered by https://github.com/spf13/hugo/issues/3025
