### ISSUE TITLE
url param in _index.md file is ignored

### ISSUE THREAD

**Issue by shmel210** [spf13/hugo#3114]
url param in _index.md file is ignored

hugo last commit
`
commit 24512fa82bb4b9a70eabb350589605d84bc63111
Author: Devin Schulz <devin@devinschulz.com>
Date:   Sat Jan 28 12:13:31 2017 -0500

    docs: Add engineering.invisionapp.com to the showcase
`

`
/content
  /content/types
    /content/types/site/_index.md
`

Contents of _index.md
`
---
date: 2017-01-13T18:11:17+02:00
description: ""
title: Сайты
weight: 1
url: /sites/
---
Some Content
`

`
$ curl -s -D - http://zina.design.dev/types/site/ -o /dev/null
HTTP/1.1 200 OK
Server: nginx/1.10.0 (Ubuntu)
Date: Wed, 01 Mar 2017 16:50:36 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 13718
Last-Modified: Wed, 01 Mar 2017 16:29:29 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "58b6f6e9-3596"
Accept-Ranges: bytes

$ curl -s -D - http://zina.design.dev/sites/ -o /dev/null
HTTP/1.1 404 Not Found
Server: nginx/1.10.0 (Ubuntu)
Date: Wed, 01 Mar 2017 16:50:51 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 178
Connection: keep-alive
Vary: Accept-Encoding
`

**Comment by bep** [comment]
It is ignored by design. We may add some warnings/logic to this at a later stage, but the home page is located at /index.html etc., and changing that would create more problems than it is currently worth.

**Comment by shmel210** [comment]
can you tell the place of code were it is ignored? Maybe i can try in  fork.
