### ISSUE TITLE
homepage: something wrong with tweets

### ISSUE THREAD

**Issue by seeekr** [spf13/hugo#3118]
on home page: https://gohugo.io/

screenshot: https://db.tt/IERYSjALao

problem: showing same (old-ish) tweet thrice

**Comment by bep** [comment]
Yes, I thought I fixed it earlier. But we seem to have a Hugo version problem on the docs server ...

https://github.com/spf13/hugo/commit/add73639cca3a6c852c2942f9615e4aaaf790cf7 should fix it.
