### ISSUE TITLE
Add Chocolatey command to gohugo.io

### ISSUE THREAD

**Issue by DarwinJS** [spf13/hugo#3120]
At the bottom of the home page under install the site says "Using HomeBrew?" and then shows a home brew command for installing it.

There is also a chocolatey package maintained for hugo, so you could also have:

Using Chocolatey?
"choco install hugo -confirm"

**Comment by bep** [comment]
Thanks for the heads up -- I notice that Hugo 0.19 is already available there, which means someone actually maintains that package, which is fantastic! Last time I had a look Chocolatey was a few versions behind.

https://chocolatey.org/packages/hugo

**Comment by DarwinJS** [comment]
@bep - fyi you can also request to be the package maintainer and then integrate the chocolatey package generation into your CI.

**Comment by digitalcraftsman** [comment]
@budparr already added this command in this redesign of the homepage that is likely to be deployed soon. Shall we close it then?

**Comment by bep** [comment]
I'm closing this -- and people arguing that "it's not fixed on the live site": This is analogue to doing code changes to master: It is fixed, but not released yet.
