### ISSUE TITLE
[Q] How to map custom url to pages?

### ISSUE THREAD

**Issue by dehghani-mehdi** [spf13/hugo#3125]
Hi,

First thanks for the amazing work, Hugo is awesome!

Based on my search, for adding a page to site, I should use `hugo add new my-page.md`, then I can access to this page using `domain.com/my-page`, so far so good. but how I can use the `my-page.md` file as content by opening `domain.com/something-else`? (_I mean the page url and the .md file name must be the same, otherwise the result will be 404 error page, how I can customize that?_)

Thank you.

**Comment by kevingimbel** [comment]
Hello @dehghani-mehdi,

Please use GitHub Issues for bug reports. To ask questions or request help use the forum at https://discuss.gohugo.io

--- 

As for your questions: Please look at the documentation about "Configuration" at https://gohugo.io/overview/configuration/ - you can define how URLs should look for different content types in your sites config file (`config.toml` or `config.yml`), for example:

```yaml
permalinks:
  post: /:year/:month/:title/
  page: /:title
```

**Comment by digitalcraftsman** [comment]
As @dehghani-mehdi said, please use the forum if his commit doesn't already solved your problem.
