### ISSUE TITLE
org-mode file parsing treating every line of text as a new paragraph

### ISSUE THREAD

**Issue by bstamour** [spf13/hugo#3126]
I'm trying to create a blog post using the org file format, but every line of text is being wrapped with paragraph tags, thus giving the generated output a very strange appearance. If I change the file extension to .md instead of .org everything looks fine (for now I am just using text, no headers, lists, etc.)

**Comment by moorereason** [comment]
Cc: @chaseadamsio

**Comment by bep** [comment]
See https://github.com/chaseadamsio/goorgeous/issues/26

**Comment by chaseadamsio** [comment]
Should have this fixed after this weekend. I've been doing a lexer/parser rewrite this week. Thanks for cc'ing @moorereason & sharing the open issue @bep.

**Comment by gour** [comment]
Ahh...shortly after posting to the Hugo [forum](https://discuss.gohugo.io/t/org-mode-and-fill-paragraph-problem/5858) I've discovered the issue is already known. :sad

**Comment by bep** [comment]
Fixed by d122260
