### ISSUE TITLE
UglyURLs vs ref/relref

### ISSUE THREAD

**Issue by jiridj** [spf13/hugo#3140]
Hi,

I want to deploy my site on S3 with Cloudfront. Cloudfront only has a Default Root Object (e.g. index.html) for the root of the site.

This means that the default pretty urls don't work. Cloudfront will not serve http://mysite.com/posts/apost/ as it does not redirect to the default root object (index.html).

I hoped to work around this issue by using ugly urls. http://mysite.com/posts/apost.html would be served just fine by Cloudfront.

However, none of the links (ref and relref) work when I turn on uglyurls. For example {{< ref "post/apost.md" >}} still results in the generation of a link targeting http://mysite.com/posts/apost/.

Serving locally with hugo, if I click the link, I get a 404 page not found. Adding .html to the address in the browser serves the right page, so the pages are generated correctly.

It looks to me like the ref and relref shortcodes do not take the uglyurls configuration into account. Is there a way to get around this issue?

Thanks!

Jiri

**Comment by bep** [comment]
I would assume that should just work. Have you got a link to a source repo demonstrating this problem?

**Comment by jiridj** [comment]
I tried to reproduce the problem in a small project. New site and fresh checkout of the theme and it works fine. Something must be messed up in my site. Sorry for the noise!
