### ISSUE TITLE
Latest go-toml doesn't work

### ISSUE THREAD

**Issue by sasanrose** [spf13/hugo#3142]
Using hugo v0.19 on linux and trying to create a new site, will generate an empty config.toml:

`hugo new site .`

I investigated the problem a little bit and it turned out that the a recent commit in go-toml broke the backward compatibility https://github.com/pelletier/go-toml/commit/7e6e4b1314c49d42d1bff74c340894921f0ccfac

They changed the tree.String function and it now calls ToWrite which asserts each config value against tomlValue type that will fail.
I am not sure what is the correct way to fix it, but I like help if you give me some hints. For instance maybe change the default config defined in createConfig before sending it to TreeFromMap

**Comment by bep** [comment]
Looksl like it is Windows only? See #3146

**Comment by sasanrose** [comment]
@bep I ran the same test on my Debian machine and here is the result (Well, part of it):

```
--- FAIL: TestNewContent (0.02s)
        content_test.go:68: [0] "title = \"Post Arch title\"" missing from output:
                "+++\n\n+++\n\n"
        content_test.go:68: [1] "test = \"test1\"" missing from output:
                "+++\n\n+++\n\n"
        content_test.go:68: [2] "date = \"2015-01-12T19:20:04-07:00\"" missing from output:
                "+++\n\n+++\n\n"
        content_test.go:68: [0] "title = \"Empty Date Arch title\"" missing from output:
                "+++\n\n+++\n\n"
        content_test.go:68: [1] "test = \"test1\"" missing from output:
                "+++\n\n+++\n\n"
        content_test.go:68: [0] "title = \"sample 2\"" missing from output:
                "+++\n\n+++\n\n"
        content_test.go:68: [0] "title = \"sample 3\"" missing from output:
                "+++\n\n+++\n\n"
        content_test.go:68: [0] "title = \"sample 4\"" missing from output:
                "+++\n\n+++\n\n"
FAIL
exit status 1
FAIL    github.com/spf13/hugo/create    0.029s
```

**Comment by bep** [comment]
OK, I'll assume you're not vendoring (i.e. using `govendor` and `make check`), which we also seem to have some issues with on the Windows build. The related PR also fails in the referenced PR, but now with an actual error message.
