### ISSUE TITLE
Raise the default rssLimit?

### ISSUE THREAD

**Issue by ominty** [spf13/hugo#3145]
I have a page with sections of "normal web pages" - these are sorted by weight to get the appropriate page order in the menu.
Then there is a blog section which is naturally is sorted by reverse date.

I create a site wide RSS feed like the following:

```
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>{{ if eq  .Title  .Site.Title }}{{ .Site.Title }}{{ else }}{{ with .Title }}{{.}} on {{ end }}{{ .Site.Title }}{{ end }}</title>
    <link>{{ .Permalink }}</link>
    <description>Custom Template - Recent content {{ if ne  .Title  .Site.Title }}{{ with .Title }}in {{.}} {{ end }}{{ end }}on {{ .Site.Title }}</description>
    <generator>Hugo -- gohugo.io</generator>{{ with .Site.LanguageCode }}
    <language>{{.}}</language>{{end}}{{ with .Site.Author.email }}
    <managingEditor>{{.}}{{ with $.Site.Author.name }} ({{.}}){{end}}</managingEditor>{{end}}{{ with .Site.Author.email }}
    <webMaster>{{.}}{{ with $.Site.Author.name }} ({{.}}){{end}}</webMaster>{{end}}{{ with .Site.Copyright }}
    <copyright>{{.}}</copyright>{{end}}{{ if not .Date.IsZero }}
    <lastBuildDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" | safeHTML }}</lastBuildDate>{{ end }}
    <atom:link href="{{.Permalink}}" rel="self" type="application/rss+xml" />
    {{ range first 15 .Data.Pages.ByDate.Reverse }}
    <item>
      <title>{{ .Title }}</title>
      <link>{{ .Permalink }}</link>
      <pubDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" | safeHTML }}</pubDate>
      {{ with .Site.Author.email }}<author>{{.}}{{ with $.Site.Author.name }} ({{.}}){{end}}</author>{{end}}
      <guid>{{ .Permalink }}</guid>
      <description>{{ .Summary | html }}</description>
    </item>
    {{ end }}
  </channel>
</rss>
```

but this does not show up any new articles from the blog but only the weighted pages from the other sections.

V0.19
https://github.com/ominty/ominty-hugoissues/tree/issue3145

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by ominty** [comment]
We had this discussion here https://discuss.gohugo.io/t/rss-feed-sorting-by-date-broken-in-0-19/5661/2 and this is a regression as it worked in V0.18.1 without any issues. So I reverted to that version as workaround.

To give some more explanation: 
There are three sections: 
blog - this is sorted by date
hund, womo and kontakt - pages are sorted by weight, but also have a date.

The rss-feed is site-wide and obviously should show the blog entries by date, but also pages from the other sections if they are updated (get new current date).

As I said: working properly in V0.18.1 but does only show pages by weight and ignores sorting by date completely in V0.19

**Comment by bep** [comment]
See https://github.com/spf13/hugo/pull/3036

Put `rssLimit = 2000000` or something in config.toml and you should be good to go.

**Comment by ominty** [comment]
> Put rssLimit = 2000000 or something in config.toml and you should be good to go.
thanks, this indeed seems to work

**Comment by moorereason** [comment]
Two questions:

1. I'll submit a PR to allow users to disable the limit by setting `rssLimit` to a negative integer.
1. Do we want to change the default `rssLimit` from `15` to `-1`?

**Comment by bep** [comment]
Yes, I think "unlimited" would be the least surprising option for most people.
