### ISSUE TITLE
.rst error in hugo 0.19

### ISSUE THREAD

**Issue by hugocruz** [spf13/hugo#3151]
Hello, 

When linking a rst document in hugo 0.19 I get this error: 

```
$ hugo version
Hugo Static Site Generator v0.19 darwin/amd64 BuildDate: 2017-02-27T11:21:29+01:00

$ hugo -w server
Started building sites ...
Error: Error building site: Failed to read data from olddocs/folder/file.rst/file.rst: Data not supported for extension 'rst'
```

It is a bit weird because it was working perfectly in 0.18.1 and also because the document that is including the .rst has this :

```
+++
date = "2017-01-18T13:58:40+01:00"
title = "File"
markdown = "rst"
weight = 210
+++
.. include:: data/olddocs/folder/file.rst

```

Notice that file.rst is duplicated in the error in `0.19` and the folder structure is `data/olddocs/folder/file.rst` not `data/olddocs/folder/file.rst/file.rst`

I guess this is a bug given that in `0.18.1` was working ok.

**Comment by bep** [comment]
>I guess this is a bug given that in 0.18.1 was working ok.

I think you will that it works even better in Hugo 0.19. It may not be in the release notes, but I remember fixing an issue where we "swallowed" an error in the data loading.

So: RST files is not allowed inside /data.

They should live in /content.

**Comment by hugocruz** [comment]
Thanks for the input !

**Comment by bep** [comment]
No problem ... I guess, with your name, Jekyll wasn't an option :-)

**Comment by hugocruz** [comment]
:-)
