### ISSUE TITLE
Unify baseof vs single/section lookup order

### ISSUE THREAD

**Issue by rdwatters** [spf13/hugo#3154]
See [#3116](https://github.com/spf13/hugo/issues/3116)

Current docs show the following for`baseof.html` templates using a `posts` section as an example:

1. `/layouts/section/post-baseof.html`
2. `/themes/<THEME>/layouts/section/post-baseof.html`
3. `/layouts/section/baseof.html`
4. `/themes/<THEME>/layouts/section/baseof.html`
5. `/layouts/_default/post-baseof.html`
6. `/themes/<THEME>/layouts/_default/post-baseof.html`
7. `/layouts/_default/baseof.html`
8. `/themes/<THEME>/layouts/_default/baseof.html`

`<TYPE>-baseof` deviates from other lookups:

1. Templates do not prepend values (e.g. `post-baseof.html`)
2. Section-specific templates are not kept in `_default/`.

Proposed change (using the above `post` example):

1. `/layouts/post/baseof.html`
2. `/themes/<THEME>/layouts/post/baseof.html`
3. `/layouts/section/baseof.html`
4. `/themes/<THEME>/layouts/section/baseof.html`
5. `/layouts/_default/baseof.html`
6. `/themes/<THEME>/layouts/_default/baseof.html`

Unlike #3116, however, this is a more drastic change than adding an item to the lookup, so I hesitate in the light of breaking changes, obviously.

Further consideration include the other *list* templates (e.g., taxonomies), which according to documentation only inherit from the `_default/baseof.html` layout?

**Comment by bep** [comment]
The current docs probably not up to date re. the latest changes to the section:

https://github.com/spf13/hugo/commit/f4779b25bc55a3b6693e9e3cbe6b2444fbf4e61b

So, given your example above it would be:

````
/layouts/section/post-baseof.html
/themes/exampletheme/layouts/section/post-baseof.html
/layouts/post/baseof.html
/themes/exampletheme/layouts/post/baseof.html
/layouts/section/baseof.html
/themes/exampletheme/layouts/section/baseof.html
/layouts/_default/post-baseof.html
/themes/exampletheme/layouts/_default/post-baseof.html
/layouts/_default/baseof.html
/themes/exampletheme/layouts/_default/baseof.html
```

Now, there is an open issue from a user claiming the above doesn't work perfectly for themes, but that is another story.

And I don't understand the "<TYPE>-baseof is counterintuitive since this is the only template that takes this approach to the lookup".

The <TYPE>.html is pretty much Hugo standard, and since a base template must live in a pair relationship with another template, some kind of naming scheme had to be invented. And we already "voted on this" on the forum.

So, unless you come up with some much better reasons, we're not making breaking changes like this that will, to quote the American president, "TREMENDOUS AMOUNT OF WORK!!". :-)

**Comment by bep** [comment]
That said; even if we HAVE lots of options, we don't have to document every variant (we have some other legacy variants floating around in the code).

This will be even more obvious when output types come into the mix ...

**Comment by rdwatters** [comment]
> we're not making breaking changes...even if we HAVE lots of options, we don't have to document every variant 

Agreed. I will do my best to make this clearer in the docs. I wonder how many sites are implementing multiple `baseof*` since this was only introduced a few versions back.

And just to clarify, your example above *is* the most up-to-date, correct?

```
/layouts/section/post-baseof.html
/themes/exampletheme/layouts/section/post-baseof.html
/layouts/post/baseof.html
/themes/exampletheme/layouts/post/baseof.html
/layouts/section/baseof.html
/themes/exampletheme/layouts/section/baseof.html
/layouts/_default/post-baseof.html
/themes/exampletheme/layouts/_default/post-baseof.html
/layouts/_default/baseof.html
/themes/exampletheme/layouts/_default/baseof.html
```

> ...to quote the American president, "CREATE TREMENDOUS AMOUNT OF WORK!!". :-)

A visual representation of my thoughts:

![statemap512](https://cloud.githubusercontent.com/assets/8184251/23764473/466a08dc-04c3-11e7-834c-d5737605129c.png)

**Comment by bep** [comment]
>And just to clarify, your example above is the most up-to-date, correct?

Yes, but it is not in the real doc.

**Comment by rdwatters** [comment]
> Yes, but it is not in the real doc.

@bep Let me know how I can help facilitate this in the new docs. Closing. Cheers.
