### ISSUE TITLE
Structural shortcode changes not detected on live-reload

### ISSUE THREAD

**Issue by bwbecker** [spf13/hugo#3156]
Further to #1894, I too had the same experience:  I added the following shortcode while the server was running

```
<p>Before .Inner</p>

{{ .Inner }}

<p>After .Inner</p>
```

With the usage 

```
{{% clickToReveal %}}

stuff

{{% /clickToReveal %}}
```

It gave the following error message at the console: Shortcode 'clickToReveal' in page 'details/counting.md' has no .Inner, yet a closing tag was provided

Output to the page was 
<p>Before .Inner</p>
<p>After .Inner</p>
<p>stuff</p>

Content after the closing shortcode was swallowed and ignored.

Restarting the server with no other changes got rid of it -- but only after a *lot* of fiddling around trying to solve it.

**Comment by bep** [comment]
I have tested it and found to, possibly related issues: 

* Creating a new shortcode while the server is running isn't picked up. Restarting the server solves that.
* Creating a "structural change" of the shortcode, i.e. making it an `inner` type,  while the server is running isn't picked up. Restarting the server solves that.

**Comment by bep** [comment]
It seems that there is a order issue here that makes this confusing:

* Add a new shortcode to a page, then create it in /layouts/shortcodes -- isn't picked up.
* Create in /layouts/shortcodes first seems to be fine

**Comment by bwbecker** [comment]
> On Mar 10, 2017, at 3:58 AM, Bjørn Erik Pedersen <notifications@github.com> wrote:
> 
> It seems that there is a order issue here that makes this confusing:
> 
> Add a new shortcode to a page, then create it in /layouts/shortcodes -- isn't picked up.
> Create in /layouts/shortcodes first seems to be fine
This does, indeed, match what I remember doing when I had trouble with it.  Thanks for your follow-up.


---------------------------------------------
Byron Weber Becker
School of Computer Science
University of Waterloo, Waterloo, Ontario  N2L 3G1
Email: bwbecker@uwaterloo.ca
Phone:  519-888-4567 x34661

Advising FAQ:  www.cs.uwaterloo.ca/current/faq
