### ISSUE TITLE
Don't repeat ERROR on front matter parse error

### ISSUE THREAD

**Issue by tmcarr** [spf13/hugo#3157]
I was publishing a new page to my simple hugo site when I got the following error:

```
ERROR 2017/03/09 22:01:28 Error parsing page meta data for post/post.md
ERROR 2017/03/09 22:01:28 (4, 9): keys cannot contain new lines
ERROR 2017/03/09 22:01:28 (4, 9): keys cannot contain new lines
Error: Error building site: Errors reading pages: Error:(4, 9): keys cannot contain new lines for post.md
```

After some time I realized it was the frontmatter in the document. Turns out (4, 9) means "Row 4, column 9"

The fix was s/False/false/. Seems like Hugo should have a better error for this. I'll see what I can do to add this feature tomorrow, but I figured I should post this for now.

**Comment by bep** [comment]
While agreeing that the error isn't perfect, the "what Hugo will do about it" stops at preventing it to prevent it from printing twice.

The error message is provided by a third party lib, and while I could wish for some improvement, it isn't important enough to add another issue that we need to follow up on.

**Comment by tmcarr** [comment]
Totally fair! Just thought it was worth reporting.
