### ISSUE TITLE
Hugo should automatically assign width and height of img tags, using original image size

### ISSUE THREAD

**Issue by thulka** [spf13/hugo#3160]
Good HTML **absolutely requires** width and height of img tags to be set. This is not just "good" or "nice to have" html writing, it is absolutely essential for the browser rendering engine. Otherwise, the browser does not know what size an image will be until the image is downloaded. So the rendering engine will need to re-layout the whole page. This is often ugly to see and it costs battery on a mobile phone.

Saying it different: HTML without img width and height set is newbie crap html. Sufficient for raw blogs but not enough for an html site that is delivered to a client who asked for serious web design.

For a static site generator this is certainly a difficult thing to do, it needs to read the images, get the size and write the tag using the original size. This feature would set any site generator apart all other site generators and put it into the group of "serious html-emitters".

There has been a discussion about this feature at https://discuss.gohugo.io/t/can-i-find-out-the-image-size/2196 . Since I could not an issue here, requesting it:

Feature request: Automatically set width and height in img tags.

**Comment by bep** [comment]
This is certainly discussed in other issue(s). You can certainly also do that today by providing your own shortcode in combination with the `imageConfig` func.

A request to, by default, change all img refs is, however, rejected.

**Comment by thulka** [comment]
i see, could you link to the other issues?
just to be sure: i am not talking about "refs" at all, i talked about "width" and "height".
