### ISSUE TITLE
No homepage rendered with V20-DEV 2017-03-10

### ISSUE THREAD

**Issue by rdwatters** [spf13/hugo#3165]
```
hugo version
=> Hugo Static Site Generator v0.20-DEV darwin/amd64 BuildDate: 2017-03-10T18:54:19-06:00
```

![__hugo](https://cloud.githubusercontent.com/assets/8184251/23818667/00220c2a-05c3-11e7-9c5f-19f9ceeeb787.png)

[The repo](https://github.com/rdwatters/hugo-docs-concept).
No warnings to the console or anything else strange happening on local dev. Site still builds without issue on v19 on Netlify as well.

**Comment by bep** [comment]
Try setting a value for the `categories` taxonomy.

**Comment by rdwatters** [comment]
Thank you @bep. Driving so will test this at home. There have been conversations about this on the forums too, and I seem to recall the empty strings were the means to prevent Hugo from building the default category/tags taxonomy. (The empty value is intentional.) Has this changed in v20; i.e., Hugo just will *only* create taxonomies if explicitly declared?

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting.

**Comment by rdwatters** [comment]
The troubleshooting is done thanks to you. I just want to document this if a breaking change between 19 and 20.

**Comment by bep** [comment]
It is a change, but not a breaking one.

* It was a bug fix, fixing a case where terms pages were not properly created
* We now have a `disableKind` option to disable a single `Kind`. If you want to disable 1 taxonomy, then leave out the definition for it.
* We have another open issue about creating warnings/errors for the "duplicate output page case", that wold have made it more clear to you what to fix.
* I know "someone" out there have used this hack to avoid taxonomy creation, but we're not keeping support for obviously wrong workarounds, and we're not documenting it the main doc either. This belongs in the release notes.

I hope you understand why I'm pedantic about the "questions on the forum" thing, it is the only way to get some kind of control with the staff we've got.

**Comment by rdwatters** [comment]
> This belongs in the release notes.

Agreed. I found the [forum conversation here](https://discuss.gohugo.io/t/turning-off-taxonomy-pages/2622/6) and it most definitely is a hack. 

> I hope you understand why I'm pedantic about the "questions on the forum" thing.

Of course, I want to respect process :smile:

> it is the only way to get some kind of control with the staff we've got.

I also understand. As I've mentioned more than once, I'm eagerly volunteering to be made a collaborator...just in the capacity of working on the docs so that all you talented devs can do the really cool work 😄. I *might* try and contribute code, but that would be a long way down the road when I'm good enough to make a positive impact. 

You've said on the forums that you treat docs as an afterthought and then told me do too much *talking* without *doing*, so *doing* is my main focus.  The empty string was something I had put in my drafts, so I'm glad I asked. It's removed now. 

Appreciate the help, Bjorn. Cheers, man!

**Comment by rdwatters** [comment]
P.S. Many OS projects have people on their teams that are just devoted to the docs/education piece. I can find more, but ember.js springs to mind. Please continue to keep me posted of how I can help.
