### ISSUE TITLE
Aliases look awesome but painful when importers are limited and a large number of posts

### ISSUE THREAD

**Issue by xenoterracide** [spf13/hugo#3167]
Post blogger import using the recommended tool... it didn't [alias](https://gohugo.io/extras/aliases/
) any of my 200 some odd posts. I'm sure I could write my own importer, and work the code until it was fixed... but I noticed that [permalinks](https://gohugo.io/extras/permalinks/
) have a really nice syntax, now I could just create the same permalink, and I might.. but why not allow a global alias, maybe on a date range (anything published between x and y will have an alias permalink)

could be as simple as a global (using ~ because it's not commonly used in dates)

     aliases:
          - 2008~2015:
                  post: /:year/:month/:title/
           - 2017-03:
                  post: /:year/:title/

**Comment by bep** [comment]
There are issue(s) discussing solution to this (use the search), and all sane conclusions to those discussions end up in facilitating something outside of Hugo (generating a list for Apache, nginx etc. could use). The multiple output feature in development could maybe be used for that, but we're not createing 1000s of aliases.

**Comment by xenoterracide** [comment]
considering I'm planning on using s3+cloudfront... but sure... realistically I only have the one, so I'll probably just change the permalink to do it
