### ISSUE TITLE
Tag names with period broken

### ISSUE THREAD

**Issue by joneskoo** [spf13/hugo#3169]
I have a tag called "yx.fi" which worked fine in v0.17 but is broken in current version (v0.19). I don't use translations on my site.

**In v0.17 (expected behavior)**, my tag "yx.fi" creates the following output:

```
public
├── 1
│   └── index.html
├── index.html
├── index.xml
├── sitemap.xml
└── tags
    └── yx.fi
        ├── index.html
        └── index.xml
```

**In v0.19 (bad)** the following broken structure is generated.

```
public
├── 1
│   └── index.html
├── index.html
├── index.xml
├── sitemap.xml
└── tags
    ├── yx
    │   └── index.fi
    └── yx.fi
        └── index.xml
```

I did a git bisect and found that this is the commit that first introduced the problem:

```
ec2d502b4f214b9505dcd57713d2236c606985e8 is the first bad commit
commit ec2d502b4f214b9505dcd57713d2236c606985e8
Author: Bjørn Erik Pedersen <bjorn.erik.pedersen@gmail.com>
Date:   Mon Nov 7 20:24:37 2016 +0100

    node to page: Handle translations
    
    Updates #2297

:040000 040000 457d7aa9578680db9ff03ebbef763f386bbc26c8 c92bbe601bcc8d245791cd44ec890429ef8fdbf1 M	hugolib
bisect run success
```

So this was first broken after v0.17 but before v0.18, introduced as part of #2297 in commit ec2d502b4f214b9505dcd57713d2236c606985e8.

**Comment by joneskoo** [comment]
Here's the reproduction site I used, if it's needed. To reproduce, I believe just creating a tag called 'yx.fi' is sufficient. [repro.zip](https://github.com/spf13/hugo/files/836378/repro.zip)

**Comment by bep** [comment]
This is fixed.
