### ISSUE TITLE
different behavior with go v1.8

### ISSUE THREAD

**Issue by mehdy** [spf13/hugo#3178]
I encountered [this problem](https://discuss.gohugo.io/t/archetypes-doesnt-work/5780) and I thought I did something wrong. but I did get the hugo binary from the v0.19 release and it was ok. so the only difference is that I built my binary with go v1.8 and I assume the released binary has been built with go v1.7. I'm not sure what's causing the problem...

**Comment by bep** [comment]
Hugo 0.19 is built with Go 1.8. Please take questions/troubleshooting on the forum.
