### ISSUE TITLE
Latest go-toml breaks hugo

### ISSUE THREAD

**Issue by raphael** [spf13/hugo#3184]
This change https://github.com/pelletier/go-toml/pull/139/files#diff-2ea985d6df96843c96ae0340ce5faa90R31 breaks hugo with:
```
../../spf13/hugo/parser/frontmatter.go:55: multiple-value toml.TreeFromMap() in single-value context
```
This function now returns an error.

**Comment by bep** [comment]
See #3142

**Comment by raphael** [comment]
Awesome, thanks!
