### ISSUE TITLE
[Feature request] Partial CSS files

### ISSUE THREAD

**Issue by Avaray** [spf13/hugo#3186]
Please add feature to use partial CSS files, like this:
{{ partial "main.css" . }}

**Comment by Jos512** [comment]
I think this is already possible by using `safeCSS` and `print` for your partial. See
https://discuss.gohugo.io/t/embed-css-in-html-head-for-critical-render-path-crp/2227/
https://discuss.gohugo.io/t/using-safecss-with-partials/1609

**Comment by Avaray** [comment]
Thanks for these links. But it is not what I need. Its about writing in text editors.
For example in Atom editor, if you open HTML file with CSS inside, it will threat that file as HTML (becaise of file extension). Syntax highlighting will not work, Snippets with Tab key will not work.
In other editors like VSCode, Notepad++, snippets works, but still no syntax highlighting.

For people who want to build websites like https://bestmotherfucking.website/ (without CSS in separated file) partial CSS files might be good thing.

**Comment by rdwatters** [comment]
@Avaray [This might help make it even easier](https://atom.io/packages/set-syntax).

@bep Can we close this since it's an editor-related request and nothing to do with Hugo...unless you're thinking about a CSS-partial-related feature?

**Comment by Avaray** [comment]
Yes, I think partial CSS files might be a good idea.
