### ISSUE TITLE
docs: Remove the findRE TOC example

### ISSUE THREAD

**Issue by whereandy** [spf13/hugo#3188]
In the documentation for generating a table of contents using findRE to grab `h2`'s, the `<a href="#{{ . | plainify | urlize }}">` will not correctly generate links for heading anchors that have non-alphanumeric characters in them, such as periods. The workaround I came up with was:

```
{{ . | plainify | htmlUnescape | urlize | replaceRE "([^0-9a-zA-Z\\.\\-\\s])" "" | replaceRE "(\\.)" "-" | replaceRE "(\\-){2,}" "-" }} 
```

Which replicated the process described in heading anchor generation.

**Comment by bep** [comment]
If this is in the docs, it should be remove, not be made more complex.

**Comment by rdwatters** [comment]
> Remove the replaceRE TOC example

There isn't a replaceRE TOC example in the (new or current) docs. Are you talking about findRE, @bep?

**Comment by bep** [comment]
I'm not talking about anything. If there isn't a replaceRE TOC example in the docs, then the thread starter must have dreamed it (which I doubt), and then this issue could be closed.

**Comment by rdwatters** [comment]
That would be a very dull dream:

 
https://gohugo.io/templates/functions/#findre

You framed your response in the example of `replaceRE' and then said adding that function might have been a mistake. I am only asking if you still think the `findRE` example in the current docs needs to be removed...

**Comment by bep** [comment]
>In the documentation for generating a table of contents using findRE to grab h2's, the <a href="#{{ . | plainify | urlize }}">

OK, I have updated the issue title. But the relevant example is in the above.

**Comment by rdwatters** [comment]
This has been removed from the `findRe` example in the new docs site:

https://hugodocs.info/functions/findre
