### ISSUE TITLE
[Feature Request] Add ability to copy some files from location to another.

### ISSUE THREAD

**Issue by Mahmoudz** [spf13/hugo#3189]
### Use case:

I have a `CNAME` file that needs to be inside the `/docs` folder for Github Pages.. And I already put my `_settings` folder outside that `/docs` in order to quickly delete the `/docs` before running `hugo` to generate the new site.. 

The problem is `CNAME` file needs to be inside the `/docs` always. So to prevent accidently deleting it, would be nice to have a configuration in the `config.toml` file to copy that `CNAME` (or any other files) from the `_settings` (content folder) to the new generate HTML files in the `/docs`.

**Comment by bep** [comment]
Put it inside /static.

Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
