### ISSUE TITLE
Respect $EDITOR and $VISUAL when newContentEditor not set

### ISSUE THREAD

**Issue by callahad** [spf13/hugo#3193]
Currently, `hugo new` will only launch an editor for you [if `newContentEditor` is set](https://github.com/spf13/hugo/blob/a99661031ad771feb53e2d4b6443528ce84e1c77/create/content.go#L80-82). This can only happen in two ways:

1. Explicitly passing the `--editor` [command line option](https://github.com/spf13/hugo/blob/a99661031ad771feb53e2d4b6443528ce84e1c77/commands/new.go#L102-L104)
2. Specifying `newContentEditor` [in the site configuration](https://github.com/spf13/hugo/blob/a99661031ad771feb53e2d4b6443528ce84e1c77/hugolib/config.go#L100)

On *nix systems, a common convention is to specify an editor in either the `$VISUAL` or `$EDITOR` environment variables. Hugo does not look for either of these. I wish it did.

This causes problems if I want to use different editors on different computers, and forces me to embed a user/machine-specific option into an otherwise universal site configuration. For example, there's no way for me to use GVim on Linux, but MacVim on macOS without manually typing `--editor` each time.

__Proposed solution:__

`hugo new` attempts editors in the following order:

1. `--editor`
2. `newContentEditor`
3. `$VISUAL`
4. `$EDITOR`

This preserves the existing behavior for users who pass `--editor` or have configured `newContentEditor`, while still providing utility to users with one of the environment variables set.

**Comment by bep** [comment]
I have not heard of the `VISUAL´ being used ... but ...

A current workaround is:

```
env  HUGO_NEWCONTENTEDITOR=nano hugo new foo.md
```

I guess you could also do this in your bash profile:

```bash
export HUGO_NEWCONTENTEDITOR=$EDITOR
```

I'm not sure we need more config options ...

**Comment by bep** [comment]
I think I'm going to close this. 

There are several options to get it the way you want. And I think it may be a surprise to many if we started to open by default on, say, the `EDITOR´ env. var without a good way to turn it off.

**Comment by callahad** [comment]
Darn. I guess I can live with hugo-specific configuration in my dotfiles. That seems marginally less bad than user-specific configuration in `config.toml`.

`$VISUAL` dates back to the days of needing to distinguish between character-mode and dumb, line-oriented terminals (`vi` compare to `ed`, for example). Nowadays I've seen people use it to distinguish between GUI and terminal-based editors.

FWIW, the following patch works for me, but it sounds like you'd rather not merge it?

```patch
diff --git a/create/content.go b/create/content.go
index d38d3c7..8be32e5 100644
--- a/create/content.go
+++ b/create/content.go
@@ -79,6 +79,14 @@ func NewContent(s *hugolib.Site, kind, name string) (err error) {
 
        editor := s.Cfg.GetString("newContentEditor")
 
+       if editor == "" {
+               editor = os.Getenv("VISUAL")
+       }
+
+       if editor == "" {
+               editor = os.Getenv("EDITOR")
+       }
+
        if editor != "" {
                jww.FEEDBACK.Printf("Editing %s with %q ...\n", name, editor)
```

**Comment by moorereason** [comment]
I understand the desire to support EDITOR and VISUAL, but I think adding this as described would be surprising behavior for most users.  I have EDITOR defined in my shell, but I don't want Hugo to exec my editor when I run `hugo new`.

**Comment by rdwatters** [comment]
> /cc @rdwatters the "override Hugo config in env vars" is kind of a hidden gem in the Hugo docs, I think. Note the pattern with upper case HUGO and _ and upper case config key.

Noted @bep: https://hugodocs.info/getting-started/configuration/#environmental-variables

Think it should be called out elsewhere?

**Comment by commonquail** [comment]
> I have EDITOR defined in my shell, but I don't want Hugo to exec my editor when I run `hugo new`.

Me neither, but nor do I want to tell Hugo specifically what I already told every other editor-aware application on my system. `git config` has an `--edit` option that launches an editor chosen from a prioritised list of configurations (including `VISUAL` and `EDITOR`) and that's really the behaviour I expect. I understand why that would be undesirable given the option ambiguity.
