### ISSUE TITLE
Integrate the flatter and simpler lang file structure

### ISSUE THREAD

**Issue by bep** [spf13/hugo#3200]
See https://github.com/nicksnyder/go-i18n/issues/62

**Comment by bogem** [comment]
I will do it, but at first we should add TOML format support to go-i18n. I will take not so long time.

**Comment by nicksnyder** [comment]
go-i18n 1.8 now supports TOML and a flatter file format
https://github.com/nicksnyder/go-i18n/releases/tag/v1.8.0

Thanks @bogem !
