### ISSUE TITLE
Remove Site.Recent from documentation

### ISSUE THREAD

**Issue by mdhender** [spf13/hugo#3201]
The Site.Recent variable is obsolete but the documentation says that it is deprecated. It is mentioned in the entry for Site.Pages.

See https://discuss.gohugo.io/t/site-recent-deprecated-or-removed/5851

**Comment by bep** [comment]
I would really appreciate if you could just create a Pull Request for such minor adjustments. I.e. just do it and not create extra work for me and others to follow up on.
