### ISSUE TITLE
Ignore "." dirs in hugo --cleanDestinationDir 

### ISSUE THREAD

**Issue by hippora** [spf13/hugo#3202]
hi,when i execute hugo --cleanDestinationDir ,it clean the public directory,but also delete .git in public what i want sync to github.io. 

so can this directive did not remove .git ? thankyou

**Comment by eamonnmcevoy** [comment]
@bep Hi, I'd like to contribute to the project, could I be assigned this issue? thanks

**Comment by eamonnmcevoy** [comment]
I'm going to extend `mostafah/fsync` to allow a filter function to configured to allow certain files to remain in the destination folder

**Comment by bep** [comment]
What is `mostafah/fsync`?

**Comment by eamonnmcevoy** [comment]
It's one of the dependencies in the vendor folder, that's where the code is to clean the destination folder.
`github.com/spf13/vendor/github.com/spf13/fsync` which is a fork of `mostafah/fsync`

**Comment by vbmade2000** [comment]
@bep  I think we can close this issue.

**Comment by eamonnmcevoy** [comment]
The change I've made for fsync won't resolve this though, it's just allows a filter to be applied. I'll need to update Hugo once the fsync pull request is merged.

**Comment by bep** [comment]
The fsync is merged ...

**Comment by eamonnmcevoy** [comment]
@bep 
Should I change the default behaviour of `cleanDestinationDir` to ignore '.' folders? 
I'm considering add a new option instead `cleanDestinationDirKeepDotFolders`? 

What do you think?

**Comment by eamonnmcevoy** [comment]
I think this can be closed now
