### ISSUE TITLE
error calling delimit: can't iterate over <nil>

### ISSUE THREAD

**Issue by luffycheung** [spf13/hugo#3204]
localhost:myblog luffycheung$ hugo --theme=casper --buildDrafts -- baseUrl="..."
Started building sites ...
ERROR 2017/03/21 00:30:02 theme/partials/semantic.html template: theme/partials/semantic.html:52:19: executing "theme/partials/semantic.html" at <delimit .Params.tags...>: error calling delimit: can't iterate over <nil>

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
