### ISSUE TITLE
Reloading post with latest date and _index.md results in build error

### ISSUE THREAD

**Issue by halogenica** [spf13/hugo#3209]
Occurs on hugo v0.19. To reproduce, I created two posts, one on Jan 1st and one on Jan 2nd. I also created an _index.md at the root of the content directory. Then run `hugo server -w`. When making any modification to the latest post (the 2nd post), the first time I save, the following error is generated:
`ERROR 2017/03/20 22:50:41 Error while rendering "page _index.md": template: C:\Users\angelk\Desktop\website\halogenica\q\themes\after-dark\layouts\_default\baseof.html:11:12: executing "main" at <.Paginate>: error calling Paginate: invoked multiple times with different arguments`

The problem only occurs on the page with the most recent date, and only if _index.md is present in the root of the content directory. When first starting the server everything behaves correctly, the error only occurs when saving the second post, and only the first time the post is saved.

[content.zip](https://github.com/spf13/hugo/files/857198/content.zip)

**Comment by ajiyakin** [comment]
I try to generate the issue with another theme ([hugo_theme_robust](https://themes.gohugo.io/robust/)) and it just works fine, only if I uses _[after-dark](http://themes.gohugo.io/after-dark/)_ theme the error is occur. Basically hugo failed to parse the template. So I think this issue should be reported to the template project itself, unfortunately they disabled the [issues](https://github.com/comfusion/after-dark#contributing).

**Comment by jhabdas** [comment]
I didn't do it. j/k taking a look

**Comment by jhabdas** [comment]
Not able to reproduce. But I've seen that error before, not consistently. Please restart your machine. If the issue persists uninstall and reinstall Hugo.

**Hugo Static Site Generator v0.18.1 BuildDate: 2016-12-30T01:12:41+08:00**
- Generate new site with `hugo new site`
- Follow theme [Getting Started](https://github.com/comfusion/after-dark#getting-started) instructions
- Copy contents of zip into `/content/`, run site
- Open `_index.md` file in editor, save file multiple times

**Hugo Static Site Generator v0.19 darwin/amd64 BuildDate: 2017-02-27T18:21:29+08:00**
- Follow above steps
- View results http://pastebin.com/KnKSwtVt

**Test environment**
macOS: 10.12.3 (16D32)

**Comment by jhabdas** [comment]
@halogenica @ajiyakin if you have a chance, please try my suggestions above and let me know if there's anything else I can do to help.

**Comment by halogenica** [comment]
@jhabdas Thanks for checking this out! Unfortunately you changed the wrong file above; it reproduces if you have to change "second.md". It only occurs if you're changing the most recent post; I suspect an out of bounds access when working with the last sorted post in the pagination code. I did reboot and try again, error still occurs. I have both windows and mac and I believe the error occurs on both systems.

**Comment by halogenica** [comment]
I should mention that It only reproduces with certain themes (presumably themes that make use of the _index.md at the root of the content folder). after-dark is one such theme, and the latest version of my ported theme "beautifulhugo" is another.  https://github.com/comfusion/after-dark https://github.com/halogenica/beautifulhugo

**Comment by jhabdas** [comment]
> Unfortunately you changed the wrong file above; it reproduces if you change "second.md".

Thanks for the additional info @halogenica. I'm **able to reproduce** the error now. It occurs on first save of most recently dated file on first build only using `hugo serve` when:

- There is an `/content/_index.md`
- And also a `/layouts/index.html` with a *filtered* [paginator](https://gohugo.io/extras/pagination#list-the-pages)

**Impact**
Doesn't seem to affect build output. But may impede dev workflows (e.g. date changes not causing the paginator pages to update without `hugo` restart).

**A workaround**
Rename `index.html` to `index.htm` (seriously, try it)

**Parting thoughts**
Weird. /cc @moorereason

**Comment by halogenica** [comment]
Haha how on earth does renaming index.html to index.htm fix it, and how did you think of that?

That workaround does in fact work for after-dark's theme, but unfortunately **does not work** for my beautifulhugo theme. 

Also I'm surprised your build output is not affected. Mine fails catastrophically 100% of the time; hugo quits building the website after the .Paginate call. For example, using the after-dark theme with the same content I provided in this bug report, here's the front page:

- First build - http://pastebin.com/aN4nVTJV
- Rebuild - http://pastebin.com/R4Ax3miD
- index.html - http://pastebin.com/fLBJ0q6Z

From the index.html above and diffing the generated HTML you can see that the generated page is missing all content after the line '{{ range (.Paginate (where .Data.Pages "Type" "post")).Pages }}' from the theme. Refreshing the browser tab doesn't do anything; only killing and restarting the hugo server fixes the issue. After the first save and live reload there are no more errors generated, but the rendered html content is still broken.

**Comment by bep** [comment]
To all of you: I'm not sure what happens in *this* scenario, but I will merge #3122 in a day or two -- which will be in the Hugo 0.20 release a week or so from now. #3122 has lots of new stuff, but also a total refurbishment/unifying of all (or most) of the path/URL handling in Hugo. It fixes a lot of reported issue, and probably also a few unreported. URL handling has been the most fragile part of Hugo, too many functions doing similar stuff, and Windows hasn't helped, either.

**Comment by jhabdas** [comment]
@halogenica @ajiyakin https://github.com/comfusion/after-dark/issues now open. I had to cut a `v1.0.0` before I opened them up and it wasn't until tonight I discovered a good way to automate the release process without overdoing it.

**Comment by martinhoefling** [comment]
Seems as renaming `index.html -> index.html` also "solves" the issue for the hugo-tranquilpeak-theme.

**Comment by jhabdas** [comment]
@martinhoefling Thanks for letting us know changing the file extension from `html` to `htm` is working for other themes as well. Glad to hear it.

**Comment by ajiyakin** [comment]
That's strange :smile:

**Comment by halogenica** [comment]
Wanted to comment that renaming the extensions from `.html` to `.htm` actually does work around the issue on my theme too, I just didn't realize at first I had to do it on multiple files (both index.html and list.html in my case).

Unfortunately, not fixed with the latest 0.20 release.

**Comment by halogenica** [comment]
I found out today that renaming the extension from html to htm does fix windows, but actually causes nothing to be built on MacOS. 

@bep Currently this bug is marked as "Can't Reproduce" but since it has indeed been reproduced by a few people in this thread, and it is still broken as of the latest version of Hugo, can we please change the tag on this bug? Just to recap, as @jhabdas pointed out above, the problem occurs when:
- There is a /content/_index.md
- And also a /layouts/index.html with a _filtered_ paginator
It seems clear that the filtered paginator code has a bug when operating on the last element in the list.

**Comment by bep** [comment]
@halogenica I'm pretty sure that this issue was solved in Hugo 0.20.2.

**Comment by halogenica** [comment]
@bep Thank you! Indeed this does appear fixed in 0.20.2 (which is also when renaming html to htm stopped working). This can now be closed.
