### ISSUE TITLE
Preserve raw .Inner in shortcode

### ISSUE THREAD

**Issue by jiridj** [spf13/hugo#3216]
Hi,

I've created a simple shortcode to generate a CSS-based terminal (shortcode, css and test file in attached [terminal.zip](https://github.com/spf13/hugo/files/862947/terminal.zip)). The command line itmes are passed in as a regular markdown list. 

```
{{% terminal "~/Sites/jiridj.be" %}}
- $ ls -l ~
- total 40
- drwx------+  8 jiri  staff    272 Mar 21 14:30 Desktop
- drwx------+ 11 jiri  staff    374 Mar 21 16:47 Documents
- drwx------+ 10 jiri  staff    340 Mar 22 13:36 Downloads
- drwx------@ 70 jiri  staff   2380 Mar 15 12:44 Library
- drwx------+  8 jiri  staff    272 Feb 14 04:54 Movies
- drwx------+  5 jiri  staff    170 Oct 19 17:07 Music
- drwx------+  9 jiri  staff    306 Feb  3 10:26 Pictures
- drwxr-xr-x+  5 jiri  staff    170 Oct 19 14:23 Public
- $ _
{{% /terminal %}}
```

The output is rendered like this.

<img width="440" alt="screen shot 2017-03-22 at 22 18 02" src="https://cloud.githubusercontent.com/assets/6419179/24221164/7ee4787a-0f4d-11e7-9aff-c192f477477d.png">

At first sight this works great, but I noticed some of the raw characters are replaced. For example, three dashes got replaced by a single '&mdash;'. 

After fixing that I tried with something more complex as a test case: ASCII art. 

```
{{% terminal "~/southpark" %}}
- $ print()
-    _O_        _____         _<>_          ___  
-  /     \     |     |      /      \      /  _  \
- |==/=\==|    |[/_\]|     |==\==/==|    |  / \  |
- |  O O  |    / O O \     |   ><   |    |  |"|  |
-  \  V  /    /\  -  /\  ,-\   ()   /-.   \  X  /
-  /'---'\     /'---'\   V( '-====-' )V   /'---'\
-  O'_:_'O     O'M|M'O   (_____:|_____)   O'_|_'O 
-   -- --       -- --      ----  ----      -- --   
- $ _
{{% /terminal %}}
```

This gets all scrambled up, mainly because of whitespace it seems. 

<img width="434" alt="screen shot 2017-03-22 at 22 21 50" src="https://cloud.githubusercontent.com/assets/6419179/24221429/92838438-0f4e-11e7-9c04-e6f6b99974a6.png">

Is my assumption correct and is it due to leading and trailing whitespace being trimmed? If so, is there a way to change this behaviour within this shortcode?

Thanks!

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).
