### ISSUE TITLE
Move current gohugo.io and themes.gohugo.io to Netlify

### ISSUE THREAD

**Issue by bep** [spf13/hugo#3228]
This is a technical prerequisite for getting the refreshed gohugo.io site out the door, but as the current build is broken on several levels (for one, the deployment machine fails on the Git command -- and the docs was the main motivation for adding that feature in the first place ... -- and it has a too old version of Hugo). 

**So I suggest we just do this quick and hard for the current static sites.**

We already have a Netlify build for the main site, so the suggested game plan is:

1) @spf13 tries to get a theme site up and running (with the scripts and all) on Netlify. (I have no access to configure the Git link)
2) When 1) is OK, @spf13 make the DNS switch.

Sounds OK?

* And please, please don't make this into a discussion about any future site setup. This is about the **current production environment**, and that only.

/cc @budparr @rdwatters

**Comment by rdwatters** [comment]
> We already have a Netlify build for the main site

Which site?  Actually, it probably doesn't matter since both the docs and the news site are on Netlify. 

I'm cool with whatever process you guys want. As I mentioned to @budparr, I already updated some of the styles per his quick and dirty suggestions, so the contrast between the new home and docs is more seamless. 

@bep, ideally, how much time are you thinking? I ask just so that I know how much time I have to finish the 1 or 2 WIP pages. . Thanks!

**Comment by rdwatters** [comment]
Also, @digitalcraftsman and @budparr; I haven't been keeping up with the themes site as much. I can do a PR to line up the styles. I'm okay with getting this done now and refining the theme/styles in future iterations.

**Comment by bep** [comment]
@rdwatters I will say this one final time: **This issue is about the CURRENT gohugo.io and themes.gohugo.io.**

**Comment by budparr** [comment]
I imagine @biilmann could be helpful with this process, and it may be helpful to get the sites on the "Pro" plan, which is free for open source projects. Let me know if there's anything specific I can do to help.

**Comment by rdwatters** [comment]
I'm cool with whatever you want to do. Still. 

I agree that the the guys at Netlify would probably be of great help. I shouldn't go on Github when I wake up at 3am randomly.

**Comment by spf13** [comment]
I support this and will do whatever I need to do / can do to help.

**Comment by bep** [comment]
>I support this and will do whatever I need to do / can do to help.

@spf13 I will turn this around: I assigned this issue to *you*, so you will have to drive this issue. You have the needed access to your DNS provider etc., so it isn't very practical for anyone else to do it.

But I will do anything I can do to help ...

**Comment by calavera** [comment]
This is how I'd approach setting up themes.gohugo.io on Netlify:

1. I'd add https://github.com/spf13/hugoThemeSiteScript as a submodule of https://github.com/spf13/hugoThemesSite
2. I'd add a script in `hugoThemesSite` that updates the submodule, runs the script and builds the site.
3. I'd create the site on Netlify making that script the build command.

There might be other alternative ways to accomplish it, but this sounds like a reasonable game plan to me.

**Comment by bep** [comment]
@spf13 Have added some TODO tasks for myself in the first post here; when I finished that, it should be ready for you to do the rest. I will let you know when I'm done.

**Comment by bep** [comment]
@spf13 I need you to create a site from the repo:

* https://github.com/spf13/hugoThemes
* Branch: master
* Build command: buildThemeSite.sh
* Publish directory: _script/hugoThemeSite/themeSite/public

Don't worry if it fails ... I will fix that.

**Comment by bep** [comment]
@spf13 I was hoping we could get this done before Hugo 0.20 (which I guess will ship on Monday), but that looks ... optimistic with this speed.

**Comment by spf13** [comment]
@bep I've set it up as hugothemes.netlify.com and invited you to be a collaborator.

**Comment by biilmann** [comment]
Let us know if there's anything we can do to help at any point :)

**Comment by bep** [comment]
@spf13 @biilmann that was pretty smooth sailing; my "blind scripting" worked almost right out of the box:

https://hugothemes.netlify.com/

As I see it, both sites are now set up correctly vs branches and deployments scripts and can be switched in DNS:

* https://hugoio.netlify.com/
* https://hugothemes.netlify.com/

**Comment by bep** [comment]
And it is pretty fast as well, considering it is pulling in and building 150+ themes ...

![image](https://cloud.githubusercontent.com/assets/394382/24828170/dc2ff006-1c57-11e7-8c37-3696f33044d1.png)

**Comment by digitalcraftsman** [comment]
It's great to see some progress in this area and I can second @bep that the build times are really fast.

@bep how can I help?

**Comment by bep** [comment]
@digitalcraftsman the DNS updates @spf13 has to do. He should also add you as a collaborator, I guess you "own" these sites more than me ... It is pretty nice to have a log to look at ... I would "never" have found the small item in my script that failed on Linux without it.

**Comment by digitalcraftsman** [comment]
> He should also add you as a collaborator, I guess you "own" these sites more than me ... 

It's more about maintenance that ownership but I get it :wink:

> It is pretty nice to have a log to look at ... I would "never" have found the small item in my script that failed on Linux without it.

This is one of the most important points - hopefully we can forget the "blind man porking around in the dark"-metaphor.

**Comment by bep** [comment]
@digitalcraftsman what you can do is to check that the site reflects the changes in the theme as you update them.

**Comment by bep** [comment]
>hopefully we can forget the "blind man poking around in the dark"-metaphor.

The good thing about that is if in the future see a job ad searching for a `Jedi DevOps`, you can apply and put me up as a reference :-)

A related story from back when I was a student and not loaded with money. My 17 inch CRT monotor broke down. I spent enough time on the university PC lab, so I could do without a computer, but I had a document on the harddrive that I really needed. The PC was not connected to any network (this was in the early days of computing), but it had a printer attached ...

A long story short: I finally managed to turn on the computer, open up the word processor, the document and print it ...

**Comment by bep** [comment]
@biilmann the Netlify log console for the theme build is consistently making my browser unresponsive (Chrome on MacBook).  But only if I "watch it" live, so it's a minor problem.

**Comment by dplesca** [comment]
It seems that the [netlify themes site](https://hugothemes.netlify.com/) is missing two themes from the [official themes site](http://themes.gohugo.io): [arch](https://github.com/syui/hugo-theme-arch) and [purehugo](https://github.com/dplesca/purehugo).

**Comment by digitalcraftsman** [comment]
That's because they're [blacklisted](https://github.com/spf13/hugoThemes/blob/master/_script/generateThemeSite.sh#L101).

**Comment by spf13** [comment]
I'm ready to pull the trigger and move the DNS over. Just let me know when and I'll flip the switch.

**Comment by bep** [comment]
@spf13 just to it whenever you please.

**Comment by digitalcraftsman** [comment]
The transition was successful and DNS entries are updated.
