### ISSUE TITLE
Errors from GitHub deployment when following instructions

### ISSUE THREAD

**Issue by fhunleth** [spf13/hugo#3232]
I've tried following the instructions for GitHub deployment using the `gh-pages` branch version. Up to the `git worktree` line, everything appears to work fine and make sense. Here's what I'm getting after this:

```
$ git worktree add -B gh-pages public origin/gh-pages
Branch gh-pages set up to track remote branch gh-pages from origin.
Preparing public (identifier public)
fatal: Refusing to point HEAD outside of refs/
```
Also,

```
$ git --version
git version 2.7.4
```
While I realize this is more of a `git` usage issue than a `hugo` one, I'm hoping someone watching who uses the `worktree` feature for their deployment can help with this. If there's some clarification needed in the instructions, I'll gladly send a PR. Fwiw, the `clone` method for older `git` versions works fine for me.

**Comment by rdwatters** [comment]
@fhunleth I would recommend trying https://discuss.gohugo.io since that's where we field all support-related issues. For that reason, I am closing this ticket. You'll get much better feedback on the forums. Cheers!

**Comment by fhunleth** [comment]
Done. Thanks for pointing me to the forums. https://discuss.gohugo.io/t/github-deployment-using-worktrees-failing/5918
