### ISSUE TITLE
Unexpected behaviour - `.Content` returns plain text if used inside a HTML tag parameter:

### ISSUE THREAD

**Issue by liwenyip** [spf13/hugo#3237]
Unexpected behaviour (or undocumented feature?) - `.Content` returns plain text if used inside a HTML tag parameter:

Tested on www.liwen.id.au/barbershop-charts

# Example 1 - expected behaviour

`plainify` doesn't remove contents of `<style></style>`, as reported in #3235

Hugo: 
`<meta property="og:description" content="{{ .Content | plainify }}">` 

HTML (newlines and whitespace removed): 
`<meta property="og:description" content="Here are some easy-to-follow flowcharts to help you remember the words to popular barbershop songs. figure { border: 1px solid lightgrey; }  (Click to zoom) Hello Mary Lou .gallery .img2` (truncated)

# Example 2 - weird...

 `.Content` returns plain text, and even strips contents of `<style></style>` - **is it supposed to do that?**

Hugo:
`<meta property="og:description" content="{{ .Content }}">`

HTML:
`<meta property="og:description" content="Here are some easy-to-follow flowcharts to help you remember the words to popular barbershop songs. (Click to zoom) Hello Mary Lou` (truncated)

# Example 3 - expected behaviour

Hugo (tested both in `<head>` and `<body>` sections:
`{{ .Content }}`

HTML content (truncated, newlines removed):
```
<p>Here are some easy-to-follow flowcharts to help you remember the words to popular barbershop songs.</p>
<p></p>
<style>
figure {
    border: 1px solid lightgrey;
}
</style>
<p>(Click to zoom)</p>
<h2 id="hello-mary-lou">Hello Mary Lou</h2>
<style>.gallery .img2 {background-image: url('/img/barbershop-charts/mary-lou.png');}</style>
```

**Comment by rdwatters** [comment]
@lilwenyip I think I might not be keeping up with this thread in the context of the previous related issue, and usually my forthcoming suggestion is a better fit for the forums, but just for my own understanding in case this requires some doc changes... 

Have you tried this is conjunction with 

https://hugodocs.info/functions/safehtmlattr/

**Comment by bep** [comment]
This is the work of the Go templates, and you should ask them. Or at the forum.

**Comment by liwenyip** [comment]
Ah I understand now this is a security feature of `html/template`. 

@rdwatters yes `{{ .Content | safeHTMLAttr }}` dumps escaped HTML into the attribute.

Apologies again for being a GitHub newbie and posting this in the wrong place, I know now, if in doubt, post in the forum in the first instance.

**Comment by rdwatters** [comment]
@liwenyip 

If you have any other suggestions for docs or how to make this clearer as people are adding template similar to what you're doing above, please comment here: 

https://discuss.gohugo.io/t/new-docs-site-need-feedback/5765

Or feel free to open an issue (or better PR :smile: ) here. I know you're not technically a new user, but I'd love feedback on the new docs: 

https://github.com/rdwatters/hugo-docs-concept/ 

And let's definitely keep all these convos out of the Hugo issues. Thanks!
