### ISSUE TITLE
Symlinks are silently ignored

### ISSUE THREAD

**Issue by satan1st** [spf13/hugo#3241]
If a markdown file is a symlink, it is ignored without an error. This [patch](http://ix.io/phk) should fix it.

I can't test it because go on freebsd is somehow broken and I can't build hugo

hugo version:
Hugo Static Site Generator v0.19 freebsd/amd64 BuildDate: 2017-02-27T12:36:56+01:00

**Comment by bep** [comment]
Markdown files as symlinks isn't supported, and the behaviour is undefined.

And we don't accept untested patches.
