### ISSUE TITLE
Leverage if blocks in Markdown

### ISSUE THREAD

**Issue by rmspeers** [spf13/hugo#3244]
We are utilizing if blocks, based on parameters/etc, in our templates and shortcodes.
```
{{ if isset .Site.Params "includeinfoaboutx" }}
```

However, there are some cases where we need to modify the content itself -- in the Markdown file, for example if we have the parameter includeinfoaboutx set, then we want to show a specific block of text, if not, we may want to display a second block of text instead.

This would work fine if it was in a template and we wrote in HTML, but this doesn't work in a Markdown file used as content.

We would like to be able to do something like the following, _in a Markdown file_:
```
{{ if isset .Site.Params "includeinfoaboutx" }}

Here we will discuss the feature X and give some examples.

> NOTE: We will want to use markdown inside this block.

{{ else }}

Here we say that feature X is not documented in this version.

{{ end }}
```

**Comment by rdwatters** [comment]
https://hugodocs.info/content-management/shortcodes/

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
