### ISSUE TITLE
Add hugo flag "--staticDir" on command-line

### ISSUE THREAD

**Issue by amaurycatelan** [spf13/hugo#3247]
Hello guys,
I have a situation where a need to pass a different folder to "staticDir" on command-line.
As well as: `--layoutDir` or `--contentDir` - for example.

`hugo --layoutDir custon-folder`  ✅ 

Well, "staticDir" option works perfecly in [config file](https://gohugo.io/overview/configuration) and
apparently this flag is not enabled. 😢 

- `hugo help | grep layoutDir` ✅ 
- `hugo help | grep contentDir` ✅ 
- `hugo help | grep staticDir` ❌ 

I think it's simple. So, can i suggest a pull request about?
Thank you. 😄

**Comment by bep** [comment]
Try: 

```
HUGO_STATICDIR=/mystatic/dir hugo
```

If that doesn't help, try the discussion forum.
