### ISSUE TITLE
Broken syntax-highlighting on current master branch

### ISSUE THREAD

**Issue by metachris** [spf13/hugo#3275]
Hello,

I've been trying out the code of the master branch today, and it seems that it does not do syntax-highlighting at all (no `<pre>` or `<code>` tags when using a highlight shortcode such as `{{< highlight go >}} A bunch of code here {{< /highlight >}}`).

It's working in the v0.19 release of course. 

Btw: It would be great if you could release v0.20 soon because it fixes the bug with period in tags (which is why I've been trying the master code in first place ;)!

<3

**Comment by bep** [comment]
>Btw: It would be great if you could release v0.20 soon because it fixes the bug with period in tags (which is why I've been trying the master code in first place ;)!

So we should release v0.20 even if the hightlight shortcode isn't working for you?

**Comment by metachris** [comment]
No need to be snarky.

I was just reporting a bug I've experienced, and on an only slightly related note expressed my desire to see the next release which fixes another pretty important issue.

**Comment by bep** [comment]
>No need to be snarky.

Yes it was.

**Comment by bep** [comment]
And I cannot reproduce this either, and we do have tests for this running fine on "all" systems, so I suspect others would have shouted already, so I suspect "something else" is going on.

Do you have a public sourced site with this problem?

**Comment by metachris** [comment]
```
$ hugo env
Hugo Static Site Generator v0.20-DEV darwin/amd64 BuildDate: 2017-04-04T10:51:42+02:00
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.8"
```

I was able to reproduce the bug (syntax highlighting shortcode getting ignored) by just following the steps in the [Hugo Quickstart Guide](https://gohugo.io/overview/quickstart/): 

* Create a new site: `$ hugo new site bookshelf`
* Add content: `$ hugo new post/good-to-great.md`
  * Add `{{< highlight go >}} A bunch of code here {{< /highlight >}})` to the post
* Add a theme: 
```
$ cd themes
$ git clone https://github.com/dim0627/hugo_theme_robust.git
$ (cd hugo_theme_robust; git checkout b8ce466)
```

* Serve the site: `$ hugo server --theme=hugo_theme_robust --buildDrafts`

---

Viewing the page there is simply no syntax highlighting, and this is the resulting HTML:

```
<div class="article-body" itemprop="articleBody">
      <p> A bunch of code here .</p>
</div>
```

**Comment by bep** [comment]
@metachris I'm not able to reproduce this with your example, either, and since my setup is similar (Mac), I guess your problem is Pygments-related.

Run `hugo -v` and look for errors or warnings.

Also note that I recently fixed an issue where WARNING from the global logger were not printed even if `-v` was set, so a pull for the latest Hugo may give you more output in verbose mode.

**Comment by metachris** [comment]
Solved the issue by installing Pygments with `pip install Pygments`. Should this perhaps be included in the installation instructions?

Thanks for the support.

**Comment by metachris** [comment]
Perhaps want to add a WARNING if the `highlight` shortcode is used but Pygments is not installed?

**Comment by bep** [comment]
We have a WARNING in that case.

**Comment by metachris** [comment]
It didn't show in my case:

```
$ hugo server --theme=hugo_theme_robust --buildDrafts -v
INFO 2017/04/05 13:06:53 Using config file:
INFO 2017/04/05 13:06:53 using a UnionFS for static directory comprised of:
INFO 2017/04/05 13:06:53 Base: /Users/chris/ToDelete/bookshelf/themes/hugo_theme_robust/static
INFO 2017/04/05 13:06:53 Overlay: /Users/chris/ToDelete/bookshelf/static/
INFO 2017/04/05 13:06:53 syncing static files to /
WARN 2017/04/05 13:06:53 Translation func for language en not found, use default.
WARN 2017/04/05 13:06:53 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
Started building sites ...
INFO 2017/04/05 13:06:53 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
INFO 2017/04/05 13:06:53 Alias "/post/page/1/index.html" translated to "post/page/1/index.html"
INFO 2017/04/05 13:06:53 Alias "/page/1/index.html" translated to "page/1/index.html"
WARN 2017/04/05 13:06:53 404.html is rendered empty
Built site for language en:
1 of 1 draft rendered
0 future content
0 expired content
1 regular pages created
8 other pages created
0 non-page files copied
2 paginator pages created
0 categories created
0 tags created
total in 53 ms
WARN 2017/04/05 13:06:53 Skip i18nDir: lstat /Users/chris/ToDelete/bookshelf/i18n: no such file or directory
Watching for changes in /Users/chris/ToDelete/bookshelf/{data,content,layouts,static,themes}
WARN 2017/04/05 13:06:54 Skip i18nDir: lstat /Users/chris/ToDelete/bookshelf/i18n: no such file or directory
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by rdwatters** [comment]
@metachris FWIW, The requirement for Pygments is called out in two different places in the docs concept, both as a section under installation and then called out and explained pretty clearly in tools/syntax-highlighting.

https://hugodocs.info/getting-started/installing/#installing-pygments-optional

https://hugodocs.info/tools/syntax-highlighting/

I know you are now asking about the warning to the console, but I'm open to suggestions if you think there are better ways to document this dependency moving forward. Thoughts?

**Comment by metachris** [comment]
Wow, thanks. This is a pretty great, constructive response!

I've been building software for a while, and typically know how to follow installation instructions ^^ 

I think my problem was that I came to this site when looking for building from source: http://gohugo.io/overview/installing/#installing-from-source. Pygments is mentioned far above and was not in the picture here. Perhaps another reminder such as in this PR?

Just trying to contribute ;)
