### ISSUE TITLE
{{ trim .Inner }} broken

### ISSUE THREAD

**Issue by jpap** [spf13/hugo#3279]
I created a shortcode for use like this:
```
{{< quote >}}
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis massa porta diam rutrum lobortis. Quisque ultricies sem porta efficitur eleifend. Aliquam nec sem cursus, lobortis justo nec, placerat odio. Sed vitae purus dui. Donec sed venenatis ipsum.
{{< /quote >}}
```
having definition:
```
<q>{{ with $x := .Inner }}{{ trim $x "\n" }}{{ end }}</q>
```
which works well.  The trim is here because otherwise the rendered HTML will have a space between the inner text and the surrounding quotes.  The only other way to remove the whitespace is to ensure that the shortcode is on the same line as the content, where it is easy for the post writer to forget.

But the straightforward shortcode definition,
```
<q>{{ trim .Inner }}</q>
```
did not work at all: it screwed up the nesting of all subsequent tags.

Similarly, the working definition at the top only worked when I add the `"\n"` second argument to `trim`.  That looks like another (possibly related?) bug to me.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by jpap** [comment]
Confirmed that this is not a bug:
* `trim` requires the "cutset" second argument specifying what to trim. In this case, it needs to be `"\n"` and/or `"\n "` (newline + space).  I was a little confused by the brevity of [the documentation](http://gohugo.io/templates/functions/).
* The straightforward shortcode definition then works as expected:
  ```
  <q>{{ trim .Inner "\n " }}</q>
  ```

**Comment by rdwatters** [comment]
> I was a little confused by the brevity of the documentation.

Thank you for mentioning this @jpap Hopefully the following clears up any confusion:

https://hugodocs.info/functions/trim/

If you have any other feedback, please add it to the forums or create [a new issue in the docs concept repo](https://github.com/rdwatters/hugo-docs-concept). I am soliciting as much feedback as possible from users. Cheers.

**Comment by jpap** [comment]
Fantastic, @rdwatters!
