### ISSUE TITLE
Minimalist website with homepage as content

### ISSUE THREAD

**Issue by falzm** [spf13/hugo#330]
Hi

I'd like to use Hugo for my personal website, which roughly consists of two HTML pages:

* the homepage (http://falzon.me/)
* my résumé (http://falzon.me/cv/)

I'm actually struggling to do a simple thing, which doesn't seem to be possible to do with Hugo: write the content of the homepage (a.k.a. `/index.html`) as Markdown — `content/index.md` for instance —, among other content pages in the `content/` directory. For what I understand from the documentation, the homepage has a special status, and requires a dedicated template file for display.

My problem is: I don't want the content of the homepage to be directly in the HTML template, I want it to be written as Markdown in `content/` as any other page, and rendered/included in the `layout/index.html` template file. Is there any way to achieve this? If not, what simple workaround can you suggest so I can keep the simple structure of my website?

Cheers,

m.

**Comment by mbertschler** [comment]
@tlipski it should work that way as well. How you write that part is totally irrelevant, because /index.html will only get generated once.

**Comment by tlipski** [comment]
@mbertschler I altered it this way so next/prev/title can work properly

**Comment by codethief** [comment]
After two hours of trying to find out how to create a simple, non-blog – in that sense, actually static – website with Hugo, I finally arrived here. Thanks for the workarounds, guys!

**Comment by gutenye** [comment]
Nice workarounds, I really wish Hugo can support it by default

**Comment by irisli** [comment]
:+1:

It would be great if Hugo had better support for homepage as a content file (and not as a layout file). On the sites I've been using Hugo on, the home page layout is the same as some other content pages.

**Comment by codethief** [comment]
@spf13 Any news regarding this issue?

**Comment by nikolas** [comment]
I needed to customize some CSS only on the homepage, so I wanted to add a class to the `body` tag to decide whether to apply my CSS. I did this:

```html
<body class="page-{{ .Title | urlize }}">
```

And now I can make a CSS rule like:
```css
body.page-title-of-my-site {
    background-color: #000;
}
```

that's only applied on the homepage.

**Comment by rhewitt22** [comment]
:+1: for handling index page content as a first class citizen.

**Comment by fazy** [comment]
After experimenting with themes, I decided to build my site from the ground up (but looking at themes for reference). It's a small, personal site, but I want to devote most of the home page to my Flickr photos feed, and relegate the blog to a sub-section. As such, the home page will be fairly bespoke, with very little blog content, while the blog section will fit well with the content/templates model used by Hugo.

So just to see it working (hello world, minimum viable product, iterate...) my entire home page is like this:

**layouts/index.html**

    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>{{ .Site.Title }}</title>
    </head>
    <body lang="en">
    
    <section id="main">
        <div>
            {{ range .Data.Pages }}
                {{if and (eq .Type "index") (eq .Title "heading" ) }}
                    {{.Content}}
                {{end}}
            {{ end }}
    
            <hr>
            <p>Stuff baked into the template... should probably still use variables like {{ .Site.Title }}</p>
            <hr>
    
            {{ range .Data.Pages }}
                {{if and (eq .Type "index") (eq .Title "intro" ) }}
                    {{.Content}}
                {{end}}
            {{ end }}
        </div>
    </section>

Then I have the content files:

**content/index/heading.md**

    +++
    type = "index"
    title = "heading"
    +++
    
    # Page heading
    ## Sub heading
    a little bit of text maybe
    
**content/index/intro.md**

    +++
    type = "index"
    title = "intro"
    +++
    
    # Hello,
    
    Here is a little intro about me that I am going to place
    further down the page (e.g. after a big photo).

I've basically done the same as @mbertschler (thanks!), but with the ability to have a couple of bits of content in different parts of the home page. I'm not 100% sure if I'll need that yet, but it's good to have the flexibility if I decide not to do the whole template in markdown.

**Comment by fazy** [comment]
This work-around doesn't seem to work for partials. For example, if including code like this:

    <title> {{ .Title }} &middot; {{ .Site.Title }} </title>

`.Title` is not set.

How can I determine what page I am really on?

**Comment by digitalcraftsman** [comment]
Try `$.Title` within the partial.

**Comment by bep** [comment]
Use The discussion site for questions.

**Comment by fazy** [comment]
If I delete my question above, will you re-open this feature request? I think a number of people would like to have an index page.

**Comment by bep** [comment]
My bad ... I thought this was a new topic... Yes, this will come at some point.

**Comment by fazy** [comment]
That's very good to know, thanks. :) And sorry to be lazy about signing up for the forums, but I've done that now.

**Comment by mbertschler** [comment]
I would like to fix this for the next release. The question is how this could be implemented. 

My proposal would be that if there is an `index.md` file in the content directory, that the relevant `single.html` template file will be used instead of the `index.html` file from the template. I think the index file could be a special case because this is how it always worked with html files.

What are your thoughts?

**Comment by rhewitt22** [comment]
Simple, solid solution. I think the homepage should also fall back on `default/single.html` too if an index.md is present but an index layout isn't defined. 

Roy

**Comment by spf13** [comment]
I think this may already be the case.

**Comment by spf13** [comment]
This may be part of the solution, but it doesn't resolve all the issues. it
doesn't treat index.md as the root. We also should have a general solution
for binding content to nodes.

**Comment by bep** [comment]
See https://discuss.gohugo.io/t/node-improvements/1593

Please, no hacks just to get the home page to "somehow work".

**Comment by integrii** [comment]
I ran into this issue today.

I personally would like to see `content/_index.md` parsed and made available to `layouts/index.html`.  This still allows for a regular `index.md` file to be created which would create a `/index` path to your site.

**Comment by richie5um** [comment]
@mbertschler Thank you!

**Comment by bep** [comment]
Will be handled in #2297.
