### ISSUE TITLE
first and after do not accept variable values for range limits

### ISSUE THREAD

**Issue by Shadow53** [spf13/hugo#3300]
I am attempting to write a taxonomy terms page that splits the full list of, say, tags into three groups so that the pieces of the list can be floated based on screen size.

The relevant code:
```
{{ $len := (.Data.Terms | len) }}
{{ $extra := mod $len 3 }}
{{ $count := div $len 3 }}

Length: {{ int $len }}
Count: {{ int $count }}
Extra: {{ int $extra }}

Count is {{ if lt $count 1 }}less{{ else }}greater{{ end }} than 1

<div class="taxonomy-list small-12 medium-6 large-4 columns">
 <ul>
   {{ range $key, $val := first $count .Data.Terms.Alphabetical }}
    <li>
      <a href="{{ "/tags/" | relLangURL }}{{ $val.Name | urlize }}">{{ $val.Name }}</a> ({{ $val.Count }})
    </li>
    {{ end }}
  </ul>
</div>

...
```
The resulting output on the page:
```
Length: 22 Count: 7 Extra: 1 Count is greater than 1 
```

And the error from `hugo`:
```
Error while rendering "page ": template: theme/_default/terms.html:22:31: executing "theme/_default/terms.html" at <first $count .Data.T...>: error calling first: can't return negative/empty count of items from sequence
```

I would expect the line `{{ range $key, $val := first $count .Data.Terms.Alphabetical }}` to successfully return the first `$count` (in this case, `7`) items from .Data.Terms.Alphabetical to `range`, rather than give the above error. I have also tried `(int $count)` (and `($count | int)` just in case), with the same error. From what I can tell of the source code, the error occurs because this line in [template_funcs.go](https://github.com/spf13/hugo/blob/260b55ea56ea8998431aca2b80d2b1e47c6a31c3/tpl/tplimpl/template_funcs.go) errors or returns 0 for another reason.

```
limitv, err := cast.ToIntE(limit)
```

This error also happens with `after`, I'm just using `first` for the example. I would assume it happens with `last`, but I haven't checked.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by Shadow53** [comment]
I'm not sure how this isn't either a bug or an enhancement... It's a deviation from the expected behavior of being able to provide a *dynamically determined* (variable) integer to a function *as well as* a hardcoded one. If that's intentional, then this post could be considered an "enhancement", but either way it makes more sense for me to list this on an issue tracker and not a discussion forum.

I'm also not sure what other details I could provide other than what I did, which includes the code I was using, other things I have tried, evidence that the number is not being passed correctly, and the error code saying that `7` is somehow `negative/empty`. What else should I provide?

**Comment by bep** [comment]
Here is how I see it:

1) We are short on staff on this project, and I had a look at your issue, and to best judgement, this is a question for the forum and not a Hugo bug.
2) If you still mean that `cast.ToIntE` returns a negative `int`  value for a non-negative integer input, you would do all a big favour and try to create a failing test case and posted it at `spf/cast` issue tracker.
