### ISSUE TITLE
tpl: "int" func should handle template.HTML input

### ISSUE THREAD

**Issue by jpap** [spf13/hugo#3308]
Constructing a string from a string array fails:
```
$array := "1,3"
$values = split $array ","
$str := delimit (last 1 $values)
$int := int $str
```

It however can be done using `printf` which indicates that the above may be a bug:
```
$array := "1,3"
$values = split $array ","
$str := delimit (last 1 $values)
$int := int (sprintf "%s" $str)
```

**Comment by moorereason** [comment]
I tagged this as upstream as I'm thinking that cast.ToIntE could detect a fmt.Stringer interface if not a basic type.  However, we may need to just put `template.HTML` handling into Hugo.

**Comment by bep** [comment]
@moorereason is this fixed?

**Comment by moorereason** [comment]
No, I'll send a PR to fix this.
