### ISSUE TITLE
lastmod in sitemap.xml get old date

### ISSUE THREAD

**Issue by wendellrios** [spf13/hugo#331]
Hi, it seems that sitemap.xml is getting an old date after hugo generation, like the sample below. 
----------------------------------------------------------------------------------------------
<url>
    <loc>http://localhost:1313/</loc>
    <lastmod>2008-01-01T00:00:00+00:00</lastmod>
    <priority>0</priority>
  </url>
----------------------------------------------------------------------------------------------

**Comment by bjornerik** [comment]
OK, now I have one site with wrong lastmod in sitemap.xml and some sites with correct date. I will try to figure out what differs here.

**Comment by bjornerik** [comment]
Found the reason in my case.

Looks like the parsing of `date` in front matter isn't very flexible.

`2014-1-31T14:18:44+01:00` => `0001-01-01 00:00:00 +0000 UTC`
 `2014-01-31T14:18:44+01:00` => `2014-01-31 14:18:44 +0100 CET`

**Comment by bjornerik** [comment]
Fixed in 837922d
