### ISSUE TITLE
hugo --help should include details for "no command"

### ISSUE THREAD

**Issue by paul-hammant** [spf13/hugo#3311]
"no command" means 'generate site to public/" but is not listed in the `Available Commands:` section.

**Comment by rdwatters** [comment]
https://hugodocs.info/getting-started/usage/#the-hugo-command

**Comment by bep** [comment]
It does:

"hugo is the main command, used to build your Hugo site."

The `Available Commands:` lists available subcommands. It could _maybe_ have been made clearer, but that is nit picking. This command has plenty of examples around.

(@rdwatters please don't post links to your personal Hugo docs site as references -- remember that these issues will be searched long after that site is long gone).

**Comment by rdwatters** [comment]
> remember that these issues will be searched long after that site is long gone

I would hope to set up redirects once we get everything moved over. Also just making note in the event  that someone submits a PR to change the content. But I understand :smile: Cheers. Wont happen again (or at least I won't just post the URL without anything else; I was being lazy.)

**Comment by paul-hammant** [comment]
Issue is valid, just mis-stated.  Corrected to "no sub command" from "no command"
