### ISSUE TITLE
Unable to locate template for custom shortcodes

### ISSUE THREAD

**Issue by keihayashi** [spf13/hugo#3340]
I made a simple portfolio using Hugo, one of the custom shortcode doesn't work with 0.20.

Here is my portfolio repository. https://github.com/keihayashi/kei_portfolio
It works with no problem when I use hugo 0.19, after upgrading to 0.20, I got an error below:

```
ERROR 2017/04/13 01:58:07 Unable to locate template for shortcode "socialLinks" in page "contact.md"
```

**Comment by bep** [comment]
This is fixed in https://github.com/spf13/hugo/issues/3333

Will release a new version later today.
