### ISSUE TITLE
Check and deprecate the disable404, disableSitemap etc. 

### ISSUE THREAD

**Issue by bep** [spf13/hugo#3345]

**Comment by digitalcraftsman** [comment]
Just to be sure: you're deprecating this config options because the same can be achieved `disableKinds` as follows:

    disableKinds = ["RSS", "sitemap", "robotsTXT", "404"]

**Comment by bep** [comment]
Yes, those double settings are (or will be) a pain to maintain. The code is shattered with double ifs and double tests etc.

**Comment by digitalcraftsman** [comment]
Thanks for the confirmation. And yes, the new approach is much cleaner.
