### ISSUE TITLE
Multilingual issue - Unable to access Params values

### ISSUE THREAD

**Issue by LeeU1911** [spf13/hugo#3346]
Hi all,

I'm working on a multilingual theme for Hugo and running into one issue. When my templates are built for the first time, I can see the Params values configuration by printing out the `.Site.Params` object, but I'm unable to use the value by reading variable e.g. `.Site.Params.footer.enable`.

Minimal code example is posted as gist [here](https://gist.github.com/LeeU1911/bc2a2464a15c817e9b0f0dd63ec8420c).

The strange thing is if I run `hugo server`, it'll not able to access the value above for first run, and then if I change my config.toml file by just entering a new line and save. The value is read and everything works correctly.

Please help if you have any idea.

Thanks,
Vu

**Comment by bep** [comment]
The time is limited, so if you want us to look into this/test this, you should provide a failing running project (i.e. not some fragmented gists).

**Comment by bep** [comment]
OK, I see you also posted this on the forum.

**Comment by LeeU1911** [comment]
Thank you @bep . Sorry for that. I was thinking your expert view may detect my silly error in configuration or so with minimal code real quick

Anyway, I found out the problem. I was stupidly thinking that when normally you configure something like 
```
[params.footer]
enable = true
```
and access it by `.Site.Params.footer.enable` then in multilingual case, you can just configure
```
[languages.en.params.footer]
enable = true
```
and access it the same way.

Apparently it's not working like that, now I have to configure it by (removing `params` key)
```
[languages.en.footer]
enable = true
```
in order to access it the same way. Otherwise, I have to access it by `.Site.Params.params.footer.enable` (notice the additional `params` key)

I'm not sure if this is a bug and it's supposed to work that way. 

Anyway, after scratching my head for a few days, I'm happy to be able to solve it now just by posting it on Github (how lucky!).

Thank you,
Vu

**Comment by LeeU1911** [comment]
@bep yeah, regarding the forum, I wasn't sure which community is more active so I tried my luck.

Thanks,
Vu
