### ISSUE TITLE
Zero-length HTML files created in public (regression from 0.19)

### ISSUE THREAD

**Issue by jgreely** [spf13/hugo#3355]
When I ported my large MovableType blog to Hugo, I handled the blogroll and microblogs as sections, suppressing the generation of single pages by creating zero-length files (`blogroll/single.html`, etc), and pulled in all the old comments by making them a section _comment that was visible only through the "comments" taxonomy, with zero-length `_comment/single.html` and `section/_comment.html` files.

In 0.19 (Mac), no files were created in `public` from these templates. In 0.20 - 0.20.2, I get 4,417 zero-length HTML files. I can write a cleanup script, but unless there's a cleaner way to suppress these pages in 0.20, I'd prefer the old behavior.

**Comment by thylong** [comment]
I face the same issue. I rolled back to 0.19 for now

**Comment by bep** [comment]
Please don't "me too" on issues.
