### ISSUE TITLE
Script Hugo release process

### ISSUE THREAD

**Issue by bep** [spf13/hugo#3358]
Based on https://github.com/goreleaser/goreleaser

**Comment by bep** [comment]
@moorereason @spf13 @digitalcraftsman 

Have a look at 

https://github.com/bep/hugo/releases/tag/v0.20.110

And esp. the file names.

There are some subtle differences to get it consistent, but the main ones are like before to keep old Wercker deploys working etc. 

* But I have changed all the Unix to tar.gz as archive format. 
* This is a change that may break something, but I'm not sure what the reasoning behind the old zip files for all but the Linux builds. I would think zip should be a more problematic format on non-Windows.
* I can change that back, maybe if you think of a good reason ...

**Comment by bep** [comment]
This is complete:

https://github.com/bep/hugo/releases/tag/v0.20.113

**Comment by moorereason** [comment]
I hadn't paid much attention to our old release filenames.  They're a mess!

Agree on the zip vs tar.gz change.

If we keep the "32bit" replacement, I prefer "32bit" to "32-bit."  Same for "64-bit."  The extra hyphen just adds more noise to a busy filename.

Personal preference, but I prefer all lowercase filenames.

Overall, looks much cleaner.  :+1:

**Comment by bep** [comment]
>If we keep the "32bit" replacement, I prefer "32bit" to "32-bit."

I'm not changing the Linux filename at all (it would break too many scripts, even some of mine).

**Comment by moorereason** [comment]
What do you mean?  Our existing releases use "32bit" not "32-bit".

**Comment by bep** [comment]
>What do you mean? Our existing releases use "32bit" not "32-bit".

Which is the reason I ask other people to look at it ... I stared at those filenames side-by side, and they looked the same to me ... Thanks, I will fix the bit.
