### ISSUE TITLE
GitInfo error after doing a git mv

### ISSUE THREAD

**Issue by jloh** [spf13/hugo#3375]
After enabling the git info feature everything worked fine until I did a `git mv` on a file. Ever since then hugo fails to render the template with this error:

```
ERROR 2017/04/22 16:38:41 Error while rendering "page": template: posts/single.html:11:207: executing "posts/single.html" at <.GitInfo.Hash>: can't evaluate field Hash in type *gitmap.GitInfo
```

Originally I thought it just didn't understand the `git mv` operation in the git log however adding another miscellaneous commit to the file after the move didn't fix it either.

Version/OS (OSX Sierra):

```
Hugo Static Site Generator v0.20.2 darwin/amd64 BuildDate: 2017-04-22T15:27:48+10:00
Darwin 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
```

**Comment by bep** [comment]
Two things:

1)  would suggest you wrap your `GitInfo` access in a `with` to prevent the panic; new files not yet committed will not have a git revision to use. See https://github.com/spf13/hugo/blob/master/docs/layouts/partials/footer.html#L3
2) I have tested this locally and it is the famous case of _it works fine for me_. But note that a git mv in itself is not enough, you need to add and commit the new file for Hugo to pick up on it.

Other than that, I have no clue.

**Comment by jloh** [comment]
I can't seem to repeat this anymore either. Sorry for the trouble!
