### ISSUE TITLE
`hugo serve` won't render fonts 

### ISSUE THREAD

**Issue by danielyang1009** [spf13/hugo#3377]
When I use `hugo serve -w`, it show different result from `hugo` which accessed locally. When I build my website, fonts are correctly rendered. But `hugo serve -w` won't render my fonts, it only show default fonts.

I'm using google fonts by 
`<link href="https://fonts.googleapis.com/css?family=Noto+Sans|Noto+Serif|Source+Code+Pro" rel="stylesheet">`

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by rdwatters** [comment]
Have you checked your browser console for errors? This isn't much to go off of and might

**Comment by bep** [comment]
@rdwatters please keep the questions on the forum.

**Comment by rdwatters** [comment]
We must have crossed paths. And that comment cut off at "might be better served on the forums"...
