### ISSUE TITLE
list template in section folder isn't used

### ISSUE THREAD

**Issue by levidrain** [spf13/hugo#3380]
In the content folder I have a "blog" folder with a few markdown files
In the layouts folder, I have a "blog" folder with both a single.html and list.html template.

The single.html template is being used to render the individual files as expected, but the list template is ignored and the one in _default is used instead.  According to the docs, I think this is supported, but I'm stumped as to why it's not working.

**Comment by rdwatters** [comment]
@levidrain Since this is more of a support question, it's better suited for the forums, please: https://discuss.gohugo.io
