### ISSUE TITLE
Custom Variables

### ISSUE THREAD

**Issue by Romansky1987** [spf13/hugo#3381]
Hello,

I am trying to add custom variables to my front matter in a certain directory. Right now I have the basic options like Title, Description.... That I am linking to in my HTML file with {{ .Title }}, 
{{ .Description }}.... I would like to have custom options so that i can have more customization with my layout while still using Markdown. If I simply use the {{ .Content }} code it limits everything to one background and one column. But if I have other variable options I can insert them with more flexibility. Any ideas?

**Comment by kevingimbel** [comment]
Hello there,
this seems more like a support question for the Hugo Forum (https://discuss.gohugo.io/). As for variables you can already assign custom variables (or "Parameters"), e.g. inside your Front-Matter, see http://gohugo.io/templates/variables/ - You can then access the custom variables/params inside your templates with `{{ .Params.myparam }}`.
