### ISSUE TITLE
Hugo binary no longer statically linked on Linux (starting 0.20.3)

### ISSUE THREAD

**Issue by munnerz** [spf13/hugo#3382]
Hi there

Since version 0.20.3, it appears the Hugo binary is no longer being statically linked.

This means when running Hugo within an alpine container, 'no such file or directory' is output (because the linked libraries are not present). I'm assuming this is to do with the transition to using goreleaser, as part of this issue: https://github.com/spf13/hugo/issues/3358

From a quick glance, it looks like goreleaser allows us to specify ld flags. etc for use when building, so this should be possible!

Thanks

**Comment by bep** [comment]
>From a quick glance, it looks like goreleaser allows us to specify ld flags. etc for use when building, so this should be possible!

It would be even better if you could provide me with the correct ld flags/or a reference.

**Comment by munnerz** [comment]
@bep I've put in a pull request with #3384!

**Comment by bep** [comment]
Thanks; I will check to see how Goxc handle this (which is what we replaced), to make sure I don't introduce even more mess.

**Comment by bep** [comment]
Note to self:

New vs old Linux:

```
ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), stripped
ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

**Comment by bep** [comment]
I have released a new version, but I had to reopen this issue. A build on Linux still shows up as  dynamically linked, so I built it on `macOS`, where everything is fine. We have to check into this some more.

**Comment by bep** [comment]
So this works by doing it directly:

```
go build -ldflags '-s -w -linkmode external -extldflags "-static"'
 file ./hugo
./hugo: ELF 64-bit LSB  executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.24, BuildID[sha1]=38440bf812b499ce299409c4bb9c2042ff24f20c, stripped
```

I assume Goreleaser is doing some funky stuff ...

**Comment by caarlos0** [comment]
> I assume Goreleaser is doing some funky stuff ...

my bad, docs were inducing to error. Sorry. Thanks @bep for for the PR :)

**Comment by dettmering** [comment]
@bep this now appears to happen with the extended version of hugo that includes SASS processing. 

I can't run hugo extended on alpine anymore. The non-extended version works perfectly, though.

**Comment by SR-G** [comment]
Same for me - this seems to be "by design choice" (as per said in other issues), but i would then need the list of expected dependencies (was not able to find that anywhere, neigher here or on the forum, if someone has the detailled informations related to this topic, thanks for providing them).

**Comment by dettmering** [comment]
I found a workaround by installing glibc: https://github.com/dettmering/hugo-build/blob/master/Dockerfile

Maybe this helps.
