### ISSUE TITLE
error: unable to locate config file

### ISSUE THREAD

**Issue by hieverest** [spf13/hugo#3383]
version: 0.20.3

after I created a new site, and when I try to create a new post by following the tutorial I got this error. But the `config.toml ` file is just under my site folder. 

Very new to hugo. At last version, I didn't encounter this problem but got stuck at deploying themes. It seems like more and more tricky... T T

**Comment by hieverest** [comment]
Oh stupid me! Found the answer on [https://discuss.gohugo.io/t/unable-to-locate-config-file/4765].

**Comment by vibhoraggarwal** [comment]
> version: 0.20.3
> 
> after I created a new site, and when I try to create a new post by following the tutorial I got this error. But the `config.toml ` file is just under my site folder.
> 
> Very new to hugo. At last version, I didn't encounter this problem but got stuck at deploying themes. It seems like more and more tricky... T T

Hi @qianch3n 
I recently rebooted my Ubuntu and was then reloading all the repositories; but could not run the website using the same command. I also receive the same error. Unfortunately, the link you mentioned [here](https://github.com/gohugoio/hugo/issues/3383#issuecomment-296684875) does not work. Would you like to mention how you proceeded to solve the issue?

**Comment by SeanTolstoyevski** [comment]
I'm surprised this is not included in the documentation. Why is that?

**Comment by moorereason** [comment]
https://discourse.gohugo.io/t/unable-to-locate-config-file/4765

Please take this discussion to the forums.
