### ISSUE TITLE
Check layout lookup for taxonomyTerm

### ISSUE THREAD

**Issue by bep** [spf13/hugo#3386]
The first one in this list looks odd:

```
WARN 2017/04/24 19:31:58 [en] Unable to locate layout for "taxonomyTerm": [taxonomy/.terms.html.html taxonomy/.terms.html _default/terms.html.html _default/terms.html indexes/indexes.html.html indexes/indexes.html theme/taxonomy/.terms.html.html theme/taxonomy/.terms.html theme/_default/terms.html.html theme/_default/terms.html theme/indexes/indexes.html.html theme/indexes/indexes.html]
```

**Comment by klara-kucerova** [comment]
Hi Bep, not sure if this would be any help to you:

I have installed v0.20.5 yesterday and started a new site (and new theme) to learn how to use Hugo. I got the same error as you (above) when running `hugo --verbose`.
Later I have added new posts to my site removed public/ directory and run `hugo --verbose` again. This would through slightly different error:

`Started building sites ...
INFO 2017/04/27 11:02:20 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
WARN 2017/04/27 11:02:20 [en] Unable to locate layout for "taxonomyTerm": [taxonomy/tag.terms.html.html taxonomy/tag.terms.html _default/terms.html.html _default/terms.html indexes/indexes.html.html indexes/indexes.html theme/taxonomy/tag.terms.html.html theme/taxonomy/tag.terms.html theme/_default/terms.html.html theme/_default/terms.html theme/indexes/indexes.html.html theme/indexes/indexes.html]
WARN 2017/04/27 11:02:20 [en] Unable to locate layout for "taxonomyTerm": [taxonomy/category.terms.html.html taxonomy/category.terms.html _default/terms.html.html _default/terms.html indexes/indexes.html.html indexes/indexes.html theme/taxonomy/category.terms.html.html theme/taxonomy/category.terms.html theme/_default/terms.html.html theme/_default/terms.html theme/indexes/indexes.html.html theme/indexes/indexes.html]
Built site for language en:
0 draft content
0 future content
0 expired content
2 regular pages created
8 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 5 ms`

and it never creates my posts .html files (as I believe it should). Instead it creates public/article/index.xml file with following content:

`<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Articles on Meanbee Site</title>
    <link>http://localhost:1313/article/</link>
    <description>Recent content in Articles on Meanbee Site</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Thu, 27 Apr 2017 11:02:13 +0100</lastBuildDate>

    <atom:link href="http://localhost:1313/article/index.xml" rel="self" type="application/rss+xml" />

    <item>
      <title>second</title>
      <link>http://localhost:1313/article/second/</link>
      <pubDate>Thu, 27 Apr 2017 11:02:13 +0100</pubDate>

      <guid>http://localhost:1313/article/second/</guid>
      <description></description>
    </item>

    <item>
      <title>first</title>
      <link>http://localhost:1313/article/first/</link>
      <pubDate>Thu, 27 Apr 2017 11:02:06 +0100</pubDate>

      <guid>http://localhost:1313/article/first/</guid>
      <description></description>
    </item>

  </channel>
</rss>`

I’m very new to Hugo, so not completely sure if this is correct behaviour or not, but I thought this could be related to your error message. I’m following this tutorial and it seems like it’s not generating the files correctly: https://gohugo.io/tutorials/creating-a-new-theme/

In case this is related to v0.20.5 version, would you know which older version I could use meanwhile before this gets resolved?

Any help is appreciated! thanks!

**Comment by bep** [comment]
I'm not sure where I picked up this, I guess it was one of the theme example sites. I guess this happens when people put empty values for the taxonomy terms definition, as a way to exclude those from build, and then this is normal behaviour. I cannot reproduce this in any normal setting.

**Comment by harri00413** [comment]
Is it already clear what causes this? I have the same thing. 
Cheers,
Frank

**Comment by vargalas** [comment]
I receive the same error with an old site created with hugo 0.15 or similar, using the current hugo version. Theme is ghostwriter.

**Comment by dldx** [comment]
I also have the same problem with a theme I ported (hpstr-hugo). Would appreciate it if someone could tell me how to fix this. I haven't been keeping up with Hugo development so I assume some recent changes to Hugo has caused this bug.

**Comment by cyc115** [comment]
any walk around for this ?

**Comment by jasonnerothin** [comment]
bumping into this myself.

i'm attempting to override a partial from the theme in my section's layout directoy, but that's just a guess...
