### ISSUE TITLE
 [hugo-0.18+] "Everything is a Page"

### ISSUE THREAD

**Issue by adrianovieira** [spf13/hugo#3387]
I've built a hotsite and I used to use *Hugo-0.16" to render it.

Now I'm trying to update to *Hugo-0.18+*, but I'm having some problem. I believe the troubles are related to what I understand of the "rule" *everything as a page*.

According to this rules of *Hugo-0.18+* it threat *everything as a page* (https://gohugo.io/content/using-index-md/) if we use ***_index.md***.

Then I created a sample test site to check, but it doesn't work (same behaviour of my hotsite).

```
├── archetypes
├── config.toml
├── content
│   ├── about
│   │   └── _index.md
│   └── _index.md
├── data
├── layouts
├── static
└── themes
    └── ...
```

What is expected?

The "home" and "about" pages render right.

-----

## My workaround: 

```
├── archetypes
├── config.toml
├── content
│   ├── about
│   │   ├── _index.md
│   │   └── index.md
│   ├── _index.md
│   └── index.md
├── data
├── layouts
├── static
└── themes
    ├── ...
```

I've created both files `index.md` and `_index.md`:

- *`_index.md`*

```
+++
date = "2017-04-23T12:21:47-03:00"
draft = false
title = "Home page"

+++

can be something else
```

- ***`index.md`***

```
+++
date = "2017-04-23T12:21:47-03:00"
draft = false
title = "Home page"

+++

# Your page with Real Content

Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. 

Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat.

*Make the Web Fun Again*

```

I hope you can point me some solution.

or Is this workaround the correct behaviour?

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by adrianovieira** [comment]
What other details do you need?

anyway, I just created a topic on discussion forum and this is the link to the question: https://discuss.gohugo.io/t/hugo-0-18-everything-is-a-page/6332
