### ISSUE TITLE
manually built v0.20.4 declares itself as v0.21-DEV

### ISSUE THREAD

**Issue by sigma** [spf13/hugo#3388]
I'm not sure I understand the git history leading to tag v0.20.4, but it seems to include the commit that bumped `helpers.CurrentHugoVersion` to 0.21-DEV
That is also reflected in the released source package for that version.

On the other hand, the binary artifacts I tried for that release declare a version v0.20.4, which puzzles me. Am I overlooking a subtlety of `goreleaser` ?
If so, how exactly are we supposed to build hugo so that `hugo version` displays the right number ?

Thanks

**Comment by bep** [comment]
>Am I overlooking a subtlety of goreleaser ?

No, you are overlooking some fault in ... me. I will look into this and get out a proper version in a little bit.

**Comment by tombennet** [comment]
@bep This issue seems to have recurred in 0.20.6 - running `hugo version` returns `Hugo 0.21-DEV`, as does the `.Hugo.Generator` variable. Unless I too have overlooked something... 
Thanks!

**Comment by bep** [comment]
@tombennet you are right, and I did not understand what happened the last time, but now I do. The tag got created by GitHub before the version numbers got updated; so while the binaries reported correct version, the tagged code was one version early. I have replaced the tag with the correct one, so now the source is also correct.
