### ISSUE TITLE
jekyll import: Extract post title from filename 

### ISSUE THREAD

**Issue by cboettig** [spf13/hugo#3390]
One of the great features of `hugo import jekyll` is that it extracts the post date from the filename if it is not already given in the post metadata (a convenient & commonly used Jekyll feature, see #285), and adds it in as explicit metadata in the post header so  Hugo can see the date.  Likewise, Jekyll defaults to use a title for a post also from the filename (e.g. `2017-04-21-this-is-the-title.md` becomes `title: "This is the title"` in a yaml header).  It would thus seem that `hugo import jekyll` should likewise be parsing the title string from the filename if it is not given in the metadata, as it already does for the date.  This would streamline importing from Jekyll.

Perhaps it should be a separate issue, but given Hugo's nicely content-driven layout, this behavior of using the post filename to indicate the title would be a nice option to add (configurable in `config.toml`, analogous to what 902ac963733289c025249b35ae9ab1616413788f already adds for dates with the `useFilenameDateAsFallback` option.

**Comment by vanadium23** [comment]
I was checking code to implement this feature, but last master already implements it:
https://github.com/spf13/hugo/blob/master/commands/import_jekyll.go#L368
https://github.com/spf13/hugo/blob/master/commands/import_jekyll_test.go#L29

Guess this issue can be closed.

**Comment by cboettig** [comment]
@vanadium23 hmm, using the v24.1 release to import from jekyll I'm still not getting post titles imported and added to the post yaml headers... importing *dates* from the file name works fine.
