### ISSUE TITLE
wrong count of monthly posts

### ISSUE THREAD

**Issue by yyBeta** [spf13/hugo#3394]
Thanks for this awesome generator, I'm new to it.

Now I'm debugging a theme "[hugo-pacman-theme](https://themes.gohugo.io/hugo-pacman-theme/)" which is not compatible greatly on new version of hugo.
I submited an issue in the repo of this theme but it seems that it is not maintained by the author for a long time, so I try to fix it by myself. Many of these compatible-problems had been fixed such as `isset` problem and "main" should be lowercase in`Site.Menus.Main` except one below.

This is the [source code](https://github.com/coderzh/hugo-pacman-theme/blob/00602abdce6355a822720fefeb3e85406b7d4177/layouts/partials/widgets/archive.html) of the sidebar which shows the monthly counts of posts
```
{{ if not (eq (len .Site.Pages) 0) }}
  <div class="archiveslist">
    <p class="asidetitle">{{ .Site.Params.Strings.Archive }}</p>
    <ul class="archive-list">
      {{ range $value := (where .Site.Pages "Type" "post").GroupByDate .Site.Params.MonthFormat }}
      {{ $url := (index $value.Pages 0).Date.Format "2006-01" | urlize }}
      <li class="archive-list-item">
        <a class="archive-list-link" href="{{ $.Site.BaseURL }}post/#{{ $url }}">{{ .Key }}</a><span class="archive-list-count">{{ len $value.Pages }}</span>
      </li>
      {{ end }}
    </ul>

  </div>
{{ end }}
```
it works well under hugo v0.17 ([demo in author's repo](http://coderzh.github.io/hugo-pacman-theme/)) but when I use v0.20 ([demo in hugo theme page](https://themes.gohugo.io/theme/hugo-pacman-theme/)), the count of first monthly posts(**only first month**) will always be 1 more.("about" page doesn't matter, because it's not in posts and the problem still exists even this page deleted)

Is this a bug of `{{ len $value.Pages }}` or just a compatible problem? How can I fix it?

**Comment by rdwatters** [comment]
@yyBeta this is a question better suited for the forums at https://discuss.gohugo.io I would post this question there and you'll get much better feedback. Thanks for your support of Hugo!
