### ISSUE TITLE
Add an HTTP Accept header when downloading JSON

### ISSUE THREAD

**Issue by lpancescu** [spf13/hugo#3395]
Some sites, like atlas.hashicorp.com, decide whether to serve HTML or JSON based on the HTTP Accept header (Atlas defaults to HTML if no header is present, although it serves curl JSON data by default - it probably detects the user agent, since doing the same request from Python's httplib or a browser results in an HTML response).

This makes it impossible to use `getJSON` from a template. Could you please insert the HTTP header `Accept: application/json` when downloading JSON data, or at least allow template creators to add their own HTTP headers?

**Comment by bep** [comment]
We should just atd the `Accept: application/json` header for `getJSON`.

**Comment by moorereason** [comment]
@bep, `getJSON` and `getCSV` don't currently return an error.  What do you think about changing that?

```go
// from
func (t *templateFuncster) getJSON(urlParts ...string) interface{} {}
func (t *templateFuncster) getCSV(sep string, urlParts ...string) [][]string {}

// to
func (t *templateFuncster) getJSON(urlParts ...string) (interface{}, error) {}
func (t *templateFuncster) getCSV(sep string, urlParts ...string) ([][]string, error) {}
```
