### ISSUE TITLE
index.md is generated in subfolder /index/index.html

### ISSUE THREAD

**Issue by marcojakob** [spf13/hugo#3396]
I've upgraded to Hugo v0.20.5 and the generated file location of the `index.md` files changed. I don't think this was intended. Here is what happened:

I use following content structure to keep content and images together:

```
├── content
│   └── blog
│       ├── my-blog-post-1
│       │   └── index.md
│       │   └── image-for-post-1.jpg
```

This generates the following structure:

### Hugo before v0.20 (expected behavior)

This is how it should be.

```
├── public
│   └── blog
│       ├── my-blog-post-1
│       │   └── index.html
│       │   └── image-for-post-1.jpg
```

### Hugo v0.20 (wrong behavior)

```
├── public
│   └── blog
│       ├── my-blog-post-1
│       │   └── image-for-post-1.jpg
│       │   └── index
│       │       └── index.html
```
I think it is not intended behavior to have an additional index subfolder (`/index/index.html`).

There is a workaround if I set `slug = '/'` in the front matter but I would rather not do that.

**Comment by bep** [comment]
Thanks for getting in touch, but it feels like this is a question  that would be better suited to the [Hugo Discussion Forum](http://discuss.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug. You may also find the answers you search for in [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by marcojakob** [comment]
See discussion here: https://discuss.gohugo.io/t/index-md-is-generated-in-subfolder-index-index-html-hugo-0-20/6338

**Comment by bep** [comment]
I have slept on this, and we can fix easily this by saying that:

* If the file base name resolves to the same as the base name for the output type (i.e. "index" for HTML), the user probably meant it, so we treat that as an `uglyURL`, i.e. `my-blog-post-1.md`=> `/my-blog-post-1/index.html`
* The main use case for this is to group blog post and images together. 
* Note that for the top level folder there will be a potential name conflict with a `section` `index.html` (if enabled)
* This issue will not be relevant for subfolders in sections
* Hugo will soon add support for nested sections, but we will have to find a way to separate them from the rest (`/content/_mysubsection` maybe).

**Comment by marcojakob** [comment]
Thank you very much @bep. That is a good fix :+1:. When I get more fluent in Go programming, I will try contributing such things as pull requests myself.
