### ISSUE TITLE
Cannot .Render a section page from the homepage layout.

### ISSUE THREAD

**Issue by aroig** [spf13/hugo#3398]
I would like to render a copy of a section page as the homepage. To that end have a `layout/index.html` that looks like this:

    {{- with .Site.GetPage "section" "about" }}
    {{- .Render "single" }}
    {{- end }}

Where "about" is a section page with content from an `_index.md` file.

The thing worked for a while, but after a recent update to hugo 0.20 it produces a blank page.

**Comment by rdwatters** [comment]
@aroig Can you do me a favor and please open a thread on this on the forums? Strikes me as more of a support-related conversation than a bug (at least at this moment). You'll have much better luck there. If we can't figure it out, and it is indeed a bug, we can reconvene here. Thanks for your support of Hug :smile: 

https://discuss.gohugo.io

**Comment by bep** [comment]
This is duplicate of #3245

I'm not sure how well this worked in earlier Hugo; you may wait and see if we implement this for Hugo 0.21 -- but I would recommend that you refactor your templates (a section page is not a single page).

**Comment by rdwatters** [comment]
Huh. My comment didn't show up @aroig I apologize. I'm having interstitial connectivity here at work. (This has also never happened before.) Didn't mean to close without commenting, but if you want some support on this, please visit the forums at https://discuss.gohugo.io .

**Comment by aroig** [comment]
@bep Thanks, I missed that one.

@rdwatters Ok, If I have anything to ask I'll go to the forums, but I'm pretty sure that this is either a regression or a feature request, depending on how you look at it.

I don't think there is currently a way in hugo to have a layout template to copy the contents of an other page, without http redirects, and without copying the contents of the template.

By the way, being able to use block templates for the homepage would help.

**Comment by bep** [comment]
1) You could use a partial which feels much more natural to me.
2) Block templates for home page works fine.

But now we are borderline what is best solved on the discussion forum: https://discuss.gohugo.io/

@rdwatters I deleted your comment as I was typing my reply ...

**Comment by rdwatters** [comment]
By accident or was there something wrong with my reply? :smile:

**Comment by bep** [comment]
I marked it as a duplicate, hence it is a "valid issue"; I only send people to the discussion site for issue that can not be resolved here (i.e. questions).

**Comment by rdwatters** [comment]
Got it.

**Comment by aroig** [comment]
> 1. You could use a partial which feels much more natural to me.

Yes, that is what I'll do. I preferred a full {{ .Render }} or block template because even with partials there is a small amount of duplication. But I guess can live with that.

> 2. Block templates for home page works fine.

Hmm... I can't make them work. They render empty for the home page.

Thanks.

**Comment by aroig** [comment]
> Hmm... I can't make them work. They render empty for the home page.

Please, disregard that. They do work indeed. I must have been doing something wrong on the earlier tests. I'm sorry.
