### ISSUE TITLE
www.gohugo.io uses an invalid security certificate

### ISSUE THREAD

**Issue by Lvl4Sword** [spf13/hugo#3409]
On Firefox I get:

> The certificate is only valid for the following names: *.netlify.com, netlify.com
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

:face_with_head_bandage:

**Comment by bep** [comment]
Yes, the gohugo.io is correctly configured (see below), www. gohugio.no not so much:

![image](https://cloud.githubusercontent.com/assets/394382/25550313/6c6b6710-2c78-11e7-84c3-c667e4b08bd4.png)

Thanks for letting us know.

/cc @spf13

**Comment by bep** [comment]
I deleted and re-added the www alias in Netlify, and now it seems to behave as expected:

https://www.gohugo.io
