### ISSUE TITLE
Re-tag of v0.20.6

### ISSUE THREAD

**Issue by woodruffw** [spf13/hugo#3428]
Could somebody on the hugo team confirm that `v0.20.6` was re-tagged on GitHub?

Homebrew checks the sha256 sum of the tarballs we fetch to ensure their integrity, and we noticed this change (https://github.com/Homebrew/homebrew-core/issues/13161):

```
857655b69fb3e7f174011fd6774501194f1241bbb833256fd63b585b6d7a3cc0
```
to:

```
692e08b009430d27064821d498f1454152cbfd5f26d019c29002e6fbff8fc387
```

As a friendly reminder, if this was indeed a re-tag: re-tagging breaks downstreams like ours, and is a very destructive way to "fix" a bad release. If you absolutely **need** to "undo" a tag, deleting and pushing a new *unique* one results in a much more obvious failure on our end.

**Comment by bep** [comment]
Yes.

**Comment by bep** [comment]
Use https://github.com/spf13/hugo/releases/tag/v0.20.7
