### ISSUE TITLE
Conditional Menus

### ISSUE THREAD

**Issue by ruaridhw** [spf13/hugo#3429]
Question regarding having a different menu for each top-level section of a site.

My template currently looks like
```
<ul class="site-menu-items">
  {{ range .Site.Menus.main }}
    {{ template "menu-node" . }}
  {{end}}
</ul>
```

Essentially I would like to dynamically set `.Site.Menus.menu1`, `.Site.Menus.menu2` etc. based on whether a page is a child of domain.com/menu1 or domain.com/menu2

I've tried playing around with `IsMenuCurrent` and `HasMenuCurrent` but get getting `wrong type for value; expected MenuEntry; got PageOutput`

Any help would be much appreciated!

**Comment by kevingimbel** [comment]
Hello, please search for or open a thread on the Discussion forums at https://discuss.gohugo.io/ - GitHub Issues are only used and intended for bug reports. 

You may also find a solution in the hugo docs, especially the menu section at https://gohugo.io/extras/menus/
