### ISSUE TITLE
Theme standards and general user experience

### ISSUE THREAD

**Issue by lebarde** [spf13/hugo#3433]
Hello,

@bep spoke of [standardizing themes](https://github.com/spf13/hugo/issues/2639#issuecomment-273824050). I think this is a great idea and a must-have, but I have not seen a general discussion over that.

So what is to do?

- Build a `hugo get` command to get a theme?
- Wouldn't it be nice to have a general `hugo get` command with the following sub-commands:
```
hugo get theme github.com/the-theme-url
hugo get widget github.com/the-widget-url
hugo get what else?
```
or even better:
```
hugo get theme the-theme's-unique-identifyier # (e.g. material-docs)
hugo get widget the-widget's-unique-identifyier
hugo get what else?
```
which would be so nice. We also would need `hugo update` to update themes and widgets in this case.

- Would we need to centralize themes and widgets? How to do it? Looking at the [hugoThemes](https://github.com/spf13/hugoThemes) repository, I think themes are already centralized and that it is ready to use with a `hugo get theme` command, which needs to be written.
- Now, what would be the standards for a theme? I assume we don't need more than the following files:
```
themes/
└── mytheme
    ├── config.toml
    └── index.html
```
And inside the `config.toml` (or `config.yaml`), the assertion to extend a theme would be:
```
extends: someother-theme
```
- I often saw that I could not switch a theme without heavily modifying the main site's config file. So, should we specify and recommend standard config vars (especially, `params`) to ensure that a same site would work with all themes that follow those guidelines (to draw the parallel, I would like to recommend some specific widget area names for the same reasons)?

### Sum up

In my opinion, the general goal we have to aim is to enable non-developers (or not-so power users) to use Hugo and get personnalized, pretty websites. This goes by:

1) Switching themes should not be painful (user has to experiment several themes if he/she cannot develop his/her own). This would be enabled by standard config recommendations for theme developers.
2) Modifying a theme should be easy. One modification, in the case of theme inheritance, would need only to create one directory, one config file with one line (`extends: …`), and one file that replaces that of the parent theme (He/she copies the original file in the child theme and modifies it). This is easy enough for not-so power users (but not true beginners, but diving into themes cannot be *that* accessible in my opinion).
3) Adding information aside of the main content should be easy. This is where widgets come into play. Widget area names should be normalized, such as that another theme would probably use that same name for the same position (e.g. sidebars, headers, footers).

And you? What do you think we need to help make the Hugo experience even happier?

**Comment by bep** [comment]
Although this is a good idea and something we will do eventually, your proposal is filled with questions (this issue tracker is (mostly) for actionable/concrete issues) better suited on a discussion forum, so I suggest you copy and paste this into a thread there.

**Comment by lebarde** [comment]
OK, no problem.
