### ISSUE TITLE
Lookup order: considering layouts/themes/mytheme

### ISSUE THREAD

**Issue by lebarde** [spf13/hugo#3438]
Hello,

As we spoke of theme inheritance, one intermediate solution might be to add `layouts/themes/mytheme/` in the lookup order between the templates located in `layouts/` and in `themes/mytheme/layouts/`.

The advantage is that we can fine tune one specific theme without impacting others. I am still considering to improve the experience at switching themes.

Do you think this behaviour should be changed in Hugo?

**Comment by bep** [comment]
>Do you think this behaviour should be changed in Hugo?

No, this is way too much work for a temporary hack.
