### ISSUE TITLE
Partials Not Working For Output Formats

### ISSUE THREAD

**Issue by felipetoffolo1** [spf13/hugo#3441]
Hi, i created a output format named "instant" and 2 partials

test.html.html and test.instant.html

It always use test.html.html

I tried:

test.html + test.instant.html
test + test.instant

They did not work too

Thanks

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by felipetoffolo1** [comment]
I think it is a bug. But i will check there first.
Thanks
