### ISSUE TITLE
hugo default RSS injects generator tag with disableHugoGeneratorInject

### ISSUE THREAD

**Issue by carandraug** [spf13/hugo#3453]
The default RSS inserts the tag

    <generator>Hugo -- gohugo.io</generator>

even when the configuration sets `disableHugoGeneratorInject`.

I tried to make it conditional on the default file but couldn't figure out how to check the value of `disableHugoGeneratorInject` in a template.

**Comment by bep** [comment]
`disableHugoGeneratorInject` is meant for the generator meta tag in HTML files. We don't inject anything in RSS files -- we have a built-in template that _creates_ the XML, including that generator tag. If you don't want it, please provide your own RSS template. For further questions, please use http://discuss.gohugo.io/. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by carandraug** [comment]
> disableHugoGeneratorInject is meant for the generator meta tag in HTML files. We don't inject anything in RSS files -- we have a built-in template that creates the XML, including that generator tag.

It can be spun whatever way you want. I would spun it in that the reason to set `disableHugoGeneratorInject` is to not have generator tags on pages, whether they are "injected" or default on template.

> If you don't want it, please provide your own RSS template.

I already do. I just noticed this surprising behaviour and thought of trying to fix it.

**Comment by JayAndCatchFire** [comment]
I actually concur with @carandraug that `disableHugoGeneratorInject` should apply to the RSS template as well.  I was also surprised to find that `disableHugoGeneratorInject` didn't also apply to RSS.

Should I open a feature request?  Could this ticket be reopened as made into a feature request?
