### ISSUE TITLE
Hugo docs: Next and Prev navigation bars' height

### ISSUE THREAD

**Issue by chankeypathak** [spf13/hugo#3458]
Example: https://gohugo.io/overview/introduction/

If you scroll till the end of the page, you'll not see the previous and next navigation bars. This is because of `    min-height: 1200px;`. This should be responsive.

**Comment by digitalcraftsman** [comment]
Hello @chankeypathak,

thanks for opening this issue. But it's unlikely that it will be fixed in the current design. Currently, we're working on a redesign of all websites that we hopefully ship soon to the public. The new design doesn't contain such large prev/next buttons anymore.

**Comment by chankeypathak** [comment]
Oh I see.
