### ISSUE TITLE
.IsTranslated issue with "index.md"

### ISSUE THREAD

**Issue by rosell-dk** [spf13/hugo#3470]
It seems that the page variable .IsTranslated is true for a page, even when there is no translation of the page. In the .Translations array, there is a link to the frontpage of the language, so it seems Hugo falls back to homepage when there is no translation of the actual page. It would be great to have an option to disable this behaviour.

Is it currently possible to detect whether a translation exists in a given language?

**Comment by rosell-dk** [comment]
The context is that I am trying to achieve a language selector, where all languages always appear, and they are listed in same order regardless of current language. When a translation is not available, the text should be striked through.
I'm at this stage:

```
{{ if .IsTranslated }}
<translations>
  {{ if eq .Lang "dk" }}
  <translation class="selected"><a href="{{ .Permalink }}">dansk</a></translation>
    {{ range .Translations }}
      <translation><a href="{{ .Permalink }}">english</a></translation>
    {{ end }}
  {{ end }}
  {{ if eq .Lang "en" }}
    {{ range .Translations }}
      {{js .}}
      <translation><a href="{{ .Permalink }}">dansk</a></translation>
    {{ end }}
  <translation class="selected"><a href="{{ .Permalink }}">english</a></translation>
  {{ end }}
</translations>
{{ end }}

```

**Comment by bep** [comment]
>It seems that the page variable .IsTranslated is true for a page, even when there is no translation of the page.

No, I'm fairly confident that is not true. Have you go got a concrete example? I.e. could you point me to your Git repository or something?

Worth noting here that the home page will always have a translation in a multilingual setup, even if it isn't really translated, but that is by design, and I'm not sure we're going to change that.

**Comment by rosell-dk** [comment]
Yes sure:
https://github.com/rosell-dk/bitwise-it.dk

**Comment by rosell-dk** [comment]
In my website on github, I for example have a page "expertice/index.md", which have no translation (there is no file named "expertice/index.dk.md"). But when i go to the URL, "/expertice", I see the translation links, even though they are set to only display when .IsTranslated is true.

The relevant code is located in "themes/bitwise/layouts/_default/single.html" (in the last lines of that file). 

```
{{ if .IsTranslated }}
<translations>
...
</translations>
{{ end }}

```

**Comment by bep** [comment]
I'm not sure what confuses Hugo in your case, but this is probably related to the "index.md" issue a while ago, where people shouted enough to get me to apply a patch. 

You have a very unstandard Hugo setup. Your `excpertice/index.md`  should really be `excpertice/index.md`, but then you would need some other layout setup.

I will keep this open, but not expect a fix any time soon.

**Comment by rdwatters** [comment]
> Your `excpertice/index.md` should really be `excpertice/index.md`, but then you would need some other layout setup.

Should be `excpertice/_index.md`, no? 

@rosell-dk, [see here for the layout](https://hugodocs.info/templates/section-templates/#adding-content-and-front-matter-to-section-templates) @bep references, and please feel free to "@" me directly (rdwatters) on the [Hugo Forums](https://discuss.gohugo.io) if you have any questions about the layout. (But please keep all support questions on the forum and not in this thread). Cheers!

**Comment by rosell-dk** [comment]
After renaming my index-files to "_index.md", .IsTranslated works as expected. So the bug apparently only occurs in the unusual setup. With this settled, I'm not sure its a bug at all, but I leave you guys to be the judge of that

@rdwatters, Thank you for the offer  :+1:

**Comment by bep** [comment]
This duplicates #2699

**Comment by nop33** [comment]
The solution of prefixing the `index.md` file with an `_` is not working for me.

My project has the following content structure:
```
project/
└── content/
    ├── legal/
    │   ├── _index.fr.md
    │   └── _index.md
    └── _index.md
```

And these are my language settings in the `.config.yml`:
``` yaml
languageCode: "en-us"
defaultContentLanguage: "en"
languages:
  en:
    languageName: "English"
    weight: 1
  fr:
    languageName: "Français"
    weight: 2
```

Now, when I check for `{{ .IsTranslated }}` in the template where the home page is rendered (`content/_index.md`), it is set to `true`, even though a `content/_index.fr.md` file doesn't exist.

Since a translation of the `content/_index.md` has not been defined, why is Hugo creating an empty page for the French translation, in my particular case, the French home page?

```
Hugo Static Site Generator v0.42.1 darwin/amd64 BuildDate: 2018-06-13T10:16:36Z
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.10.1"
```

**Comment by rdwatters** [comment]
@nop33 . Probably best to put your comment on the forums at https://discourse.gohugo.io, especially since this is a closed issue. You'll get a much faster and more comprehensive response over there! :smile:

**Comment by nop33** [comment]
Done that already, I just thought dropping a line here would attract more attention ;) Thanks!
https://discourse.gohugo.io/t/how-to-translate-only-a-subset-of-the-pages/14083

**Comment by nop33** [comment]
For what it's worth, I think we should re-open this ticket. I created a minimal Hugo project that reproduces the problem: https://github.com/nop33/hugo-minimal-setup

**Comment by nop33** [comment]
Or should I create a new issue for it?
