### ISSUE TITLE
Make possible to switch to using Kramdown or other processors

### ISSUE THREAD

**Issue by arikroc** [spf13/hugo#3494]
Purpose:

I'd like to have target=_blank for all external links.

It seems like an easy solution for this would be if it was using Kramdown: http://stackoverflow.com/a/4705645/397649

Is there a simple way to use Kramdown, or some other easy solution for target=_blank on all external links automatically (without going and manually editing hundreds of links to be html links instead of markdown links)?

**Comment by rdwatters** [comment]
@arikroc Can you please go to the forums at https://discuss.gohugo.io for all support-related questions? I think you will easily find the answer to your questions there....

As an aside, BlackFriday, Hugo's parser, is pretty badass, IMHO...and it's written in Golang...like Hugo 😉
