### ISSUE TITLE
why does gohugo.io/overview/installing differ from the project readme

### ISSUE THREAD

**Issue by gideondsouza** [spf13/hugo#3495]
So on this page : gohugo.io/overview/installing it says 

> Therefore, a simple go get is not supported since go get is not vendor-aware. You must use govendor to fetch Hugo’s dependencies.

However, doing the following did not work. govendor installed fine but just died off silently when I did `govendor get ..`

OTOH following worked perfectly fine on my system which is what the [Readme.md](https://github.com/spf13/hugo/blob/master/README.md#build-and-install-the-binaries-from-source-advanced-install) on the project says : 
`go get -v github.com/spf13/hugo`

So what gives? Is the documentation wrong? hugo now supports `go get` ?

My system is Fedora 25 I have go1.8

I this is a problem with the docs on the website I'd be very happy to make a PR.

Thanks

**Comment by bogem** [comment]
Please use http://discuss.gohugo.io/ for questions.

**Comment by gideondsouza** [comment]
Alright posted this on the discourse forum.
