### ISSUE TITLE
Feature request: JSON Feed

### ISSUE THREAD

**Issue by pjctech** [spf13/hugo#3517]
It would be nice to have [JSON Feed](https://jsonfeed.org) implemented in Hugo.

> The JSON Feed format is a pragmatic syndication format, like RSS and Atom, but with one big difference: it’s JSON instead of XML.
> 
> For most developers, JSON is far easier to read and write than XML. Developers may groan at picking up an XML parser, but decoding JSON is often just a single line of code.
> 
> Our hope is that, because of the lightness of JSON and simplicity of the JSON Feed format, developers will be more attracted to developing for the open web.

**Comment by pjctech** [comment]
Oops, its a duplicate of #3487 
Please close!

**Comment by jhabdas** [comment]
@pjctech why would this be nice, exactly?
