### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by chankeypathak** [spf13/hugo#3522]
I'm getting below errors in chrome developer tools.

```
Failed to load resource: the server responded with a status of 403 (Forbidden) api.github.com/repos/spf13/hug
Failed to load resource: the server responded with a status of 403 (Forbidden) api.github.com/users/spf13
Failed to load resource: the server responded with a status of 403 (Forbidden) api.github.com/users/bep
```

On clicking the above links I see below message:

```
{
  "message": "API rate limit exceeded for 125.16.91.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

Impact: Due to the above the fork and star counts are not appearing in header.

**Comment by bep** [comment]
I guess this happens when you don't have any active GitHub session, which I guess we cannot do anything about.

**Comment by osterman** [comment]
I'm able to work around this using the [github basic auth](https://developer.github.com/v3/auth/#via-oauth-and-personal-access-tokens), but the downside is hugo does not obfuscate errors.

```
ERROR 2020/01/14 00:45:34 Failed to get json resource https://foobar:test@api.github.com/repos/xxxxx/load-testing/contents/init.sh?ref=master with error message Failed to retrieve remote file: Unauthorized
```

Hugo should mask `foobar:test` with `********` so it's more suitable for CI/CD environments.

@bep any thoughts about this?
