### ISSUE TITLE
Hugo doesn't support Markdown tables

### ISSUE THREAD

**Issue by graemeg** [spf13/hugo#3525]
I pasted the [RippleDoc Quick Markdown Example](http://www.unexpected-vortices.com/sw/rippledoc/quick-markdown-example.html) source from this page:

  [http://www.unexpected-vortices.com/sw/rippledoc/quick-markdown-example.html](http://www.unexpected-vortices.com/sw/rippledoc/quick-markdown-example.html)

into a new Hugo post. I tried the "hugoscrolls" and "hugo-uno" themes, and in both cases the tables did not render at all.

I'm using the latest released Hugo v0.21 under FreeBSD 64-bit.

**Comment by digitalcraftsman** [comment]
Hugo uses [blackfriday](https://github.com/russross/blackfriday#extensions) to render the Markdown. As you can see tables are supported. The difference to your linked example is that columns have to be separated by using the `|` symbol.

But refer for such questions to the [Hugo forum](https://discuss.gohugo.io/); GitHub is used for concrete issues and requests/enhancements only.

**Comment by graemeg** [comment]
Apologies, and thank you for the help.
