### ISSUE TITLE
Unexpected behavior when running 'hugo' to build site

### ISSUE THREAD

**Issue by arikroc** [spf13/hugo#3537]
I renamed a URL structure, and then ran hugo and deployed my site.

I was confused to discover that an identical page was accessible at the old url.

I realized that running 'hugo' doesn't clear the /public directory - it just overwrites old pages. So the old page was still there untouched.

I'd classify this as a bug, or if not a bug at least unexpected behavior. Based on the behavior above I presume the same thing happens if someone deletes a page - it'll remain in their public directory unless they rm -r public/, which I don't imagine is what people would expect.

**Comment by moorereason** [comment]
This is by design.  Hugo is used in many different contexts and workflows.  We don't assume that Hugo is in complete control of everything in the output path.  As deleting content is risky business, we've opted not to delve into that at this point.

**Comment by arikroc** [comment]
Ok. Could be nice to have a "you've deleted/renamed content, if you don't want this content included, delete your public directory and run 'hugo' again." I expect that I'll forget every time I do this to delete the hugo folder, so I'd love to have a reminder.

**Comment by lebarde** [comment]
And what about having a `--delete` option to tell to drop the whole `public/` directory?

**Comment by bogem** [comment]
What's the problem to execute `rm -rf public && hugo`?

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting.
