### ISSUE TITLE
ERROR port 1313 already in use attempting to use an available port...??

### ISSUE THREAD

**Issue by sreebash** [spf13/hugo#3538]
ERROR: 2017/05/30 00:26:34 server.go:121: port 1313 already in use, attempting to use an available port

How to solve this issue 
Thanks in advanced!
:)

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
