### ISSUE TITLE
broken link in documentation - categories

### ISSUE THREAD

**Issue by dkebler** [spf13/hugo#354]
the url http://hugo.spf13.com/indexes/category  
has no content.  

linked from http://hugo.spf13.com/overview/introduction

thus no documentation for this bullet
"Support for categories and tags"

**Comment by bjornerik** [comment]
@anthonyfok could you check if this still is a doc issue? This thread is confuging...

**Comment by anthonyfok** [comment]
Hi @bjornerik,

Yes, will do, thanks for the note!

**Comment by anthonyfok** [comment]
Here is the whole history related to this issue for those who are as curious as I was:

1. (2014-05-15) b198cb2: docs/content/indexes/category.md → docs/content/taxonomies/category.md
2. (2014-05-27) a87f171: docs/content/taxonomies/category.md removed (Updating / Rewriting / Adding all of the documentation in preparation for the next release, i.e. v0.11), but the link in /overview/introduction.md was not updated.
3. (2014-07-04) @dkebler noticed the broken link, and filed this issue report #354.
4. (2014-08-09) @dkebler created Pull Request #392 to fix the broken link.
5. (2014-08-09) cbb2979: @spf13 merged (cherry-picked) the pull request into `master`.

Thank you @dkebler for fixing this broken link in the documentation!

Fixed, closing this issue.  :-)
