### ISSUE TITLE
disableKinds= ["sitemap"] does not seem to work

### ISSUE THREAD

**Issue by rosell-dk** [spf13/hugo#3544]
I put this line in config.toml:
```disableKinds= ["sitemap"]```

But hugo still generates sitemap.xml

However, ```disableSitemap = true``` does stop Hugo from generating sitemap.xml
It however issues the following warning:

> WARNING: site config's disableSitemap is deprecated and will be removed in a future release. Use disableKinds= ["sitemap"].

**Comment by bep** [comment]
You are right, my mistake. Please use disableSitemap for now and I will fix this.
