### ISSUE TITLE
Sections being listed on `$.Site.Pages`

### ISSUE THREAD

**Issue by robsonsobral** [spf13/hugo#3547]
Hi!

I just found an strange issue.

```
        {{ range where $.Site.Pages ".Type" "faq" }}
          <details>
            <summary>{{ .Title | safeHTML | markdownify }}</summary>
            {{ .Content }}
          </details>
        {{ end }}
```

At the end of previous loop, a section `.Type` appears.

I'm running `Hugo Static Site Generator v0.21 darwin/amd64 BuildDate: 2017-05-23T17:11:54-03:00`.

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by robsonsobral** [comment]
I reported the bug here, because the guidelines say that. If you prefer us to do it on forum, please update the guidelines.
