### ISSUE TITLE
Exclude 404 page from sitemap.xml by default

### ISSUE THREAD

**Issue by XhmikosR** [spf13/hugo#3563]
Including the 404 page in sitemap.xml gives no value at all so it should be excluded by default.

/CC @moorereason

**Comment by XhmikosR** [comment]
@bep: I still see my 404.html included in sitemap.xml.

**Comment by bep** [comment]
@XhmikosR then you must have some kind of custom 404 page, which I guess is possible, but not covered by this issue.  Try http://discuss.gohugo.io/ for further questions/troubleshooting.

**Comment by XhmikosR** [comment]
You are correct, I have the file lingering and that's why it happened.
