### ISSUE TITLE
Latest fsnotify API

### ISSUE THREAD

**Issue by elumalai** [spf13/hugo#357]
For more details

https://groups.google.com/forum/#!msg/golang-nuts/G5VgniBzSSE/VlwFwep_juUJ

**Comment by anthonyfok** [comment]
Hi @nathany,

Thank you for standardizing the fsnotify API to make it better for the future.

When you have time, could you please take a quick look at 81695717e6dcb6c040cbaf54d179c2c49202a5d1 to make sure I did the fsnotify.v0 → fsnotify.v1 switch correctly?  Many thanks for your help!  :-)

**Comment by nathany** [comment]
@anthonyfok Looks good to me. Thanks!

**Comment by anthonyfok** [comment]
@nathany Thank you!  :-)
