### ISSUE TITLE
Improve documentation: Partial templates variable

### ISSUE THREAD

**Issue by bl4ckdu5t** [spf13/hugo#3571]
The current [document here](https://github.com/spf13/hugo/blob/master/docs/content/templates/partials.md#variable-scoping) says after the variable scoping header that:
> As you might have noticed, partial calls receive two parameters
While this is great info, there had been no demonstration of how it's called with two parameters hence nothing to have noticed.
If there was an example in another documentation page can that be linked? Most people don't read all the documentation pages and referring to a context without linking may confuse the reader

**Comment by bep** [comment]
We're in the process of redoing the documentation, and even though I cannot promise that this specific issue is fixed, we cannot handle doc issues on this granularity right now. Thanks for the input.

**Comment by bl4ckdu5t** [comment]
Thanks for the response
