### ISSUE TITLE
Docs: navigation vertical scrolling issue

### ISSUE THREAD

**Issue by XhmikosR** [spf13/hugo#3572]
So, whenever I try to scroll vertically on mobile with the navbar open in order for me to go to another menu item, the navigation closes.

I'm using Android 7 with Chrome 58.

**Comment by bep** [comment]
We have a brand new docs site in the makings that will solve this and other issues.

**Comment by XhmikosR** [comment]
Is that live? I'd like to verify that this issue doesn't exist because it makes impossible to navigate the docs on mobile.

**Comment by bep** [comment]
I have checked, and this particular issue is confirmed fixed.

**Comment by XhmikosR** [comment]
OK, thanks for the replies. Just wanted to make sure the issue is fixed because it's very important for mobile.
