### ISSUE TITLE
0.22-DEV version broke my blog page

### ISSUE THREAD

**Issue by LeeU1911** [spf13/hugo#3578]
Hi all,

Does anyone know why something in the latest version 0.22-DEV somehow changed the way hugo generates my paginated blog summary page?

Here's the code where things worked flawlessly in the past but recently gives empty html output.
```
<div class="row">
            {{ range $i, $e :=  .Paginator.Pages }}
            {{ .Render "summary" }}
            {{ if modBool ( add $i 1) 4 }}
        </div><div class="row">
        {{ end }}
        {{ end }}
    </div>
        <span style="float:right;">{{ template "_internal/pagination.html" . }}</span>
    </div>
```

And `summary.html` partial for your reference:
```
<div class="col-sm-3 text-center box-item">
    <a href="{{ .Permalink }}" class="blog-link">
        {{ $url := printf "img/blog/%s" .Params.thumbnail }}
        <img src="{{ $url | absURL }}" class="img-responsive center-block" alt="{{ .Title }}">
    </a>
        <time class="blog-time">
            {{ $data := index .Site.Data .Site.Language.Lang }}
            {{ .Date.Day }} {{ index $data.month (printf "%d" .Date.Month) }}, {{ .Date.Year }}
        </time>
    <a href="{{ .Permalink }}" class="blog-link">
        <div class="blog-title">
            {{ .Title }}
        </div>
    </a>
</div>
```
My travis-ci build get hugo executable by `go get github.com/spf13/hugo` which leaves me no way to specify a version number. The build is run daily and it's only rendered an empty blog page in the last two days so my first thought is something in the new hugo version is the culprit, but I could be wrong though.

It would be very appreciated if someone can shed some lights on this and if there's a way to let me specify a version of stable version of hugo, it would be the best.

Thanks a lot for the great work here anyway.

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions/troubleshooting.
