### ISSUE TITLE
Hugo 0.22 doesn't include the latest commits to blackfriday

### ISSUE THREAD

**Issue by arikroc** [spf13/hugo#3585]
It seems all of these commits were made before hugo 0.22 was released

https://github.com/russross/blackfriday/commits/master

**Comment by bep** [comment]
Yes, and there is a reason for this. Those commits will be part of the next Hugo main release.

**Comment by arikroc** [comment]
Ok, thanks @bep. I want to say - I always appreciate how active you are in responding to issues and forum posts and so on. It's very re-assuring and has made me recommend hugo to multiple people. So thank you.

**Comment by bep** [comment]
Just to add a short note to my above: The Blackfriday commits was added 2 days ago; and I almost never update any dependencies so close to a new release -- you never know what breaks.
