### ISSUE TITLE
Support GitHub-flavoured markdown code fences for highlighting

### ISSUE THREAD

**Issue by alanpearce** [spf13/hugo#362]
I think it would be much better if hugo supported
````markdown
```html
<h1>example</h1>
`` `
````
(The extra space is there to avoid GitHub parsing the inner block as markdown)
for highlighted code rendering.

The reason behind this is that a lot of Markdown editors support code fences, but not the `highlight` tag, so this makes hugo more consistent with other Markdown-renderering projects.

I don't think it would be too difficult for hugo to re-write the example above into the one below before passing it to pygments. What do you think?

```django
{{% highlight html %}}
<h1>example</h1>
{{% /highlight %}}
```

I'd be happy to try implementing this, although I've only got a little bit of experience with go.

**Comment by nathany** [comment]
:+1: for code fences and being able to set highlighter = pygments or none. 

that also opens up the possibility of supporting other highlighters in the future.

**Comment by nathany** [comment]
Another good reason for highlighting GitHub style code fencing is that blogs from NetsaCMS or Jekyll also use this format. It's one less thing to change when transitioning, and one less place to result in errors, as I ran into with #933.

**Comment by bep** [comment]
I agree. 

This could be done fairly cheap by hooking into shortcodeparser.go.

**Comment by bramp** [comment]
I attempted to add this support. I started by changing the shortcodeparser.go to return code fence tokens, and then changed the shortcode.go to turn a sequence of backtick, param, text, backtick into a highlight code block.

However, that seemed messy, and meant that blackfriday and shortcodeparser.go was parsing backticks. Instead I'm going to subclass blackfriday.Renderer, to call the highlight shortcode when a code fence is encountered.

**Comment by bep** [comment]
@bramp yes, that sound more sensible. But it does mean that it will only work for Blackfriday, but I guess that is an OK compromise. Make sure that it is configurable (default off).

**Comment by bramp** [comment]
Ok, this was quite easy. It works functional the same to the highlight shortcode. I'll be sending a PR shortly (I need to get my employer's sign off before I can share code). But a couple of comments:
1) I haven't updated the docs. Happy to do so if requested.
2) I see there is experimental support for mmark (instead of blackfriday). I can extend this so it works for mmark, but for the moment I haven't.

**Comment by bep** [comment]
1) Oh yes. But you can maybe wait with that one, just in case we disagree about property names etc. Just create a PR with the code changes for now.
2) I would create a pull request for Blackfriday first. Then me and others can test it out and get a feel of it. Then another PR for MM would be a great addition.

**Comment by nathany** [comment]
:+1:
