### ISSUE TITLE
allow relative URL's in themes 

### ISSUE THREAD

**Issue by kevinburke** [spf13/hugo#372]
The existing themes require you to specify a host domain for the CSS/JS, which seems sort of unnecessary given you could just define them relative to the root, instead of:

```html
<link href="http://localhost:1313/css/poole.css" />
```

it would be much simpler to write

```html
<link href="/css/poole.css" />
```

This has the advantage of working in staging and production domains with no changes necessary.

**Comment by isaaki** [comment]
> Only true if you are not checking the generated files into source code (I do, so I can track the differences between them)

Any idea why this is the case? 

I've just run into this as well, trying to sync production, repo, and server.

**Comment by bep** [comment]
I don't see a real issue here. Reopen if I'm wrong.
