### ISSUE TITLE
Clean output directory before generation

### ISSUE THREAD

**Issue by natefinch** [spf13/hugo#379]
Right now, if I generate my site, then change the name of a content file, and regenerate, the old generated HTML files stay in the output directory.  This can easily cause me to have duplicate or just plain old data in the output directory.

I read this thread on the forum: https://groups.google.com/forum/#!topic/hugo-discuss/G6LkdLX3frQ

I think that having the default be "wipe the directory before outputting to it" is the safest way to ensure you don't accidentally publish old data.  

I think it's important that, by default, Hugo makes sure the output directory always looks the same after generation, regardless of what was in there before.  I need to be able to trust Hugo to make my site directory exactly correct according to the configuration I give it.

For people that want to pre-populate their directory with data outside of what Hugo knows about, then there could be a flag called something like --nowipe to keep from wiping the output directory on generation, but then it would be up to them to delete old generated files.... but I don't think that should be the default behavior, because it can cause hugo to make the directory dirty.

**Comment by swill** [comment]
Trying to figure out the status of this issue because I am having similar problems...

Is @whereisaaron's bash script the only solution to this problem at this point?

**Comment by ghostsquad** [comment]
I wrote this powershell function, which would need to be customized to exclude other files that hugo would not generate:

```
function hugo-clean-rebuild {
    if(-not (test-path 'config.yaml')) {
        write-warning "current directory does not appear to be a hugo site directory."
        return
    }
    gci -path .\public -exclude ".git", "readme.md" | %{ rm $_ -recurse }
    hugo
}
```

maybe that will help you (if on windows)

if I were to expand this for general purpose use, I'd probably require a `.hugoignore` file in `public/`, read from that, and ignore `.git` and `.hugoignore` + glob/regex matching using contents of `.hugoignore` similar to `.gitignore`.

**Comment by bep** [comment]
I'm closing this as "won't fix" for now.

I don't want to implement/review "delete folders" code in an open source project. There are plenty of effective ways to handle this:

1) Do a `rm -rf` in a shell script
2) Separate dev and prod build targets

**Comment by ghostsquad** [comment]
@bep - I agree, wrapping hugo tasks in a build/task engine (gulp/grunt?) would definitely take care of this.
