### ISSUE TITLE
taxonomy mapping to another document type

### ISSUE THREAD

**Issue by tgirod** [spf13/hugo#391]
This is a use case I am facing right now, and I can't find a way to handle it properly. Let's expand on the taxonomies example from the doc. We have two document types: ``actors`` and ``movies``. 

As suggested in the example, let's describe the relation between actors and movies through the ``actor`` taxonomy. In ``content/movie/moonrise kingdom.md``, I add ``actors: ["Bruce Willis", ...]``. This will generate an index ``actors/bruce-willis/``, which is essentially a filmography.

Unfortunately, we also have a page talking about bruce willis: ``actor/bruce-willis/`` - notice the similarity in names. Rather than having two pages like this, Bruce's filmography would be best inserted at the end of the page in his name in the ``actor`` section.

 - How should I achieve that with hugo ? 
 - Is it possible to prevent hugo from generating index pages for a taxonomy ?

**Comment by bep** [comment]
More questions? http://discuss.gohugo.io/
