### ISSUE TITLE
Specify locale for {{ .Date.Format "Jan 2, 2006" }}

### ISSUE THREAD

**Issue by alexkravets** [spf13/hugo#422]
Is there a way to specify locale for Format function so non-English locale to be used? Maybe ```languageCode``` in website config could be used for by default?

**Comment by bep** [comment]
See http://gohugo.io/tutorials/create-a-multilingual-site/

This should cover this issue. i18n issues must be handled in a bigger picture than this, and I guess we are waiting for better support in Go stdlib etc.
