### ISSUE TITLE
string manipulation inside templates

### ISSUE THREAD

**Issue by yacoob** [spf13/hugo#446]
I'm trying to do a regexp replacement on a parameter - I'd like to change a part of URL I keep in .Params.cover_img. I belive the lack of usual functions for those kind of purposes is caused by the fact that people are expected to use golang's facilities for this. However, I can't get this to work with `{{ call ... }}`. Is it at all possible? Should it be? :D

**Comment by bjornerik** [comment]
This should be covered by #801. @yacoob could you verify?
