### ISSUE TITLE
Using an invalid shortcode has confusing results

### ISSUE THREAD

**Issue by natefinch** [spf13/hugo#447]
Took me a while to figure this one out.  There's actually two problems here:  The first is that if you specify a shortcode that doesn't exist, there's no error message to the user.  If you do {{% abcde %}} and there's no abcde shortcode, it just silently fails.  I think this should merit a warning, since 99% of the time it's going to be a mistake by the user.  At the very least it should be displayed under verbose logging.  

However, that's less bad than the second half of the bug.

If you have an invalid shortcode in a document, none of the shortcodes after that one in the document will be rendered.  So, for example if you have a shortcode called valid.html and you don't have one called invalid.html:

{{% valid %}}
{{% invalid %}}
{{% valid %}}

The first valid shortcode will render, the invalid and second valid shortcode will not (they'll be output as their literal text in the HTML).  This is especially heinous when the first shortcode you have in the document is invalid, because it'll look like the shortcodes aren't getting rendered at all.

**Comment by bep** [comment]
@natefinch is this still the issue? Can you close if not.

**Comment by bep** [comment]
I take that as a no.
