### ISSUE TITLE
Don't add "s" by default to section name passed as Node variable .Title

### ISSUE THREAD

**Issue by srinathh** [spf13/hugo#460]
I'm finding that Hugo is adding an "s" for plural by default to the section name that is being passed to the list template as the Node variable .Title. I am using that .Title to display a small sub-heading

adding "s" for plural works fine if you're using the section title "Post" which becomes "Posts" - but i'm not & "Opensource" becomes "Opensources" or "Blog" becomes "Blogs" which is not necessarily correct. Hugo should not assume "s" is the right plural for everything.

**Comment by bep** [comment]
The issue described here was fixed by 35d04671d37e386ea9da376efd44006410157393
