### ISSUE TITLE
Support for AsciiDoc

### ISSUE THREAD

**Issue by tbrooke** [spf13/hugo#470]

**Comment by ollin** [comment]
asciidoc +1

**Comment by 0xMF** [comment]
asciidoc +1

**Comment by bjornerik** [comment]
asciidoc +1

**Comment by voxadam** [comment]
Don't worry folks, Steve (aka @spf13) has stated publicly[1] that he's diligently working on a solution to bring asciidoc support to Hugo. 

[1] http://discuss.gohugo.io/t/contributing-golang-code/223/3

**Comment by spf13** [comment]
I've made good progress on this. Love seeing the enthusiasm here.

**Comment by 0xMF** [comment]
@spf13 thanks! Liking Hugo thus far, making and using a theme seems easy and intuitive (so far) ;)

**Comment by bguiz** [comment]
+1 for asciidoc
(yet another one)
Is this likely to come in in v0.13 or can we be waiting for this in v0.14?

**Comment by spf13** [comment]
I really hope in v0.13 even if it's just experimental.

--
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by anthonyfok** [comment]
Hi @tbrooke, @ejemba, @voxadam, @txchen, @ollin, @0xMF and @bguiz,

An experimental support for AsciiDoc has been added in Pull Request #826.
Since @VonC's excellent https://github.com/VonC/asciidocgo needs just a little bit more work before we could use it, PR #826 searches for the original [Asciidoctor](http://asciidoctor.org/) (written in Ruby) and pipes content through it, similar to how Hugo supports reStructuredText.

Caveat: Since Asciidoctor is not written in Go, it would be slow, but it works!  :-)

There may be some quirks and idiosyncrasies, so your feedback is very welcome and very much needed.  So, please try to build from source with #826 applied, and start using it in your projects, and give us feedback on what works and what don't!

Many thanks!

**Comment by bguiz** [comment]
@anthonyfok Thanks for the great work. My trivial tests so far have been OK, but it looks like @bep has done a rather comprehensive one already: https://github.com/spf13/hugo/pull/826#issuecomment-71316363

@VonC I was going to say the same as what @bep said here: https://github.com/VonC/asciidocgo/issues/1
As the last commit was 7-8 months ago, it looks like it is pretty stagnant, but I do not want to jump to conclusions. Are you still working on this, or would you like it to be forked?

**Comment by VonC** [comment]
@bayne Sorry, I missed @bep comment. I answered it there. TLDR; you can re-create the project.

**Comment by sjfloat** [comment]
+1 FWIW

**Comment by anthonyfok** [comment]
@sjfloat: Experimental support for AsciiDoc is already committed to 0.14-DEV.  See #826 for more information.  Please test it out and give us feedback!  :-)

**Comment by sjfloat** [comment]
Nice, thanks. I'll give it a spin.

On Mon, Mar 23, 2015 at 11:33 AM, Anthony Fok <notifications@github.com>
wrote:

> @sjfloat <https://github.com/sjfloat>: Experimental support for AsciiDoc
> is already committed to 0.14-DEV. See #826
> <https://github.com/spf13/hugo/pull/826> for more information. Please
> test it out and give us feedback! :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spf13/hugo/issues/470#issuecomment-85052052>.
>



-- 
"I have delusions of grandeur. I believe myself to be Steve Jones"

**Comment by sjfloat** [comment]
Would that be master then?

On Mon, Mar 23, 2015 at 11:37 AM, Steve Jones <steve@jonescape.com> wrote:

> Nice, thanks. I'll give it a spin.
>
> On Mon, Mar 23, 2015 at 11:33 AM, Anthony Fok <notifications@github.com>
> wrote:
>
>> @sjfloat <https://github.com/sjfloat>: Experimental support for AsciiDoc
>> is already committed to 0.14-DEV. See #826
>> <https://github.com/spf13/hugo/pull/826> for more information. Please
>> test it out and give us feedback! :-)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/spf13/hugo/issues/470#issuecomment-85052052>.
>>
>
>
>
> --
> "I have delusions of grandeur. I believe myself to be Steve Jones"
>



-- 
"I have delusions of grandeur. I believe myself to be Steve Jones"

**Comment by anthonyfok** [comment]
@sjfloat: Yes, it is in the `master` branch.

**Comment by sjfloat** [comment]
OK, gave it a try:

`Hugo Static Site Generator v0.14-DEV BuildDate: 2015-03-23T15:16:45-04:00`

but I got:

`CRITICAL: 2015/03/24 Errors reading pages: Error:No handler found for about.adoc`

What must I do to see asciidoc rendered?

Thanks!

**Comment by bguiz** [comment]
If I were to guess, it could be simply changing the extension to .asciidoc

W: http://bguiz.com

**Comment by bep** [comment]
No, adoc should be a supported suffix. My guess you are building with wrong (old) Hugo version.

**Comment by sjfloat** [comment]
Well, it's telling me it's v0.14-DEV (I built master). And, yeah, the commit looked like it should recognize 'adoc'. Maybe I'll try a few other variations. And should the generated front matter markup be asciidoc or markdown?

**Comment by anthonyfok** [comment]
Thanks for catching that, @sjfloat!  A fix has just been committed for ".adoc" file extension recognition.
Please pull the latest HEAD from `master` and try again.  :-)

**Comment by sjfloat** [comment]
Will do. Thanks for jumping on that so quickly!

**Comment by sjfloat** [comment]
Yeah, seems to work. I need to familiarize myself with Hugo before I can comment further.

**Comment by chadcurry** [comment]
Hi, very interested in using AsciiDoc for a project and curious about Hugo. Any updates on support? Is the dev version near release? Thx!

**Comment by gour** [comment]
@anthonyfok Same as with reST support test - using Pandoc's README, although it renders (much) better, but I see in the terminal:

```
[...]
INFO: 2015/05/07 Rendering with /usr/bin/asciidoc ...
ERROR: 2015/05/07 exit status 1
[...]
```
How to get more output besides '-v' ?

**Comment by mojavelinux** [comment]
Nice work!

I noticed that you're using a regexp to extract the `<body>` content from the result from Asciidoctor / AsciiDoc Python. You can instruct the processor to only produce the content for the body by passing the `-s` flag.

I also recommend passing several attributes to the AsciiDoc processor so that authors can tailor content for the environment. Here are the attributes we've been setting (as applied to Hugo).

* env=site
* env-site=
* hugo-version=x.y.z

You'd pass these as follows:

```
-a env=site -a env-site= -a hugo-version=x.y.z
```

Of course, if you find other default settings to be useful, you can consider passing those as well. If you append a `@` at the end of the attribute value, you allow the page to override that setting. Otherwise, the setting is immutable.

**Comment by nickoe** [comment]
Shouldnt this issue be closed consindering that the milestone tag for this issue is v0.14 and it has been released as announced here: https://github.com/spf13/hugo/releases

**Comment by bep** [comment]
The current implementation is only temporal (hopeful).

**Comment by nickoe** [comment]
I just tried to add an foo.asciidoc file with a frontmatter and some random chars in the content, but it will not render. The only thing I see is the title (filename) of the post. Is there any way to get more debugging?  I do have a2x in my path, if that is what the temporal solution of asciidoc is using.
`ERROR: 2015/06/25 exit status 1`

**Comment by nickoe** [comment]
I just tried to use master, and I can render some asciidoc, but it will not upport the asciidoc include stuff and images seem to be wrong (not rendering), but I have not debugged those. This against 9b3d0cf5bf669603fa017e7054fe0ef8343c9e1d.

**Comment by anthonyfok** [comment]
Let's close this issue as we have accomplished our immediate goal, i.e. support for AsciiDoc, albeit experimental and through external Python-based (asciidoc) or Ruby-based (asciidoctor) helpers...

And open a new one for the native Go implementation of AsciiDoc support!  Please continue our discussions at #1435: "Add support for native Go implementation of AsciiDoc".

**Comment by nickoe** [comment]
Except that using asciidoc does not work, although asciidoctor works.

**Comment by anthonyfok** [comment]
Hi @nickoe, let's continue the discussion about `asciidoc` not working for your documents to Issue #1437, thanks!
