### ISSUE TITLE
Data models in Hugo similar to Jekyll and Mixture

### ISSUE THREAD

**Issue by isaaki** [spf13/hugo#476]
Greetings,

Can't say enough good things about Hugo. Many thanks for all the work on it. 

I've yet only fiddled with Hugo but am currently considering it as my primary static site generator. Before doing so, I'm wondering about one core feature: data models. Essentially, is it possible to store and loop through objects stored in JSON/YAML files within views? 

Two existing examples of such a feature can be seen [here with Jekyll](http://jekyllrb.com/docs/datafiles/) and [here with Mixture](http://docs.mixture.io/models).

**Comment by anthonyfok** [comment]
See also Pull Request #748, Feature: GetJson and GetJson in short codes or other layout files by @SchumacherFM

**Comment by bep** [comment]
For docs, see

https://github.com/spf13/hugo/blob/master/docs/content/extras/datafiles.md
