### ISSUE TITLE
Section is lowercased for list but not for permalink

### ISSUE THREAD

**Issue by natefinch** [spf13/hugo#484]
if I have content/FOO/bar.md, the content is created at /FOO/bar/   but the section list is at /foo/ this is quite confusing and makes for bad url navigation (editing out the /bar/ from /FOO/bar/ gives me a bare directory listing.  We should be consistent about whether we lowercase the section or not... my preference would be to not lowercase it, since the user obviously capitalized it for a reason.

**Comment by bep** [comment]
I have done some work in this department lately. Not completely happy about it, but I tried to create minimal havoc in the API department.

In my eyes, upper/lowercase URLs is the minor problem in this soup (they should match, of course) -- there are some URL vanity purists out there, I'm not.

What's worse is that with sections and taxonomies, there has been no way to get "what you type" as titles on the list pages etc. In stead you get some non-standard titleized variant with lots of chars stripped away (I'm from Norway - this suits no style guide in my country).

To sum up, the default behaviour (from top of my head) was:

1. Taxonomies and sections are put into a map with their names made tolower, then pushed through helpers.MakePath, so "You got @mail" becomes "you-got-mail". 
2. On render time, that same "you-got-mail" is:
- For title => "You Got Mail"
- Urls are sent through helpers.MakePathToLower (the tolower variant of the above), which doesn't do much in the above example. 

For sections there also were some other casing issues that should now be fixed.

But my point is, in the story I just told: The most important one is the "messing with the taxonomy names".

**Comment by bep** [comment]
I'm closing this.
