### ISSUE TITLE
Arbitrary subdirectories without associated content

### ISSUE THREAD

**Issue by dunn** [spf13/hugo#487]
This might be something deliberately unsupported, but it seems like it'd be useful to more than just me.

Say I've got `content/projects/`, `content/presentations/`, and `content/posts/`, with their associated indexes.  But I also want to have other indexes where the content is organized under broader themes—like "Professional" and "Personal."  I'd like to be able to write a `professional.html` template that includes content from `projects` and `posts`, but to do that right now I need to make `content/professional/` and populate it with at least one piece of content.

**Comment by bep** [comment]
@dunn Hugo does support HTML content files. You need some kind of front matter in them (even only the start and the stop signs), but with that you can "drop index files" wherever you want.
