### ISSUE TITLE
How can I remove the trailing slash in pretty URLs?

### ISSUE THREAD

**Issue by unor** [spf13/hugo#492]
IIRC, with v0.11 pretty URLs had no trailing slash (as it’s still documented in the example on [Pretty URLs](http://hugo.spf13.com/extras/urls/)). With v0.12, a slash gets appended.

How can I, globally, get back the old behavior?

**Comment by bep** [comment]
For further discussion, use http://discuss.gohugo.io/

**Comment by keaeriksson** [comment]
Hi, if you are using AWS to host your Hugo site I wrote a blog post on how to remove trailing slashes using S3, CloudFront and Lamdba@Edge here: https://mocki.io/hosting-a-hugo-site-on-aws-s3-and-cloudfront.
