### ISSUE TITLE
MakePermalink method chopping off end of baseurl

### ISSUE THREAD

**Issue by realchaseadams** [spf13/hugo#506]
In `helpers/url.go` in the `MakePermalink` method, the baseurl is chopped from the .[com|org|etc] on, so if I had a url like: "myhugosite.com/blog", all permalinks are getting resolved to "myhugosite.com/$1" and the `/blog` is dropped off.

**Comment by bjornerik** [comment]
@realchaseadams did you retest this?

**Comment by realchaseadams** [comment]
I haven't had a chance to, if there's a unit test for it or if someone has seen it work like it's supposed to, feel free to close.

**Comment by bjornerik** [comment]
Just checked. This is covered by tests.
