### ISSUE TITLE
Variable/function for encoded permalink URLs?

### ISSUE THREAD

**Issue by tmaiaroto** [spf13/hugo#542]
It would be nice to have encoded permalinks for social media share links. For example `facebook.com/sharer/sharer.php?u=` looks for an encoded URL. Though it does work if you just pass it `{{ .Permalink }}` it would still be nice just in case.

**Comment by digitalcraftsman** [comment]
Fixed by #2257.

**Comment by makeforindia2017** [comment]
i can use + decode in my website permalink [http://alldigitalupdate.org/train-running-status-live/](url) this url.

**Comment by makeforindia2017** [comment]
i can modify my post url ( [http://alldigitalupdate.org/train-running-status-live/] )
to (http://alldigitalupdate.org/train+running+status+live/)
