### ISSUE TITLE
Add loop function

### ISSUE THREAD

**Issue by galaktor** [spf13/hugo#552]
I would like to be able to loop using some function in a template. It would be sufficient to loop with fixed direction and start value, i.e. from 0 up to my number. So basically an equivalent of doing a for loop like this

    for i := 0; i < $foo; i++ {  }

Maybe could look like this in the template:

    {{ repeat $foo }}{{ do stuff }}{{ end }}

*Maybe* even able to re-use the range keyword?

    {{ range $foo }}{{ do stuff }}{{ end }}

Bonus: loop down to 0 option, and ability to set the step size.

**Comment by spf13** [comment]
Closed because @bep added seq as suggested
