### ISSUE TITLE
Url is downcased

### ISSUE THREAD

**Issue by nono** [spf13/hugo#557]
Hello,

on http://gohugo.io/content/front-matter/, it is said:

> url The full path to the content from the web root

But it seems it's not really the case. For example, if I put `url: "/Blog/2012/02/29/changement-de-moteur-pour-ce-blog"`, the generated file will be `public/blog/2012/02/29/changement-de-moteur-pour-ce-blog/index.html` (with a blog in downcase).

**Comment by ThinkChaos** [comment]
Can confirm the issue.
hugo's server seems to be case insensitive, so there's no issue when you try locally, but GH pages is case sensitive (IMHO this should be default behavior for hugo), thus breaking the generated site.
