### ISSUE TITLE
I cannot make to work .IsPage and .IsNode variables

### ISSUE THREAD

**Issue by jaromirmuller** [spf13/hugo#580]
Hello, 

I'm trying to have a decision inside of partial `{{ partial }}`. 

Basically I want to share same partial on home page and post view. So I have 2 templates:

 - layout/index.html (for homepage)
 - layout/archive/single.html (for post page)
 - layout/partial/head.html (there should be placed decision logic based on .IsPage and .IsNode variables)

My partial contains 

```
  {{if .IsNode }}
  -- do something when node
  {{end}}

  {{if .IsPage }}
  -- do something when page
  {{end}}
```

This snippet `{{ partial "head.html" . }}` returns empty string. Nothing is rendered in browser.

.IsNode and .IsPage variables and their behaviour is described here http://gohugo.io/templates/variables/

Can anyone help me sort this out? I'm not able to find any example related to this topic.

Thank you.

**Comment by codeincarnate** [comment]
I'm having the same issue in v0.14.  Would be happy to upload code as necessary to demonstrate the issue.

**Comment by bep** [comment]
@codeincarnate yes, this is impossible to troubleshoot without an example. A GItHub repo is best.

**Comment by bep** [comment]
Please reopen if this still is an issue.

**Comment by siefca** [comment]
Had the same problem (using Hugo v0.38). `.IsPage` and `.IsNode` seem not to be enclosed within calling context but shadowed by a context of the partial. 

Workaround to preserve values of these two variables without a need to modify a partial too much:

In calling code:

```
{{ partial "partial_name.html" (dict "context" . "IsPage" .IsPage "IsNode" .IsNode) }}
```

In partial code:

```
{{- $IsPage := .IsPage -}}
{{- $IsNode := .IsNode -}}
{{- $. := .context -}}
[…]
{{ if $IsNode }}do_something{{ end }}
```
