### ISSUE TITLE
--uglyUrl=true not uglifying category links

### ISSUE THREAD

**Issue by jmalonzo** [spf13/hugo#595]
I have the following code in my template:

    {{ range .Params.categories }}<a class="post-category post-category-{{ . }}" href="/categories/{{ . | urlize }}">#{{ . }}</a>{{ end }}{{ end }}

.. the resulting href doesn't seem to be uglified, hence it leads to a 404.

**Comment by bep** [comment]
This is by design. `--uglyUrl=true` does nothing with URLs you construct "by hand".
