### ISSUE TITLE
[Windows] Wrong directory generated for newly created content on Windows

### ISSUE THREAD

**Issue by acisternino** [spf13/hugo#604]
An extra spurious directory is created when generating new content if hugo is invoked with a full path on Windows 7.

### Precondition
Hugo 0.12 amd64 freshly installed in `C:\Software` as `hugo_0.12` and **not** added to the path.

### Steps to reproduce
```
C:\Users\Andrea\Documents\development> \Software\hugo_0.12 new site myblog
C:\Users\Andrea\Documents\development> cd myblog
C:\Users\Andrea\Documents\development\myblog> \Software\hugo_0.12 new about.md
ERROR: 2014/11/02 Config not found... using only defaults, stuff may not work
C:\Users\Andrea\Documents\development\myblog\Software\content\about.md created
```
As reported by the `hugo new` command output, a spurious **Software** directory is prepended to `content`.

This behaviour can be replicated always: the installation path of the `hugo` executable is always prepended to `content`.

**Comment by bjornerik** [comment]
OK, I interpret silence as a positive sign. Close this for now.
