### ISSUE TITLE
Taxonomy example in doc fails

### ISSUE THREAD

**Issue by bep** [spf13/hugo#608]
At least the example below from the doc fails in 0.13:

```
<ul>
  {{ range .Site.Taxonomies.series.golang }}
    <li><a href="{{ .Url }}">{{ .Name }}</a></li>
  {{ end }}
</ul>
```
`Url is not a field of struct type hugolib.WeightedPage`

This works:

```
<ul>
  {{ range .Site.Taxonomies.series.golang }}
        <li><a href="{{.Page.Url }}">{{.Page.Title }}</a></li>
  {{ end }}
</ul>
```

**Comment by JindrichPilar** [comment]
Using v0.12  

- ``.Url`` / ``.Name`` doesn't work.
- ``.Page.Title`` Works fine
- ``.Page.Url`` No error but but prints nothing.
- ``.Page.Permalink`` Works fine

**Comment by mdhender** [comment]
I can't reproduce this under v0.13.
