### ISSUE TITLE
Anyone try using something other than Disqus for comments? 

### ISSUE THREAD

**Issue by HarshaThota** [spf13/hugo#625]
I was looking for commenting solutions that weren't Disqus and found issue https://github.com/spf13/hugo/issues/160 that led to @spf13's [Kaiju](https://github.com/spf13/kaiju). There are also solutions like @aethertap's [Fuzztalk](https://github.com/aethertap/fuzztalk), @vokimon's [hyde-comments](https://github.com/vokimon/hyde-comments), @bstpierre's [pelican-comments](https://github.com/bstpierre/pelican-comments), etc. 

Has anyone tried to implement either one of these or another non-Disqus solution on their Hugo site? If so, is there any documentation/examples that I can look at?

**Comment by bep** [comment]
More questions? http://discuss.gohugo.io/
