### ISSUE TITLE
Allow taxonomies to be single string values and convert internally to a slice of strings

### ISSUE THREAD

**Issue by adrinux** [spf13/hugo#630]
Currently Hugo will throw an error if a taxonomies terms are defined as strings in front matter.

spf13 "...accept either a single string value or an array of string values and internally convert it into a slice of strings. We should look into doing this for taxonomies as well."

See this post for context:
http://discuss.gohugo.io/t/using-intersect-to-find-related-content/297

**Comment by bep** [comment]
Hasn't thy this been fixed? Or is my memory totally off ...

**Comment by adrinux** [comment]
Haven't touched hugo for months, though will get back to it eventually. Short answer: I don't know.

**Comment by bep** [comment]
Closing as stale.
