### ISSUE TITLE
[Windows] error copying static files

### ISSUE THREAD

**Issue by ghosttie** [spf13/hugo#636]
This was working fine and then I started getting this error and I can't figure out why:

    ERROR: 2014/11/13 Error copying static files to C:\Users\John\Documents\My Dropbox\personal\projects\html\expendabots\source\public

**Comment by ghosttie** [comment]
Sorry for the delay (sincerely, it's inexcusable) but I'm still getting the same error with Hugo v0.13 (which I assume includes your fix since it was released this issue was closed)

**Comment by bep** [comment]
@ghosttie, did you compile it yourself or download a binary? If self, what version of Hugo?

**Comment by ghosttie** [comment]
I downloaded the latest official release - Hugo v0.13

**Comment by bep** [comment]
@spf13 what Go version did you use to build 0.13?

**Comment by ghosttie** [comment]
I didn't build it, I just downloaded it from https://github.com/spf13/hugo/releases

**Comment by bep** [comment]
Well, @spf13 did build that, and the question was meant for him.

**Comment by ghosttie** [comment]
OK, well, I'm still getting the error so something is still not right in the latest release...

**Comment by spf13** [comment]
@bep built with Go 1.4

**Comment by gima** [comment]
I might be shooting in the dark as well, so if this doesn't apply at all, please ignore this comment.

*See this is under Linux, not under Windows, but the point is, that I wanted to avoid stress on my SSD when Hugo built the output directory over and over again after file changes. I mounted the output directory as tmpfs and chowned it to my user&group. After this, Hugo would crash with weird error messages whenever a new file should be created in the output directory. I tracked it down to the [fsync](https://github.com/spf13/fsync/blob/master/fsync.go) package trying to be over-energetic wrt/something (don't remember what anymore) and "fixed" the problem by doing a chmod 777 on the output (the tmpfs mountpoint).*
