### ISSUE TITLE
RSSlink appends "/" to the resulting URL

### ISSUE THREAD

**Issue by sickill** [spf13/hugo#669]
I used this in my layout:

    <link href="{{ .RSSlink }}" rel="alternate" type="application/rss+xml" title="{{ .Site.Title }}" />

And I got this as a result:

    <link href="http://blog.asciinema.org/index.xml/" rel="alternate" type="application/rss+xml" title="Asciinema Blog" />

Note the trailing slash in href attribute. Is this on purpose? With the current behavior I need extra rewrite rule in Nginx config to prevent 404.

**Comment by bep** [comment]
Closing as stale, please reopen if still an issue.
