### ISSUE TITLE
--baseUrl misses some links

### ISSUE THREAD

**Issue by rickb777** [spf13/hugo#681]
When I set `--baseUrl`, I expect all the (internal) links in my site to be one of

* a relative path without a leading `/`
* a path starting with `/`
* a URL starting with the base-url I specified.

Unfortunately, this doesn't always work. Some links are left in that start with the `baseurl` setting in `config.toml`.

If I edit `config.toml` and manually change `baseurl`, I get the expected behaviour.  Therefore it seems that the `--baseUrl` option is buggy.

(v=0.12)

**Comment by bep** [comment]
@rickb777 could you try with the latest Hugo version and report back if this is still an issue?
