### ISSUE TITLE
Hugo v0.12 server terminates on malformed front matter

### ISSUE THREAD

**Issue by quoha** [spf13/hugo#693]
Running Hugo v0.12 on Mac OS 10.10. The server dies unexpectedly when it encounters an error reading the front matter in a Markdown file. The following file causes the error:
```
+++
Description = ""
Tags = ["aaa", bbb", "ccc"]
Categories = ["dddd"]
menu = "main"
weight = 5
date = "2013-06-11T16:11:33-06:00"
title = "bad front matter"
+++
Lorem ipsum...
```

Note that the tag should be `"bbb"`, but is missing the opening quotation mark. The server logs the following then exits.
```
ERROR: 2014/12/02 Error parsing page meta data for bad-front-matter.md
ERROR: 2014/12/02 Near line 3, key 'Tags': Near line 3: Expected value but found 'b' instead.
ERROR: 2014/12/02 Near line 3, key 'Tags': Near line 3: Expected value but found 'b' instead.
CRITICAL: 2014/12/02 Errors rendering pages: Near line 3, key 'Tags': Near line 3: Expected value but found 'b' instead.
```

An error in the Markdown file shouldn't cause the server to terminate. It should ignore the file and continue on.

**Comment by bep** [comment]
This has been fixed.
