### ISSUE TITLE
Add support for alias with whitespace

### ISSUE THREAD

**Issue by time4tea** [spf13/hugo#701]
possibly being a bit thick, but am having a bit of trouble making an alias for a page that had a space in it.

e.g. the old page was /wiki/Some Page

aliases = [ "/wiki/Some Page" ]

makes a page redirect for /wiki/Some-Page

aliases = [ "/wiki/Some+Page" ]

makes a page redirect for /wiki/SomePage

how could I create the right alias?

thanks!

**Comment by nickoe** [comment]
Has there been any progress on this issue @bep? As you see we also have this issue, just where it is a plus sign that is removed instead of the space character.

**Comment by marekr** [comment]
The problem is hugo is filtering out the URL here:
https://github.com/spf13/hugo/blob/master/helpers/path.go#L97

Meanwhile RFC 3986 allows:
A-Z, a-z, 0-9, -, ., _, ~, :, /, ?, #, [, ], @, !, $, &, ', (, ), *, +, ,, ;, and =

+ is only not allowed in query strings but hugo doesn't use those.

**Comment by anthonyfok** [comment]
Due to a recent patch, the relevant line is now at https://github.com/spf13/hugo/blob/master/helpers/path.go#L99

Rather than modifying UnicodeSanitize(), perhaps aliases could be sanitized by another (new?) function, or even (\*gasp\*) not sanitized at all?

**Comment by bep** [comment]
Yea, for values that is entirely provided by the end user, it should be left un-touched. The user will see if it works or not. 

That may be a breaking change, though ...

**Comment by nickoe** [comment]
@bep What do you think it could break?

**Comment by bep** [comment]
@nickoe the current aliases that would be changed by this.

**Comment by marekr** [comment]
I would argue that any current alias that "changes" was initially broken because it was probably having characters filtered out that were desired.

**Comment by anthonyfok** [comment]
As it looks like an interesting exercise, I spent some minutes looking at the code and came up with a proposed fix in Pull Request #1417, basically bypassing helpers.MakePath() (hence bypassing UnicodeSanitize()) altogether, trusting the end user that he/she knows what he/she is doing.

@time4tea, @marekr and @nickoe, if you really need this feature now, you may try applying the patch in #1417 and building your local copy of Hugo.

On the other hand, I do worry about potential security implications.  Should there be some "checks and balances" to make sure a random or even **a carefully crafted and malicious** alias would harm the system?

----

Oh wait, it does!  There is a very simple way to get Hugo to create an alias **outside** the public directory, with Hugo v0.14 as well as the current HEAD in Git!  Should I open a new bug report about it?

**Comment by spf13** [comment]
I don't think this would be a breaking change. We shouldn't sanitize direct user input for aliases. Or at least we should allow the entire RFC here. I think @anthonyfok 's approach of defining a more adherent sanitize function is the best approach. Anyone want to do it?

**Comment by marekr** [comment]
The only thing to becareful of on Windows because hugo creates the folders for aliases. Windows doesn't support ?, * and : in file paths even though Linux does, so not sure what golang would throw when that a "bad" aliases occurs on Windows.

**Comment by bep** [comment]
@marekr that is a good point in this discussion: Sites should work cross platform.

**Comment by marekr** [comment]
@bep unfortunately its a difficult to fix situation and the best that could be done is throw up a obvious warning on windows platforms about attempting to generate restricted characters.

Otherwise hugo would need to start generating server redirection rules to handle it on windows :/
