### ISSUE TITLE
canonifyUrls=true, RelPermalink and baseUrl with sub-path does not work

### ISSUE THREAD

**Issue by bjornerik** [spf13/hugo#711]
I was bitten by this trying to fix #519. 

Given:

BaseUrl: http://somehost.com/sub
CanonifyUrls=true

RelPermalink for a page will give

http://somehost.com/sub/sub/rest-of-url

Not sure if this is easily fixable. Maybe the RelPermalink method could take CanonifyUrls into account?

**Comment by tatsushid** [comment]
I was bitten by the issue too when I tried to learn how `canonifyurls` works.
