### ISSUE TITLE
Allow home page to be easily authored in markdown

### ISSUE THREAD

**Issue by bguiz** [spf13/hugo#720]
Presently, it looks like the only way to put content in the home page on a hugo site with a theme is to override the theme, by creating a file `/layouts/index.html`, where the contents of the home page must be inserted manually using HTML. The `{{ partial "foo.html" . }}` syntax can only be used to include partials which also must be HTML, not markdown.

The only way I can think of working around this is to have `layouts/index.html` such that it ierates over all pages, and simply filters them based on the presence of a parameter, like so:

	{{ range .Data.Pages }}
		{{ if isset .Params "homeContent" }}
			{{ .Content }}
		{{ end }}
	{{ end }}

However, this seems like a rather roundabout, and inefficient, way of going about things. Is there a better way?

**Comment by chibicode** [comment]
:+1:

**Comment by chibicode** [comment]
I tried using markdownify filter (which was added here: https://github.com/spf13/hugo/pull/652) but this doesn't work as the filter takes a string and not `template.Html`...

```
{{ partial "home.md" . | markdownify }}
```

**Comment by hickford** [comment]
Hi. My site will only have one page, and I'd like to write it in Markdown. Can you help? I still want to use Hugo because of the csv dynamic content feature.

https://stackoverflow.com/questions/30030631/how-to-build-single-page-site-from-markdown

**Comment by scottcwilson** [comment]
I'm going to try to fix this.

**Comment by bep** [comment]
@scottcwilson talk to @spf13 -- he had a solution in place for this, that we had to roll back cause it had some side effects.

**Comment by spf13** [comment]
So my initial solution was to add in a page handler to the homepage rendering function so it could handle a node (as it does now) or a page whose content was located in index.md. This proved problematic with pagination and overall quite a bit messier than I hoped. 

A better approach would be to add support for nodes to have a content field and support nodes having content. We could actually do a lot of really neat things once that feature is in place with some of the automatically created urls (like taxonomy index pages) but before getting too far ahead I'd focus on just the home page (but think about how it would affect other places)..

Some things that need to happen:
1. We need  a mechanism and pattern to map content files to nodes. I think this is easy for the homepage just call it content/index.md, but the mapping functionality should be generic enough to be able to work for other nodes as well. 
2. Make sure that the nodes don't appear in the Site.Pages slice. (I'm not 100% sure on this)
3. Check for any other conflicts.
4. Add documentation and tests. 

The tests I already wrote for the code I submitted should still work, we just needed a better implementation. 

You can find my imperfect implementation at https://github.com/spf13/hugo/commits/spf13-content-homepage

**Comment by bep** [comment]
Also see #1051 -- if a Node has content it should also have frontmatter with proper title and params etc.

**Comment by dimo414** [comment]
A general solution for nodes to contain content would be a really nice improvement!  It might make sense to provide a `{{ .Site.Nodes }}` variable or similar at the same time, so #1303 can be addressed.

**Comment by bep** [comment]
Will be handled in #2297.

**Comment by kbhutiya** [comment]
i know this thread is old,but i just happened to have the same issue..is it solved yet?

**Comment by bep** [comment]
>is it solved yet?

yes.
