### ISSUE TITLE
CanonifyUrls does not canonicalize urls in RSS

### ISSUE THREAD

**Issue by popthestack** [spf13/hugo#725]
In my config: `CanonifyUrls = true`

In rss.xml: `{{ .Content | html }}`

Linking to another post: `[nifty thing I wrote](/article/post-slug/)`

Rendered post: `<a href="http://localhost:1313/article/post-slug/">nifty thing I wrote</a>`

Rendered index.xml: `&lt;a href=&#34;/article/post-slug/&#34;&gt;nifty thing I wrote&lt;/a&gt;`

Alternately, something like `CanonifyUrlsInRSS` would be handy, since that's really where I want canonicalized urls anyway.

(I'm brand new to Go and Hugo, but given time I'm willing to make this a PR.)

**Comment by anthonyfok** [comment]
Awesome!  @popthestack has fixed the bug very nicely with commit 7dacc99 in #728!  Thank you so much!

That means there is one less problem we have to deal with in #789 in our quest to produce the perfect RSS feed.  :-)
