### ISSUE TITLE
Support an "expiration" date

### ISSUE THREAD

**Issue by quoha** [spf13/hugo#726]
Edited from http://discuss.gohugo.io/t/deleting-unpublishing-items/324

Hugo has a useful feature for automatically publishing content on a particular date.

    publishdate: 2014-12-25

Can we add an "expiredate" key to allow content to lapse automatically?

Or a way to flag content as "do not publish" without deleting the corresponding file?

Is it possible to include a time as well as a date? e.g. "2007-04-05T14:30" (ISO8601 format)

**Comment by mohae** [comment]
I was looking at adding this and wanted to see if `expireDate` is the consensus.  I was thinking `unpublishDate`, I think it's more explicit, in terms of what will happen with that date, and it's consistent with `publishDate`.

Whatever the label, if the value is < `publishDate`, the page will be published.  If the value is > `publishDate` && < Now, it will not be published.

Information will be added to the publishing summary.

**Comment by bep** [comment]
It should be expiryDate.

>Whatever the label, if the value is < publishDate, the page will be published. If the value is > publishDate && < Now, it will not be published.

I don't understand the logic above.

It should be pretty straightforward: Don't publish if Now >= expiryDate or Now < publishDate.

**Comment by g3wanghc** [comment]
@bep Can I take a shot at it? :D

**Comment by bep** [comment]
>@bep Can I take a shot at it? :D 

Please do.

**Comment by bep** [comment]
This is now fixed.
