### ISSUE TITLE
Comments wrongly converted in Definition List and Paragraphs

### ISSUE THREAD

**Issue by duncombe** [spf13/hugo#729]
Within a definition list (`<DL></DL>`) in a markdown document, Hugo converts comments (`<!-- -->`) to `&lt;!&ndash; &ndash;&gt;`. Outside the list scope the comments are treated correctly and left as comments (`<!-- -->`). This is a bug.

Correction: within any list, including markdown lists demarcated with `-` or `*`, not just HTML tagged lists, Hugo renders the the comments incorrectly, turning them into displayed characters.

**Comment by bep** [comment]
This should now be fixed in Blackfriday -- and will be part of the next Hugo release.
