### ISSUE TITLE
An extra post/ in the FullFilePath

### ISSUE THREAD

**Issue by opennota** [spf13/hugo#732]
`{{ .Page.FullFilePath }}` inside a shortcode produces `post/post/first.md` for the file `post/first.md`.

How to reproduce:

1. Create a site, add a theme.
2. `hugo new post/first.md`
3. `mkdir -p layouts/shortcodes`
4. Add a file `layouts/shortcodes/path.html` with the following content: `{{ .Page.FullFilePath }}`
5. Add the following content to the `post/first.md`: `{{% path %}}`
6. `hugo -D -t hyde`
7. `grep post/ public/post/first/index.html`

This will output `<p>post/post/first.md`.

**Comment by bjornerik** [comment]
@spf13 - you know this code ... there is a confusion between Dir() ("post/") and Path() ("post/first/index.html") ... I guess Dir() should return "/home/myhugoproject/content/".
