### ISSUE TITLE
Add lastmod datetime

### ISSUE THREAD

**Issue by bep** [spf13/hugo#733]
There is date (default sort) publishdate (when it is published). #726 want expirydate.

I want lastmod -- to be used in sitemap.xml etc. I often make changes to my content, but I do not want to bring it to the top just to notify Google about these changes.

It should by default be set to the vale of date, but should be overridable in frontmatter. Maybe "hugo new" should add this as well?

**Comment by reactor10** [comment]
@bjornerik I also want lastmod for my sitemap and am happy to implement it. Does the following sound reasonable?

1. Always add a <lastmod> field to the sitemap
2. Use the front matter publishDate to fill the <lastmod> if present
3. Alternatively get the actual modification time of the markdown file

**Comment by bjornerik** [comment]
Great!

1. In sitemap code, just replace node.Date with node.Lastmod
2. No, the date is better, I think. Not 100% sure -- but that's more in line with how it is today. Date is normally the timestamp on creation.
3. Yes.

**Comment by bep** [comment]
@reactor10 need any more input on this? This would be very nice to have.

**Comment by jbrodriguez** [comment]
Hi, is there any update on this ?

Sometimes, I update an article to refresh the content or if something major happened (like Google Code hosting shutting down), and I'd like to have a Last Modified date to show.

Will appreciate any feedback.

**Comment by bep** [comment]
@reactor10 may know.

**Comment by reactor10** [comment]
Sorry guys. I got stuck with the implementation as I couldn't work out where best to put the timestamp. Here's a branch I was working on: https://github.com/spf13/hugo/compare/master...reactor10:byron-lastmod

My question @bep: When the sitemap is generated I cannot access the full original path in order to do an `os.Stat`, it therefore must be written a variable in the `Page` struct - is this OK?

**Comment by bep** [comment]
@reactor10 for many reasons it should be a field on Node, `Node.Lastmod`.

**Comment by rhewitt22** [comment]
Is the scope of this issue only to add `Lastmod` to the sitemap?  I'd like the ability to use this on pages, too.  Would using `Node.Lastmod` preclude that?

**Comment by bep** [comment]
The scope is:

* add lastmod to Node
* for Page:
** If lastmod is set in front matter, use that value, else set it to the value of date
* for Node
** Use the same logic that is used for date, but for lastmod (fetch the value from the "last" Page)

**Comment by bep** [comment]
@reactor10 any progress on this?

**Comment by jbrodriguez** [comment]
@bep I took @reactor10's code as a base and made some modifications, to get lastmod working on Page. Here's the branch https://github.com/spf13/hugo/compare/master...jbrodriguez:jbrodriguez-lastmod
If that's ok with @reactor10, I can move forward based on this and your review of the code, to check if I'm on the right path

**Comment by reactor10** [comment]
Sorry that my communication has been poor (nonexistent), thanks for
stepping up - it looks good @jbrodriguezeen[1]

--
Byron Williams byron@112percent.com



On Tue, 12 May 2015, at 14:42, Juan B. Rodriguez wrote:
> @bep[2] I took @reactor10[3]'s code as a base and made some
> modifications, to get lastmod working on Page. Here's the branch
> master...jbrodriguez:jbrodriguez-lastmod[4]
>
If that's ok with @reactor10[5], I can move forward based on this and
your review of the code, to check if I'm on the right path

> — Reply to this email directly or view it on GitHub[6].

>



Links:

  1. https://github.com/spf13/hugo/compare/master...jbrodriguez:jbrodriguez-lastmod
  2. https://github.com/bep
  3. https://github.com/reactor10
  4. https://github.com/spf13/hugo/compare/master...jbrodriguez:jbrodriguez-lastmod
  5. https://github.com/reactor10
  6. https://github.com/spf13/hugo/issues/733#issuecomment-101285664

**Comment by bep** [comment]
@jbrodriguez it doesn't look like what I specified. It's not like what I say must be right all the time, but I said something about:

* Put it on Node (not Page, not File)
* Follow the logic used currently for date
* Use the value set in front matter, if not set use the same value as date

**Comment by jbrodriguez** [comment]
@bep Let me check, I seem to have a general idea on how to put it in Node.

One question, eventually, from a page template (let's say _default/single.html), one would refer to Lastmod by

```{{ .Node.Lastmod.Format "20060102-15:04:05.000" }}``` ?

**Comment by bep** [comment]
`{{ .Lastmod.Format "20060102-15:04:05.000" }}`

This should work on both `Page` and `Node`.

The distinction here is confusing in Hugo. Page = content pages, Node = list pages.

In technical terms, the Node struct is embedded in Page (this is a very cool Go construct that encourages composition (in contrast to inheritance)).

So, if you look at `Node.Date` - this is only defined on Node, but can also be accessed from Page.

But since Node (home page, list pages) has no physical file connected to it, the value for Date (and Lastmod) must be derived (last post).

**Comment by jbrodriguez** [comment]
@bep That's a very cool language feature, didn't know about it.

Here's a branch that follows your specs https://github.com/spf13/hugo/compare/master...jbrodriguez:jbrodriguez-lastmod-3

If Lastmod is set in front matter, it picks it up; if not set, if assigns Date to Lastmod.

The only issue I see here is that Date == "file creation date", whereas file modification date feels like a better fit.

Please let me know your comments.

**Comment by bep** [comment]
@jbrodriguez this looks very good. Just one comments:

1. In site.go -> BuildSiteMeta. s.Info.LastChange must be set to Lastmod
2. Related to the above, and I didn't think about this until now: I think we should add another field s.Info.LastCreated and put the last Date into that one. And then use that value in RenderSitemap. 

Finally - if you could also change the sitemap.xml template in /tpl/template_embedded.go from .Date => .Lastmod I would be perfectly happy. That was the reason I opened up this issue in the first place.

**Comment by bep** [comment]
No, drop the s.Info.LastCreated  for now -- but make sure that s.Info.LastChange gets the Lastmod value.

**Comment by jbrodriguez** [comment]
Ok, I've made the changes (same branch https://github.com/spf13/hugo/compare/master...jbrodriguez:jbrodriguez-lastmod-3)

Two comments:

1 - There are other internal templates that should probably be modified as well:
- rss.xml
lastBuildDate

- opengraph.html
og -> meta property="og:updated_time"
facebook -> meta property="article:modified_time"
twitter -> meta itemprop="dateModified"


2 - This code
```
 	if len(t.pages) > 0 {
 		n.Date = t.pages[0].Page.Date
		n.Lastmod = t.pages[0].Page.Lastmod
 	}
```

t.pages is a WeightedPages, so it's sorted by user's definition (defaults to Date?).

But adding Lastmod means t.pages[0] not necessarily has the "latest" Lastmod.

If that's the case, perhaps we should scan t.pages or sort a copy of t.pages, to find the latest Lastmod.

Let me know how you see this.

**Comment by bep** [comment]
@jbrodriguez - this looks good. Create a pull request and I will pull it in.

The rest of your comments are good, but let us take those in #1141

**Comment by riklopfer** [comment]
Have the user docs been updated with this change? I don't see anything on the [template variables page](http://gohugo.io/templates/variables/).

**Comment by bep** [comment]
@riklopfer https://github.com/spf13/hugo/issues/1590

**Comment by riklopfer** [comment]
Okay cool. It's not clear to me how to order by that field though. I checked the docs [here](http://gohugo.io/templates/list/#ordering-content:8c265e2adc353bedf8022b542a0b78ab).
