### ISSUE TITLE
Idiomatic platform binaries

### ISSUE THREAD

**Issue by dch** [spf13/hugo#735]
It seems that having the standard go artifacts confuses non-programmers and programmers who've not used go before. No surprises there.

Can anybody share details on how the artifacts on github releases are built, then uploaded, and by whom (@spf13 I suppose)?

I would guess that tweaking this process so it produces e.g.:

- `hugo_0.12_windows_amd64.zip` contains `hugo.exe`
- `hugo_0.12_darwin_amd64.zip` contains `hugo` as an executable

would make newcomers' life a lot simpler.

**Comment by bep** [comment]
Questions fit better on

http://discuss.gohugo.io/
