### ISSUE TITLE
Hugo should exit with an error code in case of errors when building a website

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#740]
To help notify the user of problems when Hugo is run as an automated script on the web server, I think Hugo should exit with an error code if there are warnings/errors when building a website.

For example, due to a bug either in Hugo docs or in the source code, some error messages are displayed during a `hugo` run:

```
$ cd ~/git/hugo/docs
$ hugo
ERROR: 2014/12/26 Two or more menu items have the same name/identifier in "<map[interface {}]interface {} Value>" Menu. Identified as "Overview".
 Rename or set a unique identifier. 
ERROR: 2014/12/26 Two or more menu items have the same name/identifier in "<map[interface {}]interface {} Value>" Menu. Identified as "Ordering".
 Rename or set a unique identifier. 
0 draft content 
0 future content 
87 pages created 
15 tags created
0 groups created
in 214 ms
$ echo $?
0
```

The fact that the above returns an error code of 0 means that most automatic deployment scripts (except the really smart ones who grep strings like `ERROR` and `WARNING` in the `hugo` output)  would fail to detect any errors, leaving potential build problems undetected.

**Comment by alaska** [comment]
It seems like there are two solutions to this problem:
1. Audit the code, identifying all notable errors and setting a flag
2. Patch [jww](https://github.com/spf13/jWalterWeatherman) to (optionally?) track whether or not an ERROR, CRITICAL or FATAL has been emitted and then use that to determine exit code.

Number 2 is certainly the easiest solution, but it would necessitate an issue there. Thoughts?

**Comment by batmat** [comment]
+1. Critical IMO: finding potential 404 and so on ahead of deployment is certainly one pros of SSG. It would be great to have that.
Just found this issue after noticing I had used an incorrect relref but Hugo would not fail to deploy the site (automated, in my case, as @anthonyfok rightly points out as an example), hence not alerting me.
Thanks and congrats again for Hugo!

**Comment by bep** [comment]
I think this situation should be better after:

https://github.com/spf13/hugo/issues/1502

**Comment by phil-opp** [comment]
Is there any update on this? I want to update my page automatically via travis on every commit. But travis looks only at the exit status, so it happily deploys it even if many errors occured.

**Comment by bep** [comment]
@phil-opp see my last comment. What errors do you see that doesn't exit != 0 ?

**Comment by phil-opp** [comment]
Links to non-existing pages:

```
Started building site
ERROR: 2016/02/17 22:52:43 template_funcs.go:1167: No page found with path or logical name "does-not-exist.md".
0 draft content
0 future content
10 pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
in 10348 ms
```

**Comment by bep** [comment]
This should help fix this:

https://github.com/spf13/jWalterWeatherman/pull/10

/cc @spf13

**Comment by bep** [comment]
The maintainer of the log library we use seems to have abandoned it, so I have given up on that approach. I may revisit this later.

**Comment by phil-opp** [comment]
Isn't it owned by the same owner as hugo?

**Comment by bep** [comment]
>Isn't it owned by the same owner as hugo?

Yes.

**Comment by phil-opp** [comment]
Thanks a lot!
