### ISSUE TITLE
Add search to documentation

### ISSUE THREAD

**Issue by bjornerik** [spf13/hugo#753]
Some integration with Google search would be nice, so I don't have to do the `permalinks site:gohugo.io` dance all the time.

**Comment by anthonyfok** [comment]
Hello @bjornerik,

A Google Custom Search box has been added to the Hugo docs.

Unfortunately my changes to `docs/css/style.css` didn't seem to get deployed on the live gohugo.io website.  I have just added a temporary hack, i.e. adding the CSS internally to partials/header.html, to get the search box to show correctly on gohugo.io in the time being.

The way I did it was very basic and preliminary.  Feel free to make changes as you please.  :-)
