### ISSUE TITLE
HEAD: `.Site.Menus.x` empty if non-content added in front matter (sometimes?)

### ISSUE THREAD

**Issue by dunn** [spf13/hugo#757]
A recent commit has made it so that Hugo fails to recognize (some?) menus that are modified in front matter.

I made [a sample Hugo site](https://github.com/grumble/test-hugo/blob/master/content/hello/honk.md) showing this behavior.  Running `hugo server -w -v`, I get the following error:

```
ERROR: 2014/12/30 Error while rendering homepage: reflect: call of reflect.Value.Type on zero Value
```

I wouldn't need to be able to add arbitrary stuff to front matter if it wasn't for another limitation of Hugo: if one menu has advanced options in the front matter, then all do.  For example, [in this site](https://github.com/ucsbphil/philweb/blob/master/content/programs/undergrad/awards.md), I wish I could just do:

```
menu:
  ugrad
  main:
    parent: programs
```

But that throws a critical `mapping values are not allowed in this context` error.

I can't pointpoint which commit introduced this bug because the Go build process mystifies me—even when I `reset --hard` the repository to the `v0.12` tag and rebuild, `hugo version` still spits out `v0.13-DEV`.

**Comment by bjornerik** [comment]
@grumble what Go version do you use? (the output of "go version")

**Comment by grumble** [comment]
@bjornerik `go version go1.4 darwin/amd64`, installed with Homebrew.

**Comment by grumble** [comment]
This is sort of tangential, but I just noticed that while 

```
menu:
  whatever
```

works, this doesn't:

```
menu:
- whatever
```

Is that intended behavior?

**Comment by bep** [comment]
@dunn - a lot of water as floated under the bridge since this was opened. A lot of bug fixes, some related to menus. I cannot reproduce this. Can you with the latest version?

**Comment by dunn** [comment]
Works fine on 0.13 too; thanks for checking!
