### ISSUE TITLE
Unable to find Static Directory when copying assets from a theme

### ISSUE THREAD

**Issue by nathany** [spf13/hugo#759]
This is a little usability issue. Maybe it can be improved.

I removed some files from my `static` folder without thinking to leave a `.gitkeep` file. My [CI build](https://circleci.com/gh/go-fsnotify/fsnotify.org/6) logged this error message:

```
ERROR: 2015/01/01 Unable to find Static Directory: hyde in /home/ubuntu/fsnotify.org/static/
```

The result is it didn't copy over any of the assets from the hyde theme. In my case, this means those assets weren't deployed and missing from the server.

Two possibilities that could improve the situation:
* Just create the static directory if it's needed and missing.
* Make the ERROR into an actual error that does a log.Fatal / os.Exit(1) to fail the build.

**Comment by bep** [comment]
This just bit me, too. I vote for just create the static directory if missing.

**Comment by kzys** [comment]
I think creating the directory is unnecessary because some sites might not need any static files.

What do you think just warn it, but skip the error? That's what I did at #1498.

**Comment by nathany** [comment]
Having a warning instead of an error resulted in the issue in the OP (and the fact that my deployment process deletes removed files).

When I say `static/`, I should be saying the value of `staticdir`. I suppose if `staticdir = ""` it shouldn't create anything.

**Comment by nathany** [comment]
It wouldn't need to create the staticdir in every case. Just if the theme wanted to write files there.

An alternative would be to make `hugo new site` add .gitkeep files.

The problem is that the static folder needed to exist for the theme, but it wasn't checked into git because there were no files in it. This only matters when doing a build from a fresh git clone, as myself and others do via CI services.

**Comment by bep** [comment]
Isolated, this should be a warning (one could argue that most errors in Hugo should be warnings). But the fix should also handle the situation where a theme has a static dir and the main project has not. Because that currently fails.

**Comment by kzys** [comment]
On master, copyStatic() doesn't copy StaticDir on a theme when the project doesn't have StaticDir. That's what I fixed. However if a theme doesn't have StaticDir, Hugo skips the project's StaticDir which is unnecessary.

Let me fix the latter tonight.

**Comment by kzys** [comment]
Now I think that processing two directories on copyStatic() is not a good idea because how Hugo treats the errors from the function, is depends on the place.

On NewWatcher(), the errors have to stop Hugo, but on build() the errors are just warnings. What do you think having copyStatic(source) and calling it twice on each functions?
