### ISSUE TITLE
Partial ACE include fails in themes

### ISSUE THREAD

**Issue by bep** [spf13/hugo#763]
Given /partials/foo.ace:

`= include partials/foo.html .`

Works when the partial is in the project; it isn't found when it is in a theme.

This works in both cases:

`{{ partial "foo" . }}`

/cc @tatsushid

**Comment by tatsushid** [comment]
This is the limitation of template engines themselves (Ace, Amber etc.) function. Internally, theme template files are loaded by `hugolib/site.go#prepTemplates`. It loads theme template files with `theme` prefix so in this case, the real template name is `theme/partials/foo.html` in Hugo therefore you could refer it by `= include theme/partials/foo.html .`

`partial` template function knows that and tries to find it with both `partials/foo.html` and `theme/partials/foo.html` so it works but template engines don't know that so users have to specify the name with `theme` prefix.

To solve it, it is needed to rewrite `prefTemplates` to begin to find template files and build internal template trees from theme directory if it exists and next do them on layout directory and if the same template name (theme's one) already exists, overwrite it by layout's one. Now Hugo automatically use theme's if layout's doesn't exist so it would work but I can't predict how it affects other parts of Hugo.

**Comment by trombonehero** [comment]
Is this also why my Ace inner templates can't find `theme/THEMENAME/layouts/_default/baseof.ace`?

**Comment by bep** [comment]
@trombonehero hmm... no, if that's a fact it smells like a bug. My bug.

**Comment by trombonehero** [comment]
See https://github.com/spf13/hugo/issues/1215...

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by bep** [comment]
I will closes this as "will not fix". This have to be fixed in Ace and not here, and I'm not following up on that.

**Comment by robsaunders** [comment]
Wish I'd known this bug before I attempted to use hugo again... back to my custom rolled stuff I guess...

**Comment by jottr** [comment]
Thank god I found this comment before digging myself into the same rabbit hole that is templating in hugo.  
Thanks @robsaunders.
