### ISSUE TITLE
Impossible to use Internet Explorer conditionals

### ISSUE THREAD

**Issue by ePirat** [spf13/hugo#778]
I am trying the following to use Internet explorer conditional comments:

```
{{ "<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->" | safeHtml }}
```

and it causes the template to break.

**Comment by ePirat** [comment]
The issue there are the `"` in the comment. It would be great to somehow get the comments inside without the need to escape every single quote… This is really annoying as hell.

**Comment by ePirat** [comment]
Especially for a large amount this is annoying:

```
{{ "<!--[if lt IE 7]><html class=\"no-js lt-ie9 lt-ie8 lt-ie7\"><![endif]-->" | safeHtml }}
{{ "<!--[if IE 7]>         <html class=\"no-js lt-ie9 lt-ie8\"> <![endif]-->" | safeHtml }}
{{ "<!--[if IE 8]>         <html class=\"no-js lt-ie9\"> <![endif]-->" | safeHtml }}
{{ "<!--[if gt IE 8]><!-->" | safeHtml }} <html class="no-js"> {{ "<!--<![endif]-->" | safeHtml }}
```

**Comment by tatsushid** [comment]
According to http://golang.org/pkg/text/template/, '\`' (backquote) can be used to avoid such a too many backslash escape

**Comment by tatsushid** [comment]
Sorry I forgot to write where it was written at http://golang.org/pkg/text/template/. In "Example" section, there is a

    {{"\"output\""}}
            A string constant.
    {{`"output"`}}
            A raw string constant.

description.

**Comment by bjornerik** [comment]
This works fine:
```
{{ `<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->` | safeHtml }}
```

**Comment by ePirat** [comment]
Thanks, would be great if this could be mentioned in the docs, as there are normal quotes used.
