### ISSUE TITLE
Errors in partials are silently ignored, making them hard to find

### ISSUE THREAD

**Issue by snej** [spf13/hugo#787]
If there's an error processing a partial (e.g. a syntax error in the template, or a reference to a nonexistent page/site property…), the site generator ignores it and continues, without logging any error message.

To reproduce this: Edit a partial in any working blog and break it, for instance by changing an instance of `}}` to `}`. Then rebuild the site. No errors will be logged, and the site will be generated, but any HTML output by the broken partial will simply be missing.

This makes it very difficult and frustrating to debug partials, since if something's wrong you get absolutely no clue what it is or where it might be. I've been porting a Jekyll theme to Hugo today and ran into a lot of this.

The workaround is to replace `{{ partial "foo" .}}` with `{{template "theme/partials/foo" .}}` everywhere, since the `template` function _does_ report errors.

**Comment by bjornerik** [comment]
This has been fixed in the current master and will be available in the next release.
