### ISSUE TITLE
Content summaries don't actually include "Read More" links, contrary to docs

### ISSUE THREAD

**Issue by snej** [spf13/hugo#788]
The [documentation of content summaries](http://gohugo.io/content/summaries/) says:

>Content summaries provide links to the original content, usually in the form of a Read More link.

and

>...the summary content divider will be replaced with a Read More link. 

This doesn't actually happen in Hugo v0.12. `.Page.Summary` just contains the summary text itself, with no "Read More" at the end. Either this feature is missing, or the docs are out of date.

(The actual current behavior is nice in that it gives the theme designer more flexibility in how/whether to display the read-more link. However, one thing I don't think the theme template can do is determine whether or not there's actually more to read — if the full post is short enough that it didn't have to get truncated, then there shouldn't be a "read more" link at all, but I don't know how the logic in a template would be able to tell, unless there were a new property like `.Page.HasSummary`.)

**Comment by bjornerik** [comment]
I would say this is a documentation, @anthonyfok can probably fix that.

There is a undocumented field variable on page called `Truncated`. so you cold do:

```
{{ if .Truncated }}
<a href="">Read more </a>
{{ end }}
```

**Comment by snej** [comment]
Thanks for the tip!

**Comment by anthonyfok** [comment]
The docs have been updated, thanks to the great suggestions and ideas by @snej and @bjornerik.  Please feel free to comment (or ping me or make a pull request) if there is any remaining issue.  :-)
