### ISSUE TITLE
Doc issue: Hugo's feeds are not "Atom 2.0"

### ISSUE THREAD

**Issue by snej** [spf13/hugo#790]
The Hugo docs [say](http://gohugo.io/templates/rss/):

>Unlike other templates, Hugo ships with its own ATOM 2.0 RSS template.
...
>This is the RSS template that ships with Hugo. It adheres to the ATOM 2.0 Spec.

This is incorrect: the feed that Hugo generates is RSS 2.0. There's no such thing as Atom 2.0. (The feed does include a "self" link using an element from the Atom namespace, which is common, but that doesn't make it an Atom feed.)

**Comment by anthonyfok** [comment]
Hello @snej,

Thank you for your bug report and expert advice.  I have just removed the reference to "ATOM" in the docs, and this change will appear in my next push to the repository.

We will need a little bit more time to fix the related issues that you reported, but indeed, generating correct RSS 2.0 feed is great goal for the upcoming release.

Thanks again!
