### ISSUE TITLE
0.13 release?

### ISSUE THREAD

**Issue by tegola** [spf13/hugo#794]
Hello,
I'm testing a few static site generator, and I think I'm going to stick with Hugo because of its speed.
But I need to group a list of pages with a parameter (a "groupByParam" feature has been added after v0.12). Before setting everything up to compile the source by myself, I wanted to ask: when does 0.13 will be released?

Thanks

**Comment by bjornerik** [comment]
There is a discussion about this here:

http://discuss.gohugo.io/t/next-release/579

Questions and discussions fit better there.

**Comment by tegola** [comment]
Oops, sorry!

Thank you
