### ISSUE TITLE
Issue with nested shortcodes

### ISSUE THREAD

**Issue by bjornerik** [spf13/hugo#797]
I wrote this, so I'm to blame. But my suggested fix is simple.

Example:

```
{{% highlight go %}}
fmt.Println("foo")
{{< getGoCode >}}
{{% highlight go %}}

```

As it is now, the result of getCoCode will not get highlighted, as the shortcodes are rendered and processed separately.

I suggest they continue to do so, but make sure that the rendered result of getGoCode is part of the inner argument to highlight.

This means that the result of getGoCode will get a pass through Blackfriday (even if it is marked as "HTML"),  as it is part of hightlight's inner content.

Makes sense, @spf13 ?

**Comment by spf13** [comment]
This makes sense to me.
