### ISSUE TITLE
The default of `canonifyurls = true` got reversed silently since v0.11

### ISSUE THREAD

**Issue by anthonyfok** [spf13/hugo#802]
See discussion starting at http://discuss.gohugo.io/t/deployment-workflow/90/15

The current behavior found in v0.11, v0.12 and v0.13-DEV as of today, i.e. `canonifyurls = false` by default, is the exact the opposite of Hugo v0.10 and before, and of what is documented in http://gohugo.io/extras/urls.

So, assuming the "default reversal" isn't intentional, we need to do the following:

1. Investigate which exact commit caused this bug, this "default reversal".

2. Fix the source code to revert to the correct behaviour, i.e. `canonifyurls = true` by default.

3. Add a warning to http://gohugo.io/extras/urls (and a few other relevant places in the documentations) that v0.11 and v0.12 had buggy behaviour, recommending the end user to upgrade or to specify `canonifyurls` manually to obtain the desired behaviour.

**Comment by bjornerik** [comment]
`git blame` is nice:
62dd1d45

But I like this default, and there will be breaking changes with pre 1.0 versions.

**Comment by anthonyfok** [comment]
@bjornerik, you are awesome!  I haven't started looking yet, but I suspect I would have looked in the wrong place.  :-D

I must say I like the new default (i.e. `canonifyUrl = false`) too; the only problem was that the change was undocumented.

@spf13, I must ask you again.  :-)  Is the change to `canonifyUrl = false` in Hugo v0.11 intentional?  Or was it an oversight?  Which way we fix this issue depends on your decision.  (Either way is fine with me.)  :-)

**Comment by anthonyfok** [comment]
Wait, I forgot, it is not fixed yet.  Need to wait for @spf13 insight and decision on what the future default should be.  :-)

**Comment by bep** [comment]
@spf13 true or false?

**Comment by spf13** [comment]
I believe it was intentional. There's a much higher probability that I intentionally switched it and forgot to document it.  I also think it's the better default and should continue to be the case going forward.

**Comment by anthonyfok** [comment]
@spf13, Thanks for your clarification!  I guess the only thing left to do then is to make minor to the docs so the users know that the new default is the way to go now and in the future.  Will do that soon.

**Comment by bep** [comment]
@anthonyfok it could also be good to mention the new `hugo config` command. `hugo config | grep -i canon` is a pattern I will start to use.

**Comment by anthonyfok** [comment]
@bep Great point about `hugo config`!
