### ISSUE TITLE
BaseUrl not applied to src attributes of <img> tags generated in from markdown

### ISSUE THREAD

**Issue by bguiz** [spf13/hugo#803]
In `config.yaml`

    baseurl: http://bguiz.github.io/js-standards

I expect hugo to translated markdown content:

    ![](/img/foo.png)

Into this html:

    <img src="http://bguiz.github.io/js-standards/img/foo.png">

Or even this would work:

    <img src="/js-standards/img/foo.png">

... but it does neither, and outputs this instead:

    <img src="/img/foo.png">

How do I get image tags to take into account BaseUrl?

**Comment by bguiz** [comment]
I should add that it makes no difference whether or not a trailing `/` is present in `baseurl` in `config.yaml`

**Comment by bjornerik** [comment]
If you set canonifyurls to true in config, this should work.

The default value is false (which is opposite of what it says in the doc.)

**Comment by bguiz** [comment]
Thanks for the tip Bjørn - worked like a charm. The documentation
actually threw me off on this count!

W: http://bguiz.com

**Comment by bjornerik** [comment]
Good, close this as a duplicate of #802
