### ISSUE TITLE
3+ partials not possible?

### ISSUE THREAD

**Issue by jonaskac** [spf13/hugo#804]
Hello!
I've come across a weird problem. I'm not able to include more than 2 partials in a template. 
```
{{ partial "header.html" . }}
<---- html --->

{{ partial "footer.html" . }}
```
works fine, but 
```
{{ partial "header.html" . }}
{{ partial "topmeny.html" .}}
<---- html --->

{{ partial "footer.html" . }}
```
doesn't.

Haven't been able to figure this one out, and the only error that I get is:
> ERROR: 2015/01/18 Error while rendering homepage: html/template: "index.html" is an incomplete template

Independent of what command I run.

Any ideas?

**Comment by jonaskac** [comment]
Hmmm, managed to get rid of the error by rewriting the whole file. Might have been a hidden character. 

However, the error is really hard to read anything from, would be nice with something with a better output, or at least something pointing to the file where the problem is originating from. A stack-trace if possible would be great!

**Comment by bjornerik** [comment]
Usually these problems is due to the "." context changing.

Saving that context in a variable and pass it on makes it clearer.

And then there is the magic `$.` context.

See http://discuss.gohugo.io/t/templates-multiple-parameters/600/3 for related discussion.

**Comment by jonaskac** [comment]
@bjornerik thanks!
