### ISSUE TITLE
ref and relref doesn't respect plainIdAnchors

### ISSUE THREAD

**Issue by bjornerik** [spf13/hugo#813]
Setting `plainIdAnchors=true` breaks ref and relref.

/cc @halostatue

**Comment by halostatue** [comment]
:+1:

**Comment by yann-soubeyrand** [comment]
Hi,

Setting `plainIDAnchors = false`, ref and relref do not add unique ID at the end of anchors. Should I fill a new bug report or do you prefer reopening this one?

Regards
