### ISSUE TITLE
canonifyurl skip links on pages with schema-less links

### ISSUE THREAD

**Issue by bguiz** [spf13/hugo#816]
In my site generated using Hugo, canonify URLs works as expected on most pages, but in some pages it doesn't appear to apply. It sconsistenetly affects the same page(s), despite their front matter being structured similarly, and having no discernible difference.

For example, take a look at the left and right arrows (previous page and next page) navigation links on this page: http://bguiz.github.io/js-standards/angularjs/minification-and-annotation/

The previous page link is:

- http://bguiz.github.io/angularjs/manual-annotating-for-dependency-injection

But it should be:

- http://bguiz.github.io/js-standards/angularjs/manual-annotating-for-dependency-injection

Similarly, the next page link is:

- http://bguiz.github.io/angularjs/exception-handling

But it should be:

- http://bguiz.github.io/js-standards/angularjs/exception-handling

Because baseurl is `http://bguiz.github.io/js-standards/`

Now let's take a look at another page: http://bguiz.github.io/js-standards/

The previous and next links do indeed include the `/js-standards` section within the URL that was missing, and this is the case for all the other pages.

I am a little stumped because the the same template should theoretically render every page in a similar way, but it appears that all but one are rendered in this way instead.

The theme used is:

- https://github.com/bguiz/techdocshugotheme
- [previous page link in template](https://github.com/bguiz/techdocshugotheme/blob/master/layouts/partials/header.html#L60)
- [next page link in template](https://github.com/bguiz/techdocshugotheme/blob/master/layouts/partials/footer.html#L5)

My version of hugo is:

    $ hugo version
    Hugo Static Site Generator v0.13-DEV BuildDate: 2015-01-21T11:48:24+11:00

**Comment by bjornerik** [comment]
Thanks for the detailed report.

Looking at the code that does this -- I see two cases where a "page can slip throuch uncanonified":

If the pages contains links on the form `src="//somedomain.com"` or `href="//somedomain.com"` (and variations of these).

**Comment by bjornerik** [comment]
Looking at one of your samples I see `href="//github.com/olov/ng-annotate"` -- and the mystery is solved.

I mark this as a bug, but I'm not sure what the solution is. 

The current workaround is to always include protocol (http / https) in page links.

**Comment by bguiz** [comment]
Ah yes, thanks for doing the detective work for me. I was wondering what
the difference could have possibly been between this page and the rest, but
I would have never guessed the one you just pointed out.

Thanks once again!

W: http://bguiz.com

**Comment by tomnatt** [comment]
For the record, I've just spent the morning wondering why canonifyurl wasn't working, and it was because of this bug.

In our case it was from a common header, used in various places outside of this hugo site. We were using a protocol relative url for loading a webfont.

**Comment by bayne** [comment]
:+1: I ran into this bug twice also. It appears if the page contains a protocol-less link it will break the canonification on rest of the page.

**Comment by bep** [comment]
A patch that doesn't break down performance is welcome.
