### ISSUE TITLE
Page variables for Identifier and Name ignored

### ISSUE THREAD

**Issue by bguiz** [spf13/hugo#817]
In the documentation for menus, under the "Nesting" section:

http://gohugo.io/extras/menus/#toc_5

> The following order is used to determine identity Identifier > Name > LinkTitle > Title. This means that the title will be used unless linktitle is present, etc. In practice Name and Identifier are never displayed and only used to structure relationships.

This is excellent, and precisely what I need, because I have two different pages under different submenus, which I wish to generate, where they have the same name (but should have different identities).

However, when I insert either a `name` or an `identifier` to the front matter yaml of my page, it appears to ignored, an I continue getting the same error as before:

> ERROR: 2015/01/22 Two or more menu items have the same name/identifier in "main" Menu. Identified as "Comments".
> Rename or set a unique identifier.

Checking elsewbhere in the documentation, I find the list of accepted fields for the pages' front matter:

http://gohugo.io/templates/variables/#toc_0

- This list **does** include `.Title` and `.LinkTitle`
- This list **does not**, however, include `.Identifier`and `.Name`, which I expect it to

.. which does explain why it is getting ignored. 

Could we please get the method described in the "menu" documentation, "The following order is used to determine identity Identifier > Name > LinkTitle > Title" implemented please?

**Comment by bjornerik** [comment]
Thanks for the detailed report.

I will check this (as I have rumbled around in the menu code).

 `.Identifier` and `.Name` is mentioned in http://gohugo.io/extras/menus/ -- one could argue that since a `Page can be a menu item`, it also should be listed there, but ...

**Comment by bguiz** [comment]
Yeah, that would make sense - from reading the documentation I expect
to be able to set either .Identifier or .Name on a page.

Thanks for looking into this.
W: http://bguiz.com

**Comment by bjornerik** [comment]
Can I ask which Hugo version you are using (the output of `hugo version`)?

**Comment by bjornerik** [comment]
I'm not able to reproduce this the latest codebase.

Do you have any public project that reproduces this?

**Comment by bguiz** [comment]
13-DEV built off master as of yesterday

And yes http://github.com/bguiz/js-standards

I don't think that I committed name and identifier since they didn't work,
but you can take a look at

- content/es5/naming.md
- content/angularjs/naming.md

I would like to have both of these define the same linktitle in their front
matter, and simply have different values for identifier, but it doesn't
work, so I needed to define them with slightly different linktitle's.

**Comment by bguiz** [comment]
$ hugo version
    Hugo Static Site Generator v0.13-DEV BuildDate:
2015-01-22T11:46:04+11:00

W: http://bguiz.com

**Comment by bguiz** [comment]
Bjørn, I'm sorry, it looks like this was a mistake on my part. I re-read
your comment above, and it looks like my YAML was indeed incorrect.

W: http://bguiz.com
