### ISSUE TITLE
Could we cut a 13 release soon?

### ISSUE THREAD

**Issue by bguiz** [spf13/hugo#821]
The latest released version is 12, and in that version, there are a few things that have been fixed.

Currently, my pain point is that this thing in the template:

    {{.File.LogicalName}}

Causes version 12 to bug out and fail to render the remainder of the partial template it occurs within. This doesn't occur in version 13-DEV (lastest master), 
and I need to use Hugo in a setting where others wish to contribute content,
but simply want to use a built binary as opposed to installing golang and building from source.

... so new release please?

**Comment by bjornerik** [comment]
See http://discuss.gohugo.io/t/next-release/579
