### ISSUE TITLE
Failed to install via Homebrew

### ISSUE THREAD

**Issue by fireproofsocks** [spf13/hugo#824]
Is there some trouble-shooting magic I need to perform?  What to do if homebrew installation fails?

```
$ brew install hugo
Error: No available formula for hugo
````

**Comment by bjornerik** [comment]
I'm a Linux user, so no idea.

But in general, http://discuss.gohugo.io is a better place for questions.

**Comment by k4rtik** [comment]
I don't see any problem with hugo formula for hugo.

@fireproofsocks what do you get for `brew info hugo`? Have you tried updating brew?

```
$ brew info hugo
hugo: stable 0.12 (bottled), HEAD
http://hugo.spf13.com/
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/hugo.rb
==> Dependencies
Build: go ✔, bazaar ✔
```

**Comment by bjornerik** [comment]
If this still is an issue, post at http://discuss.gohugo.io i

**Comment by anthonyfok** [comment]
@fireproofsocks: Remember to run `brew update` before running `brew install hugo`.  ;-)
