### ISSUE TITLE
Code highlighting and asterisk

### ISSUE THREAD

**Issue by ksmigiel** [spf13/hugo#827]
I found issue with code highlighting used `{{% highlight %}}` block. If I try to put asterisk in math equation, for example:
```
List.map(fun x -> x * x)
```
asterisk disappears. But if I left code without highlight block, then asterisk is visible.
I tried also to escape with `\*` but it produces only weird `</span>` block.

Have I missed something with highlighting and Markdown syntax?

**Comment by bjornerik** [comment]
I'm pretty sure this is not an issue with Hugo 0.13-DEV (latest master), then you can say:

`{{< highlight >}}` => no markdown rendering

In 0.12 you may try:

```
<div>
{{% highlight %}}
{{% / highlight %}}
</div>
```
To "disable" markdown rendering of the block.

**Comment by ksmigiel** [comment]
In 0.12 it unfortunately doesn't work.

**Comment by bjornerik** [comment]
I have confirmed that this isn't an issue with 0.13-DEV.

A release should be around the next corner. If this is important, it is easy to build from source.
