### ISSUE TITLE
Error: no buildable Go source files in ... \dchest\cssmin

### ISSUE THREAD

**Issue by wadewegner** [spf13/hugo#832]
After running `go get -v github.com/spf13/hugo` and then `go build -o hugo main.go` from the Hugo folder I get the error:

    C:\Projects\Go\src\github.com\spf13\hugo\hugolib\handler_file.go:17:2: no buildable
    Go source files in C:\Projects\Go\src\github.com\dchest\cssmin

**Comment by wadewegner** [comment]
It appears git never pulled the files for `github.com/dchest/cssmin`. Once I did manually I had no problem with the build.

**Comment by anthonyfok** [comment]
Hi @wadewegner,

Sorry, I cannot reproduce this.  Let's try the following:

1. If you just want the `hugo.exe` binary file, the `go get` step would have already built it in `C:\Projects\Go\bin\hugo.exe`.

2. It may have been a glitch with the network that `github.com\dchest\cssmin` wasn't downloaded succesfully.  Please try `go get -v -u github.com/spf13/hugo` (note the `-u` flag) and see if that completes without error and see if you now have `C:\Projects\Go\bin\hugo.exe` if there wasn't one before.

3. After this, `go build -o hugo main.go` should work.  :-)

Oh, good, you found the solution!  :-)
