### ISSUE TITLE
Document pygments config

### ISSUE THREAD

**Issue by wadewegner** [spf13/hugo#840]
[This](http://gohugo.io/extras/highlighting/) documentation on highlighting doesn't explicitly show how to configure the config for toml, json, or yaml. It'd be good for the documentation to show explicitly how to set this up.

If someone will explain I'll gladly update and submit an pull request.

**Comment by wadewegner** [comment]
Ah, turns out it wasn't the config. I too got caught on the space between the {{ and % in the documentation. This helped: http://discuss.gohugo.io/t/pygments-howto/405

**Comment by wadewegner** [comment]
Getting strange output.

This ...

    {{% highlight bat %}}
        IF NOT EXIST "%WEBROOT_PATH%server.go" (
          cp server.go %WEBROOT_PATH%
        )

        IF NOT EXIST "%WEBROOT_PATH%go1.4.windows-386.zip" (
          cd /D %WEBROOT_PATH%
          curl -O https://storage.googleapis.com/golang/go1.4.windows-386.zip
          start unzip -o go1.4.windows-386.zip -d .
        )
    {{% /highlight %}}

... renders ...

![pygments](https://cloud.githubusercontent.com/assets/746259/5894878/974a662e-a4cc-11e4-9cfa-e28d3998e731.png)

Any idea why the `pre` and `code` tags are showing up?

**Comment by bjornerik** [comment]
Yes. But if indenting the inner code exacly 4 characters, I suggest wait for (or build from source) Hugo 0.13 and replace with

`{{< / highlight bat >}}`

**Comment by wadewegner** [comment]
Ah, thanks for some hints. I have built from source. What you wrote doesn't work exactly, but the following does work:

    {{< highlight bat >}}
    IF NOT EXIST "%WEBROOT_PATH%server.go" (
      cp server.go %WEBROOT_PATH%
    )

    IF NOT EXIST "%WEBROOT_PATH%go1.4.windows-386.zip" (
      cd /D %WEBROOT_PATH%
      curl -O https://storage.googleapis.com/golang/go1.4.windows-386.zip
      start unzip -o go1.4.windows-386.zip -d .
    )
    {{< /highlight >}}

![pygments2](https://cloud.githubusercontent.com/assets/746259/5904994/eaca3b44-a549-11e4-9c9a-c3a428b86622.png)

It would be nice to get confirmation that this is how it will continue to work moving forward.

**Comment by bjornerik** [comment]
Yes - we made a breaking change with the new "{{<" syntax (no Markdown processing) for 0.13-DEV. You can be as sure as sure can be in this software world that this will stay.

**Comment by wadewegner** [comment]
LOL, understood. Thank you @bjornerik!
