### ISSUE TITLE
installation from source fails

### ISSUE THREAD

**Issue by slimsag** [spf13/hugo#842]
Installing Hugo from source fails. `go get` reports (relevant parts only):

```
# github.com/spf13/hugo/helpers
src/github.com/spf13/hugo/helpers/content.go:92: renderParameters.HeaderIDSuffix undefined (type blackfriday.HtmlRendererParameters has no field or method HeaderIDSuffix)
src/github.com/spf13/hugo/helpers/content.go:109: undefined: blackfriday.HTML_SMARTYPANTS_ANGLED_QUOTES
```

**Comment by anthonyfok** [comment]
Hi @slimsag,

The dependent libraries fetched by your previous `go get github.com/spf13/hugo` run some weeks (?) ago are outdated.  In particular, new features that Hugo depends on have been added to the https://github.com/russross/blackfriday Markdown processor.  Please run:

    go get -v -u github.com/spf13/hugo

and try again.  Let us know if it works for you!

Cheers,
Anthony

**Comment by slimsag** [comment]
@anthonyfok Oh, my, apologies.

I had thought I was making you aware of a recent change with blackfriday -- but it appears I am the one out of date :smile: All is well :+1:

Cheers,
Stephen

**Comment by anthonyfok** [comment]
@slimsag, hehe, don't worry.  :-)

Yes, `blackfriday.HTML_SMARTYPANTS_ANGLED_QUOTES` is actually added by our own @bjornerik for the new smart angled quotes feature in the upcoming Hugo v0.13.  :-)
