### ISSUE TITLE
Hugo workflow (hugo & gulp.js). Just checking?

### ISSUE THREAD

**Issue by karland** [spf13/hugo#846]
I did not find much about `Hugo` & `gulp.js` so I am checking.

Here is my summary:

+ Hugo is fast on building Websites, but does not concern itself with any asset management.
+ For this one needs to employ a task runner, i.e. `gulp.js`

So what would gulp.js need to do:

1. Sass: `.scss` -> `.css`
2. Jade: `.jade`-> `.html` (this is valid for both pages and layouts). Jade instead of Haml because it handles the `{{`syntax nicely.
3. Coffee: `.coffee`-> `js`
4. Icons: generate `favicon.ico`, `apple-touch-icon.png`, `tile.png`, `tile-wide.png` form png-template
5. Images: optimize images
6. Fonts: copy/generate local fonts

`gulp.js` would need to take the source-files from a folder called, say, `src` and put the results into `themes\mytheme`. Actually, with this approach nothing would go into `themes\mytheme` manually but only by way of `gulp.js`

Then Hugo would do its work.

Finally `gulp.js` would need to apply hash-values to `.js` and `.css` files in the `public`-folder resulting from Hugo with something like `gulp-rev` & `gulp-rev-replace` and gzip them with `gulp-gzip`. Done. 

I suppose this is a pretty standard workflow, so I am wondering if anybody is already working along these lines or whether this is crossing paths with anything that is already been worked on.

Finally some observation concerning Markdown: currently `Hugo` is using `blackfriday`. I understand that this is a hardwired choice. Correct? I also understand that there are Shortcodes to overcome the shortcomings of markdown or the markdown engine. However, there are numbers of markdown engines around, such as [kramdown](http://kramdown.gettalong.org/) that extend the pure markdown capabilities and provide for very handy options. I think using such is much more handy then using Shortcodes (even though I like Shortcodes for not standard stuff). There is even a blackfriday fork written in Go that builds in a lot a very useful markdown extensions [mmark](https://github.com/miekg/mmark).

**Comment by bjornerik** [comment]
See http://discuss.gohugo.io/ - search for Gulp. Thats a better forum for questions/discussions.

But in general, you are right (I didn't understand the jade part, but that's me).

As to hardwired: Yes - this is Go and static linking all the way. The main rendering engine is Blackfriday (extremely fast and native go) -- there is one other (external tool), do not remember name and a 3 template engines (Go, Amber and Ace) ... If there are a good Go implementation of Kramdown or others, pull requests are welcome.
