### ISSUE TITLE
Fix defaults for Blackfriday

### ISSUE THREAD

**Issue by bep** [spf13/hugo#866]
A recent refactoring of the Blackfriday options seems to have messed up the default settings (fractions is turned off by default, should be on). Others?

**Comment by bep** [comment]
@naoina could you have a look at this? It's just the fraction flag that should be default true.

**Comment by naoina** [comment]
@bep I'm so sorry. I'll fix it and pull request soon.

**Comment by bep** [comment]
Seems like this is and "old" issue - and also was a problem with maps and default values in Viper.
