### ISSUE TITLE
Can we get a list of all the default config options and values?

### ISSUE THREAD

**Issue by ivanjuras** [spf13/hugo#871]
I was wondering if we could get a list of all the default config options and values for the config file.

For example, I'd like to know if there was a default option for changing the name of the "static" folder into a custom name. Current documentation only shows the options like contentdir, layoutdir etc.

It would be great if we could have all the options available to us in a single place.

**Comment by bep** [comment]
There's an option called StaticDir, default static.

And yes, there should be a list -- and it should be a "hugo command" -- "hugo config"? Sorted list?

**Comment by bep** [comment]
For now, you can look at the code:

Here is the latest config:
https://github.com/spf13/hugo/blob/master/commands/hugo.go#L113-L141

Here is version 0.12 (latest release version):

https://github.com/spf13/hugo/blob/v0.12/commands/hugo.go#L102-L123
