### ISSUE TITLE
Any way to create directories that are ignored at the compile time?

### ISSUE THREAD

**Issue by ivanjuras** [spf13/hugo#875]
I'm using Jade templating language with Hugo. Is it possible to create an folder inside of, let's say Layouts, that will be ignored when I run hugo?

I would create a folder called Jade inside Layouts, and the Jade folder automatically gets ignored at compile time, so that it doesn't even go into the public folder.

I only need this folder to put my Jade templates inside.

**Comment by bep** [comment]
Nothing in layouts will get included if it's not used by a template.

If you want something outside of Hugo, you could just create a my-jade-folder.

**Comment by bep** [comment]
More questions? http://discuss.gohugo.io/
