### ISSUE TITLE
Menus item missing .Url field since update to 13-DEV

### ISSUE THREAD

**Issue by bguiz** [spf13/hugo#877]
After running `go get -u github.com/spf13/hugo` to update, hugo started generating menus incorrectly - the `.Url` paramter was no longer accessible to the template and `{{.Url}}` getting rendered as an empty string.

The template used was identical to the example given in the docs: http://gohugo.io/extras/menus/#toc_6

This same template was working with a previous 13-DEV version of hugo from about 2 weeks ago, so it appears to be a regression.

P.S. What is the easiest way to downgard to an older version of hugo (installed on $GOPATH)?

**Comment by bep** [comment]
use `git log` ... pick a commit `git checkout <commit>`

**Comment by bguiz** [comment]
I have been going down the trial and error route, and it appears to
have occurred somewhere between d897b1e and ea72f15

.. will narrow this down further to pinpoint the exact commit which causes this

    $ cd $GOPATH/src/github.com/spf13/hugo
    # ...
    $ git checkout d897b1e8a7c537004c6332d1935862a9fb87318a
    Previous HEAD position was ea72f15... Correct wercker URL
    HEAD is now at d897b1e... Add missing assertion to trim-test
    $ go install
    # now it works properly

**Comment by bguiz** [comment]
@bep Binary searching by recompiling hugo at different commits
actually find one of your commits as having caused this issue:

Commit message:

commit 1b42dc572a0475596ffc64f8a9e0dbf8ec823094
Author: bep <bjorn.erik.pedersen@gmail.com>
Date:   Fri Dec 12 20:28:28 2014 +0100

    Fix RelPermalink() and Urls in menus vs canonifyUrls

    canonifyUrls=true, RelPermalink and baseUrl with sub-path did not work.

    This fixes that by adding a check for canonifyUrl=trues=true in
RelPermalink().

    So given

    - baseUrl "http://somehost.com/sub/"
    - the path "some-path/file.html"

    For canonifyUrls=false RelPermalink() returns "/sub/some-path/file.html"
    For canonifyUrls=true RelPermalink() returns "/some-path/file.html"

    In the last case, the Url will be made absolute and clickable in a
later step.

    This commit also makes the menu urls defined in site config
releative. To make them work with canonifying of ur

    Fixes #519
    Fixes #711


    $ git checkout bd1b019f8512f5c93d42d4b65785965b7b084d0b
    Previous HEAD position was ea72f15... Correct wercker URL
    HEAD is now at bd1b019... Handle empty front matter in archetype.
    FAIL

    $ git checkout 1b42dc572a0475596ffc64f8a9e0dbf8ec823094
    HEAD is now at 1b42dc5... Fix RelPermalink() and Urls in menus vs
canonifyUrls
    FAIL

    $ git checkout 743998306a02a683371caeac477501418894a8f5
    HEAD is now at 7439983... [Docs] Document the new (temp?) default
of `canonifyurls = false`
    PASS

    $ git checkout 60c6faa317d3a07d02effc86b4fe03c9bc84be98
    Previous HEAD position was 71fe85d... Try to fix mysterious test
failures on Travis
    HEAD is now at 60c6faa... Revert "Try to fix mysterious test
failures on Travis"
    PASS
W: http://bguiz.com

**Comment by bep** [comment]
@bguiz can you give a little more info? How is your menu configured?

**Comment by bguiz** [comment]
Sure thing, the project is here:

https://github.com/bguiz/angularity.github.io/tree/master/source-hugo

Copying relevant parts of the files:

`config.yaml`:

    canonifyurls: true

    menu:
      main:
        - Name: About
          Weight: 1000
          Identifier: about
        - Name: Getting Started
          Weight: 2000
          Identifier: start

Each markdown file:

    ---
    title: Roadmap
    linktitle: Roadmap
    identifier: about-roadmap
    date: 2014-12-15T13:43:03+11:00
    tags:
      - about
      - roadmap
    menu:
      main:
        parent: about
    prev: /about/intro
    next: /start/installation
    notoc: true
    weight: 1030
    ---


W: http://bguiz.com

**Comment by bguiz** [comment]
Oh yes, and you can find the full theme:

https://github.com/bguiz/techdocshugotheme
W: http://bguiz.com

**Comment by bep** [comment]
And which of the above commits works for you?

**Comment by bguiz** [comment]
commits up to 743998306a02a683371caeac477501418894a8f5 work
commit 1b42dc572a0475596ffc64f8a9e0dbf8ec823094 and onwards do not

.. so this error was introduced by that commit


    $ git checkout bd1b019f8512f5c93d42d4b6578596
5b7b084d0b
    Previous HEAD position was ea72f15... Correct wercker URL
    HEAD is now at bd1b019... Handle empty front matter in archetype.
    FAIL

    $ git checkout 1b42dc572a0475596ffc64f8a9e0dbf8ec823094
    HEAD is now at 1b42dc5... Fix RelPermalink() and Urls in menus vs
canonifyUrls
    FAIL

    $ git checkout 743998306a02a683371caeac477501418894a8f5
    HEAD is now at 7439983... [Docs] Document the new (temp?) default
of `canonifyurls = false`
    PASS

    $ git checkout 60c6faa317d3a07d02effc86b4fe03c9bc84be98
    Previous HEAD position was 71fe85d... Try to fix mysterious test
failures on Travis
    HEAD is now at 60c6faa... Revert "Try to fix mysterious test
failures on Travis"
    PASS

W: http://bguiz.com

**Comment by bep** [comment]
Yea, I hear what you're saying. But I'm not able to reproduce, not with your site, not with Hugo docs or any other site.

So you have to give me something more to work on: Like OS, Windows?

**Comment by bguiz** [comment]
> Yea, I hear what you're saying. But I'm not able to reproduce, not with
your site, not with Hugo docs or any other site.

That's strange, because I was able to consistently reproduce it using when
compiling hugo at different commits (mentioned above)

Here are all the specs I think could be relevant (let me know if you need
others):

- Ubuntu 14.04
- 64 bit
- go 1.4
- hugo 13-DEV (compiled from source)


    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:  Ubuntu 14.04.1 LTS
    Release:  14.04
    Codename: trusty
    $ uname -a
    Linux 3P-00667U 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43
UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
    $ go version
    go version go1.4 linux/amd64
    $ hugo version
    Hugo Static Site Generator v0.13-DEV BuildDate:
2015-02-05T14:17:37+11:00

W: http://bguiz.com

**Comment by bep** [comment]
I see it now.

You have commented out the baseurl in your config.

One could argue if a baseurl is needed - but in this case it is.

But it should be logged as an error.
