### ISSUE TITLE
There are no graphics in my blog

### ISSUE THREAD

**Issue by drpaneas** [spf13/hugo#884]
If I understood correctly, the "public" folder contains the required files for upload. When I upload them into my server, all I see is just plain text, no graphics, no colors nothing, like the CSS is not loading or something.

My workflow:
hugo new site myblog
cd myblog
hugo new about.md
git clone --recursive https://github.com/spf13/hugoThemes themes
hugo server --theme=hyde --buildDrafts

At the point, I have a local server, that renders the blog perfectly. All graphics, colors, fonts are absolutely fine.

the question is, how can I upload this blog on my server? I've tried by uploading the "public" folder, but no luck...

**Comment by bep** [comment]
In general, you will get faster answers on http://discuss.gohugo.io/

**Comment by anthonyfok** [comment]
This question was reposted and answered here:
http://discuss.gohugo.io/t/how-to-upload-my-hugo-blog-from-localhost-to-my-server/709
