### ISSUE TITLE
Hashmark in string

### ISSUE THREAD

**Issue by sajt** [spf13/hugo#888]
I using Hugo to generating HTML pages. My menu in my config.toml file. In the menu I like to use # for anchors. How can I use it? I tried:
url = "/team-and-mission\u0023press" // removed
url = "/team-and-mission#press" //removed
url = "/team-and-mission##press" //removed
url = "/team-and-mission#press" //error

What is the solution?

**Comment by bep** [comment]
The solution is to fix the bug. Thanks for the report.

**Comment by anthonyfok** [comment]
:+1:
