### ISSUE TITLE
safeHtml throwing ERROR: wrong type for value; expected string; got float64

### ISSUE THREAD

**Issue by thomasmodeneis** [spf13/hugo#889]
Hi,

I have the following problem:

tst_float64.md 
```
xyz blz bla 12.866.431; 27,3% xyz bla bla.
```

tst.html
```
{{ .tst64 | safeHtml }}
```

ERROR:
```
ERROR: 2015/02/10 Error while rendering page tst_float64.md: template: tst.html:32:59: executing "tst.html" at <safeHtml>: wrong type for value; expected string; got float64
```
Does anyone knows witch part should I look for possible solutions?
Thank you.

**Comment by bep** [comment]
I don't know where to look for the problem ...

What's `.tst64`?

Apparently a float64.

Maybe printf could work around this, but safeHtml should maybe accept more than just strings.

**Comment by thomasmodeneis** [comment]
.tst64 is just a field inside the .md file that contains a float64 in the middle of the string.
I will try printf as workaround when I get home, thanks for the tip.

**Comment by bep** [comment]
safeHTML now accepts "anything", including floats.
