### ISSUE TITLE
Grouping by (Custom) Page Field?

### ISSUE THREAD

**Issue by automatonic** [spf13/hugo#893]
How do i go about grouping content (in `templates/_default/section.html`) by `custom` (a custom param set in the content front matter)?

After reading the grouping documentation at: http://gohugo.io/templates/list/

I felt like I should be able to do something like:

```
      {{ range .Data.Pages.GroupBy "custom" }}
      <h3>{{ .Key }}</h3>
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Title</th>
            <th>Season</th>
          </tr>
        </thead>
        <tbody>
          {{ range .Pages }}
            {{ .Render "tr"}}
          {{ end }}
        </tbody>
      </table>
      {{ end }}
```

But obviously, there is more going on, as custom attributes bind at `.Params.custom`

I have tried:

```
{{ range .Data.Pages.GroupBy "Params.custom" }} .
```

And 

```
{{ range .Data.Pages.GroupBy ".Params.custom" }}
```

To no avail. I even managed to induce a panic with:

```
{{ range .Data.Pages.GroupBy "Params" }}
```

Now I am wondering...can this currently be done? Or would this be a new feature?

I can probably find another way to do this, but I was curious if there was an existing way, and I was just missing it?

**Comment by bep** [comment]
@tatsushid would now.

**Comment by tatsushid** [comment]
For grouping by user defining params, `GroupByParam` function can be used instead of `GroupBy`. It was introduced at https://github.com/spf13/hugo/commit/5e28606b84ef230914d0e63aebe3925364ee3966, after releasing 0.12 so you have to use the latest master branch to use the function

In this case, you can use it like following

```
{{ range .Data.Pages.GroupByParam "custom" }}
```

**Comment by automatonic** [comment]
Perfect. Thanks all!
