### ISSUE TITLE
Contribution Guidelines is counter-productive

### ISSUE THREAD

**Issue by kotp** [spf13/hugo#895]
[It](https://github.com/spf13/hugo#contribution-guidelines) states:

>> please ask in your pull request.

if you don't know how to get started testing.

It should not ask for a question, but should likely direct someone where to find the answers.

Then the real hard questions can be asked without getting everyone's attention for the basic things.

**Comment by scottcwilson** [comment]
I have done some doc updates and would be happy to do this but I'm not sure what the right verbiage would be.  Anyone have suggestions?

**Comment by bep** [comment]
I have read the docs and, anything can be improved, but I think it's fine as is. Go is new to many, and the pull request is a perfect place to get guidance and ask questions.
