### ISSUE TITLE
bufferpool/bufpool.go:21: undefined: sync.Pool

### ISSUE THREAD

**Issue by dtaht** [spf13/hugo#896]
I am unfortunately very new to go, and when I attempt to build "head" from your current git trees and installation documentation, I get:

go build -ldflags "-X github.com/spf13/hugo/hugolib.CommitHash `git rev-parse --short HEAD 2>/dev/null` -X github.com/spf13/hugo/hugolib.BuildDate `date +%FT%T%z`" -o hugo main.go
# github.com/spf13/hugo/bufferpool
bufferpool/bufpool.go:21: undefined: sync.Pool
make: *** [gitinfo] Error 2

**Comment by bep** [comment]
I believe sync.Pool was introduced in go 1.3.

So if `go version`says `go 1.2` you'll have to upgrade to 1.3 or 1.4.

**Comment by bep** [comment]
Further questions? See http://discuss.gohugo.io/
