### ISSUE TITLE
How to create bulleted list?

### ISSUE THREAD

**Issue by naveensrinivasan** [spf13/hugo#913]
I am trying to use hugo to create a bulleted list in the post like this using markdown.
*   Red
*   Green
*   Blue

It is not generating the bulleted list. How do I get a bulleted list in the generated html?

Thanks

**Comment by anthonyfok** [comment]
Hi @naveensrinivasan,

Blackfriday, the Markdown processor used by Hugo, needs a blank line between the proceeding paragraph and the start of the list.

So, this would work:

    Colors:

    * Red
    * Green
    * Blue

But this doesn't:

    Colors:
    * Red
    * Green
    * Blue

Hope this helps!

**Comment by naveensrinivasan** [comment]
Thank you! That answered my question.

**Comment by mohae** [comment]
You can also add two spaces after the line, instead of inserting the blank line prior to the bullet list.

**Comment by Avi-D-coder** [comment]
@mohae two spaces did not work for me.
```markdown
test  
- one
- two
- three
```
