### ISSUE TITLE
Hard wrap support in shortcodes

### ISSUE THREAD

**Issue by ghost** [spf13/hugo#923]
I'm a hard wrap person because I use Vim and it just makes more sense with it. One of the most interesting things about Hugo is that I can use Vim to write my content with it. Hugo doesn't really support hard wrap, though. You can get away with it without noticing because when hard wrapped content is put in an HTML `<p>` tag, browsers will join all the lines. But the moment you want to write a Front Matter title that's two lines long, or the moment you want to include long shortcodes, Hugo will throw errors. I don't have a lot of content so it's manageable but I could definitely see that being a problem for others or for me in the future. Here's an example of what Hugo understands:

```
{{% figure src="Lorem ipsum dolor sit amet, consectetur adipiscing elit." alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit." %}}
```

And here's what I would like it to understand:

```
{{% figure src="Lorem ipsum dolor sit amet, consectetur adipiscing elit." 
alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit." %}}`
```

Does that look like much work? I wish I could help but I have no idea.

Thanks!
Maxime

**Comment by bep** [comment]
Currently this works:
```
{{% figure src="Lorem ipsum dolor sit amet, consectetur adipiscing elit." 
alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit." %}}
```

This, however, fails:
```
{{% figure src="Lorem ipsum dolor sit 
amet, consectetur adipiscing elit."  alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit." %}}
```
Not sure why I put this restriction in there.

It can be fixed by removing the `\n` case here:

https://github.com/spf13/hugo/blob/master/hugolib/shortcodeparser.go#L429

PRs are welcome.

**Comment by maxime-michel** [comment]
Sorry I didn't double-check. You're right, the problem is when the quotes don't begin and end on the same line. What about the Front Matter though, why did you rename the title and not include it? Should I create another issue for it?

**Comment by bep** [comment]
I think I remember the reason for having that \n check in there:

If you forget the right quote, and don't have any other checks, the parser will run until EOF before it fails.

Not sure if that's a big deal or not.

**Comment by bep** [comment]
I changed the title to scope it as I saw it. The front matter is a different issue, and I think you have to live with the spec of TOML YAML and JSON.

**Comment by maxime-michel** [comment]
Regarding the front matter, I've found [this](http://discuss.gohugo.io/t/new-line-in-toml/230/). Is there a reason this doesn't work with v0.13 for me?

**Comment by bep** [comment]
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.
