### ISSUE TITLE
Different list templates

### ISSUE THREAD

**Issue by palpinter** [spf13/hugo#928]
Hi dear members,

Firstly, i'm not a programmer so please handle me with care. :)

My problem is the follow.
1. I've created a blog with Hugo. It is OK.
2. I've created the list.html and single.html templates. It is OK.
3. I want to see my post with different views. E.g "group by date" or "group by param". And I would like these lists from menu. But I have only one list template: "list.html".
4. I've read the whole documentation 100 times, but I haven't found the answer.

Is it possible or not at all? If yes how?

Thx!

**Comment by bep** [comment]
In general, I think you will get faster/better response to questions like this on http://discuss.gohugo.io/
