### ISSUE TITLE
Would like error if highlighter (Pygments) doesn't run

### ISSUE THREAD

**Issue by nathany** [spf13/hugo#932]
I'm having a strange issue on my [Circle CI builds](https://circleci.com/gh/luanova/luanova.org/tree/master) that I'm still trying to track down. When building with a clear cache everything works fine, but when the hugo binary was cached it's not running Pygments for some reason.

It's odd because "pygmentize -V" still works.

Hugo doesn't indicate that Pygments isn't running. So I end up deploying to production with all the {{ highlight }} blocks still present and a jumbled mess.

It would be nice if this failed with an error.

**Comment by nathany** [comment]
It looks like I'm falling back to hugo 0.12 when cached. That's probably why pygments isn't working (though I thought it was supported back then too).

**Comment by bep** [comment]
I'm not totally clear about what "cached" means?

**Comment by nathany** [comment]
Cached by Circle CI. I cache the installation of Hugo so it doesn't need to be installed the next time. I'm not sure why it has an old version, but I'm figuring that out now.

The real issue isn't with Hugo, but I put this here because of the error reporting not being great. (but maybe that is just with an older version?)

**Comment by nathany** [comment]
Maybe this could be improved alongside making the syntax highlighter more explicit? 

`highlighter = "pygments"`

(as mentioned at https://github.com/spf13/hugo/issues/362#issuecomment-76537518)

**Comment by nathany** [comment]
I think I'll just close this. We can always open a new issue that is clearer.
