### ISSUE TITLE
Hugo inserting empty paragraph tags between shortcode instances

### ISSUE THREAD

**Issue by H4tch** [spf13/hugo#935]
I have content that is basically a list of shotcodes that define small peices of content. Something like this:

    {{< list_item text="This is some text" date="28 Feb 2015" >}}{{< /list_item >}}
    
    {{< list_item text="Second item" >}}{{< /list_item >}}

When there is a space between the two instances, Hugo generates an empty pagraph `<p></p>` element between them.

I'm using Bootstrap for each list element, but they are not being connected due to the empty tags between them.
I can work around the issue by removing the empty lines between the shortcodes.

**Comment by alaska** [comment]
Does this behavior occur with the {{% tag as well?

**Comment by jtolds** [comment]
It seems to, yes

**Comment by bep** [comment]
Duplicates #1148

**Comment by matthewdolman** [comment]
I'm not sure that this is a duplicate of referenced issue.

The issue that you referenced indicated that the figure was erroneously outputting:

<p>
<figure></figure>
</p>

However the issue that I am seeing is:

<p></p>
<figure></figure>
<p></p>

**Comment by bep** [comment]
@matthewdolman what do you see? :-)

**Comment by matthewdolman** [comment]
Sorry my bad, when I looked at the source it is actually just embedded in <p> </p>

The inspect element in Chrome automatically added extra ones.  The issue still stands though, I downloaded Hugo today and so I assume I'm working on the latest version.

**Comment by bep** [comment]
@matthewdolman it would be nice if you could finish your sentences. *What* is embedded in *what*?

**Comment by matthewdolman** [comment]
lol sorry just reread my last post...think my brain was running faster than my fingers.

I looked in inspect element and it appeared that the output html looked like thsi:

<p></p>
<my shortcode stuff>
<p></p>

But this was just how chrome was rendering it.  When I looked at the source it was:

<p>
<my shortcode stuff>
</p>

Which is why this is actually a duplicate of the other issue.
