### ISSUE TITLE
Add org-mode support

### ISSUE THREAD

**Issue by eggcaker** [spf13/hugo#936]
is possible to write content with org-mode markup ? then compile with pandoc or something else ?

**Comment by bep** [comment]
Use http://discuss.gohugo.io/

**Comment by priyadarshan** [comment]
I'm sure many would be interested. For now, I have found this: http://www.personal.psu.edu/bam49/notebook/org-to-hugo/

**Comment by bep** [comment]
See #333

**Comment by digitalcraftsman** [comment]
This issue is more or less a duplicate of #1483 since both request the support for orgmode. This request the support via a third-party tool (pandoc), #1483 suggests to use a Go-native application.
