### ISSUE TITLE
Handling of # in URLs has changed

### ISSUE THREAD

**Issue by yacoob** [spf13/hugo#938]
In Hugo 0.12, titles containing `#` got this character stripped on the way to URL. For example, [this Markdown file](https://github.com/yacoob/gcu-hugo/blob/master/content/post/2015-02-15.rg-exia-wip-1.md) specifies:

```yaml
date: 2015-02-16T22:58:10Z
title: "RG Exia WIP #1"
```

In Hugo 0.12, the resulting URL is: `/2015/02/rg-exia-wip-1/` as seen [here](http://gcu.tactical-grace.net/2015/02/rg-exia-wip-1/). In Hugo 0.13, the resulting URL is `/2015/02/rg-exia-wip-%231/`. This is, technically correct, but as such is changing the URL that have been generated earlier, breaking all existing incoming links. This kind of regression should not happen.

This error was discovered by me, when I run Hugo 0.13 on my blog data. Sure enough, I can add aliases to all affected posts, but it's neither easy nor expected. :)

**Comment by bep** [comment]
See #888

In my eyes, this was a bug fix and not a regression. One could maybe handle both cases.

With 0.1* versions there will be breaking changes, but they should be documented.

**Comment by yacoob** [comment]
Sure, that's why I said that it's technically correct :) For my site I've added `slug` fields. Given that it's considered a proper behavior, I take it we can close this bug? 

I don't like it, as IMO autogenerated slugs shouldn't contain `#` - this character is for delimiting the fragment and ends up being encoded, which looks bad. But that's just my opinion.
