### ISSUE TITLE
404 page gets prettified

### ISSUE THREAD

**Issue by yacoob** [spf13/hugo#939]
Looks like a repeat of #415. My `layouts/404.html` gets rendered to `public/404/index.html`. [Documentation](http://gohugo.io/templates/404/) says it should work. It was rendered correctly in Hugo 0.12, it broke in 0.13.

**Comment by anthonyfok** [comment]
The fix for #415 might have gotten undone in commit 7b960ac121fa8cdbd9b52c4f2adf66d39440758e, but I haven't tested it yet.

**Comment by anthonyfok** [comment]
Nope, I was wrong.  `public/404.html` still gets correctly generated in 7b960ac, so that is not it.

**Comment by anthonyfok** [comment]
Finally learned `git bisect` and used it for the first time.  ;-)  Result:

```
$ git bisect good
8db3c0b0a677a6b122ad5a396ee52b074acb7e87 is the first bad commit
commit 8db3c0b0a677a6b122ad5a396ee52b074acb7e87
Author: spf13 <steve.francia@gmail.com>
Date:   Fri Jan 30 12:05:05 2015 -0800

    page rendering and writing using BBP

:040000 040000 e7986d26bc4ba4e66b8b519c01ef8a79f60b72ef d664ac7b265c15f55c57c63e784ec173245e41bf M	hugolib
```

(Assuming I didn't goof up, haha!)

**Comment by yacoob** [comment]
Very nice, thanks a lot for this fix.
Perhaps add a test to make sure it doesn't blow up in the future?

**Comment by bep** [comment]
@yacoob the code is there for everyone to fix. Pulll requests with tests are always welcome.
