### ISSUE TITLE
Improve terms in docs

### ISSUE THREAD

**Issue by Boycce** [spf13/hugo#942]
I have picked up past frameworks / API's faster with alot more functionality. I think the docs / terminology needs to be re-thought with more distinctive names. 
***e.g layouts, sections, types, views*** 
Also less ambiguous explanations and contextual examples.

**Comment by bep** [comment]
Pull requests in the Doc sections are always welcome!

**Comment by spf13** [comment]
We would certainly love any help you could provide here. I'm sure even a small effort would go a long way for all the users. 

If you want to discuss this with the other users and colloborate on possible names the best place to do that is the forum http://discuss.gohugo.io.

**Comment by bep** [comment]
Closing as stale.
