### ISSUE TITLE
hugo ignores baseurl

### ISSUE THREAD

**Issue by john-qin** [spf13/hugo#943]
I am using hugo to create a personal blog and host it using github.

in config.toml,  I defined baseurl

baseurl = "http://john-qin.github.io/"

then I ran hugo command to generate static pages in public folder

hugo server --theme=casper

here's the problem, I checked all the static pages,  they are still using localhost:1313 as baseurl, not the one I defined in config.toml.  How can i fix it?

**Comment by john-qin** [comment]
fixed it. closed

**Comment by mattyw** [comment]
I'm having this problem - what were you doing wrong?
