### ISSUE TITLE
description -> Description

### ISSUE THREAD

**Issue by yageek** [spf13/hugo#946]
I use hugo 0.12 and the `hyde` theme. By following the docs about variable and lowercase I wrote:
    [params]
      description = "Tesla's Awesome Hugo Site"
      author = "Nikola Tesla"

But it seems that the `description` variable is not used, To make it working I have to write:
    [params]
      Description = "Tesla's Awesome Hugo Site"
      author = "Nikola Tesla"

Edit: same issue with 0.13

**Comment by mdhender** [comment]
It's not clear what's happening. The file `tpl/template_embedded.go` refers to both `Description` and `description`:

```<meta itemprop="description" content="{{ with .Description }}{{ . }}{{ else }}{{if .IsPage}}{{ .Summary }}{{ else }}{{ with .Site.Params.description }}{{ . }}{{ end }}{{ end }}{{ end }}">
```

@yageek, can you give an example of how you're using it in your template, please?

**Comment by yageek** [comment]
@mdhender Sorry for the delay. You can see the sources here: https://github.com/gophersch/gophersch-hugo

**Comment by mdhender** [comment]
Checking to see if this is fixed by #2740 and relatives.

**Comment by mdhender** [comment]
Confirmed that is is. Can be closed.
