### ISSUE TITLE
Cross reference path issue on Windows

### ISSUE THREAD

**Issue by bep** [spf13/hugo#957]
Building Hugo docs on Windows:

```
ERROR: 2015/03/07 No page found with path or logical name "overview/configuration.md".
ERROR: 2015/03/07 No page found with path or logical name "extras/crossreferences.md".
ERROR: 2015/03/07 No page found with path or logical name "extras/crossreferences.md".
ERROR: 2015/03/07 No page found with path or logical name "extras/crossreferences.md".
ERROR: 2015/03/07 No page found with path or logical name "extras/crossreferences.md".

```

**Comment by halostatue** [comment]
I have a suspicion as to what is going on with this, but I do not have a Windows machine to test this on. The “name” of this file on Windows is *probably* `extras\crossreferences.md`. Ideally, when Hugo is creating the filename internally, it would normalize it to the forward-slash format and handle the Unix/Windows conversion as necessary. This may be something that @spf13 can fix in Afero and Hugo would just benefit.

**Comment by halostatue** [comment]
We could also write a modification to the comparison such that it would check for `/` or `\` in the filename. That would cost a little bit of processing time when comparing these, but it means that cross-references would be cross-platform.

**Comment by bep** [comment]
Afero is just an abstraction of the file system -- fixing it there would be a hack.

The processing time isn't a factor here.

A pull request with test case would be checked out on Windows.

**Comment by halostatue** [comment]
Depending on where Afero sits with handling files, I think it’s *exactly* the right place to put this—but I may not understand where Afero sits. Basically, at some point, we should give users of Hugo a guarantee of “this is the filename” and it will work regardless of whether the underlying OS uses `/`, `\`, or `:` or something else entirely to separate path components. If that’s what Afero is supposed to do, then it should probably provide that unified view. If it isn’t…then it gets hacked into Hugo.

**Comment by bep** [comment]
Yea, well. Maybe. As long as it gets fixed.

**Comment by bep** [comment]
It should be fairly straight forward to wrap this to create a "file path cleaned" version:

https://github.com/spf13/afero/blob/master/os.go

It could even be put in the Hugo project.

Good idea, @spf13 ?

**Comment by spf13** [comment]
I think it's a great idea. Could go in either afero or Hugo, whichever makes the most sense

**Comment by bep** [comment]
I suggest we add it here (where we have Windows-testing setup) - then consider moving it to aero once it is solid.

**Comment by bep** [comment]
Never mind, the path-cleaning abstraction I thought about would not help this issue - the File object is created by the os package ... and not something I wans to fool around with.
