### ISSUE TITLE
 BaseUrl vs BaseURL, DocumentId vs DocumentID etc.

### ISSUE THREAD

**Issue by bep** [spf13/hugo#959]
The most important thing is being consequent, and that looks good - but Golint suggests using all caps for these abbreviations:

http://goreportcard.com/report/spf13/hugo

I guess the only reason to to lowercase these is in languages with automated getter/setter generation (read Java).

Fix it or let it be?

**Comment by anthonyfok** [comment]
I think it would be fun and great to fix it.  :smile:

But let's hear from others too.  Perhaps @spf13 could chime in?  :wink:

**Comment by spf13** [comment]
I would follow golint's suggestion on those. I think that the all caps as show reads best. How much would this impact users?

**Comment by bep** [comment]
I would say "very little impact" on users, but I'm not totally sure.

But it's better to do it now than kick ourselves in the legs later on.

If @anthonyfok can do the work (suggest using an IDE with a rename function, like liteide) and do it in a pull request, then we can do some testing and see if we have to put in a temporary "alias or two".

**Comment by anthonyfok** [comment]
Hi all,

This is the first commit that I came up with.  This should be rather safe, as I purposely avoided the command-line flags (cobra and pflag?) as well as struct fields like `BaseUrl` and `Url` that are used in Go HTML templates, to avoid breaking compatibility with existing scripts.

Creating aliases for template *functions* are as simple as adding an extra entry to the FuncMap, e.g. `GetJson` and `GetJSON` both work.  But what about template struct fields?

And, in addition to  `--baseUrl=http://example.com/', do we want to support `--baseURL` and `--baseurl` too?  Or should we make these long flag names case-insensitive?  (Or not?)

Many thanks!

**Comment by spf13** [comment]
I think all flag names should be case insensitive personally.

**Comment by anthonyfok** [comment]
Great minds think alike!  :wink:  <grin, duck, run>

Does that mean we need to patch https://github.com/spf13/pflag?
(I took a quick grep ("upper", "lower", "sensi") and didn't find anything in the upstream https://github.com/ogier/pflag either.)

**Comment by spf13** [comment]
Correct. 

Steve Francia
spf13.com
@spf13

**Comment by bep** [comment]
I have boldly merged the PR. Looked and tested OK by me.

As to the template funcs (getCsv, getCSV) I suggest add a "deprecated decorator func" that logs an error (so it shows up) that says: Fix this, this will be removed in the next version.

**Comment by anthonyfok** [comment]
Just a quick status update:

Thanks to our group effort, the transition (e.g. `BaseUrl` → `BaseURL`) in the Hugo code is essentially complete, and the docs updated.

What remains to be done is to add an option to allow `pflag` to accept case-insensitive long flag names.  A feature request has just been filed at ogier/pflag/issues/18.  Hope someone from our community can submit a Pull Request!  :-)

(Keeping this issue open until case-insensitive long flag names are implemented.)

**Comment by spf13** [comment]
We use a fork of pflag. The right place for this is at spf13/pflag

--
Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

**Comment by anthonyfok** [comment]
Sorry about that!  Due to a somewhat peculiar design of GitHub, I was unable to file an issue at https://github.com/spf13/pflag, though filing pull requests are perfectly fine.  So being a bit lazy (as I won't be able to produce a patch in the near future), I went ahead and filed the issue at https://github.com/ogier/pflag/issues instead.  Sorry about that!

**Comment by eparis** [comment]
I pay attention in spf13/pflag, but rarely in ogier, since that repo is typically dead.  But we already have support for this! (Well you can already do it)

Since you are using hugo (which I believe in turn uses spf13/cobra and spf13/pflag) you can check out the "normalized name" support. It allows you to write your own custom function which in your case could translate all flags to lowercase.

https://github.com/spf13/cobra/blob/master/command.go#L158
https://github.com/spf13/pflag/blob/master/flag.go#L184

It is being used in kubernetes to turn `flags_like_this` into `flags-like-this` so we have a consistent `-`

**Comment by eparis** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/flags.go#L25 Is the function we use in kube for `_` to `-`

With https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L125 as an example of applying the function.

**Comment by bep** [comment]
@anthonyfok ^

**Comment by anthonyfok** [comment]
Thanks for the heads up, @bep.

And special thanks to @eparis for writing the "normalized name" feature in Cobra, and for showing us how it is used.  :-)

I have made a preliminary Pull Request #1415, adding `helpers.NormalizeHugoFlagsFunc()` to handle flag name changes.  I initially thought of making all long flags case-insensitive with the help of `strings.ToLower()`, but then it would turn all long flags into lowercase, e.g. `--buildDrafts`, `--pluralizeListTitles` etc. becoming `--builddrafts`, `--pluralizelisttitles`, making them harder to read and less pretty.

So, I have decided to be more conservative with this pull request, i.e. only allowing `--baseUrl` in addition to the new canonical `--baseURL`, and disallowing other variations like `--baseurl` and `--BASEURL`.  If we relax the rules too much now, it would be hard to tighten the rules again without breaking end users' scripts.

If PR#1415 needs improvement, please do not hesitate to let me know.  For example, I wondered if helpers/general.go were the right place to add the `helpers.NormalizeHugoFlagsFunc()`, etc. etc.

Once PR #1415 or its iteration is committed, there are two more patches that I would like to commit:

1. Complete the Url-to-URL transition in tests: anthonyfok@d7f2ec3
2. Complete the Url-to-URL transition in docs: anthonyfok@d793ad0

What do you think?

**Comment by anthonyfok** [comment]
I think we have accomplished the goals originally set out for this issue.  Let's close it!  :-)
