### ISSUE TITLE
Loop through .Data.Pages inside single.html

### ISSUE THREAD

**Issue by Boycce** [spf13/hugo#960]
Is there anyway to loop over the pages in a section on single.html? I want to achieve a simple sidebar on all post pages.

```
{{ range first 10 .Data.Pages }}
  <li>{{ .Title }}</li>
{{ end }}
```

**Comment by bep** [comment]
Please use http://discuss.gohugo.io/ for questions.

Or look in the doc.

**Comment by Boycce** [comment]
Ok thanks, i'll post there.
