### ISSUE TITLE
eq has problems operating on range's index since 0.13

### ISSUE THREAD

**Issue by yacoob** [spf13/hugo#961]
Create a new site, set theme, create three posts.
Add this simple template at `section/post.html`:
```
{{ $count := sub (len .Data.Pages) 1 }}
<h1>$count = {{ $count  }}</h1>
{{ range $index, $value := .Data.Pages }}
index = {{ $index }} and
(index == $count) is {{ eq $index $count }}<br>
{{ end }}
```
With hugo 0.12 I get this expected output:
```
$count = 2

index = 0 and (index == $count) is false
index = 1 and (index == $count) is false
index = 2 and (index == $count) is true
```

With hugo 0.13 and beyond, I get this unexpected output:
```
$count = 2

index = 0 and (index == $count) is false
index = 1 and (index == $count) is false
index = 2 and (index == $count) is false
```

Same thing happens if I replace `$count` in comparison with a fixed number. There seem to be something wrong with `$index` itself and the way `eq` uses it :(

**Comment by bep** [comment]
The implementation of Eq hasn't changed (reflect.DeepEqual(x, y)) and range is also a Go construct, so something in Go must have created this.

**Comment by bep** [comment]
OK, I see what happened:

The signature of add changed from int to int64.

@tatsushid may have some insight.

**Comment by tatsushid** [comment]
OK, I'll check it tonight.

**Comment by tatsushid** [comment]
As you mentioned, it's related to changing math functions return types. I'll send PR

**Comment by yacoob** [comment]
Thanks for a quick fix!

**Comment by sebz** [comment]
Hi guys, I've just switch to 0.13 and I am also impacted.
Is there a workaround or should I wait for 0.14 to get the fix...? If it is the latter, when do you plan to release it?

Thanks :)

**Comment by bep** [comment]
@sebz there was a workaround posted on the discuss forum a while ago. Cannot remember what, but believe it was to do a dummy operation on the result of sub to convert it into an int ...

**Comment by sebz** [comment]
In fact I get the error with `mod` instead of `sub`, I was assuming that it was the same issue.
Anyway, I'll search on the forum and make some tests.

Thanks @bep !

**Comment by sebz** [comment]
Did not find it on the forum (just found a thread where you point toward this issue).
But doing the dummy operation trick ( adding 0 to the `mod` result) does the job for me!

Thanks again :+1:

**Comment by bep** [comment]
@sebz Good -- but in your case you could also use `modBool`, which does not suffer from this issue.

**Comment by sebz** [comment]
OK, thanks for the tip.
