### ISSUE TITLE
Change redirect documentation to aliases

### ISSUE THREAD

**Issue by xaprb** [spf13/hugo#962]
As per http://discuss.gohugo.io/t/what-does-the-redirect-front-matter-setting-do/111, the "redirect" variable mentioned in front-matter needs to be updated to reference aliases.

**Comment by ehammond** [comment]
Yep. It's still there in the docs and it confused me.

**Comment by anthonyfok** [comment]
Sorry for the delay and the confusion.
An update to the documentation, changing `redirect` to `aliases`, is forthcoming.

**Comment by ehammond** [comment]
Thanks!
