### ISSUE TITLE
Hugo should ignore vim bkp files in layouts/

### ISSUE THREAD

**Issue by yacoob** [spf13/hugo#964]
Just noticed that since 0.13 hugo started to try to parse bkp files left behind by vim:

```
ERROR: 2015/03/08 template: section/post.html~:16: undefined variable "$pages"
```

It doesn't seem to be breaking things, but it's a sign that hugo is reading unnecessary files.

**Comment by anthonyfok** [comment]
Hi @yacoob,

Prior versions did the same thing actually.  The only difference is that the errors encountered when parsing these templates are now shown since in v0.13.  :wink:

This has just been fixed with a quick patch.  Please test.

Cheers,
Anthony

**Comment by yacoob** [comment]
Yup, works great. Thank you! :)
