### ISSUE TITLE
Add function to look up URL for paginated content

### ISSUE THREAD

**Issue by yacoob** [spf13/hugo#965]
Right now for every post on my blog I include a link to an archive containing that post. Example: [this post](http://gcu.tactical-grace.net/2014/08/wild-led-strip-appears/) links to [particular section of archive page](http://gcu.tactical-grace.net/post/#wild-led-strip-appears). I'd like to use pagination for the archive, while preserving this functionality.

Once my archive is paginated, I need a function that I can use in `layouts/single/post.html` that would allow me to "find" this particular page in the Paginator object. Sadly, it looks like I can't even instantiate Paginator object for a normal content page. Upon encountering:

```
{{ $pages := .Paginator.Pages  }}
```

hugo throws an error:

```
ERROR: 2015/03/08 template: partials/prevnext.html:10:23: executing "partials/prevnext.html" at <.Paginator.Pages>: error calling Paginator: Paginators not supported for content pages. in partials/prevnext.html
```

(`partials/prevnext.html` is a partial template used inside `layouts/single/post.html`)

I guess it's working as intended - but it'd be very useful if can do what I've described above.

**Comment by bep** [comment]
It works as (I) intended, but I think I understand what you want.

I guess a `FindPaginator` or something method would do.

The question is what to use as key.

FindPaginator("home") for home page
FindPaginator("tags/mytag") for taxonomies ... maybe.

**Comment by bep** [comment]
It works as (I) intended, yes. I understand what you want, it might be a chicken and egg problem implementing it, but I agree - it could be useful to add a finder for paginators.

**Comment by yacoob** [comment]
One extra comment about the implementation - the main problem as I see it is that there can be many different `Paginator` objects, and for an arbitrary piece of content it might be hard to decide what `Paginator` should be used for the lookup. Perhaps it'd make sense to allow creating `Paginators` in non-pagineable layouts, just for the purpose of the lookup?

**Comment by bep** [comment]
There are len(nodes) paginators. Finding them requires having a key:

* Home page => find("home")
* Taxonomies => find("tags/mytag")

??

**Comment by yacoob** [comment]
There are also custom paginators (ie. example from docs with `where`). But having the default one would be good to begin with :D 

Paginator on Page would not paginate anything - it'd be just an object that can be used in a template to look up current page in it.

**Comment by bep** [comment]
There is only one paginator per node, either custom or default.

**Comment by bep** [comment]
Please restart this discussion at http://discuss.gohugo.io/. I'm not sure what this is about, a clear sign that more minds are needed.
