### ISSUE TITLE
how to install hugo

### ISSUE THREAD

**Issue by swortain** [spf13/hugo#968]
I run the command 

> export GOPATH=$HOME/go
  go get -v github.com/spf13/hugo

and I get the infomation

> github.com\spf13\hugo (download)
bitbucket.org\pkg\inflect (download)
github.com\BurntSushi\toml (download)
github.com\PuerkitoBio\purell (download)
cd c:\Users\swortain\go\src\github.com\PuerkitoBio\purell; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details
    git pull <remote> <branch>
If you wish to set tracking information for this branch you can do so with:
    git branch --set-upstream-to=origin/<branch> master
package github.com/spf13/hugo
        imports bitbucket.org/pkg/inflect
        imports github.com/BurntSushi/toml
        imports github.com/PuerkitoBio/purell: exit status 1
github.com\armon\consul-api (download)
github.com\coreos\etcd (download)
github.com\coreos\go-etcd (download)
github.com\dchest\cssmin (download)
github.com\eknkc\amber (download)
github.com\gorilla\websocket (download)
github.com\kardianos\osext (download)
github.com\kr\pretty (download)
github.com\kr\text (download)
github.com\mitchellh\mapstructure (download)
github.com\russross\blackfriday (download)
github.com\shurcooL\sanitized_anchor_name (download)
github.com\spf13\afero (download)
github.com\spf13\cast (download)
github.com\spf13\jwalterweatherman (download)
github.com\spf13\cobra (download)
github.com\spf13\pflag (download)
github.com\spf13\fsync (download)
github.com\spf13\viper (download)
github.com\xordataexchange\crypt (download)
Fetching https://golang.org/x/crypto/cast5?go-get=1
Parsing meta tags from https://golang.org/x/crypto/cast5?go-get=1 (status code 2
00)
get "golang.org/x/crypto/cast5": found meta tag main.metaImport{Prefix:"golang.o
rg/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https
://golang.org/x/crypto/cast5?go-get=1
get "golang.org/x/crypto/cast5": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org\x\crypto (download)
Fetching https://golang.org/x/crypto/openpgp?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp?go-get=1 (status code
 200)
get "golang.org/x/crypto/openpgp": found meta tag main.metaImport{Prefix:"golang
.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at htt
ps://golang.org/x/crypto/openpgp?go-get=1
get "golang.org/x/crypto/openpgp": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
Fetching https://golang.org/x/crypto/openpgp/armor?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp/armor?go-get=1 (statu
s code 200)
get "golang.org/x/crypto/openpgp/armor": found meta tag main.metaImport{Prefix:"
golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"}
at https://golang.org/x/crypto/openpgp/armor?go-get=1
get "golang.org/x/crypto/openpgp/armor": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
Fetching https://golang.org/x/crypto/openpgp/errors?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp/errors?go-get=1 (stat
us code 200)
get "golang.org/x/crypto/openpgp/errors": found meta tag main.metaImport{Prefix:
"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"}
 at https://golang.org/x/crypto/openpgp/errors?go-get=1
get "golang.org/x/crypto/openpgp/errors": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
Fetching https://golang.org/x/crypto/openpgp/elgamal?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp/elgamal?go-get=1 (sta
tus code 200)
get "golang.org/x/crypto/openpgp/elgamal": found meta tag main.metaImport{Prefix
:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"
} at https://golang.org/x/crypto/openpgp/elgamal?go-get=1
get "golang.org/x/crypto/openpgp/elgamal": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
Fetching https://golang.org/x/crypto/openpgp/packet?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp/packet?go-get=1 (stat
us code 200)
get "golang.org/x/crypto/openpgp/packet": found meta tag main.metaImport{Prefix:
"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"}
 at https://golang.org/x/crypto/openpgp/packet?go-get=1
get "golang.org/x/crypto/openpgp/packet": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
Fetching https://golang.org/x/crypto/openpgp/s2k?go-get=1
Parsing meta tags from https://golang.org/x/crypto/openpgp/s2k?go-get=1 (status
code 200)
get "golang.org/x/crypto/openpgp/s2k": found meta tag main.metaImport{Prefix:"go
lang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at
 https://golang.org/x/crypto/openpgp/s2k?go-get=1
get "golang.org/x/crypto/openpgp/s2k": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag main.metaImport{Prefix:"gopkg.in/yaml.v2"
, VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go
-get=1
gopkg.in\yaml.v2 (download)
github.com\yosssi\ace (download)
github.com\spf13\nitro (download)
Fetching https://gopkg.in/fsnotify.v1?go-get=1
Parsing meta tags from https://gopkg.in/fsnotify.v1?go-get=1 (status code 200)
get "gopkg.in/fsnotify.v1": found meta tag main.metaImport{Prefix:"gopkg.in/fsno
tify.v1", VCS:"git", RepoRoot:"https://gopkg.in/fsnotify.v1"} at https://gopkg.i
n/fsnotify.v1?go-get=1
gopkg.in\fsnotify.v1 (download)

but it seemed that nothing happened...I still can't use command hugo in git bash..
what i'm supposed to do next?...
I'm the new guy of go&hugo...many thanks..

**Comment by spf13** [comment]
You are compiling hugo from scratch. It's a lot easier to just download the release and put it in your path. 

The command you ran installs hugo in $GOPATH/bin . You need to add that to your path.

**Comment by swortain** [comment]
thanks very much!
So all I need is download the .exe and copy it to the $GOPATH/bin?

**Comment by swortain** [comment]
Er,by the way, can you tell me the command tool you used in the video https://www.youtube.com/watch?v=w7Ft2ymGmfc?
thx!

**Comment by anthonyfok** [comment]
Hi @swortain,

If I am not mistaken, that is called "Git BASH" as explained on this https://msysgit.github.io/:

> Git for Windows provides a BASH emulation used to run Git from the command line. *NIX users should feel right at home, as the BASH emulation behaves just like the "git" command in LINUX and UNIX environments.

This is part of the Git for Windows suite, which you may download from http://git-scm.com/downloads or from https://msysgit.github.io/.  The latest installer as of today is named `Git-1.9.5-preview20141217.exe` with an MD5 checksum of b962aee34e84a749e4951237fb04ac39.

In the video, it appears that the command prompt was changed to a lambda (λ), but that doesn't really matter.  Perhaps Dan Hersam (@jaden) could elaborate?  :wink:

**Comment by swortain** [comment]
got it. thx!

**Comment by jaden** [comment]
@anthonyfok Is right on about git bash when I do the git clone. The shell with a lambda prompt is [cmder](http://bliker.github.io/cmder/).

**Comment by swortain** [comment]
thank you!
