### ISSUE TITLE
Hugo shows rss-feed as index.xml, but links to rss.xml

### ISSUE THREAD

**Issue by koebi** [spf13/hugo#971]
As far as I understood, Hugo actually puts the rss-feed at index.xml
Yet, all the links pointing to an rss-feed, as well as the pageinfo, shows rss.xml.

Am I doing something wrong, or am I right with filing an issues?

**Comment by k4rtik** [comment]
No, you are not. This should be a side effect of changes I did in https://github.com/spf13/hugo/commit/596d67938668126d49cde7b00dc9f345f0f5032e

Can you tell me which theme you are using?

**Comment by koebi** [comment]
Cool ;)
Currently, I am using a modified version of simple-a, found at http://github.com/koebi/simple-a.
Except for the rss.xml, which is now the hugo-default, I have only customized it to show my name and image, not the original author's one.

**Comment by k4rtik** [comment]
I think you will need to modify the link in `layouts/index.html` and `layouts/chrome/header.html` in the theme:
```
    <!-- atom & rss feed -->
    <link href="/rss.xml" type="application/atom+xml" rel="alternate" title="{{ .Site.Title }}">
```
 You may want to send a PR to the original theme as well. :smile:

**Comment by koebi** [comment]
Hey,
I changed it, and it worked :))
Thank you for your help!
