### ISSUE TITLE
Broken sitemap.xml template

### ISSUE THREAD

**Issue by bep** [spf13/hugo#972]
Pulled and built Hugo today, and now I get:

```
ERROR: 2015/03/13 Error while rendering sitemap: template: _internal/_default/sitemap.xml:11:14: executing "_internal/_default/sitemap.xml" at <.title>: can't evaluate field title in type string
```

**Comment by bep** [comment]
Suspect:

3c147bd41922c4f0ac81bc1e1f2ffab8093d5d1c

**Comment by spf13** [comment]
I bet that's it. I'll take a look.

**Comment by spf13** [comment]
It's a bug, because it expects params.Images to have a specific structure. We should make it more flexible. 

I didn't trigger it on my site since I don't use params.Images anyway.. and consequently I didn't notice it.

**Comment by bep** [comment]
Yes - I use params.images in combination with a internal template (opengraph.html and others) ... that expects it to be a list of strings. 

I will revert this if you don't. I can revert this locally, but others are also using the current master.

**Comment by spf13** [comment]
@bep.. Yeah, let's revert it. I see a couple other issues with it. We can put it back once it's cleaned up. My bad for merging it.
