### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by k4rtik** [spf13/hugo#973]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with hugo. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable hugo on @Sourcegraph by going to https://sourcegraph.com/github.com/spf13/hugo and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by k4rtik** [comment]
Okay, that was the default text.

**Comment by bep** [comment]
@spf13 would have to do this, but I agree: This is nice to have.

**Comment by spf13** [comment]
Done.

**Comment by k4rtik** [comment]
Awesome :+1: Thanks!
