### ISSUE TITLE
Arrange function names in templates/functions.md

### ISSUE THREAD

**Issue by quoha** [spf13/hugo#981]
It would be easier to find functions in the docs if they were sorted alphabetically.

**Comment by mdhender** [comment]
Is there anything else that needs to be done for this?

**Comment by mdhender** [comment]
Is there something missing or wrong?

**Comment by bep** [comment]
No, but I'm a little hesitant about how to merge this ... as we have a live (0.13) and a future version ...

**Comment by mdhender** [comment]
It's holding up some other changes I'd like to work on, so let me know if you need me to split it into different branches.
