### ISSUE TITLE
Generate a search.json index of all content

### ISSUE THREAD

**Issue by rhewitt22** [spf13/hugo#997]
Similar to RSS I want to be able to create a website index in JSON so I can do client-side search using something like lunrjs.  I'd like to avoid using Google due to either cost or ads.

Possibly related to #144, and [Generating JSON for consumption by JavaScript Framework](http://discuss.gohugo.io/t/generating-json-for-consumption-by-javascript-framework/195)

**Comment by bep** [comment]
This is handled by #144 - it will be natural to create this "like the RSS, but with a JSON schema"
