### ISSUE TITLE
Handle Ace-views when base-template is used

### ISSUE THREAD

**Issue by bep** [spf13/hugo#999]
See #994

This has one loop-hole: It doesn't support Ace templates with base template combined with an Ace view.

We need a way of knowing that the Ace views (`summary.ace` etc.) never has a base template.

As they are placed in the same folder as the template they are rendered from, I see two options:

1) Introduce some kind of naming convention, `summary_view.ace` or similar
2) Read the template and look for a `= content`. No content section means no base template needed.

@spf13 thoughts? I hate 1) 2) should do, and as the templates are cached and fairly small the performance hit should be negligible, and we only need to check Ace files.

**Comment by spf13** [comment]
I think you took the right approach here. Thanks!
